### ISSUE TITLE
【質問】注文約定照会のStateとOrderStateの違い

### ISSUE THREAD

**Issue by tsuchinaga** [kabucom/kabusapi#1]
https://kabucom.github.io/kabusapi/reference/index.html#tag/info%2Fpaths%2F~1orders%2Fget

注文約定照会の正常系レスポンスに、 `State` と `OrderState` とがありますが、定義値が一致してます。  
どのような違いがあるのでしょうか？

**Comment by yasuyuki-nakazawa** [comment]
ご質問に対して回答いたします
現状、株式の取り扱いだけですので、差はございません
株式の取引においては、stateを参照いただければ、注文約定の状態が確認できます

**Comment by tsuchinaga** [comment]
ご回答ありがとうございます！
