### ISSUE TITLE
【不具合】RESTで/boardを50件を超えてリクエストするとエラーになる。

### ISSUE THREAD

**Issue by johnnymny** [kabucom/kabusapi#10]
50件の制限がPUSH通信だけでなく、RESTのリクエストにも掛かっています。

**Comment by yasuyuki-nakazawa** [comment]
こちら、仕様となります。
銘柄に関する各種情報の取得においてはREST/PUSHによる情報のリクエストを含めて、50銘柄を上限としております。
RESTによる情報リクエスト等が行われると、kabuステーション上のAPI登録リストに追加されますが、当リストに登録されている銘柄の情報取得を現状上限としております。
当銘柄リストは、銘柄登録解除（unregister)を呼ぶことで登録解除を行うことができます。
その後、再度RESTによる情報取得を実施いただけますでしょうか。

当件については、リファレンス側にも説明として反映いたします。

**Comment by johnnymny** [comment]
承知いたしました。
ただ、kabuステーションにおける銘柄登録リストがシートあたり50銘柄*40シートで2000銘柄を同時に監視できます。こちらはリアルタイムに情報が更新されますよね？
負荷という意味で制限をかけているのであれば、銘柄登録リストより少なくする意味はないかと思いますのでAPI登録銘柄リストの銘柄数上限を上げて頂けるようお願い致します。
