### ISSUE TITLE
【要望】C#サンプルプログラム追加の件　→【対応中】

### ISSUE THREAD

**Issue by MitsuguKondo** [kabucom/kabusapi#100]
サンプルプログラムにC#を追加して頂きたいです。

**Comment by yasuyuki-nakazawa** [comment]
C#のユーザも多いと考えます。こちらはタイミングみて検討・追加させていただきます

**Comment by MitsuguKondo** [comment]
よろしくお願いします。

**Comment by cyber-minion** [comment]
C#のサンプルコードを提供しましたので、下記にてご確認いただければ幸いです
https://github.com/kabucom/kabusapi/issues/345#issuecomment-882171995

**Comment by MitsuguKondo** [comment]
ありがとうございました。
