### ISSUE TITLE
【要望】他証券間クロスのリスクにおけるガイドライン及び対策

### ISSUE THREAD

**Issue by kabu3995** [kabucom/kabusapi#101]
自動売買以外のトレードツールの成熟、PTS市場の有無から、残念ながら株コムは松井楽天には現時点には及ばず、GMO岡三にもまだ差があります。
デイトレードをする人にとってはKABUKOMだけで取引することは金銭的損失とほぼ同義であり、悩ましいところではあります。

何かのニュースで自動売買、何かのテクニカルで自動売買、こういった条件で自動売買すると、意図しないところで他証券の自分の売りを買ってしまうことになり、証券会社からの退場のリスクを内包してしまうことになります。
「株コムAPIを使用する場合は株コム以外の証券会社を使うと、あなたは2つの証券会社への参加資格を失う可能性があります。」

そのリスクがあることは事実です。
これについてのリスクマネジメントのガイドライン、もしくはこれは株コムさんにお願いなのですが、他証券口座間の同一名義のクロス注文を受け付けないように東証に働きかけていただきたいのです。
クロス注文はメリットは極小、処罰は極大という存在そのものが非常に厄介です。

**Comment by yasuyuki-nakazawa** [comment]
まず、PTSに関してですが、auカブコム証券ではSOR発注の仕組みを有しています。
株式のAPIに関しても、次回の更新にてSORへの対応は検討しております。

他証券間のクロス対策に関してです。
・業界を横断して個人を特定するためのIDが存在しない。
・マイナンバーは法的にも目的外利用ができない
以上のことから、個人各位からのクロス注文を制御することはできないのが現状です

**Comment by kabu3995** [comment]
SORではなくPTS市場と、無条件の3つ以上のワンクリック板発注がある、楽天と松井はプロ投資家にとって圧倒的です。
（とりあえずは実情として他の取引すべてをカブコムさんに移行しようにもできない人が多いという前提の上で）

東証さんは証券会社を跨いだクロスも認識できるようですので、後で文句を言うなら、東証が注文を受け付けないでほしいのです。
もちろんそういった要望は個人投資家として出していますが、証券会社の側も、特に自動売買を手掛け始めたカブコムさんからも東証に働きかけていただけると幸いです。

他社間場中クロスの99パーセントは事故にすぎず、そしてペナルティーがやたら重いですから。

**Comment by yasuyuki-nakazawa** [comment]
大変申し訳ございません
当件に関してはコミュニティ上のQA範疇ではないため、回答できません。
ご了承くださいませ
