### ISSUE TITLE
【要望】高速同時発注につきまして

### ISSUE THREAD

**Issue by kabu3995** [kabucom/kabusapi#102]
高速発注、並行発注のトピックを俯瞰して思いましたのは、現時点で実現可能性が一番高いのは複数PCから複数のKABUステーションにログインすることだと思いました。
これはSBIや楽天なら普通にできることです。
プレミアムプラン以上などの縛りで実装することにさほど不都合があるとも思えません。

ずっと高速で注文し続けないといけないという人は稀でしょうが、1時間の中のある0.1秒の中で2－3回したい人はものすごく多く利益に直結するケースが多そうです。

**Comment by sakatsusan** [comment]
御担当者殿、本件、要望マークがありませんが、要望としてハンドリングしていだけると幸いです。

**Comment by yasuyuki-nakazawa** [comment]
記載頂いているkabuステーションは複数端末においては起動しますが、ログインは１台からのみとなっております。
つまるところ、APIのサーバ的な役割を担えるカブステは１台となります。
特定のプラン以上に関しては流量制限を緩和するということは比較的現実的なところとも考えます。

**Comment by kabu3995** [comment]
楽天SBIはログインできるツールに制限がなく
岡三は2つまでです。
ここは他所がそうなので株コムさんも変更が不可能ではないのかなと。

**Comment by yasuyuki-nakazawa** [comment]
情報配信負荷の観点でカブステーションの重複起動を制限しています。
一定のプラン以上に関しては、流量制限を緩和する、扱い銘柄数を増やすということに関しては、目下検討を進めております。
システムの負荷状況を鑑みた上で、当該閾値に関しての見直しと、上位プランの方への利用拡大は検討します。

**Comment by yasuyuki-nakazawa** [comment]
kabuｽﾃｰｼｮﾝの仕組みとしては最終的にログインしてきたクライアントに対して注文約定の通知処理を行っています。当然のことながら、WEBやスマホアプリとkabuｽﾃｰｼｮﾝの併用は可能です。
しかしながら、kabuｽﾃｰｼｮﾝ単体のツールとして、重複ログインを許容しておりません。
そのため、高速の発注としては、秒間の発注流量制限を緩和する方向で対応させていただきます。

**Comment by kabu3995** [comment]
情報取得、同時発注については、1時間に3600回、ひいては1時間に36000回やりたいという話ではないのです。
総計は1時間に100回でいいから、0.001秒の間に同時に5回やりたいし、やらないと成立しない取引が無数にあり、そういうリクエストですし、同じ五百井の人は多いと思います。
1秒間の制限ぎりぎりで使い続ける人を前提に1秒の制限を設けるのではなく、10分、1時間の制限で同時発注規制は考えられませんでしょうか。

制限が減るのはありがたい話ですが、1時間ごとの制限はきっちりあっても少なくとも私は困りませんし、有料対応すればとも思います。

他証券会社はツールそのものが無限起動ですが、カブコムは、「API 発注ツール」
という、APIの機能だけがあるカブステーションの複数ログインを許してくだされば、懸念されてる情報の過負荷は発生しないものと思慮する次第です。
もしくは、一つのKABUSUTATIONからマルチ同時発注ができれば。
そして同時発注規制は、もう少し長い時間に対しての回数で考慮願えませんでしょうか。

マルチでできなくても、1注文が0.001秒以下で処理できれば順次処理でも幸いです。

**Comment by kabu3995** [comment]
【質問】sendorderコマンド発効後レスポンスを受け取るまでの貴社側の処理について #86

を拝見して、余力計算などの問題を除けば、秒間規制の緩和、撤廃で理論上の最速にはなるという理解でいいのでしょうか。
その場合もやはり同じく、自分は1時間あたりの発注回数が少ないので、規制ゼロで時々、5－10注文を最速でしたく、それができないとそもそもスキームが成立しない問題があります。

1時間、分などに規制を設けていただき、それに抵触しない場合、規制なしの同時発注が時々できれば助かります。

**Comment by yasuyuki-nakazawa** [comment]
記載いただいた状況に関しては理解いたしました。
kabuｽﾃｰｼｮﾝAPIとスクリプト部分に関しては特段制限を設けておりませんので、複数スレッドもしくは、複数のプロセスでkabuｽﾃｰｼｮﾝAPIとコミュニケーションをとることは可能です（同一Tokenの持ち回りは必要ですが）

> 余力計算などの問題を除けば、秒間規制の緩和、撤廃で理論上の最速にはなるという理解でいいのでしょうか

余力の再計算がなければ高速発注は理論上は可能ではあります。
しかしながら、発注処理においては同期処理をとっておりますので、
以下①～⑤、⑤～①の完了でスクリプトにレスポンスが返ります。
※場中です。場外の場合は①～④でレスポンスされます
①スクリプト→②kabuｽﾃｰｼｮﾝAPI→③kabuｽﾃｰｼｮﾝ→④カブコム取引システム→⑤取引所
そのため、現実的にに0.001Secでの発注は不可能と思慮いたします。
加えて、ポジション管理の観点でも、ポジションの先入れ先出しの制御・管理、建玉の落ち指定の管理等があるため、
順次処理は避けられません。

一方で、短時間における高速複数注文の要望に関しては理解いたしております。
注文システム全体にかかわる内容となるため、対応方法、方針に関しては慎重に検討を行っていきます。
秒間の発注制限（現状５件）に関しての拡大についても並行して検討しております。

**Comment by 4494ku** [comment]
秒間の発注制限（現状５件）の規制は現在も変わっておりませんか？
ということは場中1分間に最高３００件の注文が可能ということでしょうか？
また規制に抵触した場合は発注が通らない以外罰則？はあるのでしょうか？

**Comment by yasuyuki-nakazawa** [comment]
5件の規制に関しては、現状変更はありません。
流量制限に関しては、システム負荷の高騰を防止するために、カブステーション側で発注をリジェクトしておりますので、発注が通らないという制限以外は現状は特段制約はありません。
しかしながら、流量制限内におきましても、システムに過度な負荷があるような発注を連続で実施される場合は、状況によりAPIのご利用を停止する場合がございます。

**Comment by yasuyuki-nakazawa** [comment]
こちらはクローズさせていただきます
