### ISSUE TITLE
【質問】Pythonのwebsocket

### ISSUE THREAD

**Issue by BlackTiger4649** [kabucom/kabusapi#103]
Pythonでsampleのファイルを見ながら試してみましたが、websocketをいかに使うかで躓いてしまいました。現状で出来ていることは、トークンを取得して銘柄を登録する処理は出来ました。そして、pip install websocket-clientをインストールした後に、kabusapi_websocket.pyを動かすと、--- CONNECTED ---の表示が出てきたので、うまく接続できたと思っています。この後、登録した銘柄について、現在価格などの情報を取得したいのですが、如何なるコードを書けばいいのか分かりません。どのようなコードを書けばいいか、サンプルコードを例示して頂ければ幸いです。宜しくお願いします。

**Comment by shirasublue** [comment]
websocketはリアルタイムな情報で、休日には配信されません。サンプルコードのままで表示されます。

**Comment by yasuyuki-nakazawa** [comment]
基本的にはPushで情報をリアルタイムに受け取るコードを作成するフローでは、REST APIを呼び出し、直近の値を取得した上で、Pushによるリアルタイム情報更新を行うことがおおいです。ご参考までに。

**Comment by BlackTiger4649** [comment]
コメントありがとうございます。kabusapi_websocket.pyをザラバに動かすと、情報が更新される度に
https://gyazo.com/af26cc3bd0742d6b372b129870482a1b
が出力されました。個別の情報を取り出そうと、message['CurrentPrice']のように試してみましたが、そのような機能はないようですね。
そこでWebで検索していたら、shirasublueさんの
https://qiita.com/shirasublue/items/222c2bc7dbf284d24878
にたどり着きました。配信表示のところを実際に試してみると（最初にRuntimeError: This event loop is already runningが表示されるものの）
https://gyazo.com/ca5c1a55c91f69d9b776097fb4b68a26
のように情報がフィードされました。websocketを初めて使うのでよく分かりませんが、こんな感じで情報を取得するのでしょうか？

**Comment by shirasublue** [comment]
記事閲覧ありがとうございます。公式さんのサンプルコードの場合、文字列フォーマットままでの取得になるかと思いますので 、`json.dumps()` を行うと辞書形式への変換と `message['CurrentPrice']` のような形で情報を取得できるかと思います。

私のコードを貴環境で実行した際ののランタイムエラーは環境固有のもののようです。
参考: https://qiita.com/sin_tanaka/items/56eb1b8a677fb9b50f7b

**Comment by BlackTiger4649** [comment]
shirasublueさん、丁寧にコメント頂きまして本当にありがとうございました。Pythonを学び初めて１年足らずで素人の域を超えてませんが、コツコツと勉強していきたいと思います。
公式サンプルでは、messageが文字列形式の出力であるので、これを辞書形式に変換すれば宜しいのですね。dumpsとloadsの差もよく理解していませんが、明日にでもトライしてみようと思います。
shirasublueさんの記事、エラーの表示はこちらの開発環境がJupyter notebookのせいで起こる訳ですね。tornadoのバージョン6.0.4なので、5以下に落としてみたのですが、jupyter notebookが正常に使えない（ディレクトリーが表示されなくなる）ので、元のバージョンに戻しました。エラー表示は出るものの、リアルタイムにフィールドされているので、このままで進もうかと思います。

**Comment by yasuyuki-nakazawa** [comment]
@shirasublue ご助言ありがとうございます！
@BlackTiger4649 質問事項として、解決しているようでしたら、スレッドをクローズください。よろしくお願いいたします。

**Comment by BlackTiger4649** [comment]
公式サンプルで、messageをjson.loads(message)すると辞書型として個別の要素を取り出せました。どうもありがとうございました。
