### ISSUE TITLE
【質問】api(python)を使用した発注での「預り区分」エラーについて

### ISSUE THREAD

**Issue by lstm500** [kabucom/kabusapi#104]
api(python)から現物の発注を行おうとしたところ、以下のエラーが出ました。

>HTTP Error 500: Internal Server Error
{'Code': 100031, 'Message': '「預り区分」をご確認ください'}

エラーにある「預り区分」をリファレンス内で探しても該当する項目がありませんでした。
（https://kabucom.github.io/kabusapi/reference/index.html）
「預り区分」はどう定義すればよいのでしょうか？

ソースは公開されていた kabusapi_sendorder.pyを流用したものを使っており、以下になります。

import urllib.request
import json
import pprint

obj = { 'Password': '******',
        'Symbol': '1570',
        'Exchange': 1,
        'SecurityType': 1,
        'Side': '2',
        'TimeInForce': 0,
        'CashMargin': 1,
        'MarginTradeType': None,
        'DelivType': 2,
        'FundType': '02',
        'AccountType': 4,
        'Qty': 1,
        'ClosePositionOrder': 1,
        'ClosePositions': None,
        'Price': 20000,
        'ExpireDay': 0,
        'FrontOrderType': 20 }
json_data = json.dumps(obj).encode('utf-8')

url = 'http://localhost:18080/kabusapi/sendorder'
req = urllib.request.Request(url, json_data, method='POST')
req.add_header('Content-Type', 'application/json')
req.add_header('X-API-KEY', ' ******** ')

try:
    with urllib.request.urlopen(req) as res:
        print(res.status, res.reason)
        for header in res.getheaders():
            print(header)
        print()
        content = json.loads(res.read())
        pprint.pprint(content)
except urllib.error.HTTPError as e:
    print(e)
    content = json.loads(e.read())
    pprint.pprint(content)
except Exception as e:
    print(e)

**Comment by cyber-minion** [comment]
リファレンスの記載漏れで、申し訳ありません。「預かり区分」とは、リファレンスの「資産区分」(FundType)になりますので、再度ご確認願います。また、リファレンスを更新させていただきます。
