### ISSUE TITLE
【質問】Websocket配信データ

### ISSUE THREAD

**Issue by nobuodesu** [kabucom/kabusapi#106]
複数銘柄が登録されている場合、配信されるデータの銘柄の違いはどのように分類されるでしょうか。たとえば、配信されたデータは株aと株bの株価はどのように分類されるのでしょうか。
板情報は会社名を含め並列で階層化されていない理解なのでどのように条件づけして取得すべきかというのが質問の背景です。

**Comment by shirasublue** [comment]
配信データ内に銘柄コードや銘柄名も入っていますよ。

参考: [時価PUSH配信について](https://kabucom.github.io/kabusapi/ptal/push.html)

**Comment by nobuodesu** [comment]
ありがとうございます。
初歩的な質問で恐縮です。
階層化されていないと思うので、どのように株価を分類したら良いかというのが質問の趣旨です。
Kddiとmufgの株価、CurrentPriceをどう分類するかです。

**Comment by shirasublue** [comment]
逐次配信されるデータが先程の[時価PUSH配信について](https://kabucom.github.io/kabusapi/ptal/push.html)となります。

Python3であれば、次の記事の配信表示コードで以下のような応答が得られます。
[kabuステーション®APIのWebsocketをPythonで受ける](https://qiita.com/shirasublue/items/222c2bc7dbf284d24878)

```python
$ python recieve_sample.py 
8306 三菱ＵＦＪフィナンシャル・グループ 428.8
8306 三菱ＵＦＪフィナンシャル・グループ 428.8
9433 ＫＤＤＩ 2732.0
9433 ＫＤＤＩ 2731.0
9433 ＫＤＤＩ 2731.0
9433 ＫＤＤＩ 2731.0
8306 三菱ＵＦＪフィナンシャル・グループ 428.8
9433 ＫＤＤＩ 2731.0
8306 三菱ＵＦＪフィナンシャル・グループ 428.8
9433 ＫＤＤＩ 2731.0

```

**Comment by nobuodesu** [comment]
ご理解の通り、階層化されていないの意図は銘柄ごとに階層化されず、並列にmessageが受信されるという意味です。

**Comment by nobuodesu** [comment]
ありがとうございます。
jsonによるデータの取得が出来ました。

**Comment by masaki64** [comment]
こちら、私も同様の質問をしたいなと思っておりましたが、その後、ご状況いかがでしょうか。nobuodesu様の方で原因究明/解決に至った形でしょうか。
（こちらに質問してしまい、すみません。。）

**Comment by nobuodesu** [comment]
こちらは特定には至ってないのですが、VPSのメモリを上げること、カブステのapi設定タブの上限を高めることの二つをしたところ発生しなくなりました。
後者関連では上限以上の発注をして、発注エラーを起こしていたのかなと思います。

**Comment by shirasublue** [comment]
1. 1チャンネルでしか受けられません。（2つ目の受信用プログラムを起動するとそちらに接続が移行します。）
2. 登録銘柄は50までで、それ以上登録できません。
3. 受信データをすべて保存すると膨大なデータになります。（自分の場合は30銘柄程度を1日分保存すると5GB程度になります。）安価なコンピュータやVPSの下のプランでは容量がすぐ足りなくなってしまうでしょう。

**Comment by yasuyuki-nakazawa** [comment]
当件は別スレッドでも展開されていることもあり、集約Closeいたします
参考
https://github.com/kabucom/kabusapi/issues/196
