### ISSUE TITLE
【質問】エクセルのワークシート上では関数が動作しますが、VBA内では”functionが定義されていない”となります。VBAでAPI関数を動作させる方法を教えてください。

### ISSUE THREAD

**Issue by es2924** [kabucom/kabusapi#107]

**Comment by yasuyuki-nakazawa** [comment]
配布しているサンプルのExcelMacroにてAPI関数を呼び出すコードが記載されておりますので、ご確認ください。
Functionが設定されていないとのことですが、実際にエラーのコード等を開示いただくと、もう少しコメントできると思います。

**Comment by es2924** [comment]
エラー35となっています。試しに下記のようなVBAプロジェクトを実行しました。
Sub test()

    Cells(10, 2) = BOARD(B2, C2)

End Sub

**Comment by yasuyuki-nakazawa** [comment]
API関数はexcelの関数ではなく、REST 形式でのリクエストでないと呼べません
マクロ内のbord関数を取り扱ってる部分が参考になると思います

**Comment by es2924** [comment]
ありがとうございました。
