### ISSUE TITLE
【質問】成り行き注文の価格指定について

### ISSUE THREAD

**Issue by ukyori** [kabucom/kabusapi#108]
素晴らしいツールをありがとうございます。

EXCELのORDERツールにて
成り行き注文をしようとすると、注文価格を入力してください
というエラーになってしまいます。

価格を入力してもうまくいかず、どのように対処したらよろしいでしょうか？

**Comment by yasuyuki-nakazawa** [comment]
発注時のパラメータが不正と考えます。
FrontOrderTypeで１０(成行）を指定のうえ、注文価格には0が設定されているかを確認ください。
こちらでも同エラーが発生している場合は、パラメータを記載いただけると幸甚です。

**Comment by ukyori** [comment]
今一度みなおしたところ、正常に注文ができました。大変失礼いたしました。ありがとうございました。
