### ISSUE TITLE
【質問】kabuSログファイルはどこに出力されますか？

### ISSUE THREAD

**Issue by tsuchinaga** [kabucom/kabusapi#11]
「詳細はkabuSログファイルを確認してください」というエラーがありますが、kabuSログファイルはどこに出力されますか？

**Comment by yasuyuki-nakazawa** [comment]
kabuステーションのログは下記のパスに格納されております。
%appdata%\KabuS\Log

**Comment by tsuchinaga** [comment]
ありがとうございます！
