### ISSUE TITLE
【質問】時価情報・板情報の各パラメータの詳細情報

### ISSUE THREAD

**Issue by akira-yamamoto-f** [kabucom/kabusapi#112]
PUSH（WebSocket）で取れる各情報の内容はどこを見ればわかるでしょうか？

下記、REST、PUSHのリファレンスを見ても記載がありません。
https://kabucom.github.io/kabusapi/reference/index.html#
https://kabucom.github.io/kabusapi/ptal/push.html

例えば、「最良売気配フラグ」で"0101"などが何を指しているのかわかりません。
"BidSign": "0101"

**Comment by yasuyuki-nakazawa** [comment]
RESTの「時価情報・板情報」をご確認ください。
こちらのレスポンス情報に記載がございます。

**Comment by akira-yamamoto-f** [comment]
申し訳ありません。
レスポンス 200 OK が折りたたまれていることがわかっていませんでした。
このクローズいたします。
