### ISSUE TITLE
【要望】API登録銘柄リストの維持　→【仕様：未対応】

### ISSUE THREAD

**Issue by akira-yamamoto-f** [kabucom/kabusapi#113]
API登録銘柄リストですが、kabuステーションを再起動するとリストが初期化され登録がなくなってしまいます。
再起動しても維持されるように登録銘柄を保存してもらえないでしょうか？

**Comment by yasuyuki-nakazawa** [comment]
申し訳ございませんが、こちらは仕様となります。
API登録銘柄リストはAPI経由でリクエストされている銘柄の確認を意図としております。
APIにてRegistされている状態確認用です。APIとクライアント操作の完全分離のため、一部要求をクライアントに依存することを是としないためです。
この点はご理解いただけると幸甚です
なお、当件とは関連しないのですが、今後、RESTリクエストとPUSHリクエストを区別できるような仕様改善は検討中です
