### ISSUE TITLE
【要望】登録銘柄の取得API追加

### ISSUE THREAD

**Issue by akira-yamamoto-f** [kabucom/kabusapi#114]
REST APIには、登録銘柄関係で下記３つがあります。

・銘柄登録（/register）
・銘柄登録解除（/unregister）
・銘柄登録全解除（/unregister/all）

登録済みの銘柄一覧を取得できないため、APIの追加を要望いたします。

**Comment by yasuyuki-nakazawa** [comment]
銘柄登録を実施した際に登録銘柄の一覧が取得できるかと思われます。
登録銘柄数の取得に関しては要望として検討いたします

**Comment by akira-yamamoto-f** [comment]
想定の動作と違うかもしれませんが、下記方法で登録済みの一覧が取得できましたので
Tipsとして記載しておきます。

銘柄登録（/register）に空のリストでリクエストする。
