### ISSUE TITLE
【要望】銘柄情報の取得制限の排除

### ISSUE THREAD

**Issue by akira-yamamoto-f** [kabucom/kabusapi#115]
銘柄情報取得のREST（/symbol/{symbol}@{exchange}）について要望です。
現在、API登録銘柄リストに登録された上限５０件からしか情報が取得できない制限があるように見えます。

登録した５０件以外からも情報を取得できるよう、制限を解除してもらうことは可能でしょうか。
ご検討よろしくおねがいします。

**Comment by yasuyuki-nakazawa** [comment]
取扱い銘柄数の拡大要望は多々頂いております。
システムの情報配信負荷を勘案し、順次の拡大を検討しております。

**Comment by akira-yamamoto-f** [comment]
すいません、うまく伝わっていないように思いましたので再度記載いたします。

API登録銘柄リストに50件登録した状態から、/symbol をコールすると
　4002006 | レジスト数エラー
が返ってきます。

登録銘柄リストに登録した銘柄しか、/symbol から情報を取得することができない仕様でしょうか。

**Comment by yasuyuki-nakazawa** [comment]
登録された銘柄のみ情報取得可能となります
unregistすることで、銘柄登録を解除できますので、その後、再度別銘柄の登録が可能です

**Comment by akira-yamamoto-f** [comment]
ご回答ありがとうございます。仕様ということですね。
