### ISSUE TITLE
【質問】kabusapi_board.py

### ISSUE THREAD

**Issue by BlackTiger4649** [kabucom/kabusapi#116]
この関数で一連の価格情報等を取得できますが、取得するスピードが遅くて困っています。登録していない銘柄ですと最大５秒ほどかかることがあります。これを早くするには、どのような工夫を取り入れれば宜しいでしょうか？

**Comment by yasuyuki-nakazawa** [comment]
カブステ自体で注約照会を起動している状況でお試しいただけますか？

**Comment by BlackTiger4649** [comment]
注文約定詳解が起動している状況でもスピードに変化はありません。

**Comment by yasuyuki-nakazawa** [comment]
価格情報の取得レイテンシの改善は調査並びに対応検討実施中です。
しばらくお待ちくださいませ

**Comment by yasuyuki-nakazawa** [comment]
当件ですが、一度Registした銘柄であれば、高速に情報を取得できるように改善を実施いたします
1月に改善予定となっておりますので、連携させていただきます

**Comment by yasuyuki-nakazawa** [comment]
お知らせにて、改善計画を開示させていただいています
https://github.com/kabucom/kabusapi/issues/203

当該質問に関しては、いったんクローズさせていただき、ご要望は上記の改善計画内にて実施させていただきます
