### ISSUE TITLE
【質問】Websocketのmessage

### ISSUE THREAD

**Issue by nobuodesu** [kabucom/kabusapi#117]
WSのmessage fileは受信するたびに更新されるのでしょうか。日立の次にkddiを受信するとkddiのみのデータになるのでしょうか。

**Comment by yasuyuki-nakazawa** [comment]
Pushの配信データは差分の送信となります。
記載の例ですと、日立の次のKDDIのみのデータになります。

**Comment by nobuodesu** [comment]
理解しました。ありがとうございます。
