### ISSUE TITLE
【質問】注文約定照会の約定数量の反映について

### ISSUE THREAD

**Issue by uedatakeshi** [kabucom/kabusapi#118]
買いの注文を入れて直後に注文約定照会を行ったところ、以下のようなデータ（部分）が帰ってきました。
ステータスは 5 で 「終了（発注エラー・取消済・全約定・失効・期限切れ」　ですが、約定数量がゼロです。
約定数量が反映されるタイミングが微妙に遅れることがあるのでしょうか？？
約定数量が反映されたかどうかのステータス確認方法を教えてください。

```
"State":5,"OrderState":5,"OrdType":6,"RecvTime":"2020-10-06T12:49:42.6142587+09:00","Symbol":"1447","SymbolName":"ＩＴｂｏｏｋホールディングス","Exchange":1,"ExchangeName":"東証ﾏｻﾞｰｽﾞ","Price":769.0,"OrderQty":100.0,"CumQty":0.0,"Side":"2",
```

**Comment by yasuyuki-nakazawa** [comment]
タイムラグはない認識です
当該注文は約定してないのではないですか？
cumqtyが約定数量となりますので、こちらを参照するか、各明細でのRectypeが8のレコードで判断すれば良いと思われます

**Comment by uedatakeshi** [comment]
失礼しました。
注文が失効になっていました。Rectypeも確認しました。ありがとうございます。
IOC指値で買いを入れているのですが失効するのはどういう条件になるのでしょう？

**Comment by yasuyuki-nakazawa** [comment]
IOCだからかと思われます。
注文の特性上、板には乗りませんので、対等する注文がない場合はキャンセルされるためです。
