### ISSUE TITLE
【質問】エクセルVBAモジュール内で時価PUSH配信を利用する方法

### ISSUE THREAD

**Issue by kabucomapi** [kabucom/kabusapi#119]
お世話になります。

エクセルのVBAモジュール内で時価PUSH配信の値を利用する方法は、シート関数として用意されたWEBSOCKETでセル上に値を一旦表示させて、そのセルの値を参照するしかないのでしょうか。

VBAのモジュール内でWorksheetFunctionにより.WEBSOCKET関数を利用しようとすると、「オブジェクトは、このプロパティまたはメソッドをサポートしていません。」とエラーがでます。
WEBSOCKET関数のコードは参照することができないので、参考にするものがなく手が出せない状況です。

エラーが出るテストコード
Sub test()
　a = WorksheetFunction.WEBSOCKET(7203, 1, "現値")
End Sub

VBAのモジュール内で直接時価PUSH配信の値を取得する方法を教えていただけると助かります。
よろしくお願いいたします。

**Comment by kabucomapi** [comment]
全く回答いただけませんが、確認いただいていますでしょうか？

**Comment by yasuyuki-nakazawa** [comment]
エクセルのアドインはXLLであるため、下記の記載で取得可能かと思われます。
お試しください
Application.Run("WebSocket", 9984, 1, "現値")

**Comment by kabucomapi** [comment]
お世話になります。
期待していた動作を確認しました。
回答ありがとうございます。
大変助かりました。
