### ISSUE TITLE
【質問】kabuSTATION_API_function_sample時価総額について

### ISSUE THREAD

**Issue by MitsuguKondo** [kabucom/kabusapi#120]
kabuSTATION_API_function_sampleにつきまして質問があります

カブコムな設定を完了してサンプルマクロの時価総額タブでモニターをしたいのですが
関数設定すると1回だけ表示されるのですがざら場で変わりません

何か設定とかする必要があるのでしょうか

お忙しい所申し訳ありませんがアドバイス頂けるとありがたいです

よろしくお願いします

**Comment by hishiharahaz** [comment]
MitsuguKondoさん
私がリアルタイムで表示をさせたい場合は、PUSH配信のkabuSTATION_API_PUSH_sample.xlsxを使用しています。
ザラバの時間帯に実行して頂ければと思います。

参考
https://kabucom.github.io/kabusapi/ptal/push.html

**Comment by MitsuguKondo** [comment]
ありがとうございます。
具体的にエクセルに取り込むやり方が分かりません。アドバイス頂けると嬉しいです。
よろしくお願いします。

**Comment by hishiharahaz** [comment]
MitsuguKondoさん
私がPUSH配信をしているときの手順は以下になります。
参考として頂ければ幸いです。
【手順】
１．下記サイトから「kabuSTATION_API_PUSH_sample.xlsx」をダウンロードする。
https://github.com/kabucom/kabusapi/releases/tag/ExcelMacro-v1.2.0

２．registerメソッドにて、PUSH配信したい銘柄を登録する。
https://kabucom.github.io/kabusapi/reference/index.html#tag/register%2Fpaths%2F~1register%2Fput
kabuステーションのAPI登録銘柄リストで、銘柄が登録されているか確認することができます。

３．kabuSTATION_API_PUSH_sample.xlsxの「使い方」シートを参考にPUSH配信したい銘柄を指定する。
PUSH配信を行うには、Excelアドインの更新制御をONにする必要があるようです。
https://kabucom.github.io/kabusapi/ptal/add-in.html#step2

**Comment by MitsuguKondo** [comment]
ありがとうございます。
早速明日試してみます！

**Comment by MitsuguKondo** [comment]
その後
岡三RSSアドインとの相性が悪いのかなと思える事がありました。
岡三RSSアドインを選択から外して実行→更新されない
岡三RSSアドインソフトをアンインストール→更新されるようになりました

ありがとうございました。
