### ISSUE TITLE
【質問】エクセルマクロ動作中はWEBSOCKET関数の値が更新されない

### ISSUE THREAD

**Issue by kabucomapi** [kabucom/kabusapi#121]
お世話になります。
シート関数であるWEBSOCKET関数を用いて、シート上にpush配信される値を出力させ、その値をVBAモジュール内で取得しようとしましたが、マクロ動作中はシートの値が更新されません。更新のための待ち処理を行っていますが、更新ができません。マクロ処理停止後に更新が始まります。
別の質問にも書きましたが、この現象のためpush配信される値をVBAに取り込むことができなくて困っています。
エクセルでは、push配信されるデータは、視覚的にながめるだけで、VBAによる処理はできないのでしょうか？

**Comment by yasuyuki-nakazawa** [comment]
VBAがシングルスレッドであるためと考えます。
関数内でRaiseEvent等で処理をPush側に一時的に渡す等がジャストアイデアではあります

**Comment by kabucomapi** [comment]
お世話になります。
他社のRSSではDoEvents関数を使用して、制御を一時的にオペレーティングシステムに制御を移すことにより、シートの値が更新されますが、御社の関数は更新されません。
RaiseEvent等で処理をPush側に一時的に渡す等 と回答いただいておりますが、VBAの処理を中断して、制御をエクセルのシート関数の処理に限定して渡すことが出来るのでしょうか？具体的な回答をいただけると助かります。

別で質問していますが、VBAのモジュール内でイベント処理をしようにも、pushされる値をモジュール内の変数に取り込めないので、シート関数WEBSOCKET側で処理させるしかないです。このことから、VBAの処理のみ一時停止して、エクセルのシート関数WEBSOCKETの処理のみ限定的に実行させる処理が、VBAで実現可能である必要があると考えています。ですが、繰り返しになりますが、具体的な方法がわからないので、提示いたると助かります。
よろしくお願いいたします。

**Comment by kabucomapi** [comment]
回答いただけませんが確認していただいていますでしょうか。

**Comment by yasuyuki-nakazawa** [comment]
PUSH情報をマクロ側で取得する方法に関して確認中です

**Comment by kabucomapi** [comment]
お手数をおかけしますが、よろしくお願いします。

**Comment by yasuyuki-nakazawa** [comment]
別スレッドのほうに方法は記載させて頂きましたが、（https://github.com/kabucom/kabusapi/issues/119）
質問に記載されている
「pushされる値をモジュール内の変数に取り込めないので、シート関数WEBSOCKET側で処理させるしかない」
という点に関しては、「Pushされる値をモジュール内の変数には取り込めます。」

上記対応により、DoEventsを使用することなく、対応が可能かと思われますので、お試しください

**Comment by kabucomapi** [comment]
お世話になります。
回答ありがとうございました。
もう一方の質問にも、書きましたが大変助かりました。
株ステーションAPIがとても使いやすく気に入っております。
