### ISSUE TITLE
【質問】時価情報・板情報の処理速度について

### ISSUE THREAD

**Issue by kichikun-w** [kabucom/kabusapi#122]
時価情報・板情報のサンプルコードにトークン取得を加え、while True:のみ追加して実行してみたところ、おおよそ１秒１回程度しか取得できないことがわかりました。
情報系は１０回／秒まで許可されているので、限界まで利用したいのですが、
何かkabuStationの設定等、利用方法に何らかの問題があるのでしょうか？
[kabusapi_board_test.py.txt](https://github.com/kabucom/kabusapi/files/5360632/kabusapi_board_test.py.txt)

**Comment by sakatsusan** [comment]
#87
に記載しました（２）の影響じゃないでしょうかね・・・。

**Comment by kichikun-w** [comment]
すみません。明記が漏れていましたが、添付のテキストファイルの通り、使用しているサンプルコードはエクセルアドインではなく、pythonです。
なので、エクセルアドインのサンプルコード不具合とは無関係だと思います。

**Comment by kichikun-w** [comment]
追加情報です。
処理時間は銘柄によって大きく異なるようです。
また「１秒１回程度」と言うのは大袈裟で、遅い銘柄で平均0.61秒／回でした。
（添付txtファイル参照。1行目は証券コード、2行目以下は証券コードの時価情報・板情報をRestAPIで取得した時の応答時間です。）

よくわからないのは、平均応答時間の大小関係は
101(0.61秒)>1579(0.40秒)>1570(0.02秒)となっており、
アクセス(取引量) が多い銘柄ほど遅い・・・と言う訳でも無いようです。
なぜ銘柄によってこんなにも応答時間が異なるのでしょうか？

[timelog.txt](https://github.com/kabucom/kabusapi/files/5368597/timelog.txt)

**Comment by yasuyuki-nakazawa** [comment]
WebSocketを利用することで、レイテンシ少なく情報の取得が可能です。
API登録銘柄リストを起動した状態でも上述のレイテンシでしょうか。当該APIの特性上、起動端末のパフォーマンス状況に影響受けする部分も多くあります。
低レイテンシを求める処理であれば、WebSocketによるPush情報配信を推奨します。

**Comment by kichikun-w** [comment]
API登録銘柄リストを「起動した状態」とは「表示した状態」で良いのならば、試してみましたが、同じような結果になっています。
time.time()の処理前後の差分をログ出力しているのですが、なぜか0.0が出ているのもよくわかりませんが・・・。
ちなみに昨日の結果は寄り付き直前の時間帯です。
昨日と違い、1570も遅くなっています。
明日、ザラ場に実験してみます。

[_log_1014_list_off.txt](https://github.com/kabucom/kabusapi/files/5378507/_log_1014_list_off.txt)
[_log_1014_list_on.txt](https://github.com/kabucom/kabusapi/files/5378508/_log_1014_list_on.txt)

**Comment by kichikun-w** [comment]
実験してみました。
変わらないようです。

[_log_1015_off.txt](https://github.com/kabucom/kabusapi/files/5381730/_log_1015_off.txt)
[_log_1015_on.txt](https://github.com/kabucom/kabusapi/files/5381731/_log_1015_on.txt)

**Comment by Pusm** [comment]
同じ現象で困っております。
単純にsampleにありますboard.pyファイルを同じシンボルで連続実行すると、ちょうど0.5-7秒程度の間隔ごとに実行されます。
仕様であれば諦めますが、仕様であったとしてもちょっとあまりに遅いのでは、とは思います。
4000銘柄を監視しに行くのに、3時間もかかってしまい、手作業とたいして変わらないです。
負荷を下げる目的であれば0.1秒程度のsleep時間でも良いのではないでしょうか。

**Comment by yasuyuki-nakazawa** [comment]
目下調査しております。当スレッドにて情報アップデートさせて頂きます

**Comment by Pusm** [comment]
その後も検証しておりますが、やはり概ねどの銘柄でも0.5-1秒ほど板情報の取得に時間がかかります。
単一の銘柄に連続アクセスする場合でも、複数の銘柄にランダムにアクセスする場合でも変わりません。また、銘柄登録の有無でも変わりませんでした。
なんとなくスリープ時間をランダムに入れるコードが挿入されているような気がしますが。

また、一つのアイデアですが、現状例えば高値だけを知りたい時でも、板情報全体をダウンロードしないといけないことが時間がかかっている原因なのだとしたら、個別にアクセスできるようにしてはいかがでしょうか。
もしくは、推測ですが、板情報の取得に特に時間がかかる可能性があるとすれば、それだけ分離してしまうとか。（板情報を使用している人はあまりおらず、ほとんどの方は今の価格や前日終値などを知りたいという程度かと思います。まして、高頻度取引などをするわけではありませんので、板情報は不要かと。）

**Comment by kichikun-w** [comment]
yasuyuki-nakazawa様
「低レイテンシを求める処理であれば、WebSocketによるPush情報配信を推奨します。」
との事ですが、
「これが価格情報のみに発生する事であればWebsoketを利用することで解決する」
と記載している通り、特定銘柄価格情報の連続取得であればWebSocketで解決することはもとより承知しています。
問題は「他のコマンドの応答時間に同様の遅延が発生するか否か」です。
以下の情報を既に持っているのであれば教えてください。
・各コマンドの標準応答時間（どれぐらいの応答時間で返るのが正常動作ですか？）
・各コマンドの現状応答時間（現状、想定外に遅延しているコマンドはどれで、それはどの程度ですか？）
前者だけでも教えておいていただけると、それを前提にして設計できるので、非常に有難いです。

**Comment by yasuyuki-nakazawa** [comment]
情報アップデートいたします
現状、銘柄の情報取得に関してはご指摘のレイテンシが発生しております。これはリクエストがあった際に、当社のサーバー側に最新の情報を取得にいっているためでした。
当件は、カブステーションに保持している情報を即レスポンスできるように改善検討を始めました。
ローカル内での折り返しとなるため、レイテンシの大幅な削減がみこまれます。
改善までは、ご迷惑をおかけしますが、ご了承くださいませ。
なお、PUSHによる時価情報更新に関しては、当件とは関係なく動作しますので、不便なくご利用できることを補足させていただきます

**Comment by kichikun-w** [comment]
修正後の話になるのかもしれませんが、
kabuステーションは全銘柄の価格情報をリアルタイムで受信・保持しているのですか？
リアルタイムの配信間隔は何msですか？（それ以上細かく取得しても意味が無いので）
リストに「登録」していれば受信・保持されるのですか？
フル発注板への登録が必要ですか？タブをアクティブにしておく必要はありますか？

今回は時価情報についての質問ですが、その他の情報系コマンドについても
一度kabuステーションに問い合わせてkabuステーションが保持なり都度取得なり
して情報を返す事になると思いますので、保持される条件等あれば教えて頂きたいです。
（特に、注文約定情報についての情報が知りたいです）

**Comment by yasuyuki-nakazawa** [comment]
ここで記載されている「全銘柄」の定義ですが、kabuステーションで登録されており、画面に表示されている銘柄に関しては受信しています。全情報を保持しているわけでは在りません。各画面の特徴に応じてデータのライフサイクルが設計され保持しています。

フル板に関しては現状、配信することを想定はしておりませんが、今後の要望に応じて検討いたします。

注文約定の情報に関しては、基本的にkabuステーションの中で情報保持しております。

**Comment by yasuyuki-nakazawa** [comment]
時価情報の取得レイテンシに関しては、別要望としても頂戴しております
そちらのほうで対応検討進めております。当件は今しばらくお待ちいただけると幸甚です。
質問としては、クローズさせて頂きます
