### ISSUE TITLE
【要望】注文発注の市場コードに貴社優先市場の追加　→【対応済:2021/04/22 ver5.13.2】

### ISSUE THREAD

**Issue by sakatsusan** [kabucom/kabusapi#123]
大変お世話になっております。

注文発注の市場コードですが、現在、取引所の定指定が必須です。
銘柄発注の際に、当該銘柄が貴社が扱っている取引所なのか調べようにも
取引所を調べるAPIが不在で困っております。
（仮に調べる方法があったとしても、
発注前に一度問い合わせを発行する必要があり手間となります）

そこで、取引所のパラメータとして貴社として「当社優先市場」という
選択肢を入れていただけないでしょうか？

以上よろしくお願いいたします。

**Comment by yasuyuki-nakazawa** [comment]
ご要望理解いたしました。現状は優先市場での発注手段がないため、優先市場の情報取得または、優先市場での発注という形で検討させて頂きます。

**Comment by sakatsusan** [comment]
ありがとうございます。
記載しておりますが、優先市場の情報取得では
発注前に一度問い合わせを発行する必要があるため
優先市場での発注という方向でご検討いただけると幸いです。

**Comment by yasuyuki-nakazawa** [comment]
当件ですが、ver5.13.2（2021年04月22日 ver5.13.2）に対応完了いたしましたので、クローズとさせていただきます。
また、以下要望に関してですが、利用者からの明示的な市場指定による注文受付を行うという意向のため、１ステップ入り、ご利用しづらいと理解しつつ、今回の形をとらせていただきました。
APIは優先市場を視覚的に確認する手段がないため、諸整理で、直接優先市場が指定できるということが明確になるまでは、今回の形式を継続させていただくよう、ご理解いただけると幸甚です。
