### ISSUE TITLE
【不具合】残高照会が無いにも関わらず/positonsが空リストで返されない現象について

### ISSUE THREAD

**Issue by tomikki** [kabucom/kabusapi#124]
■[必須] 不具合事象(概要)
信用返済後、残高照会が無いにも関わらず/positionsで残高照会を行うと空リストではなく残高照会がある状態で返ってくる。
ちなみに上記事象後Kabuステーションを再起動してから再度/positionsで残高照会を行うと空リストが返ってくる。

■[必須] 本来想定されるアクションと事象
①残高照会が空であれば1570日経レバ1枚を信用成行買いで発注し/postionsで残高照会を確認
②約5分後に①の信用返済を行い/postionsで残高照会を確認、以後①②を繰り返す
　⇒空リストが返ってくることを想定するも空リストではなく残高照会がある状態で返ってくる（下記ログ参照）

■[必須] 不備発生時刻（常時の場合は、常時で記載ください)
常時

■[任意] お使いの環境(OS、Excelのバージョン等)、サンプル(Macro、アドインのバージョン）
Window10 pro
python 3.6.2

■[任意] 不備部分のログ
10:45:09.3794,I,11204,0032 KeepSession at 2020/10/12 10:45:09
10:45:45.2341,I,11204,0020 ワンショットチェック : 1570/T/ＮＥＸＴ　ＦＵＮＤＳ　日経平均レバレッジ・インデックス連動型上場投信/1 : amount=40, qty=
10:45:45.2351,I,11204,0020 KabuSApiManager.PreRelationCheck=CHECK_OK
10:45:45.2601,I,11204,0020 発注パラメータ：[新規] 成行
10:45:45.2621,I,11204,0020 OrderManager.Order Start:OrderParam: Account=01182213,CheckMode=1,Symbol=1570,Exchange=1,SecurityType=1,Side=2,CashMargin=2,MarginTradeType=2,OrderCapacity=,Price=0,Qty=1,OrdType=1,AdjustPrice=False,SellingShot=DelivType=0,FundType=11,AccountType=2,EffectiveDay=20201012,ExpireDay=20201012,Trigger=[],OrderReferenceCommand=[],ClosePositions=[],PriceType=0,TimeInForce=0,ExpireSession=0,Password=xxx,FrontInfo=FrontInfo=[Key=FrontChannelID/Value=240,Key=Trader/Value=000000A7,Key=Channel/Value=0,Key=ClientCode/Value=192.168.1.106,Key=Branch/Value=000,]
10:45:45.3364,I,11204,0020 OrderManager.Order End  :Result=0,ID=20201012A02N64614199,ClOrdID=202010120AE7h7000508,Detail=20201012B02N64614200,ResultMessage=[Key=KC_CommissionTable/Value=19,Key=KC_ConsignmentDepositRate/Value=30,Key=KC_Consideration/Value=26420,Key=KC_Commission/Value=0,Key=KC_CommissionTax/Value=0,Key=KC_DeliveryPrice/Value=26420,Key=KC_DepositRequirements/Value=7926.0,]
10:45:45.3384,I,11204,0020 UpdateOrderAndDetail Order.ID=20201012A02N64614199
10:45:45.3384,I,11204,0020 発注結果 : Result=0,ID=20201012A02N64614199,ClOrdID=202010120AE7h7000508,Detail=20201012B02N64614200,ResultMessage=[Key=KC_CommissionTable/Value=19,Key=KC_ConsignmentDepositRate/Value=30,Key=KC_Consideration/Value=26420,Key=KC_Commission/Value=0,Key=KC_CommissionTax/Value=0,Key=KC_DeliveryPrice/Value=26420,Key=KC_DepositRequirements/Value=7926.0,]
10:45:45.3494,I,11204,0018 Recv DistributeMessage = [ID=20201012B02N64614200,RecType=4,State=2,Qty=1,Price=0,SeqNum=3]
10:45:45.3504,I,11204,0017 OrderDetail.ID=20201012B02N64614200 UpdTime=10/12/2020 10:45:44
10:45:45.3504,I,11204,0017 UpdateOrderAndDetail Order.ID=20201012A02N64614199
10:45:45.3514,I,11204,0018 Recv DistributeMessage = [ID=20201012B02N64614200,RecType=4,State=3,Qty=1,Price=0,SeqNum=4]
10:45:45.3514,I,11204,0017 OrderDetail.ID=20201012B02N64614200 UpdTime=10/12/2020 10:45:44
10:45:45.3514,I,11204,0017 UpdateOrderAndDetail Order.ID=20201012A02N64614199
10:45:45.5645,I,11204,0018 Recv DistributeMessage = [ID=20201012E02N64614201,RecType=8,State=3,Qty=1,Price=21370,SeqNum=5]
10:45:45.5645,I,11204,0017 OrderDetail.ID=20201012E02N64614201 UpdTime=10/12/2020 10:45:44
10:45:45.5665,I,11204,0017 ID=E2020101201LT2,Symbol=1570,Exchange=1,Side=2,MarginTradeType=2,OpenQty=1,LeavesQty=1,HoldQty=0.0
10:45:45.5665,I,11204,0017 UpdateOrderAndDetail Order.ID=20201012A02N64614199
10:45:45.5675,I,11204,0017 UpdatePosition=ID=E2020101201LT2,Symbol=1570,Exchange=1,Side=2,MarginTradeType=2,OpenQty=1,LeavesQty=1,HoldQty=0.0
10:45:45.8580,I,11204,0001 NewsHeaders: count=3132
10:48:29.3904,I,11204,0035 KeepSession at 2020/10/12 10:48:29
10:50:00.0321,I,11204,0020 ワンショットチェック : 1570/T/ＮＥＸＴ　ＦＵＮＤＳ　日経平均レバレッジ・インデックス連動型上場投信/1 : amount=40, qty=
10:50:00.0321,I,11204,0020 KabuSApiManager.PreRelationCheck=CHECK_OK
10:50:00.0391,I,11204,0020 発注パラメータ：[返済] 成行
10:50:00.0391,I,11204,0020 OrderManager.Order Start:OrderParam: Account=01182213,CheckMode=1,Symbol=1570,Exchange=1,SecurityType=1,Side=1,CashMargin=3,MarginTradeType=2,OrderCapacity=,Price=0,Qty=1,OrdType=1,AdjustPrice=False,SellingShot=DelivType=2,FundType=11,AccountType=2,EffectiveDay=20201012,ExpireDay=20201012,Trigger=[],OrderReferenceCommand=[],ClosePositions=[ID=E2020101201LT2,Type=1,Qty=1|],PriceType=0,TimeInForce=0,ExpireSession=0,Password=xxx,FrontInfo=FrontInfo=[Key=FrontChannelID/Value=240,Key=MarginSellLimit/Value=0,Key=Trader/Value=000000A7,Key=Channel/Value=0,Key=ClientCode/Value=192.168.1.106,Key=Branch/Value=000,]
10:50:00.1068,I,11204,0018 Recv DistributeMessage = [ID=20201012B02N64614356,RecType=4,State=2,Qty=1,Price=0,SeqNum=3]
10:50:00.1148,I,11204,0018 Recv DistributeMessage = [ID=20201012B02N64614356,RecType=4,State=3,Qty=1,Price=0,SeqNum=4]
10:50:00.1308,I,11204,0020 OrderManager.Order End  :Result=0,ID=20201012A02N64614355,ClOrdID=202010120AE7h7000509,Detail=20201012B02N64614356,ResultMessage=[Key=KC_CommissionTable/Value=19,Key=KC_Consideration/Value=26420,Key=KC_Commission/Value=0,Key=KC_CommissionTax/Value=0,Key=KC_DeliveryPrice/Value=26420,]
10:50:00.1308,I,11204,0020 UpdateOrderAndDetail Order.ID=20201012A02N64614355
10:50:00.1308,I,11204,0020 UpdatePosition=ID=E2020101201LT2,Symbol=1570,Exchange=1,Side=2,MarginTradeType=2,OpenQty=1,LeavesQty=1,HoldQty=1.0
10:50:00.1308,I,11204,0020 発注結果 : Result=0,ID=20201012A02N64614355,ClOrdID=202010120AE7h7000509,Detail=20201012B02N64614356,ResultMessage=[Key=KC_CommissionTable/Value=19,Key=KC_Consideration/Value=26420,Key=KC_Commission/Value=0,Key=KC_CommissionTax/Value=0,Key=KC_DeliveryPrice/Value=26420,]
10:50:00.1308,I,11204,0017 OrderDetail.ID=20201012B02N64614356 UpdTime=10/12/2020 10:49:59
10:50:00.1308,I,11204,0017 ID=E2020101201LT2,Symbol=1570,Exchange=1,Side=2,MarginTradeType=2,OpenQty=1,LeavesQty=1,HoldQty=1.0
10:50:00.1308,I,11204,0017 UpdateOrderAndDetail Order.ID=20201012A02N64614355
10:50:00.1308,I,11204,0017 UpdatePosition=ID=E2020101201LT2,Symbol=1570,Exchange=1,Side=2,MarginTradeType=2,OpenQty=1,LeavesQty=1,HoldQty=1.0
10:50:00.1308,I,11204,0017 OrderDetail.ID=20201012B02N64614356 UpdTime=10/12/2020 10:49:59
10:50:00.1308,I,11204,0017 ID=E2020101201LT2,Symbol=1570,Exchange=1,Side=2,MarginTradeType=2,OpenQty=1,LeavesQty=1,HoldQty=1.0
10:50:00.1308,I,11204,0017 UpdateOrderAndDetail Order.ID=20201012A02N64614355
10:50:00.1308,I,11204,0017 UpdatePosition=ID=E2020101201LT2,Symbol=1570,Exchange=1,Side=2,MarginTradeType=2,OpenQty=1,LeavesQty=1,HoldQty=1.0
10:50:00.1348,I,11204,0018 Recv DistributeMessage = [ID=20201012E02N64614357,RecType=8,State=3,Qty=1,Price=21360,SeqNum=5]
10:50:00.1348,I,11204,0017 OrderDetail.ID=20201012E02N64614357 UpdTime=10/12/2020 10:49:59
10:50:00.1348,I,11204,0017 ID=E2020101201LT2,Symbol=1570,Exchange=1,Side=2,MarginTradeType=2,OpenQty=0,LeavesQty=0,HoldQty=0.0
10:50:00.1348,I,11204,0017 UpdateOrderAndDetail Order.ID=20201012A02N64614355
10:50:00.1348,I,11204,0017 UpdatePosition=ID=E2020101201LT2,Symbol=1570,Exchange=1,Side=2,MarginTradeType=2,OpenQty=0,LeavesQty=0,HoldQty=0.0

**Comment by cyber-minion** [comment]
上記の現象は仕様になります。
kabuステーションは、全返済しても再起動するまでは残高がある状態でレスポンスしています。ただし、残数量（LeavesQty）は0になるはずで、残高がないことを意味します。また、kabuステーションを再起動しますと残数量0のデータはレスポンスされません。

**Comment by tomikki** [comment]
仕様である旨承知しました。また、返済後に残数量（LeavesQty）が0になることを確認しました。
