### ISSUE TITLE
【要望】約定の検知とアクティブオーダーの管理について

### ISSUE THREAD

**Issue by kichikun-w** [kabucom/kabusapi#125]
現状の仕様を確認したところ、
約定確認もアクティブオーダーの管理も「注文約定照会」
で当日に発効した全注文を取得し、自身で解析しなければならない構造
になっているようなので、デイトレードで１日に何十回・何百回と注文→約定・キャンセル
を繰り返しつつ、リアルタイムで約定情報の監視を行うようなトレードを行うと、
膨大な量の通信が発生し、処理が非常に重くなる事が予想されます。
・件数指定をして直近の約定情報のみの取得する機能
・アクティブオーダー(終了していないオーダー）のみの取得する機能
・時刻をパラメータにしてある時刻以降に追加・変更されたオーダーのみを取得する機能
・オーダー更新情報のPUSH配信機能
等、通信量を抑えるための機能の追加をお願いします。

**Comment by yasuyuki-nakazawa** [comment]
注文約定に関しての拡張は検討しております。

ご要望頂いている下記点は推進中です。
・件数指定をして直近の約定情報のみの取得する機能
　→　後述の指定時刻以降の情報フィルタで代替を検討しておりました。
・アクティブオーダー(終了していないオーダー）のみの取得する機能
　→　当観点は検討に追加させて頂きます。
・時刻をパラメータにしてある時刻以降に追加・変更されたオーダーのみを取得する機能
　→　指定時間以降に更新のあった注文を取得するフィルタは既に検討いれています。
・オーダー更新情報のPUSH配信機能
　→　若干お時間かかりますが、こちらも検討に入れております。

**Comment by kichikun-w** [comment]
回答ありがとうございます。
とりあえずフィルタ機能の追加をお待ちしています。
