### ISSUE TITLE
【質問】python apiでの返済方法がよくわかりません

### ISSUE THREAD

**Issue by Pusm** [kabucom/kabusapi#126]
こんにちは。
python apiで発注まではできたのですが、返済がうまくいきません。
信用建玉を、指定したIDごとに成行返済するということをしたいです。
（IDごとでなく、シンボルごとにすべて返済でも構いません）

https://github.com/kabucom/kabusapi/blob/master/sample/Python/kabusapi_orders.py
をベースにして作成した下記のコードを実行すると、「{'Code': 1009001, 'Message': '建玉が選択されていません。'}」というメッセージが出ます。 
尚、この前に別途今のPosition情報を取得し、Position['Symbol]などとしてコード指定しております。

       obj = { 'Password': '******',
                'Symbol': Position['Symbol'],
                'Exchange': 1,
                'SecurityType': 1,
                'FrontOrderType': 10,
                'TimeInForce': 0,
                'Side': Position['Side'],
                'CashMargin': 3,
                'MarginTradeType': 1,
                'DelivType': 1,
                'FundType': 11,
                'AccountType': 4,
                'Qty': 100,
                'ClosePositionOrder': 1,
                'Price': 0,
                'ExpireDay': 0 }
        json_data = json.dumps(obj).encode('utf-8')

また、ClosePositionsに建玉IDを入力しないといけないのかと思い、

        obj = { 'Password': '********',
                'Symbol': Position['Symbol'],
                'Exchange': 1,
                'SecurityType': 1,
                'FrontOrderType': 10,
                'TimeInForce': 0,
                'Side': Position['Side'],
                'CashMargin': 3,
                'MarginTradeType': 1,
                'DelivType': 1,
                'FundType': 11,
                'AccountType': 4,
                'Qty': 100,
                'ClosePositions': [{'HoldID':Position['ExecutionID'] ,'Qty':Position['LeavesQty']}],
                'Price': 0,
                'ExpireDay': 0 }
        json_data = json.dumps(obj).encode('utf-8')

としても、HTTP Error 500: Internal Server Error
{'Code': 8, 'Message': '決済指定内容に誤りがあります'}と出ます。

お手数をおかけしますが、解決策を教えていただければと存じます。

P.S.
リファレンスというよりは、もう3,4個、こういった売買面を中心にサンプルコードを追加して頂けるとさらに親切になるかなと存じます。殆どの方がサンプルを土台にして組むと思いますので。

**Comment by yasuyuki-nakazawa** [comment]
Sideの指定が「'Side': Position['Side'],」となっております。
これは、残高照会APIに表示されているSideをそのまま返済パラメータに指定しているようですが、
返済の場合は反対売買を指定するので、記載頂いている処理では新規(買)の建玉を返済(買)で注文がされているのかと思われます。
（＝返済(買)の建玉が無いからエラーになっている）
本来であれば、返済(売)で注文するのが正しいです。 
Siteの指定方法をご確認ください。

**Comment by Pusm** [comment]
お返事ありがとうございます！
無事自動売買できました。
