### ISSUE TITLE
【質問】先物の価格はリアルタイムで閲覧できますか？

### ISSUE THREAD

**Issue by higenobu** [kabucom/kabusapi#127]
日経先物ミニを価格を見ながら発注したいのですが、どのAPIを利用すればいいでしょうか？

**Comment by cyber-minion** [comment]
先物、オプションのAPIの公開は10月下旬を予定しております。

**Comment by higenobu** [comment]
発注するときにはAPIを利用したいのですが、こちらはCloudのサーバからでもアクセスできますか？
プログラムをテストできる環境はありますか？

**Comment by yasuyuki-nakazawa** [comment]
当該APIはkabuステーションがインターフェースを公開することで実現しているものとなっております。
そのため、kabuステーションが起動していることが前提であることと、当該プロセスが稼動している端末からのリクエストのみ受領するような制限を設けております。
そのため、Cloudのサーバからのアクセスというのは直接的には行えません。
類似QA：https://github.com/kabucom/kabusapi/issues/92

プログラムをテストする環境に関してですが、APIのテストモードを準備しています。こちらはモック的な機能ではありますが、テスト実行を行うことができるものとなっています。

**Comment by higenobu** [comment]
ご返答ありがとうございます。
PC上でVMでUbuntuを載せてプロフラムを開発しています。
この場合は、Ubuntuに御社のプロセスを稼働させれば実現できるでしょうか？
テスト環境のモックは今でも使えるのでしょうか？
今、口座開設の手続きをしているところです。


2020年10月15日(木) 21:38 yasuyuki-nakazawa <notifications@github.com>:

**Comment by yasuyuki-nakazawa** [comment]
kabuステーション自体はインストール型のアプリケーションになっていまして、対象OSはWindowsになっています。
リクエスト元のIPチェックを実施しており、同一端末（＝IPが同一）以外のリクエストはリジェクトされます。
テスト環境という明示的なものではなく、kabuステーションがモック的にレスポンスを返す機能はございますという内容になります。

**Comment by higenobu** [comment]
先物はもう可能でしょうか？
APIのテストは開設までできないのでしょうか？
GITでサンプルコードを入手していますが、APIのインストールが必要ですね。
詳しくマニュアルを見ていないのでどこかに書かれているかもしれませんが以下の質問です。
リアルタイムのQUOTEを判定しながら発注関数をCallしたいのですが、
その関数が返す値はありますか？
約定したかどうかは別な関数で判定するのですね。
開設すればすぐに運用に入りたいのですが。

**Comment by higenobu** [comment]
APIをダウンロードして試してみました。
APIの詳しいリファレンスはどこを見ればいいでしょうか？
日経先物MINIの最新の約定価格を分単位で取り続けたいのですが、
プログラムでループするのでしょうか？
