### ISSUE TITLE
【質問】PUSH配信で、配信の引き渡しが多すぎる場合の挙動

### ISSUE THREAD

**Issue by sakatsusan** [kabucom/kabusapi#128]
時価PUSH配信について、
値が更新される際に、当方のプログラムに値が引き渡されると思いますが、
その間、時価情報が高頻度で変わった場合、受け渡しが間に合わなくなると思います。

その場合、最新の状態が渡されるだけなのでしょうか？

例えば、現値が１０００円→１０１０円→９９０円となった場合、
１０１０円の変化の受け渡しが間に合わなかった場合、それはスキップされて９９０円となるのでしょうか？

質問の背景は、分足チャートのようなものを考えており、１分内の高値、安値などを得たいのですが、
上記スキップがあると１０１０円が取得できないこととなります。

**Comment by yasuyuki-nakazawa** [comment]
PUSHについては、RESTでの情報取得の最新情報ではなく、更新情報が配信されますので、記載の例ですと、1010円の取得は可能となります。

**Comment by sakatsusan** [comment]
PUSHといっても、最低限の所要時間が必要だと思われます。

仮に、WebSocket上、秒間 千回送信しかパフォーマンスが出ない場合として、時価変化が１万回あったとします。

この場合、どこかでオーバーフローして上記の１０１０円の取得ができないことがあると思われるのですが、如何ですか？

**Comment by yasuyuki-nakazawa** [comment]
記載の部分はWebSocketの仕様に依存することになるかとおもわれます。

**Comment by sakatsusan** [comment]
> 記載の部分はWebSocketの仕様に依存することになるかとおもわれます。

質問をさせていただいた意図は、WebSocketが仮に０秒で処理できたとしても、
仮に過剰な時価変化があった場合どうなるかということとなります。

例えば時価変化が１万回あった場合、
株ステーションアプリ内で処理しきれないスループットの場合、
上記の１０１０円の取得ができないことがあると思われるのですが、如何ですか？

こちらで株ステーションを使っているPC能力としても有限のものではありますし。

**Comment by yasuyuki-nakazawa** [comment]
こちら、検証した結果、ソケット側のCloseがおこなわれることが確認されております。
