### ISSUE TITLE
【要望】注文発注のドキュメント記述について

### ISSUE THREAD

**Issue by kichikun-w** [kabucom/kabusapi#129]
注文発注のパラメータの説明が非常にわかり辛いです。

PasswordからCashMarginまでは判りますが、
MarginTradeTypeについては赤字で「必須」と書かれているにもかかわらず、
　「※現物取引の場合は省略可」と記載されており、矛盾しています。
　「現物：指定不要　信用：必須」の表示が正しいのではないでしょうか？
   「指定不要」と「省略可」では意味合いが全く異なります。
　　「省略可」なら、省略しなかった場合は何らかの意味を持つと言う事です。
　　現物取引の場合、信用取引区分を指定する事で何が変わるのでしょうか？
　 正確な説明を記載していただきたいです。
DelivType
　現物買は必須との事ですが、モバイルアプリでは設定の中にありますが、「指定なし」か「お預り金」しか指定できません。
　１と２でどう動作が変わるのでしょうか？
　１を選択した場合、どのような動作になるのでしょうか？
FundType
　この項目も赤字で「必須」と書かれていますが、
　「※信用新規と信用返済は、指定不要」との記載があり、矛盾があります。
　つまり「現物：必須 信用：不要」ではないのでしょうか？
　また、「※現物売は、「' '」 半角スペース2つを指定必須。」ともあるので、
　「現物買い時のみ必須、現物売り時はデフォルト値として自動で「' '」、信用時は不要」
　で良いのではないでしょうか？
　また、この項目に設定する値のそれぞれの意味GUIやヘルプで探したのですが、見つかりませんでした。
　買った現物株式の預かり区分だと思うのですが、「保護」が「保護預り」、
　「保証金代用」にあたるのは「信用代用」なのか「証拠金代用」なのか「信用取引」なのか・・・
　どれが何を意味するのか良くわかりません。　
AccountType
　こちらは特定／一般／法人を指定するところだと思いますが、
　特に理由が無ければ、個人の場合、「特定」で良いと思います。
　こちらも赤字で「必須」となっていますが、
　未指定でデフォルト「特定」、指定した場合のみ「一般」「法人」として扱われる
　といった対応はできないでしょうか？
ClosePositionOrder、ClosePositions 
　これらはどちらも赤字で「必須」となっていますが、
　「※ClosePositionOrderとClosePositionsはどちらか一方のみ指定可能。
　　※ClosePositionOrderとClosePositionsを両方指定した場合、エラー。」
　との記載もあるので明らかに矛盾しています。
　ClosePositionOrderの「8」に「ClosePositionsで個別指定」を設け、ClosePositionsは「ClosePositionOrderが8の場合のみ必須」
　等とした方が判りやすいと思います。
　仕様変更が難しい場合、説明の記述を見直すべきだと思います。
Price
　「※FrontOrderTypeで成行を指定した場合、0を指定する」
　とのことですが、
　「寄成（前場）」「寄成（後場」の時のpriceに意味はあるのですか？
FrontOrderType
　設定すべき値は説明文で理解できますが、Priceがここの値に依存しているので、Priceより前に記述すべき項目だと思います。
　さらに、ここに記載されている表の列を増やしてPriceの要・不要を記載すれば分り易いと思います。

総じて判り難いので全体的にドキュメントの記述を見直していただきたいです。
また、
Exchangeは「貴社優先市場」又は「東証」
SecurityTypeは「株式」（ここは一択にもかかわらず指定が必要なのが理解できません）
FundTypeは「保護」（ただし現物売の場合は半角スペース２つ）
AccountTypeは「特定」
ClosePositionOrderは「0」
ExpireDayは「0」
がデフォルト値で「省略可能」で良いと思うので、仕様も見直していただけると有難いです。

**Comment by Pusm** [comment]
同じく、orderについての情報が不親切すぎて、わけがわからないという感じです。
とりあえず、その他の部分はおいておいて、orderのアップデートに注力頂けるとありがたいです。

**Comment by kichikun-w** [comment]
さらに、一つお願いです。
APIは基本的に操作を自動化するためのツールなので、各パラメータは基本的にkabuステーションGUIで操作する時にも設定可能だと思います。
ですので、kabuステーションGUI上のどこで設定する値なのか、明示しておいていただけると非常に有難いです。
そうしておいていただけると、設定する値の意味合いがわからない時等は、kabuステーションのマニュアルで確認したり、通常のサポート窓口に質問できるので、コミュニティを汚さなくて済みます。

**Comment by yasuyuki-nakazawa** [comment]
ご指摘ありがとうございます。
一旦、Order部分に絞ってリファレンスの補正を行っていきます。

また、頂いている下記の点に関してですが、現状Orderメソッド一つで汎用的に対応していることに起因しております。
この点は当初議論として出ていた部分ですが、今後、StockOrder(現物）、MarginOrder(信用）のように
商品を限定したインターフェースを設けることで、不要なパラメータの設定の手間や考慮が必要なくなるため、
シンプルな設定インターフェースを検討推進していきます。

上述頂いている後半部分について、一部回答させていただきます。
・SecurityTypeは「株式」（ここは一択にもかかわらず指定が必要なのが理解できません）
　→　当該項目については、今後は派生商品が追加される予定です。

・FundTypeは「保護」（ただし現物売の場合は半角スペース２つ）
　→　当該項目は意識せず設定できるように現行のkabuステ上のパラメータを取得するインターフェースの追加または、
　　　kabuステの設定項目をデフォルトとするような仕様を検討しております。
　　　AccountType含め他記載項目も上記同様。

・現物買は必須との事ですが、モバイルアプリでは設定の中にありますが、「指定なし」か「お預り金」しか指定できません
　→　「自動引落」に関しては、WEBサイトから自動引き落としを選択している場合に有効になります。
　　　この点についてはリファレンスに追記いたします。

**Comment by akira-yamamoto-f** [comment]
ここで質問させていただきます。
Price の型が integer <int32> となっていますが、小数値株価（0.1円）はどのように指定するのでしょうか？

**Comment by yasuyuki-nakazawa** [comment]
こちら、numberが正しい表記となります。リファレンスの方は訂正させていただきます。
よろしくお願いいたします
