### ISSUE TITLE
【質問】注文約定照会のレスポンスにあるRecvTimeでタイムゾーン付きになることがある

### ISSUE THREAD

**Issue by tsuchinaga** [kabucom/kabusapi#13]
注文約定照会のレスポンスにある `RecvTime` について、  
多くの場合は `2020-08-20T13:22:19.471516` のようなタイムゾーンなしの結果が返されますが、  
稀に `2020-08-21T08:44:05.8233361+09:00` のようなタイムゾーン付きの結果が返されます。

タームゾーンありなしはどのように区別すれば良いでしょうか？

**Comment by yasuyuki-nakazawa** [comment]
以前、当件タイムゾーン無しで統一とお伝えいたしましたが、諸検討のうえ、タイムゾーン有りで統一させて頂くことになりました。
別途、お知らせ経由で連携させて頂きます。
