### ISSUE TITLE
【要望】マーケット関連ランキング情報のAPI提供　→【対応済：2021/01/28】

### ISSUE THREAD

**Issue by ybangit** [kabucom/kabusapi#130]
APIで現在のマーケットのランキング情報を取得したい。
yahooファイナンス（以下参考）などで一般的に提供されているランキング情報のAPIによる提供を要望します。

~~~~~~
参考（yahooファイナンス）　https://info.finance.yahoo.co.jp/ranking/?kd=4
〇マーケット関連ランキング
値上がり率
値下がり率
ストップ高
ストップ安
年初来高値更新
年初来安値更新
出来高
単元当り出来高
出来高増加率
出来高減少率
売買代金上位
売買代金下位
高かい離率
低かい離率
ゴールデンクロス
デッドクロス
など
~~~~~~~

よろしくお願いします

**Comment by yasuyuki-nakazawa** [comment]
まず、前提としてはkabuステーションが保持していない情報に関しては配信できません。
記載いただいた項目ベースですと、ゴールデンクロスやデッドクロスの情報については取得不可となります。
こちらは算出頂く形となります

各種ランキングに関しては追加を検討しておりますので、上述を含めて検討推進していきます

**Comment by ybangit** [comment]
なるほど、分かりました。ぜひよろしくお願いします。

**Comment by yasuyuki-nakazawa** [comment]
kabuステーションの詳細ランキングに掲載されている情報を取得するインターフェースを追加する予定を立てております。
「お知らせ」というIssueをたてさせて頂きました。
今後は、そちらのほうで対応内容、予定を順次更新させて頂きます
引き続き、よろしくお願いいたします。

**Comment by ybangit** [comment]
2021年1月未定（予定）
・API(ランキング)情報I/F追加

ですね。要望取り入れていただき、ありがとうございます。

**Comment by yasuyuki-nakazawa** [comment]
当件ですが、1/28 にランキングの追加を実施させていただきました
ver 5.12.5.0

**Comment by ybangit** [comment]
update確認しました。ありがとうございました。

**Comment by ybangit** [comment]
・API(ランキング)情報I/F追加 　が対応されたことへの感想 (独り言)

　この機能追加によって
　スクリーニング時に売買代金やtick回数などで取引しやすい銘柄を選びやすくなり
　値上がり率、等で自分のスクリーニングアルゴリズムを検証したりできるようになり
　有益に利用しています。

　やはり自分でスクレイピングなどして取ってくることと、APIで提供されることでは、
　APIで提供されたほうが情報取得が楽で、気持ち的にも使い勝手が全然違いました。

　今後もこのような（kabus station内の情報を API 化する）
　機能追加が（可能な限り早く）多く追加されてゆくことを期待します。

**Comment by yasuyuki-nakazawa** [comment]
コメントいただいております通り、銘柄のスクリーニングが重要であると思っております。
現状、リアルタイムに市場の全銘柄を俯瞰して監視するには付加的にも相応にきびしく、一定の条件に応じたスクリーニングを行える機能こそ重要であると考えております。
APIとしての拡張もさることながら、特定の条件下での銘柄スクリーニングに関してはkabuｽﾃｰｼｮﾝ本体の機能拡張を含め検討していく予定です。
今後とも忌憚なきご意見等頂けると幸甚でございます
