### ISSUE TITLE
【要望】1日の発注額の制限　→【見送り】

### ISSUE THREAD

**Issue by kabucomapi** [kabucom/kabusapi#131]
お世話になります。
１日あたりの発注金額について、リミット額を設定できる仕様の追加を要望します。現状では1発注当たりのリミット設定機能がありますが、自動発注システムの動作においては予期せぬ連続注文が心配なため、1発注当たりの制限より1日当たりの制限の方が安心できます。

細かな仕様としては、
・成行注文の発注額積み上げ計算は、その日の制限価格上限、発注時の株価いずれで計算するか選択できるを発注額積み上げ計算から除外する選択ができる
・現物の売却発注額・新規現物買付発注額、信用ポジション解消発注額・新規信用発注額を発注額積み上げの対象とする
・現物の売却発注額を発注額積み上げ計算から除外する選択ができる
・信用ポジション解消発注額を発注額積み上げ計算から除外する選択ができる
・現物の新規買付額を発注額積み上げ計算から除外する選択ができる
・新規信用発注額を発注額積み上げ計算から除外する選択ができる

手動発注の場合必要ない機能ですが、自動発注においては、安全性確保の面から是非ともほしい機能ですので、実装について検討いただけると幸いです。

**Comment by yasuyuki-nakazawa** [comment]
現状は、ワンショット上限という形で制限は設けさせていただいておりますが、加えて金額の合計での制御ということですね。
kabuステーションAPIはkabuステーションクライアントのインターフェース公開というソリューションになっています。
APIに限定して注文金額計と約定金額計周りを元にした制御をいれていくことは非常に難しいところではあります。
しかしながら、意図としましては理解いたしましたので、検討はさせていただきます。

**Comment by kabucomapi** [comment]
お世話になります。
ご回答いただきありがとうございます。APIに限定して、、、の部分が理解出来ていないので、認識違いの要望となるかもしれませんが、APIからの発注に限定せずに、御社web ページの注文約定照会メニューで表示される内容について、上記仕様の実現は難しいでしょうか？。使い勝手は悪くなりますが安全性を向上させたいです。
自動売買プログラム初心者にとっては、予期せぬ連続発注が怖くて開発を躊躇している方も多いと思いますし、別回答でもいただいた御社の安全性に対する方針とも合致した要望と考えていますので、前向きにご検討いただけると幸いです。

**Comment by yasuyuki-nakazawa** [comment]
発注系のシステムだけでなく、勘定系のシステムにも大きく手を入れる必要があり、非常に難しいと思慮いたします。
予期しない連続発注に対しての防止策という点では、発注パラメータに通番等を付与する等の案も過去に検討したことがあります。同一のリクエストはこれでリジェクトすることができますので。
kabuステーションで処理できる対応であれば、比較的実現性は高いのですが、チャネルを跨いで包括的なチェックを追加する場合は、発注システム自体に手を加える必要があるため、注文全体の取次ぎレイテンシの悪化等もあり、相当の検討が必要となる状況であることはご理解いただけると幸甚です

**Comment by kabucomapi** [comment]
お返事遅くなりましたが、ご回答いただきありがとうございます。技術的に困難であることは理解いたしました。
システム開発時に個人向けAPI公開は想定されていなかったであろうことから、致し方ないことと思いますが、個人で開発したプログラムを本番環境を用いてブラッシュアップしていくことや汎用pcの信頼性を考慮すると、利用者側にとっては重要な仕様ではあります。
丁寧な対応ありがとうございました。
