### ISSUE TITLE
【質問】バックテストのやり方

### ISSUE THREAD

**Issue by nobuodesu** [kabucom/kabusapi#132]
Kabu.com apiではバックテストはできないのでしょうか。

**Comment by Pusm** [comment]
pythonと組み合わせれば簡単にできるかと。

**Comment by nobuodesu** [comment]
ご返信ありがとうございます。
Python/Websocketを使用することを想定していますが、取引部分のコード以外のコードのロジックの正確性は確認済みです。
他の部分と取引部分のコードを統合して、実際の挙動をテストできないでしょうか。

**Comment by yasuyuki-nakazawa** [comment]
>他の部分と取引部分のコードを統合して、実際の挙動をテストできないでしょうか。
他の部分というのは、具体的にどのようなものをイメージされているでしょうか

**Comment by nobuodesu** [comment]
実際に取引しないのなら、取引条件の一致、不一致をカウントする等で、取引ロジックの妥当性を検証できると認識しています。
カウントするのでなく取引するコード、例えばkabusapi.sendorder.pyのようなコード入れて試したいと言うのが趣旨です。

※本来のバックテストは過去データを活用するものと思いますが、上記はリアルタイムデータを使用しての検証を想定しています

**Comment by yasuyuki-nakazawa** [comment]
本番モードと検証モードの２つを機能として有しています。
たとえばですが、時価情報を受けて、一定の処理で発注するというプログラムを作成された場合に、時価情報の取得は本番で実施。葉中処理を検証モード（Portの変更）を行うことで所定のじかに基づくトリガ発注の挙動を確認することができると考えます。
なお、この際には、本番用のトークンと検証用トークンの２つを取得した上で、適切にトークンを使用することで実現可能と考えます。
