### ISSUE TITLE
【質問】PUSH配信のタイミング、内容

### ISSUE THREAD

**Issue by nobuodesu** [kabucom/kabusapi#133]
1.Push配信が遅延する、定期的に送信されないことはあるのでしょうか。例えば、東証取引時間に特定の銘柄だけ配信が遅延する、一部時間帯で配信されないなどがないかどうかという確認です。

2.定期的にデータ配信されるものの、一部個別の配信情報がない場合は"null"とされ、０(値)や空とされることはないのでしょうか。

**Comment by yasuyuki-nakazawa** [comment]
1.基本的には特定の銘柄だけ配信遅延を起こすということはシステムの観点から発生しづらいと考えます。
　なお、情報配信に関しては、クライアント側の処理パフォーマンスにも大きく依存するため、レイテンシに関しては免責とさせていただいております。
2. Pushに関しては「定期的」にデータが配信されるわけではありません。情報更新があったタイミングで配信されます。
　そのため、配信情報がない場合は、情報自体の配信がされません。

**Comment by nobuodesu** [comment]
ご回答ありがとうございます。2.について、配信情報がない場合で、一部の情報がない場合はnullとなるのでしょうか。０や空を返すこともあるのでしょうか。

**Comment by yasuyuki-nakazawa** [comment]
上記一点訂正します
２に関しては、情報がない場合は、直近の値が設定されています
