### ISSUE TITLE
【質問】同時発注

### ISSUE THREAD

**Issue by nobuodesu** [kabucom/kabusapi#134]
※kabusapi_sendorder.pyを参照しながら質問しています。
二つの銘柄に同時発注したいのですが、postは二度に分けて行う必要があるのでしょうか。工夫して、一度に2銘柄分をpostすることは可能でしょうか。
初歩的な質問で恐縮ですがよろしくお願いします。

**Comment by yasuyuki-nakazawa** [comment]
POSTは二度分けて実施する必要があります。
発注余力の確認を各注文ごとに実施しておりますので、注文は個別に処理していく必要がございます為。

**Comment by nobuodesu** [comment]
理解しました。迅速な回答ありがとうございます。
