### ISSUE TITLE
【質問】レジスト数エラー

### ISSUE THREAD

**Issue by araposama** [kabucom/kabusapi#135]
APIで以下のエラーが出ます。これはどういう意味で、どうすれば解決しますか。マニュアルでは書いてないようです。
HTTP Error 400: Bad Request
4002006　レジスト数エラー

**Comment by ybangit** [comment]
ちょうど私も株価・板情報の照会でレジストエラーが出ていて解決しましたので共有します。

レジストエラーは「登録銘柄50件以上になって登録できません」ということです。

知っていないと悩むのは
GETで板情報などの照会をかけたときに、「登録銘柄に登録されてない場合は、サーバ側で自動的に銘柄を登録する」という仕様です。

ですので銘柄が50件登録されている状態で、
登録されていない銘柄の板情報を照会しようとすると
(サーバ側で)新しい銘柄を登録しようとして、
51件目になってしまうため、レジストエラーになっていました。おそらく同じ原因ではないかと思います。

(銘柄を登録していないと照会が遅いのは、サーバ側で銘柄登録してから応答を返すことが原因だと思います)


ロジックを整理すると以下の処理順でうまくいきました
【株価・板情報を照会する場合】
1、API key取得
2、登録銘柄全削除
3、銘柄登録
4、株価・板情報を照会

プログラムの中で銘柄を50件ずつ切り出し、
2〜4をループで回すとよいのかと思います。

私の場合はpythonで上のループを並列処理し
1秒10件を超えないように調整したところ
東証1部の2200件程の株価を11分程度(平均3.5件/秒)で取得することができました。

まだ調整の余地が若干ありますが、銘柄照会の応答時間は、サーバ側の負荷やキャッシュが関係しているのか、銘柄毎に試行毎に0.1秒であったり3秒〜5秒かかったりまちまちで、平均10件/秒のパフォーマンスは出ませんでした。

株価照会のパフォーマンスは今の10倍程の速度は必要だと思っています。

以上、参考になればとおもいます。

**Comment by araposama** [comment]
大変参考になります、ありがとうございます
登録銘柄全削除コードを入れてみます

**Comment by yasuyuki-nakazawa** [comment]
こちら、わかりづらいということで理解いたしました。
リファレンスのエラー部分に対応方法を補足するようにリファレンス拡張してまいります

**Comment by yasuyuki-nakazawa** [comment]
リファレンスの方も更新いたしました
