### ISSUE TITLE
【質問】kabusAPI経由で取得した情報の取り扱いに関して

### ISSUE THREAD

**Issue by ybangit** [kabucom/kabusapi#136]
kabusAPIで取得したデータに関する利用規約について以下の行為は問題無いでしょうか？確認させてください。

1、データを蓄積・加工してインターネット上に掲載する。または独自のアプリ等で利用して第三者に提供する。

2、営利目的で利用する。
　(インターネットや独自のアプリ等で、蓄積・加工した情報を売買する)

また、取得した情報を提供する際に必要なライセンスの記述はありますか？

よろしくお願いします

**Comment by kabusukebe** [comment]
サービス利用規定の第3条に以下のように書かれているのでどちらも不可でしょう。

> 金融商品情報サービスの内容を第三者へ販売すること、第三者へ再配信すること、第三者と共同で利用すること、情報を閲覧している端末機以外へ転載することを禁じます。

> 第三者の作成されたプログラム等を利用することを禁じます。

https://kabu.com/pdf/Gmkpdf/service/kabustationapiuserpolicy.pdf

**Comment by ybangit** [comment]
ありがとうございます。確認不足ですみません。
明確に禁止事項ですね。。緩和してほしい。。

**Comment by yasuyuki-nakazawa** [comment]
当件ですが、配信の情報に関しては、取引を目的としたものとなります。
既に上記部で記載がありますが、当社のサービス利用規定で以下のように定めており、お客さまがご記載いただいたような事項もお控えいただいております。
　金融商品情報サービスの内容を第三者へ販売すること、第三者へ再配信すること、第三者と共同で利用すること、情報を閲覧している端末機以外へ転載することを禁じます。

**Comment by ybangit** [comment]
曖昧な記載でしたが、
正式な回答ありがとうございました。

(ところでissueは解決したら基本的にはユーザのほうでcloseするのでしょうか？運営に任せておけばよいのでしょうか？)
