### ISSUE TITLE
【質問】python sampleコードの kabusapi_register.py と kabusapi_register1.py

### ISSUE THREAD

**Issue by ybangit** [kabucom/kabusapi#137]
git 上の python sampleコードに、銘柄登録のコードサンプルとして
kabusapi_register.py と kabusapi_register1.py の２つのコードがありますが
銘柄が異なるだけで内容は同じですので、手違いではないでしょうか。

**Comment by yasuyuki-nakazawa** [comment]
確認します

**Comment by cyber-minion** [comment]
掲題の２つのコードは内容は同じです。片方を削除するようにいたします。

**Comment by yasuyuki-nakazawa** [comment]
記載のとおり、kabusapi_register1.py は同一です。不要なのでこちらは削除させて頂きます。
