### ISSUE TITLE
【質問】kabuステーションの起動時の動き

### ISSUE THREAD

**Issue by ybangit** [kabucom/kabusapi#138]
株価情報のGETリクエストのレスポンスが遅いので原因を調べていたところ
kabuステーションを起動した時に毎回150MB程度のデータをサーバに送信しているようです。

私の環境では起動後の5分間ほどはネットワークがほとんど送信に使われてしまうため、その間はGETリクエストが非常に遅くなっているようでした。(20秒とか)

データの送信が終わるとGETリクエストが現状の速度になります。

起動から少し待てばよいだけなのですが、少し気になりました。
ネットワーク環境によっては10分程度かかり、その間はGETリクエストがほとんど機能しないため、あまり無視できない時間になるかもしれません。

仕様で変えられないとは思いますが、何か設定で変えることはできますか？

**Comment by yasuyuki-nakazawa** [comment]
同様のご意見はいただいております。
当該情報量を半分にする対応を目下実施しております。他に手段があるかに関しては調査してみます。
お使いの回線の太さはいかがでしょうか？

**Comment by ybangit** [comment]
回線はポケットWiFiのwimax2を利用していて、
実効速度はだいたい下り10MB, 上り5MB といったところであまり早い回線ではありません。

起動時のアップロードには実際には大体4分強かかります。

ただ起動初回のみ少し待てばよいだけなので、知っていれば問題ないですが。時間が短くなるようでしたらそれは良いとは思います。

**Comment by yasuyuki-nakazawa** [comment]
回線の太さに影響受けする部分が大きいのが現状です。
しかしながら、要望として上記は目下対応検討しておりますので、そちらは今しばらくお待ちください。

**Comment by yasuyuki-nakazawa** [comment]
kabuステーション起動時の情報量を削減する対応については別途実施させて頂きます。
当該質問に対しては、一旦クローズとさせて頂き、当対応をお待ちいただけると幸甚です
