### ISSUE TITLE
【質問】先物のapi

### ISSUE THREAD

**Issue by nobuodesu** [kabucom/kabusapi#139]
10月下旬のリリース予定と伺っておりましたが最新のスケジュールはいかがでしょうか。

**Comment by yasuyuki-nakazawa** [comment]
現状は次週末を想定しています。
改めて日付確定しましたら、こちらのほうでも展開させて頂きます。

**Comment by nobuodesu** [comment]
ありがとうございます。お待ちいたします。

**Comment by yasuyuki-nakazawa** [comment]
10月29日のkabuステーションのアップデート後より、先物、オプションのご利用が可能となります。
https://github.com/kabucom/kabusapi/issues/143
