### ISSUE TITLE
【質問】 kabuSTATION_API_PUSH_sampleについての質問

### ISSUE THREAD

**Issue by MitsuguKondo** [kabucom/kabusapi#140]
kabuSTATION_API_PUSH_sample　ファイルにて
'=WEBSOCKET(9433,1,"現値")のように入力とありますが
板情報の場合はどのようにすれば良いのでしょうか？

**Comment by yasuyuki-nakazawa** [comment]
Pushと記載されていますが、Excelのアドインとマクロに関してでしょうか。
であれば、気配情報の取得等は「=WEBSOCKET(9433,1,"売気配(1)値段")」のように記述いただければとおもいます。

**Comment by MitsuguKondo** [comment]
あるがとうございます。
上手く取得できました。
