### ISSUE TITLE
【質問】発注でMarginTradeTypeのエラーがでます

### ISSUE THREAD

**Issue by Pusm** [kabucom/kabusapi#141]
すみません、python apiにてorderを行おうとしているのですが、下記のようなエラーが出ます。
どのパラメータが問題か、わかりますでしょうか？
簡単にで構いませんので、アドバイスくださいますと幸いです。
お手数をおかけしますが、よろしくお願い致します。

{'Code': 4002013,
 'Message': 'パラメータ不正：MarginTradeType - 詳細はkabuSログファイルを確認してください'}

python コードのobj部分は下記です。

    obj = { 'Password': '********',
            'Symbol': symbol,
            'Exchange': 1,
            'SecurityType': 1,
            'FrontOrderType': 10,
            'TimeInForce': 0,
            'Side': str(Side),#1sell2buy
            'CashMargin': 2, #genbutu#shinyou
            'MarginTradeType': 1,
            'DelivType': 0,
            'AccountType': 4,
            'Qty': 100,
            'ClosePositionOrder': None,
            'ClosePositions': None,
            'Price': 0,
            'ExpireDay': 0 }

**Comment by hishiharahaz** [comment]
Pusmさん
指定しているパラメータは正しいかと思われます。
MarginTradeTypeのエラーとなるようですが、考えられる原因としましては、指定された銘柄が制度信用の新規建（買or売）ができないのかもしれません。
確認ください。

**Comment by Pusm** [comment]
どうもありがとうございます。
制度信用売買可能な銘柄についてもこのエラーが出ております。また、現物、一般を指定してもやはりエラーとなります。

**Comment by Pusm** [comment]
一番ありがたいのは、制度信用、一般信用でのobjのサンプルを一つでいいのでどなたかに見せて頂けることかと。設定項目が複雑に分岐していたり、入力不要なのか、入力してはいけないのか分からないですし、色々ときついものがあります。

**Comment by Pusm** [comment]
ちなみにほぼ同じコードで先週は制度信用約定していたのですが、どこかを変えたらオーダーできなくなってしまいました。これは私が悪いのですが、どこを変えたのか忘れてしまいまして。

**Comment by hishiharahaz** [comment]
Pusmさん
参考までとなりますが、新規建の制度信用、一般信用でのobjサンプルになります。
銘柄は、仮で8411にしています。
また、新規建の発注として必要なパラメータのみとしています。
どのパラメータが新規建の時に必要かは、APIリファレンスに記載されていました。
https://kabucom.github.io/kabusapi/reference/index.html#tag/order%2Fpaths%2F~1sendorder%2Fpost

【objサンプル】
１．制度信用
```
obj = { 'Password': '******',
        'Symbol': '8411',
        'Exchange': 1,
        'SecurityType': 1,
        'FrontOrderType': 10,
        'Side': '2',
        'CashMargin': 2,
        'MarginTradeType': 1,
        'DelivType': 0,
        'AccountType': 4,
        'Qty': 100,
        'Price': 0,
        'ExpireDay': 0 }
```

２．一般信用
```
obj = { 'Password': '******',
        'Symbol': '8411',
        'Exchange': 1,
        'SecurityType': 1,
        'FrontOrderType': 10,
        'Side': '2',
        'CashMargin': 2,
        'MarginTradeType': 2,
        'DelivType': 0,
        'AccountType': 4,
        'Qty': 100,
        'Price': 0,
        'ExpireDay': 0 }
```

**Comment by Pusm** [comment]
遅くなりましてすみません。
サンプルコードを大変ありがとうございました。
トライしてみようと思います。
