### ISSUE TITLE
【質問】検証用uriについて

### ISSUE THREAD

**Issue by nobuodesu** [kabucom/kabusapi#142]
検証用81に銘柄を登録しようとしても、空のファイルが戻ります。
また、websocketで配信が無いのかのと思いました。これは銘柄登録できていないことが要因かもしれませんが。
どのように使用することを想定しているのでしょうか。
また何が81と異なりできないのでしょうか

**Comment by yasuyuki-nakazawa** [comment]
検証用は銘柄登録は空が戻ります。
疎通を確認するのみを目的としております。
検証用は主にスタブによる返信と捉えていただけると幸甚です。

**Comment by nobuodesu** [comment]
承知しました。ありがとうございます。
