### ISSUE TITLE
【質問】NT倍率の銘柄コード？

### ISSUE THREAD

**Issue by gogotorotan** [kabucom/kabusapi#144]
日経平均先物mini、限月指定方法などわからなかったのですが、
先程API仕様をみたら、先物銘柄コード取得というAPIがありました。
日経平均先物mini期近指定などもできるようですね。

TOPIXと先物miniとのサヤ取りをしたい場合、別々に注文を出す必要がありますか？
それとも、NT倍率という銘柄コードはあるのでしょうか？
先物コード一覧に記載のものだけでしょうか？

**Comment by yasuyuki-nakazawa** [comment]
別々に発注する必要があります

**Comment by gogotorotan** [comment]
了解しました。ありがとうございました。
