### ISSUE TITLE
【要望】配信データに商品区分の追加　→【対応予定】

### ISSUE THREAD

**Issue by Ros522** [kabucom/kabusapi#145]
お世話になってます。
先物OPの対応ありがとうございます。

株式、先物を同時に銘柄登録している場合に株式データなのか先物データなのかを判断するため
時価PUSH配信のレスポンス情報に「株式、先物、オプションの区分を示すフィールド」の追加を要望いたします
現行ですとクライアント側では、Symbolの文字列長やフィールド自体の存在有無から商品を区分する必要があり
あまり適切とはいえない判断方法となってしまいます。

**Comment by yasuyuki-nakazawa** [comment]
注文時に利用しているSecurityType等で補完可能かどうかを検討させて頂きます

**Comment by cyber-minion** [comment]
#317 にて対応済ですので、クローズさせていただきます。
