### ISSUE TITLE
【要望】銘柄情報、時価情報・板情報取得の市場コードに貴社優先市場の追加 要望

### ISSUE THREAD

**Issue by quwup** [kabucom/kabusapi#146]
#123 と重複しますが、銘柄情報、時価情報・板情報取得の処理においても、銘柄コードのみで動作するよう、市場コードに優先市場を追加していただけるよう希望します。
使い勝手が悪いのは、#123 に記載されている通りです。
そもそも、Kabu ステーション自体、銘柄コードの入力のみで動作するようになっているので、同様の機能を実現していただきたいです。

**Comment by yasuyuki-nakazawa** [comment]
https://github.com/kabucom/kabusapi/issues/123
こちらと合わせて検討しております。
