### ISSUE TITLE
【要望】カスタムメニュー的な　→【見送り】

### ISSUE THREAD

**Issue by ubunsato** [kabucom/kabusapi#147]
APIというよりカブステ全般の要望となりますが

カブステでかゆいところに手が届かない処・・・例えば、決算短信や有報へのアクセスがし辛い、ETFやREITの詳細情報をメニューの「四季報」から開けないなどありますが、それらをユーザー側で補完できるようになるといいなというものでございます。
登録銘柄の右クリックメニューから自作プログラムを開くようなものを追加していただけるとその辺りの不便をユーザー側で解決できるようになるかと存じます。
誰でも簡単に使えるように＜パス＞　証券コードを引数として渡すだけのものでプログラムの知識のないひとでも、ネットで落としたスクリプトなどを使えるようにしていただければカブステの使い勝手があがるだけでなく、コミュニティの拡大も期待できるかと存じます。
よろしくお願いいたします。

**Comment by yasuyuki-nakazawa** [comment]
現状ですとUIを直接外部から操作するような想定がないため、若干難しい部分がございますが
要望としては理解いたしました。検討いたします

**Comment by yasuyuki-nakazawa** [comment]
当件ですが、kabuステーションAPIはkabuステーションを外部から操作する為のインターフェースではないポリシーもあり、
当該ポリシーに沿った対応を優先させることとなりました。
大変申し訳ございませんが、当該ご要望は見送りさせてください。

**Comment by ubunsato** [comment]
わざわざ、ご返答ありがとうございます。
