### ISSUE TITLE
【質問】未保有株の売却注文

### ISSUE THREAD

**Issue by nobuodesu** [kabucom/kabusapi#150]
Pythonのsendorderで保有していない株式について売却注文すると、どのような反応が返るのでしょうか。エラーは生じるものの、ほかの動作に影響ないでしょうか。
複数銘柄の同時買いから入って、同時売りを行うことを企図した場合を想定しての質問です。
複数銘柄の同時買いが成立せず、単一銘柄だけが買えた場合、その買えた銘柄を売ってしまいたいです。
買えた銘柄と買えていない銘柄の同時売り注文で、買えた銘柄を売ってしまうことが可能かというのが質問の趣旨です。
よろしくお願いします。

**Comment by yasuyuki-nakazawa** [comment]
現物株式の件に関しての質問だと思われますので、現物株式という前提で回答いたします。
未保有ポジションの売却注文は受け付けられません（＝エラーリターン）
買いが約定した後で売りを入力して頂く必要があります。

**Comment by nobuodesu** [comment]
ありがとうございます。
エラーリターンが返った場合、pythonの動作自体がストップするのでしょうか。

**Comment by yasuyuki-nakazawa** [comment]
>エラーリターンが返った場合、pythonの動作自体がストップするのでしょうか。
エラーリターン後にどのように処理するかについては、プログラムの作り次第だと思います。

**Comment by yasuyuki-nakazawa** [comment]
当件Closeさせていただきます
