### ISSUE TITLE
【質問】保有株数以上の売却注文

### ISSUE THREAD

**Issue by nobuodesu** [kabucom/kabusapi#151]
任意の銘柄で、保有株数以上の数量の売却注文をpythonのsendorderで出した場合、保有株数の売却を約定することが可能でしょうか。
よろしくお願いします。

**Comment by yasuyuki-nakazawa** [comment]
保有株数以上の売却注文を発注することはできません。
エラーが返されます。

**Comment by nobuodesu** [comment]
承知いたしました。
ありがとうございます。
