### ISSUE TITLE
【質問】ExpireDay

### ISSUE THREAD

**Issue by nobuodesu** [kabucom/kabusapi#152]
Pythonのsendorderの掲題項目は今日を指定すれば、本日中、注文は有効でしょうか。

**Comment by hishiharahaz** [comment]
nobuodesuさん
ExpireDayですが、引けまでの間でしたら、今日を指定すれば、注文は今日まで有効となるようです。
私は、本日中の注文をするときは、ExpireDayに「0」を指定するようにしています。
リファレンスによるとExpireDay「0」の仕様は以下となっていました。
・引けまでの間 : 当日
・引け後 : 翌取引所営業日

**Comment by nobuodesu** [comment]
ご教示ありがとうございます。
質問内容だけでなくDaytimeライブラリを使っていた部分と簡素化でき助かりました。
