### ISSUE TITLE
【質問】出来高関与率について

### ISSUE THREAD

**Issue by kabu3995** [kabucom/kabusapi#153]
ここまで大丈夫、と示せない類のものですが
気配値幅の半分以上かつ気配値幅以上は買いあがらない前提の場合

出来高関与の目安というのは
先日の出来高
当日の出来高
25日平均の出来高

の10パーセント程度を目安にしておけばよいのでしょうか
この場合、返済すれば関与率は2倍になりますが、インしてる時点で出来高は平日より増えてると考えると、25日平均の10パーセントの出来高を上限でインまでかなと想定しております。

ただ、当日材料があり出来高が急増してますと当日の出来高に倣ってポジションが増やせるとは思いますし、
開示などがあった場合、25日平均や当日の出来高ではなく、単に値段に対する関与だけ気を付けて、ポジションは無限にとりたい人も多く、ニュースがあった場合は出来高審査が変わってくるとは聞きますが。。

**Comment by yasuyuki-nakazawa** [comment]
大変申し訳ございません。
当件に関しては、当コミュニティの範疇外のため、お答えすることができません。
ご了承くださいませ
