### ISSUE TITLE
【要望】kabusapi_boardの複数銘柄同時取得について　→【代替対応済：2021/01/28】

### ISSUE THREAD

**Issue by nananain** [kabucom/kabusapi#154]
要望
例えば、取得したい銘柄リストをPOSTして、銘柄リストのboard情報を1度に取得するようにはできないでしょうか。

要望の背景としては、リクエスト処理時間が遅いという点があります。
kabusapi_board.py
に関して、以下URL文にあるように、１つの銘柄に対してのリクエストと思います。
    http://localhost/kabusapi/board/{symbol}@{exchange}
私の環境ではこのリクエストが1秒程度処理にかかっています。
（pythonで50銘柄のループ処理で50秒の処理時間）

もう少し取得できる件数を増やしたいため、python内でリクエストをマルチスレッドにしたり、
２つのプログラムでリクエストを並列で処理しようとしたのですが、時間は短縮されませんでした。

ローカルでリクエストを受けたkabuステーションがサーバへ情報取得しているため時間がどうしてもかかってしまう
という仕様ならば、短縮が難しいとも思います。

もし処理時間を短縮する方法もありましたらご教授頂けると幸いです。
なお、pythonの単純なfor文ループ処理で
kabuステーション起動後初回では、50銘柄で214秒
2回目以降でAPI銘柄登録リストへ未登録では、50銘柄で49秒
2回目以降でAPI銘柄登録リストへ登録済みでは、50銘柄で49秒
という処理時間でした。

**Comment by yasuyuki-nakazawa** [comment]
現在、REST経由での時価情報のレスポンス高速化に関しては、対応方式の検討を着手しております。
１リクエストで複数銘柄の取得というインターフェースの追加は現状想定されておりません。

記載のとおり、サーバに問合せしていることがレイテンシの発生原因となっておりますので、
こちらは、カブステーションが保有している時価情報をレスポンスすることで、高速に処理することが可能な見込みですので、対応までは不便かけますが、ご了承くださいませ。

**Comment by yasuyuki-nakazawa** [comment]
こちら、2021/1/28のver5.12.5.0 にてRESTによる/boadのレスポンス速度の大幅改善を行いました。
1度目のリクエストはサーバ取得を行う都合上、レイテンシに変更ありませんが、２回目以降のレスポンスはおよそ1ms～2msへ改善されております。
最新バージョンへアップデートの上、施行いただけると幸甚です

**Comment by yasuyuki-nakazawa** [comment]
当件は、Closeとさせていただきます
