### ISSUE TITLE
【質問】トークン発行について

### ISSUE THREAD

**Issue by FujimakiHiroyuki** [kabucom/kabusapi#158]
pythonでapiを動かしたいと思っています。
python3をインストールし、python kabusapi_token.pyを実行したのですが、

HTTP Error 401: Unauthorized
{'Code': 4001013, 'Message': 'トークン取得失敗'}

といったエラーが出てトークンが取得できません。
権限系のエラーかと思うのですが、kabuステーションは起動し、電子契約画面ではFintechプランは利用可状態になっています。
何が原因と考えられるでしょうか。宜しくお願いいたします。

**Comment by tsuchinaga** [comment]
APIドキュメントのトークン発行にレスポンスの項があり、401 Unauthorizedのエラーコードに記載がありました

> 4001013 トークン取得失敗：kabuステーションがログインしている状態で、APIパスワードが不正

パスワードが正しいかご確認ください

**Comment by FujimakiHiroyuki** [comment]
ありがとうございます。
kabusapi_token.pyの中にAPIパスワードの入力場所があることに気がついて、そこにパスワードを入れたらいけました。
readmeにそれを書いておいて欲しかった…
