### ISSUE TITLE
【不具合】<urlopen error [WinError 10061] 対象のコンピューターによって拒否されたため、接続できませんでした。>

### ISSUE THREAD

**Issue by taro-jpg** [kabucom/kabusapi#159]
■TOKENを取得する際に表題の通りエラーが表示されるようになった
■ 前営業日まで動作していたのが動作しなくなった
■ 11月３日夜
■ windows10
■ 
・ネットで調べたたところ複数のポートが開いているとこういったエラーが出ることがあるとありました。
・11月３日の夜に家の中の別のPCからもログインしようとしたことが原因でないかと思っています。
・もしポートを閉じることが対応策だとすると、一般的な対応策を教えていただければと思います。（ルーターの設定を直す等）

<urlopen error [WinError 10061] 対象のコンピューターによって拒否されたため、接続できませんでした。>
（ソースコード）
    def kabusapi_token(self):
        obj = {'APIPassword': '*****'}
        json_data = json.dumps(obj).encode('utf8')

        url = 'http://localhost:18080/kabusapi/token'
        req = urllib.request.Request(url, json_data, method='POST')
        req.add_header('Content-Type', 'application/json')

        try:
            with urllib.request.urlopen(req) as res:
                print(res.status, res.reason)
                for header in res.getheaders():
                    print(header)
                print()
                content = json.loads(res.read())
                pprint.pprint(content)
                return content['Token']
        except urllib.error.HTTPError as e:
            print(e)
            content = json.loads(e.read())
            pprint.pprint(content)
        except Exception as e:
            print(e)

**Comment by yasuyuki-nakazawa** [comment]
現状、kabuステーションAPIは同一端末からのリクエストのみ受け付ける仕組みとしております。
別PCからのリクエストはリジェクトされます。

**Comment by taro-jpg** [comment]
kabuステーションのAPIの設定画面もグレーになり、動かせない状態になってしまいました。
リジェクトの解除はどのように行えばいいでしょうか？

**Comment by yasuyuki-nakazawa** [comment]
kabuステーションAPIの設定画面というのは画面右上の「</>」のマークのことでしょうか
こちらがグレーということは、API自体が利用できない状況ということですので、
・API設定の「APIを利用する」のチェックが外れていないか
・kabuステーション自体がログインされているか
を一旦ご確認ください

APIをまず利用可能な状態にする（APIの利用マーク「</>」をグリーンにする）ことが最初のステップですので
引き続き、結果のほうを連携いただけると幸甚です。

**Comment by taro-jpg** [comment]
電話で相談したところ、私の勘違いということがわかりました。
後ほど板も削除します。失礼しました。
