### ISSUE TITLE
【質問】発注エラー　code:4001005 

### ISSUE THREAD

**Issue by takezo1004** [kabucom/kabusapi#160]
ReqestBody = {'Password': '*********', 'Symbol': '165120019', 'Exchange': 23,
		 'TradeType': 1, 'TimeInForce': 3, 'Side': '1', 'Qty': 1, 
			'FrontOrderType': 120, 'Price': 0, 'ExpireDay': 0}
xApikey = 'ad07726f679d4c1f82e37e84c67e9109'
json_data = json.dumps(ReqestBody).encode('utf-8')
url = 'http://localhost:18081/kabusapi/sendorder'
req = urlib.request....

上記の発注条件でapiを呼び出しておりますが

cntent = {'Code': 4001005, 'Message': 'パラメータ変換エラー - 詳細はkabuSログファイルを確認してください'}　のエラーとなります。
よろしくお願いいたします。

もう一つ質問ですが返済建玉指定の方法がわかりません。ご教授お願いいたします。

**Comment by cyber-minion** [comment]
呼び出されているAPIは「注文発注（先物）」で間違いないでしょうか？

また、返済建玉指定について、サンプルコード
「kabusapi_sendorder_future_pay_ClosePositions.py」
「kabusapi_sendorder_future_pay_ClosePositionOrder.py」
などがありますので、ご参照ください。

**Comment by takezo1004** [comment]
間違いありません
下記コードです    
def sendorder(self,ReqestBody,xApikey):
        # 引数
        # パスワード、銘柄コード、取引所コード、商品種別、売買区分、現物信用区分、信用区分
        # 注文数、決済順序、決済建て玉指定、注文価格、有効期限、執行条件
        orderId = ""
        json_data = json.dumps(ReqestBody).encode('utf-8')
        # 本番／検証url設定
        url = self.domain+self.Port +'/kabusapi/sendorder'

        # headersは辞書形式でxAPI-KEYを渡す
        headers = {'content-type': 'application/json','X-API-KEY': xApikey}
        req = urllib.request.Request(url, json_data, method='POST')
        req.add_header('Content-Type', 'application/json')
        req.add_header('X-API-KEY', self.xApikey)
        try:
            with urllib.request.urlopen(req) as res:
                print(res.status, res.reason)
                reason = res.reason
                status = res.status
                content = json.loads(res.read())
        except urllib.error.HTTPError as e:
            content = json.loads(e.read())
            status = content['Code']
            # return content
        except Exception as e:
            status = 0
            # return e
        finally:
            if status == 200:
                orderid = content['OrderId']
            else:
                orderid = ""
        return orderid

**Comment by takezo1004** [comment]
返済ですが
'ClosePositions': [{'HoldID':'E20200924*****','Qty':100},{'HoldID':'E20200924*****','Qty':100}],
サンプルの"HoldID"はどこに存在するのですか？
新規注文時自分でClosePositionsに設定するのですか？
約定情報では、取得できません。

**Comment by takezo1004** [comment]
お世話になります。
私のミスです。/futureが抜けていました。申し訳ありません。
検証の場合　orderId =Non ですがこれでいいのですか

url = self.domain+self.Port +'/kabusapi/sendorder'

**Comment by takezo1004** [comment]
解決できました。ありがとうございました。
