### ISSUE TITLE
【質問】ＡＰＩについて

### ISSUE THREAD

**Issue by SHIMADUTOMOYUKI** [kabucom/kabusapi#161]
先物取引の売買区分（Side）について売りが１、買いが２と記載されていますが、
買いの新規を行う、それを返却した場合、どちらも２を指定するのでしょうか？
それとも最初の買いのみ２で、その返却の場合は、１になりますでしょうか？
よろしくお願いします。

**Comment by yasuyuki-nakazawa** [comment]
記載の例をもとに回答します。
買い新規の場合は、２：買い
売り返済の場合は、１：売り
を指定することになります

**Comment by SHIMADUTOMOYUKI** [comment]
お答えいただき、ありがとうございます。

「TradeType」の指定も併せておしえてください。
買いの新規を行い、その返済を行った場合を教えてもらいたいのですが。
以下の認識でよかったでしょうか？

・買い新規
　「TradeType」に「1：新規」を指定
　「Side」に「2：買」を指定

・上記の返済
　「TradeType」に「2：返済」を指定
　「Side」に「1：売」を指定

よろしくお願いします。

**Comment by yasuyuki-nakazawa** [comment]
記載のとおりです。
