### ISSUE TITLE
時価情報・板情報のレスポンスにおいて、AskとBidが逆？

### ISSUE THREAD

**Issue by ekjls432** [kabucom/kabusapi#163]
時価情報・板情報のレスポンスにおいて、AskとBidが逆になっているのでは無いかと思い、質問させて頂きます。
レファレンスでの「時価情報・板情報」のレスポンスサンプルでも確認できますが、
BidPriceはSell1と同値となっており、AskPriceはBuy1と同値になっています。
Sellは売り気配であり、これはBuyの買い気配よりも高い数値になっているため、SellとBuyに関しては正しいと思います。
しかしBidは買い気配なので、Buy1と同値になるはずで、Askよりも低い数値のはずです。

**Comment by yasuyuki-nakazawa** [comment]
kabuステAPIは、トレーダー目線から見た場合のBID＝売値、ASK＝買値となっています。
このため、BidPrice=Sell1のPrice、AskPrice=Buy1のPriceという数値となります。

この点はわかりづらいと思慮されるため、リファレンスにも明示的に記載させて頂きます

**Comment by ekjls432** [comment]
ありがとうございます。
ご返信内容にある「トレーダー目線から見た場合のBid=売値、Ask=買値」というと、私の認識通り、Bid=買い気配、Ask=売り気配となり辻褄が合いませんが、「トレーダー目線から見た場合の買値をBid、売値をAsk」としているということでしょうか。
一般的な認識とは反対となっていると思われるため注意が必要かと思います。レファレンスへの記載について、どうぞよろしくお願いいたします。

**Comment by ekjls432** [comment]
追記です。ややこしいかもしれないため、情報を整理させて頂きますと、一般的にはAskはBidよりも高い値段を指すと思います。
Askは売り気配値（気配を提示する側にとっての売値・トレーダーにとっての買値）、Bidは買い気配値（気配を提示する側にとっての買値・トレーダーにとっての売値）を指すと思います。
このように、気配を提示する側とされる側（トレーダー）で、AskとBidどちらが買値・売値になるかは異なりますが、AskとBidそのものが反対になることは無く、常にAskはBidよりも高い値段のほうを指すと思います。
カブステAPIではこれが反対となっているため、注意喚起が必要かと思われます。

**Comment by nsop2** [comment]
私もハマりました。APIを使った取引は自己責任とはいえ、リファレンスへのBidとAskが反対であることの明示が必要だと思います。
私のBidとAskの理解は @ekjls432 さんと同じです。またトレーダー目線の表記だとすると、Sell[1-10]は買気配、Buy[1-10]は売気配になり辻褄が合わなくなります。

**Comment by yasuyuki-nakazawa** [comment]
こちら、リファレンスへの補完を実施させていただきます

**Comment by cyber-minion** [comment]
お待たせいたしました。リファレンス補完しましたので、クローズさせていただきます。
