### ISSUE TITLE
【不具合】Kabuステーション起動時にメモリの使用量が上がりました

### ISSUE THREAD

**Issue by lstm500** [kabucom/kabusapi#164]
■[必須] 不具合事象(概要)
・2020/11/5からkabuステーション立ち上げ時にメモリの使用量が大幅に上昇して、約5分でメモリ使用量が100％まで到達するようになりました。
（タスクマネージャーで目視）
（2020/11/6も再現されるか確認してみて、11/6現在はではアプリ立ち上げから約5分でメモリ使用量が25,874MB
まで上昇しています。状態としては毎秒一定ずつ使用メモリが上昇していくような状態です。11/4まではメモリの使用量はここまで目立っていなかったと記憶しています）

■[必須] 本来想定されるアクションと事象
・本来がこうなのかもしれませんが、もう少し使用メモリは少ないはずなのではないかと思います

■[必須] 不備発生時刻（常時の場合は、常時で記載ください)
・常時

■[任意] お使いの環境(OS、Excelのバージョン等)、サンプル(Macro、アドインのバージョン）
OS　　　　　　：Windows10(Home) , 
プロセッサ　　：AMD Ryzen 7 3700X - 8Core Processor 3.59GHz , 
RAM　　　　　：32.0GB
システムの種類：64ビット

■[任意] 不備部分のログ
特になし
参考画像（タスクマネージャーのスクリーンショット）
[https://gyazo.com/1af922455c53f93d2e0c79272f2a3186](url)

こちら対処の仕方や、不具合かどうなのかをご教授いただけるとうれしいです。

**Comment by yasuyuki-nakazawa** [comment]
数点ご確認させてください
・APIの利用している、していないに関わらず、記載の事象が発生していますでしょうか
・銘柄登録リストの表示枚数、表示銘柄数はどれくらいでしょうか
こちらをもとに、確認を実施してみます
現状、手元のkabuステーションでは290,000Kほどのメモリ使用量で、1日利用しても増えておりません。

**Comment by lstm500** [comment]
ご返信ありがとうございます。
こちら、先の返信に追記する形で返信させていただきます。

・APIの利用している、していないに関わらず、記載の事象が発生していますでしょうか
　→API使用有無に関係なく、カブステーション立ち上げ時点からメモリが増えだします。

・銘柄登録リストの表示枚数、表示銘柄数はどれくらいでしょうか
　→こちらは最近カブステーションのAPI部分以外あまり使わなくなってしまい、把握できておりませんのでこちらのカブステーションのスクリーンショットを載せておこうと思います。(注文の値段・時間などだけ画像を加工して伏せました）
　　→銘柄登録リストはシート2までは埋まっており、シート3からはすべて空欄です。
　
https://gyazo.com/09618f07c1ae90472e6071b526d79cd8（11/6 , 19:52アプリ立ち上げ）


・また設定で特段変更した記憶がある部分は、発注制限で現物が3万円、その他が1万円までと設定しています。

よろしくお願いします。

**Comment by lstm500** [comment]
ご返信ありがとうございます。
こちら、先の返信に追記する形で返信させていただきます。

・APIの利用している、していないに関わらず、記載の事象が発生していますでしょうか
　→API使用有無に関係なく、カブステーション立ち上げ時点からメモリが増えだします。

・銘柄登録リストの表示枚数、表示銘柄数はどれくらいでしょうか
　→こちらは最近カブステーションのAPI部分以外あまり使わなくなってしまい、把握できておりませんのでこちらのカブステーションのスクリーンショットを載せておこうと思います。(注文の値段・時間などだけ画像を加工して伏せました）
　　→銘柄登録リストはシート2までは埋まっており、シート3からはすべて空欄です。
　
https://gyazo.com/09618f07c1ae90472e6071b526d79cd8
（11/6 , 19:52アプリ立ち上げ）

・また設定で特段変更した記憶がある部分は、発注制限で現物が3万円、その他が1万円までと設定しています。

よろしくお願いします。

**Comment by lstm500** [comment]
こちら追記させていただきます

・APIの利用している、していないに関わらず、記載の事象が発生していますでしょうか
　→API使用有無に関係なく、カブステーション立ち上げ時点からメモリが増えだします。
　　→システム設定→API→利用設定→APIを利用するのチェックを外しましたら、使用メモリの上昇がなくなりました。

よろしくお願いします。

**Comment by yasuyuki-nakazawa** [comment]
回答ありがとうございます
同条件と思われる環境下で検証しておりますが、再現に至っておりません
引き続き検証してみます。

**Comment by lstm500** [comment]
ご返信ありがとうございます。
またご尽力も併せてありがとうございます。

こちらアプリの再インストールなども考えております。
またこちらも進展がありましたら、こちらでご連絡させていただきます。

よろしくお願いします。

**Comment by lstm500** [comment]
こちら、気づきがありましたので追記させていただきます。

本日、引け後に試しに色々やっていたところ、

・まずログイン後すぐにメモリ使用の急上昇はあります（変化なし）
・メモリ使用上限が70％～80％弱程度になりました（変化あり）
・そのままログインを継続し続けると約3分後に、メモリ使用量が2MB程度になりました（変化あり）
　→一応この時点で問題なく使える状態になっているのではないかと思います。場中にはまだ試しておりません。
※APIは「利用する」にチェックを入れています。

SSを時系列でとったものです。
21：00にログインで1分毎のメモリ使用量のSSです。
※ログインはアプリを立ち上げ、ログインボタンを押したの意味
https://gyazo.com/9003583a823fe9c02713e4b130b0cf0b
https://gyazo.com/7f63d98de84a2fd34f1da3158717b9bb
https://gyazo.com/ad8c054d61dc5a1f370ac5eb48715093

経験則的にですが何か重いデータを読み込んでるとき、読み終わったときにpythonで起こる反応と似ているなと思いました。
何かしらログなどが必要でしたら提出することもできます。

よろしくお願いします。

p.s.
また別件ですが、SSの中に表示されているアプリ画面の「銘柄登録リスト」「先物リスト」こちらは右上の×ボタンを押すことができませんでした。

**Comment by yasuyuki-nakazawa** [comment]
追加情報ありがとうございます
kabuステーション起動後にAPIでのリクエストは実施されておりますでしょうか
実施されている場合はどのようなリクエストをされておりますか
当方でkabuステーションを起動したままにし、APIを有効化しても対象の事象が発生しておりません
引き続き検証してみます

**Comment by lstm500** [comment]
こちら11/9にAPIで試したリクエストは以下になります。
get_token
get_symbol
いずれも正常に動作し、contentの内容も取得できております。

よろしくお願いします。

**Comment by lstm500** [comment]
こちら11/9にAPIで試したリクエストは以下になります。
kabusapi_token
kabusapi_symbol
いずれも正常に動作し、contentの内容も取得できております。


よろしくお願いします。

**Comment by yasuyuki-nakazawa** [comment]
当件ですが、同様のリクエストを実施してもメモリの使用量に大きな変化がなく、再現ができておりません。
やられていることは認証でトークンを取得して、銘柄をレジストしているのみということですよね？

**Comment by lstm500** [comment]
ご返信ありがとうございます。

当日行った行動の認識としてはその通りです。
他に当日行った可能性のあるものとしては、http://localhost/kabusapi/symbol　→　PriceRangeGroup（呼値）の取得です。

思い当たる点としては、前日までのほうに特徴があります。
メモリの使用量が大幅に上昇した前日までは発注と訂正・取消を相当数繰り返していました。

現在kabuステーションを立ち上げても、メモリの上昇は起こっておりません。
ですので、なんとなくですがもしかしたら本人の直近10日程度の過去の注文が関係している可能性があるのではないかと思います。

よろしくお願いします。

**Comment by yasuyuki-nakazawa** [comment]
了解しました。注文を相当数入れた状態でToken取得から時価情報の取得を試行してみます。

**Comment by lstm500** [comment]
ありがとうございます。どうぞよろしくお願いします。

**Comment by yasuyuki-nakazawa** [comment]
注文、約定を大量に実施した状態で、銘柄情報をMAXで取得して検証しましたが、同事象は発生しておりません。
当方では、事象再発をさせられておりません。
他に同事象が発生している方はいらっしゃいますでしょうか？

**Comment by lstm500** [comment]
ご返信ありがとうございます。
最近は起こっていません。本日確認したところ、300～400MB前後のメモリ使用で安定しています。

よろしくお願いします。

**Comment by yasuyuki-nakazawa** [comment]
>最近は起こっていません
なにか修正、改善された部分等ございますか？
メモリ利用に関しての改善等は特段実施しておりません。

また、以下でも何度も検証しましたが、指摘の事象発生はありませんでした。
概ねメモリ使用量：199.6MB～220.5MB

以下の流れで検証実施。
①kabuステ起動時                  (199.6MB)
②APIから1000注文した           (203.5MB)
③1000注文を取り消し             (220.5MB)
④BOARDメソッドを50回実行    (186.5MB)
⑤SYMBOLメソッドを50回実行  (188.3MB)

当週で再現が確認されない場合は、一旦Issue自体はCloseさせていただきます。
再発確認できた時点で、再度Openにいたします

**Comment by lstm500** [comment]
ご連絡ありがとうございます。

こちらかしこまりました。
再度、同様のことが起こりまして、かつ再現性があるようでしたらまたご連絡させていただきます。
どうぞよろしくお願いいたします。

**Comment by lstm500** [comment]
こちら最近また同様の事象が起こっているので再掲させていただきます。

＜前提条件＞
①直近でkabu STATION_APIのPUSH型の時価データの取得（先物、インデックスと現物を2銘柄ほど）しており、かつ、日々発注を行っているという前提です。
②kabu STATION APIを数日間使っていない場合は当該事象は起こりません
③APIを利用する状態になっていなければ当該事象は起こりません

＜発生する事象＞
1. kabu ステーション起動時にメモリを大幅に使用する
2. システムエラーが起こる（数日間kabu ステーションを使い発注を行っている日が続いたときは、その後はほぼ毎日この状態になる）

※本日のメンテナンス以前から起こっています

https://gyazo.com/1770e4c989a007021278f6a88c59a515
https://gyazo.com/c0e0446d54d56ea47cd9bed098ce5e22

毎日kabu STATION APIを使い発注を行っていると数日が経過後、再現性100％の確率で起こっております。
基本的な質問ですが、kabu STATION APIを使った発注は毎営業日使うような設計になっておらず、たまに使うような前提で作られたものなのでしょうか？
その場合何日間のインターバルを設けて使えばよいでしょうか？

よろしくお願いします。
