### ISSUE TITLE
【質問】対当売買について

### ISSUE THREAD

**Issue by kabu3995** [kabucom/kabusapi#165]
場中の信用×信用　　現物×現物　現物×信用
これらの注文は全く受け付けないようにするようリクエストは出しましたが
ＡＰＩで自分の注文同士が場中対当しないためにはどうすればいいでしょうか。

自分が売り注文を巣ｙ同売買のトレードで出してるとき、条件を満たして自動売買が発注されたり
後は自動売買同士のヒットを指せない設定をば

**Comment by yasuyuki-nakazawa** [comment]
頂戴している自注文の対当しないようにという点に関してですが、
APIに関わらず、ご自身にてご自分の注文が対当しないようにご留意くださいますようお願いいたします。

**Comment by yasuyuki-nakazawa** [comment]
当件、Closeさせていただきます
