### ISSUE TITLE
【不具合】PUSH配信にて送られてこないデータがある？

### ISSUE THREAD

**Issue by ob2r** [kabucom/kabusapi#167]
■[必須] 不具合事象: 
                                    時間　　　値
                                 14:31:59    1,394.0
                                 14:32:06    1,394.0　　　上から順に時間が経過するとします。(実際の歩み値です。)
                                 14:32:06    1,393.0　　　14:32:06に5回も値が更新しているにもかかわらず,
                                 14:32:06    1,392.0 　　　配信されたのは最後の[14:32:06    1,390.0]のみだけでした。
                                 14:32:06    1,391.0  　　　多数の銘柄でも同様なことが起きているのを確認しています。      
                                 14:32:06    1,390.0

■[必須] 想定する動作: リファレンス通りなら、14:32:06のデータは1394.0~1390.0まで配信できるはずだと思われます。
■[必須] 不備発生時刻: 常時(調べた限り,同じ秒数で値動きしているなら発生)
■[任意] お使いの環境: Windows10Pro64bit、Python(kabusapi_websocket.py)
■[任意] 不備部分のログ: -

**Comment by yasuyuki-nakazawa** [comment]
当件ですが、情報配信に関しては、kabuステーションが受信しているデータを再配信している形となります。
kabuステーションでは時価情報の間引きが行われている為、当該事象が発生しております
TICKの提供、四本値の提供を取り急ぎ検討いたします。

**Comment by ob2r** [comment]
ご回答ありがとうございます。

現状を把握しました。
今後ともよろしくお願いします。

**Comment by nobuodesu** [comment]
こちらのご検討はその後どうなったでしょうか。
