### ISSUE TITLE
【質問】1分足の高値/安値/終値を取得

### ISSUE THREAD

**Issue by masaki64** [kabucom/kabusapi#168]
kabuステーションAPIで、1分足の高値/安値/終値を取得できますか。
また、kabuステーションAPIで不可能な場合、どのような方法で、1分足（1分での）高値、安値、終値を取得できそうでしょうか。
⇒1分足ごとのチャートを描き、そのチャートをもとに分析したいと考えております。

以上、恐れ入りますが、
宜しくお願い致します。

**Comment by yasuyuki-nakazawa** [comment]
現在、分足での配信は行っておりません
要望としては、分足、日足の要望はあり、検討はしております

**Comment by yasuyuki-nakazawa** [comment]
タイトルを補完させて頂きました。
APIとしては、情報の取得として日中足、日足の拡張は検討しておりますが、kabuステーションにはチャートに表示されている四本値をCSVに出力する機能があります。
チャート上で右クリックをし、「４本値データ出力」をクリックすることで、チャート上の4本値のデータを取得できます。
API経由では現状インターフェースございませんが、分析等の参考になれば幸いです

**Comment by yasuyuki-nakazawa** [comment]
当件は回答済みとしてCloseさせていただきます
