### ISSUE TITLE
【質問】外部端末からのAPI利用について

### ISSUE THREAD

**Issue by kazunari-takeda** [kabucom/kabusapi#169]
お世話になっております。
私はCentOS8で構築したサーバーでPython環境を整備し、Windows10端末で立ち上げているkabuステーションAPIを叩きに行こうとしていたのですが、
httpステータスコード 400 Bad Request
invalid hostname
と返ってきてしまい、うまく行きませんでした。
そこでご質問があります。
kabuステーションAPIの仕様としてlocalhostでしかAPIが利用できないようになっているのでしょうか？
外部からAPIを利用する術はないでしょうか？

以上です。
よろしくお願いいたします。

**Comment by yasuyuki-nakazawa** [comment]
既に他でも質問がありましたが、kabuステーションAPIではkabuステーションが起動している端末以外からの＠
「直接」リクエストを受け付けないようになっております。
ご了承ください。

**Comment by kazunari-takeda** [comment]
ご回答いただきありがとうございます。
既出の質問ということで、失礼いたしました。
kabuステーションを立ち上げている端末からAPIを使用するように設計を変えたいと思います。
ありがとうございました。
