### ISSUE TITLE
【質問】アンプルのエクセルファイルで返済注文時　パラメーター変換エラーがでます

### ISSUE THREAD

**Issue by kabucomapi** [kabucom/kabusapi#17]
サンプルのエクセルファイル（kabuSTATION_API_ORDER_sample.xlsm）で返済注文時　パラメーター変換エラーがでます。
１　現物信用区分を返済を新規に変更して、決済順序、返済建玉指定を空欄にするとオーダーは通ります。
２　売り玉を買い返済するとき　売買区分　買　決済順序を　'日付（古い順）、損益（高い順）　に変更してオーダーすると'{"Code":4001005,"Message":"パラメータ変換エラー - 詳細はkabuSログファイルを確認してください"}とエラーが出ます。
３　さらに２を売買区分　売に変更してオーダーすると'{"Code":1009001,"Message":"建玉が選択されていません。"}とエラーが出ます。

オーダーを通したいのですが何が不具合の原因か不明なため回答をお願いします。

**Comment by hirocha** [comment]
恐れ入ります。私も同様の問題で困っています。
https://github.com/kabucom/kabusapi/issues/50
kabucomapiさん、よろしければ解決された方法を教えていただけませんでしょうか。

**Comment by kabucomapi** [comment]
お返事遅れましたが、私は単に受渡区分の選択を誤っていました。選択項目が多いので、正しい組合せとするのに苦労しました。

**Comment by hirocha** [comment]
おっしゃる項目を含め様々な組み合わせを試みたところ無事に解決しました。
ありがとうございました！

**Comment by yasuyuki-nakazawa** [comment]
現物、信用の新規、返済というパターンで参考となる各パラメータの組み合わせに関して、苦戦されるユーザが多いということもあり、リファレンスとは別途でWiki的なものに記載する等を検討します
