### ISSUE TITLE
【質問】/orders のレスポンスについてお教えください

### ISSUE THREAD

**Issue by takezo1004** [kabucom/kabusapi#170]

**Comment by takezo1004** [comment]
先物のレスポンスですが
0 = {'TimeInForce': 1, 'CashMargin': 2, 'ID': '20201113A02N94668140', 'State': 5,
 'OrderState': 5, 'OrdType': 1, 'RecvTime': '2020-11-13T08:47:56.1432197+09:00', 
'Symbol': '165120019', 'SymbolName': '日経225mini 20/12', 'Exchange': 2,
 'ExchangeName': '大阪日通し', 'Price': 25415.0, 'OrderQty': 2.0, 'CumQty': 2.0,
 'Side': '1', 'AccountType': 12, 'DelivType': 0, 'ExpireDay': 20201113,
返済/新規の区分はDelivType': でしょうか？　DelivType、'OrdType': の詳細をお教えください。

**Comment by yasuyuki-nakazawa** [comment]
こちらはリファレンス記載のとおりとなりますが、新規返済はCashMarginとなります
DelivTypeは受渡し区分、OrdTypeは執行条件となります
詳細はリファレンスの「注文約定照会」を参照ください

**Comment by yasuyuki-nakazawa** [comment]
当件は回答済みとしてCloseさせていただきます
