### ISSUE TITLE
【質問】検証用APIの銘柄登録について

### ISSUE THREAD

**Issue by masaki64** [kabucom/kabusapi#171]
検証用APIを利用した際の、銘柄登録APIについて、レスポンスが以下のように、値が入らず返ってきます。
{'RegistList': []}
検証用では、銘柄登録APIは利用できないのでしょうか。

また、検証用で銘柄の登録ができない場合、
どのようにWebSocketを動作させればよろしいでしょうか。

以上、よろしくお願いします。

**Comment by tsuchinaga** [comment]
#142 に

> 検証用は銘柄登録は空が戻ります。

とありました。

**Comment by yasuyuki-nakazawa** [comment]
tsuchinaga 氏が回答されているとおり、レスポンスは空となります。
検証については、あくまでも関数疎通レベルとお考えいただければと思います。
情報系であれば、実際に本番環境に対してRegistを行い、WebSocketを検証するという方法もあるかと思われます
