### ISSUE TITLE
【質問】kabuステーションの起動は必要ですか？

### ISSUE THREAD

**Issue by KoujiSano** [kabucom/kabusapi#172]
はじめまして。

REST API トークン発行のリファレンスで
kabuステーションのログアウト時などでトークンが無効になるとのことですが
REST APIを利用する際には
常にkabuステーションがログインされた状態で起動してなければならない
という意味でしょうか？

kabuステーション自体が HTTPサーバとなり、localhostに対してREST要求をするということでしょうか。

**Comment by yasuyuki-nakazawa** [comment]
記載のとおりで、kabuステーションが常に起動している必要があります。
kabuステーションがサーバになっているイメージです
