### ISSUE TITLE
【不具合】エクセルマクロ残高照会シートの表題誤り及び決済済建玉が取得される

### ISSUE THREAD

**Issue by poyoji3** [kabucom/kabusapi#173]
■不具合事象(概要)
１.ダウンロードしたサンプルマクロにて残高照会実行したところ、決済済建玉が取得される。

保有銘柄：1321　165120019	（日経225mini 20/12）
ナイトセッションにおいて、165120019（日経225mini 20/12）の反対注文を実行し決済済
決済が済み165120019（日経225mini 20/12）の建玉がなくなったことをkabuステーションにて確認済み。

決済済みの建玉が残高照会にて取得されるのはAPIの仕様でしょうか。

2．サンプルシート「残高照会」関数出力結果表題（M13セル）には「値段」と表記されているが、「残数量」の間違いではないか。

サンプルシート「残高照会」M列に表示されているのが残数量であれば、決済済み165120019（日経225mini 20/12）のM列の表示は0になっています。

上記1．とダブりますが残高照会の関数POSITIONSで得られる値は、決済済み銘柄も取得され、取得された値の内残数量（サンプルシートM列の値）は0になるのはAPIの仕様でしょうか。

※サンプルシート「残高照会シート」13行の表題にはその他にも誤りがあると思われます。
F列　誤：口座種別　正：銘柄コード　その他多数ありますので修正をお願いいたします。

■不備発生時刻　11月18日　01:45　日経225ナイトセッション
■[任意]　Windows10　Excel2019、
サンプルMacro、kabuSTATION_API_function_sample.xlsx
（11月18日　01時過ぎに新規にダウンロードしたもの）

**Comment by cyber-minion** [comment]
決済済み（全返済）の建玉が、kabuステを再起動するまでは、残高照会にて取得されますが、残数量「0」としてレスポンスします。kabuステを再起動した場合は、当該建玉がレスポンスされなくなります。 #124 と同事象かと思いますので、ご参照ください。

表題誤りの件に関しては、サンプルシートを修正させていただきます。混乱させてしまい、申し訳ありません。

**Comment by poyoji3** [comment]
kabuステを再起動するまでは、残数量「0」としてレスポンスされるのが仕様である件、承知いたしました。

サンプルシート修正の件は、ご対応いただけるようでありがとうございます。
