### ISSUE TITLE
【質問】EXCEL VBAでのpush配信の処理について

### ISSUE THREAD

**Issue by youarehappy777** [kabucom/kabusapi#174]
お世話にになります。

質問１．
push配信の度に値を取得していきたいと思い(目的は分足の作成)、
websocket関数を記述したシートにWorksheet_Changeイベントハンドラを記述したのですが、
push配信でセル値が変わってもイベントが上がってこない様でして
期待した動作を実現出来ていません。

websocket関数でイベント抑止していたりしますでしょうか。
あるいはそもそもこの実装だと実現出来ない様なものでしょうか。

質問２．
こちらはAPIの質問とはずれてしまうかもしれませんが、上記が実現出来ない場合、
JavaScript版のwebsocket.jsの様な事をEXCEL VBAで実装する方法がありますでしょうか。
可能であればサンプルプログラムなどあると非常に助かります。

基本的なご質問かもしれませんがお手数ですがよろしくお願いします。

**Comment by yasuyuki-nakazawa** [comment]
＞websocket関数を記述したシートにWorksheet_Changeイベントハンドラを記述し
部分的でもかまいませんので、記載例をいただけると幸甚です

**Comment by youarehappy777** [comment]
ご確認ありがとうございます。
用語が間違っており申し訳ありません。
単にWorksheet_Changeイベントプロシージャです。

実際のコードとは違いますが、WEBSOCKET関数を記載したシートに
以下の様なコードを記載しても、PUSH配信でセル変更されたタイミングで動作しません。

なおWEBSOCKETによるPUSH配信は正常に受信しておりセルの値は逐次変わっています。
また手操作で該当シートのセルの値を変更した場合は該当プロシージャが動作しています。

Private Sub Worksheet_Change(ByVal Target As Range)
MsgBox "変更されました。"
End Sub

**Comment by yasuyuki-nakazawa** [comment]
EXCELに関しての問合せに見受けられます。
アドインのPUSH配信の定義としては、セルに「=WEBSOCKET(銘柄コード,市場,項目名)」という計算式になっています。
計算式の値が変わっても「Change」イベントは発生しません。
計算式の値に変更があった場合は、「Calculate」イベントが発生します。実際にPCでPUSH配信を行い、試したところ「Calculate」が発生しました。
ですが、PUSH配信でいくつも項目を定義しているとその分だけ「Calculate」イベントが発生します。

また、分足を作成したいとのことですが、VBAでは処理的に厳しいものがあると思われます。
以前、他のお客様より、kabuステAPIコミュニティでPythonにてPUSHでデータを受信して、足データを作成するようなサンプルプログラムが紹介されていたと思われますので、
そちらで分足作成を検討された方がよいかと思います。

**Comment by youarehappy777** [comment]
ご回答ありがとうございます。
本件そのままにしており、またAPIそのももの質問ではなくすみません。
「Calculate」イベントを使って一旦実装は出来ていましたが、
そもそもPUSH配信データが間引きされているとの事(#167)と
Tickや4本値配信も検討されているとの事の様ですのでこのアプローチは諦めていました。

ご紹介頂いたPythonのサンプルもPUSH配信を使っている以上は
正しい足を作成出来ていないのではないかと推察されますが、
Pythonでの実装も検討したいと思います。

ありがとうございました。
