### ISSUE TITLE
【質問】PTS市場（チャイエックス、ジャパンネクスト）への注文は出来ますか？

### ISSUE THREAD

**Issue by ST3883** [kabucom/kabusapi#177]

**Comment by yasuyuki-nakazawa** [comment]
PTS]市場への直接発注は現状(11/24時点)で発注チャネル問わず対応していません
SOR機能を有効にしている場合PTS市場に取り次がれることがありますが、kabuステーションAPIではSOR機能をサポートしておりませんのでPTS発注は実施できません
以上のことから、現状はPTS市場への注文はできません

**Comment by yasuyuki-nakazawa** [comment]
当件は回答済みということで、Closeさせていただきます
