### ISSUE TITLE
【要望】CMEとSGXのリアルタイム4本値取得

### ISSUE THREAD

**Issue by gogotorotan** [kabucom/kabusapi#178]
CME（日経平均先物）とSGX（日経平均先物）のリアルタイム4本値は取得可能でしょうか？
リファレンスの先物銘柄コードには、CMEやSGXはありませんでした。
もし取得可能でしたら、銘柄コードを教えて下さい。
もし取得できないのであれば、せめて現在値だけでも取得できるようにしていただけないでしょうか。

**Comment by yasuyuki-nakazawa** [comment]
CME、SGX共に取得はできません。
カブステで出力されていない情報はAPIでは取得することができませんご要望としては理解いたしましたが、現在値段はカブステに関わらず、現在は出力しておりませんので、当件はご希望を実現はできません。
ご了承ください
