### ISSUE TITLE
【不具合】時価情報で時刻があっていないのではありませんか？また価格はどれぐらいの頻度で更新ですか？

### ISSUE THREAD

**Issue by higenobu** [kabucom/kabusapi#180]
■[必須] 不具合事象(概要)
■[必須] 本来想定されるアクションと事象
■[必須] 不備発生時刻（常時の場合は、常時で記載ください)
■[任意] お使いの環境(OS、Excelのバージョン等)、サンプル(Macro、アドインのバージョン）
■[任意] 不備部分のログ

**Comment by yasuyuki-nakazawa** [comment]
時刻が合っていないというのは、配信情報と配信時刻が異なるのでは？という質問でしょうか

**Comment by higenobu** [comment]
おそらく銘柄登録をしないで時価情報をAP経由で入手しようとしたからでしょうか？
配信情報の中にある現在時刻と現在価格の更新が行われていない
という現象がありました。

**Comment by yasuyuki-nakazawa** [comment]
銘柄登録が前提となります。
kabuステーション自体で銘柄リクエストを実施（画面上に対象の銘柄が表示）されている場合は、一部情報が取得される場合がありますが、APIで利用する銘柄に関しては、銘柄登録を前提としております。
銘柄登録を実施のうえ、再確認いただけますでしょうか

**Comment by higenobu** [comment]
その通りです。
ありがとうございます。
