### ISSUE TITLE
【質問】時価情報のAPIはどれぐらいの頻度で更新されていますか？

### ISSUE THREAD

**Issue by higenobu** [kabucom/kabusapi#181]
先物の時価情報のAPIはどれぐらいの頻度で更新されていますか？
１分単位でしょうか？
５分単位でしょうか？
http://localhost/kabusapi/board/{symbol}@{exchange}

**Comment by tsuchinaga** [comment]
リクエストした時点での情報が返ってきているようです  
更新頻度で言えばリアルタイムと言えそうです

**Comment by higenobu** [comment]
APIで３０秒単位でSLEEP(30）でLOOPしてアクセスすると
時価。更新時間ともにずいぶん遅れているように思いますが
いかがでしょうか？

26380.0
2020-11-24T17:32:24-08:00
17:32
26380.0
currentQuote: [26380.0, '17:32']
count 116

26380.0
2020-11-24T17:32:24-08:00
17:32
26380.0
currentQuote: [26380.0, '17:32']
count 117

26380.0
2020-11-24T17:32:24-08:00
17:32
26380.0
currentQuote: [26380.0, '17:32']
count 118

26380.0
2020-11-24T17:32:24-08:00
17:32
26380.0
currentQuote: [26380.0, '17:32']
count 119

26380.0
2020-11-24T17:32:24-08:00
17:32
26380.0
currentQuote: [26380.0, '17:32']
count 120

26380.0
2020-11-24T17:32:24-08:00
17:32
26380.0
currentQuote: [26380.0, '17:32']

**Comment by higenobu** [comment]
for kk in (range(120)):  
    kk+=1
    #ltime=time.strftime('%H:%M')
    #print ('local time: ',ltime)
    #check reverse loss cut
    #***********************debug purpose
    #cprice=[0,25365,'12:30']
    print ("count",kk)
    cprice=get_nk225mini_quote()    
    
    
    currentq=cprice       
    quote=currentq
    print ("currentQuote:",quote)
    qq.append(cprice)
    time.sleep(30)

**Comment by tsuchinaga** [comment]
出されているログが何を意味しているか分かりません  
JSTの実時刻とAPIで返されたCurrentPriceTimeの項目を出すことはできますか？

30sに1回確認したいなどのニーズであればwebsocketを利用されては？

**Comment by tsuchinaga** [comment]
出されているログが何を意味しているか分かりません
JSTの実時刻とAPIで返されたCurrentPriceTimeの項目を出すことはできますか？

**Comment by higenobu** [comment]
ご返事ありがとうございます。
まず、返ってくる値の時価時刻が更新されていません。
また、時価もかなりの遅れが見られます。
それとWEBSOCKETの利用に仕方のサンプルはあるでしょうか？

**Comment by tsuchinaga** [comment]
websocketのサンプルは下記が参考になると思います

https://github.com/kabucom/kabusapi/blob/master/sample/Python/kabusapi_websocket.py

**Comment by higenobu** [comment]
ありがとうございます。
一応、これは動きましたが時価情報を入手する方法はいかがでしょうか？

**Comment by tsuchinaga** [comment]
試しに10s毎に時価情報を取得してみました

nowが現在時刻、CurrentPriceTimeがレスポンスのCurrentPriceTimeですが、更新されていないということはなさそうです。

```
now: 2020-11-26 08:54:04.3542506 +0900 JST m=+0.037027001, CurrentPriceTime: 2020-11-26 08:53:24 +0900 JST
now: 2020-11-26 08:54:14.3584381 +0900 JST m=+10.041214501, CurrentPriceTime: 2020-11-26 08:54:13 +0900 JST
now: 2020-11-26 08:54:24.3600704 +0900 JST m=+20.042846801, CurrentPriceTime: 2020-11-26 08:54:23 +0900 JST
now: 2020-11-26 08:54:34.3683746 +0900 JST m=+30.051151001, CurrentPriceTime: 2020-11-26 08:54:23 +0900 JST
now: 2020-11-26 08:54:44.3740328 +0900 JST m=+40.056809201, CurrentPriceTime: 2020-11-26 08:54:43 +0900 JST
now: 2020-11-26 08:54:54.3761664 +0900 JST m=+50.058942801, CurrentPriceTime: 2020-11-26 08:54:49 +0900 JST
now: 2020-11-26 08:55:04.3774414 +0900 JST m=+60.060217801, CurrentPriceTime: 2020-11-26 08:55:01 +0900 JST
now: 2020-11-26 08:55:14.3795952 +0900 JST m=+70.062371601, CurrentPriceTime: 2020-11-26 08:55:15 +0900 JST
now: 2020-11-26 08:55:24.380718 +0900 JST m=+80.063494401, CurrentPriceTime: 2020-11-26 08:55:15 +0900 JST
```

対象にした銘柄は 165120018 で、市場は2の日通しです。

処理の流れとしては、トークン取得 → 銘柄コード取得 → 銘柄登録 → 時価情報取得をループ です。

**Comment by higenobu** [comment]
先物を登録してWebsocketで入手しみました。
これでは更新されていますね。
これを利用してみます。
ありがとうございました。

**Comment by higenobu** [comment]
すみません。あとひとつ。
時価を取り出してプログラムにパスできないでしょうか？
