### ISSUE TITLE
【質問】逆指値の注文を出したい

### ISSUE THREAD

**Issue by spotthediff** [kabucom/kabusapi#182]
APIで逆指値の注文を出したいのですが可能ですか?
価格が設定した値段になったときに成り行きで買ったりしたいのです

**Comment by tsuchinaga** [comment]
下記に同様の質問への回答がありました

https://github.com/kabucom/kabusapi/issues/67#issuecomment-688032458

**Comment by yasuyuki-nakazawa** [comment]
tsuchinagaさん、回答ありがとうございます。
現状逆指値の要望は多い為、対応予定ではございます
時期感は追って公開させていただきます
