### ISSUE TITLE
【ご質問】信用取引可能数量について

### ISSUE THREAD

**Issue by nobuodesu** [kabucom/kabusapi#183]
一般及び制度信用の売り買い建可能数量をapiを使用して取得する方法はございますでしょうか。

**Comment by yasuyuki-nakazawa** [comment]
現状は信用の取引可能数量を返答するインターフェースはありません。
ご要望が比較的多いため、検討はしておりますが、システム負荷の課題があり、インターフェース拡張まではお時間を頂戴している状況です

**Comment by nobuodesu** [comment]
承知致しました。
