### ISSUE TITLE
【質問】先物プレオープンの配信情報

### ISSUE THREAD

**Issue by nobuodesu** [kabucom/kabusapi#184]
日経平均やトピックスのプレオープンの時間帯8:45以前に配信される価格、数量情報はどのような位置付けでしょうか。
また、FOKで発注するとエラーしますが、他の執行条件であれば約定する可能性があるのでしょうか。約定するのは寄り付きで、それまでは約定成否を確認できないとの認識でよいでしょうか。

**Comment by yasuyuki-nakazawa** [comment]
プレオープニング時間とは取引所が定める寄前の板寄せ時間のことであり、この時間帯は執行条件に関わらず約定が成立しません。
大証J-GATE（大証デリバティブシステム）では8：00～9：00、イブニング・セッションの場合は16：15～16：30がプレ・オープニングの時間帯となります。

**Comment by nobuodesu** [comment]
ありがとうございます。
再度ご質問で恐縮ですが、配信される価格、数量情報はどのような意味合いがあるのでしょうか。

**Comment by yasuyuki-nakazawa** [comment]
プレ・オープニングやプレ・クロージングの時間帯も、ザラ場の時間帯と同様に取引所からの気配情報が配信されます。情報内容に関しては取引所の気配情報仕様に依存いたします。
