### ISSUE TITLE
【質問】WEBSOCKETで入手した価格でAPIを使って発注する方法を教えていただけますか？

### ISSUE THREAD

**Issue by higenobu** [kabucom/kabusapi#185]
websocketを使って登録銘柄の現在価格を表示するのはできましたが、
その価格を使ってAPIで発注する方法はあるでしょうか？
それと一旦、発注したオーダーを２重に発注しない防止策も教えていただけるでしょうか・

**Comment by yasuyuki-nakazawa** [comment]
RESTにて発注リクエストを実行頂く形となります。
株式：sendorder
先物：sendorder/future
オプション：sendorder/option
詳細に関してはAPIのリファレンスを参照ください。　https://kabucom.github.io/kabusapi/reference/index.html#tag/order

発注を２重に行わないようにする防止策に関しては、独自で制御いただくほかないのですが、
発注に関しては、同期型で処理を行い、レスポンスを元に既発注、未発注(異常リターン等)を管理していく等が考えられます。

**Comment by higenobu** [comment]
WebsocketのLoopの中で、価格を判定して、POSTで発注するという方法ですね。
その場合の発注後にLoopから出る方法がわかりません。
発注のStatusは、照会のAPIを使うということですね。

**Comment by yasuyuki-nakazawa** [comment]
WEB Socketのループというのが、何をループしているのかが明確でないので、コメントしづらいところです
Pushでデータ情報を受けた後に実施するループ処理というのは、どのようなものでしょうか？
Loopの抜け方等に関しては開発言語に依存してしまう為、こちらでの展開は控えさせて頂きます。

**Comment by higenobu** [comment]
追加してみました。
以下のようなコードをこのサイトから参考にして使ってみました。
これを実行すると、Ctr＿Cで停止するまで時価情報を表示できますが、
表示の部分で、条件をいれて発注させても、このループからは抜けられません。

async def stream():
    uri = 'ws://localhost:18080/kabusapi/websocket'
    

    async with websockets.connect(uri, ping_timeout=None) as ws:
        while not ws.closed:
            response = await ws.recv()
            board = json.loads(response)
            
            quote=str(board['CurrentPrice'])
            print (quote)
            #qq.append(quote)
            
            #write_q(str(board['CurrentPrice']))
        
            
loop = asyncio.get_event_loop()
loop.create_task(stream())

try:
    loop.run_forever()
except KeyboardInterrupt:

    exit()

**Comment by yasuyuki-nakazawa** [comment]
>このループからは抜けられません

記載のコードですと、ws.closed されるまでは無限ループになりますよね。
ループの抜けに関しては諸方法あるかとはおもいますが、breakやWhile後の条件にループ抜けいれる等検討ください。

**Comment by higenobu** [comment]
Whileの中で条件式がTrueになれば、発注して、その後にLOOPからでる
というしくみが欲しいです。

**Comment by yasuyuki-nakazawa** [comment]
上記は個々で作成頂くプログラム上での設計ならびに動きのお話と思慮いたします。
上記を条件に入れてコーディングいただくことで対応可能かとおもわれますが、どの点が課題となっておりますでしょうか

**Comment by higenobu** [comment]
async def stream():
    uri = 'ws://localhost:18080/kabusapi/websocket'
    
    quit=0
    async with websockets.connect(uri, ping_timeout=None) as ws:
        while (not ws.closed and quit==0) :
            response = await ws.recv()
            board = json.loads(response)
            
            quote=str(board['CurrentPrice'])
            print (quote)
            if (quote>'26670'):
                print ("Closing and exit")
                quit=1
               
loop = asyncio.get_event_loop()
loop.create_task(stream())

try:
    loop.run_forever()
except KeyboardInterrupt:
    exit()

このWhileループの中で、価格が２６６７０を越えたときに、返済オーダーを出したいときに
Print文の前で返済オーダーのAPIを使った関数を呼べばいいのでしょうか？
それと、このWhileループから出ても、
 loop.run_forever()
これがあるのでCtr-Cをたたかないとループからぬけない
何か方法はあるでしょうか？

**Comment by yasuyuki-nakazawa** [comment]
サンプルはあくまでもサンプルですので、自由に変更いただければと存じます。
不要なものは削除、変更いただき、ループ後に終了するように記載するだけに思えます
返済を行いたい場合という質問に関しては、値段分岐の後に発注リクエストを行うという認識でよろしいと考えます。

**Comment by higenobu** [comment]
ご指導ありがとうございます。
いろいろ試してみます。
