### ISSUE TITLE
【質問】ご担当者様へ　先物の40012 リクエスト不正のエラー　先物のフル板情報　先物のT&S　先物の残高照会情報　について

### ISSUE THREAD

**Issue by seattlesbest** [kabucom/kabusapi#186]
ご担当者様　先物のAPI非常に素晴らしい試みと存じます、これからもさらなる開発のほどを期待しまして、メインは他社証券会社利用者でしたが、この開発が面白そうだったため御社利用のため、暫時戻ってきております。
ただ現時点では、岡三のエクセルアドインなどの方が洗練されており、今からという印象も受けますが、まずは色々と試させて頂きたいと存じます。
さて、下記ご質問にご回答頂ければ幸いです。

Q1:pythonのkabusapi_symbolname_future.py
エクセルアドイン　共に先物(オプションも)銘柄取得、40012 リクエスト不正のエラーが返ってきます。
kabusapi_board.pyの方は日本製鉄5401が正しくjsonで返るので、認証周りは通っていると思うのですが、
先物、オプションがエラーを返す理由がわかりません。
何か原因がございますでしょうか？
サンプルコードからapikey以外は一切変更しておりません。
またエクセルの関数は指示通りに記載しております。
=SYMBOLNAME.FUTURE(C8,D8)
NK225 202012
銘柄コード | 銘柄名称
4001012 | リクエスト不正

Q2:板情報取得はkabuステーション上ではプレミアム会員向けにフル板が見れると思いますが、
API経由でも同様に取得できますでしょうか？

Q3:Q2に付随してkabucomステーション上の板の隣にあるT&SはAPI経由で取得できますでしょうか？

Q4:残高照会、注文照会などは先物も同様に取得できますでしょうか？（試した所どうもQ1同様取得できないようで。。。）

**Comment by yasuyuki-nakazawa** [comment]
部分的に一旦回答いたします
Q2：現状フル板情報は配信しておりませんが、インターフェースの追加検討は実施中です
Q3：T&SもQ2同様に対応検討中です。現状は未公開です
Q4：残高照会、注約照会ともに取得可能です

Q1に関して、該当のエラーが発生するパターンに関しては、確認のうえ、展開させて頂きます

**Comment by yasuyuki-nakazawa** [comment]
Q1ですが、現在ご利用のkabuステーションのVerをご確認いただけますか。
最新になっていない（kabuステーションの先物OPが対応されていないバージョン）で上記が発生しておりました。

**Comment by seattlesbest** [comment]
最新のものかと思いますが、5.12.1.0になります。対応しているバージョンでしょうか？

**Comment by yasuyuki-nakazawa** [comment]
kabuステーションのバージョンは5.12.3.0となります
先物オプションについては、5.12.2からサポートしております

**Comment by yasuyuki-nakazawa** [comment]
ご利用バージョン相違ということで、当件はクローズさせて頂きます
