### ISSUE TITLE
【要望】sendorderとordersにstrategy名・コメント等を付与したい

### ISSUE THREAD

**Issue by lstm500** [kabucom/kabusapi#187]
要望
・sendorderで注文を発注する際に、入力項目（"Password": "xxxxxx",～"ExpireDay": 20200903　：2020/11/29現在仕様）に"StragetyName": "AAA"のような戦略名・コメント（省略可）を付与し、
・ordersで問い合わせた際に、contentの中にStragegyNameの項目を入れてほしい

メリット
・同一銘柄を別戦略で発注した際に、ordersからcontentを取得するだけでどの戦略の注文なのかを判別できること
　・これにより戦略毎に銘柄を分散させることなく多数の戦略の管理ができ、多数戦略を採用しやすくなるので売買代金の上昇に寄与できると思います。

ぜひよろしくお願いします。
割と発注端末ではよくある機能だと思います。

**Comment by yasuyuki-nakazawa** [comment]
備考欄的なものということですね。
現状のkabuステーションにも備考欄機能が注文約定照会、残高照会ともに保有していない為、即対応はむずかしいところですが、検討させて頂きます

**Comment by lstm500** [comment]
まさにその通りです。
どうぞよろしくお願いします。

**Comment by yasuyuki-nakazawa** [comment]
当件ですが、検討させて頂きましたが、kabuステーションAPIはkabuステーションに保持している情報を連携する仕様の為、
ユーザの方が任意で設定した備考文字列を保持することができません。
注文システムとして大きな修正を伴うことから、当要望に関しては申し訳ございませんが、見送りさせてください。

なお、注文番号は一意となっておりますので、こちらをキーに備考文字を各自にて管理いただくことで対応いただければと存じます。

**Comment by lstm500** [comment]
こちらご検討ありがとうございました！
