### ISSUE TITLE
【質問】信用取引の注文から約定までの時間

### ISSUE THREAD

**Issue by nobuodesu** [kabucom/kabusapi#188]
制度信用取引で指値注文した時、現物に比べ約定までに時間がかかるのはなぜでしょうか。

**Comment by yasuyuki-nakazawa** [comment]
APIと注文システムの仕組み上、現物と信用の発注自体にレイテンシ差はございません。
板乗りにおいても、現物と信用による差は特段なく記載いただいた制度信用の指値が現物より時間がかかるということが通常化しているということはございません。

**Comment by nobuodesu** [comment]
ありがとうございます。
承知致しました。
