### ISSUE TITLE
【質問】注文約定照会　state 5について

### ISSUE THREAD

**Issue by takezo1004** [kabucom/kabusapi#189]
注文約定照会　state 5　終了（発注エラー・取消済・全約定・失効・期限切れ）とありますが
各項目をチェックする方法を教えてください。'RecType'で確認できるのですか？

**Comment by yasuyuki-nakazawa** [comment]
RecTypeで各明細の注文状態を確認できます。

**Comment by yasuyuki-nakazawa** [comment]
回答済みとしてクローズさせて頂きます
