### ISSUE TITLE
【質問】Excel ORDER_sampleファイルのMarginTradingでの返済建玉指定について

### ISSUE THREAD

**Issue by kabucomapi** [kabucom/kabusapi#19]
kabuSTATION_API_ORDER_sample.xlsmに下記コードについてですが、 ClosePositionListで一括注文するように見受けられますが、単一発注しかできません。ClosePositionList(i) の配列を作る意味を教えていただけないでしょうか？
よろしくお願いします。

  If ClosePositionCount > 0 Then
    Dim row As Integer
    row = RowNo
    For i = 0 To (ClosePositionCount - 1)
      Dim dic As Object
      Set dic = CreateObject("Scripting.Dictionary")
      dic.Add "HoldID", ActiveSheet.Cells(row, 信用_返済建玉ID)
      dic.Add "Qty", ActiveSheet.Cells(row, 信用_返済建玉数量)
      Set ClosePositionList(i) = dic
      row = row + 1
    Next

param("ClosePositions") = ClosePositionList

**Comment by yasuyuki-nakazawa** [comment]
こちら、複数返済注文が実施できることを確認しております。
当件は未解決継続でしょうか

**Comment by kabucomapi** [comment]
解決に至っておりませんが、シートから当該注文することはなくなりましましたので、クローズしていただいて結構です。
ありがとうございました。
