### ISSUE TITLE
【不具合】エラー 100031 「預り区分」をご確認ください、について。

### ISSUE THREAD

**Issue by sakatsusan** [kabucom/kabusapi#190]
ご担当殿

従来、現物買い発注では、 「資産区分」として  02保護で発注しておりました。
ストリーム(3071)の現物買い発注において、
 「資産区分」として  02保護でと発注できないのですが、どのように発注するものなのでしょうか。

また、資産区分の意味を説明するページを案内いただけると幸いです。

ErrorCode=100031 「預り区分」をご確認ください

と返答されます。

**Comment by yasuyuki-nakazawa** [comment]
現在、信用口座を開設済みではないでしょうか？
その際は信用代用（＝AA）をご指定ください。

当件はわかりにくい為、リファレンスに補完させて頂きます。

**Comment by sakatsusan** [comment]
信用口座を開設済みです。
ストリーム(3071)の現物買いは、AAで現物買いできるようになったのですが、
今度は今まで出来た、3113 Ｏａｋ　キャピタル
にて、

ErrorCode=100267 代用での買付が制限されている銘柄です。「預り区分」をご確認ください。

と出ます。
どうすればよろしいでしょうか？
銘柄ごとに一律に判定することは私側ではできないと思われます。
株ステーションではそのような指定なしに買えるわけですが。

**Comment by yasuyuki-nakazawa** [comment]
3113の銘柄は、代用不適格銘柄に位置づけられているため、この銘柄の場合は保護での買付が必要となります。
ご指摘のとおりに、銘柄によって預り区分を意識する必要がないような改善は現在検討させていただいております。
あわせて、各銘柄の規制情報を取得したいという要望もあり、当該２点については機能追加、改善を検討しておることは展開いたします。

**Comment by yasuyuki-nakazawa** [comment]
当件は回答済みとして、クローズさせて頂きます
