### ISSUE TITLE
【質問】成行の発注直後の約定照会について

### ISSUE THREAD

**Issue by higenobu** [kabucom/kabusapi#192]
成行の先物発注直後にHoldIDを入手して、そのHoldIDを使って返済オーダーのパラメーターにはめ込みたいのですが
注文・薬剤照会のAPIの結果からHoldIDを取り出すのにいい方法はあるでしょうか？
RecvTimeの最新のものを抽出すればいいのでしょうか？
それと、約定したときの価格を入手するのは、このAPIのPriceではありませんね？

**Comment by yasuyuki-nakazawa** [comment]
まず、ご質問に対して回答いたします
約定価格を取得する場合は、注約照会の明細データ（Detail）でRecType=8（約定）のデータを抽出し、そのなかのPriceが約定価格となります
返済に建玉指定をしたいということであれば、記載の手順を踏んでいただく必要がございます。
ただし、現在（１２月予定）で注約照会と残高照会のフィルタリング機能のリリースを検討しております。
その機能が実装されますと、指定時間以降のデータを抽出することもできますので、ご要望のアクションが実現しやすくなると思われます。

**Comment by higenobu** [comment]
明細データに気づきませんでした。
ありがとうございます。
建玉指定のときのHoldIDというのは、この詳細データにある
ExecutionID
のことでしょうか？
それとも、
約定照会の返値のトップにある注文番号のことでしょうか？

**Comment by nobuodesu** [comment]
お役に立てるかわかりませんがコメントします。
ポジション確認後IDを取得するコードを書いたので共有します。
サンプルコードにあるpositionsの中にCloseOrdersを埋め込む感じです。

import urllib.request
import json
import pprint

url = 'http://localhost:18080/kabusapi/positions'
params = { 'product': 0, }
req = urllib.request.Request('{}?{}'.format(url, urllib.parse.urlencode(params)), method='GET')
req.add_header('Content-Type', 'application/json')
req.add_header('X-API-KEY', xxxxx)

try:
    with urllib.request.urlopen(req) as res:
        print(res.status, res.reason)
        for header in res.getheaders():
            print(header)
        print()
        content = json.loads(res.read())
        
        x1 = 1
        x2 = 1 
        x3 = 1
        x4 = 1 
        
        for i in content:
        
            if content[i]["Symbol"] == "xxxx":
                x1 = content[i]["LeavesQty"]
                x2 = content[i]["ExecutionID"] 

            if content[i]["Symbol"] == "xxxx":
                x3 = content[i]["LeavesQty"] 
                x4 = content[i]["ExecutionID"] 

この後に返済注文コマンドを書いてx1～x4で建玉を指定すれば、返済注文できるかと思います。
ただこの方法だとExecutionIDが複数ある場合は機能しないので約定数量残高のみを抽出してサンプルコードにあるClosePositionOrder形式で注文を出すことにしました。
上記コメントにある発注明細を参照した方がより確実ですね。
ただ約定しているかが明確ではないので、約残を確認するようにしております。

**Comment by higenobu** [comment]
約定照会の結果から、本日の約定データを抽出するために関数を試作してみました。
この関数を呼ぶと、Listが戻ります。
ご参考まで。
def syokai(tkey,jdate):

    url = 'http://localhost:18080/kabusapi/orders'
    skai=[]
    params = { 'product': 3, }
    req = urllib.request.Request('{}?{}'.format(url, urllib.parse.urlencode(params)), method='GET')
    req.add_header('Content-Type', 'application/json')
    req.add_header('X-API-KEY', tkey)

    try:
        with urllib.request.urlopen(req) as res:
        #print(res.status, res.reason)
            for header in res.getheaders():
                pass
            #print(header)
        #print()
            content = json.loads(res.read())
        #pprint.pprint(content)
            for i in range(len(content)):
                sakiid=content[i]['ID']
                sakistate=content[i]['State']
                sakiordtype=content[i]['OrdType']
                sakiprice=content[i]['Price']
                sakiside=content[i]['Side']
                cm=content[i]['CashMargin']
                sakiq=content[i]['OrderQty']
                sakirtime=content[i]['RecvTime']
                detail=content[i]['Details']
            
                #print (detail)
                for k in range(len(detail)):
                    edate=detail[k]['ExecutionDay']
                    print ("edate:",edate)
                    eqty=detail[k]['Qty']
                    eid=detail[k]['ExecutionID']
                    eprice=detail[k]['Price']
                    if (detail[k]['RecType']==8 and edate==jdate):
                        print (sakiid,sakistate,sakiordtype,sakiprice,sakiside,sakiq,sakirtime,cm,eid,edate,eprice,eqty)
                        skai.append([sakiid,sakistate,sakiordtype,sakiprice,sakiside,sakiq,sakirtime,cm,eid,edate,eprice,eqty])                
                
                    
            
                

                
            result=skai
        

        return result

    except urllib.error.HTTPError as e:
        print(e)
        content = json.loads(e.read())
        pprint.pprint(content)
    except Exception as e:
        print(e)

**Comment by higenobu** [comment]
指定する返済建玉IDというのは、
約定照会のdetail[k]['ExecutionID']
のことでしょうか？
それと、フォーマット形式エラーにひっかかりますが、
正しいフォーマットの例を教えていただけませんか？

**Comment by yasuyuki-nakazawa** [comment]
返済建玉IDは記載いただいたとおりです。
フォーマット形式エラーということですが、エラーのリターンコードはなんでしょうか？
フォーマット等は上述頂いているIDをそのまま設定する形となります

**Comment by yasuyuki-nakazawa** [comment]
こちら、解決しておりますでしょうか？

**Comment by higenobu** [comment]
ありがとうございます。解決しました。

2021年1月28日(木) 3:37 yasuyuki-nakazawa <notifications@github.com>:
