### ISSUE TITLE
【要望】信用取引規制等

### ISSUE THREAD

**Issue by utech-lab** [kabucom/kabusapi#193]
幾つか要望があります。

(1) 信用取引規制（サイトでは取引制限銘柄と表記されてる）を取得できるようにしてほしいです

(2) /kabusapi/orders及び/kabusapi/positionsで返されるレスポンスデータに種別(現物/信用/先物/OP)を追加して欲しいです
　関連してordersの説明でCashMarginとMarginTradeTypeには「※信用の場合のみ」の記載が必要ではないですか？

(3) /kabusapi/ordersで返されるデータが詳細過ぎると思います。サイトの「資産管理」－「注文約定照会」－「信用取引」で表示される程度に纏めて欲しいです。例えば不成注文を取り消した場合などOrdType=4になってるのは1つのDetailsの要素だけで他は違う値になっているので正確に把握するのは難しいです

(4) 要望と言うほどではないですが、REST API リファレンスで認証 トークン反抗の右側には「POST /token」と表示されていますが、なんとなくHTTPプロトコルを想起させるので「POST /kabusapi/token」の方が良いのではないでしょうか。また、その下には
Server URL
http://localhost/kabusapi/token
と書かれていますが、これは
Server URL
http://localhost:18080/kabusapi/token
にした方が良いと思います。

(5) APIのバージョンを取得できるようにしてほしいです。

以上、宜しくお願い致します

**Comment by yasuyuki-nakazawa** [comment]
各ご要望に関しまして、一旦ご返答させていただきます
（１）信用取引規制について
　取引規制を含めた、各種規制関連情報に関しては対応検討しております
（２）レスポンスデータに種別(現物/信用/先物/OP)を。
　こちら、注約照会のフィルタリング機能追加を予定しており、それに合わせて区分の追加を予定しています
（３）/kabusapi/ordersで返されるデータが詳細過ぎる
　現状のkabuステーションAPIはkabuステーションが保持している情報を外部連携するというコンセプトとなっており、注文の状態ごとに注文詳細情報を情報管理している関係上、まとめて連携ということを想定しておりません。
　お手数をおかけして申し訳ございませんが、当件はご了承くださいませ
（４）リファレンスの記載に関して
　「POST /kabusapi/token」は確かに、そちらのほうが理解しやすいということで了解いたしました。
　サーバーURLに関しては、本番と検証環境でポートが異なりますので、敢えて記載から外させて頂いております。
（５）バージョンの取得。検討いたします。
　　　ちなみにですが、バージョンの利用方法はどういう場合を想定されているか教示いただけると、付加情報等も含めて検討材料になります。

**Comment by utech-lab** [comment]
お世話になります
(1)～(4)について了解しました

(5)のバージョンの利用方法は、意図したバージョンでは無い場合発注等の動作を停止して、自作アプリの修正の有無に関係なく一通りテストする必要があると考えています。
可能ならば/kabusapi/tokenのパラメータでAPIPasswordと共にバージョンを与えてそのバージョンがサポート対象ならばkabuステーション側がそのバージョンの挙動をして頂けると助かります。

**Comment by cyber-minion** [comment]
下記にて対応済ですので、クローズさせていただきます。
（1）#305 
（2）#202 
（4）リファレンス修正済
（5） #305
