### ISSUE TITLE
【質問】レイテンシーと同時注文について

### ISSUE THREAD

**Issue by nobuodesu** [kabucom/kabusapi#195]
先物の同時注文しております。APIで配信された価格が一定の条件を満たした直後に成行注文していますが、当該価格条件どおりに約定しません。
同時に注文した2つ目の注文が条件を満たさない状況です。
2つ目の発注所要時間が1つ目の半分程度であっても、更新日時が同時か1秒後になっています。
こうした状況を踏まえると、RAIDENでは、任意の口座から同時注文をした場合、1つ目の注文を処理してから2つ目の注文の処理をおこなうという理解でよろしいでしょうか。
任意の口座からの同時注文は並列処理されない、他の口座からまた別の注文が有れば、複数の口座間では並列処理されるという理解でよろしいでしょうか。
厳密には同時注文は出来ず、複数のsendorderをしなければならないことは従前質問をさせていただいており、理解しております。ここでの同時注文は連続した複数の注文という趣旨です。
よろしくお願いします。

**Comment by yasuyuki-nakazawa** [comment]
同一口座の場合は、並列処理はされません。
記載のとおりで、他口座間では並列処理されています。

**Comment by nobuodesu** [comment]
ありがとうございます。
承知しました。

**Comment by yasuyuki-nakazawa** [comment]
当件はクローズさせて頂きます
