### ISSUE TITLE
【質問】WebSocket のConnectionErrorについて（connectionclosederror: code = 1006）

### ISSUE THREAD

**Issue by masaki64** [kabucom/kabusapi#196]
お世話になっております。

WebSocket にて、20銘柄を以下のように
取得、取得した情報をDBに登録しております。

毎日9時より、起動させているのですが、
その場合、取引が多くなる9時1分～3分頃に「connectionclosederror: code = 1006」となり、処理が落ちてしまいます。

WebSocket で取得した情報をもとに、1分足や、BBを作成し、
可能な限り、リアルタイムで購入判断/購入を行いたいと思っており、上記を解決したく思っております。

原因や、安定的に動かすための解決方法について、ご存じの方、ご教示いただきたいです。。
以上、宜しくお願い致します。

【動かしたロジック】
async def stream():
  uri = 'ws://localhost:18080/kabusapi/websocket'

  async with websockets.connect(uri, ping_timeout=None) as ws:
    while not ws.closed:
      response = await ws.recv()
      board = json.loads(response)
      
      if (board['CurrentPrice'] is None):
          pass
      else:
          
          with closing(sqlite3.connect(dbname)) as connection:
            cursor = connection.cursor()
     
            # データ重複チェックをし、重複しないデータであれば挿入
           
            ins = 'INSERT INTO symbol_data VALUES (?,?,?,?,?)'
            ins_data = (board['Symbol'],
                        board['CurrentPrice'],
                        board['CurrentPriceTime'],
                        board['TradingVolume'],
                        board['TradingVolumeTime'],)
            cursor.execute(ins, ins_data)
            connection.commit()
            connection.close()
    
if __name__ == '__main__':

    loop = asyncio.get_event_loop()
    loop.create_task(stream())
    try:
      loop.run_forever()
      
    except KeyboardInterrupt:
        exit()

**Comment by shirasublue** [comment]
```connectionclosederror: code = 1006``` そのものはping timeoutエラーのようですが、それと関係なく
配信に対してプログラム側の処理が追いついていないか、ファイルロックの関係で落ちていると思われます。

asyncio は非同期処理なので、1つのファイル（今回でいうsqlite3のデータベースファイル）に
対する処理をその中でおこなうべきではありません。

自分が提案する解決方法は2つ、

1. sqlite3でなく、複数からアクセスされることを前提としたデータベースを使用する。
（例: redis, mongodbなど）

2. 配信データごとにファイルを書き出してしまう

自分の場合は2を採用しています。

https://qiita.com/shirasublue/items/f51986f39dd8a3bf8310

タイムスタンプをファイル名にして書き出しを行っています。
```
@api.websocket
def recieve(msg):
    symbol = msg['Symbol']
    path = pkl_path + '/' + date + '/' + symbol
    ts = str(datetime.now().timestamp())

    if not os.path.exists(path):
        os.makedirs(path)
    with open(path + '/' + ts, 'wb') as f:
        pickle.dump(msg, f)
```

以上、参考までにご検討ください。

**Comment by masaki64** [comment]
@shirasublue 

shirasublue 様
ご教示くださいり、ありがとうございます！（ちなみに、記事もいつも拝見しております。参考にさせていただき、ありがとうございます！）

頂いた解決策の「①MongoDbの利用」を採用し、構築を行ってみましたが、
「WebSocketは起動して、値を取得しているが、DBには登録されていない」状態になってしまいました。
➡起動してから、1分くらいはデータを格納できておりましたが、その後、データが登録されておらず。。（WebSocketは動作し、値を取得できてはいました）

もし原因やアイデアがあれば、ご教示いただけないでしょうか。。
ご多用のところ、恐れ入ります。、お願い致します。。。

**Comment by shirasublue** [comment]
記事の参照、ありがとうございます。

実際のコード、エラーメッセージそのもの、また実行環境の情報が無いと、具体的な原因の特定は難しいです。

もしデータ重複チェックをPython側でされているのでしたら、
MongoDBに一意制約を課してデータベース側に処理を任せてしまうといいかもしれません。

_MongoDB の unique index 整理
https://qiita.com/risou/items/1ccdced87547a73cffc1_

**Comment by shirasublue** [comment]
サンプルとして配信データ保存スクリプトとグラフ化スクリプトを書いたので、よろしければ参考にしてください。

kabuステーション®API - PUSH APIから情報を取得・保存し、表示する
https://qiita.com/shirasublue/items/9038b187ef465019d31c

**Comment by yasuyuki-nakazawa** [comment]
当方でも検証してみました。
50銘柄のリクエストを行ったうえで、情報を取得した後に、DBアクセスを含んだ諸処理を追加し、シングルスレッドで稼動させた場合に同事象が発生。
時価情報取得と諸処理を別スレッドで実行することで解消したことから、処理がボトルネックになり、切断が走った可能性があるとみています。
こちら、ご確認いただけますでしょうか

**Comment by taro-jpg** [comment]
nakazawa様
以前投稿したものですが、同様に20銘柄ほどに落としたところ午後3時まで動きました。
参考までに、直情報取得と諸処理を別スレッドで実行したコードのサンプルをご提供いただけないでしょうか？

**Comment by yasuyuki-nakazawa** [comment]
taro-jpg 様
諸都合により、こちらにコードを張ることはできませんが実施していることは下記です
２つのスレッドをたてて、①で情報受信、②で処理実行をしています。
こうすることで、情報処理を取得と切り分け、非同期にて処理しております。
①情報取得スレッド
　情報の取得　→　メッセージキューにて処理スレッドに情報送信
②情報処理スレッド
　①のメッセージをキューより取得、情報をデータベースに格納

**Comment by masaki64** [comment]
@shirasublue 
お世話になっております。
>サンプルとして配信データ保存スクリプトとグラフ化スクリプトを書いたので、よろしければ参考にしてください。
有難うございます。Mongoが適していない場合、採用させて頂きます。助かります！！

＞実際のコード、エラーメッセージそのもの、また実行環境の情報が無いと、具体的な原因の特定は難しいです。
失礼しました。MongoDBを利用して、Threadで取得すると、記載されていたエラーは解消されているようです、失礼しました。
以下のようなコードになります。（貼り付けで失礼します）

class Mongo():

     def __init__(self,obj):
         self.clint = MongoClient()
         self.db = self.clint['symbol_data']
         self.obj = obj
         self.collection = self.db.get_collection(self.obj['Symbol'])
         #self.collection = self.db.get_collection('Symbol')

     def add_one(self):
        timedate = self.obj['CurrentPriceTime']
        #print(timedate + "&&" + timedate[0:16])
        
       
        #---データ挿入---
        post = {
            'timeId': timedate[0:16],
            'Symbol': self.obj['Symbol'],
            'CurrentPrice': self.obj['CurrentPrice'],
            'CurrentPriceTime': self.obj['CurrentPriceTime'],
            'TradingVolume': self.obj['TradingVolume'],
            'TradingVolumeTime': self.obj['TradingVolumeTime']
        }
        
        return self.collection.insert_one(post)
    
     def find_one(self, projection=None,filter=None, sort=None):
        return self.collection.find_one(projection=projection,filter=filter,sort=sort)

     def find(self, projection=None,filter=None, sort=None):
        return self.collection.find(projection=projection,filter=filter,sort=sort)
    
     def count_documents(self, filter=None):
        return self.collection.count_documents(filter)

def func1(board):
    print(board['Symbol'])
    mongo = Mongo(board)
    mongo.add_one()


async def stream():
  uri = 'ws://localhost:18080/kabusapi/websocket'
  logger = logging.getLogger('websockets')
  logger.setLevel(logging.INFO)
  logger.addHandler(logging.StreamHandler())

  async with websockets.connect(uri, ping_timeout=None) as ws:
    while not ws.closed:
        try:
          response = await ws.recv()
          board = json.loads(response)

          if board['CurrentPrice'] is None:
          #if (numpy.isnan()):
            pass
          else:
            try:
                t1 = threading.Thread(target=func1, args=([board]))
                #t1 = threading.Thread(target=func1, args=([ins_data]))
                t1.start()
            except Exception as e:
              logger.exception(f'{e}')
        except websockets.exceptions.ConnectionClosedError:
          ws.close()


while True:
    loop = asyncio.get_event_loop()
    loop.create_task(stream())
    try:
        #logger.info("実行")
        loop.run_forever()
    except KeyboardInterrupt:
        exit()
    
    time.sleep(1)

**Comment by masaki64** [comment]
@yasuyuki-nakazawa 
有難うございます。問題解決の参考とさせていただきました！
ちなみに、DBは何を利用されていたのでしょうか。

**Comment by yasuyuki-nakazawa** [comment]
@masaki64 
DBはMySQLです

**Comment by shirasublue** [comment]
@masaki64 

提示していただいたコードを1時間ほど動かしましたが、
私の環境では問題なく動作します。
TOPIX Core30を含む35銘柄を捌いています。

MongoDB バージョン 4.4.2

CPU: AMD Ryzen 5 2600X Six-Core Processor
メモリ: 16GB
ストレージ: SSD

**Comment by masaki64** [comment]
@shirasublue 
検証くださり、有難うございます。
私の環境でも、9時～9時6分以外の時間帯は、問題なく動作しているのですが、
市場が開いてからの5~10分間は、動作が落ちてしまいます。（取引数が多いからですかね）

メモリ等の情報、有難うございます。
もしかすると、４ＣＰＵ、＄Ｃｏｒｅだと、厳しいんですかね。（パフォーマンスモニタでは、余裕はありそうでしたが）

ちなみに、shirasublue 様は、WebSocket の取得データから1分足を作成されました？
もし、1分足を作成されていた場合、1分足の数値は、実際のデータと数値（始値など）合いましたか。。
⇒（例）14：00の１分足データを14:00~14:59で取得したWebSocket のデータを対象に作成しているのですが、値が合わない場合があり。。

以上、ご多用中、恐れ入りますが、ご確認お願い致します。

**Comment by shirasublue** [comment]
確かに、kabuステーションのチャートから4本値データ出力した結果と、
保存したデータのCurrentPriceから生成した1分足を比較してみましたが、一部合いませんね。
CalcPriceはむしろ悪化しました。参考に画像を添付します。

![compare](https://user-images.githubusercontent.com/70629373/102729709-3129f500-4375-11eb-8aa5-02581331b86a.png)

https://github.com/kabucom/kabusapi/issues/196#issuecomment-744151321
私自身の方法を用いて保存していますが、こちらでは35銘柄を朝の時間帯でも捌き切っているように見えます。

記事のコードを一部`CurrentPrice`系に変更、また冒頭、末尾に以下のコードを追記し生成しています。
```
from datetime import datetime, timedelta, timezone
～
candle_df = tick_df['price'].resample('1Min').ohlc()

start = datetime(2020, 12, 21, 9, tzinfo=JST)
end = datetime(2020, 12, 21, 10, tzinfo=JST)

candle_df[start:end].to_csv('1Min-ohlc.csv')
```

また、@masaki64 さんのコードの確認は websocket 有効接続本数が1本の関係でこれ以上は私の方では難しいです。
参考までによろしくお願いいたします。

**Comment by yasuyuki-nakazawa** [comment]
kabuステーション自体のPush情報は間引き配信されております。
3月を目処にTICK情報の配信を予定しております。こちらは間引きなく、全TICKをリアルタイムで取得することを想定しています。
このタイミングで、分足データの配信インターフェースも追加できればと思っております。

**Comment by masaki64** [comment]
@shirasublue 
お世話になっております。
＞、@masaki64 さんのコードの確認は websocket 有効接続本数が1本の関係でこれ以上は私の方では難しいです。
参考までによろしくお願いいたします。

今更で申し訳ございません。上記の意味について　ご教示頂きたいです。
WebSocket の有効接続数を2本以上にするのは、どのように作成すればよろしいでしょうか。

すみません。。教えていただければ嬉しいです。。

**Comment by shirasublue** [comment]
@masaki64
KabuステーションAPI側の関係で、PUSH配信のWebsocketは最新の1コネクションのみ有効になるという認識です。

さかのぼってTickデータが取得できればいいのですが、現状不可能です。
データベースの欠損を極力避けるため、私の方では実装の検証が難しいです。

**Comment by masaki64** [comment]
@shirasublue 
ご返答、有難うございます。
すみません、こちら勘違いしておりました。。
カブーステーションの仕様について、おしゃっていた点、理解できました。
色々教えて頂き、ありがとうございました❗️

**Comment by yasuyuki-nakazawa** [comment]
こちら、クローズさせていただきます
