### ISSUE TITLE
【質問】WebSocket の「CurrentPriceTime」と「TradingVolumeTime」について

### ISSUE THREAD

**Issue by masaki64** [kabucom/kabusapi#198]
WebSocket にてJsonを取得する際に、「CurrentPriceTime」と「TradingVolumeTime」の時間がずれる可能性はありますでしょうか。

**Comment by yasuyuki-nakazawa** [comment]
基本的にはズレはない認識ですが、確認させて頂きます。
商品は株式でしょうか？

**Comment by masaki64** [comment]
有難うございます。
はい、株式です。

**Comment by yasuyuki-nakazawa** [comment]
こちら確認しましたが、特段ズレ等はございません

**Comment by kabusukebe** [comment]
現値と同値で売買が成立した場合は `TradingVolumeTime` だけが変動するのではないでしょうか？

**Comment by yasuyuki-nakazawa** [comment]
@kabusukebe 
こちら、確認しましたが、記載の場合でもTradingVoulumeTimeも更新されます

**Comment by kabusukebe** [comment]
同値で売買が成立した場合も `CurrentPriceTime` が更新されるのを確認しました。
横から失礼いたしました。
