### ISSUE TITLE
【質問】検証用環境におけるオプションの注文発注について

### ISSUE THREAD

**Issue by shirasublue** [kabucom/kabusapi#199]
本番環境から`Symbol`を取得して検証環境にてオプションの注文発注を行っているのですが、
`code:4002005 商品エラー`になってしまいます。先物は問題なく`Result:0, OrderId: None`となります。

なお、私は本番環境において先物・オプション口座ともに開設していません。

これが標準的な仕様なのか、バグなのか、注文の仕方がおかしいのか判別がつかないため、確認をお願いしたく存じます。

以下リクエストサンプルです。
```
{
    "Password": "hoge",
    "Symbol": 135126818,  # 日経平均オプション 20/12 プット 26875
    "Exchange": 23,
    "TradeType": 1,
    "TimeInForce": 2,
    "Side": 2,
    "Qty": 10,
    "ClosePositionOrder": None,
    "FrontOrderType": 120, # 成行
    "Price": 0,
    "ExpireDay": 0,
}
```

**Comment by hishiharahaz** [comment]
shirasublueさん
先物は問題なく、オプションは商品エラーになるとの事ですが、オプション発注APIは「/kabusapi/sendorder/option」です。
オプション発注時に先物発注API「/kabusapi/sendorder/future」を呼び出しているのかもしれませんので確認ください。

■オプションAPIリファレンス
https://kabucom.github.io/kabusapi/reference/index.html#tag/order%2Fpaths%2F~1sendorder~1option%2Fpost

**Comment by shirasublue** [comment]
おっしゃる通りケアレスミスでした。失礼しました。
