### ISSUE TITLE
【質問】発注数について

### ISSUE THREAD

**Issue by ee97081** [kabucom/kabusapi#2]
APIに発注の機能がございますが、発注数に制限などはございますか。
制限がない場合、短期間に大量の注文を送ることも許されているという理解でよろしいでしょうか。

**Comment by yasuyuki-nakazawa** [comment]
kabuステーションAPIの利用規程の第3条18項では、同一銘柄に対しての注文は5件までとされている事に加えて、13項にてシステムの負荷を著しく増加させる行為を禁じているため、こちらに抵触しない範囲での発注を行っていただく必要があると考えます

**Comment by ee97081** [comment]
kabuステーションAPIの利用規程はどこで拝見することができるのでしょうか。口座を持っている方しか見ることができませんか？

**Comment by yasuyuki-nakazawa** [comment]
API利用規程に関しては、ログイン後画面のkabuステーション利用設定のページより参照できます。
また、kabuステーションのシステム設定のAPIタグの画面からも確認できます

**Comment by ee97081** [comment]
ありがとうございました。
