### ISSUE TITLE
【要望】kabuステーションAPIの利用条件について

### ISSUE THREAD

**Issue by kazu-tsuru** [kabucom/kabusapi#20]
個人投資家向けの「kabuステーションAPI」の公開ありがとうございます。
非常に魅力的ですので試してみたいと思ったのですが、当方Fintechプランの条件を満たしていなかったため利用できません。
Fintechプランになるには「前月当社全取引における約定回数が1回以上ある場合」とのことで非常に良心的とは思いますが、
次月にならないと試すことができないことと、仮にとても有用なツールと確認できたとしてもシステム作成に時間を要する
ことから初月3か月等適当な期間は利用条件緩和できないでしょうか。
ご検討お願いいたします。

**Comment by cyber-minion** [comment]
要望として承りました。検討させていただきます。

**Comment by yasuyuki-nakazawa** [comment]
新規でのkabuステーションご利用であれば、トライアルの期間はございます。
kabuステーションの無料条件、Fintechプランのトライアルに関しては、お手数をおかけして申し訳ございませんが、
auカブコム証券のサポートにお問い合わせいただけると幸甚です。

**Comment by ybangit** [comment]
.
