### ISSUE TITLE
【質問】Bloombergとの相違

### ISSUE THREAD

**Issue by nobuodesu** [kabucom/kabusapi#200]
カブステAPIで取得したbid/askがBloombergで取得したティックデータと異なります。
特に我々にとって有利なbid/askがカブステAPI側には存在していないとの認識です。
これはカブコムAPIのbid/askはマージンを内包しているのでしょうか。
そうしたbid/askは自己勘定で取引をされているのでしょうか。
日経225ミニ2月、3月限月を参照しています。よろしくお願いします。

**Comment by nobuodesu** [comment]
なお、データ間引きの件も認識しておりますが、その点は無関係かと思います。

**Comment by yasuyuki-nakazawa** [comment]
自己勘定取引はございません。
当社が配信している気配に関しては、取引所から直通で取得された情報を利用、配信しております。
Bloomberg社の配信している情報の取得元、配信仕様に関してはわかりかねます。
