### ISSUE TITLE
【質問】リファレンスにある「建玉ID」とは？

### ISSUE THREAD

**Issue by Rocky0156** [kabucom/kabusapi#201]
信用返済注文には「建玉ID」パラメータが必須とありますが、このIDはどこを参照すればよいですか？

残高照会にて得られる「約定番号」のことでしょうか？
もしそうであれば、リファレンス訂正いただいたほうが親切かと思います。違うようでしたらご指導ください。

**Comment by yasuyuki-nakazawa** [comment]
注約照会にある['ExecutionID']や残高照会の約定番号が対象となります
