### ISSUE TITLE
【質問】提供情報の個別取得について

### ISSUE THREAD

**Issue by taroro81** [kabucom/kabusapi#205]
![取得項目を単独で取得する方法](https://user-images.githubusercontent.com/70005674/102313122-5bfdfd00-3fb3-11eb-8f39-c0b8c0d29134.png)

平素より大変お世話になっております。
Python初学者であり、知識不足であるだけかもしれないのですが、
カブコム証券さんにご提供をしていただいた情報の中から、特定の項目を指定して抽出するにはどうすれば良いでしょうか？

**Comment by yasuyuki-nakazawa** [comment]
RESTにおいては上述いただいた形式でレスポンスを受けてしまいます。
レスポンスを分割して取得頂くのが現状仕様からのお願いとなりますが、その手段に関しては各種ライブラリをはじめ、独自でSplitする等、様々な方法がございます。

**Comment by cyber-minion** [comment]
サンプルコードの17行目を下記のように修正すれば"AskQty"のみ取得できます。
修正内容：contentの後ろに ['AskQty'] を追加すること。
※[ ] の中身（この例では 'AskQty' ）を他の項目に変更すれば、該当する値が取得できます。
　ただし、中身の書き方（大文字小文字等）は既存のレスポンスと一致する必要があります。

pprint.pprint(content['AskQty'])

**Comment by taroro81** [comment]
取得出来ました。
ご回答いただきありがとうございました。
初歩的な質問で申し訳ありませんでした。
