### ISSUE TITLE
【要望】API登録銘柄リストに登録せずに情報の取得がしたい

### ISSUE THREAD

**Issue by nakanakoto** [kabucom/kabusapi#206]
>情報系のリクエストは秒間10件ほどの流量制限を設けています。
>リクエストされた銘柄は自動でAPI登録銘柄リストに登録されます。

PUSH通知いらないので、
単純に情報だけ取得できるようにしてほしい。

**Comment by yasuyuki-nakazawa** [comment]
1月に銘柄時価情報のREST取得パフォーマンスの大幅改善を検討しております
その前提としても、銘柄登録は必要となる為、PUSH以外のRESTにおいても、銘柄登録を必須とする仕様は現状変更できない点はご了承ください
※システム負荷の関係です

**Comment by yasuyuki-nakazawa** [comment]
RESTにより情報取得については、Registを必ずしも必須としておりません。
銘柄リクエストをされた際に内部的にＲegist処理を実施するためです。しかしながら、情報取得のタイミング（銘柄情報の初回リクエスト）によっては銘柄情報のレスポンスとして十分な情報が返らない可能性があるため、銘柄登録（Ｒｅｇｉｓｔ）後のデータリクエストを推奨しております。
