### ISSUE TITLE
【質問】4本値データ出力で出力される1分足のデータについて

### ISSUE THREAD

**Issue by masaki64** [kabucom/kabusapi#208]
KabuStationで作成される１分足のデータについて、
例えば、09:27の1分足データは、09:27:00~09:27:59までのデータをもとに作成される認識でよろしいでしょうか。

WebSocket で取得したデータをMongoに格納し、
その情報をもとに1分足データを柵瀬氏しようとしているのですが、
1分足のデータが、「4本値データ出力で出力される1分足のデータ」と合わず、お聞きした次第です。

ご確認お願い致します。

**Comment by yasuyuki-nakazawa** [comment]
>09:27:00~09:27:59までのデータをもとに作成される認識でよろしいでしょうか
こちらは認識通りです。

1分足のデータが合わないという件ですが、情報の間引きに起因するものではないでしょうか
https://github.com/kabucom/kabusapi/issues/167

当件はTICKの配信と合わせて、日中足データ（分足、日足）の配信を含めて検討しております

**Comment by masaki64** [comment]
お世話になります。
情報のご連携、ありがとうございます。

また、情報の間引きだけでなく、
Current Timeの誤差もあると思ってるのですが、認識合ってますでしょうか。

・1分足のデータをpush機能で作成
9時27分の1分足のデータを、current time9時27分00秒〜27分59秒のデータを基に作成しています。
その範囲のデータで集計したところ、
株ステーション4本値の出力結果と出来高や終値が合いませんでした。
こちらで作成した27分、28分の1分足の出来高の合計が、4本値の出力結果の27分、28分の出来高の合計と合致したりするので、
 Current timeが27分のものが、pushでは、28分扱いとして配信されているように見えます。
*複数の銘柄で、1日のうち、2.3件見受けられます。

ご確認お願いします

**Comment by yasuyuki-nakazawa** [comment]
こちらお時間かかっており恐縮です。調査中となります

**Comment by yasuyuki-nakazawa** [comment]
こちらはクローズさせていただきます
