### ISSUE TITLE
【質問】同一建玉複数注文について

### ISSUE THREAD

**Issue by titaniumPig** [kabucom/kabusapi#209]
初歩的な質問になり、すみません。

現状、APIからは逆指値注文ができないとのことでしたので、残高照会により値動きを見ながらトレイリング注文をしていくことを想定してします。
その場合、値動きに合わせて指値注文を置くことになりますが、
**①同じ建玉（現物の場合は同じ銘柄）に対して別価格の指値注文をすると旧注文は自動的に取り消されるのでしょうか。
　それとも、注文取消が必須になるのでしょうか。**

また、不成注文も利用したい場合、
**②不成注文と指値注文は同時に出せるのでしょうか。
　それとも、やはり注文取消の上で指値注文ではなく不成注文に切り替える必要があるのでしょうか。**

既にどこかにご案内があれば、恐縮ですがお示しいただけると幸いです。
どうぞよろしくお願いします。

**Comment by yasuyuki-nakazawa** [comment]
①同一建玉を指定した別価格の指値注文は行えません。
　返済注文を実施した時点で対象のポジションは拘束されます。同一ポジションを指定した返済注文はエラーとなります。
　そのため、対象ポジション拘束を開放する必要があるため、取消しをする必要があります
②不成の発注は可能です。
　詳細はリファレンスを参照ください（FronOrderTypeの指定部分です）

**Comment by titaniumPig** [comment]
ご対応ありがとうございます！

>①同一建玉を指定した別価格の指値注文は行えません。
ポジションの開放が必要になるのですね、了解しました。
別記事（現在は削除済み？）になりますが、逆指値注文の実装を来年に予定していると拝見しました。
要望が多く大変だと思いますが、楽しみに待っております。

>②不成の発注は可能です。
”（指値注文を出している場合でも）不成注文の発注は（同時に）可能です。”
と読み替えて捉えさせていただきます。

**Comment by yasuyuki-nakazawa** [comment]
逆指値は3月をターゲットに対応できればと思っております。
逆指値の要望は多く、なるべく早く対応できるようにいたしますので、今しばらくお待ちください。

「お知らせ」の対応検討中のスレッドに逆指値注文の対応を追記させていただきました。
今後、対応時期が明確化した時点で、リリースのお知らせの方で追記、展開させていただきます
