### ISSUE TITLE
【質問】逆指値注文の方法

### ISSUE THREAD

**Issue by ybn500** [kabucom/kabusapi#210]
逆指値注文する方法を教えて頂けますでしょうか

※下記の記事には提供されていると記載されていますが、「REST API リファレンス」には情報がありませんでした。
https://liginc.co.jp/524558

もし、逆指値注文の機能が無い場合は、以下2点について
ご知らせ頂けますと幸いです。
　・代替する方法
　・逆指値注文を正式に提供する予定の有無/時期

お手数をお掛けいたしますが
ご回答の程よろしくお願いいたします。

**Comment by yasuyuki-nakazawa** [comment]
こちらでも回答させていただいておりますが、逆指値は現状サポートしておりません
https://github.com/kabucom/kabusapi/issues/67#issuecomment-688032458

ただ、要望として強いので、こちらは3月を予定で対応させて頂こうと考えております。

**Comment by ybn500** [comment]
ご回答ありがとうございます。
承知いたしました。
