### ISSUE TITLE
【不具合】板情報のPriceとQtyが0になっている

### ISSUE THREAD

**Issue by FujimakiHiroyuki** [kabucom/kabusapi#211]
■[必須] 不具合事象(概要)
一部銘柄の板情報を取得しようとした所、PriceとQtyがすべて0になっていた。確認したのは5802住友電気工業
■[必須] 本来想定されるアクションと事象
PriceとQtyが正しく表示される
■[必須] 不備発生時刻（常時の場合は、常時で記載ください)
常時
■[任意] お使いの環境(OS、Excelのバージョン等)、サンプル(Macro、アドインのバージョン）
■[任意] 不備部分のログ
board取得のログ
{'OverSellQty': 0.0, 'UnderBuyQty': 0.0, 'TotalMarketValue': 1054750048573.5, 'MarketOrderSellQty': 0.0, 'MarketOrderBuyQty': 0.0, 'BidTime': '2020-12-23T10:29:32+09:00', 'AskTime': '2020-12-23T10:29:32+09:00', 'Exchange': 1, 'ExchangeName': '東証１部', 'TradingVolume': 1095900.0, 'TradingVolumeTime': '2020-12-23T10:29:29+09:00', 'VWAP': 1345.4135, 'TradingValue': 1474438600.0, 'BidQty': 1400.0, 'BidPrice': 1329.0, 'BidSign': '0101', 'Sell1': {'Price': 0.0, 'Qty': 0.0, 'Sign': None, 'Time': '2020-12-23T10:29:32+09:00'}, 'Sell2': {'Price': 0.0, 'Qty': 0.0}, 'Sell3': {'Price': 0.0, 'Qty': 0.0}, 'Sell4': {'Price': 0.0, 'Qty': 0.0}, 'Sell5': {'Price': 0.0, 'Qty': 0.0}, 'Sell6': {'Price': 0.0, 'Qty': 0.0}, 'Sell7': {'Price': 0.0, 'Qty': 0.0}, 'Sell8': {'Price': 0.0, 'Qty': 0.0}, 'Sell9': {'Price': 0.0, 'Qty': 0.0}, 'Sell10': {'Price': 0.0, 'Qty': 0.0}, 'AskQty': 1700.0, 'AskPrice': 1328.0, 'AskSign': '0101', 'Buy1': {'Price': 0.0, 'Qty': 0.0, 'Sign': None, 'Time': '2020-12-23T10:29:32+09:00'}, 'Buy2': {'Price': 0.0, 'Qty': 0.0}, 'Buy3': {'Price': 0.0, 'Qty': 0.0}, 'Buy4': {'Price': 0.0, 'Qty': 0.0}, 'Buy5': {'Price': 0.0, 'Qty': 0.0}, 'Buy6': {'Price': 0.0, 'Qty': 0.0}, 'Buy7': {'Price': 0.0, 'Qty': 0.0}, 'Buy8': {'Price': 0.0, 'Qty': 0.0}, 'Buy9': {'Price': 0.0, 'Qty': 0.0}, 'Buy10': {'Price': 0.0, 'Qty': 0.0}, 'Symbol': '5802', 'SymbolName': '住友電気工業', 'CurrentPrice': 1328.0, 'CurrentPriceTime': '2020-12-23T10:29:29+09:00', 'CurrentPriceChangeStatus': '0058', 'CurrentPriceStatus': 1, 'CalcPrice': 1328.0, 'PreviousClose': 1367.5, 'PreviousCloseTime': '2020-12-22T00:00:00+09:00', 'ChangePreviousClose': -39.5, 'ChangePreviousClosePer': -2.89, 'OpeningPrice': 1370.0, 'OpeningPriceTime': '2020-12-23T09:00:00+09:00', 'HighPrice': 1371.0, 'HighPriceTime': '2020-12-23T09:00:00+09:00', 'LowPrice': 1326.0, 'LowPriceTime': '2020-12-23T10:15:22+09:00'}

**Comment by FujimakiHiroyuki** [comment]
今見たら正しく表示されていたので、何か条件があったのかもしれません…

**Comment by yasuyuki-nakazawa** [comment]
当件、確認いたします。
銘柄リクエストに当たり、Registは適切に実施されているでしょうか？

**Comment by FujimakiHiroyuki** [comment]
ありがとうございます。本日午前に何回かこの状況になって以来、問題は出ていません。
Registというのは銘柄登録の事でしょうか？

銘柄登録の機能は何のためにあるのか正直分かっておらず、活用していません。
現在は、板情報か銘柄情報だったかをGETすると銘柄登録が自動でされて、銘柄登録が50件を超えると板情報がエラー見れなくなるので、その前に銘柄登録全解除をする、といった使い方をしています。

**Comment by yasuyuki-nakazawa** [comment]
Registは銘柄登録のことです。
当該機能は銘柄リクエストをkabuｽﾃｰｼｮﾝに実施することで、移行の情報更新をkabuｽﾃｰｼｮﾝ自体がリアルタイムに受付、2回目以降のリクエストのレイテンシを向上させるためのものです。
現状はRegistしていない状態でも情報が取得されるケースがあります（すでにkabuｽﾃｰｼｮﾝ上に情報が表示されている場合等）
未登録の場合、初回リクエスト時に記載の事象が発生することがございますので、銘柄取得の前にはRegistの実行をお願いします。

**Comment by FujimakiHiroyuki** [comment]
ありがとうございます。理解しました。
私は現在、約1000銘柄の価格情報を順番にチェックし、良さそうなものを買うといったロジックを作っていますが、
チェックの時に毎回registをするというのは不便なので、可能ならregist無しでも問題なく取得できるようになると助かります。

**Comment by tekuteku2023** [comment]
ありがとうございます。
「未登録の場合、初回リクエスト時に記載の事象が発生することがございますので、」⇒このご説明の事象です。「銘柄取得の前にはRegistの実行をお願いします。」⇒理解しました。
