### ISSUE TITLE
【質問】kabusapi_sendorder_cash_buy.pyの疑問

### ISSUE THREAD

**Issue by hmhjapan** [kabucom/kabusapi#212]
obj = { 'Password': '409175hmh',
        'Symbol': '7733',
        'Exchange': 1,
        'SecurityType': 1,
        'FrontOrderType': 20,
        'Side': '2',
        'CashMargin': 2,
        'DelivType': 0,
#        'FundType': 'AA',
        'AccountType': 2,
        'Qty': 100,
        'Price': 2262,
        'ExpireDay': 20201230 }
json_data = json.dumps(obj).encode('utf-8')

url = 'http://localhost:18080/kabusapi/sendorder'
req = urllib.request.Request(url, json_data, method='POST')
req.add_header('Content-Type', 'application/json')

信用取り引きで、買う。
パラメータはどこが間違いましたか。或いは他の原因ですか。エラーは下記の通りです。
　HTTP Error 400: Bad Request
　{'Code': 4001005, 'Message': 'パラメータ変換エラー - 詳細はkabuSログファイルを確認してください'}
以上、よろしくお願いします。

**Comment by hmhjapan** [comment]
上のソースをもう一度送付します。FundTypeの設定がなかったです。
obj = { 'Password': '409175hmh',
        'Symbol': '7733',
        'Exchange': 1,
        'SecurityType': 1,
        'FrontOrderType': 20,
        'Side': '2',
        'CashMargin': 2,
        'DelivType': 0,
        'AccountType': 2,
        'Qty': 100,
        'Price': 2262,
        'ExpireDay': 20201230 }
json_data = json.dumps(obj).encode('utf-8')

url = 'http://localhost:18080/kabusapi/sendorder'
req = urllib.request.Request(url, json_data, method='POST')
req.add_header('Content-Type', 'application/json')

**Comment by yasuyuki-nakazawa** [comment]
上記の実行でもエラーメッセージは変わらないですか？

**Comment by yasuyuki-nakazawa** [comment]
まず、発注パスワードはマスクいただいたうえで記載していただいた方がよいかと思われます。
現物（買）サンプルの「kabusapi_sendorder_cash_buy.py」をもとに信用新規（買）をしようとしていますが、
信用新規のサンプルは、「kabusapi_sendorder_margin_new.py」ですので、こちらを参考にされた方がよいと思います。
信用発注の場合は「FundType」の指定は不要です。

**Comment by hmhjapan** [comment]
上記の実行でもエラーメッセージは変わらないです。
分かりました。「kabusapi_sendorder_margin_new.py」をもとに信用新規してみます。

**Comment by yasuyuki-nakazawa** [comment]
信用取引に関しては、信用取引用のサンプルをご利用、ご確認ください。
なお、当件、信用用のサンプルでは挙動いかがでしたでしょうか
問題なければ、当件はクローズさせていただきます。

**Comment by hmhjapan** [comment]
すみません。明日この問題を確認するつもりです。連絡が遅れてすみません。

**Comment by hmhjapan** [comment]
試しました。OKです。ありがとうございました。この件をクローズします。
