### ISSUE TITLE
【要望】/board（時価情報・板情報データ取得）の速度向上・劣化抑止

### ISSUE THREAD

**Issue by ybn500** [kabucom/kabusapi#213]
■要望事項
　/board（時価情報・板情報データ取得）のレスポンスが遅いため、取引結果に影響を及ぼしています。
　速度向上いただけますようお願いいたします。
　
　特に同時リクエスト（1秒間に2～10件）の際、著しく速度が劣化（2秒～10秒）となっているため
　APIの利用制限内（1秒間10件）のリクエストは、速度劣化のないよう改善いただけますようお願い申し上げます。

　【期待値】1リクエスト500ms未満、かつ1秒間10件のリクエストでも同等の応答時間を担保。

■補足（環境と計測結果）
＜計測したインターネット環境＞
　上り 30.5Mbps
　下り 36.6Mbps

＜応答時間＞
　1件（単発リクエスト）：平均980ms（0.98秒）/件
　2件（同時リクエスト）：平均2,045ms（2.045秒）/件
　3件（同時リクエスト）：平均3,040ms（3.04秒）/件
　10件（同時リクエスト）：平均10,174ms（10.174秒）/件

　※計測のサンプリング数は、約1,000件程度。
　（kabusapi_board.py株式銘柄の時価情報・板情報データ取得にて、1リクエストあたりの平均応答時間を算出。）

何卒よろしくお願い申し上げます。

**Comment by yasuyuki-nakazawa** [comment]
以下お問い合わせと同質問ということで、こちらの方はクローズさせていただきます。
https://github.com/kabucom/kabusapi/issues/214
