### ISSUE TITLE
【質問】/board（時価情報・板情報データ取得）の速度向上・劣化防止

### ISSUE THREAD

**Issue by ybn500** [kabucom/kabusapi#214]
■状況
　/board（時価情報・板情報データ取得）のレスポンスが遅いため、取引結果に影響を及ぼしています。
　
　特に同時リクエスト（1秒間に2～10件）の際、著しく速度が劣化（2秒～10秒）となっているため
　複数銘柄を同時に取引できず困っております。

■質問事項
　下記2点の対応方法ございましたらお知らせ願います。
　（１）/board（時価情報・板情報データ取得）のレスポンスを改善させる方法
　（２）/board（時価情報・板情報データ取得）の同時リクエスト時の速度劣化を抑止する方法

■補足（環境と計測結果）
＜計測したインターネット環境＞
　上り 30.5Mbps
　下り 36.6Mbps

＜応答時間＞
　1件（単発リクエスト）：平均980ms（0.98秒）/件
　2件（同時リクエスト）：平均2,045ms（2.045秒）/件
　3件（同時リクエスト）：平均3,040ms（3.04秒）/件
　10件（同時リクエスト）：平均10,174ms（10.174秒）/件

　※計測のサンプリング数は、約1,000件程度。
　（kabusapi_board.pyを用いた株式銘柄の時価情報・板情報データ取得にて、1リクエストあたりの平均応答時間を算出。）

　※本記載内容は、別途要望として記載させていただきました。

**Comment by ybangit** [comment]
kabu api の rest のレスポンスが遅すぎる件は、以前から問題が挙がっていて
今月末 28日に以下のissueにて解消される予定だと認識しています。

開発チームさん、間違いないでしょうか ? 
ちなみに 具体的にどの程度 パフォーマンスが改善される見込みなのでしょうか？ (おおよその目安は ? )

#203
■kabuステーションAPI改善予定（2021年01月)　
○リリース予定日：2021年1月28日（予定）
・API(銘柄情報取得ﾊﾟﾌｫｰﾏﾝｽ改善)


現状はリクエスト毎に毎回サーバに接続していることが激遅の原因らしく、それをやめて
kabuステーションから直接データ取得するだけの仕様にすることでスピードが改善されるようです。

push配信レベルのスピードになることを期待していますが
とりあえず月末updateまで待ちます。

**Comment by yasuyuki-nakazawa** [comment]
ybangitさん
回答ありがとうございます。
当月改善版後にご確認いただきたいのですが、今回の修正では、初回はサーバアクセスが入るため、レスポンスは変わりませんが、以降はレジストされた銘柄をkabuｽﾃｰｼｮﾝ側でリアルタイムで情報更新を行い、問い合わせがあった際はkabuｽﾃｰｼｮﾝからレスポンスを返すようにいたしますので、２回目以降は大幅なレイテンシ削減が図られると考えております。

**Comment by yasuyuki-nakazawa** [comment]
こちらのIssueですが、レスポンスについてはいかがでしょうか。
改善確認できておりましたら、Closeさせていただこうと考えています

**Comment by ybn500** [comment]
改善確認できました。Close頂ければと存じます。
ご対応ありがとうございました。
