### ISSUE TITLE
【お知らせ】kabuステーションAPIリファレンスのOASバージョンアップ(1/28実施済)

### ISSUE THREAD

**Issue by yasuyuki-nakazawa** [kabucom/kabusapi#216]
現在、kabuステーションAPIのリファレンスはOpenAPI Specification (以下OAS) v2にて公開しております。
こちらにつきまして、1月末よりOAS v3でのご提供に変更いたします。
お客さまがご利用なさっているツールやサービスによりましては、OASバージョンのサポート状況が異なりますのでご注意ください。

**Comment by spotthediff** [comment]
OpenAPI Specification v2での提供はなくなるということでしょうか?

**Comment by yasuyuki-nakazawa** [comment]
OpenAPI Specification v2とのダブルメンテナンスが厳しいため、v3でのみの対応を考えております。

**Comment by yasuyuki-nakazawa** [comment]
こちら、1/28に対応実施済みです
