### ISSUE TITLE
【質問】逆指値注文について　→【対応済：2021年5月25日 ver5.13.3】

### ISSUE THREAD

**Issue by masaki64** [kabucom/kabusapi#217]
注文(order)のAPIで、逆指値注文は可能でしょうか。(不可である認識です）
不可である場合、リリース時期の目途を教えていただきたいです。

**Comment by yasuyuki-nakazawa** [comment]
逆指値は現在検討しているところです
３月の追加検討中です

**Comment by yasuyuki-nakazawa** [comment]
諸案件の都合上、当該機能の対応は3月以降で予定となりましたこと、ご連絡いたします

**Comment by cyber-minion** [comment]
#317 にて対応済ですので、クローズいたします。
