### ISSUE TITLE
【不具合】時価PUSH配信においてTradingValueの更新が遅いことがある

### ISSUE THREAD

**Issue by stn** [kabucom/kabusapi#218]
■[必須] 不具合事象(概要)

時価PUSH配信のデータに不整合がみられる。

以下のデータは時価PUSH配信から得たデータのCurrentPrice, CurrentPriceTime, TradingVolume, TradingVolumeTime, VWAP, TradingValueを時系列にならべたものです。

```
(3912.0, '2021-01-12T14:59:27+09:00', 3483900.0, '2021-01-12T14:59:27+09:00', 3929.967, 13691612100.0)
(3909.0, '2021-01-12T14:59:27+09:00', 3484000.0, '2021-01-12T14:59:27+09:00', 3929.9664, 13691612100.0)
(3909.0, '2021-01-12T14:59:27+09:00', 3484000.0, '2021-01-12T14:59:27+09:00', 3929.9664, 13692003000.0)
```

1行目から2行目にかけてTradingVolumeが100増加していますが、TradingValueが変化していません。
3行目でTradingVolumeが変化していないにも関わらず、TradingValueが変化しています。
TradingVolume * VMAP = TradingValueになるはずですので、2行目のデータの整合性がとれておらず、
TradingValueの更新が遅れていると推察されます。

■[必須] 本来想定されるアクションと事象

2行目は次のようになるはずです。

```
(3912.0, '2021-01-12T14:59:27+09:00', 3483900.0, '2021-01-12T14:59:27+09:00', 3929.967, 13691612100.0)
(3909.0, '2021-01-12T14:59:27+09:00', 3484000.0, '2021-01-12T14:59:27+09:00', 3929.9664, 13692003000.0)
(3909.0, '2021-01-12T14:59:27+09:00', 3484000.0, '2021-01-12T14:59:27+09:00', 3929.9664, 13692003000.0)
```

■[必須] 不備発生時刻（常時の場合は、常時で記載ください)

上記の日時の通り。対象は3382.T。

■[任意] お使いの環境(OS、Excelのバージョン等)、サンプル(Macro、アドインのバージョン）

Windows 10 20H2 (OS build 19042.685)
kabu Station 5.12.4.0

**Comment by yasuyuki-nakazawa** [comment]
当件ですが、TradingVolume(売買高)とTradingValue(売買代金)は、同時に更新されるべきという理解はございます。
しかしながら、Pushに関しては、情報受信と同時に配信を行っている都合上、先に売買高の更新が行われた状況下において不整合が発生しているとおもわれます。
配信情報に関しては、取引所から受信した情報をもとにそのまま配信し、依存関係を持っていないことが原因となります。
対応策があるかを含めて検討はさせていただきますが、現行は仕様となります。

**Comment by stn** [comment]
取引所から受信したtickデータを元に売買高を計算しているのではなく、売買高と売買代金は取引所から受信したデータをそのまま配信しているということで認識はあってますでしょうか。

**Comment by yasuyuki-nakazawa** [comment]
>売買高と売買代金は取引所から受信したデータをそのまま配信しているということ

はい。そのまま配信しております。

**Comment by yasuyuki-nakazawa** [comment]
当件はクローズとさせていただきます
