### ISSUE TITLE
【質問】Side(売買区分)だけstring型なのはなぜですか?

### ISSUE THREAD

**Issue by spotthediff** [kabucom/kabusapi#222]
Side(売買区分)だけstring型なのはなぜでしょうか?
ClosePositionOrder(決済順序)やTimeInForce(有効期間条件)などのほかのフラグはint型ですがなぜかこれだけstringです
できれば変えたほうがよいのではないでしょうか?
 backward compatibilityの問題もあるかもしれませんが、ちょっとややこしいなと思いました。

**Comment by cyber-minion** [comment]
お手数、ご不便をおかけして申し訳ございませんが、当社のシステム都合によるものです。ご了承ください。

**Comment by yasuyuki-nakazawa** [comment]
当件はCloseさせていただきます
