### ISSUE TITLE
【要望】指値の変更、成り行きへの変更はできないのですか

### ISSUE THREAD

**Issue by hsaeki2013-A** [kabucom/kabusapi#227]

**Comment by yasuyuki-nakazawa** [comment]
現在、シンプルな注文形態を提供するために、訂正機能を設けておりません。
そのため、取り消しのうえ、再発注をお願いしている次第です。
訂正においては、取引所としても許容している条件の組み合わせもおおく、諸変更の際のインパクトも大きいこともあり、APIチャネルに関しては、お手数をお掛けしますが、取消・再発注の形式のままとさせてください

**Comment by yasuyuki-nakazawa** [comment]
訂正機能の導入に関しては、現状見送らせてください。
理由としては上述の通りですが、今後、他機能改善との兼ね合い、ニーズによって再度検討させていただきます
