### ISSUE TITLE
【要望】Ordersでの注文照会は何日分でるのですか？当日分のフィルター欲しい

### ISSUE THREAD

**Issue by hsaeki2013-A** [kabucom/kabusapi#228]

**Comment by yasuyuki-nakazawa** [comment]
注約照会は基本的に2週間分出力されます。
ただし、約定が完了したものに関しては、受渡日を超えるとkabuｽﾃｰｼｮﾝ上からは消えるため参照することができません」

**Comment by yasuyuki-nakazawa** [comment]
注文照会は諸フィルタでの絞り込みが可能です。
指定日以降の取得が可能ですので、当日をしていただくことで取得情報をフィルタ取得いただけます。

**Comment by hsaeki2013-A** [comment]
２週間分は了解しましたが、注文照会？てOrdersではないのですよね。何ですか？

**Comment by yasuyuki-nakazawa** [comment]
>２週間分は了解しましたが、注文照会？てOrdersではないのですよね。何ですか？

失礼しました。注約照会です。Ordersはメソッド違いですので放念ください

**Comment by cyber-minion** [comment]
注文約定紹介は「[orders](https://kabucom.github.io/kabusapi/reference/index.html#tag/info/paths/~1orders/get)」で、残高照会は「[positions](https://kabucom.github.io/kabusapi/reference/index.html#tag/info/paths/~1positions/get)」となります。

**Comment by cyber-minion** [comment]
本件は回答済ですので、クローズいたします。
