### ISSUE TITLE
【要望】銘柄登録で登録した銘柄のリストを取得したい

### ISSUE THREAD

**Issue by spotthediff** [kabucom/kabusapi#229]
銘柄登録`/register`で登録済みの銘柄のリストを取得するAPIがあるといいなと思います。
API referencesを見てみても`銘柄登録`、`銘柄登録解除`、`銘柄登録全解除`はありますが、登録されている銘柄全体をAPIを使って取得する方法が見つかりません。
なにか方法があるのでしょうか?

**Comment by hmhjapan** [comment]
クローズしましたが、登録されている銘柄全体をAPIを使って取得する方法がありますか。教えてください。
要望は対応済み、対応中ですか。
よろしくお願いいたします。

**Comment by tsuchinaga** [comment]
登録銘柄の取得だけをするAPIは提供されていません。

登録する際に取得するしかない状態は変わっていません。

**Comment by hmhjapan** [comment]
分かりました。ご回答ありがとうございます。
