### ISSUE TITLE
【質問】登録済みの銘柄の一覧を取得する方法

### ISSUE THREAD

**Issue by spotthediff** [kabucom/kabusapi#230]
銘柄登録/registerで登録済みの全銘柄を取得するする方法はありますか(どの銘柄を登録しているかの一覧がほしい)
API referencesを見てみても銘柄登録、銘柄登録解除、銘柄登録全解除はありますが、登録されている銘柄の一覧をAPIを使って取得する方法が見つかりません。
なにか方法があるのでしょうか?

**Comment by yasuyuki-nakazawa** [comment]
Regist関数の戻りで登録銘柄の一覧があるかとおもいます。
ご確認ください
