### ISSUE TITLE
【質問】APIで発注を出そうとすると手続きが済んでないので取引できないと表示される。

### ISSUE THREAD

**Issue by ShotaroMinami** [kabucom/kabusapi#233]
HTTP Error 500: Internal Server Error
{'Code': 32, 'Message': 'お取引にかかる書類のご確認/お手続きがお済みでないため、お取引を承ることができません'}

と表示されます。

株ステーション上では、直接取り引きもできるし、各種設定もすべて完了しているはずであるのですが、上記のメッセージがでます。どうしたら良いでしょうか。探しても該当する書類や手続が見当たりません。

import urllib.request
import json
import pprint

obj = { 'Password': 'XXXXXX',
        'Symbol': '9433',
        'Exchange': 1,
        'SecurityType': 1,
        'FrontOrderType': 20,
        'Side': '2',
        'CashMargin': 1,
        'DelivType': 2,
        'FundType': 'AA',
        'AccountType': 2,
        'Qty': 100,
        'Price': 3244,
        'ExpireDay': 20210126 }
json_data = json.dumps(obj).encode('utf-8')

url = 'http://localhost:18080/kabusapi/sendorder'
req = urllib.request.Request(url, json_data, method='POST')
req.add_header('Content-Type', 'application/json')
req.add_header('X-API-KEY', 'XXXXXXXXXXXXXXXXXXXXXXX')

try:
    with urllib.request.urlopen(req) as res:
        print(res.status, res.reason)
        for header in res.getheaders():
            print(header)
        print()
        content = json.loads(res.read())
        pprint.pprint(content)
except urllib.error.HTTPError as e:
    print(e)
    content = json.loads(e.read())
    pprint.pprint(content)
except Exception as e:
    print(e)

**Comment by ShotaroMinami** [comment]
'AccountType': 2, が法人指定になっていなかったためだと解決しました。

**Comment by yasuyuki-nakazawa** [comment]
こちら、解決済みということで、Closeさせていただきます
