### ISSUE TITLE
【不具合】schema定義のenum系descriptionが複数行定義になっていない

### ISSUE THREAD

**Issue by hori-ryota** [kabucom/kabusapi#235]
■[必須] 不具合事象(概要)
`|-` が漏れているようで複数行定義になっていないところが所々ある

該当箇所の例：[kabusapi/kabu\_STATION\_API\.yaml at 5223a055bb7ef7812f80e2b1b2eddde9babe8335 · kabucom/kabusapi](https://github.com/kabucom/kabusapi/blob/5223a055bb7ef7812f80e2b1b2eddde9babe8335/reference/kabu_STATION_API.yaml#L2322)

■[必須] 本来想定されるアクションと事象
`|-` をつける
■[必須] 不備発生時刻（常時の場合は、常時で記載ください)
■[任意] お使いの環境(OS、Excelのバージョン等)、サンプル(Macro、アドインのバージョン）
■[任意] 不備部分のログ

**Comment by hori-ryota** [comment]
せっかくgithubなので、仕様書に変更が入るとき（記載方法や仕様変更どちらも）は不完全でも早め早めにプルリクエストで晒しておけるといいかもですね〜

**Comment by hori-ryota** [comment]
閉じタグ漏れもありました

[kabusapi/kabu\_STATION\_API\.yaml at master · kabucom/kabusapi](https://github.com/kabucom/kabusapi/blob/5223a055bb7ef7812f80e2b1b2eddde9babe8335/reference/kabu_STATION_API.yaml#L3019)

**Comment by cyber-minion** [comment]
ご指摘ありがとうございます。リファレンスを修正いたしましたので、ご確認いただければと思います。
不備・漏れ等ございましたらまたご指摘ください。

**Comment by hori-ryota** [comment]
ご対応ありがとうございます。自作のparserで確認中です。enum定義のtableタグ周りの記述が変わったのでparserを改修しているため少々お時間をいただいております。

**Comment by hori-ryota** [comment]
ちなみにdescriptionのhtml tableをparseするのが結構手間になりがち（特に `<tr> ... </tr>` が複数行のため行ごとにparseしようとすると状態を持つparserになってしまう）なのですが、enumの定義ってもうすこしparseしやすい形式になったりしませんでしょうか。

markdownのtableか、description外でparseしやすい定義にするか、 `<tr> ... </tr>` は一行にまとめるようにするか、descriptionはtable以外もhtml化するか、などを検討できると嬉しいです。

**Comment by hori-ryota** [comment]
無事、直ったのを確認できましたー！ありがとうございます。

[follow updating of reference: https://github\.com/kabucom/kabusapi/commit/26fed7f69f46833d9571a542e0c8eb3fceb964f2 by hori\-ryota · Pull Request \#2 · hori\-ryota/go\-kabusapi](https://github.com/hori-ryota/go-kabusapi/pull/2)
