### ISSUE TITLE
【要望】情報系のリクエスト秒間10件「流量制限の緩和」をお願いいたします。

### ISSUE THREAD

**Issue by ybn500** [kabucom/kabusapi#236]
ver512.5にて速度改善いただき誠にありがとうございます。
以前よりとても使いやすくなりました。

一方で、パフォーマンス向上いただいたものの
情報系のリクエスト「秒間10件の流量制限※」に抵触することが多くなり
結局は、秒間10件しか処理できない状況となっております。

現在のverが「2回目以降kabuｽﾃｰｼｮﾝからレスポンスを返す」という仕様であれば
（勝手ながらサーバ負担にはなり難いと考えており）
kabuｽﾃｰｼｮﾝからレスポンスを返す場合は、「流量制限の緩和」をご検討いただけないでしょうか

※特に「時価情報・板情報（/board）」が制限に抵触しております。

どうぞよろしくお願いいたします。

**Comment by yasuyuki-nakazawa** [comment]
当件ですが、秒間の流量制限の順次拡大を実施させていただきます。
他要望と同一のため、統合管理させていただきます。
現状の10件を20件、30件、40件と不可状況見つつ、拡大させていただきます

統合Issue：https://github.com/kabucom/kabusapi/issues/157
