### ISSUE TITLE
【不具合】詳細ランキングのAverageRankingがfloatで返される

### ISSUE THREAD

**Issue by tsuchinaga** [kabucom/kabusapi#237]
■[必須] 不具合事象(概要)

詳細ランキングのレスポンスにあるAverageRankingがfloatで返される

■[必須] 本来想定されるアクションと事象

リファレンスではintになっているので、intを期待しています

■[必須] 不備発生時刻（常時の場合は、常時で記載ください)

常時

■[任意] お使いの環境(OS、Excelのバージョン等)、サンプル(Macro、アドインのバージョン）

kabuステーション ver.5.1.2.5

■[任意] 不備部分のログ

ご確認をよろしくお願いします

**Comment by cyber-minion** [comment]
ご指摘ありがとうございます。kabuステ内としては、AverageRankingは「double」として保持しているので、APIとしても「double」としてレスポンスをしています。

リファレンスを修正いたしましたので、ご確認いただければと思います。不備・漏れ等ございましたらまたご指摘ください。
