### ISSUE TITLE
注文の指値は変更でないのですか？今はCancel 　Re-Orderにしてます。

### ISSUE THREAD

**Issue by hsaeki2013-A** [kabucom/kabusapi#238]

**Comment by hori-ryota** [comment]
以前に投げている同じ質問に回答いただいているようですね

[【要望】指値の変更、成り行きへの変更はできないのですか · Issue \#227 · kabucom/kabusapi](https://github.com/kabucom/kabusapi/issues/227#event-4260670658)

**Comment by yasuyuki-nakazawa** [comment]
上記回答済みですが、現状は訂正を行うことはできません。

**Comment by yasuyuki-nakazawa** [comment]
こちら、クローズさせていただきます
