### ISSUE TITLE
【質問】PTSの時価情報・板情報、銘柄情報も取得可能でしょうか

### ISSUE THREAD

**Issue by gatehub1496** [kabucom/kabusapi#240]
＜質問１＞
kabuステーションAPIでは、日中および１５時～１６時、１６時３０～０時のPTSの時価情報・板情報、銘柄情報も取得可能でしょうか。

＜質問２＞
下記マニュアルの　情報＞時価情報・板情報＞exchangeの定義値「２４」に夜間とありますが、この定義値では具体的にどのような情報が取得できるでしょうか。「２」日通し、「２３」日中についてもご教示いただけると幸いです。
https://kabucom.github.io/kabusapi/reference/index.html#tag/info/paths/~1board~1{symbol}@{exchange}/get

補足：定義値２４、２、２３で情報取得を試みたところ下記のエラーコードが出力されました。
HTTP Error 400: Bad Request
{'Code': 4002001, 'Message': '銘柄が見つからない'}

**Comment by yasuyuki-nakazawa** [comment]
＜質問１＞
現状PTSの時価情報、板情報の取得はできません。
＜質問２＞
exchangeの２４等に関しては派生商品（先物）の銘柄指定の際に指定する市場コードとなります。
