### ISSUE TITLE
【質問】kabu station でとれる指数が取れない

### ISSUE THREAD

**Issue by kunioya** [kabucom/kabusapi#243]
こんにちは。
kabu station で 101 と入れると日経平均株価が取れます。kabusapi でも同様に取れます。
「日経平均 VI 」という指数があり kabu station で 145 で取れます。これが kasuapi だと
{'Code': 4002001, 'Message': '銘柄が見つからない'}
になってしまいます。どうやったら kabusiapi で取れるようになるのでしょうか。
ちなみに kabu station で 144 で「NYダウ」が取れますが、kabusapi では取れません。

**Comment by cyber-minion** [comment]
「日経平均 VI 」の取得については、「銘柄コード：145、市場コード：2」を指定いただければ取得できます。
「NYダウ」の取得はkabuステーションAPIは対応しておりません。また、2021年2月22日(月) より、マイページおよびkabuステーションでの「NYダウ」の情報提供は廃止させていただきます。詳しくは、[こちら](https://kabu.com/info/20210129_1.html)にてご確認ください。
