### ISSUE TITLE
【質問】東証障害時の確認について

### ISSUE THREAD

**Issue by hori-ryota** [kabucom/kabusapi#246]
本日生じた東証の情報系システム障害によってAPIも影響を受けたと思うのですが、このような障害をAPIにて検知する方法を整備することは可能でしょうか。

自動取引停止や運用の緊急アラートに用いたいです。

また、本日の障害の影響かは確認できていませんが、私のシステムでは繋ぎっぱなしにしていたPUSH APIが午後から新規情報を受け取れていないようでした。

もし可能でしたら今回の障害によるAPIへの影響を教えていただけたら嬉しいです。

メモ：[システム運行状況 \| 日本取引所グループ](https://www.jpx.co.jp/systems/system-status/01.html)

![Screen Shot 2021-02-15 at 14 43 07](https://user-images.githubusercontent.com/2936501/107909716-2e760580-6f9c-11eb-9eb9-fb0be4238ca2.png)

**Comment by yasuyuki-nakazawa** [comment]
東証障害に関してですが、kabuｽﾃｰｼｮﾝとして影響が出る可能性がある機能としては、
フル板、T＆S、リアルタイム株価予測、時価情報系、チャート
となり、API観点では時価情報系の情報取得に影響がある可能性があります。
こちらはPUSHもRESTも同様となります。
ただし、どの情報がロストしたのかということが明確にならないため、配信情報の一部がロストしている可能性がありますというご案内しかできない状況で、大変申し訳ございません。

なお、すでに取引所側でも公開しておりますが、当該事象は今週末まで続くとの報告を受けております

**Comment by hori-ryota** [comment]
> また、本日の障害の影響かは確認できていませんが、私のシステムでは繋ぎっぱなしにしていたPUSH APIが午後から新規情報を受け取れていないようでした。

こちら、本日も午後よりデータが受け取れていないようです。12:05-12:06に十数件受け取った後にデータが来ていないように見えます。

- 東証の障害によるもので解決すれば直るものなのか、仕様変更などでこちらで対応が必要なものなのかは切り分けたい
- 検知できるなら再起動処理などで対応したいので障害検知手段を知りたい

該当箇所付近のアプリログを貼っておきます

```
11:22:44.3766,I,3764,0030 UpdateService.UpdateCheck : start
11:32:44.3912,I,3764,0030 UpdateService.UpdateCheck : start
11:42:44.3994,I,3764,0013 UpdateService.UpdateCheck : start
11:52:44.4147,I,3764,0017 UpdateService.UpdateCheck : start
12:00:23.2997,I,3764,0025 Recv Event Type=2,Account=*@BROADCASTNEWS,Value=BROADCASTNEWS
12:00:23.2997,I,3764,0025 MasterManager Recv NotifyEvent = Type=2,Account=*@BROADCASTNEWS,Value=BROADCASTNEWS
12:00:23.2997,I,3764,0025 OrderManager Recv NotifyEvent = Type=2,Account=*@BROADCASTNEWS,Value=BROADCASTNEWS
12:02:44.4187,I,3764,0013 UpdateService.UpdateCheck : start
12:12:44.4321,I,3764,0013 UpdateService.UpdateCheck : start
12:22:44.4444,I,3764,0033 UpdateService.UpdateCheck : start
```

**Comment by yasuyuki-nakazawa** [comment]
東証側のデータロストに関しては、何らかのデータ喪失であり、再起動により復旧（ロストデータを含めた取得）できるものではありません。
・事象としては、データが取得できなくなった後には一切情報更新されていないということでしょうか？
・対象はPushという認識で会っていますか

**Comment by hori-ryota** [comment]
> ・事象としては、データが取得できなくなった後には一切情報更新されていないということでしょうか？

はい、PUSHに接続しっぱなしにしていたところ12:06以降はデータが受信できていないようでした

> ・対象はPushという認識で会っていますか

はい、PUSHです

**Comment by kujiracapital** [comment]
私も昨日は接続しっぱなしでしたが、私の環境では12:05以降も引けまで問題なく取得できているようです。

**Comment by hori-ryota** [comment]
@kujiracapital 情報ありがとうございます！

**Comment by hori-ryota** [comment]
本日も私の環境では午後から取得が止まっていたようです。

こちら、データを送出しているかのデバッグログの取り方など、なにかデバッグの取っ掛かりなどございましたらご教示願えますと幸いです。

**Comment by yasuyuki-nakazawa** [comment]
@hori-ryota 
コネクション自体が切断されたりしているわけではないのですよね。
データが創出されているかのデバック方法は、現状思いつかないです。申し訳ございません。
また、当件が取引所の件に起因しているかの確証がもてておりません
kabuｽﾃｰｼｮﾝの時価情報も止まっているということはないのですよね

**Comment by hori-ryota** [comment]
> kabuｽﾃｰｼｮﾝの時価情報も止まっているということはないのですよね

APIしか起動していないため、明日の実行で確認してみます。

**Comment by masaki64** [comment]
こちら、東証障害に関してですが、kabuｽﾃｰｼｮﾝとして影響が出るPUSH機能については、
もう影響がない認識でいてよろしいでしょうか。
16日ごろ～昨日まで、Pushにおけるデータの間引き（不足）が多く、質問させていただきました。
（Pushされたデータをもとに、1分足を作成しているのですが、合わない部分があるため）

ご確認お願い致します。

**Comment by yasuyuki-nakazawa** [comment]
kabuｽﾃｰｼｮﾝAPIとして、東証障害の影響はない認識でおります。
今後足データの取得を実施できるような検討を行っております

**Comment by hori-ryota** [comment]
> APIしか起動していないため、明日の実行で確認してみます。

こちら、別途インフラ環境のトラブルのため実施できず未確認です。別環境に移植作業をしているので、終わり次第あらためて確認いたします。

**Comment by masaki64** [comment]
> kabuｽﾃｰｼｮﾝAPIとして、東証障害の影響はない認識でおります。
> 今後足データの取得を実施できるような検討を行っております

ご確認くださり、ありがとうございます。
・現状、pushで配信される(間引かれるデータ)は、いつ、どのような条件で間引かれるのでしょうか。(取引量が多い時間帯など)
・pushの改善は、1分足配信の前にされるのでしょうか。
・1分足取得は、リアルタイム出されるような想定でしょうか。(9時2分に、9時1分の分足が取得可能)

**Comment by hori-ryota** [comment]
> > APIしか起動していないため、明日の実行で確認してみます。
> 
> こちら、別途インフラ環境のトラブルのため実施できず未確認です。別環境に移植作業をしているので、終わり次第あらためて確認いたします。

こちら、インフラ環境を変えたところ再現しなくなりました。元の環境が壊れてしまったので再現条件は確認できておりません（すみません）。

もし再発したら別issueとするので、私のこの件はclose扱いでお願いします。

**Comment by hori-ryota** [comment]
> @yasuyuki-nakazawa
> > kabuｽﾃｰｼｮﾝAPIとして、東証障害の影響はない認識でおります。
> > 今後足データの取得を実施できるような検討を行っております
> 
> ご確認くださり、ありがとうございます。
> ・現状、pushで配信される(間引かれるデータ)は、いつ、どのような条件で間引かれるのでしょうか。(取引量が多い時間帯など)
> ・Pushの改善は、リリースの予定はあるのでしょうか。
> ・pushの改善は、1分足配信の前にされるのでしょうか。
> ・1分足取得は、リアルタイム出されるような想定でしょうか。(9時2分に、9時1分の分足が取得可能)

こちら、マシン負荷などが間引き条件に影響があるかは気になりますね（意外と低スペックのマシンでもPUSH APIの受け取りはできていそうなのですが、負荷を考慮して間引きされるならスペックに余裕をもたせたいため）
