### ISSUE TITLE
【要望】FXもAPIトレードできるようにしていただきたいです

### ISSUE THREAD

**Issue by masaux** [kabucom/kabusapi#247]
店頭・くりっく365問わず、FXもAPIトレードできるようにしていただきたいです。
現状、kabuステーションにFXが乗っていませんので、なかなか難しいかとは思いますが、将来的に対応いただけますと幸いです。
8～9年前の公式プレスリリースではMT4への対応も検討中のようでしたが、シストレFX公開後、進んでいないようでした。
シストレFXではテクニカル以外の複雑な変化率などを実装出来ずにいます。
目下、カブステAPI大改修で大変ご多忙と存じますが、ご一考いただけますと幸甚です。

**Comment by yasuyuki-nakazawa** [comment]
FX APIのご要望は多く頂戴しておりまして、検討させていただきます

**Comment by masaux** [comment]
ご検討いただき、ありがとうございます
