### ISSUE TITLE
APIの内容について

### ISSUE THREAD

**Issue by toshigood2007** [kabucom/kabusapi#248]
お世話になります。

APIをPythonで動かす場合について教えて下さい。

発注、決済を、自動売買±指値とかを組み込めるのでしょうか？

よろしくお願いします。

**Comment by kujiracapital** [comment]
指値で発注・決済して自動売買できます。

**Comment by toshigood2007** [comment]
自動売買±指値みたいに、始値から10円下がった買い、30円上がったら決済との自動売買はできると考えて良いのでしょうか？

**Comment by kujiracapital** [comment]
はい可能です。

**Comment by toshigood2007** [comment]
対応、ありがとうございます。

可能ということなので、追加質問お願いします。

私は、プログラミングには、無知に近いです。
それで、プログラマーに頼む時は、どのようなところから、一旦知識を得て、
指示すれば良いのでしょうか？

プログラマーは、株の知識をもっていなので、始値とか指値などの理解がありません。
それで、私が一旦知識を入れないと、指示をできないと感じました。

よろしくお願いします。

**Comment by kujiracapital** [comment]
基本的なことを本などでご自身で勉強するか、株の知識があるプログラマーを探すことになると思います。
株に限らずソフトウェアの外注全般に言えることです。
ここはkabuステーションapiに関する質問・要望・不具合報告の場なので、質問の場を変えたほうが良いです。

標題の内容が解決したら、"Close issue"してください。
他のissueで同じ質問をしているので、そちらもお願いします。

**Comment by toshigood2007** [comment]
>質問の場を変えたほうが良いです。

わかりました。
お手数をおかけしました。

**Comment by yasuyuki-nakazawa** [comment]
kabuｽﾃｰｼｮﾝAPIとしては、基本的には、成行、指値の条件指定となります。
お客様の方で時価情報を取得して、その値段をもとに発注するという処理を組み込む必要があることを補足させていただきました。
