### ISSUE TITLE
【要望】sendorderのExpireDayについて

### ISSUE THREAD

**Issue by kabucomapi** [kabucom/kabusapi#25]
一般信用の売り銘柄の一部には、注文有効期限を当日しか指定できないものがあります。
そのような銘柄については、土日祝日や発注する時間帯を考慮して発注有効期限を決定する必要があり、誤発注の原因となります。
そこで、ExpireDayに当日のみを指定できる仕様と追加していただきたい。

ExpireDay | integer <int32> 必須注文有効期限yyyyMMdd形式

**Comment by yasuyuki-nakazawa** [comment]
目下検討しておりますが、ご指摘の観点から、利便性向上を行うために、
「当日」に加えて、「週末」というものを追加しようと検討中です

**Comment by kabucomapi** [comment]
ありがとうございます。非常に使い勝手が向上します。

**Comment by yasuyuki-nakazawa** [comment]
「週末」設定に関しては、お時間かかってしまいますので、取り急ぎ、「当日」の設定をご対応させていただきます
2020年9月3日（予定）のkabuステーションバージョンアップにて当機能を追加いたします
