### ISSUE TITLE
【要望】InternalServerError時のレスポンスに含まれるCodeとMessageの一覧がほしい

### ISSUE THREAD

**Issue by kujiracapital** [kabucom/kabusapi#252]
約定済みの注文に対して、PUT /cancelorderをリクエストすると、
InternalServerErrorが発生し、エラーレスポンスの内容を確認したところ、
{"Code":43,"Message":"該当注文は既に約定済です"}
となっていました。
エラーの内容で処理を分岐したいので、どのリクエストの時にどの組み合わせのCodeとMessageが発生しうるか事前に把握したいです。
よろしくお願いいたします。

【質問】として投稿していましたが、なさそうなので【要望】に変更しました。

**Comment by yasuyuki-nakazawa** [comment]
リファレンスの戻りの部分をご確認ください
エラーリターンのパターンに関しては可能な限り掲載させていただいております。

**Comment by kujiracapital** [comment]
@yasuyuki-nakazawa 
リファレンス確認していますが、InternalServerError時のコードは無いように思われます。
実際、{"Code":43,"Message":"該当注文は既に約定済です"}はないです。

**Comment by cyber-minion** [comment]
こちらのページを追加しましたので、クローズさせていただきます。
https://kabucom.github.io/kabusapi/ptal/error.html
