### ISSUE TITLE
【質問】キャンセルオーダーで「商品エラー」となる件

### ISSUE THREAD

**Issue by ita3github** [kabucom/kabusapi#254]
ご担当者様

PHPでAPIを使うコードを組んでいます。
「注文取消」で、正しい情報を設定しても商品エラーがでます。
商品エラーとなる場合を教えてください。
対象の注文は「予約中」となっています。

Array
(
    [http] => Array
        (
            [method] => PUT
            [header] => Content-type: application/json
X-API-KEY: キー***
            [ignore_errors] => 1
            [protocol_version] => 1.1
            [content] => {"OrderID":"受付番号***","Password":"パスワード***"}
        )

)
Array
(
    [0] => HTTP/1.1 400 Bad Request
    [1] => Content-Length: 44
    [2] => Content-Type: application/json; charset=utf-8
    [3] => Server: Microsoft-HTTPAPI/2.0
    [4] => X-Content-Type-Options: nosniff
    [5] => X-XSS-Protection: 1; mode=block
    [6] => X-Frame-Options: DENY
    [7] => Content-Security-Policy: default-src 'none'
    [8] => Access-Control-Allow-Origin: *
    [9] => Date: Sat, 27 Feb 2021 04:57:24 GMT
    [10] => Connection: close
)
{"Code":4002005,"Message":"商品エラー"}

**Comment by cyber-minion** [comment]
httpリクエストはJSON形式に変換していないからと考えられます。

こちらを
`[content] => {"OrderID":"受付番号***","Password":"パスワード***"}`

```
[content] => json_encode(array(
                              'OrderID' => '受付番号***',
                              'Password' => 'パスワード***'
	                      )
                        )
```
上記のコードにて書き換えて、再度お試しいただけますでしょうか。

**Comment by takei0723** [comment]
すみません、私も似た現象が出たため質問させてください。

＜現象＞
信用取引の返済注文の予約になっているものがキャンセルされない。
タイミングは取引時間外。
レスポンス：{'Code': 4002005, 'Message': '商品エラー'}

ほかの状態であればキャンセルされます。
・信用返済予約注文：キャンセルNG
・信用新規予約注文：キャンセルOK
・信用返済通常注文：キャンセルOK（取引時間中）
・先物返済予約注文：キャンセルOK

＜環境＞
OS : Windows10 home
program : Python 3.7.3

なにかわかりますでしょうか？
よろしくお願いします。

**Comment by cyber-minion** [comment]
該当注文の市場が「SOR」になっていないかをご確認いただけますでしょうか。

**Comment by takei0723** [comment]
ご返信ありがとうございます。
ご指摘の通り、手動でSORで発注を出した注文でした。
SORで発注を出したものに対してAPI経由でのキャンセル方法はありますか？

**Comment by cyber-minion** [comment]
kabuステーションAPIは、SORでの発注またはその発注に対するキャンセルは対応しておりませんので、ご了承ください。

**Comment by takei0723** [comment]
了解しました。
いつかSORの発注／キャンセルにご対応いただけたらいいなと思います。
ありがとうございました。

**Comment by yasuyuki-nakazawa** [comment]
SORは各種調整の上、対応検討させていただきます。
当件はCloseさせていただきます
