### ISSUE TITLE
±指値→Uターン注文→約定±指値注文をPythonのコードで実現したい【質問】

### ISSUE THREAD

**Issue by toshigood2007** [kabucom/kabusapi#255]
お世話になります。

現在、注文画面で使っている、±指値→Uターン注文→約定±指値注文をPythonのコードで実現したいです。
どのように記述すればいいのでしょうか？

例えば、
始値より－100円で買い→Uターン注文→約定より＋100円で決済を実現したいです。

よろしくお願いします。

**Comment by toshigood2007** [comment]
回答がありません。
説明が不足しているのでしょうか？

**Comment by hirocha** [comment]
ここはAPIの機能に関する質問・要望を行うところですので、bot開発に関する質問は別の場所で行うべき、ということかも？
しかし、ご質問のような売買方法の具体的なコードサンプルがあったほうが多くのプログラミング初心者が助かるでしょうし、カブステAPIの発展にも繋がると思いますので、公式さんにはフォーラム的なサイトを用意していただけるとありがたいですね。


2点アドバイスさせて下さい。

コーディングの質問の際は、まずは自分が努力して書いたコードを記載することがマナーです。
質問者のコードが元となって、ここがおかしいとかこう書いたほうがいいといった建設的なやり取りに繋がるのです。

また、文面から察するにPythonの基礎知識が備わっていらっしゃらないようにお見受けします。
まずはプロゲートやドットインストールなどの学習サービスを使ってPythonの基礎を学ばれることをオススメします。
修了したならば自ずと解決できるはずです。

**Comment by toshigood2007** [comment]
hirochaさん、対応ありがとうございます。

>自分が努力して書いたコードを記載することがマナーです。
>基礎知識が備わっていらっしゃらない

そうですね。
少しでもヒントをもらえればと書き込みました。
初心者では、難しすぎました。
