### ISSUE TITLE
【不具合】信用口座を閉鎖すると利用できなくなる。

### ISSUE THREAD

**Issue by yyinz** [kabucom/kabusapi#257]
■[必須] 不具合事象(概要)
信用口座を閉鎖（現物口座はそのまま）したところ、APIを利用することができなくなる。

■[必須] 本来想定されるアクションと事象
エラーが発生しない。

■[必須] 不備発生時刻（常時の場合は、常時で記載ください)
常時

■[任意] お使いの環境(OS、Excelのバージョン等)、サンプル(Macro、アドインのバージョン）

■[任意] 不備部分のログ
`{'Code': 100204, 'Message': '「信用取引口座設定約諾書」のご確認/お手続きがお済みでないた め、お取引を承ることができません'}`

**Comment by ybangit** [comment]
違っていたらすみません。

APIが利用できなくなったのは、信用口座を閉鎖されたことで、
kabus API の利用条件を満たさなくなったことが原因ではないでしょうか？

-----------------------------------------------
https://kabu.com/company/lp/lp90.html  
 => kabuステーション® Fintechプラン以上の適用が必要になります。

https://kabu.com/kabustation/services.html#2 
 =>Fintechプランの適用条件 :  信用取引口座または、先物オプション取引口座開設済みかつ、前月当社全取引における約定回数が1回以上ある場合
-----------------------------------------------

**Comment by yyinz** [comment]
@ybangit さん
コメントいただきありがとうございます。
そのような可能性は考えていませんでしたので、なるほどと思いました。
しかし、先物オプション口座は開いたままですので、Fintechプランが2021/04/01まで利用可となっていました。
「kabuステーションAPI」の欄も同様に利用可と表示されております。

**Comment by ybangit** [comment]
@yyinz さん
横から失礼しました。

私は以前、利用条件を満たさずAPI を１か月間も使えないという苦い経験がありましたので
それを思い出しました。

早く復旧されるといいですね。

**Comment by yasuyuki-nakazawa** [comment]
@yyinz 
不備部のログですが、これは認証実行時のログでしょうか？発注実行時のログでしょうか

**Comment by yasuyuki-nakazawa** [comment]
@yyinz  さん
想像ですが、APIとしては利用できており、現物発注時にエラーとなっているのではないでしょうか
考えられるケースとしては、FundType資産区分（預り区分）が信用代用になっており、この部分を修正していないからということではないでしょうか。一推測での回答となり恐縮ですが、ご確認いただけると幸甚です

**Comment by yasuyuki-nakazawa** [comment]
こちらクローズさせていただきます
