### ISSUE TITLE
【質問】通知音につきまして

### ISSUE THREAD

**Issue by kabu3995** [kabucom/kabusapi#259]
APIでの発注、約定はKABUSTATIONからは音は出ないのでしょうか。
特に約定については音が出てくれると助かります
約定を確認してからこちら側でおとを出そうとするのも蛇足すぎますので。

**Comment by cyber-minion** [comment]
通知音が有効になっていれば、発注、約定時に音は出ます。
設定方法は、kabuステーションの「システム設定」→「通知」タブ、になります。

**Comment by kabu3995** [comment]
デイトレ板をクリックすれば発注の音が出ますが
API経由ですと出ません

約定と失効は出ましたかね
それはAPIの発注の手を離れたツール内の出来事だからかもしれません

**Comment by kabu3995** [comment]
約定もどうだったか、、IOCの失効だったよな

**Comment by yasuyuki-nakazawa** [comment]
現在、kabuｽﾃｰｼｮﾝとしては、以下の通知（音だし、ホップアップ通知）が可能となります
注文受付、注文完了、訂正受付、訂正完了、取消受付、取消完了
全部約定、一部約定、期限切れ執行

**Comment by yasuyuki-nakazawa** [comment]
こちらクローズさせていただきます
