### ISSUE TITLE
【質問】Windowsパソコンが必須ですか？

### ISSUE THREAD

**Issue by chocopon** [kabucom/kabusapi#261]
Windowsのアプリケーションがローカルサーバーになるような仕様に見えます。
AWSのようなクラウドサーバーでの運用を考えていたのですが、ローカルPCが必要ですか。

**Comment by tsuchinaga** [comment]
動作させるだけならAWS ec2のwindows osにRDPでも動くのではないかと思います。

ただ、規約にkabuステーションが動作しているマシンの外にデータを持ち出してはいけないので、開発・デバッグは実質不可能じゃないかと思います
