### ISSUE TITLE
【要望】移動平均乖離率

### ISSUE THREAD

**Issue by kyoutarou719** [kabucom/kabusapi#263]
PUSH API リファレンスを確認いたしましたが、
移動平均乖離率
は取得できないでしょうか？　
（他社RSSから乗り換え検討中です）

**Comment by yasuyuki-nakazawa** [comment]
現状PUSHでの移動平均乖離率は取得できません

**Comment by yasuyuki-nakazawa** [comment]
情報系の拡張は順次検討しておりますが、現状配信している情報の計算から導き出せる項目の追加優先度は低いです。
まずは、過去分のTICK情報の配信等で過去を含めた推移の把握、そこからの計算による記載いただいたような移動平均乖離率の算出を円滑に実施頂ける情報の追加を優先して検討させていただいております。
