### ISSUE TITLE
評価損益（単純損益ー諸費用ー税金）はどの様に取れますか？約定照会ではCommission（RecType=8)では常に０です。【質問】

### ISSUE THREAD

**Issue by hsaeki2013-A** [kabucom/kabusapi#265]

**Comment by yasuyuki-nakazawa** [comment]
約定照会のCommissionは、「手数料」となります。
評価損益は、positionsメソッドのValuation(評価金額)で取得ができると思います。

１．現状の残高照会にある評価損益
現状、カブステの評価損益には、諸経費が含まれない金額となっています。
諸経費という項目が別にありますので、そちらを参照して頂くようにお願いします。

２．7月上旬以降の残高照会にある評価損益
カブステの残高照会にある評価損益に諸経費を含めるように仕様を変更する予定です。
リリースは、7月上旬を予定しています。

**Comment by yasuyuki-nakazawa** [comment]
当件はクローズさせていただきます
