### ISSUE TITLE
【要望】歩み値のpush配信

### ISSUE THREAD

**Issue by kujiracapital** [kabucom/kabusapi#268]
現状のpush配信は気配の更新ごとに配信されますが、約定ごとに約定値や時刻のみ配信されるAPIがほしいです。

**Comment by yasuyuki-nakazawa** [comment]
kabuｽﾃｰｼｮﾝでいうと、Time’Salesの画面が対象の機能画面となりますので、この画面を介して、歩み値を提供することができると考えております。
過去分の取得も可能なのですが、サーバへの問合せ負荷が課題となっており、今しばしお待ちいただけると幸甚です。

**Comment by cyber-minion** [comment]
本件は回答済ですので、一旦クローズさせていただきます。
