### ISSUE TITLE
【質問】日経平均株価の値を取得したい

### ISSUE THREAD

**Issue by hiroaki425** [kabucom/kabusapi#27]
お世話になっております。
kabuSTAION_API_PUSH_sampleのエクセルを参照しているのですが、このエクセル内に日経平均株価の値をリアルタイムで表示させたいのですが、対応していますでしょうか？
ご確認よろしくお願い致します。

**Comment by cyber-minion** [comment]
ご質問いただき、ありがとうございます。ご質問いただきました件は、対応いたしております。
方法は、以下の通りです。
 
【方法】
①銘柄登録
　API登録銘柄リストに下記のように日経平均株価を登録する。
　{'Symbol': '101', 'Exchange': 1}
②PUSH配信
　「websocket」APIを実行する。

**Comment by yasuyuki-nakazawa** [comment]
当件、現状展開しているExcelMacro ver1.1 では日経平均のリアルタイム受信ができないものとなっております。
次回の更新にて当指数のマクロ対応版を公開させていただきます。
