### ISSUE TITLE
【質問】

### ISSUE THREAD

**Issue by ChuChuBuzzO** [kabucom/kabusapi#270]
kabu station apiで売買自動化を試みようとしている者です。
API説明を見る限り恐らく無理なのだと理解しておりますが、本apiで分足や日足を各銘柄に関して取得することは出来ないのでしょうか?

自動化する上で戦略決めにはほぼ必須だと思われるのですが..
また、GUIを介さず、取得を可能にする方法などはありませんでしょうか?

**Comment by hirocha** [comment]
https://github.com/kabucom/kabusapi/issues/204
既出です。
現状、カブステAPIにはお望みの機能はありませんね。
岡三RSSを併用されている方が多いのではと想像しています。


初心者の方が気になるような質問事項はすでにほぼ出尽くしています。
IssuesのOpen Closeともに全て目を通すか検索を駆使するなどしてから質問しましょう。

また概要のわかるタイトルを付けましょう。

**Comment by ChuChuBuzzO** [comment]
念のため聞いてみました。
ありがとうございました。
