### ISSUE TITLE
【要望】定義書の破壊的変更のアナウンスがほしい

### ISSUE THREAD

**Issue by hori-ryota** [kabucom/kabusapi#271]
yamlはドキュメント生成だけでなくparseして使用できる点が有益であり、公開しているということはparseして使用することを想定しているかと思っております。

破壊的な変更が入る場合はサードパーティツールも追従して更新する必要が生じます。

[updated the reference · kabucom/kabusapi@ded73f4](https://github.com/kabucom/kabusapi/commit/ded73f46ff1c5d504eea799cc87d6ccae12438a0)

のような定義書の破壊的変更の場合、事前のアナウンスやフォーマットのレビューなどが行えるとコミュニティとして有益かと思いますのでご検討願いたいです。

**Comment by hori-ryota** [comment]
yamlの破壊的な変更は

> [【要望】oneofの仕様を避けたい、用途ごとにAPIを分割して欲しい · Issue \#234 · kabucom/kabusapi](https://github.com/kabucom/kabusapi/issues/234)

の

> 今後はリリース前に想定変更という形でリファレンスの先行公開をさせていただき、このようなご意見をいただけるようにさせていただきます

と同じように扱っていただけるととても助かります。

**Comment by yasuyuki-nakazawa** [comment]
了解しました。ご不便をおかけしております。
次回のアップデートの情報の先行公開を次週検討します

**Comment by yasuyuki-nakazawa** [comment]
今後は先行してアップデートを別ブランチにて公開する運用とさせていただきます

**Comment by cyber-minion** [comment]
リリース前に先行してアップデートを別ブランチにて公開する運用をしておりますので、クローズさせていただきます。
