### ISSUE TITLE
【質問】定義書の修正プルリクエストは作成してもいいのか

### ISSUE THREAD

**Issue by hori-ryota** [kabucom/kabusapi#273]
定義書について軽微な修正や調整の希望などがある場合、プルリクエストにて相談も可能でしょうか。

issue上で相談し対応いただくフローでもいいのですが、ドキュメントの調整やバグ修正などはプルリクエストを取り込んでいただければ互いに楽ですし、修正後のコードを見ながらのほうが議論も捗りそうに思います。

直近で有り得そうなプルリクエストの例は以下のようなものです

- yamlのindent修正
- ドキュメントのUI調整、伴うyamlのDescription系の調整
- 複数箇所で定義されている型のcomponent化

**Comment by yasuyuki-nakazawa** [comment]
いつもありがとうございます。
是非PullRequestの要望にはお答えしていきたいところです。
一旦当方でお預かりいただき、反映を検討する方向で進めさせていただければと思います
