### ISSUE TITLE
【要望】オートネッティング注文

### ISSUE THREAD

**Issue by Ros522** [kabucom/kabusapi#274]
いつもお世話になっております。
一つ要望させていただきます。

両建てを防ぎたく、注文方法として新規返済を自動的に判別する機能
オートネッティング注文の実装を希望いたします。
現行の仕様でもポジション情報を元にこちら側で返済、新規注文を分けて注文することは可能ですが
いわゆるドテンの際に、１つの注文で完結したい　という思いがあります。

#　kabuステーションのAPIというよりはkabuステーション自体に機能があるかどうかかもしれませんが・・

**Comment by yasuyuki-nakazawa** [comment]
ドテンのニーズも強く、一時は検討したことがあったのですが、１注文で新規、返済を両方で制御するのは一部トランザクションの失敗リスクもあることから、ドテンの機能追加は実施しておりません。
kabuｽﾃｰｼｮﾝとしては、2wayという発注画面はありますが、こちらは売買の別だけを指定することでポジションがあれば返済、なければ新規といったように発注をかけることはできますが、ドテンの機能を有しておりません。

現状は大変お手数ではございますが、返済、新規と2注文を出していただく必要がございます。

**Comment by Ros522** [comment]
ご回答ありがとうございます。
返済、新規で出すようにします。
