### ISSUE TITLE
【要望】株ステーション自動起動用のツールを提供してもらいたい

### ISSUE THREAD

**Issue by gatehub1496** [kabucom/kabusapi#275]
株ステAPIを日々利用させていただいております。

PC起動後に都度、株ステーションを手動起動させるのが大変煩わしいです。
やろうと思えばUWSC等のツールを使用して自動起動させる事も可能とは思いますが、
株コム側からそういった自動起動用のツールを提供していただくことは出来ないでしょうか。

また、株ステを起動しっぱなしでも日を跨ぐとTokenの有効期限が切れるのか株ステを再起動しなければいけなくなります。
この辺の手間が少なくなると大変助かります。よろしくお願いいたします。

**Comment by yasuyuki-nakazawa** [comment]
大変申し訳ございませんが、kabuステーションを自動起動させるツールの提供は現状検討しておりません。
お手数をお掛けして恐縮ですが、こちらは各人でご準備いただけると幸甚です。
本来はオープンAPIのような形で個人向けのAPI解放できることが好ましいのですが、こちらに対しては、
超えるべき多くの課題があり、今回はいち早くAPIというソリューションをお客様にご提供するという趣旨で、カブステーションを介してインターフェース公開する方式をとらせていただいております。
ご面倒をお掛けしますが、クライアントの起動、停止、制御はお客様の方で実施いただけますよう、宜しくお願いいたします
