### ISSUE TITLE
【不具合】決算期日3月の銘柄のFiscalYearEndBasicが202103xxにならない

### ISSUE THREAD

**Issue by Taqman-probe** [kabucom/kabusapi#278]
■[必須] 不具合事象(概要)
KDDIのSymbolを指定し、銘柄情報を取得したところ、FiscalYearEndBasicは20210203が返されました

■[必須] 本来想定されるアクションと事象
https://kabucom.github.io/kabusapi/reference/index.html#operation/symbolGet
のResponse samplesは20210331となっています。
YYYYMMDD形式のようなので、FiscalYearEndBasicは20210331が正しいと思います。

■[必須] 不備発生時刻（常時の場合は、常時で記載ください)
常時

■[任意] お使いの環境(OS、Excelのバージョン等)、サンプル(Macro、アドインのバージョン）
OS: Windows 10

/kabusapi/symbol/9433@1
の2021/03/22時点での結果:
{
  "BisCategory": "5250      ",
  "TotalMarketValue": 8039282449950.0,
  "TotalStocks": 2355373.0,
  "FiscalYearEndBasic": 20210203,
  "KCMarginBuy": true,
  "KCMarginSell": true,
  "MarginBuy": true,
  "MarginSell": true,
  "DisplayName": "ＫＤＤＩ",
  "Exchange": 1,
  "ExchangeName": "東証１部",
  "TradingUnit": 100.0,
  "PriceRangeGroup": "10003",
  "UpperLimit": 4189.0,
  "LowerLimit": 2789.0,
  "Symbol": "9433",
  "SymbolName": "ＫＤＤＩ"
}

**Comment by cyber-minion** [comment]
FiscalYearEndBasicは、次回決算報告がありましたら更新されます。
※公式サイトによりますと、2021年2月3日は、2021年3月期第3四半期報告書を掲載した日となります。

**Comment by Taqman-probe** [comment]
ご返信ありがとうございます。
kabuステーションAPIリファレンスによると、
> FiscalYearEndBasic
> integer <int32>
> 決算期日
> ※株式銘柄の場合のみ

と記載されています。

> 2021年3月期第3四半期報告書を掲載した日

というのは決算期日といえるでしょうか。
決算期日というのは損益を集計する一年単位での最終日であり、月末日が返るのが妥当ではないでしょうか。
レスポンスの値か、kabuステーションAPIリファレンスの記載のどちらかが間違っていると思います。

**Comment by yasuyuki-nakazawa** [comment]
情報更新します
決算情報に関しては、3/22より情報ソースが変更となっているため発生している事象であると推測されます。
こちら、改善を検討しております。
今しばらくお待ちくださいませ

**Comment by yasuyuki-nakazawa** [comment]
こちら、2021年3月30日に改善対応させていただきました。
