### ISSUE TITLE
【要望】注文訂正API　→【見送り】

### ISSUE THREAD

**Issue by hitsuji7** [kabucom/kabusapi#28]
新規注文、注文取消に加え `PUT /editorder` のような注文訂正APIを要望いたします。

**Comment by yasuyuki-nakazawa** [comment]
訂正機能に関してですが、今後SORへの対応を見込んでおります。
SORの仕様上、訂正を認めておりませんので、APIは発注と取消というシンプル仕様とすること、SORの仕様との兼ね合いもあり、訂正機能の導入は一旦見送る方向とさせて頂きます。
お手数をおかけしますが、取消し後の再発注でご対応の程、よろしくお願いいたします。
