### ISSUE TITLE
【質問】pythonでの日経先物の決済方法

### ISSUE THREAD

**Issue by e1231** [kabucom/kabusapi#280]
お世話になります。
非常に基本的な質問で申し訳ありませんが、日経先物の決済のコード記述をご教授いただけないでしょうか？

python3.8 を使用しており、発注はコーディングできております。

特にわからないのは決済するポジションの指定方法とsideの指定方法です。
基本的にはすべてのポジションを成り行きでクローズできれば良いと考えております。

以下の項目は何をしていしたらいいのでしょうか？
"ClosePositionOrder": 
"ClosePositions": 
よく理解できず、数量と優先順位を指定すればいいのか？、と解釈して、
Qty:1
"ClosePositionOrder": 0
と指定してコードを実行させましたが
{'Code':1009001, 'Message':建玉が指定されておりません`}
というエラーが出て決済できませんでした。

sideというのは、
買い玉を決済するときは"1"と指定するのでしょうか？"2"と指定するのでしょうか？
（エントリーと同じ数字を使うのか、反対売買なので逆の数字なのか？）
売り玉を決済するときはどうでしょうか？

各項目について私の理解できている部分と、理解できていない部分を記載します。
"Password": "xxxxxx"　#これはパスワード,
"Symbol": "165120019", ＃これは別のリクエストで取得できています
"Exchange": 23, #日中なら23、夜間は24
"TradeType": 2, #返済なので2
"TimeInForce": 2,#これはとりあえずFAKでいいです
"Side": "1",　#これは売り玉に対しては"1"で決済するのでしょうか、"2"で決済するのでしょうか？買い玉なら？
"Qty": 1,　＃数量１
"ClosePositionOrder": null,＃これがよくわかりません。全玉決済はどうやったらいいのでしょうか？
"ClosePositions": [{}], #こちらもよくわかりません。別のリクエストで取得するのでしょうか？
"FrontOrderType": 120, #成り行き
"Price": 0,　#成行
"ExpireDay": 0 #当日

よろしくお願いいたします。

**Comment by seattlesbest** [comment]
お困りのようですので、少しだけ。

全てリファレンス
https://kabucom.github.io/kabusapi/reference/index.html
サンプルコード
https://github.com/kabucom/kabusapi/releases/tag/Python-v1.3.0

にて解決できます。

おそらく、現在本部の方々は機能改修とメンテなどで、リソース不足でしょうから、
ドキュメンテーションなどは後回しになっている様子です。

先物でも、OrdTypeと言う項目が約定照会ででるのですが、コードが記載されておらず
現物のFrontOrderTypeを参照してもそれとは違うコードが出ていたりと。。。
とりあえず、よくわからない列はリストにするときに、デリートして整形すると見た目もよくなり便利です。

なので、困ったときに一番いいのは、
指し値を約定しない高い（安い）金額にするなどして、発注をしてみて確認することです。
また、パラメータで確かによくわからないものも多いのですが、
サンプルコードにサンプルパラメータが記載されてますので、それで殆ど理解できます。

とにかく全てのサンプルコードをそのまま使ってみるところからかと存じます。

私のメモ抜粋しておきます。

            # 'ClosePositions': [{'HoldID':'E2021031904444','Qty':1}],
            # 'ClosePositions': [{'HoldID':ei,'Qty':eq}],#newの場合は入れていても反応しない
            'ClosePositionOrder': eo,#exit時に両方指定するとエラー # 0	日（古）損（高） 1:	日（古）損（低）2:	日（新）損（高）3:	日（新）損（低） 4:	損（高）日（古）5:	損（高）日（新）6:	損（低）日（古）7:	損（低）日（新）

ともに頑張って参りましょう。

**Comment by e1231** [comment]
親切にご回答いただき、どうもありがとうございます。

実際に売買をやってみたところ
Qtyに数量を入れて、
'ClosePositionOrder'に4を入れたところ買戻しができていました。

どうもありがとうございます！
