### ISSUE TITLE
【質問】カブステーション上のAPI銘柄登録リストは再起動すると消えてしまうのでしょうか？

### ISSUE THREAD

**Issue by seattlesbest** [kabucom/kabusapi#282]
下記によりますと
https://kabucom.github.io/kabusapi/reference/index.html#tag/register

PUSH配信する銘柄の登録や解除を行います。
登録された銘柄はkabuステーションのAPI登録銘柄リストに表示されます。

とありますが、この画面はどこから入れるのでしょうか？
投資情報＞銘柄登録リスト（リスト）にもありませんでした。

**Comment by kabusukebe** [comment]
APIアイコン（</>）の右クリックメニューから開けます。
![image](https://user-images.githubusercontent.com/70708663/112878901-69bf3480-9103-11eb-9ac0-b817ce3fd73a.png)

**Comment by seattlesbest** [comment]
@kabusukebe 
このマークがそれだったんですね。助かります。
しかも、右クリックからしか入れないしマニュアルにも記載がないから、ちょびっとわかりずらいというUI設計。。。。


他のWindowsForms10.BUTTON.app.XXXのクラスは全て左クリックで何らかのactionが設定されているのですが。。。
３つ並べたかったのでとりあえず右クリックでメニュー表示させたのではと、今理解しました。

投資情報の登録銘柄リストの下にも投資銘柄リスト（API）という表記で
ショートカットがあってもいいのではと思いました。（これは重要度低い要望ということで。。。）


ちなみに、このAPI銘柄登録リストは、カブステーションを再起動すると消えてしまうのですが、

そういう仕組みなのでしょうか。
銘柄登録リストに入れると遅延しにくくなる改善が行われたということで、
期待しながら、その指示に従うように設計を変更しました。

が、
皆様は、RESTで各種情報を呼び出す為に、その最初の段階で、一度全ての銘柄を起動の度に、
再度登録しなおしてから
http://localhost:18080/kabusapi/board/
なり、を呼び出しているということでしょうか？

そういう仕様でしたら、それに従いますが、念のため。

**Comment by yasuyuki-nakazawa** [comment]
マニュアルに関しては確認させていただきます

APIの銘柄登録リストは再起動で初期化されます。
RESTで銘柄を呼び出す場合、普通に呼び出していただくだけで、当該銘柄リストには追加されます。
その際に、Regist処理が走り、リアルタイムでカブステーション上に時価情報がPUSHされて、保持されますので、以降はカブステーション上の問合せで情報が返りますので、極めて高速に情報を取得することが可能となります

**Comment by seattlesbest** [comment]
起動時に一括で事前にregistしてから各種処理する方がよさそうですね。トークンの空値確認と維持処理の所に同様な処理を加えておきます。
