### ISSUE TITLE
【質問】２２５先物の情報取得・発注方法

### ISSUE THREAD

**Issue by makoto-asao** [kabucom/kabusapi#289]
通常の株式の板情報などは取得できるようになりました

先物やオプションなどの情報を取得する方法を教えていただけますか？？

**Comment by tsuchinaga** [comment]
先物銘柄コード取得 や オプション銘柄コード取得 などで銘柄コードを取得し、  
取得した銘柄コードを 時価情報・板情報 に渡せば取れます

**Comment by yasuyuki-nakazawa** [comment]
こちら、上記で回答いただいておりますので、クローズとさせていただきます
