### ISSUE TITLE
【質問】トリガチェックに関するエラーについて

### ISSUE THREAD

**Issue by kwon-o** [kabucom/kabusapi#290]
pythonでAPIを利用して
注文発注を行う途中に以下のエラーが発生します。
HTTP Error 400: Bad Request
{'Code': 4002004, 'Message': 'トリガチェックエラー - 詳細はkabuSログファイルを確認してください'}

\AppData\Roaming\KabuS\Log
上記の経路のログからエラーのところを確認したら
トリガチェックエラー(sx) : ERROR_CD_000_000_102
こうゆうメッセージのみ残っていて何が問題なのか分からない状況です。

どうゆうときにトリガチェックエラーが発生するのか教えて頂きますでしょうか

**Comment by cyber-minion** [comment]
ログに出力されている「ERROR_CD_000_000_102」行の１行上に「ｘｘｘエラー」と出力されているはずですので、ご確認いただけますでしょうか

**Comment by kwon-o** [comment]
09:05:23.2189,I,10420,0001 NewsHeaders: count=5945
09:06:04.6499,I,10420,0015 ワンショットチェック : 2513/T/ＮＥＸＴ　ＦＵＮＤＳ　外国株式・ＭＳＣＩ‐ＫＯＫＵＳＡＩ指数（為替ヘッジなし）連動型上場投信/1 : amount=200, qty=
09:06:04.6499,I,10420,0015 KabuSApiManager.PreRelationCheck=CHECK_OK
09:06:04.6499,I,10420,0015 トリガチェックエラー(sx) : ERROR_CD_000_000_102

１～３行上の出力は以上です。
