### ISSUE TITLE
【質問】日経先物の板情報取得可能時間帯

### ISSUE THREAD

**Issue by chikugoy** [kabucom/kabusapi#291]
日経先物miniの

銘柄コード：166060019
市場コード：23 （日中）、24（夜間）

を銘柄登録して
https://kabucom.github.io/kabusapi/reference/index.html#tag/register

websocketで板情報を取得しています。
https://kabucom.github.io/kabusapi/ptal/push.html

日経先物の時間帯ですが日中取引は8:45から15:15、夜間取引は16:30から翌日の5:30という認識です。

本日日経先物miniの板情報をwebsocketで取得して保存していたのですが
2021-04-10 05:25以降のCurrentPriceTimeの値が下記で固定されているのに気づきました。

```
CurrentPriceTime
2021-04-10 05:25:00.000000
```

取引時間＝板情報が取得可能な時間ではない感じでしょうか？

**Comment by seattlesbest** [comment]
https://kabu.com/item/fop/rule.html#anc04

**Comment by chikugoy** [comment]
なるほど

> ※PUSH配信は、値が更新される際に配信されます。場間（昼休み）、引け後での配信はございません。

で引け後とはレギュラー・セッション（ザラバ）より後を示すと理解しました。

本件クローズしますが、この理解が違う場合等ありましたらreopenしてください。

@seattlesbest 回答ありがとうございました。
