### ISSUE TITLE
【質問】日経先物の板情報取得日中・夜間区分

### ISSUE THREAD

**Issue by chikugoy** [kabucom/kabusapi#292]
日経先物miniの

銘柄コード：166060019
市場コード：23 （日中）、24（夜間）

を銘柄登録して
https://kabucom.github.io/kabusapi/reference/index.html#tag/register

websocketで板情報を取得しています。
https://kabucom.github.io/kabusapi/ptal/push.html

Exchange:23の大阪日中の板情報が下記の時間帯で配信されています。

2021-04-10 05:56:57.903615
2021-04-09 23:55:11.863657
2021-04-08 00:02:37.836935

限定的に夜間時間帯で日中の板情報がぽろぽろとあるみたいなのですがこれはなぜでしょう？

日中時間帯でも夜間が
夜間時間帯でも日中のデータ取得される事があるという認識でよいでしょうか？

**Comment by tsuchinaga** [comment]
時価PUSH配信のリファレンスに

> ※PUSH配信は、値が更新される際に配信されます。

ってあるんで、気配値か何かが更新されたんじゃないですかね？

**Comment by yasuyuki-nakazawa** [comment]
当件ですが、tsuchinaga様記載の通り、何らかの値に変更があった際に配信されます。
TICKとしては場中しか配信されませんが、気配情報の更新の際にも情報は配信されます。
