### ISSUE TITLE
/board（時価情報・板情報の多銘柄高速データ取得）【質問】

### ISSUE THREAD

**Issue by mik2008** [kabucom/kabusapi#293]
多数の銘柄の時価情報等をなるべく高速に取得する方法があれば教えてください。
サンプルコードに従う記述だと１銘柄に対して余計な情報も含んだ一括で取得する形になっているためか、
１銘柄分の取得で１秒弱程度時間が掛かっています。
例えば特定の欲しい項目情報のみ取得するような最小限の情報で高速に取得する方法があれば教えて欲しいです。
（例えば、楽天RSSでの方式だとそのような事が実現できたのですが）

**Comment by tsuchinaga** [comment]
各銘柄ごとの初回リクエストについて、速度を改善する方法は現在提供されていません

また取得に時間がかかるのは項目が多いからではなく、kabuステーションがカブコムのサーバから情報を引っ張ってくるためです

#122

**Comment by mik2008** [comment]
なるほどありがとうございます。

**Comment by yasuyuki-nakazawa** [comment]
こちら、解決済みのように見えますが、参考までに。
銘柄情報は、取得前に事前にregistを行うことで、以降は低レイテンシーにてレスポンスが見込まれます。
