### ISSUE TITLE
【質問】

### ISSUE THREAD

**Issue by ohisamatoohirune** [kabucom/kabusapi#294]
KabuステーションAPI に興味があり、auカブコム証券への口座開設を検討する者です。

エクセルのマクロぐらいしか使えないのですが、

例えば、

特定の銘柄について、寄り付きで特定の価格範囲なら成行で買い注文を入れ、それが一定額上がったら売り、また一定額下がっても損切りする

ようなことは組むことはできますか。

ご多用な中恐れ入りますが、ご回答くださいますようお願い申し上げます。

**Comment by yasuyuki-nakazawa** [comment]
時価情報の取得は可能です
excelのアドインサンプルも提供しておりますので、組み合わせながらロジックを組んで頂くことで対応は可能と考えます

**Comment by ohisamatoohirune** [comment]
ありがとうございます！
