### ISSUE TITLE
【質問】EXCELの複数セルにVBAで=BOARD(1234,1)のように連続で入力すると、ちゃんと値が取得できるセルと、”API実行回数エラー”が表示されるセルがあります。 この原因と回避方法を教えてください。

### ISSUE THREAD

**Issue by miyato64** [kabucom/kabusapi#295]

**Comment by hishiharahaz** [comment]
@miyato64 さん
銘柄情報系のリクエストは、秒間回数の制限がかかっているためかもしれません。
【参考】
https://kabucom.github.io/kabusapi/reference/index.html#tag/info

**Comment by miyato64** [comment]
回答ありがとうございます。 最大銘柄数が50だとは知りませんでした。 RSSの最大300項目と比べて大変少ないですね。

**Comment by yasuyuki-nakazawa** [comment]
解決済みとして、クローズさせていただきます
