### ISSUE TITLE
【質問】トリガチェックに関するエラーについて 

### ISSUE THREAD

**Issue by kwon-o** [kabucom/kabusapi#297]
回答がなくて少し内容を追加して再投稿します。

pythonでAPIを利用して
注文発注を行う途中に以下のエラーが発生します。
HTTP Error 400: Bad Request
{'Code': 4002004, 'Message': 'トリガチェックエラー - 詳細はkabuSログファイルを確認してください'}

\AppData\Roaming\KabuS\Log
上記の経路のログからエラーのところを確認したら
```
ワンショットチェック : 2513/T/ＮＥＸＴ　ＦＵＮＤＳ　外国株式・ＭＳＣＩ‐ＫＯＫＵＳＡＩ指数（為替ヘッジなし）連動型上場投信/1 : amount=200, qty=
KabuSApiManager.PreRelationCheck=CHECK_OK
トリガチェックエラー(sx) : ERROR_CD_000_000_102
```
こうゆうメッセージのみ残っていて何が問題なのか分からない状況です。
どうゆうときトリガチェックエラーになるのか分からなくて推測ですが、
発注の1回目は通常の発注となりますが二回目からトリガチェックエラーになるのかと思います。 

どうゆうときにトリガチェックエラーが発生するのか教えて頂きますでしょうか

**Comment by tsuchinaga** [comment]
注文リクエストの内容を共有いただければエラーを特定できるかもしれません 

でも根本的な問題はエラーメッセージを見ても原因が分からないところなんですよね

僕もよく不明なエラーを引いて詰まります

> 08:32:01.0535,I,3580,0020 KabuSApiManager.PreRelationCheck=ERROR_CD_001_010_001  
> 08:32:01.0535,E,3580,0020 不明なエラー(ERROR_CD_001_010_001)

**Comment by kwon-o** [comment]
@tsuchinaga 
```
obj = _{'Password': self.auth['APIPassword'],_
 'Symbol': _code,_
 'Exchange': 1,
 'SecurityType': 1,
 'FrontOrderType': 27,
 'Side': '2',
 'CashMargin': 1,
 'DelivType': 2,
 'FundType': '02',
 'AccountType': 2,
 'Qty': _int(buy_qty),_
 'Price': _target_price,_
 'ExpireDay': 0}
 ```
 上記は注文リクエストです。Qty、Priceは現在の価格と保有現金をもとに計算されています。 
トリガチェックエラーはどんな状態で発生するのかが分かれば自分で対応できると思いますが、、これに関する情報はないでしょうか？

**Comment by tsuchinaga** [comment]
ログに出されるエラーの詳細については提供されてないです

共有いただいたパラメータに揃えて安い銘柄に注文を入れてみましたが、僕の口座ではFundTypeに保護が指定できないみたいで同じエラーにはなりませんでした。  

> {StatusCode:500 Body:{"Code":100031,"Message":"「預り区分」をご確認ください"} Code:100031 Message 「預り区分」をご確認ください}

**Comment by hishiharahaz** [comment]
@kwon-o さん
横から失礼します。
パスワードは伏字にしていますが、共有いただいたパラメータに、Symbol、Qty、Priceをベタ書きにして注文をしたところ発注できました。
kwon-o さんは、２回目からトリガチェックエラーになるとの事ですので、変数としているSymbol、Qty、Priceを１回目と２回目とで違いがあるか確認されると何かわかるかもしれません。

obj = { 'Password': 'xxxxxxxxxxxxxxxxx',
        'Symbol': '2513',
        'Exchange': 1,
        'SecurityType': 1,
        'FrontOrderType': 27,
        'Side': '2',
        'CashMargin': 1,
        'DelivType': 2,
        'FundType': 'AA',
        'AccountType': 2,
        'Qty': 10,
        'Price': 1427,
        'ExpireDay': 0 }

**Comment by kwon-o** [comment]
@hishiharahaz さん、コメントありがとうございます。
Qty、Priceは注文毎に変わるのが当たり前ではないですか？株価と持ってる現金が変わるので、、
発注でき株を売ったあと、また同じSymbolに対して買おうとするときに問題なく発注できるのかが気になります。

**Comment by kwon-o** [comment]
@tsuchinaga FundTypeを指定せず注文しても同じトリガチェックエラーが発生しました。。

**Comment by tsuchinaga** [comment]
試してたんですが、制限値幅下限以下の指値をするとトリガチェックエラーが出ました

もしかすると、制限値幅に引っかかっているのかもしれません

**Comment by kwon-o** [comment]
ありがとうございます。その制限値幅ってAPIで確認できますか？

**Comment by tsuchinaga** [comment]
銘柄情報のUpperLimitとLowerLimitが上限と下限です

**Comment by kwon-o** [comment]
@tsuchinaga おかげで解決できました。ありがとうございます。

**Comment by chocopon** [comment]
値幅制限、呼び値の間違い（5円単位なのに3111円で指値とか）がよくひっかかりますね。
呼び値については一覧はありますが、それ用の関数は自作するしかないようです。

**Comment by kwon-o** [comment]
@chocopon あ、確かに！！！！コメントありがとうございます。
