### ISSUE TITLE
【不具合】/board/{symbol}でHighPriceTimeが設定されない(null)ケースがある

### ISSUE THREAD

**Issue by HolyMartianEmpire** [kabucom/kabusapi#299]
■[必須] 不具合事象(概要)
日経VIの情報取得（/board/145@2）でHighPriceTimeがnullになる場合がある。
HighPirceは正しく設定されているようでした。
アプリケーション/kabuステーションを再起動しても変化なし。

その後、高値が更新(13:45)されると、正常にとれるようになりました。

■[必須] 本来想定されるアクションと事象
HighPriceTimeに時刻("2021-04-15 12:00:00")が設定される。
発生時は、前場と後場の間に高値更新しており、日経のサイトでは12:00が高値時刻となっていました。HighPriceは正しい値が設定されていました。

■[必須] 不備発生時刻（常時の場合は、常時で記載ください)
2021-04-15 12:00～13:45

■[任意] お使いの環境(OS、Excelのバージョン等)、サンプル(Macro、アドインのバージョン）
OS:Windows10
(コードはC#でOpenAPI Generatorで作成したものなので省きます。
 他の指数や銘柄は問題なく収集できており、日経VIのHighPriceTimeも前場までは正常でした。)

■[任意] 不備部分のログ
"{\"Symbol\":\"145\",
\"SymbolName\":\"日経VI\",
\"CurrentPrice\":17.13,
\"CurrentPriceTime\":\"2021-04-15T12:20:15+09:00\",
\"CurrentPriceChangeStatus\":\"0058\",
\"CurrentPriceStatus\":null,
\"CalcPrice\":16.82,
\"PreviousClose\":16.82000,
\"PreviousCloseTime\":\"2021-04-14T00:00:00+09:00\",
\"ChangePreviousClose\":0.31000,
\"ChangePreviousClosePer\":1.84,
\"OpeningPrice\":17.08,
\"OpeningPriceTime\":\"2021-04-15T09:00:15+09:00\",
\"HighPrice\":17.21,
\"HighPriceTime\":null,
\"LowPrice\":16.67,
\"LowPriceTime\":\"2021-04-15T09:09:15+09:00\"
}"

**Comment by cyber-minion** [comment]
本件はまた発生しているのでしょうか？
当該銘柄は本日12:05に高値更新し、13時過ぎに確認したところ、「HighPriceTimeが設定されない(null)」という事象がありませんでした。
![MicrosoftTeams-image](https://user-images.githubusercontent.com/69830869/116216380-86db3780-a783-11eb-8eff-26d6efb02f16.png)

**Comment by HolyMartianEmpire** [comment]
今日は発生しませんでした。
前場と後場の間の12:00～12:04で指数の取得が失敗する時間帯※があり、そのタイミングで高値更新されると発生するように見えました。

なので、発生するには、以下の条件が成立する必要があると思われます。
・12:00:00～12:04:59の間で高値を更新する
・12:05以降でその高値を更新しない
・それ以降、高値が更新されるまでその状態が継続し、更新されると時刻が設定される。
　（この間、カブステーションを再起動しても解消されない)

今日は12:05のようなので、ぎりぎりnullにならないタイミングなのだと思います。
(過去のログを確認したところ、4/1にも起こっていましたが、実際に日経VIがどうだったかまでは確認できていません。)

※毎日12:00:00～12:04:59で指数の情報の一部がかけているか失敗するのですが、
　これ自体は興味がなかったので詳細は確認していません。

**Comment by yasuyuki-nakazawa** [comment]
当件ですが、高値更新のタイミングで、高値、時刻とセットで配信されていれば、両方ともに情報が入った状態で同様に配信されますが、値段が先に配信され、その後、時刻が配信された場合は記載されているようなデータ配信状態となることもございます。
基本的には、kabuステーションが情報を受信したタイミングで、当該情報をパススルーする仕様となっておりますので、当該の記載事象が発生しているものと推測されます。

**Comment by HolyMartianEmpire** [comment]
仕様ということで承知いたしました。
