### ISSUE TITLE
【質問】EXCELのアドイン

### ISSUE THREAD

**Issue by kusugoro** [kabucom/kabusapi#300]
EXCELのメニューバーから「KabuSTATIONアドイン」のメニューが消えてしまったため、アドインのKabusuteaddin-Addinにチェックを入れてOKボタンをクリックしたのですが、やはりパスワード入力のメニューが表示されません。原因を教えていただけますか。よろしくお願いします。先週までは問題なく使用できておりました。

**Comment by cyber-minion** [comment]
「KabuSTATIONアドイン」のメニューは永久に表示するものではなく、消えた場合は下記をご参考いただき、再度アドインのインストールを試していただけますでしょうか？
https://kabucom.github.io/kabusapi/ptal/add-in.html

**Comment by kusugoro** [comment]
再度アドインをインストールし、アドインのリストからKabusuteaddin-Addinにチェックを入れ、OKしたのですが、EXCELのアドインが使える状態になりません。

**Comment by cyber-minion** [comment]
下記画面のことを仰っているかと思いますが、「参照」ボタンをクリック→ファイル選択 をお試しいただけますでしょうか？具体的には、上記手順書の8番と9番をご参照いただければと思います。
![image](https://user-images.githubusercontent.com/69830869/115168917-885b8e80-a0f7-11eb-829f-528442f1bc9a.png)

**Comment by kusugoro** [comment]
「参照」ボタンからKabusuteAddin-Addin64.xllを選択しOKボタンをクリックし、Kabusuteaddin-Addinにチェックを入れOKボタンをクリックしたのですが、やはりEXCELのアドインが有効にならないようです。

**Comment by cyber-minion** [comment]
お手数ではございますが、下記をご確認いただけますでしょうか
１．「参照」ボタンからKabusuteAddin-Addin64.xllを選択　についてですが、
　　手順書9番の通り、「２で保存したファイルの中から」ファイルを選択したのでしょうか。
２．上記「２で保存したファイルの中から」ファイルを選択した後、「この場所に"xxx"という名前のファイルが既にあります。置き換えますか？」というメッセージが表示される場合がございます。その際、「はい」を選択してください。メッセージがない場合もありますので、なければこのステップをスルーしてください。
３．その後、「Kabusuteaddin-Addinにチェックを入れ」をせずに、そのままＯＫボタンをクリックしてください。

**Comment by kusugoro** [comment]
「参照」ボタンをクリックし、「２で保存したファイルの中から」KabuSuteAddin-AddIn64.xllを選択しました。その後「この場所に"xxx"という名前のファイルが既にあります。置き換えますか？」というメッセージは表示されませんでしたので、その後リスト内のKabusuteaddin-Addinにチェックを入れずにOKボタンをクリックしました。
まだEXCELアドインは有効になっておりません。

**Comment by cyber-minion** [comment]
> その後リスト内のKabusuteaddin-Addinにチェックを入れずに
言葉足らず申し訳ございません。チェックを外すという意味ではなく、チェック部分を何もせずに、デフォルト状態（✓が入っている状態）のままでOKボタンをクリックという意味でした。

それでも有効にならない場合は、PCを再起動し再度試していただければ幸いです。

**Comment by kusugoro** [comment]
PCを再起動しました。その後「参照」ボタンをクリックし、KabuSuteAddin-AddIn64.xllを選択しました。この段階で、デフォルト状態ではリスト内のKabusuteaddin-Addinにチェックが入っていないのですが、これが問題でしょうか。

**Comment by cyber-minion** [comment]
一度アドインのチェックボックスをOFFにしてから、再度チェックをONにして改善されるか試して頂けますでしょうか。
手順は以下となります。
１．「kabuSute Add-In」のチェックボックスをOFFにする
２．すべてのExcelを終了させる
３．下記URLのExcelアドインのインストールにある３以降をして頂く
https://kabucom.github.io/kabusapi/ptal/add-in.html

**Comment by kusugoro** [comment]
チェックボックスをOFFにした後EXCELを終了し、再起動した後にURLの手順を繰り返したのですが、まだ正しく使用できる状態になりません。
以前にインストールしたカブステ関連のアドインを全てアンインストールすることは可能ですか。
その後、再度添付いただいたURLのインストール手順を試してみることはあまり意味がないでしょうか。

**Comment by cyber-minion** [comment]
アドインのアンインストール手順は以下にてご確認ください。何度もお手数をおかけし申し訳ございません。

１．下記画面（Excelアドインのインストール手順書10番の画面）にてkabuステーションアドインのチェックを外し、OKを押します。
![image](https://user-images.githubusercontent.com/69830869/115191243-21080380-a124-11eb-9f06-61a2149898ea.png)
２．エクセルを終了します。
３．kabuステーションアドインのファイルを任意の場所（デスクトップ等）に移動します。
４．エクセルを起動します。
５．再度１の画面を出します。kabuステーションアドインのチェックボックスを操作しますと、「アドインが見つかりません。リストから削除しますか？」というメッセージが表示されます。はいを押しますとリストから削除されます。

また、アドインを再インストールする際に、アドインのzipファイルを解凍する前に、「許可する」のところにチェックを入れておいてください。
![image](https://user-images.githubusercontent.com/69830869/115198055-9d064980-a12c-11eb-9ca5-968467023d2a.png)

**Comment by DDT1947** [comment]
土曜日同類の現象を発見。金曜までは問題無しで、以降VBAはいじったもののアドインは触っていないのだが。
バックアップ用ノートPCで、アドインが消えたExcelファイルの動作確認では正常に設定可能。
＜環境＞
　・OS：Win10(20H2)・Excel2019(REST & VBA)・Access2019・アドイン：KabuSuteAddin-AddIn64.xll + 岡三RSS
＜現象＞
　Excel2019を立ち上げたところリボンエリアの [kabuSTASTIONアドインタブ] が消えていて、アドイン設定フォームでは
　[KabuSute Add-In] の行が消えていた。
   　一旦これまで使用のExcelアドインファイル群を削除し新たにダウンロードし、Excelアドイン設定の参照で 
　KabuSuteAddin-AddIn64.xll を設定するも、アドイン設定フォームに[KabuSute Add-In]が表示されない。
＜以下実施するも変化なし＞
　・Excel2019再インストール
　・Win10更新チェック（最新状態）
　・EXCELファイルをセーフモード起動しアドインの試み
　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　以上解決ヒント等ご教示いただければ幸いです。

**Comment by DDT1947** [comment]
投稿を書いている間に解決策が書き込まれてました！
ワタシの場合は、Zipファイルプロパティのアクセスブロック解除許可☑で解決。　勉強になりました ありがとうございます。
だた、 リボンエリアのアドインタブはなぜ消えたんでしょうね？　再発の可能性はないのでしょうか？

**Comment by kusugoro** [comment]
ご説明ありがとうございます。上記の手順でアドインを再インストールしたところ、「KabuSTATIONアドイン」がリボンエリアに表示されました。
その後、本番用ログインパスワードを入力したのですが、「Code 4001013:トークン取得失敗」のメッセージが出てしまいます。KabuステーションとExcelを閉じてから試しても同じです。

**Comment by DDT1947** [comment]
kusugoro さんへ　DDTです  ワタシもトークン取得失敗でつまずいていましたよ。
REST APIリファレンスでトークンをチェックしたら、HTTP通信が見覚えのない POST になってるではないですか。
POSTに書き換えてOKでした。
原因は、記憶が定かではないので断定はできませんが１月実施の kabu STATION バージョンアップの際、EXCELアドインを入れ替えしなかったからではと考えています。 前述のアドインが消えたのもこれが原因かもです。
久しぶりに APIリファレンスを見たのですが、綺麗に整理され大変見やすくなりましたね。
良い仕事は良い環境からです。　ご担当の方　ありがとうございます！

**Comment by DDT1947** [comment]
間違いの訂正。　kabu STATION １月のバージョンアップではなく、４月４日のバージョンアップでした。

**Comment by kusugoro** [comment]
DDTさん、情報ありがとうございます。

**Comment by cyber-minion** [comment]
アドインのフォルダを「信頼できる場所」に追加しますとアドインタブは消えないようになります。
#303 の方もこの方法で解決したそうです。
 
①アドインのファイルがおいてあるフォルダのパスをコピーしておきます
②ファイル→オプション→セキュリティセンター→セキュリティセンターの設定→新しい場所の追加→①のパスを貼り付け→OK
③Excel再起動

**Comment by kusugoro** [comment]
ありがとうございます。お手数おかけしました。

**Comment by cyber-minion** [comment]
> アドインのアンインストール手順は以下にてご確認ください。何度もお手数をおかけし申し訳ございません。
> 
> １．下記画面（Excelアドインのインストール手順書10番の画面）にてkabuステーションアドインのチェックを外し、OKを押します。 ![image](https://user-images.githubusercontent.com/69830869/115191243-21080380-a124-11eb-9f06-61a2149898ea.png) ２．エクセルを終了します。 ３．kabuステーションアドインのファイルを任意の場所（デスクトップ等）に移動します。 ４．エクセルを起動します。 ５．再度１の画面を出します。kabuステーションアドインのチェックボックスを操作しますと、「アドインが見つかりません。リストから削除しますか？」というメッセージが表示されます。はいを押しますとリストから削除されます。
> 
> また、アドインを再インストールする際に、アドインのzipファイルを解凍する前に、「許可する」のところにチェックを入れておいてください。 ![image](https://user-images.githubusercontent.com/69830869/115198055-9d064980-a12c-11eb-9ca5-968467023d2a.png)
