### ISSUE TITLE
【質問】pythonで日経平均株価、TOPIX、東証マザーズ指数の取得について

### ISSUE THREAD

**Issue by hmhjapan** [kabucom/kabusapi#301]
すみません。
pythonで日経平均株価、TOPIX、東証マザーズ指数のリアルタイムデータを取得できますか。取得方法を教えてください。
よろしくお願いします。

**Comment by cyber-minion** [comment]
PUSHをご利用いただければと思います。
https://kabucom.github.io/kabusapi/ptal/push.html

**Comment by hmhjapan** [comment]
分かりました。ありがとうございます。
日経平均株価、TOPIX、東証マザーズ指数の銘柄コードを確認します。
日経平均株価：101、TOPIX：151、東証マザーズ指数：154
上記の銘柄コードが大丈夫ですか。

**Comment by cyber-minion** [comment]
銘柄コードはご認識通りで、市場は「1」をご指定ください。

**Comment by hmhjapan** [comment]
補充していただき、ありがとうございます。
すみません。一点を確認させていただきます。
101@1で下記の日経平均株価を取得しました。
{'CalcPrice': 29126.23,
 'ChangePreviousClose': 105.6,
 'ChangePreviousClosePer': 0.36,
 'CurrentPrice': 29126.23,
 'CurrentPriceChangeStatus': '0056',
 'CurrentPriceStatus': None,
 'CurrentPriceTime': '2021-04-26T15:15:02+08:00',
 'HighPrice': 29241.28,
 'HighPriceTime': '2021-04-26T13:06:25+08:00',
 'LowPrice': 28896.37,
 'LowPriceTime': '2021-04-26T09:44:20+08:00',
 'OpeningPrice': 29095.49,
 'OpeningPriceTime': '2021-04-26T09:00:05+08:00',
 'PreviousClose': 29020.63,
 'PreviousCloseTime': '2021-04-23T00:00:00+08:00',
 'Symbol': '101',
 'SymbolName': '日経平均'}

 'CurrentPriceChangeStatus': '0056'について、レスパンスの説明書に下記の内容を書いております。
CurrentPriceChangeStatus | 文字列 | 現値前値比較

0056の値について、具体的の意味は何ですか。
或いはコードの参照ドキュメントがありますか。

以上、よろしくお願いします。

**Comment by tsuchinaga** [comment]
https://kabucom.github.io/kabusapi/reference/index.html#operation/boardGet

Responsesの200 OKのところに定義があります

**Comment by hmhjapan** [comment]
0056の値はResponsesの200 OKのところにに見つけました。

今回の質問をクローズさせていただきます。

ありがとうございました。
