### ISSUE TITLE
エクセル　アドイン　追加して利用。リボンからKabu STATIONアドイン　が表示されない【不具合】

### ISSUE THREAD

**Issue by ShuichiKato** [kabucom/kabusapi#303]
■[必須] 不具合事象(概要)
エクセルでKabu STATIONアドインを利用していたが、ある日以降、リボンに表示されなくなり、ログイン出来なくなった。
たぶん、Windowsのアップデイト　が行われてからと思われる。
■[必須] 本来想定されるアクションと事象
1．アドインの管理で、チェックマークが付いているのに、リボンに表示されない。
2．アドイン管理で、チェックマークを外すと、次からチェックマークを付けても、外れていて、チェックマークが付かなくなる。
■[必須] 不備発生時刻（常時の場合は、常時で記載ください)
発生時刻は不明、2021/4/19に発見、
■[任意] お使いの環境(OS、Excelのバージョン等)、サンプル(Macro、アドインのバージョン）
Windows10Home  Excel19 
■[任意] 不備部分のログ
ログは解りません。
次の対処方法で直りました。参考にしてください。KabuComのサポートに問い合わせした後に、いろいろ試した結果です。
原因は、ダウンロードしたAPIのアドイン　ファイルが、信頼されるソフトとして認識されずエクセルではじかれる。
よって、エクセルのオプション -> トラストセンター -> Microsoft Excel トラストセンター -> [トラストセンターの設定(T)] -> 信頼出来る場所　-->> ユーザー指定の場所　[新しい場所の追加(A)] でダウンロードファイルの場所を指定して登録します。
すると、自動的にリボンに現れ利用可能になりました。

追伸
現在、BOARD　コマンドしか利用していません。要望として、PM3:00過ぎ(後場終了)は50件限定を無くしてほしい。
終値等の情報を、多くの銘柄(400件ほど)で管理・分析して、売買の候補資料を作成しているため。
Kabuステーションの銘柄ボードの情報が、エクセルで利用出来る様に毎日ダウンロード出来ればよいのですが。

以上、報告まで。

加藤　修一

**Comment by cyber-minion** [comment]
取り扱いができる銘柄数に関しては順次拡大を検討してまいります。

**Comment by yasuyuki-nakazawa** [comment]
@ShuichiKato 
本文中に氏名に相当するものを記載することは適切でないため、当該部分のみ訂正させていただきます
