### ISSUE TITLE
【質問】Excelアドインのインストール

### ISSUE THREAD

**Issue by baku314** [kabucom/kabusapi#304]
お世話になっております。

Excelアドインの利用方法：https://kabucom.github.io/kabusapi/ptal/add-in.html#step1
にてしたがってインストールを試みているのですが、成功しません。
9.にてKabuSuteAddin-AddIn.xllを選択するのですが、
10.有効なアドインに追加されません。また、エラーメッセージも表示されません。

解決策をご教授いただければありがたく存じます。

**Comment by cyber-minion** [comment]
アドインのzipファイルを解凍する前に、zipファイルを右クリックし、プロパティの「許可する」のところにチェックを入れておいてから、再度お試しいただけますでしょうか。

**Comment by baku314** [comment]
解決しました。ありがとうございました。

**Comment by cyber-minion** [comment]
では、クローズさせていただきます。

**Comment by baku314** [comment]
お世話になっております。
ありがとうございました。
