### ISSUE TITLE
【不具合】優先市場のレスポンスにExchangeがなく代わりにPrimaryExchangeがある

### ISSUE THREAD

**Issue by tsuchinaga** [kabucom/kabusapi#309]
■[必須] 不具合事象(概要)

優先市場のリファレンスにはレスポンスにExchangeがあると記載されているが、実際にはPrimaryExchangeが返される

■[必須] 本来想定されるアクションと事象

Exchangeという項目名で返される

**Comment by cyber-minion** [comment]
ご指摘ありがとうございます。リファレンスを修正させていただきます。

**Comment by tsuchinaga** [comment]
ご対応をお願いします
