### ISSUE TITLE
【不具合】EXCELアドインが表示されません

### ISSUE THREAD

**Issue by kabucomapi** [kabucom/kabusapi#31]
EXCELのアドインがツールバーに表示されず困っています。
32bit版は正常に動いたのですが、64bit版の別のエクセルでも使用できるようにセッティングしたところ、ツールバーにアドインが表示されません。
一部ファイルがダウンロード時にブロックされてしまっており、それが原因でインストールに失敗した可能性があります。
KabuSuteAddin.dllがブロックされていたようです。アドインインストール後それに気づいてダウンロードしましたがアドインは表示されません。
また、再インストールしたいのですが、コントロールパネルのプログラムのアンインストール又は変更にアドインが表示されないためアンインストールできません。
また、有効なアドインにカブステの64bit用アドインは表示されており、選択はできています。選択を外して、参照から再度64bit用ファイルのパスを選択、上書きしても症状は解消されません。
エクセルは2019です。
対応方法を回答いただけないでしょうか。よろしくお願いします。

**Comment by yasuyuki-nakazawa** [comment]
32bitは正常に稼動し、64bit版のアドイン選択時にツールバーが出力されないということですが、
ご懸念のとおり、アドインのインストールが不正となっている可能性がございます。
追って、アドインの削除方法を展開いたしますので、その後、必要ファイルをダウンロードいただき再試行いただければと思います。

**Comment by kabucomapi** [comment]
回答ありがとうございます。64bit環境で使用できないため、不便しておりますのでアドインの削除方法を早急に展開していただけると助かります。
よろしくお願いします。

**Comment by cyber-minion** [comment]
@kabucomapi 
横から失礼いたします。アンインストールの手順を確認し、折り返しご回答させていただきます。

ちなみに、「64bit版の別のエクセルでも使用できるように」とありますが、32bit版で動かしたPCとは、別のPCという事でしょうか。

**Comment by kabucomapi** [comment]
そのとおりです。1台目と別のパソコンです。

**Comment by cyber-minion** [comment]
ご回答いただき、ありがとうございます。ご確認させていただきます。

**Comment by kabucomapi** [comment]
コントロールパネルから削除できないことから、インストール元のフォルダを移動して、エクセルのアドイン選択メニューから当該アドインの表示を削除して再度インストールしましたが症状は解消しません。
レジストリものぞきましたが、それらしきフォルダがわからないので対応策に苦慮しているところです。

**Comment by cyber-minion** [comment]
ご迷惑をおかけしてしまい、申し訳ございません。

一部ファイルがダウンロード時にブロックされたとのことですので、それが原因であると考えられます。ブロックされたファイルを再度ダウンロードするようにご検討頂ければと思います。
例えば、ファイルをダウンロードする際、「ファイルダウンロードを継続しますか」のメッセイージが表示される場合、「継続」を選択して頂ければ、ダウンロードできるかと思います。

**Comment by kabucomapi** [comment]
再度、すべてのファイルをダウンロードしてインストールを行ったところインストールできました。ブロックされたファイルをダウンロードしてやり直しただけではだめでした。
お騒がせしました。

原因はよくわかりませんが、一度インストールを失敗したファイルを用いて再度インストールできないようです。また、19のファイルがあり、ダウンロードが作業が煩雑かつ、ブロックされるファイルがあることは今後改善されるほうが良いと思います。
ありがとうございました。

**Comment by kabucomapi** [comment]
ちなみに、症状が解消されないときに何度もファイルがすべてそろっていることは確認しました。

**Comment by yasuyuki-nakazawa** [comment]
ダウンロードファイル群を一括で取得できる等は改善検討させていただきます

**Comment by cyber-minion** [comment]
インストールできて、何よりです。

「一度インストールを失敗したファイルを用いて再度インストールできない」については、ファイルが正常にダウンロードできなかったからと考えられます。

また、ご指摘いただきましたブロックとダウンロード作業の件、今後改善させていただきたいと考えておりますので、
引続き、よろしくお願いいたします。

**Comment by kabucomapi** [comment]
大変お騒がせしました。一層のサービス改善に努めていただけると助かります。
ありがとうございました。
