### ISSUE TITLE
【不具合】APIからの応答で想定しているKEYが存在しない場合がある

### ISSUE THREAD

**Issue by chocopon** [kabucom/kabusapi#310]
■[必須] 不具合事象(概要)
　http://localhost:18080/kabusapi/wallet/margin
　KEY "MarginAccountWallet"が存在しないことがある

■[必須] 本来想定されるアクションと事象
　KEYが存在する

■[必須] 不備発生時刻（常時の場合は、常時で記載ください)
　たまに発生。

■[任意] お使いの環境(OS、Excelのバージョン等)、サンプル(Macro、アドインのバージョン）
　Windows Python3.9

```
import json
import requests
-- 中略（TOKENの取得等） --
res = requests.get('http://localhost:18080/kabusapi/wallet/margin')
dic = json.loads(res.text)
print(dic['MarginAccountWallet'])
```
KEY ERROR

**Comment by yasuyuki-nakazawa** [comment]
当該事象が発生した時にAPIログをご確認いただき、
「MarginAccountWallet」が含まれているか確認して頂けますでしょうか。

**Comment by yasuyuki-nakazawa** [comment]
こちら、クローズさせていただきます
