### ISSUE TITLE
【不具合】エクセルアドインが表示されず

### ISSUE THREAD

**Issue by BlackTiger4649** [kabucom/kabusapi#311]
これまで利用できていたエクセルのアドインが利用できません。エクセルのオプションからアドインを見ると、アクティブでないアプリケーションアドインに区分されていて、リボンからもkabuSTATIONアドインがなくなっています。アドインを新しくリリースされたものにしても変わりませんでした。当方はExcel2013 32bitを利用していますが、Excel2019 でも同様の症状です。過去の日付を遡ってみると、少なくとも2021年4月10日までは正常に軌道していました。何か解決法がないか教えて下さい。

**Comment by DDT1947** [comment]
Closed の #300,#303,#304 がヒントになるかもしれません。

**Comment by BlackTiger4649** [comment]
#303の対応で解決できました。ありがとうございました。
