### ISSUE TITLE
【質問】kabu ステーション APIを用いて現物発注ができません．

### ISSUE THREAD

**Issue by dev-takuya** [kabucom/kabusapi#312]
kabu ステーション APIを用いて現物の発注ができません．
原因があれば教えていただけないでしょうか．以下，実行環境，実行プログラム，発注エラーの結果です．

[環境]
windows10，python3.7.4
API設定は済んでおり，トークン取得，板情報の取得はできている状態です．

[実行プログラム]
「https://github.com/kabucom/kabusapi」で提供されているpython サンプルプログラムの「kabusapi_sendorder_cash_buy.py」
を，取得したトークン，カブコム証券のログインパスワードで書き換えたプログラム

以下変更したプログラム抜粋
obj = { 'Password': PASSWORD, # カブコム証券のログインパスワード
        'Symbol': symbol,
        'Exchange': 1,
        'SecurityType': 1,
        'FrontOrderType': 20,
        'Side': '2',
        'CashMargin': 1,
        'DelivType': 2,
        'FundType': 'AA',
        'AccountType': 4,
        'Qty': qty,
        'Price': price,
        'ExpireDay': 0}
json_data = json.dumps(obj).encode('utf-8')

url = 'http://localhost:18080/kabusapi/sendorder'
req = urllib.request.Request(url, json_data, method='POST')
req.add_header('Content-Type', 'application/json')
req.add_header('X-API-KEY', TOKEN) # 取得したトークン

[エラー内容]
HTTP Error 500: Internal Server Error
{'Code': 10019, 'Message': 'パスワードをご確認ください'}

以下のエラーコード一覧等を確認しましたが，原因がわかりませんでした．
https://kabucom.github.io/kabusapi/ptal/error.html#message

恐れ入りますが，ご対応をよろしくお願いいたします．

**Comment by hori-ryota** [comment]
[リファレンス](https://kabucom.github.io/kabusapi/reference/index.html#operation/sendorderPost) の通り、Passwordに設定するのはログインパスワードでなく注文パスワードですね。

**Comment by dev-takuya** [comment]
ご回答いただきありがとうございます．
注文パスワードを入力するのですね．大変お手数ですが，注文パスワードはどこで設定したパスワードなのか教えていただけないでしょうか．

**Comment by hori-ryota** [comment]
すみません、記憶違いだったみたいです。自分もログインパスワードを使っていました :pray::pray::pray:

**Comment by cyber-minion** [comment]
APIパスワードのことかと思いますが、kabuステーション画面右上の　</>　を右クリック→「APIシステム設定」で設定していただければと思います。

**Comment by dev-takuya** [comment]
ありがとうございます．
kabuステーションで設定したAPIパスワードも試しましたが．同様のエラーが表示されます．
検証用ではAPI呼出しに成功しますが，本番用ではリクエストエラーが発生している状態です．

**Comment by cyber-minion** [comment]
ポート番号の問題かと思いますが、本番用（検証用）のパスワードを使う場合、ポート番号を18080（18081）に設定していただき、再度お試しいただけますでしょうか。

**Comment by dev-takuya** [comment]
ポート番号は本番用，検証用で分けて調査しました．
ポート番号を18080，本番用のパスワードを設定していますが．同様のエラーが出ます．

**Comment by dev-takuya** [comment]
@cyber-minion さん
ポート番号の問題かと思いますが、本番用（検証用）のパスワードを使う場合、ポート番号を18080（18081）に設定していただき、再度お試しいただけますでしょうか。
＞こちら試しましたが，同様のエラーが出力されます．こちら更なる対応及び，本エラーコードの意味，エラーになる理由を教えていただけないでしょうか．よろしくお願いいたします．

**Comment by cyber-minion** [comment]
> obj = { 'Password': PASSWORD, 

上記の「PASSWORD」の部分は、変数としてログインパスワードを代入しているという理解でよろしいでしょうか。
その場合、変数ではなく、パスワードを直接入力するという形にしていただき、再度お試しいただけますでしょうか。

何度もお手数をおかけし恐縮ですが、よろしくお願いいたします。

**Comment by dev-takuya** [comment]
パスワードは変数（PASSWORD）に格納していました．
また，パスワードを直接入力しましたが，同様のエラーが出力されます．
なお，kabuステーションを5.13.3.0へアップデートした後にも動作確認しましたが，同様のエラーが出力されます．

**Comment by cyber-minion** [comment]
説明不足で申し訳ありません。パスワードはログインパスワードを直接入力して再度お試しいただけますでしょうか。

token発行APIでは、「APIPassword」を使いますが、
注文発注APIでは、ログインパスワードを使います。

**Comment by dev-takuya** [comment]
こちらの問題ですが，解決しました．

これまでの私のログインパスワードには「ドット」の文字が入っていたのですが，「ドット」の文字を除いた文字列で構成し，設定したところ．プログラムから注文できました．
Web上でのログインパスワード設定の時点では「ドット」の文字を許しているにもかかわらず，プログラムからは認証が通らない状態でした．

こちら側では，上記事象のみ確認しており，パスワードの更新によって認証が通った可能性もあると考えられます．
いずれにせよ，パスワードの認証について調査いただければと思います．

これまで，お答えくださった皆様ありがとうございました．

**Comment by cyber-minion** [comment]
ご不便をおかけしております。
パスワードに記号が入っている場合は、エスケープ文字列を入れなければならない時があります。

**Comment by yasuyuki-nakazawa** [comment]
当件はクローズさせていただきます
