### ISSUE TITLE
【不具合】先物返済発注がキャンセル直後にできない

### ISSUE THREAD

**Issue by ee97081** [kabucom/kabusapi#313]
■ 不具合事象(概要)
最初に先物返済発注をし、一度キャンセルして、その直後にまた新規返済発注をした場合、発注が失敗します。以下にログを載せます（銘柄名やOrderIDやPriceは伏せています）。1回目と2回目の返済発注の違いはPriceだけ。その他に違うところはありません。

CancelOrderはResult:0で成功しているようなのですが、その後の注文ではなぜか

"建玉が選択されていません。"

というエラーが返ってきます。キャンセルされて20ミリ秒後に新たな発注を送っているので、1回目の注文がまだ実際内部でキャンセルされなく、返済可能なポジション用意できていないのかもしれないとの推測はしております。

とりあえず、新規で発注をかけるように対応いたしますが、同様の問題が他の方にも起こる可能性もあるかと思い、バグとして報告させて頂きます。

■ 本来想定されるアクションと事象
1度目の注文と同様に、発注は問題なく通ることを想定しております。

■ 不備発生時刻（常時の場合は、常時で記載ください)
17:09:05.8422　(2021 / 5/ 12)

■ お使いの環境(OS、Excelのバージョン等)、サンプル(Macro、アドインのバージョン）
Windows Server

■ 不備部分のログ

17:09:03.9772,I,3452,0007 【SendOrderFuture】({"Password":"****************","Symbol":"*********","Exchange":2,"TradeType":"2","TimeInForce":1,"Side":"1","Qty":"4","Price":?????,"ExpireDay":0,"FrontOrderType":20,"ClosePositionOrder":2})
17:09:04.0142,I,3452,0007 【SendOrderFuture】({"Result":0,"OrderId":"20210512************"})
17:09:05.7712,I,3452,0007 【CancelOrder】({"Password":"****************","OrderId":"20210512************"})
17:09:05.8262,I,3452,0007 【CancelOrder】({"Result":0,"OrderId":"20210512************"})
17:09:05.8422,I,3452,0007 【SendOrderFuture】({"Password":"****************","Symbol":"*********","Exchange":2,"TradeType":"2","TimeInForce":1,"Side":"1","Qty":4,"Price":?????,"ExpireDay":0,"FrontOrderType":20,"ClosePositionOrder":2})
17:09:05.8552,I,3452,0007 【SendOrderFuture】({"Code":1009001,"Message":"建玉が選択されていません。"})

**Comment by yasuyuki-nakazawa** [comment]
エラーコード見る限りは返済の建玉が指定されていないというモノですが、こちらご確認されておりますでしょうか？

**Comment by ee97081** [comment]
確認しております。

建玉指定せずにClosePositionOrderで指定しているので、選択の必要はないとの認識ですが間違っておりますでしょうか。

尚、同様の発注メッセージが１回目の発注では成功しているのに、キャンセル直後の２回目では失敗するので、そのエラーコードが出てくる理由がわかりません。

**Comment by cyber-minion** [comment]
新規（2回目）返済発注を出された後、返済建玉の「ClosePositionOrder」の数値が変わる可能性がありますので、
1回目と同様の「"ClosePositionOrder":2」で指定すると、"建玉が選択されていません。"になるかもしれません。

返済建玉のClosePositionOrderをご確認いただき、再度お試しいただけますでしょうか。

**Comment by cyber-minion** [comment]
@ee97081 
本件は改善されていますでしょうか

**Comment by cyber-minion** [comment]
本件はクローズさせていただきます。再発しましたらご連絡ください。
