### ISSUE TITLE
【要望】全体的なこと

### ISSUE THREAD

**Issue by chocopon** [kabucom/kabusapi#314]
カブステーションありきでAPIがつくられているのに、なぜカブステーションの保持している情報や機能を使えないのか不思議です。

銘柄情報：銘柄リスト、歩値　
注文：逆指値、トレイル

APIだと銘柄も５０までですが、カブステーションの銘柄リストは数千保持できます。
カブステーションが保持している情報を取得する形であれば、サーバーの負荷はかからないと思うのですが。
別アプリでスクリーニングして、わざわざ登録するのがなんとも無駄な気がしています。

銘柄リストだけでも株ステーションでみれるとスマホと連動できて便利なのですが。
ご一考いただけないものでしょうか。

**Comment by yasuyuki-nakazawa** [comment]
注文の逆指値に関してはご対応させていただく想定です。5月中予定
ご指摘のkabuｽﾃｰｼｮﾝの出力情報なら取得できるべきというご指摘に関してですが、以下理由で即解放をしておりません。
•各画面は複数枚開ける場合が多く、情報制御が複雑であること
•画面を開いていないと利用できない制約
•画面の情報はデータとして保持しているものとは限らず、WebView的に表示されているものもある
以上のことをふまえ、連携できるものは順次インターフェースを追加、公開していく想定でおります。
