### ISSUE TITLE
【質問】後場始値の取得方法

### ISSUE THREAD

**Issue by ab1234567891** [kabucom/kabusapi#315]
PythonのAPIで、後場の始値は取得可能でしょうか。
前場始値については、boardのOpeningPriceで取得できると思いますが、後場の情報の取得方法がわかりませんでした。

**Comment by yasuyuki-nakazawa** [comment]
現在の情報配信の仕組み上、後場始値という概念がないため、こちらを指定して取得する方法はございません。
お手数ですが、当件に関しては、後場開始時点の時価情報を取得、格納して処理いただくしかございません。

**Comment by ab1234567891** [comment]
承知しました。
一定間隔で株価を取得しておりますが、後場始めの値動きが激しいと、取得値と実際の始値で差が生じるため取得方法があればと思いました。
本件Closeとさせていただきます。
