### ISSUE TITLE
【不具合】残高のRecvTimeのマクロ秒が７桁が格納されている

### ISSUE THREAD

**Issue by chocopon** [kabucom/kabusapi#316]
■[必須] 不具合事象(概要)
残高情報のRecvTime等のマイクロ秒が７桁が格納されているため、パースで失敗する。

import datetime
print(order['RecvTime'])
# 2021-05-20T09:00:23.0616808+09:00
datetime.datetime.strptime(data['RecvTime'], "%Y-%m-%dT%H:%M:%S.%f%z").replace(tzinfo=None)

パースで失敗するので確認したところマイクロ秒の部分が７桁になっていた。
板情報は６桁でパースできています。７桁は聞いたことないんですが・・・無知ならすみません。

■[必須] 本来想定されるアクションと事象
マイクロ秒は６桁

■[必須] 不備発生時刻（常時の場合は、常時で記載ください)
2021-05-20T09:00:23.0616808+09:00
■[任意] お使いの環境(OS、Excelのバージョン等)、サンプル(Macro、アドインのバージョン）
python3.9 Windows10 Pro

■[任意] 不備部分のログ

{'AccountType': 4,
 'CashMargin': 2,
 'CumQty': 0.0,
 'DelivType': 0,
 'Details': [{'Commission': 0.0,
   'CommissionTax': 0.0,
   'DelivDay': 20210524,
   'ExchangeID': None,
   'ExecutionDay': None,
   'ExecutionID': None,
   'ID': '20210520A01N80619398',
   'OrdType': 1,
   'Price': 865.0,
   'Qty': 500.0,
   'RecType': 1,
   'SeqNum': 1,
   'State': 3,
   'TransactTime': '2021-05-20T09:00:23.0616808+09:00'},
  {'Commission': 0.0,
   'CommissionTax': 0.0,
   'DelivDay': 20210524,
   'ExchangeID': '1F111700005457',
   'ExecutionDay': None,
   'ExecutionID': None,
   'ID': '20210520B01N80619399',
   'OrdType': 1,
   'Price': 865.0,
   'Qty': 500.0,
   'RecType': 4,
   'SeqNum': 4,
   'State': 3,
   'TransactTime': '2021-05-20T09:00:23.161476+09:00'}],
 'Exchange': 1,
 'ExchangeName': '東証１部',
 'ExpireDay': 20210520,
 'ID': '20210520A01N80619398',
 'MarginTradeType': 2,
 'OrdType': 1,
 'OrderQty': 500.0,
 'OrderState': 3,
 'Price': 865.0,
 'RecvTime': '2021-05-20T09:00:23.0616808+09:00',
 'Side': '2',
 'State': 3,
 'Symbol': '6236',
 'SymbolName': 'ＮＣホールディングス'}

**Comment by yasuyuki-nakazawa** [comment]
残高照会にはRevTimeないので注文約定照会APIでしょうか
当方で確認しましたが、６桁となっております。
７桁で返されている方、他におりましたら、情報頂けると幸甚です

**Comment by yasuyuki-nakazawa** [comment]
こちら、記載されている事象が確認できておりません。
時間計については、想定通り6桁となっております。同事象が発生されている方がおりましたらご連絡いただけると幸甚です。
6/20を一旦時限として切らせていただき、続報等ないようでしたら、いったんクローズさせていただきます

**Comment by yasuyuki-nakazawa** [comment]
こちら、類似報告がないことと、各種パターンでの検証の上、同事象が発生しておりませんので、
いったんクローズとさせていただきます。
