### ISSUE TITLE
【お知らせ】kabuステーションAPI改善（2021年5月25日 ver5.13.3)

### ISSUE THREAD

**Issue by cyber-minion** [kabucom/kabusapi#317]
kabuステーションAPIに関しては、ご要望やご意見に基づき、下記の機能を提供することとします。

〇リリース日：2021年5月25日（火） 予定
　ver5.13.3
　以下機能はkabuステーションのバージョンアップ後にご利用になれます。
　インターフェースの詳細に関してはリリースと合わせて、リファレンスの更新を実施させていただきます。

〇対応機能
・注文発注APIに逆指値追加(※注記)
　対象API：
　　注文発注（現物・信用）、注文発注（先物）、注文発注（オプション）
　　トリガとなる項目（商品により異なります）
・時価情報・板情報APIのレスポンスに銘柄種別を追加
・PUSH配信データに銘柄種別を追加
・その他
　kabuステーションデジタル証明書の更新

〇プレビュー
詳細につきましては、下記にてご確認ください。
▼ブランチはこちらです。
https://github.com/kabucom/kabusapi/tree/release/ver5.13.3
▼masterとの差分はこちらからご確認ください。
https://github.com/kabucom/kabusapi/compare/release/ver5.13.3

※注記
今回のリリースにおきましては、Excelアドインのサンプルコードの提供は5月25日以降とさせていただきます。
サンプルの提供は準備完了次第アップロードさせていただきます。
ご迷惑をおかけし、誠に申し訳ございません。

**Comment by seattlesbest** [comment]
逆指値の追加、ありがとうございます！！！
色々と要望が多く大変だったかと思いますが、引き続き良い商品の開発のほどお願い申し上げます。
m(_ _)m

差分を拝見したところ、多分今回のバージョンでは、
単体での逆指値での新規発注、返済発注のみ実装で、
「W指による逆指」（新規(返済)時に指値と逆指値を両方指定）
「Uターン注文における逆指」（新規時に返済の逆指値をあらかじめ指定）
は、独自で開発しない限り、まだ機能としては未実装という認識ですが
あっていますでしょうか？

**Comment by cyber-minion** [comment]
ご認識の通りです。
W指値等の機能に関しましては、検討の上、対応していきたいと考えております。
引続きよろしくお願いいたします。

**Comment by DDT1947** [comment]
RESTにおける注文約定照会（kabusapi/orders?）で、
逆指値注文（ReverseLimitOrder）のトリガー価格のレスポンスデータキーは設定されていないのでしょうか？

**Comment by cyber-minion** [comment]
現状、注文約定照会では逆指値注文のトリガー価格のレスポンスデータキーは設定しておりません。
要望として検討させていただければ幸いです。

**Comment by cyber-minion** [comment]
Excelアドインのサンプルシート（kabuSTATION_API_ORDER_sample.xlsm）をアップロードいたしました。参考としてご利用ください。
