### ISSUE TITLE
【質問】サンプルのExcelマクロで発注ができません

### ISSUE THREAD

**Issue by tsujitakg** [kabucom/kabusapi#318]
Excelマクロのサンプルプログラムでの発注ができません。
アドイン、kabuステーションは設定済みで3つあるサンプルプログラムのうち
kabuSTATION_API_PUSH_sample.xlsx
kabuSTATION_API_function_sample.xlsx
は動くのですが
kabuSTATION_API_ORDER_sample.xlsm
で発注すると
{"Code":4001009,"Message":"APIキー不一致"}
のエラーメッセージがでて発注できません。

ポートやパスワード以外どこかまだ設定する必要があるのでしょうか？よろしくお願いします。

**Comment by hishiharahaz** [comment]
@tsujitakg さん
APIキー不一致エラーとの事ですので、kabuSTATION_API_ORDER_sample.xlsmにてもExcelリボンにあるポートの右となりの本番用にAPIパスワードを入力して発注してみてください。

**Comment by tsujitakg** [comment]
ありがとうございます
でも、先刻から本番用APIパスワードは入力していました

質問後、アドインが以前にインストールしたものであったのを思い出し、新しいものをダウンロードしなおしましたが今度は「発注が有効になっていません」とのメッセージが出ます

もちろん制御ボタンは発注、更新ともにグリーンにしてあります

**Comment by hishiharahaz** [comment]
私も以前、同じことになった事があります。
その時は、Excelをすべて落としてから、該当のExcelを起動したらマクロ動いた記憶があります。

**Comment by tsujitakg** [comment]
日を変えて何度か試行してみたところ、うまく発注できるときとできないときがあるようです。
しばらく検証してみます。
