### ISSUE TITLE
【不具合】kabusapi_symbol.pyで先物のTradeStart、TradeEndは同じです。

### ISSUE THREAD

**Issue by hmhjapan** [kabucom/kabusapi#320]
■[必須] 不具合事象(概要)
TradeStartの値はTradeEndの値と同じです。
■[必須] 本来想定されるアクションと事象
TradeStartの値はTradeEndの値により小さいです。
■[必須] 不備発生時刻（常時の場合は、常時で記載ください)
常時
■[任意] お使いの環境(OS、Excelのバージョン等)、サンプル(Macro、
アドインのバージョン）
OS:Windows 10
サンプル：kabusapi_symbol.py
■[任意] 不備部分のログ
URL:http://localhost:18080/kabusapi/symbol/166060019@24
{'ClearingPrice': None,
 'DerivMonth': '2021/06',
 'DisplayName': '日経225mini 06',
 'Exchange': 24,
 'ExchangeName': '大阪夜間',
 'LowerLimit': 26040.0,
 'PriceRangeGroup': '10119',
 'Symbol': '166060019',
 'SymbolName': '日経225mini 21/06',
 'TradeEnd': 20210610,
 'TradeStart': 20160610,
 'TradingUnit': 1.0,
 'Underlyer': 'NK225',
 'UpperLimit': 30660.0}
ご確認の上に対応をよろしくお願いします。

**Comment by tsuchinaga** [comment]
ログを見る限り、TradeStartは2016年06月10日で、TradeEndは2021年06月10日に見えます。

**Comment by hmhjapan** [comment]
そうです。
日経225mini 21/06のトレードは多分2021年01月頃に始まりました。
TradeStartは2016年06月10日の前です。

**Comment by tsuchinaga** [comment]
メジャー限月の6月限月が2021年01月スタートということはないと思います。

例えば下記が参考になるのではないかと思います。

[日経平均先物の限月はどのように設定されていますか？](https://faq.kabu.com/s/article/k000628)

**Comment by hmhjapan** [comment]
参考URLを見ました。
■日経225mini
3月、9月の限月取引：直近の3限月取引
6月、12 月の限月取引：直近の10 限月取引
上記以外の直近3限月を加えた16限月（最長5年）

メジャー限月の6月限月は何か月前にトレードは始まりましたようです。
TradeStartの修正をよろしくお願いいたします。

**Comment by seattlesbest** [comment]
hmhjapan さんがおっしゃるのをまとめると

■[必須] 不具合事象(概要)
TradeStartの値はTradeEndの値と「同じ」
（つまりTradeEnd またはTradeStartがどちらかの値に一致している　という主張）
です。
■[必須] 本来想定されるアクションと事象
TradeStartの値はTradeEndの値により小さいです。
（つまりTradeStart<TradeEnd であるべきという主張）

という不都合の主張と、
'TradeEnd': 20210610,
'TradeStart': 20160610,

というログの事実
（つまりTradeStart<TradeEnd であるべきという主張に一致していて本来あるべきアクションになっている）

からみて、
「不都合は発生していない」

ということかと思いますが、もし日付だけ見ていて
「TradeStartの値はTradeEndの値と同じです。」という話で勘違いされていたのであれば、
不都合は発生してないとなりますが、いかがでしょうか？

ちなみに今なら、2025年6月限のminiを取引できますので、
通常4～5年後の取引ができるのが普通です。
約定するかどうかは別として、それは名前の通り「先物」ですから。。。。笑

**Comment by hmhjapan** [comment]
もうしわけありません。私は年度を見間違いました。
'TradeEnd': 20210610,
'TradeStart': 20160610,
20210610と20160610の年度は違いますが、見間違いました。
20210610＝20160610と思いました。もうしわけありません、後にこの課題をクローズさせていただきます。

**Comment by hmhjapan** [comment]
不具合の提出は間違いました。'TradeStart': 20160610＜'TradeEnd': 20210610ですので、大丈夫です。
もうしわけありません。クローズします。
