### ISSUE TITLE
【質問】投資信託への対応について

### ISSUE THREAD

**Issue by hayato0311** [kabucom/kabusapi#325]
今後、投資信託への対応も検討されているのでしょうか？

**Comment by yasuyuki-nakazawa** [comment]
現状は投信への対応は検討しておりません。
カブステAPIは、kabuｽﾃｰｼｮﾝで取り扱っている前提が必要となっております。
現状、kabuｽﾃｰｼｮﾝとしても、投信は取り扱っておらず、当該取引ツールの特性上、今後の取り扱いもないものと思慮いたします
