### ISSUE TITLE
【質問】API による買い注文に対するパラメータ変換エラーについて

### ISSUE THREAD

**Issue by kabutarou-ookinakabu** [kabucom/kabusapi#326]
下記のコードでパラメーター変換エラーで返ってきますなぜでしょうか？
取引銘柄と取引の価格については変数を使っています。
ここで使うパスワードはログインの時のパスワードでいいんでしょうか？
株ステーションのシステム設定及び注文１を確認して、とリファレンスにはありますが何が悪いかわかりません。

obj = { 'Password': '*******',  
            'Symbol': Buymeigara,  """ 取引銘柄 """
            'Exchange': 1,  """ 東証 """
            'SecurityType': 1,  """ 株式 """
            'FrontOrderType': 20,  """ 指値 """
            'Side': '2',  """ 買 """
            'CashMargin': 1, """ 現物 """ 
            'DelivType': 2,  """ 預り金 """
            'FundType': '02',  """ 保護預り """
            'AccountType': 4,  """ 特定口座 """
            'Qty': 100,  """ 注文数量 """
            'Price': kaine,
            'ExpireDay': 0  } 

    json_data = json.dumps(obj).encode('utf-8')

    url = 'http://localhost:18080/kabusapi/sendorder'
    req = urllib.request.Request(url, json_data, method='POST')
    req.add_header('Content-Type', 'application/json')
    req.add_header('X-API-KEY', passkey)

**Comment by hishiharahaz** [comment]
@kabutarou-ookinakabu 
過去に類似の投稿がありましたので、参考になればと思います。
#297

パスワードはログインの時のパスワードとなります。

**Comment by kabutarou-ookinakabu** [comment]
回答コメントありがとうございました。
Python 初心者すぎて、パラメーターの説明をコメントで入れていたところが悪影響を与えていたようでした。
なんとなくコメントを削除したらエラーがなくなりました！ありがとうございました！

**Comment by yasuyuki-nakazawa** [comment]
こちらはクローズとさせて頂きます
