### ISSUE TITLE
【質問】kabuステーションAPIは利用不可になる原因について

### ISSUE THREAD

**Issue by hmhjapan** [kabucom/kabusapi#327]
今日電子契約画面で確認して、kabuステーションAPIは利用不可になりました。利用不可の原因を教えてください。

kabuステーションAPIを使いたい場合、どこへ連絡すればいいですか。

以上、よろしくお願いします。

**Comment by tsuchinaga** [comment]
利用条件はここにあります

[機能・サービス | kabuステーション®専用サイト ｜kabuステーション®専用サイト｜株のことならネット証券会社【カブコム】](https://kabu.com/kabustation/services.html#2)


kabuステーションは使えるけどAPIが使えないということでしたら、Fintechプランの条件から外れたのではないかと思います。

> 信用取引口座または、先物オプション取引口座開設済みかつ、前月当社全取引における約定回数が1回以上ある

**Comment by hmhjapan** [comment]
Fintechプランを確認しました。最終申込日は2020/11/29で、契約期間は2021/06/01 までです。なぜ2021/06/01まで満期になりましか。半年ずつ契約を更新しますか。
また契約更新をしたい場合、手続きなどを教えてください。
以上、よろしくお願いします。

**Comment by hmhjapan** [comment]
現在信用取引口座または、先物オプション取引口座開設済みでした。
多分前月当社全取引における約定回数が1回以上あるの条件から外れたでしょうか。
もし6月に1回以上の取り引きしたら、7月1日からFintechプランは自動更新されますか、或いは他の手続きが必要ですか。
Fintechプランの条件から外れたので、6月はまたkabuステーションAPIを使えますか。
以上、ご確認をよろしくお願いします。

**Comment by kabusukebe** [comment]
@hmhjapan 
条件を満たしていれば翌月から使えますよ。
あと、本件はAPIと直接関係が無いので、問い合わせるならお客様サポートセンターの方が良いんじゃないですかね。

**Comment by hmhjapan** [comment]
分かりました。ご回答ありがとうございました。
本件に関してまだ何かあればお客様サポートセンターに聞きます。
本件をクローズさせていただきます。
