### ISSUE TITLE
【質問】13．注文約定照会 コマンド：python kabusapi_orders.pyについて

### ISSUE THREAD

**Issue by kabutarou-ookinakabu** [kabucom/kabusapi#328]
注文約定照会のプログラムを投げてやって買い注文が約定できてるのか失効しているのか戻り値で判別することはできるのでしょうか？

リファレンスは下記のとおりなっておりまして判別でき無いように見えます。
stateが5だけ帰ってきてもあまり意味がないように思うのですが。。。

-----------------------------------------------------------------
state | stringEnum:&nbsp;1&nbsp;2&nbsp;3&nbsp;4&nbsp;5状態※指定された状態と一致する注文のみレスポンスします。※フィルタには数字の入力のみ受け付けます。※複数の状態を指定することはできません。定義値説明1待機（発注待機）2処理中（発注送信中）3処理済（発注済・訂正済）4訂正取消送信中5終了（発注エラー・取消済・全約定・失効・期限切れ） | 定義値 | 説明 | 1 | 待機（発注待機） | 2 | 処理中（発注送信中） | 3 | 処理済（発注済・訂正済） | 4 | 訂正取消送信中 | 5 | 終了（発注エラー・取消済・全約定・失効・期限切れ）
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

1 | 待機（発注待機）
2 | 処理中（発注送信中）
3 | 処理済（発注済・訂正済）
4 | 訂正取消送信中
5 | 終了（発注エラー・取消済・全約定・失効・期限切れ）
----------------------------------------------------------------------------------------------

**Comment by kabutarou-ookinakabu** [comment]
すいませんかこのやり取りの中に回答ありました。
約定価格を取得する場合は、注約照会の明細データ（Detail）でRecType=8（約定）のデータを抽出し、そのなかのPriceが約定価格となります。

**Comment by kabutarou-ookinakabu** [comment]
何度もすいません。

上記のJSONファイルから明細データ（Detail）でRecType=8（約定）のデータを抽出するコードが分かりません。

誰か分かる方いらっしゃいませんでしょうか？

**Comment by seattlesbest** [comment]
stateに関しては、今同様の質問をまとめています。カブコムさんから回答があれば、集約した方がよいかと思いますので、
よろしければ、こちらもご参照ください。
https://github.com/kabucom/kabusapi/issues/281

**Comment by kabutarou-ookinakabu** [comment]
rectype = content[x]['Details'][4]['RecType']

このようなコードで変数に入れれました。

売り注文を出すときの材料として注文約定照会を考えてたんですが、よくよく見ると2営業日後の受け渡しが終われば注文約定照会から明細が消えてしまうので、残高照会の結果を使うことにしました。

ありがとうございます。

**Comment by yasuyuki-nakazawa** [comment]
回答遅くなり、恐縮です。
既に解決されておりますが、注文約定照会の情報は受け渡しが完了すると情報として取得できなくなるため、
記載されている通り、残高照会から現在のポジションを取得していただく必要がございます

**Comment by cyber-minion** [comment]
解決済のようで、いったんクローズさせていただきます。
