### ISSUE TITLE
【質問】

### ISSUE THREAD

**Issue by syoujirou** [kabucom/kabusapi#33]
APIリファレンスを見たところ、システム化して監視可能な銘柄数は最大でも50。
また各種ランキングを取得する為のメソッド等も存在しないように見受けられます。
今回の個人向けAPI公開はどのように個人投資家に使用されることを想定されているのでしょうか？

**Comment by yasuyuki-nakazawa** [comment]
取り扱いができる銘柄数に関しては順次拡大を検討してまいります。
また、ランキングに加えて、各種銘柄群を絞り込めるような銘柄リストインターフェースの追加に関しても検討中です。

ご質問の後半部分に関してですが、（個人投資家の使用想定に関して）
お取引ルールを遵守いただいている範囲で、当社側から特定の用途をご提示することはございません。
お客さまのAPIの活用方法については、様々な可能性があると考えており、お取引に役立て頂ければ幸いです。
