### ISSUE TITLE
【質問】VBAによる注文全取消

### ISSUE THREAD

**Issue by rxatya** [kabucom/kabusapi#330]
VBAによる注文全取消は可能でしょうか？

**Comment by yasuyuki-nakazawa** [comment]
前取消というAPIは提供しておりませんので、注文約定照会をもとに、現在発注されている注文をループして取消していただく必要があるかと思われます。
その処理の構築自体はVBAでも問題なく実装は可能かと思慮します

**Comment by rxatya** [comment]
ご回答ありがとうございました。
