### ISSUE TITLE
【要望】「発注系リクエストの流入制限の緩和」もしくは「複数PCによるkabuステーションの発注」

### ISSUE THREAD

**Issue by rxatya** [kabucom/kabusapi#331]
・発注系リクエストの流入制限は秒速5件ということですが、出来れば10倍、少なくとも2倍を希望します。
・複数PCによるkabuステーションの発注は不可ですが、出来れば5台、少なくとも2台を希望します。
現在、サードバーティが提供しているkabu.com APIを利用しています。
kabuステーションAPIへの変更を検討中ですが、発注能力に差があり変更出来ません。

**Comment by yasuyuki-nakazawa** [comment]
・発注数の流量緩和は検討しておるところです。
・複数PCによる発注は現状の仕組み上、許容しておりません。というのも、ログインを前提としており、カブステ自体が複数端末でのログインを認めていないためです。

複数PCでの利用を求められている背景としては、多様な情報を取得したいというニーズによるものでしょうか。
差し支えなければ、どのようなツール、手法を想定しているかを教示いただけると幸甚です。

**Comment by rxatya** [comment]
お返事ありがとうございます。

・流量緩和の件、「いつまでに」「どの程度」をお考えでしょうか？

・カブステの複数端末ログインの件
以前は複数端末ログイン可能でした。
以前のように戻していただければ幸甚です。
（その場合、流量緩和は必要ございません）

・ツール、手法の件
一般論になりますが、情報取得量の増大、発注量の増大、複数ストラテジーの対応などでニーズがあると思います。

よろしくお願い致します。

**Comment by kabutarou-ookinakabu** [comment]
私も、様々なアルゴリズムを試してみて、その中で優秀なアルゴリズムを選んでいきたいというニーズは高くあると思います。

**Comment by yasuyuki-nakazawa** [comment]
〇流量制限の緩和にかんして
　想定としましては現状の5件から10件への拡大を想定しています。
　対応機関に関しては、現状公開できず、申し訳ございません。

〇カブステのログインに関して
カブステの複数端末での同時ログインについては、過去からもできない仕組みになっています。
跡勝ちしますので、先行してログインしていたカブステのログインセッションは切断されます
※ツール上は画面更新等されますが、ログインセッションが切れているため、注文情報の更新や、発注処理は実施されません

**Comment by rxatya** [comment]
流入制限の緩和の件
10件なら最低限使えるのでうれしいです。
ただ、手厳しい表現で心苦しいのですが、時期の目安が公開出来ないのならあまり意味ない気もします。

カブステのログインの件
情報の更新が出来ていたので実務上問題なかったため、複数ログイン可能と考えておりました。
こちらの錯誤でした。申し訳ございません。
複数ログインの対応を切に希望致します。

**Comment by takei0723** [comment]
すみません、私もいちユーザーとして複数端末のログインを希望しています。用途は本番と開発を同時に行うためです。
出来上がった本番運用プログラムをひとつのPCで動かして、同時に新しいプログラムを別のPCで開発していますが、本番運用中は動作確認ができません。特に先物取引を行っているため平日は動作確認が16時前後か朝の６～８時しかできません。しかもこの時間帯で取引時間と同じように板が動いている時間はかなり短いです。
この先JPXは取引時間を祝日などにも拡張していく流れだと、より動作確認ができる時間が少なくなり、不便になります。そのため複数端末でログイン、動作ができると開発をしやすくなります。
ご検討のほどよろしくお願いします。

**Comment by yasuyuki-nakazawa** [comment]
@takei0723 さん
複数端末のログインはテスト・検証が目的と言うことで認識いたしました。
確かに稼動している時価を、元にした検証のニーズはあるものと理解いたしております
こちらも含めまして、改善については検討させていただきます。
負荷の分散が一番の課題となりそうではございますが。

**Comment by rxatya** [comment]
複数PCだと負荷が掛かるというのは大変よくわかります。
とはいえ、kabu.com APIは複数PC可能ですし、他社のRSSも全て複数PC可能な状況を鑑み、複数PC対応を希望致します。
