### ISSUE TITLE
【質問】買い注文の返り値の受付注文番号と残高照会で得られる資産の関連が分かるかどうかについて

### ISSUE THREAD

**Issue by kabutarou-ookinakabu** [kabucom/kabusapi#332]
残高照会で得られる資産一覧においてどの回注文（受付注文番号）で約定したものかどうかを判別する方法はありますか？
銘柄や数量、金額以外のユニークな ID で識別できると便利だなと思うのですが。

ストラテジーが違うアルゴリズムを並行して動かす場合、どのアルゴリズムによっての買い注文の結果としての資産（約定結果）なのかが分かる方がいいです。

**Comment by yasuyuki-nakazawa** [comment]
現物取引ですと、ポジションとの紐づけができませんが、信用取引ということでしたら、
新規の約定の際の注文明細における約定番号と残高照会のIDがリンクしませんか？

**Comment by kabutarou-ookinakabu** [comment]
すいません。まだ株式投資初心者なもので信用取引を行っておりません。現物取引のみで行なっておりますので、現物取引の残高照会や約定照会においてもユニークな ID を付与していただけるとありがたいのですが...

**Comment by kabutarou-ookinakabu** [comment]
すいません、よく確認してみたら注文約定照会には注文番号があったのでユニークに識別ができそうです。
残高照会ではなく注文約定照会をエクセルにでも貯めて、売り注文に使いたいと思います。

**Comment by yasuyuki-nakazawa** [comment]
当件はクローズさせていただきます
