### ISSUE TITLE
【質問】株の発注におけるSORの選択について

### ISSUE THREAD

**Issue by sotoboft** [kabucom/kabusapi#333]
株の発注（現物・信用）における「市場」の選択において、SORを選ぶことはできないのでしょうか？

**Comment by yasuyuki-nakazawa** [comment]
SORは諸都合によりAPIからは発注できないようになっております
ご了承ください

**Comment by sotoboft** [comment]
ご回答ありがとうございます。了解いたしました。
もし差支えなければ「諸都合」のところを教えていただけないでしょうか？

**Comment by yasuyuki-nakazawa** [comment]
レギュレーション的な整理と調整ということだけコメントさせていただきます
今後、要望に応じて拡張は検討させていただきます

**Comment by sotoboft** [comment]
早速ご回答ありがとうございます。つまり、金融庁からの認可にからむ事情であり、技術的な問題ではないということですね。ありがとうございました。

**Comment by yasuyuki-nakazawa** [comment]
こちらはクローズさせていただきます
