### ISSUE TITLE
【不具合】最新の取引余力が一度で取得できない

### ISSUE THREAD

**Issue by takasheep** [kabucom/kabusapi#336]
■[必須] 不具合事象(概要)
資金を振替した後に「取引余力（先物）」で余力を取得しても、最新の証拠金残高が取得できない。
ただし一度取得した直後に再度取得すると最新残高を取得できることを発見したので、とりあえず2連続で実行することで対応しています。

恐らく、kabuステーションで保持している残高からの情報を取得しているのだと思いますが、この更新タイミングが分かりませんでした。
しかしAPIで一度取得することで更新されるため、APIでの取得により何らかの更新トリガーが発生しているようにも見えます。
そうであれば、一度目から更新後の残高を返すべきかと思います。

■[必須] 本来想定されるアクションと事象
一度目の取得から最新の証拠金残高を返す

■[必須] 不備発生時刻（常時の場合は、常時で記載ください)
常時

**Comment by yasuyuki-nakazawa** [comment]
注文結果反映、約定反映のタイミングでリクエストが集約される場合があります。
短時間による余力のサーバリクエスト回避のため。
こちらが影響している可能性があるように見受けられます
https://github.com/kabucom/kabusapi/issues/105

**Comment by takasheep** [comment]
すみません、既出でしたね。

これまでのやり取りを拝見すると、現状においてはAPI（及びkabuステ）の余力取得においては遅延する可能性があるということですね。
リアルタイムの数字については、Web側の数字を確認するしかなさそうですね。

**Comment by yasuyuki-nakazawa** [comment]
約定や注文をした際の余力変更はすぐに実施されますが、連続発注や連続約定が行われた際は、
余力の計算を束ねて実施するため、連続発注される際は、最後に余力の取得に行く等を考慮いただけると幸甚です。
おおむね、数秒間の余力計算を束ねている想定です

**Comment by takasheep** [comment]
了解しました。
また発注ではなく、Web画面による資金移動のみを行った場合は、すぐ反映されない、ということですね。
資金移動したあとにAPIによる確認を行うと、すぐ反映されないケースがあるのはそのためですね。

発注や約定がなくても資金の変化について反映されるタイミングもあるようですが、これはまちまちということですね。

**Comment by yasuyuki-nakazawa** [comment]
基本的には、カブステへも資金移動の通知が飛び、余力を含めた資産の更新が行われます。
WEB等で資金移動を行った際も数秒後にはカブステへも反映されていると思われます。
ただし、その反映までの時間に関しては、お約束できるものはございません。

**Comment by takasheep** [comment]
基本的に数秒後に自動的に更新される、ということですが、ここ数日毎日確認している限り、9:00頃に行った先物証拠金への資金移動については、9:10にAPIから確認を行っても必ず1回目はFutureTradeLimitが移動前の数字を返します。
0.1秒後に再度取得すると、想定される移動後の金額が返ります。

毎回、10分経過しても2回取得しないと更新されない、というのは仰る仕様とは少し異なるように感じます。

本来kabuステーション上の仕様のお話かと思いますが、APIで2回取得すると更新される、というのはAPIでの取得が残高更新のきっかけになっているように見えますので、もしそうであれば1回の取得で更新後の値を返す様な改修をして頂けると助かります。

**Comment by yasuyuki-nakazawa** [comment]
当件、少々調べました。
バスケット画面を開いた状態ですと、問題なく余力が取得できますので、お試しいただけますでしょうか。
おそらく、口座余力の取得の際は、カブステ上のキャッシュを返す仕様となっており、バスケット画面が開かれていますと、そちらに可能額を出力する関係上、最新の余力情報が取得されており、そちらを返すということがわかっております。
パフォーマンスの関係上、リクエスト都度の余力取得が厳しいため、いったんは上記でご対応いただけると幸甚です

**Comment by takasheep** [comment]
大変遅くなりすみません。
バスケット画面について動作を確認してみましたが、開いているだけでは即時更新されないように見えます。
資金移動した後、バスケット画面を閉じて、開き直したタイミングで即時更新されることは確認できました。
kabuステーション内のバスケット画面をAPIから開いたりの操作はできないと思うので、補助的更新手段ですね。

証券APIの動作として、1回のリクエストでリアルタイムの残高余力を拾えないことは適切でないと思いますので、いずれ何らかの対応をして頂きたいところですが、自分の使用範囲ではとりあえず対症療法的に対応は出来ているので大丈夫です。

**Comment by chocopon** [comment]
株の信用取引でも同様の現象になりましたので報告します。
口座には100万円程度入金＝333万円の余力
注文縦玉のある状態で、170万円程度の余力をスマホアプリで確認。
APIで信用余力（株）を取得した際、１回目333万円、おかしい？と思い再取得170万円

はっきり言って困りますよね。

**Comment by cyber-minion** [comment]
>パフォーマンスの関係上、リクエスト都度の余力取得が厳しい

仕様改善には課題がありますが、継続検討させていただきます。
本チケットはいったんクローズさせていただきます。
