### ISSUE TITLE
【質問】トークン発行の手順

### ISSUE THREAD

**Issue by keigami** [kabucom/kabusapi#337]
00.Readme.txt　に記載されている手順でトークン発行を行おうとしているのですが、以下のエラーが出て先に進めません。
何か確認すべきことがあればご指摘ください。

HTTP Error 401: Unauthorized
{'Code': 4001013, 'Message': 'トークン取得失敗'}

環境などはこのようになっています
- APIのID, passwordの発行済み
- Kabuステーションの設定実施済み (APIアイコン </> が緑色になっています)
- Python 3.8.10, websocket-client 0.59.0
- windows10, windows powershell(x86)
kabusapi_token.py に取得したIDとパスワードを設定するのかな? と思うのですが、いろいろ試しても結果変わらず。

ヒントを頂ければ大変ありがたいです。
よろしくお願いします。

**Comment by tsuchinaga** [comment]
https://github.com/kabucom/kabusapi/blob/master/sample/Python/kabusapi_token.py#L5

kabuステーションが立ち上がっている状態で、`qwerty` を kabuステーションで設定したAPIパスワードに変えることで動きそうですが、どうでしょう？

**Comment by keigami** [comment]
tsuchinaga-san
早速のアドバイスありがとうございます。

kabuステーションを立ち上げた状態で "obj = { 'APIPassword': 'qwerty' } " この qwerty の箇所にパスワードを設定しているのですが、上述のエラーが表示されてしまいます。
パスワードを再発行して試してみましたが、状況変わらずです。。。

**Comment by tsuchinaga** [comment]
私の環境ですと、例えばAPIパスワード(本番用)に `Password1234` と設定していたとして、  

`obj = { 'APIPassword': 'Password1234' }`

のように変更すれば

```
200 OK
('Content-Length', '59')
('Content-Type', 'application/json; charset=utf-8')
('Server', 'Microsoft-HTTPAPI/2.0')
('X-Content-Type-Options', 'nosniff')
('X-XSS-Protection', '1; mode=block')
('X-Frame-Options', 'DENY')
('Content-Security-Policy', "default-src 'none'")
('Access-Control-Allow-Origin', '*')
('Date', 'Wed, 30 Jun 2021 23:49:30 GMT')
('Connection', 'close')

{'ResultCode': 0, 'Token': 'token string'}
```

といったレスポンスを得られました。


変更したのがパスワードの部分だけなので、パスワードが原因でなければわかりませんね…

**Comment by yasuyuki-nakazawa** [comment]
ちなみにですが、接続ポートは正しいでしょうか？本番向けと検証向けで異なって、、、ということもございます

**Comment by keigami** [comment]
yasuyuki-nakazawa さん

コメントありがとうございます。
素人質問で恐縮ですが、接続ポートについて何をどのように確認すればよいでしょうか？　全く技術的なところを理解できておらず。　設定や確認すべき箇所をご指示いただけると大変ありがたいです。

**Comment by yasuyuki-nakazawa** [comment]
APIの検証用(スタブモード)と本番用のポートが違います
まずは、APIパスワードをキチンと設定されているでしょうか？
<\>のアイコンの上で右クリックを押して、、設定画面を開き、検証用のパスワード、本番用のパスワードをご確認ください。
こちらは、ログインパスワードとは異なります。
接続する際にリファレンスにポート番号が記載されておりますので、、そちらのポートを指定してトークン発行をお試しいただけますか

**Comment by keigami** [comment]
yasuyuki-nakazawa さん

コメントありがとうございます。
Kabuステーション上の設定は行えています。　APIパスワード(本番用)、APIパスワード(検証用)どちらも設定しています。

>リファレンスにポート番号が記載されております
これはどこを指していますでしょうか? 　またポートの指定方法は具体的にどのように行えばよいでしょうか?
自力で調べているのですが、情報が見あたらず。　引き続きアドバイスをお願いします。

**Comment by cyber-minion** [comment]
リファレンス→トークン発注のところに以下の表記がありまして、18080/18081を指定することによって、ポートが異なります。再度お試しいただけますでしょうか
![image](https://user-images.githubusercontent.com/69830869/125546854-b7b2e46f-f8a7-49f7-b550-8ca30f8dea3a.png)

**Comment by keigami** [comment]
yasuyuki-nakazawa さん

コメントありがとうございます。
ポートに関する情報をどうしても見つけられなかったので、助かりました。
自宅ネットワークがポート開放に対応していないことが判明しましたので、ネットワークの契約変更をすすめています。　
これできっと使えるようになるはず。。

サポートありがとうございました。

**Comment by yasuyuki-nakazawa** [comment]
こちら、解決されているようですので、クローズさせていただきます
