### ISSUE TITLE
【質問】Mac 環境における API の利用について

### ISSUE THREAD

**Issue by hajime-f** [kabucom/kabusapi#339]
まだ調査を始めたばかりの段階ですので、私の理解が間違っていたら申し訳ございません。

API を利用するためには、
(1) ローカル環境で kabu ステーションを起動する
(2) localhost:18080 の各エンドポイントにアクセスする

という方法をとると理解いたしました。
（関連：https://github.com/kabucom/kabusapi/issues/34）

ところが、macOS 用に kabu ステーションが提供されていないので、
上記方法をとることができず、API 利用は Windows 環境に限られると、いまのところ認識しております。

もしこの理解が正しいなら、
(1) 現時点で、その他の方法により Mac 環境で API を利用できる方法はあるでしょうか？
(2) Windows 以外の環境で API を利用できるようにする予定はあるでしょうか？

私の理解が間違っており、すでに Mac 環境で利用できるのであれば、
詳細なドキュメントなどをご案内いただければ幸いです。

（個人的には、localhost 以外からのリクエストに対応できるようにするか、
localhost:18080 からシステムにトンネルする部分だけでも、
Windows 以外でリリースしていただければいいかなと思いました。。）

よろしくお願いいたします。

**Comment by yasuyuki-nakazawa** [comment]
現状ではMAC用のカブステーションが存在しないため、カブコムが利用想定の方式では利用はできません。

厳密に、この方法でという言及はできませんが、技術的観点でコメントさせていただきますと、
kabuステーションAPIはカブステと同一IPからのリクエスト以外をリジェクトします。
逆に言うと、カブステと同一IPからのリクエストであれば稼働します。

MACやLINUXサーバで稼働しているアルゴリズムをカブステが稼働している端末にリクエストを連携できれば理論上は要求事項が可能となるのではないでしょうか。

**Comment by hajime-f** [comment]
よく分かりました。ありがとうございます。

Windows 環境以外での利用や、localhost 以外からの利用も
ご検討いただければと思います。
よろしくお願いいたします。
