### ISSUE TITLE
【要望】localhost以外からのAPIアクセスについて

### ISSUE THREAD

**Issue by yukleides** [kabucom/kabusapi#34]
お世話になっております。
kabuステーションのAPIについて、localhostのみアクセスが許可されていると認識しておりますが、
localhost以外からもアクセスできるようにしていただけますと大変有り難く思います。
（セキュリティ上の制約もあるかと思いますので、例えば、設定でアクセスできるサブネットを指定できるなど）

例えばLinux上で走らせているPython等からkabuステーションAPIへのアクセスを想定しています。
ご検討のほど、宜しくお願い申し上げます。

**Comment by yasuyuki-nakazawa** [comment]
LocalHost以外からのリクエストに関しては強いご要望があがっております。
しかしながら、レギュレーション課題もあり、現状はLocalHostからのアクセスに制限をさせていただいております。

**Comment by yasuyuki-nakazawa** [comment]
ご要望頂いている当件ですが、現状は記載のとおりです。
別端末であるMACやLinuxからの「直接リクエストに対しての応答」はできません。

当要望におきましては、諸リスク勘案し検討いたします。

**Comment by iitenkida7** [comment]
自己責任ですが、

kabuステーション がインストールされた
Windows端末に nginxを導入し、リバースプロキシーとして動作させることにより、
外部からリクエストが可能となりましたので参考までに。

nginx.conf
``` 
worker_processes  1;
events {
    worker_connections  1024;
}
http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;

    map $http_upgrade $connection_upgrade { 
    default upgrade;
    ''      close;
    } 

    server {
        listen       80;
        server_name  localhost;

        proxy_http_version 1.1;
        proxy_set_header Host localhost;
        proxy_set_header Upgrade $http_upgrade; 
        proxy_set_header Connection $connection_upgrade;

        location / {
            proxy_pass   http://127.0.0.1:18080/;
        }
    }
}
```

上記では、通信が暗号化されていないので、ローカルネットワーク等安全が担保された経路でIP制限などして、
お試しください。また、Websocket に関してはまだ未検証です。

**Comment by tsuchinaga** [comment]
第3条2項に

> 情報を閲覧している端末機以外へ転載することを禁じます

とあります。また、第3条13項に

> 当社のシステム等の安全性を低下させる行為、当社のシステムの負荷を著しく増加させる行為を禁じます。

とあります。

抵触していませんか？

**Comment by tsuchinaga** [comment]
じゃあDockerは？とか、wslは？とか、考えなくはないですが……

**Comment by hajime-f** [comment]
お世話になります。nginxのリバプロによるAPIアクセスを試しています。

簡単なリバプロの設定と思うのですが、ハマってしまったらしく、うまく動作しません。
他に試すべきことはあるでしょうか？

【環境】
ローカルマシン：
- Windows 10
- nginx 1.21.0
- WSL2 Ubuntu 20.04
- Python 3.8.5

リモートマシン：
- macOS Big Sur
- Python 3.8.2

ローカルマシンとリモートマシンは同一のLAN内にあります。

【確認したこと】
- ローカルマシンでテスト環境 http://localhost:18081 からアクセストークンを取得できる
- デフォルトのnginx.confで、Welcome画面がローカル・リモートの両方で表示される

【試したことの手順と結果】
(1) nginx.confをリバースプロキシ用の設定（@iitenkida7さん記載の設定そのまま）に書き替える
(2) コマンドプロンプトからnginxを再起動する
    - nginx -s stop
    - start nginx
(3) ローカルマシンからブラウザで http://localhost/ にアクセスすると、404 Not Foundが表示される
(4) リモートマシンからブラウザで http://（ローカルマシンのIP）/ にアクセスすると、同様に404が表示される
(5) リモートマシンでテスト環境 http://（ローカルマシンのIP）:18081/ からアクセストークンの取得を試みるが、レスポンスがないままタイムアウトする

【困っていること】
リモートマシンからアクセストークンを取得できない
（APIにアクセスできず、上記手順の(5)でタイムアウトしてしまう）

【ご意見を伺いたいこと】
他に試すべきことはあるでしょうか？

Windows Defenderとか、そのあたりの設定ですかね。。？

**Comment by yasuyuki-nakazawa** [comment]
@hajime-f 
当チケットとは別に、新規でチケット上げていただいたほうがいいかもしれません。
内容も異なりますし。

レスポンスがなく、タイムアウトしている。とのことですが、カブステAPIのログとしてはリクエストの着信は確認できておるでしょうか。
おそらく、ノーレスポンスなので、カブステまで着信していないように見えますね。
nginxのリバプロの知見がないため、直接的な回答ができませんが、こちらも調べてはみます。
※別チケットの記載はお願いします

**Comment by hajime-f** [comment]
@yasuyuki-nakazawa 
ありがとうございます。チケットは上げなおしました。
https://github.com/kabucom/kabusapi/issues/343

C:\Users\（ユーザ名）\AppData\Roaming\KabuS にある2つのログを見ました。
- PLAIN_202100709_15.log
- KabuS_20210709.log

リモートマシンからトークン発行を試みたところ、
- 前者（PLAIN）は更新されない
- 後者（KabuS）は数分おきに更新される

後者の更新内容は、
```
16:01:00.5926,I,1384,0001 NewsHeaders: count=6181
16:02:16.6411,I,1384,0014 KeepSession at 2021/07/09 16:02:15
16:03:57.0427,I,1384,0001 NewsHeaders: count=6182
16:03:58.7992,I,1384,0001 NewsHeaders: count=6189
16:05:36.6549,I,1384,0014 KeepSession at 2021/07/09 16:05:35
16:08:47.4308,I,1384,0036 UpdateService.UpdateCheck : start
16:08:56.6576,I,1384,0033 KeepSession at 2021/07/09 16:08:55
```

となっています。

……が、これは kabu ステーションが動作している最中に吐く通常のログのように思われるので、
リモートマシンから API にアクセスしようとしていることとは無関係と考えています。

**Comment by fdfpy** [comment]
お世話になります。最近になってAPIを触っている者ですが分からない点があり、質問させてください。
Windows11上にDokcerコンテナを立ち上げ、curlコマンドで"http://localhost:18080/kabusapi/token"にアクセスしましたがうまくいきません。Win11上のDocker コンテナからKabu station APIにアクセスができている方が入れば、どのようにすればいいか教えていただけないでしょうか。
ちなみに、実施したことを下記に示します。



(1)Docker Desktopn for windowsでコンテナを作成

★docker-compose.yml
version: "3"
services:


  # バックエンド
  be:
    container_name: be0
    build: ./be
    volumes:
      - ./be/app:/app
    ports:
      - "5000:5000"
    command: tail -f /dev/null   #コンテナ起動状態を維持するため
    links:
      - db

★Dockerfile
FROM ubuntu:20.04
FROM python:3.9.2-buster

RUN apt-get update
RUN apt-get install lsof


# 必要パッケージのインストール

RUN apt install -y nodejs npm
RUN npm install python-shell
RUN npm install express
RUN npm install mysql

RUN mkdir /app
ADD requirements.txt /app

ENV PYTHONUNBUFFERED 1
EXPOSE 5000

WORKDIR /app
RUN pip3 install -r requirements.txt

(2)iitenkida7様 commented on Sep 11, 2020に従い、Win11上にnginxを導入

(3)Win11上ホスト コマンドプロンプトにて下記コマンドを実施し、トークンが取得できることを確認済

curl -X POST -H "Content-Type: application/json" "http://localhost:18080/kabusapi/token" -d "{\"APIPassword\":\"mypassword\"}"

(4)Win11 Dokcerコンテナ上で下記のコマンドを実施。応答が正常であることを確認


sh-5.0# curl (Win11のローカルIPアドレス):80
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
html { color-scheme: light dark; }
body { width: 35em; margin: 0 auto;
font-family: Tahoma, Verdana, Arial, sans-serif; }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>

(5))Win11 Dokcerコンテナ上で下記のコマンドを実施。APIにアクセス不可であることを確認

sh-5.0# curl -X POST -H "Content-Type: application/json" "http://(Win11のローカルIPアドレス):80/kabusapi/token" -d "{\"APIPassword\":\"mypassword\"}"
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.22.1</center>
</body>
</html>
