### ISSUE TITLE
【質問】空売り規制のレスポンスについて

### ISSUE THREAD

**Issue by kabucomapi** [kabucom/kabusapi#340]
お世話になります。
規制情報の空売り規制における「Reason」の内容を教えていただけないでしょうか。
よろしくお願いいたします。

**Comment by yasuyuki-nakazawa** [comment]
空売りに関しては、「空売り規制」という文言がReasonには設定されます

**Comment by kabucomapi** [comment]
回答ありがとうございます。
実動作でレスポンスが得ることが難しいので助かります。

**Comment by yasuyuki-nakazawa** [comment]
可能な限り、リファレンスも拡張させていただきます。
お気づきの点はお気軽にご意見いただければ幸いです
