### ISSUE TITLE
【質問】7/19以降のMarginTradeTypeについて

### ISSUE THREAD

**Issue by sotoboft** [kabucom/kabusapi#344]
現在MarginTradeTypeは、1=制度信用、2=一般信用長期、3=一般信用短期、となっていますが、7/19以降一般信用短期が無くなり、デイトレ信用が追加されることに伴い、どのように変更されますか？　3=デイトレ信用、となるのでしょうか？

**Comment by cyber-minion** [comment]
ご認識の通り、3 はデイトレ信用となります。

**Comment by sotoboft** [comment]
早速のご回答ありがとうございました。

**Comment by yasuyuki-nakazawa** [comment]
当件はクローズさせていただきます
