### ISSUE TITLE
【お知らせ】kabuステーションAPIデイトレ信用対応（2021年7月19日 ver5.14.0)

### ISSUE THREAD

**Issue by cyber-minion** [kabucom/kabusapi#345]
当社[デイトレ信用対応](https://kabu.com/company/pressrelease/20210607_3.html)の一環として、kabuステーションAPIにて下記の機能を提供することとします。

〇リリース日：2021年7月19日（日） 予定
　ver5.14.0
　以下機能はkabuステーションのバージョンアップ後にご利用になれます。
　インターフェースの詳細に関してはリリースと合わせて、リファレンスの更新を実施させていただきます。

〇対応機能
・注文発注（信用）API
　信用取引区分に「一般信用（デイトレ）」を新設します(※注記)。

・注文約定照会API
　レスポンスに「プレミアム料」という項目を新設します。

〇プレビュー
詳細につきましては、下記にてご確認ください。
▼ブランチはこちらです。
https://github.com/kabucom/kabusapi/tree/release/ver5.14.0
▼masterとの差分はこちらです。
https://github.com/kabucom/kabusapi/commit/781a05b1f86739f4fe5ddebdbaf23ff7fa827fa1

※注記
既存の一般信用（売短）を廃止します。

**Comment by tsuchinaga** [comment]
銘柄情報で、各銘柄の当日のプレミアム料の情報はとれませんか？

**Comment by cyber-minion** [comment]
銘柄情報でのプレミアム料の取得は今年年末提供する予定ですので、お待ちいただければ幸いです。

**Comment by cyber-minion** [comment]
C#のサンプルコードも併せて提供しますので、ご確認・ご利用いただければと思います。
▼ブランチはこちら
https://github.com/kabucom/kabusapi/tree/release/issue100
