### ISSUE TITLE
【質問】既発注の注文の変更

### ISSUE THREAD

**Issue by Atari7** [kabucom/kabusapi#347]
「kabuステーションAPI (1.5)」のAPI一覧を見たのですが、「注文変更」のようなリクエストが見当たりませんでした。既発注の注文を変更したい場合（株価を変更したい等）、いったんその注文をキャンセルしてから変更したい株価で新規オーダーを発行するということでよろしいのでしょうか？

初歩的な質問で恐縮ですがよろしくお願いします。

**Comment by tsuchinaga** [comment]
これと同じですかね #227

**Comment by Atari7** [comment]
さっそくのレスありがとうございます。ご指摘の通り同じ内容です。オープンのスレのみ表示していて気づきませんでした。
