### ISSUE TITLE
【質問】エクセルorder_sampleからの一括or順次連続新規発注

### ISSUE THREAD

**Issue by yuuta110** [kabucom/kabusapi#349]
お世話になります。

提供いただいております
kabuSTATION_API_ORDER_sample.xlsm
を使用して5つの信用新規発注を行おうとしたのですが…
No.1を処理後にNo.2の処理以降に進まず終わります。

マクロの内容は単純に
No.1~5　各行に発注に必要な情報を入れてから
For i = 1 To 5　~ Next i でセル"D4"に i をいれて マクロ"MarginTrading()"を実行を繰り返させる
としているのですが…

先の通りNo.1の処理のみ実行されて残りは発注されません。

一括or順次発注にはどうしたら良いでしょうか？

素人質問で申し訳ありませんがご教示の程、宜しくお願いいたします。

**Comment by yasuyuki-nakazawa** [comment]
コメントから判断するとループから処理が抜けてしまっているように見えます。
詳細はコードを見ないとわからないです。
D4に入れる値は数値ですよね。
単純な原因かとおもいます。可能な範囲でコードを連携いただければコメントも可能です。

**Comment by yuuta110** [comment]
お世話になります。
ループのコードは

 For i = 1 To 5
      Sheets(sheetname).Range("D4") = i
      Call MarginTrading
 Next i

※sheetnameには注文発注(信用)が入ります。

他マクロでNo.1～5に必要事項入力済みなにで上記の簡単なループ処理としています。
 ・Call MarginTrading　を入れないで実行するとRange("D4")にi(1～5)が入るのは確認済み
・No.2以降が処理されないとしたのは、注文が確認されないのと、シートの[発注結果（受付注文番号、メッセージ）]欄に
　何も記載されないため、実行されていないと判断。(No.1は両者確認できる。）

お手数をおかけしますがよろしくお願いいたします。

**Comment by yasuyuki-nakazawa** [comment]
非常にシンプルなコードなので、ループを抜ける条件にヒットしたと仮定して考えますと、この変数iのスコープがローカルではなくパブリックになっており、呼ばれているMarginTrading関数の中でも i を利用されて、i >5 となっていたりしませんでしょうか？

**Comment by yuuta110** [comment]
お世話になります。
ループカウンタ変数を　k　などに変えてみましたが、やはり1つ目の注文で止まりました。。。

他に何か可能性ありますでしょうか？

お手数をおかけしますがよろしくお願いいたします。

**Comment by yasuyuki-nakazawa** [comment]
ループカウンタの文字を変更しても結果は変わりません。
上述している通り、変数のスコープを確認して、Public変数になっていないか、ほか関数内で書き換わっていないかをトレースしてみることを提案いたします。
また、ExcelのVBAということであれば、デバックによるステップ実行も可能かと思います。
業単位でプログラムを実行し、結果を確認する等も思考いただければと存じます

**Comment by Atari7** [comment]
「Call MarginTrading」のあとに、DoEventsなどを使って数100ms程度のウェイト処理を入れてみてはどうでしょうか？

**Comment by yyy978** [comment]
すみません、やってみましたけど
ダメみたいですわ

**Comment by Atari7** [comment]
お役に立てずごめんなさい…。

エクセルの方は使ってないので「MarginTrading」の挙動など詳細わからないのですが、プログラムと不具合現象を読んだ第一感は「Kabuステーションの流量制限（1秒間5件以下）に引っかかって2個目以降のオーダーが通らないのでは？」と感じました。以下のような感じのコードをMarginTradingの直後に差し込んでもダメでしょうか？


---ここから---
Dim T0 As Single
T0 = Timer
Do
DoEvents
Loop While Timer < T0 + 0.2
---ここまで---

**Comment by yyy978** [comment]
ありがとうございました、無理のようです
「MarginTrading」自体を修正しないと無理なんですかね
作った人に聞いてみたい

**Comment by yasuyuki-nakazawa** [comment]
エクセルのアドインのソースコードも公開しております
必要がありましたら、ご確認ください
あわせて、当方でも調査してみます

**Comment by Atari7** [comment]
時間があったのでマクロの挙動を確認してみました。確かに皆さまと同じく1個目で処理が止まって2個目のオーダーを実行してくれませんでした。ソースコードを見てみたところ、「MarginTrading」からコールされている「SendOrder」というプロシージャの最後で強制的に処理を停止していました。（短いプロシージャなので張り付けておきます。「Catch:」の直前の「End」で処理が停止されます）。

---ここから---
Private Sub SendOrder(param As Dictionary, OutPutCol As String, RowNo As Long)
  On Error GoTo Catch
    Dim objHTTP As Object
    Set objHTTP = CreateObject("msxml2.xmlhttp")
    objHTTP.Open "POST", "http://localhost:" & PortNo & "/kabusapi/sendorder", False
    objHTTP.setRequestHeader "Content-Type", "application/json"
    objHTTP.setRequestHeader "X-API-KEY", ApiToken
    objHTTP.send JsonConverter.ConvertToJson(param)
    ActiveSheet.Range(OutPutCol & RowNo) = objHTTP.responseText
    
  End
Catch:
  ActiveSheet.Range(OutPutCol & RowNo) = "この要求の送信中にエラーが発生しました"
  End
End Sub
---ここまで---

回避方法を簡単に確認してみましたが、Worksheet_Changeイベントなどを使ってセルの内容が変更になったとき（＝オーダーの実行結果がセルに入力されたとき）に次の注文処理を行うようなプロシージャを新たに作れば連続注文可能なようです。（なおその際、適切なウェイト（0.2秒以上）を入れないとKabuステーションの流量制限に引っかかります）。

以上、何かのお役に立てば幸いです。

**Comment by Atari7** [comment]
連投失礼します。上でいろいろと書きましたが、実のところ一番シンプルな回避方法は上記SendOrderの「End」を「Exit Sub」に書き換えることです。それだけでForループが普通に通るようになります。

ただこの類の改変は、kabuステーションAPI開発者ポータルサービス利用規定に抵触するような気もします。（一方でそもそもソースコードが開示されているので、このレベルの修正は問題ないようにも思います）。カブコムさん側の見解を教えて頂けるとありがたいです。

**Comment by yyy978** [comment]
発注できるようなりました
ありがとうございました
本当に助かりました！！！！！！！

**Comment by cyber-minion** [comment]
解決済ですので、クローズいたします。
