### ISSUE TITLE
【質問】計算用現値CalcPriceについて

### ISSUE THREAD

**Issue by Ros522** [kabucom/kabusapi#35]
時価情報・板情報APIにて返却されるCalcPriceについて「計算用現値」という記載がありますが
これはどのような値でしょうか？
取引時間中であればCurrentPriceと一致する値となるでしょうか？

**Comment by cyber-minion** [comment]
確認いたします。

**Comment by cyber-minion** [comment]
CalcPriceとは、終値気配値、特別気配値、約定値、権利落修正理論価格の中から、
一定の基準に基づいて採用された価格で、各種指数を算出するために使われております。
基本的にCurrentPriceと一致しますが、異なる場合もございます。

**Comment by Ros522** [comment]
ご回答ありがとうございます。内容について理解いたしました。
