### ISSUE TITLE
【質問】"TradingVolume" が表す出来高の数値について

### ISSUE THREAD

**Issue by hajime-f** [kabucom/kabusapi#350]
お世話になります。

ある時点において板情報を取得した場合、JSON に含まれる「TradingVolume」の値は、具体的にどのような「出来高」を示しているでしょうか？

「その日におけるその時点までの出来高」で合っているでしょうか？
（各日で数値が単調増加しているので、そう推測してます）

**Comment by cyber-minion** [comment]
ご認識の通り、「その日におけるその時点までの出来高」であっています。

**Comment by yasuyuki-nakazawa** [comment]
こちら、クローズさせていただきます。
