### ISSUE TITLE
【質問】銘柄情報の取得パラメータについて

### ISSUE THREAD

**Issue by tks1002** [kabucom/kabusapi#355]
http://localhost:18080/kabusapi/symbol/{symbol}
にアクセスし、[TradeStart]を取得しようとしましたが、そのようなKeyはありませんでした。リファレンスではばっちり載ってますが、削除されたのでしょうか？

**Comment by tsuchinaga** [comment]
銘柄コードはなんですか？

**Comment by hishiharahaz** [comment]
@tks1002 
リファレンスには「※先物・オプション銘柄の場合のみ」と記載がありましたので、先物・オプションの時のみレスポンスされる項目なのかもしれません。

**Comment by tks1002** [comment]
![無題](https://user-images.githubusercontent.com/88259474/127874024-956483e0-5457-4b1b-9abf-dbcb96532204.png)

リファレンスのレスポンス例と実際のapiのレスポンスが違いますが、これってどういうことでしょうか？

**Comment by cyber-minion** [comment]
リファレンスを補完させていただきます。

**Comment by tks1002** [comment]
よろしくお願いいたします。あと要望なんですが、まぁ大体はわかるんですが、パラメータの意味が分かるようなリファレンスがあると助かります。例えば今回の件でいうとSymbol：銘柄コード、TradeStart：上場開始日など。たまに何のパラメータなのか、ほしいパラメータの命名はなんなのかわかりずらいと感じました。

**Comment by yasuyuki-nakazawa** [comment]
パラメータの意味については記載されている認識ですが、いかがでしょうか

**Comment by tks1002** [comment]
パラメータの意味の意味ではなく、レスポンスの意味です。例えば銘柄情報を取得したらレスポンスとして返るのが
Symbol:銘柄コード
SymbolName：銘柄名
DisplayName：表示名
Exchange：市場コード
ExchangeName：市場名
・・・
ClearingPrice：需給均衡化価格？
まぁ、無理にとは言いませんが、あればいいなぁ程度です

**Comment by yasuyuki-nakazawa** [comment]
> パラメータの意味ではなく、レスポンスの意味です
こちらも記載ございます。
リファレンスの正常リターン（200)の記載部分を展開いただければ、明記されております
ご確認くださいませ

**Comment by tks1002** [comment]
ああ、確かに。ありました。教えていただいてありがとうございます

**Comment by yasuyuki-nakazawa** [comment]
こちらはクローズとさせていただきます
