### ISSUE TITLE
【質問】　C#  12．注文約定照会にてデシリアライズ

### ISSUE THREAD

**Issue by MitsuguKondo** [kabucom/kabusapi#357]

**Comment by yasuyuki-nakazawa** [comment]
うまく取得することができない。というのは、具体的にどのような状況でしょうか。
エラーが返ってくる場合は、エラーコードを記載いただけますか。

**Comment by MitsuguKondo** [comment]
Json ファイルから C# Classes Onlineに上手く変換出来ていないと思います
階層になっているので上手くいきまん

よろしくお願いいたします。

**Comment by yasuyuki-nakazawa** [comment]
不正となっている部分のプログラムを可能な限りで記載いただけると、ご提案等ができるかと存じます。
（階層になっていても、特段問題なく処理は可能なため。）

**Comment by MitsuguKondo** [comment]
ソースファイルを下記します
Json ファイルから C# Classes Onlineにつきましては無料の変換サイトを見つけまして変換してみました
問題として階層下の値段データの取得が上手くいきません
よろしくお願いいたします。

class Cls_Kabusapi_Orders
    {
        private string m_strRet;

        private string m_Token;
        private string product = "0";
        private string m_symbol;

        private string my_Symbol_R = "0";
        private string my_SymbolName = "-";
        private string my_CumQty = "0";
        private string my_Price = "0";
        private string my_Side = "0";

        public void Kabusapi_Orders()
        {
            var builder = new UriBuilder("http://localhost:18080/kabusapi/orders");
            var param = System.Web.HttpUtility.ParseQueryString(builder.Query);
            if (!string.IsNullOrEmpty(product))
            {
                param["product"] = product;
            }
            if (!string.IsNullOrEmpty(m_symbol))
            {
                param["symbol"] = m_symbol;
            }
            //if (!string.IsNullOrEmpty(state))
            //{
            //    param["state"] = state;
            //}

            builder.Query = param.ToString();

            string url = builder.ToString();
            try
            {
                var client = new HttpClient();
                var request = new HttpRequestMessage(HttpMethod.Get, url);
                request.Headers.Add("X-API-KEY", m_Token);
                HttpResponseMessage response = client.SendAsync(request).Result;
                //my_json = ("{0} \n {1}", JsonConvert.DeserializeObject(response.Content.ReadAsStringAsync().Result), response.Headers);

                List<Root_Orders> myDeserializedClass = JsonConvert.DeserializeObject<List<Root_Orders>>(response.Content.ReadAsStringAsync().Result);
                if (myDeserializedClass.Count > 0)
                {
                    int Count;
                    myDeserializedClass.ForEach(ramen =>
                    {
                        my_Symbol_R = ramen.Symbol;                 //銘柄コード
                        my_SymbolName = ramen.SymbolName;           //銘柄名
                        my_Side = ramen.Side;                       //売買区分
                        my_CumQty = ramen.CumQty.ToString();        //約定数量
                        my_Side = ramen.Side;                       //売買区分

			//値段のデータが欲しいのですがやり方が分かりません//////
                    });
                }
            }
            catch (HttpRequestException e)
            {
                m_strRet = Convert.ToString(e);
            }
            catch (Exception ex)
            {
                m_strRet = Convert.ToString(ex);
            }

        }

**Comment by MitsuguKondo** [comment]
もう一つあります
ﾎﾟｼﾞｼｮﾝが１銘柄の時は上手く行きますが複数になると
                List<Root_Positions> myDeserializedClass
                    = JsonConvert.DeserializeObject<List<Root_Positions>>(response.Content.ReadAsStringAsync().Result);
の所でエラーが発生します

これも分かりません



namespace Win_KabuComAPI
{

    public class Root_Positions
    {
        public int MarginTradeType { get; set; }
        public int ExecutionDay { get; set; }
        public double Expenses { get; set; }
        public double Commission { get; set; }
        public double CommissionTax { get; set; }
        public int ExpireDay { get; set; }
        public string ExecutionID { get; set; }
        public int AccountType { get; set; }
        public string Symbol { get; set; }
        public string SymbolName { get; set; }
        public int Exchange { get; set; }
        public string ExchangeName { get; set; }
        public double Price { get; set; }
        public double LeavesQty { get; set; }
        public double HoldQty { get; set; }
        public string Side { get; set; }
        public double CurrentPrice { get; set; }
        public double Valuation { get; set; }
        public double ProfitLoss { get; set; }
        public double ProfitLossRate { get; set; }
    }



    class Cls_Kabusapi_Positions
    {
        private string m_strRet;
        private string m_Token;
        private string m_product = "0";
        private string m_symbol;
        private string m_addinfo = "true";

        private string my_Symbol_R;
        private string my_SymbolName;
        private string my_LeavesQty;
        private string my_Price;
        private string my_CurrentPrice;
        private string my_ProfitLoss;
        private string my_Side;
        private int iCount;


        public void Kabusapi_Positions()
        {

            var builder = new UriBuilder("http://localhost:18080/kabusapi/positions");
            var param = System.Web.HttpUtility.ParseQueryString(builder.Query);
            if (!string.IsNullOrEmpty(m_product))
            {
                param["Product"] = m_product;
            }
            if (!string.IsNullOrEmpty(m_symbol))
            {
                param["symbol"] = m_symbol;
            }
            if (!string.IsNullOrEmpty(m_addinfo))
            {
                param["addinfo"] = m_addinfo;
            }

            builder.Query = param.ToString();
            string url = builder.ToString();
            try
            {
                var client = new HttpClient();
                var request = new HttpRequestMessage(HttpMethod.Get, url);
                request.Headers.Add("X-API-KEY", m_Token);
                HttpResponseMessage response = client.SendAsync(request).Result;

                List<Root_Positions> myDeserializedClass
                    = JsonConvert.DeserializeObject<List<Root_Positions>>(response.Content.ReadAsStringAsync().Result);

                iCount = 0;
                if (myDeserializedClass.Count > 0)
                {
                    myDeserializedClass.ForEach(ramen =>
                    {
                        my_Symbol_R = ramen.Symbol;                         //銘柄コード
                        my_SymbolName = ramen.SymbolName;                   //銘柄名
                        my_CurrentPrice = ramen.CurrentPrice.ToString();    //現在値
                        my_ProfitLoss = ramen.ProfitLoss.ToString();        //評価損益額
                        my_LeavesQty = ramen.LeavesQty.ToString();          //残数量
                        my_Price = ramen.Price.ToString();                  //残数量
                        my_Side = ramen.Side;                               //売買区分
                    });
                }
            }
            catch (HttpRequestException e)
            {
                m_strRet = Convert.ToString(e);
            }
            catch (Exception ex)
            {
                m_strRet = Convert.ToString(ex);
            }

        }


        public string inp_Token
        {
            set { m_Token = value; }
        }

        public string inp_symbol
        {
            set { m_symbol = value; }
        }


        public string out_Symbol
        {
            get { return my_Symbol_R; }
        }

        public string out_SymbolName
        {
            get { return my_SymbolName; }
        }

        public string out_LeavesQty
        {
            get { return my_LeavesQty; }
        }

        public string out_Price
        {
            get { return my_Price; }
        }


        public string out_CurrentPrice
        {
            get { return my_CurrentPrice; }
        }

        public string out_ProfitLoss
        {
            get { return my_ProfitLoss; }
        }
        public string out_Side
        {
            get { return my_Side; }
        }
    }
}

**Comment by MitsuguKondo** [comment]
その後検討を続け上手くいきました
この要望は取り下げでお願いします

参考になったのは
無料コンパート https://json2csharp.com/  
参考になりました

尚、階層は使用しなくても良くなりました

出来上がりソフトは以下の様になりました


    public class Root_Positions
    {
        public int MarginTradeType { get; set; }
        public int ExecutionDay { get; set; }
        public double Expenses { get; set; }
        public double Commission { get; set; }
        public double CommissionTax { get; set; }
        public int ExpireDay { get; set; }
        public string ExecutionID { get; set; }
        public int AccountType { get; set; }
        public string Symbol { get; set; }
        public string SymbolName { get; set; }
        public int Exchange { get; set; }
        public string ExchangeName { get; set; }
        public double Price { get; set; }
        public double LeavesQty { get; set; }
        public double HoldQty { get; set; }
        public string Side { get; set; }
        public double CurrentPrice { get; set; }
        public double Valuation { get; set; }
        public double ProfitLoss { get; set; }
        public double ProfitLossRate { get; set; }
    }

    class Cls_Kabusapi_Positions
    {
        private string m_strRet;
        private string m_Token;
        private string m_product = "0";
        private string m_symbol;
        private string m_addinfo = "true";

        private string my_Symbol_R;
        private string my_SymbolName;
        private string my_LeavesQty;
        private string my_Price;
        private string my_CurrentPrice;
        private string my_ProfitLoss;
        private string my_Side;

        public void Kabusapi_Positions()
        {

            var builder = new UriBuilder("http://localhost:18080/kabusapi/positions");
            var param = System.Web.HttpUtility.ParseQueryString(builder.Query);
            if (!string.IsNullOrEmpty(m_product))
            {
                param["Product"] = m_product;
            }
            if (!string.IsNullOrEmpty(m_symbol))
            {
                param["symbol"] = m_symbol;
            }
            if (!string.IsNullOrEmpty(m_addinfo))
            {
                param["addinfo"] = m_addinfo;
            }

            builder.Query = param.ToString();
            string url = builder.ToString();

            try
            {
                var client = new HttpClient();
                var request = new HttpRequestMessage(HttpMethod.Get, url);
                request.Headers.Add("X-API-KEY", m_Token);
                HttpResponseMessage response = client.SendAsync(request).Result;
                //my_json = ("{0} \n {1}", JsonConvert.DeserializeObject(response.Content.ReadAsStringAsync().Result), response.Headers);
                List<Root_Positions> myDeserializedClass = JsonConvert.DeserializeObject<List<Root_Positions>>(response.Content.ReadAsStringAsync().Result);

                foreach (Root_Positions obj in myDeserializedClass)
                {
                    my_Symbol_R = obj.Symbol;                         //銘柄コード
                    my_SymbolName = obj.SymbolName;                   //銘柄名
                    my_CurrentPrice = obj.CurrentPrice.ToString();    //現在値
                    my_ProfitLoss = obj.ProfitLoss.ToString();        //評価損益額
                    my_LeavesQty = obj.LeavesQty.ToString();          //残数量
                    my_Price = obj.Price.ToString();                  //残数量
                    my_Side = obj.Side;                               //売買区分
                }
 
            }
            catch (HttpRequestException e)
            {
                m_strRet = Convert.ToString(e);
            }
            catch (Exception ex)
            {
                m_strRet = Convert.ToString(ex);
            }
        }

**Comment by yasuyuki-nakazawa** [comment]
当件はクローズいたします
