### ISSUE TITLE
kabustationから強制切断される

### ISSUE THREAD

**Issue by chocopon** [kabucom/kabusapi#358]
■カブステーションか強制切断される（ごく稀に）
■安定的な通信
■9:00:01
■Windows Server (conoha VPS) , python3.9
■ Error:[WinError 10054] 既存の接続はリモート ホストに強制的に切断されました。
　kabustationは起動したままであり、再接続は可能。

接続が切れる前提でスクリプトを作るべきですかね。

**Comment by tsuchinaga** [comment]
下記が参考になるのではないかと

#175 #284

**Comment by yasuyuki-nakazawa** [comment]
既に @tsuchinaga さんがメンションいただいておりますが、ご参考になると思います
端末の設定変更で改善される可能性がございますので、お試しください

**Comment by yasuyuki-nakazawa** [comment]
こちら、上記ご案内の通り、過去お問い合わせと重複していることが想定されます
当スレッドはクローズさせていただきます
