### ISSUE TITLE
【質問】kabuステーションAPIの執行条件の種類について

### ISSUE THREAD

**Issue by kero5512** [kabucom/kabusapi#359]
APIリファレンスを見ると下記の執行条件は設定できるようですが、WEB経由で執行できるW指値、±指値、Uターン注文などの自動売買執行条件では発注できないとの認識であってますでしょうか？

10	成行	0
13	寄成（前場）	0
14	寄成（後場）	0
15	引成（前場）	0
16	引成（後場）	0
17	IOC成行	0
20	指値	発注したい金額
21	寄指（前場）	発注したい金額
22	寄指（後場）	発注したい金額
23	引指（前場）	発注したい金額
24	引指（後場）	発注したい金額
25	不成（前場）	発注したい金額
26	不成（後場）	発注したい金額
27	IOC指値	発注したい金額
30	逆指値	

よろしくお願い致します。

**Comment by yasuyuki-nakazawa** [comment]
回答としては、記載されている執行条件のみのご提供となっております。
将来的な拡張は検討の余地がございますが、APIの特性上、シンプルな執行条件に絞らせていただき、提供する形をとっております

**Comment by kero5512** [comment]
ご回答ありがとうございました。
