### ISSUE TITLE
【質問】時価情報・板情報のPUSH配信の寄付時の各値について

### ISSUE THREAD

**Issue by Ros522** [kabucom/kabusapi#36]
寄付前気配、および昼休みのPUSH配信APIの仕様についてご教授お願いいたします。
こちら側の不具合の可能性もございますので、まずはデータ配信のタイミング、値について明確にしていただきたく。

■寄付前気配について
　（１）データ配信は有り、という理解でよいでしょうか
　（２）一部配信されてこない(null?)ように見えている項目がございます。（CurrentPriceなど)　配信されてこない項目値を明確にしていただくことは可能でしょうか。
　（３）板寄せ中かの判断についてはBidSign、AskSignを見るのが適切でしょうか。CurrentPriceStatusについても寄り付き前気配にて配信なし(null)となるでしょうか？

■昼休み
　（１）データ配信は無し、という理解でよいでしょうか

**Comment by cyber-minion** [comment]
確認いたします。

**Comment by yasuyuki-nakazawa** [comment]
寄付き
データの配信仕様に関しての詳細は申し訳ございませんが、未公開となっております。
公開できる範囲で順次リファレンスの拡張を実施させて頂きます。
（１）（２）
PUSH配信に関してですが、寄前であってもkabuステーションに配信があった情報に関しては同様に配信されます。
未配信の情報に関してはNullとなっていると想定されます。
（３）
CurrentPriceStatusに関しては別途調査の上、こちらに展開させて頂きます

昼休みに関しても上述のとおり、kabuステーション上に配信されている情報に関しては配信されます。

**Comment by Ros522** [comment]
ご回答ありがとうございます。
CurrentPriceStatusを含め、リファレンスの充実をお待ちしています。
