### ISSUE TITLE
【不具合】株ステーションのチャートが表示されない

### ISSUE THREAD

**Issue by tks1002** [kabucom/kabusapi#360]
APIの動作不具合ではないが、株ステーションに大きな機会損失の可能性大
■[必須] 不具合事象(概要)
チャートが表示さない
■[必須] 本来想定されるアクションと事象
チャートが表示される
■[必須] 不備発生時刻（常時の場合は、常時で記載ください)
発生タイミングは適当な数の銘柄コードを順々にダブルクリックしてチャートの観察をしている際に突然発生する。サーバーからのデータ遅延など考えて、しばらく待ってたが回復するときと１時間たっても解消されない場合がある
■[任意] お使いの環境(OS、Excelのバージョン等)、サンプル(Macro、アドインのバージョン）
Windows10 Home/kabu Station ver.5.14.00
■[任意] 不備部分のログ
![image](https://user-images.githubusercontent.com/88259474/128796674-ed4f31fb-bd34-4389-b6e7-fda2a5c8ac39.png)

**Comment by yasuyuki-nakazawa** [comment]
システム的なチェックを実施してみましたが異常は確認できませんでした
カブステーションの再起動、ルータの再起動で改善される場合がありますが、いかがでしょうか

**Comment by tks1002** [comment]
再起動試みましたが改善されませんでした。再インストールして様子見ます。どういったタイミングで発生するかわかってないんですが、銘柄登録してるコードをダブルクリックで順々にチャートを表示していくと突然歩み値もチャートもブラックアウトします。板は表示されてます。

**Comment by yasuyuki-nakazawa** [comment]
当該事象が出た際に、カブステのログ上でエラーがないかをご確認いただけると幸甚です
％appdata％ kabusにlogというフォルダがあります

**Comment by tks1002** [comment]
再発しました。原因わからず。logを添付いたしますので解析お願いできますか。
[NetLib.Server.20210824.log](https://github.com/kabucom/kabusapi/files/7033050/NetLib.Server.20210824.log)
[KabuS_20210824.log](https://github.com/kabucom/kabusapi/files/7033052/KabuS_20210824.log)

**Comment by tks1002** [comment]
原因わかりませんか？この現象発生すると30min～1hほどチャートが表示されません。

**Comment by yasuyuki-nakazawa** [comment]
セキュリティソフト関連とか何かお使いでしょうか？
これから詳細を調査していきますが、チャートの情報を出力するサーバへ接続できない（通信遮断等が発生している可能性）状況が発生しています。
切り分けのため、セキュリティソフトをいったんオフにした状態でお試しいただけますか。

**Comment by tks1002** [comment]
セキュリティソフトはwin difenderだけですね。一度difenderをoffにしてPC再起動&カブステ起動から銘柄登録リストにある銘柄を「↓ to Enter」で順々にチャートを表示してみましたが、再発しました。何個かまでは順調にチャートが表示されますが、途中でチャートと歩み値がブラックアウトしました。再現できませんか？私の環境だけなのでしょうか。

**Comment by yasuyuki-nakazawa** [comment]
当該事象が発生している、ほかのユーザーのかた、いらっしゃいますでしょうか？
数環境で確認しましたが、該当事象は発生しておりません。
ログを拝見した限りカブステーションのチャート情報を取得する際のサーバへの接続がブロックされているようにみられるため、セキュリティソフト以外の可能性としては、回線を変更してお試しいただくことは可能でしょうか

**Comment by tks1002** [comment]
回線を変更するのは厳しいですね。そのようなものは持ち合わせてないです。そもそも接続がブロックされるってどういった条件で発生するんでしょうか？株ステーションがそういったロジックを組んでるんですよね？この事象なかなかイラつきますｗ売買ができないですからね。

**Comment by yasuyuki-nakazawa** [comment]
この事象に関して、カブステとしては、特段制御ロジックをいれることはしていません。
カブステからのリクエストが、何らかの理由でブロックされている事はログから判明しております
過去のカブステのお問い合わせとして、チャートが出力されない場合、セキュリティソフトやプロバイダやルータのファイヤーウォール設定であるケースがかなりありました。
チャート情報を管理しているサーバーまでリクエストが到達しておりませんので、その間のネットワーク類の可能性が高いと想定されます

**Comment by yasuyuki-nakazawa** [comment]
当件ですがクローズさせて頂きます
チャート非表示は上述した原因であることが過去の事例では多かったため、こちらをご確認いただければと思います
