### ISSUE TITLE
【質問】特別気配時の寄り付き前現値取得とリアルタイム株価予測のAPI実装予定について

### ISSUE THREAD

**Issue by YOHSIKI** [kabucom/kabusapi#362]
いつもお世話になっております。
主題の件について、質問がありますので投稿させていただきました。

１．特別気配時の寄り付き前現値取得について
PUSH配信では現値を"Current Price"で取得できますが、寄り付きで特別気配となったような場合、
始値が確定する寄り付き前の板を消化した途中の暫定価格が取得できるという理解であっておりますか。
そうでない場合、寄り付き前の気配値を取得する方法はありますか。
（具体的な運用イメージは、発注をかけている銘柄のうち、寄り付き前に高騰や暴落しすぎているものを検知したいです。）

２．リアルタイム株価予測のAPI実装予定について
PUSH配信のAPIリファレンスを見る限り、「リアルタイム株価予測」のAPIは未実装のようですが対応予定はありますか。
以下のプレスリリースでは、2021年5月に対応予定となっておりましたが、実装の目処等が立っているようでしたら
ご教示のほどお願いいたします。
https://kabu.com/sp/company/pressrelease/20210122_1.html
（これも始値の予想として参考値になるので、高騰暴落銘柄の検知に使えると思いました。）

以上、お手数おかけしますがよろしくお願いいたします。

**Comment by YOHSIKI** [comment]
いつもお世話になっております。

質問の件、いかがでしょうか。
回答が難しいためスルーされているのでしょうか。

**Comment by yasuyuki-nakazawa** [comment]
@YOHSIKI 
回答が遅くなり申し訳ございません
1.寄り付き前の気配を取得することはできません
ご記載頂いている処理を行いたい場合はリアルタイム株価予測の情報を利用されるのが適切と考えます
2の回答にもなりますが、リアルタイム株価予測のインターフェース提供は他カブステーションのアップデートの都合上遅れており、ご不便をおかけしておりますが、今しばらくお待ちいただけると幸甚です

**Comment by YOHSIKI** [comment]
ご回答ありがとうございます。
ですが、流石に回答がおそすぎると思うのでもう少し早く回答いただけると助かります。
他の開発が優先されているため、当該機能のAPI実装が遅れている旨は承知いたしました。
引き続きよろしくお願いいたします。
