### ISSUE TITLE
【質問】注文パスワードについて

### ISSUE THREAD

**Issue by hajime-f** [kabucom/kabusapi#363]
お世話になります。

発注系 API に対する API リファレンス記載の「注文パスワード」は、
(1) 出金パスワード
(2) API パスワード（アクセストークン取得時のパスワード）
(3) 新 API パスワード

のいずれでしょうか？
（いろいろなパスワードがあるので。。上記 (2) で合っているでしょうか？）

また、実際に発注することなく、そのパスワードで認証が通るかどうかを検証したいのですが、
どうすればいいでしょうか？

初歩的な質問で恐縮ですが、よろしくお願いいたします。

**Comment by hishiharahaz** [comment]
@hajime-f 
注文パスワードは、kabuステーションへのログインパスワードを指定すればよいかと思います。

**Comment by yasuyuki-nakazawa** [comment]
当件は解決しているようなので、クローズいたします
