### ISSUE TITLE
EXCELでの返済注文において決済順序を選択すると「"Code":1009001,"Message":"建玉が選択されていません」とでます

### ISSUE THREAD

**Issue by yyy978** [kabucom/kabusapi#365]
※決済順序、返済建玉指定はどちらか一方のみ入力
と記述がありまして

EXCELでの返済注文において「返済建玉指定」をする場合は問題なく注文が通るのですが
返済建玉指定に入力してある項目を削除し
「決済順序」を選択すると「"Code":1009001,"Message":"建玉が選択されていません」とでます

これはなぜでしょうか？

**Comment by yasuyuki-nakazawa** [comment]
設定しているパラメータを含めて記載いただけると幸甚です

**Comment by yyy978** [comment]
返信ありがとうございます
下記のようになります

例えば
No　　　　　　　　　　　　　　	1
銘柄コード　　　　　　　　　　　	6740
市場	　　　　　　　　　　　　　　　東証
売買区分　　　　　　　　　　　　	売
現物信用区分　　　　　　　　　　	返済
信用取引区分　　　　　　　　　	一般信用（デイトレ）
１株あたりのプレミアム料	
受渡区分	　　　　　　　　　　　　自動振替
口座種別　　　　　　　　　　　　	特定
注文数量　　　　　　　　　　　　	100
決済順序　　　　　　　　	　損益（高い順）、日付（新しい順）
返済建玉ID	
返済建玉数量	
注文価格　　　　　　　　　　　　	0
注文有効期限　　　　　　　　　　	0
執行条件	　　　　　　　　　　引成(後場)
トリガ銘柄	
トリガ価格	
以上／以下	
ヒット後執行条件	
ヒット後注文価格	
発注結果（受付注文番号、メッセージ）	{"Code":1009001,"Message":"建玉が選択されていません。"}

**Comment by Atari7** [comment]
直接の回答ではないですが、ちょっと思ったことをレスしておきます。

リクエストボディのClosePositionOrderという変数の設定値を決めるために、MarginTradingから「GetClosePositionOrder」という下記の短い関数がコールされます。

---ここから---
Private Function GetClosePositionOrder(val As String)
  Select Case val
    Case "日付（古い順）、損益（高い順）": GetClosePositionOrder = 0
    Case "日付（古い順）、損益（低い順）": GetClosePositionOrder = 1
    Case "日付（新しい順）、損益（高い順）": GetClosePositionOrder = 2
    Case "日付（新しい順）、損益（低い順）": GetClosePositionOrder = 3
    Case "損益（高い順）、日付（古い順）": GetClosePositionOrder = 4
    Case "損益（高い順）、日付（新しい順）": GetClosePositionOrder = 5
    Case "損益（低い順）、日付（古い順）": GetClosePositionOrder = 6
    Case "損益（低い順）、日付（新しい順）": GetClosePositionOrder = 7
    Case "": GetClosePositionOrder = ""
    Case Else: GetClosePositionOrder = 999
  End Select
End Function
---ここまで---

引数valの設定値を一字一句合わせないと「Case Else: GetClosePositionOrder = 999」の部分が走ってしまってまともに動きません。なのでヒューマンエラーを避けるために普通はエクセルシートの入力部分でプルダウンにするはずなのですが、なぜかプルダウンになってないですね。ここはプルダウンにすべきだと思います。

逆にyyy978さんのエクセルシート上の設定値の「損益（高い順）、日付（新しい順）」にスペースとかタブとか改行とか紛れ込んでないですかね？

**Comment by yyy978** [comment]
返信ありがとうございます

たぶん関係ないかなー、思います（間違ってたらすみません）

ためしに
Case Else: GetClosePositionOrder = 999
を
Case Else: GetClosePositionOrder = 0

に改変してみましたが
'{"Code":1009001,"Message":"建玉が選択されていません。"}
となりました
バグですね

**Comment by yasuyuki-nakazawa** [comment]
受渡区分以外、同パラメータで発注確認してみましたが、こちらでは問題なく発注が完了します。
同事象になっていらっしゃる他の方とかいらｓっしゃいますでしょうか。

**Comment by sakurajane** [comment]
エクセルマクロの発注部分で、リクエストの内容を出力すると原因がわかるかもしれませんね。

' 注文発注(信用)
Public Sub MarginTrading()

＜最後の方＞
'MsgBox JsonConverter.ConvertToJson(param)

Range("X1").Value = JsonConverter.ConvertToJson(param)  'X1のセルにリクエストを出力する処理を追加

' APIリクエスト
Call SendOrder(param, OutPutCol, RowNo)

**Comment by yyy978** [comment]
回答ありがとうございます
パラメーターはテキトーにふってるので上記のこだわる必要はないんですが
自分は同じ結果でした

もしかして
発注確認を本番用でやってますか？
自分は超初心者なので検証用しか使ったことないので

**Comment by yasuyuki-nakazawa** [comment]
@yyy978 
発注確認は本番用を利用して実施しています。

**Comment by yyy978** [comment]
本番用で試しました
無事できました、ありがとうございました

**Comment by cyber-minion** [comment]
問題解決したようですので、クローズします。
