### ISSUE TITLE
【質問】注文変更時の待ち時間設定

### ISSUE THREAD

**Issue by ob2r** [kabucom/kabusapi#367]
python使用です。
注文変更するために、
初めに注文をキャンセルしてから
再度注文を入れたのですが、
({"Code":1009001,"Message":"建玉が選択されていません。"})
と表示され再発注ができませんでした。
キャンセルと再発注の間に待ち時間がなかったため発生したのかと思い質問します。

今回のように注文変更する場合、キャンセルAPI実行と注文API実行の間の推奨待機時間はありますか?

**Comment by Atari7** [comment]
質問に対するダイレクトな回答ではないのですが、キャンセル発行後にそのオーダーのStateが5（終了）になったのを確認してから新規のオーダーを発行するのではダメでしょうか？

なお本題とは違いますが、APIに注文変更のリクエストがないために本件のようにユーザ側プログラムで煩雑な処理が増えてしまうことが少なからずあるように思います。自分の場合は他証券会社からの乗り換えなのですが、注文変更リクエストがAPIにないがために面倒なプログラム変更を強いられました。注文変更はカブコムさん側のインパクトが大きくサポートしない方向と認識していますが、個人的には再検討の余地ありではないかと感じます。

**Comment by ob2r** [comment]
回答ありがとうございます。

待機時間を設けるより、注文キャンセルできたか確認してからの再注文の方が確実ですね。
