### ISSUE TITLE
kabuSTATION_API_function_xlsm利用者です。残高照会自動化するため、shinoperさんが紹介しているコードを使って、コーディングしました。作成したPCでは問題なく動きますが、Surfaceに移したら正常に作動しません。問題のコードは、Range("D21").Select ActiveCell.FormulaR1C1 = "=POSITIONS(R[-13]C[-1])"で、Surfaceでは"D21"～該当セル全てに　=@POSITIONS(C8) と代入値が隠れて入っております。作動するPCエクセルビルド#1808(ビルド10376.20033)、Surface#2106(14131.20278)です。マニュアルで　=POSITIONS(C8)　を入力すれば、Surfaceでも正常に作動します。@が表示されないようにする方法を教えていただけますでしょうか。

### ISSUE THREAD

**Issue by skytreetokyo** [kabucom/kabusapi#371]

**Comment by Atari7** [comment]
Excelのバージョン1911で数式関連の大幅アップグレードがあったようですが、PCのExcel（1808）とSurfaceのExcel（2106）でそのアップグレードを挟んでしまっているようですね。「Range("D21").Select ActiveCell.FormulaR1C1」の「FormulaR1C1」を新しい関数「Formula2R1C1」に置き換えてみたらどうでしょうか？

**Comment by skytreetokyo** [comment]
Atari7さん、ありがとうございました。

関数「Formula2R1C1」に置換えたところ、問題解決できました。
vba, kabuST_API,GitHub、いずれも初級者で一人で試行錯誤しながら困っておりました。
重ね重ね御礼申し上げます。

**Comment by cyber-minion** [comment]
解決済ですので、クローズさせていただきます
