### ISSUE TITLE
高速同時発注につきまして 

### ISSUE THREAD

**Issue by 4494ku** [kabucom/kabusapi#372]
#102 を見ての質問です
秒間の発注制限（現状５件）の規制は現在も変わっておりませんか？
ということは場中1分間に最高３００件の注文が可能ということでしょうか？
また規制に抵触した場合は発注が通らない以外罰則？はあるのでしょうか？

**Comment by yasuyuki-nakazawa** [comment]
秒間の流量制限は現状変更ありません。
理論上は場中に最高３００件というのは可能です。
流量制限に抵触した注文は発注エラーとなる仕様です

**Comment by 4494ku** [comment]
流量制限に抵触した注文とは秒間の発注制限（５件）だけですか？
