### ISSUE TITLE
【質問】その後の進捗状況等について

### ISSUE THREAD

**Issue by peichan0823** [kabucom/kabusapi#374]
以下、2点の内容について、現時点における、その後の進捗状況、今後の予定を教えて下さい。

https://github.com/kabucom/kabusapi/issues/92#issuecomment-697126029

https://github.com/kabucom/kabusapi/issues/191#issuecomment-737696656

**Comment by yasuyuki-nakazawa** [comment]
#92 に関しては、カブステーションを起動せずAPIを利用いただける形はとれないというステータスは変わりません。
また、現在ToB向けとして開放しているAPIの個人向け解放につきましても、提供側の諸管理監督義務の関係上、ペンド状態です。

#191 こちらに関しては、過去の要望と対応一覧、質問を整理したFAQという形での集約公開想定。
他案件状況との兼ね合いで調整の上、という状況のため、時期感はお約束できない状況でございます

**Comment by yasuyuki-nakazawa** [comment]
こちらはクローズさせていただきます
