### ISSUE TITLE
【質問】ReverseLimitOrderについて

### ISSUE THREAD

**Issue by cdgfx0322** [kabucom/kabusapi#375]
kabu station apiをC#から利用しています。
日経225miniの成り行き注文後、ストップロス注文をしているのですが、パラメータ不正と表示され、注文出来ずに困っています。

色々とパラメータを変更して試していますが、よろしければ、日経225miniの成行注文、ストップロス注文でkabu station apiとのjson情報を開示して頂けないでしょうか？

個別のサンプルは有るのですが、買い注文のポジション情報と、返済注文のポジション情報が異なったサンプルのため、返済建玉IDに指定するべきIDは、どのデータを使うのか？、返済注文のSideは、建玉の逆で良いのか？などについて参考にさせていただきたいと思っています。

過去ログとサンプルで確認できた部分が有りますので、返済建玉IDは、残高照会で得られるExecutionID、返済注文のSideは、建玉の逆としています。

FrontOrderTypeを30（逆指値）としたとき、Priceに指定する数値の記述がリファレンスに載っていません。

TriggerPriceや、ポジションの建値などで試してみましたが、どれも同じく「パラメータ不正　－　ReverseLimitOrder」と表示され、詳細はkabuSログファイルを参照してください。と書かれていますが、送受信したパラメータのJSONデータが載っているだけで、どの値が原因でエラーとなっているのか見当がつきません。

保有ポジションは、日経225mini を27335でBUYしています。

ストップロス注文をした時の、kabuSログ内容です。
【SendOrderFuture】(
{"Password":"****************",
"Symbol":"166090019",
"Exchange":23,
"TradeType":2,
"TimeInForce":2,
"Side":"1",
"Qty":1,
"ClosePositionOrder":null,
"ClosePositions":[{"HoldID":"E20210823*****","Qty":1}],
"FrontOrderType":30,
"Price":27135,
"ExpireDay":0,
"ReversLimitOrder":{"TriggerPrice":27135,"UnderOver":1,"AfterHitOrderType":1,"AfterHitPrice":0}}
)

どこか相談できる窓口が有れば、教えていただければ、そちらに問い合わせたいと思います。

よろしくお願いします。

**Comment by yasuyuki-nakazawa** [comment]
こちら、確認してみます

**Comment by cyber-minion** [comment]
返済建玉指定のパラメータは、ClosePositionOrderとClosePositionsはどちらか一方のみ指定可能ですので、
ExecutionIDにて指定したい場合は、「"ClosePositionOrder":null,」を削除し、再度お試しいただけますでしょうか。

**Comment by cdgfx0322** [comment]
返信をありがとうございます。

> 返済建玉指定のパラメータは、ClosePositionOrderとClosePositionsはどちらか一方のみ指定可能ですので、
> ExecutionIDにて指定したい場合は、「"ClosePositionOrder":null,」を削除し、再度お試しいただけますでしょうか。

"ClosePositionOrder":nullを削除して試してみます。

**Comment by cdgfx0322** [comment]
"ClosePositionOrder":nullを削除した状態で試してみましたが、結果は同じ症状でした。

保有ポジションは、日経225mini をBUYしています。

【SendOrderFuture】(
{
"Password":"****************",
"Symbol":"166090019",
"Exchange":23,
"TradeType":2,
"TimeInForce":2,
"Side":"1",
"Qty":1,
"ClosePositions":[{"HoldID":"E20210825****","Qty":1}],
"FrontOrderType":30,
"Price":27720,
"ExpireDay":0,
"ReversLimitOrder":{"TriggerPrice":27520,"UnderOver":1,"AfterHitOrderType":1,"AfterHitPrice":0}
}
)
【SendOrderFuture】({"Code":4002023,"Message":"パラメータ不正：ReverseLimitOrder - 詳細はkabuSログファイルを確認してください"})

ちなみに、ClosePositionsを指定して、"ClosePositionOrder":nullを付けていても、成行決済は正常に処理されています。

対象法が分かりましたら、よろしくお願いします。m(__)m

**Comment by Atari7** [comment]
リファレンスではReverseLimitOrderの「TriggerSec」という設定値がrequiredになっていますが、実際のオーダーでは指定されていないように見えますね。間違ってたらごめんなさい。

**Comment by Atari7** [comment]
すみません。「現物・先物」の方を見てました。。

**Comment by cdgfx0322** [comment]
反応、ありがとうございます。
実は・・・TriggerSecも追加して試しました。

でも、ダメだったんです。

**Comment by cyber-minion** [comment]
スペルが間違っているようですが、下記の通りご修正のうえ、再度お試しいただけますでしょうか

誤：ReversLimitOrder
正：ReverseLimitOrder

**Comment by cdgfx0322** [comment]
あら・・・ホントですね。恥ずかしい(x_x)
修正してテストしてみます。

**Comment by cdgfx0322** [comment]
ReverseLimitOrderが、どのポジションについての返済となっているか？については、自分のプログラムで管理するしか無いのでしょうか？

手動で決済する時など、成行決済前にオーダーをキャンセルしたいと思ってます。

APIからの情報で、紐付けられたポジションとオーダーが分かる方法が有れば、教えて頂けますでしょうか？

よろしくお願いします。

**Comment by yasuyuki-nakazawa** [comment]
どのポジションと紐づいているかはご自身のプログラムで管理いただく必要があります
ちなみにですが、期待する機能、結果はどのようなものであるかを教示いただけると幸甚です

**Comment by cdgfx0322** [comment]
返信をありがとうございます。
前提として、ポジション保有後、逆指値注文で損切りを予約している状態とします。
複数のポジションが有って、それぞれのPriceをベースに逆指値を持っている場合で、一つのポジションを成り行きで決済したい場合に、該当する予約注文だけをキャンセルして、成り行き決済注文を入れようと考えています。

具体的イメージとしては、OrderのDetail情報の中で、返済の対象となるポジションのExecutionIDが入っていれば、ポジション情報からオーダーIDが分かります。
APIの仕様上、返済対象のポジションが複数、存在するケースも有るので、難しいと思いますが。
今後のバージョンアップ時に検討いただけると幸いです。

現状、紐づいているオーダーは、自分のプログラムで管理する必要が有る件については、了解しましたので、この質問は閉じたいと思います。

よろしくお願いします。

**Comment by shujiji** [comment]
> Priceに指定する数値の記述がリファレンスに載っていません

FAQという意味でも、逆指値で指定するパラメータは、下記にて相違ないかご確認いただけますでしょうか。

以下、例として、1,000円で買った注文に「990円以下になったら980円の指値で売り」という逆指値を出すと仮定します。

"Side":　Positionsにおける"Side"と逆。この例では売りの逆指値なので"1"
"Qty":　当注文で発注する総量（補足："ClosePositions"で複数ID分注文する場合、それらの"Qty"の合計値）
"ClosePositions":　[{"HoldID":"EYYYYMMDD~", "Qty": int型の数量}]
"Price":　逆指値を発注するPositionの"Price"(=約定値)。この例ではfloatで1000.0
"ReversLimitOrder":
　{"TriggerPrice":　逆指値のトリガー値段。この例ではfloatで990.0
　"UnderOver":　この例では「990円以下ならば」なので1
　"AfterHitOrderType":　この例では指値なので2
　"AfterHitPrice":　"AfterHitOrderType"が2ならば希望額、1ならば0。この例ではfloatで980.0
　}

**Comment by cyber-minion** [comment]
> "Price":　逆指値の場合は0を指定(??)

逆指値の場合、Priceは指定なしでお願いいたします。
また、この場合はPriceの値は無視されていますので、指定しても発注されます。

リファレンスのほうは補完しておきます。混乱させてしまい、申し訳ございません。

**Comment by shujiji** [comment]
> 逆指値の場合、Priceは指定なしでお願いいたします。 また、この場合はPriceの値は無視されていますので、指定しても発注されます。

逆指値の場合”Price"は記述しなくて良い（"Price"=0ではなく、コメントアウトして良い）ものと理解しました。もし違っていた場合のみご訂正をお願い致します。
ご回答を有難うございました。
