### ISSUE TITLE
【質問】いつもお世話になっております。検証用APIだと、数値やアクションを要求してもブランクで帰ってきますので、プログラムを試験的に運用することができません。何のための検証用APIなのでしょうか?みなさまはどういうふうに対応なさっておられるのでしょうか?

### ISSUE THREAD

**Issue by fwarit** [kabucom/kabusapi#377]

**Comment by tsuchinaga** [comment]
何かを試す場合は、1単元1株の1000~2000円くらいのETF現物株に対して実際に注文を入れて試しています

検証用APIに特定の動作を期待しているのであれば要望を出されてはどうですか？

**Comment by hajime-f** [comment]
私は実データを使ったシミュレータを用いて、バックテストを行ってます。

**Comment by fwarit** [comment]
tsuchinaga さん、コメント頂戴しておりまして誠にありがとうございます。
仰せの通りですね! 当面は安価なものを使用して、本番環境でテストすればよいですね!
私は日経225を走らせようとしていますので、225Miniで代用するか、動きが似たもっと安価なものを見繕ってみたいと思います。

**Comment by fwarit** [comment]
hajime-f さん、コメントをいただきありがとうございました。
私もダウンロードした実dataを用いて、バックテストを行っております。飽くまでバックテストとなりますので、実運用で検証したいという意図なんです。

**Comment by fwarit** [comment]
【質問・続き】
FXでよくあるような、お金のやり取りが発生しないだけのシミュレーションが出来ることを求めています。一番実践的に検証出来ます由…　そのようなことは可能でしょうか？

**Comment by tsuchinaga** [comment]
FXは取引所なので、約定の機能がFX業者の内側にあると思いますが、  
株や先物は東証なり大証なりの内側に約定の機能があるので、kabuステーションで実現するのは一筋縄ではいかないと思います。

また、kabuステーションAPIは、kabuステーションを他のアプリケーションから操作するためのインターフェースを提供しているというのも難しさの要因だと思います。

ただし趣旨からずれますが、板情報があればある程度似た動きを再現することはできるので、kabusapiを使えば自前で用意することは可能です

**Comment by hajime-f** [comment]
@tsuchinaga 
> 1単元1株の1000~2000円くらいのETF現物株に対して実際に注文を入れて試しています
具体的にどの銘柄で試しているのか、教えていただけませんでしょうか。

**Comment by tsuchinaga** [comment]
1475 を使うことが多いです  
ちがう価格の動きを見たいときは、 1476 も使います

カブコムでは[フリーETF](https://kabu.com/item/free_etf/meigara/default.html)対象になっているので、現物であれば手数料などのコストがなくテストしやすいです

**Comment by hajime-f** [comment]
なるほど、手数料も大事ですね。ありがとうございます。
試行錯誤しながらやってみます。

**Comment by yasuyuki-nakazawa** [comment]
こちらは、クローズさせていただきます
