### ISSUE TITLE
【要望】残高照会の決済済みポジションについて

### ISSUE THREAD

**Issue by cdgfx0322** [kabucom/kabusapi#378]
C#でkabu station apiを利用しています。

成行注文、成行決済のテストをしていまして、決済後に残高照会（/kabusapi/positions）で受け取る情報に、決済済みのポジションが含まれていました。

決済後、kabu stationの残高照会Windowからポジションが消えた後には、APIで受け取る残高照会にも含まれない様にして貰えないでしょうか？

無いはずのポジションが返されるのは、ちょっと焦ります。

よろしくお願いします。

**Comment by hishiharahaz** [comment]
@cdgfx0322 さん
私はこちらを参考にしてLeavesQty=0は決済済みとして判断しています。
https://github.com/kabucom/kabusapi/issues/124#issuecomment-706896386

**Comment by cdgfx0322** [comment]
> @cdgfx0322 さん
> 私はこちらを参考にしてLeavesQty=0は決済済みとして判断しています。
> [#124 (comment)](https://github.com/kabucom/kabusapi/issues/124#issuecomment-706896386)
返信をありがとうございます。
なるほど...LeavesQtyを使うのですね。

それで解決出来そうなので、この要望は閉じようと思います。
