### ISSUE TITLE
【質問】kabuステーションの強制ログアウトの挙動について

### ISSUE THREAD

**Issue by tsuchinaga** [kabucom/kabusapi#38]
kabuステーション自体の質問になって申し訳ないのですが、強制ログアウトの挙動について教えてください。

昨晩からkabuステーションと時価情報WebSocketをつなぎっぱなしにして8時台を迎えたところ、  
kabuステーションもtokenも生きたままで時価情報が渡されてきました。

強制ログアウトは何をトリガーに発動されますでしょうか？

**Comment by yasuyuki-nakazawa** [comment]
強制ログアウトの時間帯ですが、5時～6時の間に実施されます。
ログアウトは当該タイミングで実施されますが、WebSocketが切断されることはございません。
銘柄のリクエストについては過去のトークンで行われたもので時価情報が配信されているため、時価情報取得（Push)に関しては情報を現状受け取ることができております。
但し、リクエスト銘柄の登録、削除等TOKENを利用するリクエストに関してはTOKENが無効化されているため、再度の認証の上、リクエストが必要となります

**Comment by tsuchinaga** [comment]
ご回答ありがとうございます

5時～6時の強制ログアウトでトークン自体は無効にされているがWebSocketは切断されないこと承知しました。

**Comment by spotthediff** [comment]
@yasuyuki-nakazawa ログアウト後にREST APIを使用する場合、再度ログインが必要になるのでしょうか?
それとも、ログアウト状態であってもkabu stationが起動さえしていれば再度tokenを取得できて、その新トークンを利用すれば、REST APIを使用できるのでしょうか?
