### ISSUE TITLE
【質問】過去分の期近先物価格の取得について

### ISSUE THREAD

**Issue by peichan0823** [kabucom/kabusapi#380]
方法がありましたらご教授頂けると助かります。

時価情報・板情報は、python kabusapi_board.py により取得出来ますが、
日々の日中と夜間別に、各取引終了時の情報を"遡って”取得したいです。
板情報は、なくてもかまいません。

**Comment by yasuyuki-nakazawa** [comment]
現状は、過去分の情報を取得することができません。
現在、四本値情報を（過去分含めて）取得することは検討しております。

**Comment by yasuyuki-nakazawa** [comment]
こちらはクローズさせていただきます
