### ISSUE TITLE
【質問】現物の成行買いに対する約定の成否を知る方法について

### ISSUE THREAD

**Issue by hajime-f** [kabucom/kabusapi#383]
現物の成行買いを発注した後、
- その注文が約定したか？
- いくらで約定したか？

を知るには、どうすればよいでしょうか？

kabusapi_orders.py のサンプルプログラム（注文約定照会）を見ているのですが、よくわからずに困っております。
https://github.com/kabucom/kabusapi/blob/master/sample/Python/kabusapi_orders.py

例えば、注文番号が 20201207A02N04830518 の注文が約定しているかどうかについては、

```
url = 'http://localhost:18080/kabusapi/orders'
params = { 'product': 1 }               # product - 0:すべて、1:現物、2:信用、3:先物、4:OP
params['id'] = '20201207A02N04830518'   # id='xxxxxxxxxxxxxxxxxxxx'

req = urllib.request.Request('{}?{}'.format(url, urllib.parse.urlencode(params)), method='GET')
...
```

として GET リクエストを投げると思うのですが（たぶん）

(1) 約定していた場合は、API リファレンス記載の JSON が返ってくるという理解で正しいでしょうか？
(2) 約定していなかった場合は、何が返ってくるのでしょうか？
(3) いくらで約定したかは、返ってきた JSON の「Price」を参照すればよいのでしょうか？
(4)「注文番号」は、注文発注（sendorder）した後に返ってきた OrderId と同じものでしょうか？
(5) ```params = { 'product': 1 }``` とした場合、他のパラメータはすべて設定しなければならないのでしょうか？

いつもどおり初歩的な質問で恐縮ですが、よろしくお願いいたします。

**Comment by hishiharahaz** [comment]
@hajime-f 
下記、私はこのように使っています。ということでの回答となります。
>(1) 約定していた場合は、API リファレンス記載の JSON が返ってくるという理解で正しいでしょうか？
>(2) 約定していなかった場合は、何が返ってくるのでしょうか？
約定していても、いなくてもJSONが返ってきます。

>(3) いくらで約定したかは、返ってきた JSON の「Price」を参照すればよいのでしょうか？
RecType=8(約定)をひろって、Priceの値を参照しています。

>(4)「注文番号」は、注文発注（sendorder）した後に返ってきた OrderId と同じものでしょうか？
OrderIdと同じっぽいです。

>(5) params = { 'product': 1 } とした場合、他のパラメータはすべて設定しなければならないのでしょうか？
任意のパラメータだけ指定しています。

**Comment by hajime-f** [comment]
ありがとうございます。
本番環境ではなかなか気軽に試せないので、ぐずぐず考えていたところでした。

他の方がどうなさっているかも気になりますね。。

**Comment by yasuyuki-nakazawa** [comment]
@hajime-f 
@hishiharahaz 氏が回答いただいているやり方が主な方法だと思われます
注文約定情報を取得して、Rectypeで約定データを確認して処理する方法です

**Comment by hajime-f** [comment]
@yasuyuki-nakazawa 
ありがとうございます。

いまよく見たら、
https://kabucom.github.io/kabusapi/reference/index.html#operation/ordersGet
このドキュメントの「Response 200 OK」の「details」をさらにプルダウンして開いたら、内容の詳細が全部載ってますね。。
（気づきませんでした。すみません）

全部解決しました。ありがとうございました。
