### ISSUE TITLE
【質問】リアルタイム株価予測の実装について

### ISSUE THREAD

**Issue by YOHSIKI** [kabucom/kabusapi#385]
リアルタイム株価予測のAPI実装はどのような状況でしょうか。
以下のプレスリリースでは5月実装予定となっております。

https://kabu.com/sp/company/pressrelease/20210122_1.html

**Comment by yasuyuki-nakazawa** [comment]
お待たせしており、申し訳ございません。
諸プロジェクトの関係上、優先度を変更して対応させていただいております。
具体的な日程が確定次第、これまで通り、お知らせという形で公開させていただきます

**Comment by hirocha** [comment]
リアルタイム株価予測は日本に存在する一般個人向け証券会社ツールの中で最強機能と個人的に思っています。
これがあるからカブコムさんを使っていると言う人はたくさんいることでしょう。
ぜひ実装お願いします。
有料でも全然構いません。
