### ISSUE TITLE
【質問】逆指値注文による数量拘束について

### ISSUE THREAD

**Issue by zmp365** [kabucom/kabusapi#387]
#386 の質問の後、新たな問題に気づきました。

1357（Dインバ）で動作検証しているのですが、

①新規成り買い１枚　→　②返済売り（逆指値指定）１枚　→　③返済売り（指値指定）１枚　と実行すると、
　③でコード８エラーになります。

①新規成り買い２枚　→　②返済売り（逆指値指定）１枚　→　③返済売り（指値指定）１枚　と実行すると、
　エラーは出ません。

どうやら、逆指値注文を出すと、その枚数分は拘束されてしまい、その分は指値注文出来なくなる仕様のようです。
（順番が逆でも同じです。　指値注文を出すと、その枚数分は拘束されていまい、その分は逆指値注文出来ません。）

逆指値は条件に合致するまでは注文発生しないので、拘束枚数としてカウントしてしまうのは仕様的におかしいような気がするのですが、私の勘違いでしょうか？

**Comment by yasuyuki-nakazawa** [comment]
逆指値にかかわらず、残高管理の関係上、各種注文が行われた時点でポジションの拘束がおこなわれます。
これは、同一ポジションで異なる複数の返済注文が行われるのを避けるためです。
拘束が行われないと、他注文で該当するポジションの返済が実施されてしまうためです。
こちらはしようとなりますので、ご了承くださいませ

**Comment by zmp365** [comment]
ご回答有難うございます。　そうなりますと、現状、新規買い建て玉に対し、売り返済と逆指値を同時に出したい場合、W指値機能のリリースを待つという事になるでしょうか？

W指値の要望は既に本コミュニティーでも出ているようですが、優先順位を上げていただけると大変有難いです。　（その上で、指値も逆指値も任意に後から変更出来ると、更に有難いです。）

**Comment by yasuyuki-nakazawa** [comment]
要望、認識致しました
現在の改善計画を確認いたします

**Comment by zmp365** [comment]
宜しくお願い致します。　本件、いったんクローズとさせていただきます。
