### ISSUE TITLE
【要望】OpenAPI Specification Version 3 への対応 → 【対応済：2021/01/28】

### ISSUE THREAD

**Issue by supermomonga** [kabucom/kabusapi#39]
現状 [kabu_STATION_API.yaml](https://github.com/kabucom/kabusapi/blob/master/reference/kabu_STATION_API.yaml) は OpenAPI Specification Version 2（Swagger）にて記載されているかと思います。

こちらについて、OpenAPI Version 3 のものも別途同梱されていると周辺ツールの活用の幅が広がって嬉しいです。

**Comment by yasuyuki-nakazawa** [comment]
OpenAPI Version 3 にかんしては、内部で試行させていただいた上、検討させていただきます

**Comment by yasuyuki-nakazawa** [comment]
こちら、1/28 に対応実施させていただきました

**Comment by supermomonga** [comment]
ありがとうございます。
