### ISSUE TITLE
【質問】日経225miniの銘柄登録に失敗する件について

### ISSUE THREAD

**Issue by cdgfx0322** [kabucom/kabusapi#390]
本日、日経225miniを/kabusapi/registerで登録しようとしましたが、登録に失敗しました。

昨日まで、先物銘柄コード取得で帰ってきていたのが、日経225mini 21/09だったのですが、本日から日経225mini 21/10になったので、新しいSymbolで登録しようとしましたが、/kabusapi/board/166100019でも銘柄が見つからないというエラーとなります。
/kabusapi/registerで登録しようとしても、銘柄が登録できませんでしたというエラーが返ってきます。

先月も、同じような状態になったのですが、次の日には新しいSymbolで正常に処理出来ていました。

この原因と対策を教えていただければ幸いです。

**Comment by hishiharahaz** [comment]
@cdgfx0322 さん
ためしに同じ銘柄で/kabusapi/registerを実行したら登録することができました。
APIログを見ると登録できなかった原因が書かれているかもしれません。
【APIログ】
`02:11:13.3183,I,15076,0014 【Regist】({"Symbols":[{"Symbol":"166100019","Exchange":"2"}]})
02:11:13.4204,I,15076,0014 【Regist】({"RegistList":[{"Symbol":"166100019","Exchange":2}]})
02:11:18.7983,I,15076,0014 【Regist】({"Symbols":[{"Symbol":"166100019","Exchange":"23"}]})
02:11:18.8049,I,15076,0014 【Regist】({"RegistList":[{"Symbol":"166100019","Exchange":2},{"Symbol":"166100019","Exchange":23}]})
02:11:22.8024,I,15076,0014 【Regist】({"Symbols":[{"Symbol":"166100019","Exchange":"24"}]})
02:11:22.8035,I,15076,0014 【Regist】({"RegistList":[{"Symbol":"166100019","Exchange":2},{"Symbol":"166100019","Exchange":23},{"Symbol":"166100019","Exchange":24}]})
`

**Comment by cdgfx0322** [comment]
@hishiharahaz  さん
反応、ありがとうございます。

日付が変わると、成功するんです。・・・実際、同じコードで今は銘柄登録に成功しています。

失敗した日付9/10のログだと、こんな感じです。
09:00:21.7239,I,6800,0009 【SymbolNameFuture】(futureCode=NK225mini, derivMonth=0)
09:00:21.7395,I,6800,0009 【SymbolNameFuture】({"Symbol":"166100019","SymbolName":"日経225mini 21/10"})
09:00:21.7395,I,6800,0009 【Board】(166090019@23)
09:00:21.7552,I,6800,0009 【Board】({"Code":4002001,"Message":"銘柄が見つからない"})
09:00:24.8784,I,6800,0009 【Regist】({"Symbols":[{"Symbol":"166090019","Exchange":23}]})
09:00:24.9188,I,6800,0009 【Regist】({"Code":4001018,"Message":"銘柄が登録できませんでした"})

今日の日付9/11のログです。
12:42:59.8459,I,5248,0011 【SymbolNameFuture】(futureCode=NK225mini, derivMonth=0)
12:42:59.8459,I,5248,0011 【SymbolNameFuture】({"Symbol":"166100019","SymbolName":"日経225mini 21/10"})
12:42:59.8615,I,5248,0011 【Board】(166100019@23)
12:43:00.7990,I,5248,0011 【Board】({"ClearingPrice":30165.0000,"Exchange":23,"ExchangeName":"大阪日中","TradingVolume":33750.0,"TradingVolumeTime":"2021-09-10T15:15:01+09:00",....
12:43:00.8147,I,5248,0011 【Regist】({"Symbols":[{"Symbol":"166100019","Exchange":23}]})
12:43:00.8459,I,5248,0011 【Regist】({"RegistList":[{"Symbol":"166100019","Exchange":23}]})

勝手な推定ですが、日経225miniの前日まで使えてた 日経225mini 21/09が使えなくなった日は、日経225mini 21/10が返ってくるのですが、使い始められるのが、その次の日になってる？という感じに見えます。

なので、新しいSymbolに切り替わった日の取引がAPIから出来ないので困っています。

このエラーを回避できる方法は無いのでしょうか？

**Comment by tsuchinaga** [comment]
ログを見た限りだと、9/10の Board と Regist の銘柄コードが 166090019 になっているようです

**Comment by cdgfx0322** [comment]
あ！・・・なるほどです。
取得した新しいSymbol名を表示させている部分には更新していたのですが、他のパラメータに反映するタイミングが遅かったのが原因でした。

表示内容が変わっていたので、新しいSymbolを使っているハズと思い込んでいました・・・反省です。

おかげさまで、原因が判明して修正が出来ました・・・助かりました。m(__)m

解決しましたので、クローズしたいと思います。
