### ISSUE TITLE
【不具合】認証更新時例外エラー発生でログアウト？（要望付き）

### ISSUE THREAD

**Issue by ob2r** [kabucom/kabusapi#391]
■[必須] 不具合事象
　　　　エラー発生して強制的に切断されログアウトさせられた？。
　　　　その時、PUSH配信は一時停止したのち再開しました。
　　　　その後、発注APIを利用すると　**【SendOrder】({"Code":4001007,"Message":"ログイン認証エラー"})**
　　　　と表示して発注できません。
             　　　 （kabuステは朝の7時に起動して、15時半に終了しています。）

■[必須] 本来想定されるアクションと事象
　　　　エラーが発生しない。
　　　　**要望（切断が起きてログアウトしまった時のために再ログインできるようにするAPIの提供）**

■[必須] 不備発生時刻
　　　　21/09/13 09:10:31.0687　（20/09/14~21/09/13の間で二回発生）

■[任意] お使いの環境
　　　　・Windows 10 Home プロセッサ　Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz   1.61 GHz　実装RAM 64.0 GB
　　　　・Python 3.9.2 64bit

■[任意] 不備部分のログ
09:06:49.4880,I,47924,0074 KeepSession at 2021/09/13 09:06:49
09:08:16.6716,I,47924,0001 NewsHeaders: count=5927
09:10:02.1901,I,47924,0064 UpdateService.UpdateCheck : start
09:10:31.0687,E,47924,0067 認証更新時例外エラー発生。Account=********
System.ServiceModel.CommunicationException: 接続が切断されました: 維持される必要があった接続が、サーバーによって切断されました。 ---> System.Net.WebException: 接続が切断されました: 維持される必要があった接続が、サーバーによって切断されました。 ---> System.IO.IOException: 転送接続からデータを読み取れません: 接続済みの呼び出し先が一定の時間を過ぎても正しく応答しなかったため、接続できませんでした。または接続済みのホストが応答しなかったため、確立された接続は失敗しました。。 ---> System.Net.Sockets.SocketException: 接続済みの呼び出し先が一定の時間を過ぎても正しく応答しなかったため、接続できませんでした。または接続済みのホストが応答しなかったため、確立された接続は失敗しました。
   場所 System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- 内部例外スタック トレースの終わり ---
   場所 System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   場所 System.Net.FixedSizeReader.ReadPacket(Byte[] buffer, Int32 offset, Int32 count)
   場所 System.Net.Security._SslStream.StartFrameHeader(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   場所 System.Net.Security._SslStream.StartReading(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   場所 System.Net.Security._SslStream.ProcessRead(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   場所 System.Net.TlsStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   場所 System.Net.PooledStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   場所 System.Net.Connection.SyncRead(HttpWebRequest request, Boolean userRetrievedStream, Boolean probeRead)
   --- 内部例外スタック トレースの終わり ---
   場所 System.Net.HttpWebRequest.GetResponse()
   場所 System.ServiceModel.Channels.HttpChannelFactory`1.HttpRequestChannel.HttpChannelRequest.WaitForReply(TimeSpan timeout)
   --- 内部例外スタック トレースの終わり ---

Server stack trace: 
   場所 System.ServiceModel.Channels.HttpChannelUtilities.ProcessGetResponseWebException(WebException webException, HttpWebRequest request, HttpAbortReason abortReason)
   場所 System.ServiceModel.Channels.HttpChannelFactory`1.HttpRequestChannel.HttpChannelRequest.WaitForReply(TimeSpan timeout)
   場所 System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
   場所 System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
   場所 System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   場所 System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   場所 System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   場所 System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   場所 System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   場所 TA.KC.IAccountService.KeepSession(AuthenticationHeader Header)
   場所 ao5.d(AuthenticationHeader oHeader)
   場所 ao5.d(Object A_0)
09:10:31.0737,I,47924,0067 認証更新エラー Code=10010
09:10:31.0747,I,47924,0067 カブステAPIクリア
09:10:34.6289,I,47924,0069 失敗：ダウンロード先URL Timeout:http://194.223.146.66/Historical/Ranking/101/Ranking_101_9999.bin
System.Net.WebException: 要求は中止されました: 操作はタイムアウトになりました。
   場所 System.Net.WebClient.OpenRead(Uri address)
   場所 apq.a(String A_0, RequestCacheLevel A_1, a A_2)
09:10:34.6299,I,47924,0054 失敗：ダウンロード先URL Timeout:http://194.223.146.66/Historical/Ranking/201/Ranking_201_9999.bin
System.Net.WebException: 要求は中止されました: 操作はタイムアウトになりました。
   場所 System.Net.WebClient.OpenRead(Uri address)
   場所 apq.a(String A_0, RequestCacheLevel A_1, a A_2)
09:10:39.2807,W,47924,0065 キャッシュ更新チェックに失敗しました。
System.ServiceModel.EndpointNotFoundException: メッセージを受信できる https://web.r10.kabu.co.jp/TA/MasterService.svc/b でリッスンしているエンドポイントがありませんでした。これは一般に、アドレスまたは SOAP アクションが正しくない場合に発生します。詳細については、InnerException を参照してください (ある場合)。 ---> System.Net.WebException: リモート サーバーに接続できません。 ---> System.Net.Sockets.SocketException: 接続済みの呼び出し先が一定の時間を過ぎても正しく応答しなかったため、接続できませんでした。または接続済みのホストが応答しなかったため、確立された接続は失敗しました。 194.223.146.44:443
   場所 System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   場所 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 内部例外スタック トレースの終わり ---
   場所 System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   場所 System.Net.HttpWebRequest.GetRequestStream()
   場所 System.ServiceModel.Channels.HttpOutput.WebRequestHttpOutput.GetOutputStream()
   --- 内部例外スタック トレースの終わり ---

Server stack trace: 
   場所 System.ServiceModel.Channels.HttpOutput.WebRequestHttpOutput.GetOutputStream()
   場所 System.ServiceModel.Channels.HttpOutput.Send(TimeSpan timeout)
   場所 System.ServiceModel.Channels.HttpChannelFactory`1.HttpRequestChannel.HttpChannelRequest.SendRequest(Message message, TimeSpan timeout)
   場所 System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
   場所 System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
   場所 System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   場所 System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   場所 System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   場所 System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   場所 System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   場所 TA.KC.IMasterService.GetCacheTime(AuthenticationHeader Header)
   場所 apx.c(Object A_0)
09:10:55.6919,I,47924,0054 失敗：ダウンロード先URL ConnectFailure:http://194.223.146.66/Historical/Ranking/201/Ranking_201_9999.bin
System.Net.WebException: リモート サーバーに接続できません。 ---> System.Net.Sockets.SocketException: 接続済みの呼び出し先が一定の時間を過ぎても正しく応答しなかったため、接続できませんでした。または接続済みのホストが応答しなかったため、確立された接続は失敗しました。 194.223.146.66:80
   場所 System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   場所 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 内部例外スタック トレースの終わり ---
   場所 System.Net.WebClient.OpenRead(Uri address)
   場所 apq.a(String A_0, RequestCacheLevel A_1, a A_2)
09:10:55.6919,I,47924,0069 失敗：ダウンロード先URL ConnectFailure:http://194.223.146.66/Historical/Ranking/101/Ranking_101_9999.bin
System.Net.WebException: リモート サーバーに接続できません。 ---> System.Net.Sockets.SocketException: 接続済みの呼び出し先が一定の時間を過ぎても正しく応答しなかったため、接続できませんでした。または接続済みのホストが応答しなかったため、確立された接続は失敗しました。 194.223.146.66:80
   場所 System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   場所 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 内部例外スタック トレースの終わり ---
   場所 System.Net.WebClient.OpenRead(Uri address)
   場所 apq.a(String A_0, RequestCacheLevel A_1, a A_2)

**Comment by yasuyuki-nakazawa** [comment]
時価情報の取得に関しては、カブステーション自体がセッションの切断を検知した際に再接続を行っております。
しかしながら、ログインの状況に関しては、自動的にログインを行うことを諸セキュリティの観点で実施しておりません。

なお、当該切断ですが、サーバ側には特段アラート、異常がなく、過去の同事象の際は、以下が原因として挙げられていました。
こちら、ご確認いただけますでしょうか。
・セキュリティソフトによる情報遮断（今回はこのパターンではないと思われます）
・短時間に大きな情報を継続的に取得したことに起因する切断事象
　→　下記のスレッドが参考になると思います 
　 #175  #284
