### ISSUE TITLE
【要望】取引余力として預り金を取得できるようにしてほしい

### ISSUE THREAD

**Issue by tsuchinaga** [kabucom/kabusapi#392]
kabuステーションのリアルタイム資産評価と同等の情報を得たいため、  
預り金の値を取得できるようにしていただきたいです。

ご検討のほどよろしくお願いします。

**Comment by yasuyuki-nakazawa** [comment]
リアルタイム資産評価のインターフェース提供は既に検討されております。
一部、開発は完了しておりますが、諸負荷の兼ね合いから提供を見合わせておる状況です。
こちらの課題が解決次第、ご提供を想定しておる次第です。

**Comment by tsuchinaga** [comment]
ご回答ありがとうございます。

すでに開発が進んでいること、目先の課題として負荷の問題があること承知しました。  
期待しながら待ちます！
