### ISSUE TITLE
【質問】先物の指値価格について

### ISSUE THREAD

**Issue by Love-Trend** [kabucom/kabusapi#395]
APIの仕様で株式のPrice(注文価格)は、number<double>で定義されていますが、先物のPriceはinteger<int32>と表記されてます。
TOPIX先物は1ティック0.5、ミニは0.25で、整数では対応できません。
TOPIX先物の小数点以下の指値の方法はありますか？
また、株式と先物でPriceの型が違うのは理由がありますか？

**Comment by Love-Trend** [comment]
誤：number
正：double
失礼しました。

**Comment by yasuyuki-nakazawa** [comment]
こちら、小数点以下の発注が確認できており、リファレンスの記載誤りと思われます。
大変申し訳ございません。リファレンスの修正を行わせていただきます

**Comment by Love-Trend** [comment]
表記のミスで、サンプルコードでは小数点以下の発注が可能なことを確認しました。
お手数をおかけし、ありがとうございます、クローズします。

**Comment by cyber-minion** [comment]
リファレンスを修正いたしました。ご迷惑をおかけし申し訳ございませんでした。

**Comment by Love-Trend** [comment]
ありがとうございます！！

**Comment by cyber-minion** [comment]
解決済ですので、一旦クローズいたします。
