### ISSUE TITLE
【要望】KABUSTATION同時起動

### ISSUE THREAD

**Issue by kabu3995** [kabucom/kabusapi#396]
楽天とSBIは誰もが複数PCで無限起動でき
岡三は2つまで
松井は大口さんに2つまで取引ツールの起動を許可しています

カブコムで複数起動したいなんて人はAPIをやる人だけだと思いますし、おそらくカブコムが有料で2つ目以降の起動を条件にしたとしても支払える程度の条件になるとは思いますので、有料で検討していただけると幸いです。
現状同時発注をすると1発注当たり0.3秒遅くなってしまうハンデは相当のもので、また、1日当たりの発注数についてはツールの起動数によって変化するものではなく一定のままです。

**Comment by yasuyuki-nakazawa** [comment]
一点教示ください
同時発注すると1注文辺り0.3秒遅くなると言うのはどういうことでしょうか？
複数台を許容したとしても、口座単位の注文処理は順次処理となりますので、流量制限以外では当該レイテンシの削減ははかれないものという認識でおりますゆえ

**Comment by kabu3995** [comment]
同時注文すると順次処理なので2つ目の注文以降遅くなるということです。
ツールが一つであることが問題なのではなく、順次処理が問題なのであり、順次処理でないならツールは一つでも同時高速発注を理論的には可能ということでしょうか

自分は制限が来るほど非常に多数の注文をしたいわけではなく、注文するときに高速に同時に複数の注文をしたいだけなので、流量制限にはそもそも引っかかっていないと思われます。引っかかっていないからこそぜひとも同時発注をしたいのですが。

流量制限があるなら、同時処理を禁じて順次処理にすることもないとは思うのですが。。

**Comment by yasuyuki-nakazawa** [comment]
当件については申し訳ございませんが、同時起動によるご提供（並列処理の許容）を行うことができず、見送りクローズとさせていただきます。
理由としては記載いたしました通り、お客様からの注文は注文順を担保する必要があることから、順次処理を行っております。発注後に余力の計算等も行い、並列化を許容していないことが主な原因となります。

**Comment by kabu3995** [comment]
例えばSBI証券でweb同時発注をした場合、0.2秒でほぼ同時に注文終了の返答が返ってきます
これは順次に余力の把握をするのではなく、リアルタイムに余力が存在して、そこから余力の使用をリクエストされるたびに引いていくのだと推察されます。
現状の余力を確認する必要がそもそもないとは思います。現状の余力は確認せずとも、注文するたびに余力の使用を要求して都度減らしてゆき、足りなくなれば余力不足エラーを出せばいいだけですのでシステムに蛇足を感じます。

理由というのは注文した順番の後の方の注文が通り、先のほうが余力不足になるとまずいからでしょうか？
