### ISSUE TITLE
【不具合】kabuステーションに「システムエラー」のダイアログが表示される

### ISSUE THREAD

**Issue by sakurajane** [kabucom/kabusapi#398]
■[必須] 不具合事象(概要)
kabuステーションの７月５日以降のバージョンから、動作途中に「システムエラー」というダイアログが
表示されることがあります。詳細情報はなく、閉じる（ＯＫ）ボタンが一つあるだけです。

■[必須] 本来想定されるアクションと事象
API使用時のエラーは、APIのレスポンスまたはログに出力される。

■[必須] 不備発生時刻（常時の場合は、常時で記載ください)
最初（７月５日以降）は３日のうち２回程度発生していましたが、kabuステーションの「暗号化ログを出力する」の
チェックを外した後は、１週間に１回程度発生しています。

■[任意] お使いの環境(OS、Excelのバージョン等)、サンプル(Macro、アドインのバージョン）
Windows10

■[任意] 不備部分のログ
参考までに、発生した場合のメッセージと思われるものを３つ送付します。
画面上で発生した時間を正確に記録していたわけではありませんが、発生した日のログのみに必ず出力されている
メッセージがあったたため、問題発生時のメッセージと推測しています。

/wallet/future/{symbol}のAPI使用時に発生しているようです。

####################################################
ログその１
[KabuS_20210915.log]
09:43:20.0089,E,4268,0001 System.NullReferenceException: オブジェクト参照がオブジェクト インスタンスに設定されていません。
   場所 oz.d(AccountWallet A_0)
   場所 oz.c(AccountWallet A_0)
   場所 oz.b(AccountWallet A_0)
   場所 oz.b.c()

[PLAIN_20210915_09.log]
09:43:20.0089,I,4268,0009 【WalletFuture】(166120019@2)
09:43:20.0089,I,4268,0009 【WalletFuture】({"FutureTradeLimit":******.*,"MarginRequirement":135000.0})

####################################################
ログその２
[KabuS_20210915.log]
16:51:38.3527,E,4268,0001 System.Collections.Generic.KeyNotFoundException: 指定されたキーはディレクトリ内に存在しませんでした。
   場所 System.ThrowHelper.ThrowKeyNotFoundException()
   場所 System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   場所 oz.d(AccountWallet A_0)
   場所 oz.c(AccountWallet A_0)
   場所 oz.b(AccountWallet A_0)
   場所 oz.b.c()

[PLAIN_20210915_16.log]
16:51:38.3527,I,4268,0009 【WalletFuture】(166120019@2)
16:51:38.3527,I,4268,0009 【WalletFuture】({"FutureTradeLimit":******.*,"MarginRequirement":135000.0})

####################################################
ログその３
[KabuS_20210922.log]
23:39:46.0429,E,3040,0001 System.Collections.Generic.KeyNotFoundException: 指定されたキーはディレクトリ内に存在しませんでした。
   場所 System.ThrowHelper.ThrowKeyNotFoundException()
   場所 System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   場所 oz.d(AccountWallet A_0)
   場所 oz.c(AccountWallet A_0)
   場所 oz.b(AccountWallet A_0)
   場所 oz.b.c()

[PLAIN_20210922_23.log]
23:39:46.0429,I,3040,0011 【WalletFuture】(166120019@2)
23:39:46.0429,I,3040,0011 【WalletFuture】({"FutureTradeLimit":******.*,"MarginRequirement":135000.0})
####################################################

**Comment by cyber-minion** [comment]
こちらは先物の取引余力APIを実行しましたが、再現できませんでした。
ご利用のkabuステーションは最新版（ver5.15.0.0）ではない場合は、最新版にしていただき、再度お試しいただけますでしょうか。

**Comment by yasuyuki-nakazawa** [comment]
kabuステーションAPIのログではなく、kabuステーション自体のログをご確認いただけますでしょうか？

**Comment by sakurajane** [comment]
> ご利用のkabuステーションは最新版（ver5.15.0.0）ではない場合は、最新版にしていただき、再度お試しいただけますでしょうか。

常に最新版を使用しており、確認したところver5.15.0.0でした。
取引余力APIは、約１秒毎に定期的に実行しています。（１日約１８時間実行）
１週間に１回程度発生しているので、発生頻度は非常に低いと思います。

> kabuステーションAPIのログではなく、kabuステーション自体のログをご確認いただけますでしょうか？

ログの種別が明確になっていないので推測で添付しました。

PLAIN_****  ・・・APIのログ（添付済）
KabuS_****  ・・・Kabuステーション自体のログ？（添付済）
NetLib.Server.****  ・・・ネットワーク関連のログ？（発生時刻付近の情報はありませんでした）

上記以外にログがあるでしょうか。

**Comment by yasuyuki-nakazawa** [comment]
失礼いたしました。記載いただいたログ種で問題ありません。
こちらの方でも確認してみます。
ちなみにですが、ストレージの空き容量等は十分でしょうか。
暗号ログのチェックを外したら、発生頻度が下がったとのことで、ストレージ容量やログの記載処理時のエラー可能性が想定されましたので。

**Comment by sakurajane** [comment]
ストレージ容量の空きは十分あります。（20GB程度）

なお、暗号ログのチェックを付けて動作させたところ早速再現しました。
![kabus1](https://user-images.githubusercontent.com/81540348/135121873-bca79d73-80b9-4d13-832a-df538dbc604b.png)

ログは以下の通りです。（KabuS_20210928.log）
20:17:33.2710,E,1876,0001 System.Collections.Generic.KeyNotFoundException: 指定されたキーはディレクトリ内に存在しませんでした。
   場所 System.ThrowHelper.ThrowKeyNotFoundException()
   場所 System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   場所 oz.d(AccountWallet A_0)
   場所 oz.c(AccountWallet A_0)
   場所 oz.b(AccountWallet A_0)
   場所 oz.b.c()

処理が早くなるような気がしてウィンドウに何も表示させていないのですが、その影響も考えられるでしょうか。

**Comment by cyber-minion** [comment]
エラーになるまでの操作フローを確認させていただきたく、
暗号化ログ出力のチェックを付ける→取引余力（先物）APIを実行、でエラーになってしまう、ということでしょうか。
それ以外の操作（他にAPIを頻繁に実行されることなど）はなかったのでしょうか。

**Comment by sakurajane** [comment]
以下のように、残高照会／取引余力／板情報×２のリクエストを周期的に実行しています。
それぞれの間隔は0.12秒以上空けるようにしており、１秒間に８回程度のリクエスト量になっています。

「ログその１」の場合の履歴。
09:43:19.3371,I,4268,0009 【Positions】(3,,,)
09:43:19.3371,I,4268,0009 【Positions】([])
09:43:19.4621,I,4268,0009 【WalletFuture】(166120019@2)
09:43:19.4621,I,4268,0009 【WalletFuture】({"FutureTradeLimit": ******.*,"MarginRequirement":135000.0})
09:43:19.5871,I,4268,0009 【Board】(101@1)
09:43:19.5871,I,4268,0009 【Board】(省略)
09:43:19.7121,I,4268,0009 【Board】(166120019@2)
09:43:19.7121,I,4268,0009 【Board】(省略)
09:43:19.8839,I,4268,0009 【Positions】(3,,,)
09:43:19.8839,I,4268,0009 【Positions】([])
09:43:20.0089,I,4268,0009 【WalletFuture】(166120019@2)
09:43:20.0089,I,4268,0009 【WalletFuture】({"FutureTradeLimit": ******.*,"MarginRequirement":135000.0})
09:43:20.1496,I,4268,0009 【Board】(101@1)
09:43:20.1496,I,4268,0009 【Board】(省略)
09:43:20.2590,I,4268,0009 【Board】(166120019@2)
09:43:20.2590,I,4268,0009 【Board】(省略)
09:43:20.4308,I,4268,0009 【Positions】(3,,,)
09:43:20.4308,I,4268,0009 【Positions】([])
09:43:20.5714,I,4268,0009 【WalletFuture】(166120019@2)
09:43:20.5714,I,4268,0009 【WalletFuture】({"FutureTradeLimit": ******.*,"MarginRequirement":135000.0})
09:43:20.6808,I,4268,0009 【Board】(101@1)
09:43:20.6808,I,4268,0009 【Board】(省略)
09:43:20.8214,I,4268,0009 【Board】(166120019@2)
09:43:20.8214,I,4268,0009 【Board】(省略)

他に考えられる要因としては、コア数ですかね。（８コア使用しています）
以下のようにCollectionsに不具合または使用上の注意点がある場合、コア数の違いや
機能のオン／オフにより動作タイミングが変わり、問題が出たり出なかったりするかもしれません。
https://docs.microsoft.com/ja-jp/dotnet/standard/collections/thread-safe/

**Comment by cyber-minion** [comment]
7/5あたりで操作を増やしたりしていましたでしょうか

**Comment by sakurajane** [comment]
5月位から今まで処理の変更はしていません。

**Comment by yasuyuki-nakazawa** [comment]
当件ですが、エラー原因の切り分けのためにリクエスト頻度を落としていただいて試行することは可能でしょうか。
サーバからカブステーション側の情報の更新処理と、API経由でのリクエストの際の情報取得で排他関連でエラーが発生している可能性を疑っております。

**Comment by sakurajane** [comment]
夜間帯は変更可能ですので、リクエスト間隔を変えて動かしてみます。（エラーは時間に関係なく発生していました）

■変更前：１秒間に８回程度のリクエスト
14:00:00.8412,I,5780,0006 【Board】(166120019@2)
14:00:01.0130,I,5780,0006 【Positions】(3,,,)
14:00:01.1381,I,5780,0006 【WalletFuture】(166120019@2)
14:00:01.2631,I,5780,0006 【Board】(101@1)
14:00:01.4037,I,5780,0006 【Board】(166120019@2)
14:00:01.5755,I,5780,0006 【Positions】(3,,,)
14:00:01.7006,I,5780,0006 【WalletFuture】(166120019@2)
14:00:01.8256,I,5780,0006 【Board】(101@1)
14:00:01.9506,I,5780,0006 【Board】(166120019@2)
14:00:02.1380,I,5780,0006 【Positions】(3,,,)

■変更後：１秒間に４回程度のリクエスト
18:06:59.4268,I,3124,0008 【Board】(166120019@2)
18:06:59.7550,I,3124,0008 【Positions】(3,,,)
18:07:00.0050,I,3124,0008 【WalletFuture】(166120019@2)
18:07:00.2706,I,3124,0008 【Board】(101@1)
18:07:00.5362,I,3124,0008 【Board】(166120019@2)
18:07:00.8644,I,3124,0008 【Positions】(3,,,)
18:07:01.1144,I,3124,0008 【WalletFuture】(166120019@2)
18:07:01.3956,I,3124,0008 【Board】(101@1)

**Comment by yasuyuki-nakazawa** [comment]
こちら、リクエスト間隔を変更した結果、エラーの発生はいかがでしたでしょうか

**Comment by sakurajane** [comment]
従来、１週間に１度程度発生していましたので、１ヶ月発生しなかったら報告します。
また、発生した場合も報告し、間隔をさらに広げてみたいと思います。

ところで、サーバ／カブステ間の情報更新と、カブステ／クライアント間の情報取得における排他関係が
怪しいかもということですが、つまりWalletFutureだけ連続してリクエストすれば発生頻度が高まるような
ことはないですかね。（問題は必ずWalletFutureのリクエスト時に発生していたため）
「情報の更新処理」「情報取得」に書かれている「情報」とは、取引余力（WalletFuture）のことだと
勝手に思いました。

**Comment by yasuyuki-nakazawa** [comment]
@sakurajane 
情報＝記載のとおり、walletに関してです。
余力情報の取得については、各種排他制御は間引き制御を裏で実施しています。
クライアント的には問題が発生しない状況ですが、APIによる高頻度の問い合わせ下において、発生する可能性があるのではという想定です。
こちらはまだ再現はしておりませんが、継続で情報がありましたらアップデートいたします。

**Comment by yasuyuki-nakazawa** [comment]
@sakurajane 
こちら、間隔を短くして試行いたしましたが、同事象の発生は確認されておりません。
ご利用されているPCの型番、スペック等をご連携いただけると幸甚です
また、カブステーション以外に起動しているアプリ（バックサイド実行含む）があれば、合わせて教示ください

**Comment by sakurajane** [comment]
@yasuyuki-nakazawa
使用しているマシンは、ESXi6.7 U3の仮想マシンです。
・CPUは8コア割り当て（Core i7-4785T）
・メモリは10GB割り当て
・OSはWindows 10 Pro 20H2
・動作しているサービス／プロセスは以下です。
[get-service.txt](https://github.com/kabucom/kabusapi/files/7618984/get-service.txt)
[get-process.txt](https://github.com/kabucom/kabusapi/files/7618985/get-process.txt)
意識して動かしているものは、Kabuステーション、取引用アプリ（KabuTrade）、VNCサーバー、
vmtoolsd（VMware agent）です。

なお、２週間程度（夜間のみ）リクエスト間隔を広げて動作させていますが、問題の発生はありませんでした。
昼間は従来の間隔で動作させていますが、２週間で１回問題の発生がありました。

取引余力のみ連続でリクエストする方式は、数時間試しましたが問題の発生はありませんでした。

**Comment by yasuyuki-nakazawa** [comment]
了解いたしました
ログ頂いたリクエストと同様な処理にて、事象の再現をはかってみます。

**Comment by sakurajane** [comment]
今週Kabuステーションがアップデートされましたが、問題発生状況は特に変更ありませんでした。

10:37:00.9838,E,4356,0001 System.NullReferenceException: オブジェクト参照がオブジェクト インスタンスに設定されていません。
   場所 o0.d(AccountWallet A_0)
   場所 o0.c(AccountWallet A_0)
   場所 o0.b(AccountWallet A_0)
   場所 o0.b.c()

なお、WalletFutureのリクエスト間隔を空けて試して場合は問題発生はありませんでした。（１ヶ月程度、夜間のみ実行）

**Comment by cyber-minion** [comment]
昼間でも間隔を空けて試していただければと思いますが、いかがでしょうか。

**Comment by sakurajane** [comment]
現在のシステムの仕組みとしては、トリガーの価格になった場合に発注直前に取引余力を確認すると
その間に価格変動があるため、価格を調べる直前に先に取引余力を確認するという仕組みになっています。
そのため、頻繁に取引余力を確認するという処理になっています。

そもそも、ぎりぎりの取引余力で運用することは実際はないため、取引余力確認は頻繁に行わず、
万が一取引余力が無い状態で発注してしまった場合はそこでエラー処理をすれば良いわけですが、
先に書いた方式のほうが作りやすかったためそのようになっています。

ダイアログが表示されること以外にデータ送受信などに不具合はないようですので、様子を見つつ
処理の変更なども考えたいと思います。

最初にも書きましたが、エラー発生自体は特に問題視していませんでした。
-----------------------------------------------
■[必須] 本来想定されるアクションと事象
API使用時のエラーは、APIのレスポンスまたはログに出力される。
-----------------------------------------------
エラー発生も考慮してシステムを作成しているため、システムが停止するエラーや頻繁に発生するエラーで
なければ問題はありません。

エラーダイアログがモーダルで表示されるため、Kabuステーションの動作（操作）に支障があるのではと思い
問い合わせを行いました。（OKボタンでダイアログを閉じないと内部処理が停止したままの状態になるなど）

また.Net Frameworkの場合、キャッチされていない例外はダイアログで表示されるという記事を見かけたので、
単純に例外を最終的に全部キャッチしてログに出力すればよいのではと思いました。

**Comment by yasuyuki-nakazawa** [comment]
情報のご連携ありがとうございます。
現状、一旦はログの暗号出力モードをオフのままで運用いただければと存じます

**Comment by sakurajane** [comment]
以前、問題発生環境として「処理が早くなるような気がしてウィンドウに何も表示させていない」と書いたのですが、
試しにウィンドウを表示して動かしてみました。
■以下のような、先物の取引余力を含むウィンドウを表示していた場合は２か月程度一度も問題が発生しませんでした。
![image](https://user-images.githubusercontent.com/81540348/152970326-005e62e5-c1f0-402c-811f-b15d8aa646c3.png)
![image](https://user-images.githubusercontent.com/81540348/152970723-ed29be1b-2fd2-481a-8e28-6c28b901a3d9.png)

■以下のような、先物の取引余力を含まないウィンドウを表示していた場合は以前と同じように問題が発生しました。
![image](https://user-images.githubusercontent.com/81540348/152970995-0eef46d4-bab4-4a11-90df-26e413876f25.png)

以前、「サーバ／カブステ間の情報更新と、カブステ／クライアント間の情報取得における排他関係」が関連しているかも
というコメントがありましたが、ウィンドウ表示との排他関係が関連しているかもしれませんね。

**Comment by cyber-minion** [comment]
解決済みのようですので、クローズさせていただきます。再発しましたらご連絡ください。
