### ISSUE TITLE
【質問】注文パスワードとはどのパスワードなのか?

### ISSUE THREAD

**Issue by spotthediff** [kabucom/kabusapi#399]
Kabu station APIを使って発注するとき(/sendorderにリクエストを送るとき)はRequest bodyに注文パスワードを含めることになっていますが、この注文パスワードというのはどのパスワードのことなのでしょうか?

口座開設時の初期段階(パスワードが初期パスワードだったころ)において、出金パスワードと同じものだったものということでしょうか?

APIパスワードを指定してもエラーになるので、違うパスワードなのかと思っているのですが、上記のような理解で良いでしょうか?

**Comment by tsuchinaga** [comment]
ログイン時に使うパスワードですよー

**Comment by yasuyuki-nakazawa** [comment]
紛らわしくて恐縮ですが、以下の種類がございます
今回でいいますと、②のログイン、取引パスワードがそれとなります
①初期パスワード：口座開設時に書面にて配送されている「ログイン・取引用」のパスワード
②ログイン・取引パスワード
③出金パスワード
④kabuステーションAPIパスワード

**Comment by yasuyuki-nakazawa** [comment]
当件はクローズさせていただきます
