### ISSUE TITLE
【質問】APIトークンのライフサイクルについて

### ISSUE THREAD

**Issue by hori-ryota** [kabucom/kabusapi#4]
APIトークンの取得のライフサイクルはどのような想定でしょうか。

例えば以下のような選択肢があるかと思います。

- 取得したものを保管し、基本的にずっと同じAPIトークンを使用する
- API利用ツールの立ち上げ時に取得、終了時に破棄
- リクエストごとに取得

トークン取得時に有効期限も返っていないため、使い方の想定を教えていただけますと幸いです。

**Comment by yasuyuki-nakazawa** [comment]
まず、有効な本番用トークンは1つです。
当該トークンは下記タイミングでリセットされます。
・kabuステーションが終了した時
・kabuステーションがログアウトした時
・別トークンが発行された時
となっております
kabuステーションは強制的に早朝にログアウトされますので、ご留意下さい

トークンはリクエストの度に発行する必要はありません
一度発行したトークンは有効である限り利用可能です。

**Comment by tsuchinaga** [comment]
基本的には同時に動かせるツールは1つだけってことですよね
