### ISSUE TITLE
Uターン注文【質問】

### ISSUE THREAD

**Issue by mitsu2355** [kabucom/kabusapi#40]
いつも、WEBから、信用取引で指値注文して、「Uターン」注文して、「約定±指値」でUターン注文を出しています。

このAPIで、そのように、「Uターン」注文まで出すことは可能でしょうか？

**Comment by yasuyuki-nakazawa** [comment]
現在提供されているAPIの中ではUターン（「約定±指値」」のような、トリガ付注文は発注できません。

**Comment by mitsu2355** [comment]
Uターン（「約定±指値」」のような、トリガ付注文）が、将来、可能になる予定はありますでしょうか？

**Comment by yasuyuki-nakazawa** [comment]
ご要望に応じて、インターフェースの追加、改善は順次検討実施のうえ、対応させて頂く予定です。

**Comment by mitsu2355** [comment]
今後、この機能が、追加されること、希望いたします。

**Comment by yasuyuki-nakazawa** [comment]
当チケットはCloseとさせていただきます
