### ISSUE TITLE
【質問】指値と逆指値の同時売り注文の方法について

### ISSUE THREAD

**Issue by hajime-f** [kabucom/kabusapi#400]
お世話になります。

例えば、時価が950円の銘柄に対して、
(1) 1000円に値上がりしたら売る（指値注文＝利益確定）
(2)  900円以下に値下がりしたら成行で売る（逆指値注文＝ロスカット）

という注文を出したいとき、次の JSON で１つのリクエストを投げる、という理解で合っているでしょうか？
（実際にやってみたのですが、できている気がしません。。）

```
obj = { 'Password': order_password,
        'Symbol': symbol,       
        'Exchange': exchange,   
        'SecurityType': 1,      
        'Side': '1',            # 売り
        'CashMargin': 1,        # 現物
        'DelivType': 0,         
        'FundType': '  ',       
        'AccountType': 4,       
        'Qty': count,           
        'FrontOrderType': 30,   # 執行条件
        'Price': 1000,          # 指値（1000円）
        'ExpireDay': 0,         
        'ReverseLimitOrder': {
            'TriggerSec': 1,               
            'TriggerPrice': 900,      # 逆指値（900円）
            'UnderOver': 1,           # 以下
            'AfterHitOrderType': 1,   # 成行
            'AfterHitPrice': 0
        }
}
```

毎回初歩的な質問で恐縮ですが、よろしくお願いいたします。

**Comment by tsuchinaga** [comment]
OCOやW指値といった注文方法は提供されていないので、指値と逆指値を両方指定することはできません

**Comment by hajime-f** [comment]
そうなんですね。ありがとうございます。

ということは、上記(1)および(2)にそれぞれ対応する注文のリクエストを２つ投げ、
一方が約定すれば、他方をキャンセルする（OCO）という処理を、自力で実装することになりますね。

**Comment by tsuchinaga** [comment]
仰る通りです

エントリー時は両注文を投げられますが、  
エグジット時は片方の注文を投げた時点でポジションの拘束が行なわれるため、  
価格を監視して注文を投げる必要が発生します。

**Comment by hajime-f** [comment]
@tsuchinaga 
なるほど。。ありがとうございます！

@cyber-minion 
ちなみに、今年５月時点で検討を進めるとなっていたこの機能のリリースですが、
その後にメドなどはついていますでしょうか？ → https://github.com/kabucom/kabusapi/issues/317

自力実装は面倒なので、近日中にリリース予定があるならそれを待ちたいと思います。
よろしくお願いいたします。

**Comment by hajime-f** [comment]
@tsuchinaga 
すみません、この件もう少し教えてください。

> エグジット時は片方の注文を投げた時点でポジションの拘束が行なわれるため、
> 価格を監視して注文を投げる必要が発生します。

この部分なのですが、具体的には、リアルタイムで価格を監視しつつ、

＜1000円に上がった場合＞
(a) 逆指値注文をキャンセルする
(b) 指値注文の執行完了を待つ

＜900円以下に下がった場合＞
(a) 指値注文をキャンセルする
(b) 逆指値注文の執行完了を待つ

という段取りが必要ということでしょうか？

つまり、他方の執行(b)に先立って、一方のキャンセル(a)が必要になる
（言い換えれば、キャンセルしないと執行されない）

、、という理解で合っているでしょうか？

**Comment by tsuchinaga** [comment]
エグジット時にポジションを拘束された時点で他の注文が通らないです。  
エントリー時に余力を拘束されるのと同じ考え方で問題ないと思います。

エントリー時に持ってる余力では1単元分しか購入できないとしたら、  
指値・逆指値両方のエントリー注文を入れることはできません。

エグジット時にも、持っているポジションが1単元分しかないなら、  
指値・逆指値両方のエグジット注文を入れることはできません。

**Comment by hajime-f** [comment]
なるほどです。よくわかりました。
たびたび詳しくありがとうございます！

**Comment by cyber-minion** [comment]
@hajime-f 
お待たせして申し訳ございません。
ご要望を多数いただいているため、優先順位等検討の上、順次対応させていただきたいと考えております。
対応予定が決まり次第、お知らせいたします。

**Comment by hajime-f** [comment]
@cyber-minion 
よろしくお願いいたします。
