### ISSUE TITLE
【質問】発注時のResult=10016について

### ISSUE THREAD

**Issue by macrophyllus** [kabucom/kabusapi#401]
VBプログラムからAPIで株式の注文発注を行っていたのですが2021年10月5日より注文発注が行えなくなってしまいました。
KabuSログのKabuS_20211005.logを確認したところ
OrderManager.Order End  :Result=10016,ID=,ClOrdID=,Detail=,ResultMessage=NULL
となっており、注文が行えてないようでした。
発注に成功していた10月4日のログを確認したところ
OrderManager.Order End  :Result=0,ID=(以下省略)
とあり、実際に注文はできていました。
発注エラーのエラー定義にもResult=10016については記載がないようですのでどういったエラーなのかわかりません。
ご存じの方原因と対策をご教授いただければ幸いです。

**Comment by cyber-minion** [comment]
可能な範囲で注文発注のプログラムを開示いただけますでしょうか

**Comment by macrophyllus** [comment]
カブステのログ(KabuS_20211005.log)として抜粋しますと以下の通りでした。

--------------------------------------------------------------------
23:47:43.9442,I,11168,0005 OrderManager.Order Start:OrderParam: Account=(以下省略)
23:47:44.7880,I,11168,0005 OrderManager.Order End  :Result=10016,ID=,ClOrdID=,Detail=,ResultMessage=NULL
23:47:44.7880,I,11168,0005 発注結果 : Result=10016,ID=,ClOrdID=,Detail=,ResultMessage=NULL
--------------------------------------------------------------------

kabuステーションAPIのログ(PLAIN_20211005_23.log)は以下の通りでした。
--------------------------------------------------------------------
23:44:27.6925,I,11168,0005 【Token】({"APIPassword":"****************"})
23:44:28.1143,I,11168,0005 【Token】({"ResultCode":0,"Token":"****************"})
23:45:49.2977,I,11168,0005 【Positions】(,,,)
23:45:50.0113,I,11168,0005 【Positions】([{"ExecutionID":null,"AccountType":(以下省略)
23:46:35.9363,I,11168,0005 【WalletCash】()
23:46:36.0144,I,11168,0005 【WalletCash】({"StockAccountWallet":9031.0})
23:46:39.6502,I,11168,0005 【Symbol】(1655@1,)
23:46:40.7915,I,11168,0005 【Symbol】({"BisCategory":"9999      ","TotalMarketValue":32615144750.0,"TotalStocks":null,"FiscalYearEndBasic":null,"KCMarginBuy":true,"KCMarginSell":true,"MarginBuy":true,"MarginSell":true,"DisplayName":"ｉＳ米国株/ETF","Exchange":1,"ExchangeName":"東証ETF/ETN","TradingUnit":1.0,"PriceRangeGroup":"10000","UpperLimit":4125.0,"LowerLimit":2725.0,"Symbol":"1655","SymbolName":"ｉシェアーズ　Ｓ＆Ｐ　５００　米国株　ＥＴＦ"})
23:47:43.7767,I,11168,0005 【SendOrder】({"Password":"****************","Symbol":"1655","Exchange":1,"SecurityType":1,"Side":"2","CashMargin":1,"MarginTradeType":null,"DelivType":2,"FundType":"AA","AccountType":4,"Qty":1.0,"ClosePositionOrder":null,"ClosePositions":null,"FrontOrderType":10,"Price":0.0,"ExpireDay":0,"ReverseLimitOrder":null})
23:47:44.7880,I,11168,0005 【SendOrder】({"Code":10016,"Message":"ログイン認証の有効期間が切れました。再ログインしてください。"})
--------------------------------------------------------------------

APIのログを見る限りSendoOrder以外は成功しているようで
文言によると再ログインしろとのことですが、kabuステーションの再起動
発注処理を行うプログラム自体の再起動が行われている10月6日(上記ログの翌日)でも
同様のログが出力されていました。
この「ログイン」とは何を指すのでしょう？ご連絡お待ちしております。

**Comment by cyber-minion** [comment]
REST APIコード一覧に当該エラーを追加しましたので、ご確認いただければと思います。
https://kabucom.github.io/kabusapi/ptal/error.html

**Comment by macrophyllus** [comment]
当該エラーの追加ありがとうございます。
これにてクローズとさせて頂きます。
重ね重ねありがとうございました。
