### ISSUE TITLE
【質問】残高照会API（ポジション照会API）における「LeavesQty」と「HoldQty」の違い

### ISSUE THREAD

**Issue by yasmz** [kabucom/kabusapi#406]
positionsのAPIにて、現在保持しているポジション一覧を照会できるかと思いますが、そのレスポンスの中の「LeavesQty」と「HoldQty」は仕様上どういった違いがあるのでしょうか？

ドキュメントを見ると「LeavesQty」が残数量、「HoldQty」が拘束数量（保有数量）とのことですが、どちらも同じような意味に捉えられることと、実際のレスポンスも同じ値が入っていることしか見たことがないため、異なる値が入りうるパターンがあればご教示いただけますと幸いです。

**Comment by yasuyuki-nakazawa** [comment]
こちら、記載いただいた通りです
リファレンスの記載修正を検討させていただきます
