### ISSUE TITLE
【質問】kabu station api利用中にkabu stationがログアウトされてしまう問題

### ISSUE THREAD

**Issue by shimo33333** [kabucom/kabusapi#407]
現在、kabu station apiを用いたシステムトレードを進めておりますが、一定時間経つとkabu stationが自動的にログアウトされてしまうために、システムトレードがエラーで中断されてしまいます。何らかの方法で、少なくとも、日中の取引時間の間と、夜間の取引時間の間は、自動的にログアウトされてしまうのを防ぐことはできないでしょうか。

**Comment by shimo33333** [comment]
冒頭の質問に関連して、確認したいことがございます。

上記返答の中で言及した以下についてですが、
　＞以下のQ&Aに、3時間画面操作がないと自動ログアウトされるという記載があり、
　＞kabu stationのPCソフトも、それにひっかかっているものと想像していました。
　＞https://faq.kabu.com/s/article/k001726

kabu stationは、上記Q&Aの仕様とは異なり、「3時間画面操作がないと自動ログアウトされる」
という仕様にはなっていない、という認識であっていますでしょうか。


上記仕様ではなかった場合、現時点で考えられる要因としては、以下に絞られると思われます。

-----
　①有線接続ではあるが、何らかの不具合で通信が一定期間遮断されたため、
　　その後セッションが切断され、ログアウトされた。

　②セキュリティソフト（Windows Defender）が何らかの悪さをした。
-----

①の場合、サーバー側は、セッション切断のタイムアウトは何分に設定されていますでしょうか。

**Comment by yasuyuki-nakazawa** [comment]
@shimo33333 
カブステでは一定時間でのログアウトはありません

**Comment by shimo33333** [comment]
ご返答いただき、ありがとうございます。
一定時間でのログアウトがないとのこと、了解致しました。

毎回問題が発生するわけではなく、その後まだ再現していない状態のため、
私の環境下で何らかの通信障害が発生し、セッションが切断されたのが要因と思われます。

以下の質問（タイムアウトの設定）についても、ご回答いただけないでしょうか。

＞上記仕様ではなかった場合、現時点で考えられる要因としては、以下に絞られると思われます。
＞
＞　①有線接続ではあるが、何らかの不具合で通信が一定期間遮断されたため、
＞　　その後セッションが切断され、ログアウトされた。
＞
＞　②セキュリティソフト（Windows Defender）が何らかの悪さをした。
＞
＞→ ①の場合、サーバー側は、セッション切断のタイムアウトは何分に設定されていますでしょうか。

**Comment by yasuyuki-nakazawa** [comment]
セッションのタイムアウトは確認いたします

**Comment by yasuyuki-nakazawa** [comment]
セッションのタイムアウトという表現が適切かとう店はございますが、ログイン状態の確認はおよそ３分の間隔で実施しております

**Comment by shimo33333** [comment]
少なくとも3分間以上ネットが切断されてしまうと、セッションも切れてしまうと、理解致しました。
ご回答いただき、ありがとうございました。

**Comment by kienphan** [comment]
@shimo33333 私は同じ現像が発生しています。APIを利用できるように、毎朝Kabuステーションを再起動しないといけないです。不便ですね。昔どうやって解決できましたか？
ご回答よろしくお願いいたします。
