### ISSUE TITLE
【要望】ワンショットの金額について　→【一部検討中】

### ISSUE THREAD

**Issue by kabucomapi** [kabucom/kabusapi#41]
お世話になります。
発注の安全性確保のため、通常時はワンショット上限の金額を低く設定していますが、時々大きな金額で発注をするときがあり、その時にワンショット上限の金額の変更を忘れる恐れがあります。
自動取引の場合、トリガーが出現して発注した時に設定不良が発覚するので、機会損失の可能性が高いです。さらに、高額設定の時それが発生するため、通常より大きな機会損失となります。
私はエクセルを使用しているため、ワンショット上限の金額を設定するコード、もしくは設定値金額を戻り値とするファンクションを公開していただきたいです。
検討いただけると幸いです。よろしくお願いします。

**Comment by yasuyuki-nakazawa** [comment]
外部からのワンショット上限の変更できるインターフェースということですね。
ご利用意図と使い方は理解いたしました。
ワンショット上限はミスコーディングによる誤発注を防止するという観点で設けさせていることもあり、スクリプト等での変更を許容してしまうと、先述した防止策が十分機能しない可能性もあるため、慎重に検討させていただきます。

**Comment by kabucomapi** [comment]
回答ありがとうございます。回答いただいた意図は十分に承知しております。
上記後半部の「もしくは設定値金額を戻り値とするファンクション」を検討いただけないでしょうか？
VBAからのリクエストに、現在のワンショット上限値を返す関数を公開していただけると、設定ミスによる機会損失の恐れがなくなります。
プログラム始動直後にその値と、発注予定額を比較すれば、問題は解決します。
トークンの未取得等をチェックするコードは、サンプルプログラムにありますので、そのような形で提供していただけると幸いです。
よろしくお願いします。

**Comment by yasuyuki-nakazawa** [comment]
設定金額を戻り値とするインターフェースということですね。
それであれば、対応可能と考えますので、継続検討いたします。

**Comment by yasuyuki-nakazawa** [comment]
当件ですが、外部からワンショット上限の金額の変更を行うということはセキュリティの観点上見送りいたしますが、
要望にも在りましたとおり、設定金額を返すようなインターフェースを追加することで対応する方向で進めております。

**Comment by kabucomapi** [comment]
仕様の変更についてご検討いただきありがとうございます。
金額設定ミスによる機会損失等を防止できるので、大変助かります。

**Comment by yasuyuki-nakazawa** [comment]
当件、検討いたしましたが、利用用途を正確に把握させて頂きたいです。
ワンショット上限の変更はkabuステーションの設定にて変更しなければならない状況で、
設定値をAPIで取得することの意味を改めて確認させて頂ければと。
設定ミスによる機会損失に関して言及されておりますが、
当該APIがあることで、どのタイミングでどのように利用することで、機会損失リスクを削減するのかという点に関して教示いただけると幸甚です

**Comment by kabucomapi** [comment]
お世話になります。
仕様をご検討いただきありがとうございます。

私は、ワンショットの上限値をトレード手法により変更しています。
通常使っている手法は小さなロットで自動発注するため、上限値を低く設定していますが、たまに大きなロットを自動発注する手法を用いるため上限値を再設定する必要があります。しかし、プログラムによる自動発注を繰り返していると、設定変更忘れにより発注エラー（発注額の上限値オーバー）を起こすことがしばしばあります。大きなロットで上記のミスが発生しますので、その際の機会損失は大きなものとなります。
（プログラム実行による自動発注が習慣化してくると、ワンショット上限値についての意識が低下します。）

そこで、APIがワンショット上限値を返してくれば、想定発注額とそれを比較することにより、プログラム実行時にアラートを出せるため、機会損失は防止できます。

以上となります。

**Comment by cyber-minion** [comment]
#305 にてソフトリミットAPIを追加いたしましたので、クローズいたします。
