### ISSUE TITLE
【質問】板情報取得のタイムアウトと情報取得時間短縮について

### ISSUE THREAD

**Issue by ultragenma** [kabucom/kabusapi#416]
【質問1】
pythonサンプルプログラムで板情報を取得すると各銘柄の1度目の取得でほぼ100%タイムアウトします。
kabuステーションのログを確認すると
「BoardData(4374@1)の取得処理に5000msec以上経過しました。」
と出ます。
タイムアウトした場合、1件あたり7秒ほどかかります。
これを改善する方法はありますでしょうか？

【質問2】
同じ銘柄の2回目以降でも銘柄情報、板情報ともに1件あたり2-3秒かかります。
これを高速化する方法はありますでしょうか？

・環境
kabuステーション 5.15.0
python 3.8.10
windows 10 pro
cpu ryzen 3700X
メモリ 16GB
Cドライブ M.2SSD

**Comment by cyber-minion** [comment]
Issueはクローズされましたが、事象は改善されたということでしょうか。

**Comment by ultragenma** [comment]
昨日返信がなかったためクローズしてしまいました。解決はしておりません。お手数ですがご回答お願いします。

**Comment by cyber-minion** [comment]
こちらで検証したところ、タイムアウトが発生することはありませんでしたので、詳細状況を確認させてください。
kabuステーションの銘柄登録リストで、値の点滅が遅かったりしますでしょうか。

**Comment by ultragenma** [comment]
APIは大引け後にデータ取得のために使用しています。
場中は点滅が遅いと思ったことはありません。現在も先物リストは普通にチカチカと動いていますので問題はないかと思います。

**Comment by ultragenma** [comment]
register()での証券コード登録の有無に関わらずタイムアウトが発生します。
上記と違うログですが、例として9265がタイムアウトしたときのログを記載します。

・Kabusのログ
23:59:07.6039,W,14536,0029 BoardData(9265@1)の取得処理に5000msec以上経過しました。

・NetLib.Serverのログ
23:59:00.4395,I,14536,0024 Start b[194.223.146.99:20008] FS@E@9265@T@M_TSE_FS : Q@E@9265@T@M_TSE_Q : TA@E@9265@T@M_TSE_TA : D@E@9265@T@Hd
23:59:00.4395,I,14536,0024 End b[194.223.146.99:20008][True]FS@E@9265@T@M_TSE_FS : Q@E@9265@T@M_TSE_Q : TA@E@9265@T@M_TSE_TA : D@E@9265@T@Hd
23:59:00.4395,I,14536,0024 Start e[194.223.146.99:20008] FS@E@9265@T@M_TSE_FS : Q@E@9265@T@M_TSE_Q : TA@E@9265@T@M_TSE_TA : D@E@9265@T@Hd
23:59:00.4395,I,14536,0024 End e[194.223.146.99:20008][True]FS@E@9265@T@M_TSE_FS : Q@E@9265@T@M_TSE_Q : TA@E@9265@T@M_TSE_TA : D@E@9265@T@Hd

23:59:00.4463,I,14536,0008 Recv RequestResult [DD:194.223.146.99:20008]Size=92:FS@E@9265@T@M_TSE_FS : Q@E@9265@T@M_TSE_Q : TA@E@9265@T@M_TSE_TA : D@E@9265@T@Hd
23:59:00.4522,I,14536,0008 Recv RequestResult [DD:194.223.146.99:20008]Size=92:FS@E@9265@T@M_TSE_FS : Q@E@9265@T@M_TSE_Q : TA@E@9265@T@M_TSE_TA : D@E@9265@T@Hd
23:59:00.4721,I,14536,0023 Recv EndOfGet [DD:194.223.146.99:20008]Size=92:FS@E@9265@T@M_TSE_FS : Q@E@9265@T@M_TSE_Q : TA@E@9265@T@M_TSE_TA : D@E@9265@T@Hd

23:59:01.4487,I,14536,0024 Start c[194.223.146.99:20008] FS@E@9265@T@M_TSE_FS : Q@E@9265@T@M_TSE_Q : TA@E@9265@T@M_TSE_TA : D@E@9265@T@Hd
23:59:01.4487,I,14536,0024 End c[194.223.146.99:20008][True]FS@E@9265@T@M_TSE_FS : Q@E@9265@T@M_TSE_Q : TA@E@9265@T@M_TSE_TA : D@E@9265@T@Hd
23:59:01.4557,I,14536,0056 Recv RequestResult [DD:194.223.146.99:20008]Size=92:FS@E@9265@T@M_TSE_FS : Q@E@9265@T@M_TSE_Q : TA@E@9265@T@M_TSE_TA : D@E@9265@T@Hd

23:59:03.4617,I,14536,0024 Start b[194.223.146.99:20008] FS@E@9265@T@Qn : FS@E@9265@T@QM : FS@E@9265@T@QO : FS@E@9265@T@DPP : FS@E@9265@T@DPS : FS@E@9265@T@DPG : FS@E@9265@T@QOV : FS@E@9265@T@QUV : FS@E@9265@T@ABV : FS@E@9265@T@AAV : TA@E@9265@T@DPG : D@E@9265@T@Hd
23:59:03.4617,I,14536,0024 End b[194.223.146.99:20008][True]FS@E@9265@T@Qn : FS@E@9265@T@QM : FS@E@9265@T@QO : FS@E@9265@T@DPP : FS@E@9265@T@DPS : FS@E@9265@T@DPG : FS@E@9265@T@QOV : FS@E@9265@T@QUV : FS@E@9265@T@ABV : FS@E@9265@T@AAV : TA@E@9265@T@DPG : D@E@9265@T@Hd
23:59:03.4617,I,14536,0024 Start e[194.223.146.99:20008] FS@E@9265@T@Qn : FS@E@9265@T@QM : FS@E@9265@T@QO : FS@E@9265@T@DPP : FS@E@9265@T@DPS : FS@E@9265@T@DPG : FS@E@9265@T@QOV : FS@E@9265@T@QUV : FS@E@9265@T@ABV : FS@E@9265@T@AAV : TA@E@9265@T@DPG : D@E@9265@T@Hd
23:59:03.4617,I,14536,0024 End e[194.223.146.99:20008][True]FS@E@9265@T@Qn : FS@E@9265@T@QM : FS@E@9265@T@QO : FS@E@9265@T@DPP : FS@E@9265@T@DPS : FS@E@9265@T@DPG : FS@E@9265@T@QOV : FS@E@9265@T@QUV : FS@E@9265@T@ABV : FS@E@9265@T@AAV : TA@E@9265@T@DPG : D@E@9265@T@Hd
23:59:03.4617,I,14536,0024 Start b[194.223.146.99:20008] FS@E@9265@T@M_TSE_FS : Q@E@9265@T@M_TSE_Q : TA@E@9265@T@M_TSE_TA : D@E@9265@T@Hd
23:59:03.4617,I,14536,0024 End b[194.223.146.99:20008][True]FS@E@9265@T@M_TSE_FS : Q@E@9265@T@M_TSE_Q : TA@E@9265@T@M_TSE_TA : D@E@9265@T@Hd
23:59:03.4617,I,14536,0024 Start e[194.223.146.99:20008] FS@E@9265@T@M_TSE_FS : Q@E@9265@T@M_TSE_Q : TA@E@9265@T@M_TSE_TA : D@E@9265@T@Hd
23:59:03.4617,I,14536,0024 End e[194.223.146.99:20008][True]FS@E@9265@T@M_TSE_FS : Q@E@9265@T@M_TSE_Q : TA@E@9265@T@M_TSE_TA : D@E@9265@T@Hd

23:59:07.9974,I,14536,0056 Recv RequestResult [DD:194.223.146.99:20008]Size=228:FS@E@9265@T@Qn : FS@E@9265@T@QM : FS@E@9265@T@QO : FS@E@9265@T@DPP : FS@E@9265@T@DPS : FS@E@9265@T@DPG : FS@E@9265@T@QOV : FS@E@9265@T@QUV : FS@E@9265@T@ABV : FS@E@9265@T@AAV : TA@E@9265@T@DPG : D@E@9265@T@Hd
23:59:08.0434,I,14536,0056 Recv RequestResult [DD:194.223.146.99:20008]Size=228:FS@E@9265@T@Qn : FS@E@9265@T@QM : FS@E@9265@T@QO : FS@E@9265@T@DPP : FS@E@9265@T@DPS : FS@E@9265@T@DPG : FS@E@9265@T@QOV : FS@E@9265@T@QUV : FS@E@9265@T@ABV : FS@E@9265@T@AAV : TA@E@9265@T@DPG : D@E@9265@T@Hd
23:59:08.0434,I,14536,0056 Recv RequestResult [DD:194.223.146.99:20008]Size=92:FS@E@9265@T@M_TSE_FS : Q@E@9265@T@M_TSE_Q : TA@E@9265@T@M_TSE_TA : D@E@9265@T@Hd
23:59:08.0434,I,14536,0056 Recv RequestResult [DD:194.223.146.99:20008]Size=92:FS@E@9265@T@M_TSE_FS : Q@E@9265@T@M_TSE_Q : TA@E@9265@T@M_TSE_TA : D@E@9265@T@Hd
23:59:08.0434,I,14536,0023 Recv EndOfGet [DD:194.223.146.99:20008]Size=228:FS@E@9265@T@Qn : FS@E@9265@T@QM : FS@E@9265@T@QO : FS@E@9265@T@DPP : FS@E@9265@T@DPS : FS@E@9265@T@DPG : FS@E@9265@T@QOV : FS@E@9265@T@QUV : FS@E@9265@T@ABV : FS@E@9265@T@AAV : TA@E@9265@T@DPG : D@E@9265@T@Hd
23:59:08.0434,I,14536,0023 Recv EndOfGet [DD:194.223.146.99:20008]Size=92:FS@E@9265@T@M_TSE_FS : Q@E@9265@T@M_TSE_Q : TA@E@9265@T@M_TSE_TA : D@E@9265@T@Hd


・PLAINのログ
23:58:59.6331,I,14536,0029 【Symbol】(9265@1,true)
23:59:00.5471,I,14536,0029 【Symbol】({"BisCategory":"6050      ","TotalMarketValue":5093235000.0,"TotalStocks":2553.0,"FiscalYearEndBasic":20220531,"KCMarginBuy":true,"KCMarginSell":true,"MarginBuy":true,"MarginSell":false,"DisplayName":"ヤマシタＨＤ","Exchange":1,"ExchangeName":"東証１部","TradingUnit":100.0,"PriceRangeGroup":"10000","UpperLimit":2395.0,"LowerLimit":1595.0,"Symbol":"9265","SymbolName":"ヤマシタヘルスケアホールディングス"})

23:59:02.5933,I,14536,0029 【Board】(9265@1)
23:59:07.6039,I,14536,0029 【Board】({"OverSellQty":9800.0,"UnderBuyQty":9900.0,"TotalMarketValue":5093235000.0,"MarketOrderSellQty":0.0,"MarketOrderBuyQty":0.0,"BidTime":"2021-11-09T14:59:48+09:00","AskTime":"2021-11-09T14:59:48+09:00","Exchange":1,"ExchangeName":"東証１部","TradingVolume":1300.0,"TradingVolumeTime":"2021-11-09T15:00:00+09:00","VWAP":2006.8462,"TradingValue":2608900.0,"BidQty":200.0,"BidPrice":2001.0,"BidSign":"0101","Sell1":{"Price":2001.0,"Qty":200.0,"Sign":"0101","Time":"2021-11-09T14:59:48+09:00"},"Sell2":{"Price":2003.0,"Qty":200.0},"Sell3":{"Price":2005.0,"Qty":200.0},"Sell4":{"Price":2006.0,"Qty":100.0},"Sell5":{"Price":2007.0,"Qty":200.0},"Sell6":{"Price":2009.0,"Qty":200.0},"Sell7":{"Price":2011.0,"Qty":200.0},"Sell8":{"Price":2013.0,"Qty":200.0},"Sell9":{"Price":2015.0,"Qty":200.0},"Sell10":{"Price":2017.0,"Qty":200.0},"AskQty":200.0,"AskPrice":1985.0,"AskSign":"0101","Buy1":{"Price":1985.0,"Qty":200.0,"Sign":"0101","Time":"2021-11-09T14:59:48+09:00"},"Buy2":{"Price":1983.0,"Qty":400.0},"Buy3":{"Price":1982.0,"Qty":100.0},"Buy4":{"Price":1981.0,"Qty":600.0},"Buy5":{"Price":1980.0,"Qty":800.0},"Buy6":{"Price":1977.0,"Qty":200.0},"Buy7":{"Price":1971.0,"Qty":200.0},"Buy8":{"Price":1965.0,"Qty":200.0},"Buy9":{"Price":1959.0,"Qty":200.0},"Buy10":{"Price":1954.0,"Qty":200.0},"Symbol":"9265","SymbolName":"ヤマシタヘルスケアホールディングス","CurrentPrice":1995.0,"CurrentPriceTime":"2021-11-09T15:00:00+09:00","CurrentPriceChangeStatus":"0061","CurrentPriceStatus":1,"CalcPrice":1995.0,"PreviousClose":2009.00000,"PreviousCloseTime":"2021-11-08T00:00:00+09:00","ChangePreviousClose":-14.00000,"ChangePreviousClosePer":-0.70,"OpeningPrice":2011.0,"OpeningPriceTime":"2021-11-09T13:55:11+09:00","HighPrice":2011.0,"HighPriceTime":"2021-11-09T13:55:11+09:00","LowPrice":1995.0,"LowPriceTime":"2021-11-09T14:52:06+09:00","SecurityType":1})

**Comment by cyber-minion** [comment]
お手数をおかけし申し訳ございませんが、セキュリティソフトを利用しているのであれば、一旦停止してみて改善されるかをご確認いただけますでしょうか。

**Comment by ultragenma** [comment]
返信ありがとうございます。windows標準のもの以外のセキュリティソフトは使用していません。

**Comment by yasuyuki-nakazawa** [comment]
上記に関しては問題ない認識です
リクエスト部分だけでもソースコードを記載いただけますか？

**Comment by ultragenma** [comment]
銘柄リスト作成→板情報取得→銘柄情報取得→ファイル出力をループで繰り返しています。
ループありなしに関わらず最初の方からタイムアウトは発生しています。よろしくお願いします。

### 板情報関数
```
def get_board_info(code, token, exchange = "1"):
    url = 'http://localhost:18080/kabusapi/board/' + code + '@' + exchange
    req = urllib.request.Request(url, method='GET')
    req.add_header('Content-Type', 'application/json')
    req.add_header('X-API-KEY', token)
    
    try:
        with urllib.request.urlopen(req) as res:
            content = json.loads(res.read())
        return content
    except urllib.error.HTTPError as e:
        content = json.loads(e.read())
        if content["Code"] == 4002001:
            pass
        else:
            print(e)
            print(content)
            return "Exception"
    except Exception as e:
        print(e)
        return "Exception"
```

### 銘柄情報関数
```
def getSymbolInfo(code, token, exchange = "1"):
    params = { 'addinfo': 'true' } # true:追加情報を出力する、false:追加情報を出力しない　※追加情報は、「時価総額」、「発行済み株式数」、「決算期日」、「清算値」を意味します
    url = 'http://localhost:18080/kabusapi/symbol/' + code + '@' + exchange
    req = urllib.request.Request('{}?{}'.format(url, urllib.parse.urlencode(params)), method='GET')
    req.add_header('Content-Type', 'application/json')
    req.add_header('X-API-KEY', token)
    
    try:
        with urllib.request.urlopen(req) as res:
            content = json.loads(res.read())
        return content
    except urllib.error.HTTPError as e:
        content = json.loads(e.read())
        if content["Code"] == 4002001:
            pass
        else:
            print(e)
            print(content)
            return "Exception"
    except Exception as e:
        print(e)
        return "Exception"`
```

### ファイル出力
```
    # 銘柄情報、板情報を出力する
    while counter <= len(list):
        # 50銘柄のリストを作る
        obj = createRegObj(list, counter)

        # 最初の50件を登録する
        register(api_token["Token"], obj)
        #time.sleep(1)

        for i in range(50):
            current_time = datetime.datetime.now()
            diff_time = current_time - prev_time
            print(str(obj["Symbols"][i]["Symbol"]) + "  {}:{}:{}  diff:{}".format(current_time.hour, current_time.minute, current_time.second, diff_time))

            # 銘柄情報取得
            stockInfo = getSymbolInfo(obj["Symbols"][i]["Symbol"], api_token["Token"], str(obj["Symbols"][i]["Exchange"]))
            # 板情報取得
            boardInfo = get_board_info(obj["Symbols"][i]["Symbol"], api_token["Token"], str(obj["Symbols"][i]["Exchange"]))
            if boardInfo == "Exception" or stockInfo == "Exception" :
                break;
            else:
                #ファイル書き込み
                with open(data_today, 'a', encoding="utf-8") as fout:
                    # end=''を入れると出力ファイルに空行が入らない
                    #print(json_response, end='', file=fout)
                    # encodeがデフォルトではUnicodeのためensure_ascii=Falseをつける
                    # ファイル出力
                    print(json.dumps(stockInfo, indent=4, sort_keys=True, ensure_ascii=False), file=fout)
                    print(json.dumps(boardInfo, indent=4, sort_keys=True, ensure_ascii=False), file=fout)

            counter += 1
            prev_time = current_time

        # 50回ごとに銘柄登録解除(解除しないとエラー4002006が出る)
        unregister(api_token["Token"])
```

**Comment by Paynomono** [comment]
お世話になります。
私の環境でも同様の現象が発生しているので、投稿します。

◆ コード概要（PHP8.2）

```
// 対象となる銘柄情報を DB より 10 件取得
$Symbol_arr = ★処理内容省略 ;

// メモリ計測 開始時
kabukom_memory_measure();

// 取得処理 ※ １銘柄取得するごとに、銘柄登録を抹消し、ボード情報取得後には 0.2 秒の待ち時間を入れて流量制限に引っかからないように
foreach($Symbol_arr as $sym_val){
	
	// 銘柄登録解除
	$head_param =			array('Content-Type: application/json', "X-API-KEY: {$token}");
	$result_json =			★ CURL で PUT して銘柄登録解除する処理 ;
	$result_unregister =	json_decode($result_json, true);

	// ボード情報の取得
	$board_info =		[];
	$head_param =		array('Content-Type: application/json', "X-API-KEY: {$token}");
	$result_json =		★ CURL で GET して対象の銘柄のボード情報を取得する処理 ;
	$board_info =		json_decode($result_json, true);

	// 取得できれば、DBに保存
	// 処理内容省略
	
	usleep(200);
}

// メモリ計測 終了時
kabukom_memory_measure();

```


◆ 環境
OS：Windows 10 Pro 64 bit
CPU：Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz
RAM：16.0 GB
セキュリティソフト：デフォで入っているDefenderのみ
XAMPP（ PHP 8.2 ） → KabuStation に Curl で接続して API を叩いている

◆ 結果
1件目取得後以降、「〇〇の取得処理に5000msec以上経過しました。」が多発する。
0.2秒間隔で10件取得しようとした場合、8件～9件は上記エラーがログファイルに出力される。
ボード情報取得以外（例えば残高照会、トークン発行）は遅延なく実行できている。

このほかに必要な情報があれば確認して投稿します。
よろしくお願いします。
