### ISSUE TITLE
【不具合】信用新規成行での建玉可能額拘束額が計算値よりも大きい

### ISSUE THREAD

**Issue by jintonic3561** [kabucom/kabusapi#417]
■不具合事象(概要)
信用新規成行注文にて、前日終値＋ストップ高から計算される拘束建玉可能額と、実際に拘束される金額に大きな差異があります。

■本来想定されるアクションと事象
11/08大引け後にて確認
コード8698を300株、新規信用成行買いで注文を出すと、終値が895円のため、拘束額は(895+150)*300=313,500円のはずであるが、注文前後で /kabusapi/wallet/margin の MarginAccountWallet の返り値の差は403,500円になる。

この金額の差異は不具合によるものでしょうか？ご教授ください。

**Comment by cyber-minion** [comment]
発注時間はいつ頃でしょうか。
拘束額の計算基準値は16:15頃更新していますので、11月8日16:15頃以降注文した場合、計算は以下となります。

前日終値 = 11/8終値 = 1,045円
拘束額 = (1,045+300) * 300 = 403,500円

**Comment by yasuyuki-nakazawa** [comment]
こちらはクローズさせていただきます
