### ISSUE TITLE
【質問】ApiTokenの文字列が勝手に消えてしまうのは、どういう理由でしょうか。

### ISSUE THREAD

**Issue by shimo33333** [kabucom/kabusapi#418]
KabuSuteAddinSetting.xmlに保持されているApiTokenの文字列データがいつの間にか空の文字列になってしまい、
システムトレード中にエラーが発生してしまうことがあります。

Excelアドインを用いてトレードを行っているのですが、
Excelを再起動しておらず、kabu stationの終了やログアウトも行っていない状態で、
ApiTokenが勝手に空の文字列になってしまうのは、どういう理由が考えられますでしょうか。

また、勝手に空の文字列になってしまう問題を回避する方法は、どのような方法がありますでしょうか。

**Comment by yasuyuki-nakazawa** [comment]
エラーが発生した付近のエラーログメッセージ等はございませんでしょうか。

**Comment by shimo33333** [comment]
本日、8:30頃からExcelアドインを用いて稼働しておりましたが、
本日の「10:01:24」に「KabuSuteAddinSetting.xml」が更新されて、ApiTokenの文字列が空白に変わっておりました。
参考になるかわかりませんが、その前後のログ（KabuS_20211111.log）を以下に貼り付けておきます。

10:01:16.9970,I,8592,0017 UpdateService.UpdateCheck : start
10:01:24.8892,I,8592,0052 KeepSession at 2021/11/11 10:01:23
10:04:44.8909,I,8592,0046 KeepSession at 2021/11/11 10:04:43

（気付いた時点での「KabuSuteAddinSetting.xml」の更新日時が「10:01:24」でしたが、
　もっと前の時点で空白に置き換わっていた可能性もあるとは思います。）

**Comment by yasuyuki-nakazawa** [comment]
記載いただいたログは本件とは関連のないものと思慮いたします。
Addinの再インストールをお勧めいたしますが、当該事象の可能性に関して確認いたします。

**Comment by cyber-minion** [comment]
アドインをインストールする時に、初期ファイルで上書きされるので、空白になります。

**Comment by shimo33333** [comment]
一度Addinの再インストールを試してみたいと思います。

ちなみに、本日（11/12）は、8時半頃から稼働していますが、
まだApiTokenが空白に置き換わる事象は発生していないため、
起きるタイミングは、日によっても違いそうです。

**Comment by yasuyuki-nakazawa** [comment]
@shimo33333 
こちら、再インストール以降、事象は発生いたしましたでしょうか
当方側では、通常利用いただいている中で、TOKENがブランクで更新されてしまう事象は確認できておりません。

**Comment by shimo33333** [comment]
トークンが空白となる問題自体は解決していないのですが、
トークンが空白となってしまった場合を検知し、トークンを取得するコマンド（/token）を実行して
プログラム内でトークンを保持するように改良することで、問題を回避できるようになりました。

お手数おかけ致しました。
