### ISSUE TITLE
【質問】日経225先物の9:00の始値（正確な始値）を取得する手段はありますでしょうか。

### ISSUE THREAD

**Issue by shimo33333** [kabucom/kabusapi#419]
現在価格を取得する手段はあると思いますが、
9:00ちょうどの正確な始値を取得する方法はありますでしょうか。

**Comment by yasuyuki-nakazawa** [comment]
どちらの情報を取得したいのか
①9時ちょうどの時価情報
②先物の始値

始値が取得したい。という前提でコメントいたします。
※先物は8:45分かとおもわれますが、始値取得はboard() にて始値を取得できます。

**Comment by shimo33333** [comment]
①の方になるかと思います。
日経225先物の9時0分以降の最初の価格です。
（別の言い方をすると、日経225先物の9時ちょうどの分足の始値）

**Comment by yasuyuki-nakazawa** [comment]
なるほどです。
そうなると、現状は分足のデータ取得等は行えない（検討中）のため、Pushによる時価情報をリアルタイムに受信して、9時に受けた情報を採用していくのが確実かと思慮します

**Comment by shimo33333** [comment]
＞Pushによる時価情報をリアルタイムに受信して、9時に受けた情報を採用していくのが確実かと思慮します

はい、現状そのように取得しておりますが、ポーリング間隔の限界から、やはり取得価格にずれが生じてしまいます。
分足データの取得まではできなくても、9時ちょうどの始値の取得だけでも対応いただけると助かります。

**Comment by yasuyuki-nakazawa** [comment]
@shimo33333 
Pushによるリアルタイム時価配信下におけるポーリング処理とはどのようなことでしょうか。
都度のポーリング処理による時価取得ですと、記載のとおりタイミング差異というのは発生することは理解できますが、Pushであれば、更新都度のデータ取得となるため、当該差異は発生しないものと思慮しております。

**Comment by shimo33333** [comment]
ポーリング処理によって、できる限り9時ちょうどに近い値を取得しようとしても、
9時ちょうどの分足チャートの始値の値とは、差が生じてしまうという意味です。

例えば、本日11/15であれば、「29790」の価格の取得方法です。
ポーリング処理による取得では、「29810」という値が取得されて、20円のずれが生じてしまいました。

9時ちょうどの始値の値を差異なく正確に取得する方法があるのであれば、教えていただきたいです。

**Comment by shimo33333** [comment]
失礼致しました。

Pushではなく、Getによるポーリング処理を行っておりました。
Pushによる値取得に変更して実施してみたいと思います。

ご助言いただき、ありがとうございました。

**Comment by shimo33333** [comment]
すみません、ExcelVBAを用いて、Pushで値取得するサンプルコードを
ご提示いただくことはできないでしょうか。
（ダウンロードしたExcel群には含まれていないようです。）

過去のIssuesを検索したところ、
以下のような呼び出し方でスタートさせる、というところまでは分かったのですが、

　Application.Run("WebSocket", 9984, 1, "現値")

値取得を受け取る側のコードは、どのような記述になりますでしょうか。

また、時刻の差異が発生しないように、
「現値」とその「現在時刻」を同時に取得したいのですが、
その場合、どのような記述になりますでしょうか。

**Comment by cyber-minion** [comment]
下記場所にある「kabuSTATION_API_PUSH_sample.xlsx」をご利用いただけると思いますが
https://github.com/kabucom/kabusapi/releases/tag/ExcelMacro-v1.10.0

**Comment by yasuyuki-nakazawa** [comment]
@shimo33333 
上記のサンプルのご利用、お試しいただけたでしょうか。
9時ちょうどのデータの取得をプログラム側で判断して、9時からの始値を生成していただけると思慮いたします

**Comment by shimo33333** [comment]
以下のような記述で、VBAのプログラム内で、値と時刻を取得することができました。
　price = Application.Run("WebSocket", xxxx, yyyy, "現値")
　time = Application.Run("WebSocket", xxxx, yyyy, "現値時刻")

ただし、これはVBAで記述したプログラム内で、ポーリングで値を取得する形であり、
ポーリング間隔よりも早い値更新があった場合に、やはり値の取り逃しが発生してしまいます。
（9時ちょうどのデータ取得ができるとは限らない）

ポーリングではない形で、VBAのプログラム内で、
PUSH通信からのトリガを元に値取得するには、どのように記述すれば実現できるのかご教授いただけないでしょうか。

**Comment by yasuyuki-nakazawa** [comment]
そうなりますと、push形式で受けた時価関連情報をもとに処理するしかないかもしれません。
アドイン側のプログラムを修正するか、pushを処理するプログラムを作成されてはいかがでしょうか？

**Comment by shimo33333** [comment]
現状ご提供いただいているものでは実現できない点、了解致しました。
ご提案いただいた方法や、その他のアプローチについて、別途検討したいと思います。
ご回答いただき、ありがとうございました。
