### ISSUE TITLE
【質問】kabuステーションを複数PCで起動することについて

### ISSUE THREAD

**Issue by Ros522** [kabucom/kabusapi#42]
kabuステーションを複数のPCにて立ち上げ、APIを利用することについて
制限などはあるでしょうか。
例えば、複数起動により50銘柄以上の情報の通知を受けようとする行為は利用許諾上の「システムの負荷を増加させると判断する行為」に当たるでしょうか。

※下記ページでは、「最後に起動したkabuステーションからの発注のみが有効となる」旨の記載があります。
https://faq.kabu.com/s/article/k001796

**Comment by yasuyuki-nakazawa** [comment]
複数端末でkabuステーション自体を起動することはできますが、APIの認証においては、kabuステーションがログイン常態である必要があります。
ログインは複数台では実施できず、最後にログインをしたクライアントのみログイン状態が有効となります。
従いまして、複数台でのAPI接続は不可となります

**Comment by Ros522** [comment]
ご回答ありがとうございます。Issue#38にて、WebSocket APIについては一度銘柄登録がされたものはログアウト状態でも配信される旨記載されておりますが、銘柄登録後にログアウト状態のkabuステーションを複数起動することで銘柄50以上も受信可能ということになるでしょうか？
当方の環境でも、ログアウト状態で通知APIが機能していることは確認しています。

証券会社様のほうで負荷になり得る可能性はあると思うので、確認させていただきます。

**Comment by yasuyuki-nakazawa** [comment]
kabuステーションは二重起動できないため、同一端末上で複数起動することはできません。
kabuステ全体として、200銘柄を超える情報配信に関しては他お客様の配信に影響を及ぼす可能性があり、お控えいただけますと幸いです。
今後、５０銘柄の制約に関しては改善をさせていただくよう検討しております。

**Comment by hori-ryota** [comment]
@Ros522 すみません質問させてください。
ここ最近複数PCでのデータ取得が安定せず、今日のデータで詳細をみたところログイン状態のものしかデータが入っていないようでした。
安定しなくなったのは先週のアップデートくらいからなのですが、同様の症状が発生したりしていないでしょうか。

**Comment by Ros522** [comment]
> @Ros522 すみません質問させてください。
> ここ最近複数PCでのデータ取得が安定せず、今日のデータで詳細をみたところログイン状態のものしかデータが入っていないようでした。
> 安定しなくなったのは先週のアップデートくらいからなのですが、同様の症状が発生したりしていないでしょうか。

@hori-ryota 
ご連絡ありがとうございます。本日のデータ、金曜のデータを見る限りは自分は取れてそうです。
その前は、アップデート忘れてたりで一部ミスで取りこぼしてますが、特段記載頂いてる症状は起きてなさそうですね

**Comment by hori-ryota** [comment]
@Ros522 情報ありがとうございます！

では私の個人的なバグの可能性が高そうですね…。助かりました。ありがとうございます。

**Comment by hori-ryota** [comment]
@Ros522 Issueを立てたのですが、データ流量により発生する症状の可能性があるようなので念のためご連絡しておきます。

[【不具合】PUSH API（Web Socket）が切断される · Issue \#284 · kabucom/kabusapi](https://github.com/kabucom/kabusapi/issues/284#issuecomment-809984269)
