### ISSUE TITLE
【質問】ドキュメント 銘柄情報の呼値グループ10003に呼値単位が一致する条件分岐がある

### ISSUE THREAD

**Issue by tsuchinaga** [kabucom/kabusapi#420]
[銘柄情報](https://kabucom.github.io/kabusapi/reference/index.html#operation/symbolGet)の呼値グループにある10003の、
「50000000円以下」と「50000000円超」が同じ呼値単位になっています。

不要な条件分岐があるか、呼値単位が間違っているかだと思います。

**Comment by yasuyuki-nakazawa** [comment]
当件、確認させていただきます。

**Comment by cyber-minion** [comment]
JPXサイトによりますと、「50000000円以下」と「50000000円超」が同じ呼値単位になっているので、問題ないかと思います。
https://www.jpx.co.jp/equities/trading/domestic/07.html

呼値グループは「TOPIX100構成銘柄」なのか「その他の銘柄」なのかが分かるようにリファレンスを補完するようにいたします。

**Comment by tsuchinaga** [comment]
JPXのサイトに合わせるということで認識しました。

「5,000円以下」などもJPXには明記されているので、「50,000,000円以下」と同様にドキュメントに追加されるということでしょうか？

**Comment by cyber-minion** [comment]
項目の追加はしない想定です。
JPXのページは、TOPIX100構成銘柄とその他銘柄を横に並べて表示しています。１つの表で表しており、その他の銘柄で「5,000円以下」は呼値が異なるので、この行があるのかと思います。カブステAPIのリファレンスでは、表が分かれているので、項目追加はしない形とさせていただきたいと考えております。

**Comment by tsuchinaga** [comment]
一貫性がないことが気になり質問させていただきました。

値が間違っているわけじゃないことは理解し、変更ないことを承知しました。
