### ISSUE TITLE
【質問】既に注文済（ただし未約定）の指値注文の指値価格を変更する手段はありますでしょうか。

### ISSUE THREAD

**Issue by shimo33333** [kabucom/kabusapi#421]
既に注文済（ただし未約定）の指値注文の価格を変更したい場合に、
同じOrderIDに対し、価格を変更する手段はありますでしょうか。

現状やろうと思うと、一度注文をキャンセルしてから、再度指値注文を行う必要がありますが、
その場合、「キャンセル」と「再度指値注文を行う」の間に行き違いが生じ、
誤って複数注文されてしまうなどのリスクが生じ得ます。

もし同じOrderIDに対し、価格を変更する手段がないのであれば、対応いただきたいです。

もしくは、現状のおいて、上記リスクなく確実に実施できる手段
（複数注文されてしまうことを確実に防ぎながら価格を変更する手段）があれば、ご提示いただきたいです。

**Comment by tsuchinaga** [comment]
#227 
注文訂正機能はない。と、過去に回答があります

> 誤って複数注文されてしまうなどのリスクが生じ得ます

取消 → 取消確認をwhileループ → 注文 を一連の動作にすれば複数注文されなくないですか？

**Comment by shimo33333** [comment]
返答いただき、ありがとうございます。
過去に同様の質問があったとのこと、失礼致しました。

以前、注文取消「canselorder」のレスポンスが成功で帰ってきた直後、
同じ建玉IDへの注文をするとエラーになってしまうことがあり、うまくいかないと思っていましたが、
canselorderのレスポンスではなく、取り消し対象の注文IDが実際に取消済になっているかを、
whileループで確認し続ければ、うまくいきそうな気がします。

ご助言いただき、ありがとうございます。
