### ISSUE TITLE
code 4001005 パラメータ変換エラー　詳細はKABUログで

### ISSUE THREAD

**Issue by 4494ku** [kabucom/kabusapi#422]
売り玉返済の信用返済注文で上記のエラーが出ます。
同様の注文で買い玉の信用返済注文は問題なく通ります。

教えてください。

**Comment by tsuchinaga** [comment]
ひとまずログを確認して、同時に掲載して頂いたほうが回答を得やすいと思いますが

下記がログの位置です
https://github.com/kabucom/kabusapi/issues/11#issuecomment-678062067

**Comment by 4494ku** [comment]
kabuSログファイルの内容は以下でした。

以下ログの内容です＝＝＝＝＝＝＝
12:58:52.8951,I,8432,0010 【SendOrder】({"Password":"****************","Symbol":"2317","Exchange":1,"SecurityType":1,"Side":"2","CashMargin":3,"MarginTradeType":1,"DelivType":0,"AccountType":2,"Qty":100,"ClosePositionOrder":null,"ClosePositions":[{"HoldID":"E20211115009JM","Qty":100}],"Price":2052,"ExpireDay":20211115,"FrontOrderType":20})
12:58:52.8951,I,8432,0010 【SendOrder】({"Code":4001005,"Message":"パラメータ変換エラー - 詳細はkabuSログファイルを確認してください"})

**Comment by tsuchinaga** [comment]
信用返済ではDelivTypeの指定が必須とされています。これが原因の一つではないでしょうか？

**Comment by yasuyuki-nakazawa** [comment]
@tsuchinaga さん、支援コメントありがとうございます。
@4494ku 
信用返済ですので、DelivType＝０ではなく、指定のほどをお願いします

**Comment by 4494ku** [comment]
@tsuchinagaさん、yasuyuki-nakazawaさんありごとうございました。
ご指摘の通りでした。
とても助かりました。

**Comment by yasuyuki-nakazawa** [comment]
こちらはクローズさせていただきます
