### ISSUE TITLE
【質問】リクエスト上限について

### ISSUE THREAD

**Issue by woodwood928** [kabucom/kabusapi#423]
株価情報の定期モニタリングに本APIの利用したいと考えております。
各APIの利用上限（秒間リクエスト数等）はございますか？

**Comment by tsuchinaga** [comment]
レファレンスの各見出しに記載があります

### 発注
> 発注系のリクエストは秒間5件ほどの流量制限を設けています。

### 取引余力
> 取引余力のリクエストは秒間10件ほどの流量制限を設けています。

### 情報
> 情報系のリクエストは秒間10件ほどの流量制限を設けています。

**Comment by woodwood928** [comment]
ご返信ありがとうございます。
