### ISSUE TITLE
【質問】夜間の0時以降にExpireDay=0（当日）で発注すると即期限切れになるのは仕様でしょうか

### ISSUE THREAD

**Issue by shimo33333** [kabucom/kabusapi#424]
日経225Miniの取引を行っておりますが、
夜間の0時以降にExpireDay=0（当日）で指値で新規発注すると、
発注したタイミングで即約定しない限り、即期限切れになってしまうのは仕様でしょうか。

APIの資料には、「その市場の引けまでの間 : 当日」という記載があるため、
夜間での発注であれば、夜間の取引が終了するまでの期限であることを期待します。

上記問題を避けるために、0ではなく、ExpireDayに8桁の数値（32bitのInteger（ExcelVBAではLong））を指定するのですが、
以下のように不正と判断されて、注文を行うことができません。
（本日2021/11/17の夜中1時頃のログの例）
01:39:34.2319,E,9064,0011 注文期限が不正です : 166120019@24, 24, ExpireDay=20211117
01:42:47.2698,E,9064,0011 注文期限が不正です : 166120019@24, 24, ExpireDay=20211118

上記問題により、現在指値による注文が実施できない状態に陥っております。
問題の回避方法を早急にご提示いただけないでしょうか。
（ExcelVBAにて発注処理を行っており、成行であれば問題なく動作しております。）

もし、こちらの勘違いや初歩的なミスであれば、大変申し訳ありません。
ご回答の方、よろしくお願い致します。

**Comment by shimo33333** [comment]
本件、日中の指値発注においても、生じることが確認できました。
つまり、日中・夜間問わず、正常に指値注文自体ができない状態に陥っております。

日中にてExpireDay=0で指値発注した結果、即期限切れとなった注文のkabu stationでの例を添付致します。

本件について、コメントいただけないでしょうか。
<img width="586" alt="期限切れの様子" src="https://user-images.githubusercontent.com/93054199/142131679-8f3be050-ad28-4b1e-b072-5e0026e01a07.png">

**Comment by ys-110** [comment]
FAKの指定をしているので即時失効しているのではないでしょうか。
以下のページの「8. 執行数量条件」に執行条件ごとの挙動が書いてあります。
https://kabu.com/item/fop/rule.html

**Comment by shimo33333** [comment]
まさにご指摘の通りと思います。
大変助かりました。
コメントいただき、ありがとうございます。
