### ISSUE TITLE
【質問】=POSITIONS(0)を別のシートに値のみ貼り付け、マクロを作成したいのですが

### ISSUE THREAD

**Issue by 4494ku** [kabucom/kabusapi#425]
】=POSITIONS(0)で得た自分の銘柄コード、株数、株価などの情報を別のシートに値のみ貼り付け、
VBAマクロを作成したいのですが、
証券コードなどの数字をコードを書いても認識してくれません。
（同セルに一度消去して同様の証券コードを手入力すると認識してくれます。）
別の加工をする必要があるのでしょうか？

**Comment by 4494ku** [comment]
見ていただきましてありがとうございます。
自己解決しました。
貼り付けた数値がエラー値でしたのでそれぞれ数値に変換したところ解消されました。

**Comment by yasuyuki-nakazawa** [comment]
解決されたということで、当件はクローズさせていただきます
