### ISSUE TITLE
【質問】kabuステーションの起動について

### ISSUE THREAD

**Issue by sakatsusan** [kabucom/kabusapi#43]
現在、仕様書を読み始めた段階ですが、
このＡＰＩは、kabuステーションを起動しておかないと動かないのでしょうか？

**Comment by cyber-minion** [comment]
はい、その通りです。kabuステーションを起動した状態でAPIをご利用ください。

**Comment by sakatsusan** [comment]
早速ご回答ありがとうございます。

kabuステーションは、ＡＰＩを発行するＰＣ上で動作していないといけませんか？
（すなわち、別ＰＣであっても動いていればいいのですか？）

また、kabuステーションが万一動作・挙動が重くなってしまった場合などあっても
発注スピードには影響せず、無関係なのでしょうか？

**Comment by yasuyuki-nakazawa** [comment]
1点目の質問に関してですが、
　kabuステーションAPIは、同一端末からのリクエストのみを許容する仕組みとなっております。

2点目の発注速度の影響について
　端末状況、アプリケーションの状況により発注速度の影響は異なるため、断定回答はできませんが、
　kabuステーションが重くなっている状況下においては、発注処理には影響があると考えられます。
