### ISSUE TITLE
【質問】日経２２５先物 日通し発注エラーにつきまして

### ISSUE THREAD

**Issue by fwarit** [kabucom/kabusapi#430]
いつも大変お世話になっております。

日経２２５先物で、日通しで成り行き発注をしたいのですが、逆指値以外は不可ということなので、
逆指値で対応しようと下記のようにしたのですが、

「HTTP Error 400: Bad Request
　{'Code': 4001005, 'Message': 'パラメータ変換エラー - 詳細はkabuSログファイルを確認してください'}」
と出ます。

どこがダメなのでしょうか??　kabusログファイルの場所もわかりませんし…

これが丸っきりダメだとした場合、日通しで、成り行き発注と同じ効果を出す手立てがあれば、ご教示
頂きたく何とぞ宜しくお願い致します。

def sendorder_future_close_buy(Password,
                               stock_code,
                               Order_quantity,
                               triggerprice,
                               token):

    obj = {'Password': Password,
           'Symbol': stock_code,
           'Exchange': 2,
           'TradeType': 2,
           'TimeInForce': 1,
           'Side': "2",
           'Qty': Order_quantity,
           'ClosePositionOrder': 0,
           'FrontOrderType': 30,
           # 'Price': 0,
           'ExpireDay': 0,
           'ReverseLimitOrder': {
               'TriggerPrice': triggerprice,
               'UnderOver': 2,  # 1.以下 2.以上
               'AfterHitOrderType': 1,  # 1.成行 2.指値
               'AfterHitPrice': 0}
           }

    json_data = json.dumps(obj).encode('utf-8')

    url = 'http://localhost:18080/kabusapi/sendorder/future'
    req = urllib.request.Request(url, json_data, method='POST')
    req.add_header('Content-Type', 'application/json')
    req.add_header('X-API-KEY', token)

    try:
        with urllib.request.urlopen(req) as res:
            print(res.status, res.reason)
            for header in res.getheaders():
                print(header)
            print()
            content = json.loads(res.read())
            pprint.pprint(content)
    except urllib.error.HTTPError as e:
        print(e)
        content = json.loads(e.read())
        pprint.pprint(content)
    except Exception as e:
        print(e)

**Comment by fwarit** [comment]
pythonです
# 'Price': 0,となっていますが、実際は＃はなしです。
すみませんが、宜しくお願いいたします。

**Comment by tsuchinaga** [comment]
ログの位置です。ログの内容も記載いただいたほうが返答を得やすいと思います

https://github.com/kabucom/kabusapi/issues/11#issuecomment-678062067

**Comment by hishiharahaz** [comment]
@fwarit さん
確か、先物の日通しで成行(逆指値も)は不可だったかと思います。

**Comment by fwarit** [comment]
tsuchinaga さん、hishiharazさん、ありがとうございます。

ログを見ましたところ、
発注時刻毎に　11:09:07.0308,I,2424,0010 KabuSApiManager.PreRelationCheck=ERROR_CD_001_005_002
　　　　　　11:09:07.0308,E,2424,0010 不明なエラー(ERROR_CD_001_005_002)
が出ていました。

添付: 
[KabuS_20211201.log](https://github.com/kabucom/kabusapi/files/7665340/KabuS_20211201.log)

日通しでは逆指値も不可とのことですが、APIリファレンスを読む限りはダメというニュアンスは読み取
れないのですが、どこかに記載がございますでしょうか??

ご教示いただきたく何卒宜しくお願い致します。

**Comment by hishiharahaz** [comment]
@fwarit さん
私の場合、発注出来るか出来ないかの執行条件は、カブステーションの発注画面で指定してみて、ボタンが押せなければ発注できないと認識しています。
参考になれば幸いです。

**Comment by tsuchinaga** [comment]
TimeInForce 有効期間条件 にて FAS を選択した場合は、指値しかできません。
これは TimeInForce の項に記載があります。

**Comment by fwarit** [comment]
tsuchinaga さん、ありがとうございます。
日通し×FASは、逆指値は出来るけど、〇〇円以上(以下)の指値のみということですね??
逆指値後の成行きを指値に変えればよいということですね??　試してみます。

**Comment by yasuyuki-nakazawa** [comment]
当件はクローズさせていただきます
