### ISSUE TITLE
kabustation apiの今後について【質問】

### ISSUE THREAD

**Issue by YOHSIKI** [kabucom/kabusapi#431]
お世話になっております。
今年は殆どapiの機能追加などなかったと思いますが、今後アップデートされていくのでしょうか。
他のユーザから度々質問に挙がる分足の取得（過去分を含め）や、リアルタイム株価予測の取得など比較的要望が多いと思われる機能に関して、開発は進行中なのでしょうか。
今後機能が拡充されていくのか期待してよいのか知りたいです。
可能な範囲でご教示いただけますと幸いです。
以上、よろしくお願いいたします。

**Comment by cyber-minion** [comment]
お待たせして申し訳ございません。上記機能含めて、今後機能拡充の予定がありますが、他案件状況との兼ね合いで調整の上、という状況のため、現在の検討が一旦目処付き次第展開させて頂きます。

**Comment by YOHSIKI** [comment]
ご回答ありがとうございます。
今後も機能拡充の予定があるとのこと承知いたしました。
引き続きよろしくお願いいたします。
