### ISSUE TITLE
innovation.mufg.jpはDNSエラーになります

### ISSUE THREAD

**Issue by jcayzac** [kabucom/kabusapi#436]
https://innovation.mufg.jp/api/ fails to load (cannot resolve hostname)

**Comment by yasuyuki-nakazawa** [comment]
this site is not our site, but I will get in touch with this site window.

**Comment by cyber-minion** [comment]
The access failure is due to the change of MUFG's URL. The new URL is https://www.mufg.jp/profile/strategy/dx/api/index.html.
We will also update the corresponding pages on our website and will let you know once it is done.
Sincerely apologize for the inconvenience.

**Comment by yasuyuki-nakazawa** [comment]
we had already modified the link.
so i close this issue. thank you.
