### ISSUE TITLE
【要望】利用停止の解除に関して

### ISSUE THREAD

**Issue by mole5** [kabucom/kabusapi#437]
kabuステーションAPIを利用させて頂いております。
先日、kabuステーションAPIにて、短時間に多くのリクエストを送信してしまいました。
その為だと思うのですが、kabuステーションAPIを利用できなくなってしまいました。
ご迷惑をお掛けしてしまい大変申し訳ないのですが、kabuステーションAPIを利用できるようにして頂くことは出来ますでしょうか。
今後リクエストの送信には十分注意して参りますので、宜しくお願い致します。

※auカブコム証券のお問い合わせフォームから問い合わせたところ、こちらからお問い合わせくださいとのことでした。

**Comment by cyber-minion** [comment]
本文中に氏名に相当するものを記載することは適切でないため、当該部分のみ訂正させていただきます。

> kabuステーションAPIを利用できなくなってしまいました

画面右上のAPIインジケーター（ </> のマーク）は何色でしょうか。

**Comment by yasuyuki-nakazawa** [comment]
こちらでは利用停止処理を行っていない認識です
上記ご確認をお願いします

**Comment by yasuyuki-nakazawa** [comment]
タイトルが未入力であったため、追記させていただきました

**Comment by obara2** [comment]
画面右上のAPIインジケーターは緑色で、「利用停止処理を行っていない認識」とのことなので詳しく調査したところ、
こちらの設定ミスが原因で、無事にレスポンスを受け取ることができました。
お忙しいところお騒がせしてしまい、申し訳ありませんでした。
