### ISSUE TITLE
【質問】

### ISSUE THREAD

**Issue by 5524takahashi** [kabucom/kabusapi#438]
以下のようなルールで自動売買のシステムを作成したいのですが、可能でしょうか。
銘柄は任意の自分で選んだ銘柄、もしくは日経先物２２５ミニを想定しています。

１．指値あるいは成り行きで信用買いの注文を出す。
２．価格が上昇し、含み益のまま大引けを迎える場合は大引け成り行きで決済。
３．場中に下落し、含み損になった場合は、即売却し、新規空売りをする。
４．そのまま含み益がある場合は大引けで決済。
５．信用売り建ての建玉が上昇し、含み損になった場合は、即損切り（買い戻し）し、信用買い。
６．以降２～４の繰り返し。

どうぞ、よろしくお願いいたします。

**Comment by yasuyuki-nakazawa** [comment]
損益に部分は計算する必要がございますが、可能かと思慮します
記載された意向を拝見すると、pushによるリアルタイムでの時価監視は必要です
サンプルプログラムで、pushの時価受信の処理をご参考頂き、プログラムを記載されていけば良いかと存じます
注文に関しては、引成注文もございます

**Comment by 5524takahashi** [comment]
返信ありがとうございます。
損益部分の計算とは、場中の損切りの値段設定ということでしょうか。
それを設定すれば、時価を監視しつつプログラムが可能ということですね。
素人なので、これから色々勉強していきたいと思います。
今後ともよろしくお願いいたします。

**Comment by yasuyuki-nakazawa** [comment]
はい。損益計算の部分です
ご不明点等ございましたら、また記載いただければと存じます

**Comment by yasuyuki-nakazawa** [comment]
こちらはクローズさせて頂きます
