### ISSUE TITLE
【質問】kabuステーションAPIを使用した場合のルールをご教授ください

### ISSUE THREAD

**Issue by tiro3** [kabucom/kabusapi#439]
kabuステーションAPIを利用して、「制度信用」・「一般信用（長期）」・「デイトレ信用」の「デイトレ信用」の取引きを実施しようと思っております。

■教えていただきたい事項１
デイトレ信用を実施しようとしているのですが、デイトレを例えば12月16日に1日実施した場合、12月16日の株式市場開場から終業までの間を期日内と考えればよろしいでしょうか。
■教えていただきたい事項2
上記1がyesの場合、期日内に建玉の返済をするというのは、具体的にどのような手順を行えばよろしいのでしょうか。

以上2点ご教授ください、よろしくお願いいたします

**Comment by yasuyuki-nakazawa** [comment]
ご質問の回答ですが、デイトレ信用は当日(上記ですと12/16中)に新規建ポジションを返済する必要があります。

デイトレに関しての詳細は以下のページをご覧下さいませ
https://kabu.com/sp/item/shinyo/about/deitore.html

**Comment by yasuyuki-nakazawa** [comment]
当件はクローズさせていただきます
