### ISSUE TITLE
間違ったAPIパスワードでtoken要求した時のエラーコード

### ISSUE THREAD

**Issue by uedatakeshi** [kabucom/kabusapi#44]
{"Code":4001013,"Message":"トークン取得失敗"}

で返って来ましたが、4001007 | ログイン認証エラーの間違いでは？

**Comment by yasuyuki-nakazawa** [comment]
記載頂いているエラーの違いに関してですが、下記のとおりとなっております。

4001013：トークン取得失敗：kabuステーションがログインしている状態で、APIパスワードが間違っている
4001007：ログイン認証：kabuSステーションログイン認証でない。APIパスワードの正誤にかかわらず。

こちら、リファレンスの補完させていただきます

**Comment by yasuyuki-nakazawa** [comment]
こちら、リファレンスの更新も実施させて頂きました。
https://kabucom.github.io/kabusapi/reference/index.html#tag/auth%2Fpaths%2F~1token%2Fpost
