### ISSUE TITLE
【質問】価格チャートを描く為、株の価格の配列が必要あると考えておりますが、このAPIは可能でしょうか？

### ISSUE THREAD

**Issue by gs-kien** [kabucom/kabusapi#441]
【質問】価格チャートを描く為、株の価格の配列が必要あると考えておりますが、このAPIは可能でしょうか？

```
{ prices: [189, 188.85, 189, ..., 192., 190] }
```

**Comment by yasuyuki-nakazawa** [comment]
現状、過去情報の履歴をご提供するインターフェースを有しておりません。
リアルタイムに時価情報を取得、対応していただくしかない状況で申し訳ございません。
過去情報の展開に関しましては、取引所との情報配信のルールに則り対応していく必要がございますので、将来的に課金サービス等の付加サービスとして対応することを検討しております

**Comment by yasuyuki-nakazawa** [comment]
過去の情報に関しては、以下のサイトでの購入が可能です
ご検討いただければと思います
http://db-ec.jpx.co.jp/

**Comment by yasuyuki-nakazawa** [comment]
こちらはクローズさせていただきます
