### ISSUE TITLE
【質問】日経平均先物の銘柄コードを取得する方法について。

### ISSUE THREAD

**Issue by icnmyx** [kabucom/kabusapi#442]
KabusapiサイトのPythonサンプルコードを参考にして日経平均先物の銘柄コードを取得したいのですが、kabusapi_symbolname_future.pyの引数を‘NK225’と‘202203’に変えてプログラムを実行したところ、以下のレスポンスが返ってきます。
 
```
200 OK
('Content-Length', '33')
('Content-Type', 'application/json; charset=utf-8')
('Server', 'Microsoft-HTTPAPI/2.0')
('X-Content-Type-Options', 'nosniff')
('X-XSS-Protection', '1; mode=block')
('X-Frame-Options', 'DENY')
('Content-Security-Policy', "default-src 'none'")
('Access-Control-Allow-Origin', '*')
('Date', 'Fri, 17 Dec 2021 04:35:40 GMT')
('Connection', 'close')

{'Symbol': None, 'SymbolName': None}
```

エラーコードではないのですが、銘柄コードが‘None’として帰ってきます。
日経平均先物の銘柄コードを取得するにはどうすればいいですか？

**Comment by hishiharahaz** [comment]
@icnmyx さん
パラメータを以下にしたところ、問題なく銘柄コードを取得することができました。
指定されたパラメータをご確認いただければと存じます。
`params = { 'FutureCode': 'NK225', 'DerivMonth': 202203 }`

レスポンス
`{'Symbol': '167030018', 'SymbolName': '日経平均先物 22/03'}`

**Comment by icnmyx** [comment]
回答ありがとうございます。
パラメータを確認したところ問題はありませんでしたが、検証用ポートを使っていたことが原因だったみたいです。本番用ポートでプログラムを実行したところ問題なく銘柄コードを取得することができました。

本番用ポートで銘柄コードを取得できたとしても、検証用ポートで銘柄コードを取得できないと、プログラムのテストできません。プログラムを検証用ポートでテストランさせるには、どうすればいいのでしょうか？

まず検証用ポートでプログラムを組み立て、テストしてから、本番用ポートで稼働させるのが手順だと思うのですが、本番用ポートでしか使えないAPIの機能は他にもあるでしょうか？

お手数をお掛けしますが、よろしくお願いいたします。

**Comment by yasuyuki-nakazawa** [comment]
検証用ポートはいわゆるスタブ的な機能となります
ですので、パラメータのいかんに関わらず同一値が返却されますので、留意いただければと思います
ご要望の多さと、、利用者数の状況に応じて仮想的なテスト環境の準備は検討させていただきます

**Comment by cyber-minion** [comment]
本件は解決済みのようですので、クローズさせていただきます。
