### ISSUE TITLE
【質問】kabusAPIでの米国株の取扱いについて

### ISSUE THREAD

**Issue by ybangit** [kabucom/kabusapi#443]
auカブコム証券では2022年初春に米国株の取り扱いを始める予定だとアナウンスされていますが、
kabusAPIでの米国株取引サポートはどのような予定でしょうか？

よろしくお願いします。

**Comment by cyber-minion** [comment]
あいにく、現状、お答えできることはございません

**Comment by ybangit** [comment]
回答ありがとうございました。

個人的なことですが
昨年、kabusAPIがリリースされたおかげで
今年本格的なアルゴリズムによる自動売買システムを構築することができました。毎日、自動売買を動かせることに感謝しています。

2022年の機能拡充に期待しています。

**Comment by ybangit** [comment]
https://www.itmedia.co.jp/business/spv/2112/28/news116.html

この記事によると

「2023年冬には他大手ネット証券と同様、外貨決済も提供するという。また、米国株信用取引も同時期に提供する予定だ。」

とありますので、外貨建てで米国株信用取引のAPIが始まるのも早くて2023年冬以降ということになりますね。

日本株で実績を積みながら気長に待ちます。
