### ISSUE TITLE
【要望】信用取引でIOC指値の注文後、残高照会の結果の反映にタイムラグがないようにしてほしい

### ISSUE THREAD

**Issue by snowballrichdad** [kabucom/kabusapi#444]
IOC指値でsendorderを発行し、APIがのレスポンスがあったら即座に、positionsを発行し残高照会をしています。
IOCは即時約定かキャンセルだと思っていましたので、APIが復帰したらすでにサーバ上ではpositionsに反映されているかと思ったのですが、約定されてキャンセルされていないにも関わらずpositionが0のことが多いです。
IOC注文の場合は、sendorderの復帰時にはpositionsに反映されるようにしてもらえませんでしょうか？
そうしないと、sendorderの結果を確実に取得するのが難しくなってしまいます。

特に気配値と指値の差が大きいときにそのようなことが多いような気がします。

これまでは1秒待つと反映されていましたが、確証が持てません。
sendorderが約定したかどうかが確定しないと、次のアクションをプログラムする前提を立てることが難しくなってしまいますので、自動取引のプログラムを作るのが難しくなってしまいます。

せっかく数あるauカブコム証券の注文方法の中で、IOC注文だけはAPIでサポートしているのですから、そこはsendorder復帰時にはpositionsの結果に反映されてるいかたちにしてほしいです。

**Comment by tsuchinaga** [comment]
要望について横からあれこれ言うのはアレなんですが、前提となる知識の共有だけ。

注文は ユーザー → 証券会社 → 取引所(東証など) と流れて板に乗ります。
そしてユーザーが行なった注文リクエストに対してのレスポンスである注文番号は、
証券会社が作成して返しているのか、証券会社が取引所に送信して発行されたものを返しているのかは分かりません。
しかし、どちらにしても約定するのを待ってから注文番号を返しているわけではないということは容易に想像できます。

snowballrichdad さんが要望として出している「sendorder復帰時にはpositionsの結果に反映されてるいかたちにしてほしい」は、「約定するのを待ってからレスポンスを返す形に変えてほしい」と読めます。

**Comment by snowballrichdad** [comment]
コメントありがとうございます。
>「約定するのを待ってからレスポンスを返す形に変えてほしい」と読めます。
半分はそうです。
IOC注文というものは証券会社が極めて短時間で約定するかどうか判断し、約定しなかったら即キャンセルするものだと思っていました。
その約定を待っている極めて短時間の間は、APIのレスポンスを返さないで待機してほしいという要望になります。

**Comment by yasuyuki-nakazawa** [comment]
お世話になります
@tsuchinaga 
コメントありがとうございます
@snowballrichdad 
記載いただいたとおり、IOCは取引所が処理しているものになります
注文時には対象のポジションや資金を拘束します
注文結果と残高処理は同期処理していません。
注文結果を受けて、約定処理、未約定の場合は注文拘束の解除を行っております
そのため、注文結果後即座に残高反映されることを保証することはできません
なお、カブステAPIとしては、カブステに反映された情報は即座にAPI経由で取得可能なものではありますが、カブステに反映されていない状態では当然のことながら最新情報を返すことはできない点はご理解頂けると幸甚です

**Comment by snowballrichdad** [comment]
＠yasuyuki-nakazawa
ご回答ありがとうございます。お話は分かりましたが、カブステのシステム本体とカブステAPIの同期タイミングの問題は、auカブコム証券さん内部の問題だと思いますので、今後のバックログ的な課題の1つとして改善を目指していただけると、kabuステーションAPIを利用される皆様にとりましてもよいかと思われます。

**Comment by snowballrichdad** [comment]
@yasuyuki-nakazawa 
 一旦クローズします
