### ISSUE TITLE
【質問】手数料について

### ISSUE THREAD

**Issue by tekunari** [kabucom/kabusapi#445]
お世話になります。
日経先物ミニの自動売買での手数料は、現在どのようになっていますでしょうか？
過去には月額8,000円程度の定額だったこともあるみたいですが、現在の手数料が出ているページを見つけることが出来ませんでしたので質問させて頂きました。
よろしくお願い致します。

**Comment by tsuchinaga** [comment]
これじゃないですかね？

https://kabu.com/item/fop/cost.html

**Comment by tekunari** [comment]
ご回答、有難うございます。
教えて頂いた手数料ですが、通常、手入力で取引した際と同じです。
昨年の日経先物は、↓のページのように月定額8,360円での手数料体系が用意されていたみたいなので、現在も株の信用取引のように有利な手数料体系を用意してくださっているのだろうかと思い、質問させて頂いた次第です。
https://www.kabu.com/company/pressrelease/20201026_1.html

**Comment by yasuyuki-nakazawa** [comment]
@tekunari 
先物の手数料に関してはご意見として承ります

**Comment by tekunari** [comment]
ご回答ありがとうございます。
同時に要望として、主要な指標である日経先物やドル円やユーロ円などの為替、日経平均だけでも最低10年程度の出来高を含むデータをAPIで読み込めるようにして頂きたいことを要望致します。
過去のデータが蓄積されていないために検証が難しくて困っています。

**Comment by yasuyuki-nakazawa** [comment]
@tekunari 
別スレッドでも回答させていただきましたが、過去分のデータ提供に関しては、取引所よりご購入いただくことが望ましいと考えます。
リアルではなく、蓄積データのAPI提供は現状はできない状況でございます。

**Comment by yasuyuki-nakazawa** [comment]
当件はクローズさせていただきます
