### ISSUE TITLE
【質問】{'Code': 4001007, 'Message': 'ログイン認証エラー'}

### ISSUE THREAD

**Issue by saru-da-mon** [kabucom/kabusapi#446]
HTTP Error 401: Unauthorized
{'Code': 4001007, 'Message': 'ログイン認証エラー'}

このエラーはTokenの期限切れなのか、当方の通信エラーなのか、どっちでしょうか？切り分けられますか？Tokenの有効期限はその日に発行したものは24時間有効なのか、教えていただきたい。

**Comment by tsuchinaga** [comment]
https://kabucom.github.io/kabusapi/ptal/error.html

> kabuステーションにログインしているかを確認してください。

kabuステーション自体でログインできているか確認する必要がありそうです。

Tokenはログアウトされるまで有効です。朝方に強制的にログアウトさせられるので、最長24時間程度有効ではありますが、24時間有効というわけではないです。

**Comment by saru-da-mon** [comment]
通信状態が回復してもログインし直さないとkabuステーション自体がログアウトされたものと認識されてTokenが無効になるんですね。ありがとうございます。外部サーバーを借りることにしました。

**Comment by yasuyuki-nakazawa** [comment]
瞬断であればログイン状態は継続されます
当該セッションの維持時間は記載できかねますが、tokenの有効確認で、再ログインを行う等をあわせてご検討ください

**Comment by yasuyuki-nakazawa** [comment]
こちらはクローズさせていただきます
