### ISSUE TITLE
【質問】webhook　を受け取って、その内容に応じて、カブコムで先物を発注できますか？

### ISSUE THREAD

**Issue by masaAppDev** [kabucom/kabusapi#448]
個人です。
TradingView から　webhook を受け取って、その内容に応じて、先物を発注したいです。

1.Appleの　Xcodeを使用し、iOSアプリ、もしくは mac PC向けのアプリとして、swift でコーディングしたいのですが、可能でしょうか？
カブコムAPIの実装は、言語の自由度が高いということですが、個人でも原理的に可能かどうか、お知らせください。

また、同様の内容で、
2.Android　のアプリも可能かどうか。

以上、２点について、よろしくお願いします。

**Comment by tsuchinaga** [comment]
kabuステーションAPIはWindows向けのkabuステーションの機能で、
kabuステーションAPIは名前の通りkabuステーションを操作するためのインターフェースです。
ということで、基本的にはWindows上での動作を前提とされているところが大きいです。
ただし、Windowsでkabuステーションを立ち上げたうえで、プロキシサーバを用意して他端末から操作する方法が他issueであげられています。

安全性はさておき、規約を遵守して自己責任でやる分には
1. 可能
2. 可能
です。

**Comment by masaAppDev** [comment]
回答ありがとうございます。

私が全く理解していなかったようです。
直接、カブコム証券と通信するのかと思っていましたが、kabuステーションを操作するためのAPIなのですね。
常に、PC・kabuステーションを起動しておく必要がありそうで、iOSやAndroidなどから操作するのは遠回りと分かりました。

自宅のWindowsでwebhookを受け取り、kabuステーションに通知する方向でやってみます。

**Comment by yasuyuki-nakazawa** [comment]
@tsuchinaga さんがコメントされている結論の通りです
推奨することはできかねますが、理論的には上記で対応することは可能ですね

**Comment by cyber-minion** [comment]
解決済のようですので、いったんクローズいたします。
