### ISSUE TITLE
【不具合】先物成行決済のオーダーが通らない{'Code': 1009001, 'Message': '建玉が選択されていません。'}

### ISSUE THREAD

**Issue by saru-da-mon** [kabucom/kabusapi#449]
■[必須] 不具合事象(概要)

■[必須] 本来想定されるアクションと事象
15:48:55.5088,I,5568,0008 KabuSApiManager.PreRelationCheck=ERROR_CD_001_009_001
■[必須] 不備発生時刻（常時の場合は、常時で記載ください)
常時
■[任意] お使いの環境(OS、Excelのバージョン等)、サンプル(Macro、アドインのバージョン）
■[任意] 不備部分のログ

**Comment by cyber-minion** [comment]
可能な範囲で結構ですので、実行したプログラムを共有いただけますでしょうか

**Comment by yasuyuki-nakazawa** [comment]
当スレッドは同一内容のIssueがありますので、クローズさせていただきます
https://github.com/kabucom/kabusapi/issues/450
