### ISSUE TITLE
【不具合】先物成行決済のオーダーが通らない{'Code': 1009001, 'Message': '建玉が選択されていません。'}

### ISSUE THREAD

**Issue by saru-da-mon** [kabucom/kabusapi#450]
■[必須] 不具合事象(概要)
def close_position(TradeType,Side):
    obj = { 'Password': Password,
            'Symbol': symbol,
            'Exchange': Exchange,  #2.日通し　23.日中　24.夜間
            'TradeType': TradeType,  #1.新規　2.返済
            'TimeInForce': 2,
            'Side': str(Side),  #1.売り 2.買い
            'Qty': Qty,
            'ClosePositionOrder': 0,
            'FrontOrderType': 120,
            'Price': 0,
            'ExpireDay': 0,
          }
    json_data = json.dumps(obj).encode('utf-8')
]（以下略・・・・・）

日経先物mini の建玉を成行決済しようとしてるのですが、
{'Code': 1009001, 'Message': '建玉が選択されていません。'}
というエラーが生じます

■[必須] 本来想定されるアクションと事象
？？？？
■[必須] 不備発生時刻（常時の場合は、常時で記載ください)
常時
■[任意] お使いの環境(OS、Excelのバージョン等)、サンプル(Macro、アドインのバージョン）
WindowsServer2016

■[任意] 不備部分のログ
15:48:05.0745,I,5568,0027 Recv Event Type=201,Account=,Value=
15:48:05.0745,I,5568,0027 MasterManager Recv NotifyEvent = Type=201,Account=,Value=
15:48:05.0745,I,5568,0027 OrderManager Recv NotifyEvent = Type=201,Account=,Value=
15:48:05.1057,I,5568,0027 UpdatePositions=ID=E202201040344P,Symbol=167030019,Exchange=2,Side=1,MarginTradeType=0,OpenQty=1,LeavesQty=1,HoldQty=0.0
15:48:05.1057,I,5568,0027 UpdatePosition=ID=E202201040344P,Symbol=167030019,Exchange=2,Side=1,MarginTradeType=0,OpenQty=1,LeavesQty=1,HoldQty=0.0
15:48:27.5465,I,5568,0001 NewsHeaders: count=5893
15:48:55.5088,I,5568,0008 KabuSApiManager.PreRelationCheck=ERROR_CD_001_009_001

HoldQty の値が0になってるのが気になりますが、、、、

**Comment by saru-da-mon** [comment]
あっ、ここに何か書いてますね
https://github.com/kabucom/kabusapi/issues/126

**Comment by saru-da-mon** [comment]
http://snowballrichdad.xyz/post-4511/
そういう問題でも無さそう

**Comment by saru-da-mon** [comment]
エクセルでもかあ？
https://www.giters.com/kabucom/kabusapi/issues/365

**Comment by saru-da-mon** [comment]
#126
が正しいとすると、私も売買逆に指定してますね🐒

**Comment by saru-da-mon** [comment]
それでもダメみたいです
![image](https://user-images.githubusercontent.com/91817714/148046040-52449f63-2387-40d4-a862-caae5a330a68.png)

**Comment by saru-da-mon** [comment]
お騒がせしました・・・解決いたしました

**Comment by hori-ryota** [comment]
@saru-da-mon 解決した場合は詳細を記載いただけると同様の症状が起きた場合にありがたいです（関係ないところのバグだったとしても、関係ないところのバグだったという結論はあると嬉しいです）

**Comment by saru-da-mon** [comment]
#126 同様、決済のSideを勘違いしておりました。これには理由があって決済の際に通知されるアナウンスでは、売って決済した場合「決済（買）」となっており紛らわしいです。これを逆にしてもダメだったというのは、Exchangeの値、日中と夜間を間違って試しておりました。申し訳ございません🐒。

**Comment by cyber-minion** [comment]
解決済のようですので、クローズいたします。
