### ISSUE TITLE
【質問】レンタルサーバーからkabuステーションapiで記述したスクリプトファイルを実行したいです

### ISSUE THREAD

**Issue by tkknot** [kabucom/kabusapi#454]
レンタルサーバーのCron設定を使って、
貴社apiを用いたファイルを実行しようとしたところ、
Failed to establish a new connection: [Errno 111] Connection refused
というメッセージが出ました。

PCのローカルのKabuステーションは起動させていましたが、
おそらくサーバー内にローカルホストという物自体が建てられないことが、
失敗原因なのかと考えております。
ですので、レンタルサーバーで貴社apiを用いたファイルの実行の可否が知りたいです。
（もし可能なら自分の勉強不足を明らかにすることになってしまいますが、、、）

**Comment by tsuchinaga** [comment]
localhost以外からの呼び出しは許可されていないですね

#34 が参考になると思います

**Comment by snowballrichdad** [comment]
Windowのレンタルサーバを使用し、そこにkabuステーションも動作させればいいのではないでしょうか。Linuxのレンタルサーバよりは少し割高ですが。
