### ISSUE TITLE
【質問】IOC注文ってAPIが復帰しても、取引所で処理が終わってないことがあるのでしょうか？

### ISSUE THREAD

**Issue by snowballrichdad** [kabucom/kabusapi#455]
IOC注文ってAPI復帰時には約定かキャンセルが決まっているものかと思いましたが、そうではないのでしょうか？
【現象】
IOC注文をして、残高照会をしたら建玉が残っているようだったので、注文が約定せずキャンセルされたと判断し(実際にキャンセルされていました)、PUSH APIで次のTickを受信したのちに再度同じ注文をしました。
そうすると、APIの復帰値が
`{'Code': 8, 'Message': '決済指定内容に誤りがあります'}`
という内容でした。

※捕捉
#444 でIOC注文がAPI復帰と同時に残高照会に反映されない旨を質問させていただきました。
その際は、取引所が注文→約定した結果がカブステに反映されるまでにタイムラグがあるかと思いましたが、
どうも、取引所側で、IOC注文であっても、注文受付→約定までの間にタイムラグがあるような気がしました。
つまり、IOC注文は板に表示されず、注文受付→約定までの期間がかなり速いが、本当に即時であるわけではないと。

-追記
上記のエラーが出る前のIOC注文の結果を注文約定照会の詳細画面で見ると
「発注所要時間」という欄が追加されており、「769ミリ秒」と表示されていました。
この発注所要時間中に前のAPIが復帰し、次のAPIを発行したため上記のエラーになるように推察されます。
この発注所要時間がauカブコム証券さん側で所要しているものであれば、その間はIOC注文のAPIが復帰しないようにしていただけると大変助かります。
逆に取引所側で、証券会社から発行されるAPI的なものが復帰したあとで所要しているのであれば、auカブコム証券さん側としては致し方ないと思いますが。

--再追記
https://kabu.com/company/info/2009/arrowhead.html
を見ると、発注所要時間について
> 当社システムにて発注を受け付けてから取引所へ注文を送信完了するまでの時間です。

とありましたので、auカブコム証券さん側で所要している時間のように見えますね。
すみません、まとめてから書けばよかったですが、本件質問ではなく、要望である可能性が高いです。

**Comment by yasuyuki-nakazawa** [comment]
残高照会や注文約定照会に反映されないという点に関して、以下のスレッドで記載させていただいた通り、
過去に内包された不具合が影響している可能性があり、ご連絡させていただきます
https://github.com/kabucom/kabusapi/issues/456

現在は、当不具合に関しては改善されております。
再度お試しいただけますでしょうか

**Comment by snowballrichdad** [comment]
@yasuyuki-nakazawa 
ご連絡ありがとうございます。次にシステムが動く機会がありましたら確認してみます。

**Comment by snowballrichdad** [comment]
@yasuyuki-nakazawa 
残念ながら直ってませんでした。

**Comment by yasuyuki-nakazawa** [comment]
IOC注文ですが、取引所側の条件注文となります。
対当する注文が板上になければ、即座にキャンセルとなり、対象がある場合は約定となります。
しかしながら、注文結果と残高反映は別処理となります。
基本的に取引所は発注された注文をもとに正常に注文が受注された際に注文結果（OKとして）をレスポンスしますが、
その時に約定処理/取消処理が完了したということを保証するものではございません

注文約定照会より、対象の注文が取り消しされたのか、約定されたのかご確認いただく必要がございます。
残高照会への反映に関しては、カブステーション側の残高が更新されている場合は、API経由でも最新の状態が取得できます。
当APIではあくまでもカブステーションのインターフェースであるため、カブステーション側の情報更新が未完ですと、レスポンス内容も最新状態でないという点はご了承くださいませ

**Comment by snowballrichdad** [comment]
@yasuyuki-nakazawa
そうなんですか。取引所がレスポンスを返しても、その時に約定処理/取消処理が完了したということを保証してないんじゃ、auカブコム証券さんではやりようがありませんね。
東証も世界のHFTとかで世界の取引所に負けないようにarrow head導入して、IOC注文サポートしたのかと思っていましたが、その仕様じゃ発注側のクライアントはいつまで待てばよいかわからず、高速取引できないですね。やれやれですね。
何度も丁寧にご回答ありがとうございました。
