### ISSUE TITLE
【不具合】注文の約定情報が更新されない

### ISSUE THREAD

**Issue by tsuchinaga** [kabucom/kabusapi#456]
## 不具合事象(概要)
現値的に約定しているはずの指値注文が約定せず、kabuステーション上でも未約定状態のままになっている

## 本来想定されるアクションと事象
常に最新の注文情報がkabuステーションに反映される

## 不備発生時刻（常時の場合は、常時で記載ください)
該当注文が約定した 2022-01-07T14:03:05.816538+09:00 から、
少なくとも次の同一銘柄の他の注文が約定した 2022-01-07T14:07:57.114932+09:00 まで。
この間はフル板発注機能で目視でも確認できており、最良値とは2, 3ティックほど離れている注文が残っている状態でした。

目視での確認ができていませんが、注文を取り消そうとした 2022-01-07T14:58:00+09:00 まで発生していた可能性があり、
注文を取り消そうと取消注文を送信した際に、約定済みの注文であるとエラーが返されて状態が更新されたように見えます。

## 備考
2週間に1度くらいのペースで発生している印象です。
kabuステーション自体に約定情報を含む最新の注文情報が落ちてきていないため、
kabusapiでも約定情報が取れていない状況だと思われます。

発生タイミングはkabuステーションが固まっているタイミングで、
同時に約定した注文が多いタイミングに、
銘柄のチャートを切り替えたりすると発生しやすいように感じます。

その際には、普段のCPU使用率が0.1%のところ、5% - 12%ほどに増え、
普段の通信量が0.1Mbpsのところ、10Mbps - 20Mbpsほどに増えます。
メモリ使用量は変わりません。
この状態は5秒 - 10秒ほど続き、その間はkabuステーションが操作できなくなり、
その状態でクリックなどすると、マウスカーソルがぐるぐるの状態になり応答なしとなります。

復帰時には一度タスクバーから消えすぐに表れるという挙動をします。
プロセスIDは変わっていないので、再起動というわけではなさそうです。

この事象によりデイトレ信用のポジションを決済できなくなっています。
ご確認のほどよろしくお願いします。

**Comment by tsuchinaga** [comment]
APILogを確認しました

引け後にAPIで注文情報を取得した際には、該当注文のDetailsの最後には約定済みのデータが入っていました

```
{"SeqNum":5,"ID":"20220107E02N87984471","RecType":8,"ExchangeID":"1149","State":3,"TransactTime":"2022-01-07T14:03:05.816538+09:00","OrdType":0,"Price":2048.0,"Qty":3.0,"ExecutionID":"E202201070305Y","ExecutionDay":"2022-01-07T14:03:05.816538+09:00","DelivDay":20220112,"Commission":0.0,"CommissionTax":0.0}
```

このことから、2022-01-07T14:03:05.816538+09:00時点で約定していることが確認できます。

2022-01-07T14:07:59.6969+09:00に確認した該当注文のDetailsの最後には発注済みのデータが入っていました。

```
{"SeqNum":4,"ID":"20220107B02N87984382","RecType":4,"ExchangeID":"1F111000014814","State":3,"TransactTime":"2022-01-07T14:02:00.774514+09:00","OrdType":1,"Price":2048.0,"Qty":3.0,"ExecutionID":null,"ExecutionDay":null,"DelivDay":20220112,"Commission":0.0,"CommissionTax":0.0}
```

**Comment by cyber-minion** [comment]
「2週間に1度くらいのペースで発生」とありますが、一番最初発生したのはいつ頃だったのでしょうか。

**Comment by tsuchinaga** [comment]
うろ覚えではありますが、12月の中旬だったと記憶しています。
そのあと、12月の下旬、先週末と発生し、合計3回確認しています。

**Comment by yasuyuki-nakazawa** [comment]
当件調査、対応いたしましたことをご報告いたします。
Ver5.16.0のカブステにおいて、残高、注文等の情報取得タイミングが不正となっていることが判明いたしました。
本件は2022年1月7日22:38に改善済みです。
サーバー側での修正となりますので、カブステーションの更新等は不要でございます。
ご迷惑をおかけし申し訳ございません

**Comment by tsuchinaga** [comment]
ご対応、ご連絡ありがとうございます。
修正済みであること承知しました。

手元で確認できた事象として、過去3回あったとご報告させてもらいましたが、
本件の約定情報が落ちてこないことのログが取ったのは今回だけで、
その前の2回が同一の原因かは不明であるため、このissueはcloseします。
