### ISSUE TITLE
【質問】過去のデータについて

### ISSUE THREAD

**Issue by tekunari** [kabucom/kabusapi#458]
主要な指標である日経先物やTOPIX先物、マザーズ先物、ドル円やユーロ円などの為替情報だけでも1分足、3分足、５分足、10分足、日足などの最低10年分程度の出来高を含むデータを.csvで取得できるようにして頂きたいことを要望致します。
過去のデータが少ししか蓄積されていないために検証が難しくて困っています。

**Comment by yasuyuki-nakazawa** [comment]
各情報配信元との情報配信契約にかかわる部分が多分にございますので、データとしてご提供する形をとるためには検討のお時間を頂きます。
過去データに関しましては、取引所から購入する手段もございますので、お急ぎの場合は当該手段も検討していただければと存じます。

**Comment by yasuyuki-nakazawa** [comment]
カブステーションAPIの現状としては蓄積データを提供することはできません
過去分10年分等の蓄積データを当社側からご提供することはできませんので、過去蓄積データに関しては取引所よりご購入の程、よろしくお願いいたします。

**Comment by tekunari** [comment]
こちらのサイトから無料で取得できました。
有難うございました。
https://225labo.com/

**Comment by yasuyuki-nakazawa** [comment]
こちらは、クローズさせていただきます
