### ISSUE TITLE
【質問】レギュレーションについて

### ISSUE THREAD

**Issue by kouhey0427** [kabucom/kabusapi#46]
本APIを利用したシステムを自作する場合は問題ないかと思うのですが、
本APIを利用した自作の自動売買システムを他社に販売することについて、御社の許可が必要というレギュレーションはあるのでしょうか？
法人によるAPI契約は審査等がおありの様ですが、伺えたら幸いです。

**Comment by yasuyuki-nakazawa** [comment]
レギュレーションに関してのお問い合わせについては、auカブコム証券サポートに問い合わせください。
kabuステーションAPIの利用規定上では３条1７項にて第三者の作成されたプログラム等の利用を禁じております。
当該APIを利用した自動売買システムの販売に関しては、お控えいただくようお願いいたします
