### ISSUE TITLE
【質問】約定番号について

### ISSUE THREAD

**Issue by tetsuji0211** [kabucom/kabusapi#460]
カブコムAPIを使って高速なトレードを実現したいと考えています。今のところは、Excel　サンプル + VBAで構築しています。

概ね良好な動作ですが、約定番号が取得できるまでに時間を要しました。
遅い時では5分以上かかる場合もありました。

今後は、C#で構築していこうと考えています。
構築する前に、注文約定情報シートで得られた実際の結果をもとに質問させてください。
～～～ここから～～～
通番　　　明細種別　市場コード　　　状態　 処理時刻　　　　　　　　　　　　　　　約定番号
1　　　　　1　　　　　　　　　　　　　3　　　2022-01-11T14:53:22.690739+09:00
4　　　　　4　　　　1F111700015595　3　　　2022-01-11T14:53:22.712024+09:00
5　　　　　8　　　　39402　　　　　 　3　　　2022-01-11T14:53:32.294371+09:00　　E20220111xxxxx
～～～ここまで～～～
//見にくいですがご容赦ください。

１．Excelのデータの種類について
　エクセルの「注文約定情報」結果のうち次の項目の意味が不明でした。教えてください。
　通番（何故、連続番号ではないのでしょうか？）
　明細種別
　市場種別
　状態

　入力値には説明がありますが、出力値についても説明があるとありがたいです。

2. この時は、約定後シートの再計算や関数のコピー&ペーストを繰り返したのですが、なかなか約定番号が表示されませんでした。
　この情報からは14:53:22～32の間に約定したと思います。しかし、約定番号が表示されたのが15時過ぎと記憶しています。

　約定タイミングと処理時刻の関係が分かりませんが、こんなものなのでしょうか？
　約定番号を出すタイミングと処理時刻が合っていないのでしょうか？
　こちらのインターネット回線やネットワークの混雑状況にもよりますが、そもそも高速取引は避けた方が良いのでしょうか？
　'エクセルだから、仕方ない面もあるのでしょうかね？

**Comment by tetsuji0211** [comment]
追記です。
約定番号が戻って来ないときに再計算を実行したら、エクセルが固まっていなかったので、値は戻ってきてると思います。この時の戻り値は、通番　1と4が得られ、5は得られませんでした。

**Comment by yasuyuki-nakazawa** [comment]
カブステAPIのリファレンスに記載がございます
注約照会であれば、Responseの200:OKの中からドリルダウンしていただき、さらに、詳細の方を展開いただければ、ご確認いただけるかと思います

**Comment by tetsuji0211** [comment]
ご回答ありがとうございます。
リファレンス拝見しました。

通番（1, 4, 5）や明細種別（1, 4, 8）に対応したリファレンス中のアイテムが不明です。

状態はすべて「3」でした。状態はStateに相当していると考えます。このデータの羅列から、最初の行は私からの発注、2番目の行は貴社から市場への発注と推測すると、Stateの「処理済（発注済・訂正済）」は適切と思います。しかし、約定完了後の3行目は「3」ではなく、「5」の「終了（発注エラー・取消済・全約定・失効・期限切れ）」が正しいと思いますが、いかがでしょうか？

また、リファレンスでは市場コードが1桁あるいは２桁の数値と記されています。しかし、戻り値は3桁以上の数字と文字になります。何故違うのでしょうか？

約定番号が遅い件についても、ご回答いただけると幸いです。

また、最初の質問で少し書きすぎた点がありました。申し訳ありません。

**Comment by cyber-minion** [comment]
こちらで確認してみましたが、再現されませんでしたので、事象についてお伺いさせてください。

> この時は、約定後シートの再計算や関数のコピー&ペーストを繰り返したのですが、なかなか約定番号が表示されませんでした。
> 　この情報からは14:53:22～32の間に約定したと思います。しかし、約定番号が表示されたのが15時過ぎと記憶しています。

当該注文の約定日時のセル（約定番号の右側）で表示された時刻はいつでしょうか。



> 状態はすべて「3」でした。状態はStateに相当していると考えます。

こちらの「状態」は、リファレンスの「Details」中にある「状態」でしょうか。



> リファレンスでは市場コードが1桁あるいは２桁の数値と記されています。しかし、戻り値は3桁以上の数字と文字になります。

3桁以上の数字と文字に関しては、具体的に何と書いていますでしょうか。

**Comment by tetsuji0211** [comment]
> > この時は、約定後シートの再計算や関数のコピー&ペーストを繰り返したのですが、なかなか約定番号が表示されませんでした。
> 　この情報からは14:53:22～32の間に約定したと思います。しかし、約定番号が表示されたのが15時過ぎと記憶しています。
> 
> 当該注文の約定日時のセル（約定番号の右側）で表示された時刻はいつでしょうか。

ログが残っていないため正確な時刻は不明です。15:02~03くらいに表示されたと記憶しています。

> > 状態はすべて「3」でした。状態はStateに相当していると考えます。
> 
> こちらの「状態」は、リファレンスの「Details」中にある「状態」でしょうか。

リファレンスの[GET 注文約定照会](https://kabucom.github.io/kabusapi/reference/index.html#operation/ordersGet) -> Query ParametersのStateを示していると考えていました。


> > リファレンスでは市場コードが1桁あるいは２桁の数値と記されています。しかし、戻り値は3桁以上の数字と文字になります。
> 
> 3桁以上の数字と文字に関しては、具体的に何と書いていますでしょうか。

質問の中に記載しています。「1F111700015595　」や「39402」になります。

**Comment by tetsuji0211** [comment]
エクセル上のAPIの状態について、何となくわかってきました。
エクセルの記載とkabu_STATION_API.yamlの間で違いがあるため混乱しているのだと思います。
エクセルの「注文約定照会」シート記載
「1	待機（発注待機）	
2	処理中（発注送信中）	
3	処理済（発注済・訂正済）	
4	訂正取消送信中	
5	終了（発注エラー・取消済・全約定・失効・期限切れ）	」

kabu_STATION_API.yamlの記載
「
                            <td>1</td>
                        <td>待機（発注待機）</td>
                            <td>2</td>
                            <td>処理中（発注送信中・訂正送信中・取消送信中）</td>
                            <td>3</td>
                            <td>処理済（発注済・訂正済・取消済・全約定・期限切れ）</td>
                            <td>4</td>
                            <td>エラー</td>
                            <td>5</td>
                            <td>削除済み</td>
」
たぶん、yamlが正しいのだと思いますが如何でしょうか？

**Comment by cyber-minion** [comment]
質問の中に記載いただきましたデータは、「注文詳細」に該当するものかと思います。
「注文詳細」は、[注文約定照会](https://kabucom.github.io/kabusapi/reference/index.html#operation/ordersGet)→Responses→Details配下のものになります。
その中、State（状態）の「3」は「処理済（発注済・訂正済・取消済・全約定・期限切れ）」ですので、状態はすべて「3」で問題ないかとおもいます。
また、ご指摘の「Query Parameters」は、注文約定照会を呼び出すための設定条件ですので、Responses/レスポンスとは別物になります。

> ～～～ここから～～～
> 通番　　　明細種別　市場コード　　　状態　 処理時刻　　　　　　　　　　　　　　　約定番号
> 1　　　　　1　　　　　　　　　　　　　3　　　2022-01-11T14:53:22.690739+09:00
> 4　　　　　4　　　　1F111700015595　3　　　2022-01-11T14:53:22.712024+09:00
> 5　　　　　8　　　　39402　　　　　 　3　　　2022-01-11T14:53:32.294371+09:00　　E20220111xxxxx
> ～～～ここまで～～～

**Comment by yasuyuki-nakazawa** [comment]
当件に関しましては、ご回答済みということでクローズさせていただきます

**Comment by tetsuji0211** [comment]
エクセル上で約定番号が表示されるまでに5分以上要する件は、カブコムさんで 
再現せず原因は不明だった、ということでしょうか？
私の方のログ等は提出できますが、特段これまで求められていません。

なんとなく終息って感じで気持ち悪くてメールしています。
