### ISSUE TITLE
【不具合】返済済の銘柄が残高照会で保有中として出力される

### ISSUE THREAD

**Issue by ksayo** [kabucom/kabusapi#463]
■[必須] 不具合事象(概要)
javascriptでwindow.onloadで５分ごとにpositionsを取得して返済処理を行っています。
返済済の銘柄が、残高照会で取得すると、保有中として出力され続けてしまいます。

カブステの画面上では、正常に返済済の銘柄は残高として表示されません。
javascriptでpositionsを取得すると、返済済の銘柄も保有中として出力されます。

ブラウザ（Chrome）のキャッシュなのかなと思って、キャッシュ無効化設定やシークレットモードにして検証しても、この事象になります。
カブステを手動で終了して、再起動すると、返済済の銘柄はjavascriptで出力されなくなり、正常になります。
そして再び別の銘柄を取引をして返済後、そのまま返済後の銘柄が保有中として出力され続けるので、手動でカブステを再起動することを繰り返します。
カブステを再起動しなければ、何時間でも保有中のまま出力され続けます。
ブラウザのキャッシュは無関係で、カブステを再起動すると解消することから、カブステの不具合ではないかと思いました。

返済済になるたびにカブステの再起動やトークンエラーなどの処理を手動で行わねばならず、とても苦痛です。なんのためにプログラム組んだんだかわかりません。
ご確認お願いします。

■[必須] 本来想定されるアクションと事象
返済済の銘柄はpositionsで出力されないでほしい

■[必須] 不備発生時刻（常時の場合は、常時で記載ください)
常時

■[任意] お使いの環境(OS、Excelのバージョン等)、サンプル(Macro、アドインのバージョン）
Windows10　お名前.comリモートデスクトップクラウド
javscript
ブラウザ：Chrome

■[任意] 不備部分のログ

■コード
`getPositions(apikey).then(data => {
    console.log(data);
  })`

`function getPositions(apikey){
  var url = new URL('http://localhost:18080/kabusapi/positions');
  url.searchParams.append('addinfo', 'true');

  return fetch(url, {
    method: 'GET',
    headers: {
      'Content-Type': 'application/json',
      'X-API-KEY': apikey,
    }
  })
    .then(response => {
      if (response.ok) {
        console.log(response.status, response.statusText);
        for (var pair of response.headers.entries()) {
           console.log(pair[0] + ': ' + pair[1]);
        }
        return response.json().then(data => {
          return data;
        });
      } else {
        console.log(response.status, response.statusText);
      }
    })
    .catch(e => {
      console.log(e.message);
    });
}`

■備考
↓で修正済とのことですが、現在でも不具合があるように思います。
https://github.com/kabucom/kabusapi/issues/456#
＞Ver5.16.0のカブステにおいて、残高、注文等の情報取得タイミングが不正となっていることが判明いたしました。
＞本件は2022年1月7日22:38に改善済みです。

１２月中頃から、時々このような事象があるなー？と思っていたら、1月7日ころから確実にこの事象が起きるようになり、とても困っています。
ご確認よろしくおねがいします。

**Comment by yasuyuki-nakazawa** [comment]
確認いたします。
記載いただいたバージョンにて、事象の改善を確認しておりますが、再確認いたします

**Comment by cyber-minion** [comment]
#124 と似たような事象でしょうか

**Comment by ksayo** [comment]
#124 と全く同じ内容です。
仕様である旨承知いたしました。
確認不足で大変申し訳ございません。
LeavesQtyを確認いたします。
