### ISSUE TITLE
【要望】PUSH APIを複数クライアント(同一マシン複数プロセス)で受信できるようにしてほしい

### ISSUE THREAD

**Issue by snowballrichdad** [kabucom/kabusapi#465]
現在、kabuステーションAPIのPUSH APIはlocalhostのWebSocketサーバに対して、WebSocketクライント1つに対してのみConnectionが張れるかたちになっているのではないかと推察しています(2つめのクライアントを接続すると1つめのクライアントがフリーズしてしまうので)。
例えば、複数銘柄でトレードを行う場合などに、複数プロセスでkabuステーションAPIを使用したいと考えているのですが、PUSH APIで情報を取得するのが1プロセスに限定されると、スレッド間の情報の受け渡しなどをしなければならなくなり、プログラミングが難しくなってしまいます。
可能であれば、kabuステーションが起動しているマシンと同一マシンであれば、複数プロセスのWebSocketクライアントからの接続ができるようにしていただけませんでしょうか
(配信される情報を各プロセスで取捨選択することは難しくないので、登録銘柄は共通でかまいません)

**Comment by yasuyuki-nakazawa** [comment]
少々、調査してご回答させていただきます

**Comment by cyber-minion** [comment]
現状、kabuステーションAPIとしては、localhostのみ対応としていますので、複数クライアントでの受信は不可となります。
また、WebSocketは、１本のみ有効としているので、複数プロセスは不可となります。
