### ISSUE TITLE
【質問】注文約定照会レスポンスのStateとOrderStateについて

### ISSUE THREAD

**Issue by genbu-jp** [kabucom/kabusapi#466]
注文約定照会HTTP200レスポンスについてペイロードのStateとOrderStateはどのような違いがあるのでしょうか。
また、部分約定した場合の状態はそれぞれどの定義値となるのかご教授いただきたく思います。

**Comment by cyber-minion** [comment]
特に違いがございません。 #1 , #75 も合わせてご確認いただければと思います。

**Comment by cyber-minion** [comment]
一部約定については、CumQty/約定数量をご確認いただければと思います。

**Comment by sanwa-starch-koji-yamaguchi** [comment]
ご返答ありがとうございました。
確認不足で申し訳ありませんでした。とても助かりました。

**Comment by yasuyuki-nakazawa** [comment]
補足します
stateは注文の最新状態を示します
一方、orderstateは注文明細毎の状態を示します
基本的には同じ値が設定されます

**Comment by cyber-minion** [comment]
新規注文の場合は建玉IDが異なります。

**Comment by shujiji** [comment]
ご返信有難うございます。

つまり、「単一の注文が何回に分かれて一部約定を繰り返したとしても、各約定における建玉IDは同一である」ということで相違ございませんでしょうか？

システム的な質問に言い換えると、「http://localhost:18080/kabusapi/orders の"Details"に複数の辞書が入っていた場合、各辞書における"ExecutionID"は同一である」と言うことで相違ございませんでしょうか。


=====　補足　=====
新規注文ではなく、単一の注文において一部約定した場合について伺っております。（言語はPythonです）

ユーザー目線の具体例としては、
1)1,000株を1,000円で買い注文
2)一瞬WebsocketのAskPriceが1,000円まで下落。1で発注した1,000株の内500株だけが約定　
3)株価が上がる（この時点ではPositionのLeavesQtyは500。Ordersは恐らく、"OrderQty"が500で"Details"には2で約定した500株に係る建玉ID等が入っている？）
4)再びAskPriceが1,000円まで下落。1で発注した残りの500株が約定

上記例において、2及び4での2つの約定をordersの"Details"から確認した場合、対応する2つの辞書が入っているものと推察しますが、それらの辞書の"ExecutionID"は互いに異なりますか、という質問です。

**Comment by cyber-minion** [comment]
> つまり、「単一の注文が何回に分かれて一部約定を繰り返したとしても、各約定における建玉IDは同一である」ということで相違ございませんでしょうか？

いいえ、建玉IDは異なります。

> 上記例において、2及び4での2つの約定をordersの"Details"から確認した場合、対応する2つの辞書が入っているものと推察しますが、それらの辞書の"ExecutionID"は互いに異なりますか、という質問です。

はい、2と4で約定したExecutionID(=建玉ID)は、異なります。

**Comment by shujiji** [comment]
> はい、2と4で約定したExecutionID(=建玉ID)は、異なります。

了解しました、ご回答を有難うございます。
