### ISSUE TITLE
【質問】リアルタイム株価予測について

### ISSUE THREAD

**Issue by mayamaya07** [kabucom/kabusapi#468]
初めまして。カブコムAPIで株の自動売買デビューいたしましたプログラミング初心者です。
質問なのですが、リアルタイム株価予測の値をAPIで取り込むにはどうすればいいのでしょうか？
それともまだ開放されていないのでしょうか？
お詳しい方宜しくお願い致します。

**Comment by yasuyuki-nakazawa** [comment]
リアルタイム株価予測のインターフェースご提供が遅れておる状況です。
当機能の公開まで今しばらくお待ちくださいませ

**Comment by mayamaya07** [comment]
ご回答ありがとうございました。
どうぞよろしくお願いいたします。

**Comment by cyber-minion** [comment]
いったんクローズさせていただきます。
