### ISSUE TITLE
【質問】プレミアム料金取得APIについて

### ISSUE THREAD

**Issue by zmp365** [kabucom/kabusapi#469]
お世話になっております。
#370 によると、プレミアム料金取得APIは昨年末リリース予定となっておりましたが、進捗状況を教えてください。

**Comment by cyber-minion** [comment]
お待たせいたしました。当該機能は今週末（予定）のリリースにて提供させていただきます。
詳細につきましては、 #471 をご確認いただければと思います。

**Comment by zmp365** [comment]
#471 確認しました。　リリース有難うございます！！
本件はクローズさせていただきます。
