### ISSUE TITLE
【質問】Excelサンプルファイルの注文発注(現物)シートでエラー　'{"Code":4001005,"Message":"パラメータ変換エラー - 詳細はkabuSログファイルを確認してくだ

### ISSUE THREAD

**Issue by poyoji3** [kabucom/kabusapi#47]
サンプルファイルをダウンロードし、発注ボタンを押下すると、

下記エラーが発生します。

{"Code":4001005,"Message":"パラメータ変換エラー - 詳細はkabuSログファイルを確認してください"}

サンプルファイル名は、kabuSTATION_API_ORDER_sample.xlsm

受け渡し区分や、預かり区分などのパラメーターも変更して複数回試してみましたが、結果に変化はありませんでした。

銘柄コード、注文価格　の書式を数値に変更。
有効期限の書式をyyyymmddに変更等も実施しまたが、同じエラーが表示されています。

「詳細はkabuSログファイルを確認」このkabuSログファイルの所在も分からなかったので、内容は確認出来ていません。

対処方法をご教示いただきたく。

![20200829apiQ](https://user-images.githubusercontent.com/70047934/91628027-d3088900-e9f6-11ea-9844-8ade25c99254.JPG)

**Comment by hirocha** [comment]
【質問】kabuSログファイルはどこに出力されますか？ 
https://github.com/kabucom/kabusapi/issues/11

**Comment by poyoji3** [comment]
hirochaさん
既出の質問をしてしまいました。　ご指摘ありがとうございます。

ログを確認する事が出来ました。

**Comment by poyoji3** [comment]
kabuSログファイルの内容は以下でした。

気になる点は、Excelの　K列「注文有効期間」に入力している期日が、

2020年8月31日に対して、
ログでは"ExpireDay":"2020-08-30T15:00:00Z"　となっている点です。

Excelのセル内容を2020年9月1日に変更したところ
ログでは"ExpireDay":"2020-08-31T15:00:00Z"　となっていました。


エラーも解消されていません。


以下ログの内容＝＝＝＝＝＝＝
14:56:41.0989,I,8484,0007 【SendOrder】({"Password":"****************","Symbol":"1570","Exchange":1,"SecurityType":1,"Side":"2","CashMargin":1,"DelivType":0,"FundType":"  ","AccountType":2,"Qty":1,"Price":23450,"ExpireDay":"2020-08-30T15:00:00Z","FrontOrderType":10})
14:56:41.0999,I,8484,0007 【SendOrder】({"Code":4001005,"Message":"パラメータ変換エラー - 詳細はkabuSログファイルを確認してください"})

**Comment by yasuyuki-nakazawa** [comment]
リファレンスの発注部分を確認いただきながら設定いただく事をおすすめします。
画像を見る限り、預かり区分の指定がないようです。
リファレンス上ですと、こちら必須となっております

**Comment by poyoji3** [comment]
yasuyuki-nakazawaさん

ありがとうございます。

リファレンスの発注部分をもう一度見直してみたいと思います。

**Comment by poyoji3** [comment]
リファレンスの発注部分を読み返し、再度試しました。

ダウンロードしたサンプルファイル（kabuSTATION_API_ORDER_sample.xlsm）に各項目を再入力しましたが、同じエラーが返ってきます。

エラーメッセージに「パラメータ変換エラー」とありましたので、**数値**の入っているセルはExcelの書式設定で**数値**に設定しています。

セル番地Ｋ８にはExpireDay（注文有効期限）を入力していますが、
リファレンスに「yyyyMMdd形式」と記載がありましたので、こちらもExcelの書式設定でyyyyMMddに変更済み。
※Excelの書式設定でyyyy**MM**ddと入力しましたが、後に再度書式設定を見るとyyyy**mm**ddとMMが小文字に戻っていました。この影響はあるのでしょうか？



エラーログを見るとExpireDayの部分は下記となっています。

"ExpireDay":"2020-08-31T15:00:00Z"

Excelのセル番地Ｋ８（ExpireDay入力セル）へ入力した期日は20200901ですが、エラーログの"ExpireDay"は"2020-08-31T15:00:00Z"このように、期日が前日の8月31日となりT15:00:00Zが追記されています。

私の理解した範囲では、レファレンスの説明と異なる部分は、上記"ExpireDay"の書式だけでした。
（現物の発注に必須なパラメーターは揃っていると思っています。違うかな？）



ａｕカブコム証券さん公式のサンプルファイルをそのまま使っており、VBAコードの改変も行っていません。

なお、セル番地Ｋ８への入力は、INT関数を使い小数点以下を省いています。（時間の部分を削除する意図）



Excelのバージョンは2019を使用しました。
PCのパワーも十分なはずです。
CPU：AMD Ryzen 7 3700X (3.6GHz-4.4GHz/8コア/16スレッド)
メインメモリ：32GB 


困りました。


下は、使用したサンプルシートの画面イメージ
![20200829apiQ-2](https://user-images.githubusercontent.com/70047934/91639535-3b388880-ea52-11ea-9594-e3d6518467ca.JPG)




以下エラーログ＝＝＝＝＝＝＝

23:40:50.8389,I,8484,0007 【SendOrder】({"Password":"****************","Symbol":"1570","Exchange":1,"SecurityType":1,"Side":"2","CashMargin":1,"DelivType":2,"FundType":"02","AccountType":2,"Qty":1,"Price":19980,"ExpireDay":"2020-08-31T15:00:00Z","FrontOrderType":20})
23:40:50.8399,I,8484,0007 【SendOrder】({"Code":4001005,"Message":"パラメータ変換エラー - 詳細はkabuSログファイルを確認してください"})

**Comment by hirocha** [comment]
すでに試されていたらすみません。
東証1部の8306とか7182といった株式銘柄でいかがでしたか？
預り区分は3つの選択肢それぞれ設定していかがでしたか？

**Comment by yasuyuki-nakazawa** [comment]
excelの書式設定が原因だと思われます
ここを文字列か数値にしてお試し下さい
エクセルの書式は表示変更のみですので、本来の数値型を日付型に変更してしまったことが原因だと思われます

**Comment by poyoji3** [comment]
hirochaさん
yasuyuki-nakazawaさん

ありがとうございます。

注文有効期限の「日付の書式を文字列」に変え、（20200902この形式でセルに入力）
預かり区分を「保証金代用」に変えたら注文が繋がりました。

Excelの書式では無く素直にyyyymmddの数字を入力すればよかったのですね。
ちなみにExcelの書式は「数値」「文字列」どちらでも注文が通りました。
