### ISSUE TITLE
【不具合】複数建玉IDをIOC指値返済で一部約定した後、建玉IDごとの残positions数が実際と異なる値になってしまい、次の注文に失敗することがある

### ISSUE THREAD

**Issue by snowballrichdad** [kabucom/kabusapi#470]
■[必須] 不具合事象(概要)
複数注文IDをIOC指値返済で一部約定した後、建玉IDごとの残positions数が実際と異なる値になってしまい、次の注文に失敗することがある
■[必須] 本来想定されるアクションと事象
以下、KabuS\Logの内容です
1. kabuステーションAPIから130口の建玉を返済した1回目のIOC指値注文
Qty=130.0 ClosePositions=[ID=E20220126013RW,Type=1,**Qty=60**|ID=E20220126013RX,Type=1,**Qty=70**|]
2. 40口だけ約定したので、次の注文
Qty=90.0 ClosePositions=[ID=E20220126013RW,Type=1,**Qty=60**|ID=E20220126013RX,Type=1,**Qty=30**|]
そうすると、エラー
発注結果 : Result=8,ID=,ClOrdID=,Detail=,ResultMessage=[Key=KC_CommissionTable/Value=1200,]
3. しょうがないので成行で手動で決済したときのログ
Qty=90.0 ClosePositions=[ID=E20220126013RW,Type=1,**Qty=20**|ID=E20220126013RX,Type=1,**Qty=70**|]

kabuステーションAPIで返済発注したときの建玉IDごとの建玉数は自動で指定されるのですが、
どうもその計算が実際と異なるようです。

とりあえず、ClosePositionOrder指定に切り替えて回避を試みます。
ただ、それで上手くいったとしても、同一銘柄で複数プログラムで異なる戦略でトレードする場合は困ってしまいます。

■[必須] 不備発生時刻（常時の場合は、常時で記載ください)
2022/1/26 09:59:32
■[任意] お使いの環境(OS、Excelのバージョン等)、サンプル(Macro、アドインのバージョン）
■[任意] 不備部分のログ

**Comment by cyber-minion** [comment]
現在確認中ですので、少々お時間いただけたら幸いです。

質問の中にあった２番の発注数量と３番の決済した数量が異なることから、注文時の数量指定の問題かと考えております。
Qty=90.0 ClosePositions=[ID=E20220126013RW,Type=1,Qty=**60**|ID=E20220126013RX,Type=1,Qty=**30**|]
Qty=90.0 ClosePositions=[ID=E20220126013RW,Type=1,Qty=**20**|ID=E20220126013RX,Type=1,Qty=**70**|]

**Comment by snowballrichdad** [comment]
よろしくお願いします。
こちらりプログラムでは、1番目、2番目でQtyは130→90に変更していますが、
ClosePositionsは、1番目、2番目ともに
```
"ClosePositions":[
    {"HoldID": "E20220126013RW","Qty":70},
    {"HoldID": "E20220126013RX","Qty":60}
]
```
を指定しています。

**Comment by snowballrichdad** [comment]
もし、
Qty=90.0 ClosePositions=[ID=E20220126013RW,Type=1,Qty=**60**|ID=E20220126013RX,Type=1,Qty=30|]
の注文が実際の残高に合わせてどこのレイヤーで補正されて
Qty=90.0 ClosePositions=[ID=E20220126013RW,Type=1,Qty=**20**|ID=E20220126013RX,Type=1,Qty=30|]
になることで、Qty > ClosePositionsのQty合計値 によりエラーになるということであり、
実際の建玉の合計が90であっても、
Qty=130.0 ClosePositions=[ID=E20220126013RW,Type=1,Qty=**60**|ID=E20220126013RX,Type=1,Qty=**70**|]
で上手くいくのであれば、私としてはそれでも結構です。

改めてログをみてみたところ、しばらくすると、残高照会に、建玉IDごとの最新建玉数が反映されるようですが、
#444 でお話させていただとおり、それなりに時間がかかるようなので、決済処理においてはそのタイムラグがこちらとしてはかなり厳しいものがあります。
したがって、上記の案でうまくいくのであれば、そのほうが嬉しいです。

**Comment by snowballrichdad** [comment]
@cyber-minion 
残高照会で最新の建玉IDごとの建玉数がとれるようですね。
示唆いただいた内容にのっとって、返済注文において、建玉IDごとに最新の建玉数を指定するようにしてみます。
結果は、このスレッドでご報告させていただきます。

**Comment by snowballrichdad** [comment]
@cyber-minion @yasuyuki-nakazawa
うまくいきました。
ClosePositionsを指定する場合は、Qtyの総数量と、各建玉IDごとの数量のそれぞれが建玉数よりも少ない場合のみ、kabuステーションAPI側で補正されるが、そのいずれかが、実際の建玉数よりも多い場合は
`{'Code': 8, 'Message': '決済指定内容に誤りがあります'}`
のエラーになるということですね。
ご回答いただきありがとうございました。
不具合とは言えない事象のようですね。お手数をおかけして申し訳ありません。
(決済から残高照会の結果で残建玉数の最新化までのタイムラグがなければ、より良いのですが…
現状何回か{'Code': 8, 'Message': '決済指定内容に誤りがあります'}のエラーをスルーしなければなりませんので)
