### ISSUE TITLE
【要望】今後のMac 環境における API の提供について

### ISSUE THREAD

**Issue by kojikojikojikoji** [kabucom/kabusapi#474]
初めまして。カブコムAPI初心者です。
MAC対応の目処はございますでしょうか。

こちらのサービスを利用するためにWIndows PCを購入してプログラム開発をしております。(ちなみに、auカブコム証券で口座を開設してからwindowsしか対応していないことを知り、泣く泣くPC購入をいたしました。)
しかし、やはり慣れているMACでの開発を切望しております。
また、潜在利用者の中にはMAC対応がされておらずkabu stationの利用を断念しているユーザーの数多くいるのではないかと思います。

**Comment by yasuyuki-nakazawa** [comment]
Macでのカブステ利用希望は非常に多く頂戴しております。
しかしながら当該トレーディングツールのマック向け開発はコスト面を、鑑みて現状は計画にございません
仮想環境でwindowsをご利用頂く等のご対応を検討いただけると幸甚です
環境依存の少ないウェブベースのトレーディングツールが今後のソリューションの、鍵になる認識ではおります

**Comment by kitty2117** [comment]
いま、pythonでやろうと思ってsampleを読んでいました
そこに
url = 'http://localhost:18080/kabusapi/token'
との記述があります。
ここのlocalhostをkabuステーションが動いているパソコンのipアドレスに書き換えたら、
macからkabuステーションにアクセスできるのではないでしょうか？

**Comment by tsuchinaga** [comment]
localhost以外からは注文できませんが、下記issueが参考になると思います

#34
