### ISSUE TITLE
【質問】tick情報の取得はできないのでしょうか？

### ISSUE THREAD

**Issue by kitty2117** [kabucom/kabusapi#475]
pythonのサンプルをみているのですが、
tick情報の取得はできないのでしょうか？
あと、ローソク足情報の取得もできないのでしょうか？
tick情報から分足を作ろうとおもっていたのですが、
５分足を上抜けたら買いとかそういうことができないような。。。

**Comment by yasuyuki-nakazawa** [comment]
現在値の取得は可能です
push形式でデータの加工をすることで5分足を作成することはできます
現状は過去情報の配信は諸情報配信契約に関連して、実施しておりません
上述の方法で記載いただいている仕組みは構築できると思慮いたします

**Comment by kitty2117** [comment]
過去の質問にも同様のものがありました。重複質問失礼しました。
しかし、秒間５回のアクセス制限
まぁ、Tickを１分足にしてと考えていましたが、５回アクセスで１分足やってみます

**Comment by kitty2117** [comment]
売買シミュレーシュンやテスト用のデータですが、
JPX　日本取引所グループで販売してますね
http://db-ec.jpx.co.jp/
値段そんなに高くないし、わるくないかも？

**Comment by yasuyuki-nakazawa** [comment]
分足データであれば、おっしゃるとおり高すぎる金額設定ではないかと思います。
バックテスト等にはデータの購入をおすすめいたします。

**Comment by kitty2117** [comment]
Tickデータ買いました
取引おおい株で秒間１０回くらい取引されてますね（成り行きなんかでTcik飛びもあるでしょうけど）
２０回とかも稀にありました。最高は４０回みたな
見た範囲での値段の飛びは１秒で5tickくらいのがあった
成り行きで2,3tick飛びが交錯したのかな

**Comment by yasuyuki-nakazawa** [comment]
当件は一旦クローズさせていただきます
