### ISSUE TITLE
【質問】PUSH配信のエラー原因を教えてください。

### ISSUE THREAD

**Issue by avatarRDA** [kabucom/kabusapi#477]
サンプルの「kabuspi_websocket.py」を実行した際に下記エラーが発生。
正常に作動した場合「--- CONNECTED --- 」が表示されるはずですが、
原因を教えてください。
プログラミング初心者です。

＜エラーメッセージ＞
C:\Users\user\anaconda3\python.exe C:/Users/user/PycharmProjects/push/kabusapi_websocket.py
--- ERROR --- 
Handshake status 404 Not Found
--- ERROR --- 
on_close() takes 1 positional argument but 3 were given

Process finished with exit code 0

<状況＞
使用環境：pycharm
kabuステーションにはログイン済み（トークン発行等は可能）
実施日は株取引時間外（日曜日）

**Comment by hishiharahaz** [comment]
@avatarRDA さん
下記、２点確認いただけますでしょうか。
１．Pythonサンプルに含まれていた「00.Readme.txt」の前提に記載されている「websocket-client」はインストール済でしょうか。

２．時価情報・板情報は、取得できますでしょうか。
https://kabucom.github.io/kabusapi/reference/index.html#operation/boardGet

**Comment by yasuyuki-nakazawa** [comment]
websocket-clientが原因かと思われますね。上記ご確認ください
