### ISSUE TITLE
【質問】VBAでの注文約定照会のQueryについて

### ISSUE THREAD

**Issue by kabucomapi** [kabucom/kabusapi#48]
VBAで注文約定照会するため、次の通りQueryを設定していますがレスポンスを取得できません。（エラーは表示されない）
　レスポンスはJsonConverter.ConvertToJson(objHTTP)で確認しています。
　初歩的な質問で申し訳ないのですが、対応策の回答をお願いします。
 
　Set objHTTP = CreateObject("msxml2.xmlhttp")
    objHTTP.Open "GET", "http://localhost:" & PortNo & "/kabusapi/orders/?product=0, False"
    objHTTP.setRequestHeader "Content-Type", "application/json"
    objHTTP.setRequestHeader "X-API-KEY", ApiToken
    objHTTP.send

**Comment by yasuyuki-nakazawa** [comment]
API側かkabuステーション側のログに何かエラー等出ていませんでしょうか。

**Comment by kabucomapi** [comment]
回答ありがとうございます。お恥ずかしながら、API側、kabuステーション側のエラーログの確認方法がわかりません。マニュアル保存先URLと当該確認方法の記載ページをご教示いただけないでしょうか？

**Comment by kabucomapi** [comment]
カブステーションのマニュアルを確認しましたが、上記の確認方法の記載を見つけることができませんでした。
お手数ですが、回答をお願いいたします。

**Comment by tsuchinaga** [comment]
ログの出力先は #11 に回答があります

> kabuステーションのログは下記のパスに格納されております。  
> %appdata%\KabuS\Log

**Comment by kabucomapi** [comment]
回答ありがとうございます。
該当フォルダにあるファイルをwindows10標準のメモ帳で開きましたが、字化けして全く内容がわかりません。全ての文字コードで確認しましたが、駄目でした。
どうすれば内容を確認できるのでしょうか？
回答をお願いいたします。

**Comment by tsuchinaga** [comment]
少なくとも私の環境ではSJISで出力されていてメモ帳で開けば見れますね  
ファイル名は例えば `KabuS_20200901.log` です。

**Comment by kabucomapi** [comment]
tsuchinaga様
コメントありがとうございました。
おかげさまで確認することができました。

**Comment by kabucomapi** [comment]
Topに記載のコードを走らせたところKabuSのログに次のように出力されました。
21:17:16.9056,I,6012,0019 KeepSession at 2020/09/01 21:17:17
NetLib.Server.20200901のログは50分以上前のログしかありませんでした。
また、readyState<>4のまま戻ってきません。
VBAで、注文約定照会は動作していますか？
何度もお手数をおかけしますが回答をよろしくお願いします。

**Comment by yasuyuki-nakazawa** [comment]
kabuステーションAPI側のログではどうでしょうか？
エクセルマクロとしては注文約定照会は動作しております

**Comment by kabucomapi** [comment]
PLAIN_20200901_21.logのファイルでしょうか？
こちらには何も出力されていません。

**Comment by kabucomapi** [comment]
トークン等必要情報の取得に失敗していましたので、修正して再度トライしたところ次のエラーログに変化しました。
よろしくお願いします。
22:04:18.7416,I,6012,0015 メソッドが見つからない : /kabusapi/orders/ / GET

**Comment by yasuyuki-nakazawa** [comment]
差し支えなければ、問題となっていた部分をコメントいただけると他の方の参考ともなるかとおもいますので、
よろしくお願いいたします。

**Comment by kabucomapi** [comment]
色々とありがとうございました。
この件について、時間のかかった原因は、まず、ファンクション処理をしていたため、メインモジュールからトークン等の情報を取得していなかった事です。誠にはお恥ずかしいかぎりです。
さらに、APIの応答をjsonコンバータで解析しようとしてましたが、どうやら対応してないようで、テキスト出力しました。
さらに、ここからパースのモジュールを作成する必要があるので大変です。

別の質問で、銘柄登録の際のパラメータ設定についても悩んでいますので、こちらの方も何卒よろしくお願いします。

**Comment by yasuyuki-nakazawa** [comment]
当件は解決済みとして、Closeさせていただきます。
