### ISSUE TITLE
【質問】ordersのフィルタリングについて

### ISSUE THREAD

**Issue by excelderpa** [kabucom/kabusapi#481]
リファレンスに、注文番号※指定された注文番号と一致する注文のみレスポンスします。とありますが、パラメータをいろいろ変更しても、複数オーダーが返されます。detailsのtrue,falseは効きます。その他の項目も指定有無に関わらず、毎回同じ複数オーダーが返されるので、そういう仕様でしょうか？

**Comment by hishiharahaz** [comment]
@excelderpa さん
ordersのリファレンスにあるように問題なく各項目でフィルタされるかと思います。
可能な範囲で注文番号をフィルタしている実行スクリプトを記載いただけますでしょうか。

**Comment by excelderpa** [comment]
御多忙のところ申し訳ありません。
Excel VBAで、GET取得しています。
objHTTP.Open "GET", "http://localhost:" & PortNo & "/kabusapi/orders", False
objHTTP.setRequestHeader "Content-Type", "application/json"
objHTTP.setRequestHeader "X-API-KEY", ApiToken
objHTTP.send JsonConverter.ConvertToJson(param)

デバッグ時のパラメータ（json変換後）は
{"id":"20220221A01N3081XXXX"}　　<=IDは一部変えてあります
となっております。

※下記Queryパラメータは任意設定となり～　とあり、フルセットから１項目まで試してみましたがフィルタされません。
リターンコードは200で、当該id以外も返ってきますので、力業で必要データの取り出しはできています。
キャシュコントロールを行っていますが、それは関係ないと思うのですが。
勘違いしていましたら、申し訳ありません。

**Comment by cyber-minion** [comment]
実施にどのように「id」を指定しているかまで、スクリプトを記載いただければ幸いです。

**Comment by excelderpa** [comment]
お手数おかけします。

id （タイプstring）に注文番号をセットし、ディクショナリに入れ、jsonコンバートする、サンプルと同じ手順で利用しております。
上記の前行で、
Set param = New Dictionary
param("id") = id
Set objHTTP = CreateObject("msxml2.xmlhttp")

としています。json変換後の内容は、イミディエイトで確認しております。
それでも念のため、json変換後の、{"id":"20220221A01N3081XXXX"}　の内容を直接テキストでセットしても同じでした。

同様のコーディングで、他のAPIは問題なく動作しています。（全てを使ってはいる訳ではありませんが）

**Comment by yasuyuki-nakazawa** [comment]
上記を実施した際にフィルタリングがきかずに複数明細が返されるという事象ということで認識あっておりますか

**Comment by excelderpa** [comment]
はい、複数明細が返されます。
他の項目を指定しても同様です。

**Comment by cyber-minion** [comment]
OrdersAPIは「クエリパラメータ」で項目をフィルタリングしますが、下記のコードは「クエリパラメータ」としてフィルタリングしていないようです。

`objHTTP.send JsonConverter.ConvertToJson(param)`

ご参考までにサンプルのスクリプトを添付します。
※申し訳ございませんが、こちらのサンプルスクリプトの動作保証はいたしかねますので、ご了承ください。

```
Dim param As String
param = "id=xxxxxxxxxxxxxxx"

' リクエストオブジェクト作成
Dim objHTTP As Object
Set objHTTP = CreateObject("msxml2.xmlhttp")
objHTTP.Open "GET", "http://localhost:" & PortNo & "/kabusapi/orders?" & param, False
objHTTP.setRequestHeader "Content-Type", "application/json"
objHTTP.setRequestHeader "X-API-KEY", ApiToken
objHTTP.send

End
```

**Comment by excelderpa** [comment]
どうもありがとうございました。
検証できました。

**Comment by yasuyuki-nakazawa** [comment]
こちら、解決済みかと思いますので、クローズさせていただきます
