### ISSUE TITLE
【質問】pushのタイミング、pushされる情報について教えてください

### ISSUE THREAD

**Issue by kitty2117** [kabucom/kabusapi#486]
pushされる情報で確認させてください
　5:CurrentPriceと9:CalcPriceの違い
　25:BidPriceは成り行き売りで注文したときの売却値段、40:AskPriceは成り行き買いの値段とかんがえていいでしょうか？ただし、28:MarketOrderSellQtyと43:MarketOrderBuyQtyの内容がゼロでない場合はその限りでないし、数十ミリセックで板状況が変わった場合はその限りでない
　42:AskSign,27:BidSign,29-2:Sign,44-2:Signって何ですか？

それから、pushされるタイミングは板情報が変わったタイミングと考えていいでしょうか？

**Comment by yasuyuki-nakazawa** [comment]
まず、
■5:CurrentPriceと9:CalcPriceの違い
　5=現値、9=計算用現値　となります
　通常は同じ値になります。ただし、コーポレートアクションが発生した場合は異なります。
　
■25=最良売気配値段：成行買いで約定する値段
■40=最良買気配値段：成行売りで約定する値段
　※当然のことながら、あくまでも気配値となりますので、数量次第では成り行き値段は変わりますので、ご留意ください

■42,27, 29-2, 44-2のフラグの意味
　APIのリファレンスの時価情報板情報に記載しているので、こちら参照ください

■Pushされるタイミングについては、時価、板が更新されるとpush配信されます

**Comment by cyber-minion** [comment]
> 5:CurrentPriceと9:CalcPriceの違い

こちらについては、下記Issueをご参照いただければと思います。https://github.com/kabucom/kabusapi/issues/35#issuecomment-680353718

**Comment by kitty2117** [comment]
回答ありがとうございます。

>■42,27, 29-2, 44-2のフラグの意味
>　APIのリファレンスの時価情報板情報に記載しているので、こちら参照ください

つまり、発注しても直ぐに売買が成立しない気配情報があるということですね。

**Comment by cyber-minion** [comment]
解決済のようですので、クローズさせていただきます。
