### ISSUE TITLE
【要望】Fintech契約の条件について

### ISSUE THREAD

**Issue by kitty2117** [kabucom/kabusapi#487]
ここで書き込む事でもないかもしれませんが

３月１日でFintech契約の期限が切れて、アクセスできなくなってしまいました
サポート電話で聞いたら、取引をした翌月の第二営業日からFintech契約が使えるようになるとの事
株APIが使えるので、株コム証券を使うようになったのに、、、４月４日からしか使えない

株APIが使いたくて口座つくったのに株APIが使えない

**Comment by cyber-minion** [comment]
お客さまのご意見は社内に周知させていただきます。
ご不便をお掛けし申し訳ございません。

**Comment by kitty2117** [comment]
株APIの利用承諾書に同意したら、あとはkabuステーションの利用条件と同じ条件で使えるようになればよいかと思います。
よろしくお願いします。

**Comment by yasuyuki-nakazawa** [comment]
即時のご利用という要望は多く頂戴しております。

新規のお申込みに関しては、Fintechプランも無料期間を設けている関係上、すぐのご利用は可能ではございますが、
今回の例のように途中でFintechプランではなくなった場合はご指摘の状態となっております。

Fintechプランは料金をお支払いいただいてご利用するプランではなく、お取引を前提としたお客様へのプランとなってしまっておりますので、今回のご要望に関しては、別途課金プランの作成等を含めた検討はさせていただきます。

**Comment by kitty2117** [comment]
閉じます
