### ISSUE TITLE
【質問】WEBSOCKETの共存

### ISSUE THREAD

**Issue by DDT1947** [kabucom/kabusapi#489]
Excel Sheet上に関数 WEBSOCKET を配置・構成した板と VBA・REST で日々売買してますおじ（い）さんです。

ご教示願いたし

後場暇な時間帯に、kabusapi_websocket.py を参考に作成した時価PUSH配信プログラム（.py)を起動し、登録銘柄の時価情報（Symbol,CurrentPrice,CurrentPriceTime）が逐次表示されることを確認しました。

が、Excel Sheet上の板がフリーズしてしまい、他銘柄に切り替えても登録外と思われる銘柄のフリーズした板が表示されます。（再現性あり）

ついては、Excel上の ”関数 WEBSOCKET” と Python での ”PUSH配信WEBSOCKET” の共存は、仕様上無理なのではとの推察に至ったのですが　いかがなものでしょうか？

○✕等　簡便で結構ですのでご教示いただければ幸いです。

**Comment by yasuyuki-nakazawa** [comment]
Excel上の板がフリーズするときはどのような場合でしょうか？

**Comment by DDT1947** [comment]
＜本日前場に確認した内容＞

エクセルシートセルに埋め込んだ
　・WEBSOCKET(銘柄code,1,""最良売気配値段"")
　・WEBSOCKET(銘柄code,1,""最良買気配値段"")
　・WEBSOCKET(銘柄code,1,""現値"")
　　などの数値（板）を見ながら、VBA・RESTで個別銘柄を売買。

上記の売買可能状態で、Pythonプログラムを起動
　Pythonプログラムは、貴社配布の"kabusapi_websocket.py"を参考にした、
　board['CurrentPriceTime'],board['Symbol'],board['CurrentPrice']を表示するだけの内容
　逐次、表示が更新されることを確認

すると、エクセルシートセルに埋め込んだWEBSOCKETに、実際の数値とは異なる、変化しない数値が表示され、元に戻らない状態となる
　・銘柄codeを切替えても、実際の数値とは異なる、変化しない数値が表示される
　・感覚的には、Pythonプログラムを起動した時点のデータ表示のような気がする
　・Pythonプログラムをクローズしても復帰しない
　・kabuステーションだけの再起動では復帰しない
　・kabuステーションとエクセルの再起動で復帰する

環境　OS:Win10Home(21H2)、CPU:AMD Rizen3700X 8Core、RAM:16GB

以上　よろしくお願いします。

**Comment by cyber-minion** [comment]
websocketのセッションは１本ですので、共存しない仕様となっております。
最後に接続したほうのみ有効となりますので、先に接続していた方のWEBSOCKETは配信されなくなります。

**Comment by DDT1947** [comment]
ご回答ありがとうございます。
Pythonで生成した４本値、エクセルチャートで表示を目論んでいましたが残念です。

つきましては、かねてから懸案の”分足配信”早々のご決断に期待します。

**Comment by cyber-minion** [comment]
解決済ですので、クローズさせていただきます。
