### ISSUE TITLE
【質問】銘柄登録における配列の設定について

### ISSUE THREAD

**Issue by kabucomapi** [kabucom/kabusapi#49]
銘柄を登録するため、下記のコードを作成したのですが、動作しません。(指定されたコードが見つかりません。とダイアログが表示される)JsonConverter.ConvertToJsonに渡すパラメーターが間違っていると思っているのですが、どの部分に誤りがあるのか回答をいただけると幸いです。
また、Pythonのコードをみると、複数銘柄同時に登録が可能なようなので、その方法もご教示いただけると助かります。
さらに、Pythonでは下記のようなコードが公開されていますが、VBAでもこれらのコードを公開していただけないでしょうか。
よろしくお願いいたします。

kabusapi_orders.py
kabusapi_positions.py
kabusapi_register.py
kabusapi_register1.py
・・・

Public Function regset(code As Variant, ex As Variant) As Variant '引数：code 銘柄コード,ex 取引所
    Dim objHTTP As Object
    Set objHTTP = CreateObject("msxml2.xmlhttp")
    Dim param(1) '←通常Dim param(2)と思われるが、2にするとJsonConverter.ConvertToJson(param)で、3つ目の要素にnull値が入って返ってきます。
  
    param(0) = "Symbol: 7203"
    param(1) = "Exchange: 1"
  
    objHTTP.Open "PUT", "http://localhost:" & PortNo & "/kabusapi/register", False
    objHTTP.setRequestHeader "Content-Type", "application/json"
    objHTTP.setRequestHeader "X-API-KEY", ApiToken
    objHTTP.send JsonConverter.ConvertToJson(param)

End Function

**Comment by kabucomapi** [comment]
APIとKabusのログを確認しました。
パラメータ配列の設定に誤りがあるのだと思いますが、VBAでどのようにパラメータ配列を定義してJsonConverter.ConvertToJsonに渡せばよいのかわかりません。
何度もお手数をおかけしますが、よろしくお願いいたします。


00:47:22.9897,I,6012,0015 【Regist】(["Symbol: 7203","Exchange: 1"])
00:47:22.9897,I,6012,0015 【Regist】({"Code":4001005,"Message":"パラメータ変換エラー - 詳細はkabuSログファイルを確認してください"})
00:47:55.1619,E,6012,0015 JSON文字列のパースに失敗
Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'TA.KC.Enterprise.ClientApplication.Infrastructure.Core.KabuSApi.ApiRegistParam' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
Path '', line 1, position 1.
   場所 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureArrayContract(JsonReader reader, Type objectType, JsonContract contract)
   場所 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   場所 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   場所 Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   場所 Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   場所 Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   場所 tr.b[T](String json)

**Comment by yasuyuki-nakazawa** [comment]
配列の設定項目部分が不正にみえます。
サンプルプログラムのPythonにある kabusapi_register.py が参考になると思いますが、
複数銘柄をリクエストする記載としては下記のとおりとなります。

抜粋して記載します。
配列としては、銘柄、市場を下記のように設定し、これをリクエストとしてPUTすればよいです
ご確認ください

obj = { 'Symbols':
        [ 
            {'Symbol': '9433', 'Exchange': 1},
            {'Symbol': '6501', 'Exchange': 1},
            {'Symbol': '6501', 'Exchange': 3}
        ] }
json_data = json.dumps(obj).encode('utf8')

url = 'http://localhost:18080/kabusapi/register'
req = urllib.request.Request(url, json_data, method='PUT')
req.add_header('Content-Type', 'application/json')
req.add_header('X-API-KEY', 'TOKENを設定')

**Comment by kabucomapi** [comment]
回答ありがとうございました。
パラメータに直接テキストデータを渡して実行すると、応答が帰ってきました。
コンバータを使ってパラメータ設定を実行しようとしてましたが、それが問題でした。
