### ISSUE TITLE
【要望】kabuステーションと複数のセッションを作りたい

### ISSUE THREAD

**Issue by kitty2117** [kabucom/kabusapi#491]
kabuステーションと複数のセッションを張ることができるようにならないでしょうか？
現状、検証用のポートがありますが、それは制限がかなり多い様子
（すみません、Fintec契約なくてkabuステーションとつながらないので検証ポートの制限なければ、この要望は無しということで、、、）

具体的なイメージとしては、
kabuステーションと本番のセッションを２つ張って、
１．コンソール１でトレードするスクリプトを動かし、コンソール２で開発中のスクリプトを動かす
コンソール２で動きがおかしかったら、すぐにブレークして、すべてのポジションを解消するスクリプトを動かします
コンソール１はブレークしないで動きっぱなし

２．セッション１でトレードスクリプトを動かして、セッション２でデータ収集用のスクリプトを動かす、翌日トレードする銘柄探しなど、

あと、質問になるのですが、二台のパソコンで同じ口座番号でkabuステーションを起動してアクセスできるでしょうか？
それができれば、２セッションが実現できます。

**Comment by yasuyuki-nakazawa** [comment]
セッションに関しては、確認いたしますが、Pushのセッションは１本です。
※確認のうえ、再度ご回答いたします

質問にあります複数台のパソコンではご利用いただけません。
カブステAPIはログインされていることが前提となります。
カブステ自体は別段末で複数起動できるものの、ログインできる端末は１台となっております。
そのため、カブステAPIが利用できる端末は１台となります

**Comment by kitty2117** [comment]
閉じます
