### ISSUE TITLE
【質問】情報系のリクエストの流量制限について

### ISSUE THREAD

**Issue by hiuchida** [kabucom/kabusapi#493]
APIリファレンスの情報系のリクエスト制限に関して質問です。

> 銘柄情報の取得や注文・残高の照会を行います。
> 情報系のリクエストは秒間10件ほどの流量制限を設けています。
> リクエストされた銘柄は自動でAPI登録銘柄リストに登録されます。
> API登録銘柄リストに登録できる銘柄数は、REST/PUSHを含めて最大50銘柄です。

Q1. オプションのATM±6本の時価情報をCall, Putで取得しようとすると、上記の制限では合計26件となりますか？

Q2. 自動でAPI登録銘柄リストに登録され、最大50銘柄というのは、ユニークな51件以降は、最も古いものから自動で削除されるという動作ですか？

Q3. これは質問というより要望ですが、オプション向けの時価情報として、ATM±6本を１リクエストで取得できるAPIを追加して欲しいです。

Q4. しばらくしてから再実行したら、すべて{"Code":4001006,"Message":"API実行回数エラー"}が返りました。
[２.リクエストチェックエラー（Message）](https://kabucom.github.io/kabusapi/ptal/error.html#message)のコード4001006の説明が空欄ですが、これはどのような制限でしょうか？

**Comment by hiuchida** [comment]
追加質問です。

Ｑ５．カブステーションのＡＰＩメニューにＡＰＩ登録銘柄リストがあったので、表示したところ、オプションのATM±6本の26銘柄が表示されていました。なお、隣に、オプションビュー：ATM±6本を表示していて、リアルタイムに気配やGreeksの値が更新されています。このような状態でなぜ、銘柄情報の取得ＡＰＩに対してのリクエストに制限がかかっているのでしょうか？　アプリ→カブステーション→データセンターの3層構造において、アプリ→カブステーションにしか負荷がかからず、かつ、カブステーションの画面上にはリアルタイムに値が表示されているのなら、その値を返してくれればいいです。

**Comment by cyber-minion** [comment]
> Q1. オプションのATM±6本の時価情報をCall, Putで取得しようとすると、上記の制限では合計26件となりますか？

情報系のリクエストは秒間10件の流量制限がありますので、1秒間に10本ずつ実行するようにしていただければと思います。

> Q2. 自動でAPI登録銘柄リストに登録され、最大50銘柄というのは、ユニークな51件以降は、最も古いものから自動で削除されるという動作ですか？

ユニークな51件以降は登録することができません

Q3は要望として検討させていただきます。
Q4に関しては、リクエストは流量制限に抵触していないかをご確認いただけますでしょうか。
Q5は確認して回答いたします。

**Comment by hiuchida** [comment]
Q1, Q4について

こちらがテスト的に26リクエストをスリープを入れずに連続して投げていたためでした。
ただ、質問したかったのは、１０分ほど経過してもエラーになっていたので、どうすれば復帰するのか分からなかったです。
一旦ブロックされたら、kabuステーションの再起動が必要ならば、そうするしかないですが。。。

ただ、アプリ開発者から意見として、制限を超えたらブロックするよりは、制限を超えたリクエストの本処理前に指定秒数になるまでHTTPサーバー（kabuステーション内）でスリープしてくれた方が、アプリ開発者の負担が軽くなるとは思います。

Q2について

APIリファレンスを読み返していて、銘柄登録カテゴリの説明として、PUSH配信のみに関する登録・解除と思い込んでいましたが、

> PUSH配信する銘柄の登録や解除を行います。
> 登録された銘柄はkabuステーションのAPI登録銘柄リストに表示されます。
> API登録銘柄リストに登録できる銘柄数は、REST/PUSHを含めて最大50銘柄です。

実際は、以下のとおり解除はRESTの場合でも可能で、解除すれば手動で不要な銘柄を削除して51銘柄以上の情報取得が可能ということですね。
・銘柄登録　PUSHのみ
・銘柄登録解除　REST/PUT共通
・銘柄登録全解除　REST/PUT共通

さらに関連して、気になったので、追加質問です。

Q6. もともとExcelマクロ（→BOARD）を利用しようとしましたが、複数セルにマクロを16個ほど貼り付けて、行挿入等の操作ですべてを再取得するようで、一部セルが「API実行回数エラー」となり、Excelマクロで使えないと判断して別の方法を模索したのですが、そもそもExcelマクロで1秒間に10リクエストの制御をかけることは可能なのでしょうか？

**Comment by cyber-minion** [comment]
Q5について、

＞なぜ、銘柄情報の取得ＡＰＩに対してのリクエストに制限がかかっているのでしょうか？
銘柄情報APIを実行すると、当該リクエストはkabuステーションを介して、サーバーにアクセスします。
サーバーへの負荷を軽減するために、流量制限を設けております。

＞カブステーションの画面上にはリアルタイムに値が表示されているのなら、その値を返してくれればいいです。
PUSH APIを利用すれば、値をリアルタイムに取得できるかと思います。

**Comment by yasuyuki-nakazawa** [comment]
補足します
>Q3. これは質問というより要望ですが、オプション向けの時価情報として、ATM±6本を１リクエストで取得できるAPIを追加して欲しいです
こちらに関しては、利用用途考えても上下±6本を取得できた方が処理もしやすいかと思慮いたしますので、引き続き検討いたします。

>こちらがテスト的に26リクエストをスリープを入れずに連続して投げていたためでした。
>ただ、質問したかったのは、１０分ほど経過してもエラーになっていたので、どうすれば復帰するのか分からなかったです。
>一旦ブロックされたら、kabuステーションの再起動が必要ならば、そうするしかないですが。。。
対象のリクエストが流量制限としてエラーになったあともエラーが継続していたという件に関しては
確認いたします

＞カブステーションの画面上にはリアルタイムに値が表示されているのなら、その値を返してくれればいいです。
APIはカブステーションの画面とは別にリクエストを実施しております。
※画面に日表示項目もあります関係上です。
　一度、サーバー側への銘柄登録（情報配信）を実施した後は、カブステーション内のメモリ上のデータを返信しますので、高速に処理することが可能になっております。
　銘柄数に制限を設けているのはサーバー側の処理負荷を防止するためとなっており、各情報の参照（メモリ参照）に関しては流量制限を緩和できる可能性はございますので、こちらも改善検討はさせていただきます

**Comment by hiuchida** [comment]
こちらの質問は、当時はREST APIは馴染みがあったが、PUSH API(WebSocket)に馴染みがなく、なんとかREST APIだけで実現しようという意識が高かったです。
いまは、PUSH APIで安定して取得できているため、issueをCloseで構いません。

**Comment by cyber-minion** [comment]
クローズさせていただきます。
