### ISSUE TITLE
【質問】信用取引のフローについて

### ISSUE THREAD

**Issue by kitty2117** [kabucom/kabusapi#494]
信用取引のフローについて確認させてください
１．sendorderで発注する（成り行きの場合）
　　証券コード9999で売り板が[ 300円:100株, 301円: 200株, 302円: 100株, 303円: 300株 ]のところに
　　500株の成り行き買いを入れると、300円で100株,301円で200株,302円で100株,303円で100株の約定が行われる
２．positionsで持ち高確認をする
　　返り値は配列で返る
　　[ [ 300円, 100株, long], [ 301円, 200株, long], [ 302円, 100株, long], [ 303円, 100株, long] ]　こんな感じ
　　現在の損益額はこの配列から計算する必要がある
３．sendorderでポジションを閉じる
　　sendorderのClosePositionOrderの指定で、どのポジションが優先して閉じられるかを指定する
　　この場合500株を成り行きで売れば何も考えなくてもすべてのポジションが閉じる
　　買い板が[ 321円:200株, 320円: 300株, 319円: 100株, 318円: 300株 ]の場合は321円で200株、320円で300株が約定される
４．ordersで注文約定情報を得る
　　返り値は配列で
　　[ ['9999', 500株, 信用返済, 成り行き売り], [’9999’, 500株, 信用新規,  成り行き買い], ['1111', 400株, 信用返済売り, 指値300円], [’1111’, 400株, 信用新規買い, 指値290円] ]　こんな感じ
　　この配列の要素数はいくつまででしょうか？
　　成り行きで複数価格で約定したものも一括でリストされる。['9999', 500株, 信用返済, 成り行き売り] は分割でされない

取引のフローはこうした理解でいいでしょうか
仕様書だけだと理解がなかなかむずかしいです。
よろしくおねがいします。

　追記：直近の約定情報は、配列の先頭にあるのでしょうか？配列の最後になるのでしょうか？
　　　　それとも日時で並べ替えして探してくるのでしょうか？

**Comment by kitty2117** [comment]
注文約定照会と残高照会の詳細を読みました。
なんか頓珍漢な質問してますね。失礼しました

ordersは複数の約定情報がリストで送られてくるのではない。
potisionsも複数銘柄のポジションがすべて得られるわけではない。
そうすると、スクリプトがバグって止まったとか、何かの異常事態が起きた時にポジション解消をするスクリプトは作れないいうことでしょうか
基本的にマルチスレッドで複数銘柄を取引する事を想定したAPIではないと思います。将来的には複数銘柄トレードも想定しているのでしょうか？

**Comment by cyber-minion** [comment]
ordersもpositionsもフィルターをかけずに呼び出したら、すべての注文約定情報、残高情報が返ってくると思います。

**Comment by cyber-minion** [comment]
本件は回答済ですので、いったんクローズさせていただきます。
