### ISSUE TITLE
【質問】ドテン買いドテン売りのウエイト時間について

### ISSUE THREAD

**Issue by kitty2117** [kabucom/kabusapi#496]
連投失礼します
ドテン売りの時に、
成り行きで買い戻しをかけて、その直後に新規の売りを行います
その時にウエイト時間はどれほど考えれば良いでしょうか？
フローを書くと

1.成り行き売り
成り行き売り注文、ロングポジションを解消します
2.解消売買成立確認
ポジションが無くなった事を確認、または、売り注文が約定した事を確認
3.新規の成り行き買い注文
4.新規買い成立確認
新規売りポジションがてきた事を確認、または、新規売り注文の約定確認

この時に1と2の間、3と4の間にウエイト時間はどれくらい必要でしょうか？
適切な時間待たないと、ポジションや約定情報の再要求を繰り返して、1秒の流量制限エラーになってしまう気がします
1秒くらい待つと、監視銘柄数30とか40とか増えると、処理落ちが頻発すると思います

また、今はシングルスレッドでスクリプト動かす事を考えていますが、慣れてきたらマルチスレッドにすると思います、30とか40銘柄監視する
たまたま、同じタイミングでドテン買いやドテン売りが重なるとエラーになる、しかも、レアなタイミングエラーになる気がします

よろしくお願いします

**Comment by kitty2117** [comment]
自己解決
トレードシュミレーターができたので回してみましたが
３０銘柄４０銘柄はタイミングで流量制限でひっかかるときもありそう
２，３銘柄なら、多分問題なし
マルチスレッドはやめて、シングルだけでいいかも、回したデータ少なくてあれですが、、、

ただ、成り行き発注後にどれくらいの時間で約定データを取りにいけばよいかは、目安がほしいです
システムは
ArrowHead←→auカブコムシステム←→kabuステーション←→ユーザースクリプト
この流れで良いでしょうか？
ArrowHeadとauカブコムシステム間だとどれくらいでしょうか？ほぼゼロ？

**Comment by yasuyuki-nakazawa** [comment]
記載いただいたフローは、その通りです
発注時は
ユーザー→カブコム→
ここまでのレイテンシとしては、15ミリ秒〜となっており、平均で100ミリ秒程とお考えいただければと思います
当然、寄り付きや引けなどタイミングにより異なりますので、あくまでも参考値として。
arrowhead、カブコム間の処理、ネットワークレイテンシは未定ですが、数十ミリと考えてよいと思われます

**Comment by yasuyuki-nakazawa** [comment]
約定時は
arrowhead→カブコム
となり、ここは50ミリ〜
このあたりを参考にインターバルの方をご検討いただければと思います

**Comment by kitty2117** [comment]
回答ありがとうございます

まずは100msecのウエイトいれて約定情報要求をするようにします
確かに寄り付きの時は人間が目で見てて遅い時ありますね
それは再送要求を何度かすることになるか、、、

**Comment by cyber-minion** [comment]
回答済ですので、クローズさせていただきます。
