### ISSUE TITLE
【質問】一般信用　長期／デイトレ　の売買可否について

### ISSUE THREAD

**Issue by takei0723** [kabucom/kabusapi#497]
銘柄情報に一般信用の売買可否として「KCMarginBuy」「KCMarginSell」があります。
長期とデイトレには分かれていませんが、このステータスがTrueであれば
一般信用の長期／デイトレどちらも取引可能という認識でよろしいでしょうか？

逆に言うと片側だけ取引可能のような
一般信用（長期）：NG
一般信用（デイトレ）：OK
という銘柄はないという認識でよろしいですか？

**Comment by yasuyuki-nakazawa** [comment]
確認いたします。お待ちください
基本的には、記載されている認識で問題ないかと思いますが、裏付けとります

**Comment by cyber-minion** [comment]
「KCMarginBuy」「KCMarginSell」は、長期、デイトレのどちらかが売買可能であれば「True」になります。リファレンスの補完をさせていただきます。

> 逆に言うと片側だけ取引可能のような
> 一般信用（長期）：NG
> 一般信用（デイトレ）：OK
> という銘柄はないという認識でよろしいですか？

現時点で2751の売は上記のような銘柄となります。

**Comment by takei0723** [comment]
ご回答ありがとうございます。
いまのところはどちらが可能なのか判別する手段はないのでしょうか？

**Comment by cyber-minion** [comment]
kabuステーションかログイン後ページにてご確認いただければと思います。
判別するインターフェースの追加は検討させていただきます。

**Comment by takei0723** [comment]
承知しました。ぜひともその情報をAPIでとれるようにしていただけると助かります。
よろしくお願いします。
