### ISSUE TITLE
【要望】pushされるjsonデータをダウンロードしたい

### ISSUE THREAD

**Issue by kitty2117** [kabucom/kabusapi#499]
お世話になります。

pushされるjsonデータをダウンロードできるようにならないでしょうか？
ストップ高ストップ安になった株のデータ、９：００に寄らないで９：０３分によった時のデータなど、特殊な場合のサンプル
普通によく取引される株、出来高上位、ティック数上位、売買金額上位の株の２，３日分のjsonデータ
２２５銘柄、JASDAQ銘柄、マザーズ銘柄で、２，３銘柄くらいづつ
板情報もついてますし、最良売気配値段もついている。そのままトレードスクリプトに流してテストしやすいです。

APIとかでなく、Sampleスクリプトのダウンロードみたいな感じで、サンプルデータってことで、ここからDLできる形でかまいません

**Comment by yasuyuki-nakazawa** [comment]
過去データのダウンロード提供は諸契約上できません
データの購入は以下のサイト等をご検討ください
http://db-ec.jpx.co.jp/

**Comment by kitty2117** [comment]
これは、立てた人がクローズするのか
