### ISSUE TITLE
質問API実行回数

### ISSUE THREAD

**Issue by kenichi3** [kabucom/kabusapi#5]
最大API実行回数は、どれくらいでしょうか？

**Comment by yasuyuki-nakazawa** [comment]
kabuステーションAPIでは、秒間における流量制限がございます。
情報系と発注系で制限は異っておりますが、情報系は秒間10件ほど、発注系は秒間5件ほどを目安にお考えください。
なお、当該数値に関しては変更されることがございます。

**Comment by kenichi3** [comment]
ありがとうございます。
