### ISSUE TITLE
【質問】Excelアドイン　信用返済注文の決済順序・返済建玉指定の設定について

### ISSUE THREAD

**Issue by hirocha** [kabucom/kabusapi#50]
配布されているkabuSTATION_API_ORDER_sample.xlsmを使って株式信用取引を検証しています。
新規買い注文→約定は確認しています。
返済のほうがうまくいかないため質問させて下さい。

・決済順序
・返済建玉指定（返済建玉ID・返済建玉数量）

質問①　まず返済建玉IDとは関数「=POSITIONS(0)」で返ってくる配列の一番左の列に表示される14桁の英数字で合っていますでしょうか？

質問②
![信用返済質問](https://user-images.githubusercontent.com/70001206/91680508-691ee980-eb86-11ea-9182-b70ae7f95111.jpg)
No1.　決済順序を「日付（古い順）、損益（高い順）」と入力、返済建玉IDと返済建玉数量を空白で発注すると、発注結果欄に{"Code":1009001,"Message":"建玉が選択されていません。"}と返ってきます。

No2.　決済順序を空白、返済建玉IDに質問①で挙げた14桁の英数字を入力、返済建玉数量を現在保有の100と入力して発注すると、
発注結果欄に{"Code":4001005,"Message":"パラメータ変換エラー - 詳細はkabuSログファイルを確認してください"}と返ってきます。
ログのスクショ画像↓
![No2のKabuSログ](https://user-images.githubusercontent.com/70001206/91680482-56a4b000-eb86-11ea-86bb-0f2db73dce40.jpg)

No3.　決済順序を「日付（古い順）、損益（高い順）」と入力、返済建玉IDに質問①で挙げた14桁の英数字を入力、返済建玉数量を現在保有の100と入力して発注すると、
発注結果欄に「決済順序、返済建玉指定はどちらか一方を入力してください」と返ってきます。

正しい入力方法を教えて下さい。
具体的なサンプル画像など掲載していただけると助かります。
なお、当方のケアレスミスが原因でしたらそのときは申し訳ありません…

**Comment by yasuyuki-nakazawa** [comment]
No1.ですが、返済建玉IDはExcecutionID（一番左側の項目）となります
No2.こちら、kabuステーションのログを確認頂き、エラーメッセージを教示いただけますか。
　　　　　　kabuステーションのログは下記のとおりです。　%appdata%kabuS
No3.：Excelのマクロのバージョンはいくつを利用されておりますでしょうか。
　　　Ver1.１.0では返済順序に関してはプルダウンで選択できるようにしておりますので、ご確認ください

**Comment by hirocha** [comment]
返済建玉IDは合っているのですね。良かったです。

＞エラーメッセージを教示いただけますか。
上の質問に画像を貼っています。スクショ画像がわかりにくくてすみません。
同様の内容になりますがスクショ画像を掲載し直します。
![screenshot_02](https://user-images.githubusercontent.com/70001206/91710768-c2573f00-ebbf-11ea-9ca2-be8fc204c79c.jpg)

マクロのバージョンがアップデートされていたのですね。把握していませんでした。失礼しました。
早速ver1.1.0で試してみましたが、上の質問と全く同様の結果となりました。

**Comment by yasuyuki-nakazawa** [comment]
kabuステーションAPI側のログはいかがでしょうか？何か出てますか？エクセル的には誤りはないように見受けられますので。

**Comment by hirocha** [comment]
![カブステAPIのログ](https://user-images.githubusercontent.com/70001206/91858943-d0cb5680-eca4-11ea-8ea9-f06936a2495c.jpg)
APILogフォルダのPLAIN_XXXX_XX.logファイルのスクショです。

ちなみにPythonで実行しても同様の結果でした。

**Comment by hirocha** [comment]
![カブステAPIのログ](https://user-images.githubusercontent.com/70001206/91859518-85657800-eca5-11ea-8f6e-6ffa6a5687dd.jpg)
APILogフォルダのPLAIN_XXXX_XX.logファイルのスクショです。

ちなみにPythonで実行しても同様の結果でした…

**Comment by hirocha** [comment]
なんとか解決しました。
項目の選択ミスでした。
yasuyuki-nakazawaさんご多忙の中ご対応ありがとうございました。
今後ともよろしくお願いいたします。
