### ISSUE TITLE
【質問】ヒストリカルデータの取得

### ISSUE THREAD

**Issue by YoshimiRebaza** [kabucom/kabusapi#502]
ー背景
現在こちらの資料から、
https://engineering.kabu.com/entry/2021/04/01/193049
カブコム証券のAPIより
(トークンの取得後に)
現在値の取得
ポジションの発注が
できることは理解していますが、
日経225先物取引のヒストリカルデータの取得に関して
理解できていない状況です。

ー質問
カブコム証券のAPIは
日経225先物取引の過去の限月に関して、
MQL4の為替の過去のチャート取得のように、
ヒストリカルデータを取得することが可能かどうか
お伺いできればと思います。

**Comment by cyber-minion** [comment]
現状は、過去分の情報を取得することができませんが、取得することは検討しております。

**Comment by yasuyuki-nakazawa** [comment]
現状はリアルタイム情報のご提供のみとなっております
過去データは取引所のサイト等での購入が可能となっておりますので、こちらも検討いただけると良いかと存じます

**Comment by cyber-minion** [comment]
本件は回答済ですので、いったんクローズさせていただきます。
