### ISSUE TITLE
websocketについて【質問】

### ISSUE THREAD

**Issue by gfd05600** [kabucom/kabusapi#503]
API 始めた初心者です。お教え願います。Websocketがうまく動きません。pythonの環境に問題があるのでしょうか？。pythonインストール後に「py -m pip install websocket-client」のコマンドは実行済です。

エラー表示
 File "C:\sna\kabusapi_websocket.py", line 34, in <module>
    websocket.enableTrace(True)
AttributeError: module 'websocket' has no attribute 'enableTrace'

**Comment by gfd05600** [comment]
34行目をコメントアウトしても35行がエラーになります。
AttributeError: module 'websocket' has no attribute 'WebSocketApp'
Traceback:
File "C:\Users\gfd05600\anaconda3\lib\site-packages\streamlit\script_runner.py", line 354, in _run_script
    exec(code, module.__dict__)
File "C:\sna\kabusapi_websocket.py", line 35, in <module>
    ws = websocket.WebSocketApp(url,

**Comment by cyber-minion** [comment]
確認させてください。「py -m pip install websocket-client」の実行は問題なかったという認識でよろしいでしょうか。

ご参考として、以下のAPIリファレンスを参照しながら、websocketを実行すれば、データ取得できるかと思います。
https://kabucom.github.io/kabusapi/ptal/push.html

**Comment by gfd05600** [comment]
忙しいところありがとうございます。再確認します。

**Comment by snowballrichdad** [comment]
Pythonにはwebsocket-clientとwebsocketという2つのパッケージがあり、どちらにもwebsocketというモジュールがあります。
何かの設定ミスで、websocketパッケージが参照されていしまうと、上記のエラーが起こることがあります。

**Comment by gfd05600** [comment]
お世話になります。
２つのパッケージのうちどちらに参照されているかの確認の仕方をお教えいただけば幸いです。

**Comment by gfd05600** [comment]
パワーシェルプロンプトで　ｐｉｐ　ｌｉｓｔを実行したところ
websocket-clientがいなくて、 websocket  0.2.1がいました。
原因はこれでしょうか。再度、処置の仕方をご指導お願いします。お手数おかけしますがよろしくお願いいたします。

**Comment by snowballrichdad** [comment]
pip uninstall websocket
のあと
pip install websocket-client
でいいと思いますが

**Comment by gfd05600** [comment]
uninstallしたら
Would you remove:
c:\users\gfd05600\anaconda3\lib\site-packages\websoket-0.2.1.dist-info\ж
c:\users\gfd05600\anaconda3\lib\site-packages\websoket\ж
Proceed(y/n)？y　　→yes or noを求められｙｅｓ
すると
 Successfully uninstalled websoket-0.2.1




次にinstall pip install websocket-clientを実行。

すると
Collecting websocekt-client
Downloading websocket client-1.3.2-py3none-any.ehl(54kB)
Installing collected packages: websocket-client
Successfilly installed websocket-client-1.3.2




pip listで確認すると
websocket-client でバージョン1.3.2が確認できました。

ありがとうございます。




まだpython のkabisapi websocketは動かしていませんが
これで、下準備はＯＫでしようか？

**Comment by gfd05600** [comment]
APIリファレンスにはpy -m の指定がありますが、
「py -m　pip install websocket-client」のコマンド指定と当方ＰＣとの相性でしょうか？

**Comment by gfd05600** [comment]
snowballrichdadさん　本日現物が動いている時間に走らせましたところエラーもなく動きました。ご親切に感謝します。

**Comment by gfd05600** [comment]
残念に思うこと。

1.カブステにいちいち登録しなけば消えてしまう。ＴＯＰＩＸ100銘柄を登録したいが50銘柄までの制限がある。（システムを立ち上げたとき登録する仕組みを組むしかない、50銘柄を交互に入れ替えトータルで100銘柄にするとか）

2.夜間の日経225ラージ・ミニ、プットオプション等が現物時間しか取れない。
（これの対応は当方では対応不可。）

**Comment by gfd05600** [comment]
websocketの使用感その2

当方としては、独自のテクニカルのインジケーターを作りたい思うが、取れる情報が少ないというか無い。ネイキッドＰＯＣを作りたいが銘柄別の価格帯出来高データが無いし作るデータの元ネタが無い。
websocketのデータも50銘柄しか取れない。東証には約4000銘柄あるのに50銘柄とは、50銘柄を選別できるならwebsocketのリアルタイムデータとれる利用価値が制限されebsocket　
を使う価値がない。ｗebsocketを使う理由は銘柄を探すことで、一番重要なものが銘柄情報で、株式投資の３つの重要点があると思う。その1っが銘柄選択で上がる銘柄が分かれば今日始めた個人投資家でも含み益を出せる。
証券口座数Ｎｏ一番はＳＢＩ証券だが、楽天証券が猛追している。その理由として楽天のマーケットスピード3は機関投資家が使っているアルゴの発注ができる。アイスパーク発注ステルス発注、スナイパー発注等いままで機関投資家しか使えないツールを楽天は個人に提供している。これを見るとＰｙｔｈｏｎをつかって個人がこのシステム組むのは無理がある。たぶん大勢の人に作れないと思う。それは取れるデータが無いし制限されているから。だったら、カブコム証券さんには失礼で申し訳ありませんが、マーケットスピード3を使った方が利口だろう。
