### ISSUE TITLE
【質問】kabuステーションのプロキシ対応

### ISSUE THREAD

**Issue by spotthediff** [kabucom/kabusapi#504]
kabuステーション APIではなくkabuステーションのソフトウェアについての質問ですが
kabuステーションのソフトはプロキシを設定した環境下で使用可能なのでしょうか?

競合の楽天証券のマーケットスピードでは可能なのですが、kabuステーションでは対応しておられますか?

https://www.rakuten-sec.co.jp/MarketSpeed/onLineHelp/msman1_2_9.html

**Comment by cyber-minion** [comment]
現状、kabuステーションはプロキシ経由での利用はできませんが、ご要望として検討させていただきます。

**Comment by yasuyuki-nakazawa** [comment]
プロキシを経由した動作に関しては保証できかねるところがございます。
情報の反映スピードのみならず、チャートの更新で情報抜けが発生する等の事象が過去に確認されております

**Comment by cyber-minion** [comment]
回答済ですので、いったんクローズさせていただきます。
