### ISSUE TITLE
【質問】トークンが取得できません

### ISSUE THREAD

**Issue by sinsaku1973** [kabucom/kabusapi#507]
プログラミング1年未満の初心者です。
サンプルのkabusapi_token.pyを実行すると以下のエラーが出ます。

> HTTP Error 400: Bad Request
> {'Code': 4001005, 'Message': 'パラメータ変換エラー - 詳細はkabuSログファイルを確認してください'}
> 

ログファイルを確認するとjsonがparseできてないような記載があります。

対応方法ご教示いただけますと幸いです。

不足情報などありましたらご指摘お願いします。

**Comment by cyber-minion** [comment]
APIPasswordの設定は問題ないでしょうか。

**Comment by sinsaku1973** [comment]
ありがとうございます。
kabuステーションのapiシステム設定「apiパスワード（本番用）」、「apiパスワード（検証用）」に設定したパスワードのいずれも試してみましたが、ダメでした。
