### ISSUE TITLE
【質問】リアルタイム資産評価の項目の取得の仕方

### ISSUE THREAD

**Issue by lstm500** [kabucom/kabusapi#508]
Kabu ステーションのアプリで表示される
・「リアルタイム資産評価」の項目をAPIで取得するにはどうすればよいでしょうか？
リファレンスのsampleを見たのですが該当するサンプルがなかったように感じます。

具体的には
・資産総額
・保有商品評価額
・株式合計
・先物オプション合計
・現金合計
になります。

よろしくお願いします。

**Comment by yasuyuki-nakazawa** [comment]
ご確認させていただいております。少々お待ちください

**Comment by yasuyuki-nakazawa** [comment]
リアル資産評価自体は開発は完了しているのですが、パフォーマンス上の懸念があり、公開をしておりません。
当該課題が解決次第、公開をさせていただこうと考えております

**Comment by lstm500** [comment]
ご回答ありがとうございます。
公開される日をお待ちしております。
Closeいたします。
