### ISSUE TITLE
【質問＆トラブル】kabuステーションの別端末からのログイン＆利用について

### ISSUE THREAD

**Issue by mik2008** [kabucom/kabusapi#509]
今まで自分のＰＣでkabuステーション（API）を利用していたのですが
Windowsサーバー端末をレンタルしてそこからの利用に切り替えたいと考えています。
kabuステーションの複数端末の同時起動は出来ないという事は理解していますが、
同時ではない形での複数端末での利用は可能でしょうか…？

本日テスト運用すべくレンタルした端末からログインをしようとした所エラーでログインできませんでした。
更に、その後自分のＰＣでもログインが出来なくなってしまいました。
（サーバーとの通信に失敗しましたというメッセージ）
自分のＰＣ側のkabuステーションを起動したままもう一つの端末側でログインを試みてしまったのが原因かもしれません。
いずれにしても自分のＰＣでのログインができるようにするためにはどうすればいいのか困っている状況です。

ご回答の程、宜しくお願いいたします。

**Comment by mik2008** [comment]
ログインが出来なかった件、先ほど解決したようです。
土日のサーバメンテナンスが関係あったのかもしれません。
（レンタルサーバーの端末からも無事にログインできました）

**Comment by cyber-minion** [comment]
同時ではない形での複数端末での利用に関しては、あと勝ちしますので、先行してログインしていたカブステのログインセッションは切断される仕組みになっております。
ツール上は画面更新等されますが、ログインセッションが切れているため、注文情報の更新や、発注処理は実施されません。

**Comment by yasuyuki-nakazawa** [comment]
補足します
既に回答がある通り、複数端末による起動は可能ですが、ログインセッションが有効なのは最後にログインしたクライアントのみです
他クライアントからはログアウトされた状態となります
ログアウト状態ですと、API接続自体がリジェクトされますので、直情報の目視確認は可能ですが、クライアントからの注文処理、API利用はできません

**Comment by cyber-minion** [comment]
解決済みのようですので、クローズさせていただきます。
