### ISSUE TITLE
【要望】リファレンスの /sendorder  FundType 説明文について

### ISSUE THREAD

**Issue by kc-api-f** [kabucom/kabusapi#51]
「11	信用取引(新規 と 返済)」の説明ですと、「信用返済」指定時に迷うので、変更を要望いたします。

> ※現物売、信用返済の場合は「' '(指定なし)」を指定する。
> (半角スペース2つ) 指定なし
> 11	信用取引

を

(半角スペース2つ) 現物売、信用返済
11 信用新規

とでもしていただけると安心です。ご検討いただけると幸いです。

**Comment by yasuyuki-nakazawa** [comment]
こちら、変更させて頂きます。
ご意見ありがとうございます。

**Comment by kc-api-f** [comment]
ご回答ありがとうございました。

**Comment by kc-api-f** [comment]
ご回答ありがとうございました。

**Comment by kc-api-f** [comment]
ご回答ありがとうございました。

**Comment by kc-api-f** [comment]
FundType の説明文更新を確認しました。
頭の回転に問題がある利用者(私)からの要望を意識しての更新、
誠にありがとうございました。

…私の記憶違いかもしれませんが、 DelivType の説明文が更新されていて、

> ※現物買は〇〇
> ※現物売は△△
> ※信用新規は□□
> ※信用返済は▽▽

この4パターンで順に注釈がありました。この方式がわかりやすいと感じ、
FundType の説明文でも同様となっていれば…と感じました。

私の要望を取り消しますので、あるべき説明文へ更新(元に戻す)していただければと存じます。
細かい事でご面倒をおかけし、申し訳ございませんでした。

**Comment by yasuyuki-nakazawa** [comment]
FundTypeも更新させて頂きました。
以後、パターンがあるものはそのパターンをそれぞれ記載させて頂きます
