### ISSUE TITLE
【不具合】kabu_STATION_API.yamlの定義ミス

### ISSUE THREAD

**Issue by hiuchida** [kabucom/kabusapi#510]
OpenAPI定義ファイルから、javaのクライアントおよびサーバーをジェネレートしたところ、2点見つかりました。
自己解決していますが、情報共有します。

■[必須] 不具合事象(概要)：swagger editorでエラーメッセージが表示される。
■[必須] 本来想定されるアクションと事象：/margin/marginpremium/{symbol}に対してパラメータ名がSymbolでなくsymbolであるべき。
■[必須] 不備発生時刻（常時の場合は、常時で記載ください)：常時
■[任意] お使いの環境(OS、Excelのバージョン等)、サンプル(Macro、アドインのバージョン）：qiita記事を参照
■[任意] 不備部分のログ：qiita記事を参照
→https://qiita.com/hiuchida/items/73b7fc846d4c9501ef2f#swagger-editor

■[必須] 不具合事象(概要)：swagger editorからGenerate Server/springを生成した際にコンパイルエラーとなるソースが生成される。
■[必須] 本来想定されるアクションと事象：サンプルデータがOpeningPriceTime: 8"2020-07-22T09:00:00+09:00"と余計な8が付いている。
■[必須] 不備発生時刻（常時の場合は、常時で記載ください)：常時
■[任意] お使いの環境(OS、Excelのバージョン等)、サンプル(Macro、アドインのバージョン）：qiita記事を参照
■[任意] 不備部分のログ：qiita記事を参照
→https://qiita.com/hiuchida/items/5944a704028a8f4ceafa#%E3%82%B3%E3%83%B3%E3%83%91%E3%82%A4%E3%83%AB%E3%82%A8%E3%83%A9%E3%83%BC

**Comment by cyber-minion** [comment]
> /margin/marginpremium/{symbol}に対してパラメータ名がSymbolでなくsymbolであるべき。


こちらについて確認して回答いたします。

> サンプルデータがOpeningPriceTime: 8"2020-07-22T09:00:00+09:00"と余計な8が付いている。

こちらは昨日の更新にて修正されております。再度ご確認いただけますでしょうか。

**Comment by yasuyuki-nakazawa** [comment]
ご指摘ありがとうございました

**Comment by cyber-minion** [comment]
リファレンスを更新いたしました。ご確認いただければと思います。

**Comment by cyber-minion** [comment]
こちら対応済ですので、クローズさせていただきます。
