### ISSUE TITLE
【質問】sendorderの引数のClosePositionsの配列に、Qtyが0の要素があると、{'Code': 8, 'Message': '決済指定内容に誤りがあります'}になりますでしょうか

### ISSUE THREAD

**Issue by snowballrichdad** [kabucom/kabusapi#512]
#470 に関連した質問です。
sendorderの引数のClosePositionsの配列に、positionsで返却された値を反映して指定しています。
しかし、本日、sendorderの引数のClosePositionsの配列に建玉IDの数量が0の引数を含んだ発注をした場合、
{'Code': 8, 'Message': '決済指定内容に誤りがあります'}が返却されました。
そういう仕様でしょうか？それても他にエラーとなった原因があるのでしょうか？
※ もしそういう仕様なら、positionsでは数量が0の建玉IDも返却されているので違和感があります。

■KabuS_20220405.log
09:45:59.1931,I,6004,0018 Recv DistributeMessage = [ID=20220405G02N69075390,RecType=3,State=3,Qty=,Price=,SeqNum=8]
09:45:59.1931,I,6004,0017 OrderDetail.ID=20220405G02N69075390 UpdTime=04/05/2022 09:45:58
09:45:59.1931,I,6004,0017 ID=E2022040501619,Symbol=1568,Exchange=1,Side=1,MarginTradeType=1,OpenQty=0.0,LeavesQty=0.0,HoldQty=0.0
09:45:59.1931,I,6004,0017 ID=E202204050161A,Symbol=1568,Exchange=1,Side=1,MarginTradeType=1,OpenQty=40.0,LeavesQty=40.0,HoldQty=0.0
09:45:59.1931,I,6004,0017 UpdateOrderAndDetail Order.ID=20220405A02N69075382
09:45:59.1931,I,6004,0017 UpdatePosition=ID=**E2022040501619**,Symbol=1568,Exchange=1,Side=1,MarginTradeType=1,**OpenQty=0.0,LeavesQty=0.0**,HoldQty=0.0
09:45:59.1931,I,6004,0017 UpdatePosition=ID=**E202204050161A**,Symbol=1568,Exchange=1,Side=1,MarginTradeType=1,**OpenQty=40.0,LeavesQty=40.0**,HoldQty=0.0
…
09:45:59.7310,I,6004,0007 ワンショットチェック : 1568/T/ＴＯＰＩＸブル２倍上場投信/1 : amount=10000, qty=
09:45:59.7310,I,6004,0007 KabuSApiManager.PreRelationCheck=CHECK_OK
09:45:59.7320,I,6004,0007 発注パラメータ：[返済] ＩＯＣ指値24,280円
09:45:59.7320,I,6004,0007 OrderManager.Order Start:OrderParam: Account=xxxxxxxx,CheckMode=1,Symbol=1568,Exchange=1,SecurityType=1,Side=2,CashMargin=3,MarginTradeType=1,OrderCapacity=,Price=24280.0,Qty=40.0,OrdType=6,AdjustPrice=False,SellingShot=DelivType=2,FundType=11,AccountType=4,EffectiveDay=20220405,ExpireDay=20220405,Trigger=[],OrderReferenceCommand=[],ClosePositions=[ID=**E2022040501619**,Type=1,**Qty=0**|ID=**E202204050161A**,Type=1,**Qty=40**|],PriceType=2,TimeInForce=0,ExpireSession=0,Password=xxx,FrontInfo=0,UsePoint=FrontInfo=[Key=FrontChannelID/Value=240,Key=Trader/Value=000000A7,Key=Channel/Value=0,Key=ClientCode/Value=10.20.243.56,Key=Branch/Value=000,]
09:45:59.7320,I,6004,0007 OrderManager.Order Start:OrderParam: Account=xxxxxxxx,CheckMode=1,Symbol=1568,Exchange=1,SecurityType=1,Side=2,CashMargin=3,MarginTradeType=1,OrderCapacity=,Price=24280.0,Qty=40.0,OrdType=6,AdjustPrice=False,SellingShot=DelivType=2,FundType=11,AccountType=4,EffectiveDay=20220405,ExpireDay=20220405,Trigger=[],OrderReferenceCommand=[],ClosePositions=[ID=E2022040501619,Type=1,Qty=0|ID=E202204050161A,Type=1,Qty=40|],PriceType=2,TimeInForce=0,ExpireSession=0,Password=xxx,FrontInfo=0,UsePoint=FrontInfo=[Key=FrontChannelID/Value=240,Key=Trader/Value=000000A7,Key=Channel/Value=0,Key=ClientCode/Value=10.20.243.56,Key=Branch/Value=000,]
09:45:59.7700,I,6004,0007 OrderManager.Order End  :Result=8,ID=,ClOrdID=,Detail=,ResultMessage=[Key=KC_CommissionTable/Value=1200,]
09:45:59.7700,I,6004,0007 **発注結果 : Result=8**,ID=,ClOrdID=,Detail=,ResultMessage=[Key=KC_CommissionTable/Value=1200,]

**Comment by yasuyuki-nakazawa** [comment]
確認いたします

**Comment by cyber-minion** [comment]
口座番号が入っていますので、マスクさせていただきました。

**Comment by cyber-minion** [comment]
残高照会APIは、カブステ起動中に子建玉を全返済しても、レスポンスが返ってくる仕様となっています。
全返済した場合は、残数量=0が返ってきます。返済注文に全返済した建玉IDを指定した場合は、既に返済済みのため、「決済指定内容に誤りがあります」エラーとなります。

**Comment by snowballrichdad** [comment]
了解しました。ありがとうございました。
