### ISSUE TITLE
【質問】TCPストリーム区切りについて

### ISSUE THREAD

**Issue by sanwa-starch-koji-yamaguchi** [kabucom/kabusapi#513]
PUSH配信のTCPストリームの区切りはどのようになっているのでしょうか。(CRLFや固定バイトなど)
ご教授頂けると幸いです。

**Comment by yasuyuki-nakazawa** [comment]
送信電文のセパレータの質問でしょうか。
確認いたします

**Comment by sanwa-starch-koji-yamaguchi** [comment]
仰るとおり電文セパレータについての質問です。
お手数お掛けしますが、よろしくお願いします。

**Comment by yasuyuki-nakazawa** [comment]
カブステAPIのPush配信はMicrosoftライブラリのWebSocketを使っているので、区切りはWebSocketの仕様に従います。
WebSocket通信の確立はライブラリ側で処理されるかと思いますので、電文の区切りは特に気にしなくて良いのではないでしょうか。

**Comment by sanwa-starch-koji-yamaguchi** [comment]
ご確認ありがとうございました。
RFC6455の仕様で動作していることを確認しましたので、クローズさせて頂きます。
