### ISSUE TITLE
【不具合】[WinError 10054] 既存の接続はリモート ホストに強制的に切断されました。

### ISSUE THREAD

**Issue by kitty2117** [kabucom/kabusapi#514]
■[必須] 不具合事象(概要)
kabusapiAPIでpush配信を受けるときに
”[WinError 10054] 既存の接続はリモート ホストに強制的に切断されました。”
と表示されて止まる

■[必須] 本来想定されるアクションと事象
銘柄登録で３０件を登録してそのpush情報を取得する

■[必須] 不備発生時刻（常時の場合は、常時で記載ください)
常時発生

■[任意] お使いの環境(OS、Excelのバージョン等)、サンプル(Macro、アドインのバージョン）
Winodws10、Python3.10
----------以下push受信部分のスクリプト抜粋　ほぼサンプルそのまんまです。
TM = ThreadPoolExecutor(max_workers=6)
#TM = ProcessPoolExecutor(max_workers=16)

print('push受信スタート')

# PUSH受信

def on_message_log(message):
    global RECORD_FOLDER,TODAY
    message = message.rstrip()
    mes = json.loads(message)
    record = f'{RECORD_FOLDER}\{TODAY}.push.{mes["Symbol"]}.record'
    record_all = f'{RECORD_FOLDER}\{TODAY}.push.all.record'
    _echo(f'{message}', 'a', record) # _echoはファイルへの一行書き出しモジュール
    _echo(f'{message}', 'a', record_all)
    sc = mes["Symbol"]
    pp = mes["CurrentPrice"]
    ttt = re.findall(r'\d+',  mes["CurrentPriceTime"])
    tt = f'{ttt[0]}{ttt[1]}{ttt[2]}{ttt[3]}{ttt[4]}{ttt[5]}'
    vv = 100
    tick = [sc, tt, pp, vv]

def on_message(ws, message):
    global TM
    print('--- RECV MSG. --- ')
    print(message)
    #_thread.start_new_thread(on_message_log, (message))
    pp = TM.submit(on_message_log, message)

def on_error(ws, error):
    print('--- ERROR --- ')
    print(error)

def on_close(ws):
    print('--- DISCONNECTED --- ')

def on_open(ws):
    print('--- CONNECTED --- ')

    def run(*args):
        while(True):
            line = sys.stdin.readline()
            if line != '':
                print('closing...')
                ws.close()
    _thread.start_new_thread(run, ())

url = f'ws:{IPPORT}/kabusapi/websocket'　#IPPORTはkabuステーションのIPとポート番号
# websocket.enableTrace(True)
ws = websocket.WebSocketApp(url,
                            on_message=on_message,
                            on_error=on_error,
                            on_close=on_close)
ws.on_open = on_open
ws.run_forever()
-----------------スクリプト抜粋終わり

■[任意] 不備部分のログ
なし

所見
なんか、pythonだと処理能力が絶対的に不足してしまうようです。
取引の多い銘柄を３件程度登録まではいけましたが、4coreCPUでスクリプトのCPU使用率が２５％になってました
マルチプロセスも考慮しましたが、銘柄比較などをする場合のプロセス間通信とかオーバーヘッドとか、複雑になってメンテできないと思う
テクニカル分析まですると、せいぜい２件登録な気がする

ここからは【要望】
Benchmarkのページとかつくれないでしょうか？
CPUの種類と使用言語とpush情報を毎秒いくつまで受信できるか？のランキングページ
そういうページがあれば、pythonで４０銘柄監視＆テクニカル分析とか、
そういう無茶な構想のもとに開発する人が減る気がする
あるいは、corei7でC#なら２０件push受信くらいとかそういう目安を出すことはできないでしょうか？
あと、pushは一つのスクリプトでしか受けられないとの事ですが、それを複数のスクリプトで受けれるようにすることはできないでしょうか？そうすれば、４coreCPUで８銘柄情報取得とテクニカル分析とかできると思う

**Comment by kitty2117** [comment]
なんか投稿でフォントサイズが大きくなって太字になってるところありますが、
たぶん、スクリプトのコメントの＃のとこだと思うけど、
GitHUBってそういう仕様なんでしょか？

**Comment by tsuchinaga** [comment]
マークダウン記法ですね

`#` は見出しで、HTMLでいうところのh1などです

**Comment by cyber-minion** [comment]
こちらと同じ事象でしょうか。
https://github.com/kabucom/kabusapi/issues/284#issuecomment-1087000764

**Comment by kitty2117** [comment]
> こちらと同じ事象でしょうか。 [#284 (comment)](https://github.com/kabucom/kabusapi/issues/284#issuecomment-1087000764)

はい、同じです
内容を整理して、追加で負荷調べたので、その結果も書いたつもりです
これ、Pythonの限界と自分のパソコンの限界で不可能だろうなという結論に、、
.NET frameworkは単に取引少ない時間だっただけ
インタプリタだと処理落ち不可避かと

**Comment by kitty2117** [comment]
> マークダウン記法ですね
> 
> `#` は見出しで、HTMLでいうところのh1などです

マークダウン、なんか聞いたことあります
バクでないならいいかな

**Comment by hori-ryota** [comment]
貼ったコードをすごい雑にチラ見した感じだと、少なくとも `_echo` が都度ファイルをopen, closeしていて遅いとかやってそうな。

on_messageをprofilerやbenchmarkで調査してみるといいかもですね

**Comment by kitty2117** [comment]
> 貼ったコードをすごい雑にチラ見した感じだと、少なくとも `_echo` が都度ファイルをopen, closeしていて遅いとかやってそうな。
> 
> on_messageをprofilerやbenchmarkで調査してみるといいかもですね

ご指摘の通り都度opencloseしてる、月曜日にログの出力をしないのはやってみます
Pythonは言語仕様でマルチスレッド各々にcpuを割り当てるのはできないそうで、on_messageでいかにも並列処理ぽくなってるけど、cpu一つでしか動いてないです
コンパイルのc#とかGoに言語切り替えようかな

インタプリタはRESTの無限ループ情報取得にはいいけど、pushで使うにはきついのかも

**Comment by kitty2117** [comment]
少し過去ログを読んでいたのですが、
#285のsakurajaneさんがC++、#284のhori-ryotaさんがGolang
pythonがインタプリタなの関係ないのかな
ここ２，３日でpushされた情報の解析を少ししてみたので書き込んでみます
（１）push登録２件
毎秒８～１０件のpush配信、WEBSocket切断なし
（２）push登録27件
毎秒８～13件のpush配信、WEBSocket切断発生

あと、気になる事象があります
push配信される情報がたまに千切れていることがある？
----------------以下pushログ取得スクリプト　websocketのon_messageのモジュールから呼び出してます
def on_message_log(message):
    global RECORD_FOLDER, TODAY
    message = message.rstrip()

    try:
        mes = json.loads(message)
    except json.decoder.JSONDecodeError as e:
        ERR = ERR+1
        _echo(message, 'a', 'err.log')
        # return

    #record = f'{RECORD_FOLDER}\{TODAY}.push.{mes["Symbol"]}.record'
    record_all = f'{RECORD_FOLDER}\{TODAY}.push.all.record'
    #_echo(f'{message}', 'a', record)
    _echo(f'{message}', 'a', record_all)
    logtime = datetime.datetime.now().strftime('%H%M%S')
    _echo(f'{logtime}, {message}', 'a', f'{record_all}.time')
-----------------スクリプト終わり

おかしなログ出力あったので上げておきます
jsonを出力時間と一緒に出力しているだけなのですが

-----------------おかしなログの抜粋　１
022-04-13T14:00:01+09:00","SecurityType":1}
-----------------おかしなログの抜粋　２
9:00","SecurityType":1}
-----------------おかしなログの抜粋　３
e":17350.0,"LowPriceTime":"2022-04-13T09:00:00+09:00","SecurityType":1}
-----------------ログ抜粋終わり
pushされたmessageの頭が消えてしまって、後ろのごく一部しかログに出力されない、切れる場所も一定していない
あと、json変換のエラートラップしてログを出しているはずなんですが、なぜが'err.log'が作成されていない

**Comment by hori-ryota** [comment]
千切れているのは受信時ではなくマルチスレッドで同じファイルに出力しようとしているのにflushとかをうまくやれていない、みたいな出力側の問題の可能性ありそうですね、勘ですが

**Comment by kitty2117** [comment]
pushされた情報のファイル出力やめただけで、pushの受信可能数は結構増えました
毎秒１３件くらい、あまりいいＣＰＵではないので最新のＣＰＵなら倍くらいいけるんじゃないかな
CPU使用率は２３～２４％で少し余裕がある（4core4threadCPUなので上限は25%）
テクニカル分析いれたら、また、おちるだろうけど、
pythonだと、pushは１，２銘柄登録くらいでしょうか？
それから売買の処理も結構時間かかるのかな？

pythonでのpushでのトレードは基本的に無理で、RESTで処理するほうが良いかも
ただ、処理のフローやClassLibraryの構造なんかは他の言語でもいけると思うから
pythonで試作して、CとかＣ＃とかＧｏとかＪＡＶＡに移植する感じがいいのかな

あと、相談したいことがあります
偶に処理落ちして切断されますが、その場合の自動復帰の処理ってなんかありますか？
今のところ、エラー発生したら、全注文キャンセルと全ポジション解消をいれようかと思っていましたが
エラー処理は特にしないでこれじゃだめなのかな？websocketの部分を無限ループにします。
------------------以下スクリプト引用------------------------
def on_message(ws, message):
    global TM
    print('--- RECV MSG. --- ')
    mes = json.loads(message)
    log = datetime.datetime.now().strftime('%H%M%S')+' ' + \
        str(mes['Symbol'])+'  ' + str(mes['CurrentPriceTime']) + \
        '  ' + str(mes['CurrentPrice'])
    print(log)
    # print(message)
    #_thread.start_new_thread(on_message_log, (message))
    #pp = TM.submit(on_message_log, message)

def on_error(ws, error):
    print('--- ERROR --- ')
    print(error)

def on_close(ws):
    print('--- DISCONNECTED --- ')

def on_open(ws):
    print('--- CONNECTED --- ')

    def run(*args):
        while(True):
            line = sys.stdin.readline()
            if line != '':
                print('closing...')
                ws.close()
    _thread.start_new_thread(run, ())

while True:    # websocketを無限ループ
    url = f'ws:{IPPORT}/kabusapi/websocket'
    # websocket.enableTrace(True)
    ws = websocket.WebSocketApp(url,
                                on_message=on_message,
                                on_error=on_error,
                                on_close=on_close)
    ws.on_open = on_open
    ws.run_forever()
    # エラーログ
    print('*************************')
    print('*************************')
    print('***  ERROR   ************')
    print('*************************')
    print('*************************')
    log = datetime.datetime.now().strftime('%H%M%S')
    err=f'{log}  処理落ち発生　リスタート'
    _echo(err,'a','failure_error.log')

------------------引用スクリプト終わり--------------------------
なんか問題おこるかな？処理落ちしても気にしない作戦

**Comment by kitty2117** [comment]
pushされた情報のファイル出力やめただけで、pushの受信可能数は結構増えました
毎秒１３件くらい、あまりいいＣＰＵではないので最新のＣＰＵなら倍くらいいけるんじゃないかな
CPU使用率は２３～２４％で少し余裕がある（4core4threadCPUなので上限は25%）
テクニカル分析いれたら、また、おちるだろうけど、
pythonだと、pushは１，２銘柄登録くらいでしょうか？
それから売買の処理も結構時間かかるのかな？

pythonでのpushでのトレードは基本的に無理で、RESTで処理するほうが良いかも
ただ、処理のフローやClassLibraryの構造なんかは他の言語でもいけると思うから
pythonで試作して、CとかＣ＃とかＧｏとかＪＡＶＡに移植する感じがいいのかな

あと、相談したいことがあります
偶に処理落ちして切断されますが、その場合の自動復帰の処理ってなんかありますか？
今のところ、エラー発生したら、全注文キャンセルと全ポジション解消をいれようかと思っていましたが
エラー処理は特にしないでこれじゃだめなのかな？websocketの部分を無限ループにします。
--------------------------

def on_message(ws, message):
    global TM
    print('--- RECV MSG. --- ')
    mes = json.loads(message)
    log = datetime.datetime.now().strftime('%H%M%S')+' ' + \
        str(mes['Symbol'])+'  ' + str(mes['CurrentPriceTime']) + \
        '  ' + str(mes['CurrentPrice'])
    print(log)
    # print(message)
    #_thread.start_new_thread(on_message_log, (message))
    #pp = TM.submit(on_message_log, message)


def on_error(ws, error):
    print('--- ERROR --- ')
    print(error)


def on_close(ws):
    print('--- DISCONNECTED --- ')


def on_open(ws):
    print('--- CONNECTED --- ')

    def run(*args):
        while(True):
            line = sys.stdin.readline()
            if line != '':
                print('closing...')
                ws.close()
    _thread.start_new_thread(run, ())


while True: # 無限ループ
    url = f'ws:{IPPORT}/kabusapi/websocket'
    # websocket.enableTrace(True)
    ws = websocket.WebSocketApp(url,
                                on_message=on_message,
                                on_error=on_error,
                                on_close=on_close)
    ws.on_open = on_open
    ws.run_forever()
    # エラーログ
    log = datetime.datetime.now().strftime('%H%M%S')
    err=f'{log}  処理落ち発生　リスタート'
    _echo(err,'a','failure_error.log')

---------------------------------------
多少おちても気にしない処理です

**Comment by kitty2117** [comment]
少し情報追加

現在、restスクリプトとpushスクリプトの２本を走らせて記録するテストしています。
restスクリプトとpushスクリプトはそれぞれ別のCPUに割り当てられて動いていますが、
CPU負荷がそれぞれ１％行きません

以前push受信テストで使っていたスクリプトではCPU使用率が２５％近くまであがります
新しいpushスクリプトは古いpushスクリプトのほぼコピペなので、なぜそんな事になるのか理解できない。。。

Python 3.10.3
Windows10 OSビルド 19043.1645

**Comment by kitty2117** [comment]
ユーザースクリプトのバグと思う
閉じておきます
