### ISSUE TITLE
【質問】米国ETFの板情報を取得するには

### ISSUE THREAD

**Issue by sinsaku1973** [kabucom/kabusapi#515]
米国ETFの板情報を取得するにはkabusapi_board.pyのURLはどのように設定したらよいでしょうか。
そもそも、提供事態がされてないのでしょうか。

**Comment by yasuyuki-nakazawa** [comment]
現状ですが、カブステAPIは、米株未対応です。
対応時期は未定ですが、検討中でございますので、目途付けできた時点で情報連携させていただきます

**Comment by sinsaku1973** [comment]
ありがとうございます。
承知しました。
早めに実装いただけると助かります。
