### ISSUE TITLE
【要望】気配情報の取得件数を増やすことはできないでしょうか

### ISSUE THREAD

**Issue by msk-fukuda** [kabucom/kabusapi#516]
kabusapi/board にて取得できる気配情報に関しまして、売り気配と買い気配の値はそれぞれ10件ずつ取得するような仕組みになっておりますが、件数が少なく活発に取引されている銘柄では±0.5％にも満たない範囲の値になってしまいます。

気配情報を解析して使用するような処理を組みたいと考えており、可能でしたら買い気配売り気配それぞれで50件ほど取得できるとありがたいのですが、以下のような拡張をご検討いただくことは難しいでしょうか。

A ) kabusapi/board のSell,Buy のパラメータを10件以上取得できるよう拡張いただく
B ) kabusapi/board 以外に気配取得に特化したAPIを追加していただく

お忙しいところ恐れ入りますが、ご検討いただけますと幸いです。

**Comment by yasuyuki-nakazawa** [comment]
システムの内部の状況となって恐縮ですが、
上下１０本を超過する場合は、フル板からの情報取得となってしまいます。
現在、カブステーションもフル板を出力する枚数を絞っているのはシステム負荷を勘案した結果です（徐々に増やしておりますが）
そのため、上下１０本を超過した情報連携となると、内部的にフル板情報で対応する必要があるため、非常に実現が難しいじょうきょうとなります。
ご要望としては理解しておりますが、諸検討のため、お時間頂戴いたします。

また、当該機能の提供にあたっては、別途課金体制を検討する等もございます。

**Comment by msk-fukuda** [comment]
ご返答ありがとうございます。

システム負荷の都合上難しい旨、承知いたしました。

別途課金体制もありえるとのことですが、
機能提供された際には試してみたいと考えておりますので、引き続きご検討いただけますと幸いです。

ご返答いただけたことで区切りがついておりますので、本件はクローズさせていただきます。
