### ISSUE TITLE
【要望】PUSH配信について

### ISSUE THREAD

**Issue by gfd05600** [kabucom/kabusapi#517]
PUSH配信について、レスポンスデータでランキング情報・銘柄情報で取れるデータ制限されていますが、全てリアルタイムでPUSH配信できないでしょうか？。たとえば、Upper-limit-plice, Lower-limit-price、出来高、売買高急増、値上がり率、値下がり率　等他。

**Comment by cyber-minion** [comment]
ランキング情報、銘柄情報はPUSH配信の対象ではありません。
PUSH配信のレスポンスについて、[こちら](https://kabucom.github.io/kabusapi/ptal/push.html)にてご確認いただければと思います。

**Comment by gfd05600** [comment]
カブコム証券さんには失礼ですがＡＰＩ使えない。

**Comment by cyber-minion** [comment]
ご不便おかけし申し訳ございません。PUSH情報の充実はご要望として承り、検討させていただきます。
開発リソース等の兼ね合いで、順次対応させていただきます。

**Comment by gfd05600** [comment]
「ご要望お寄せ下さい。」なんて言わないでほしい。
