### ISSUE TITLE
【要望】カブステ銘柄登録数について

### ISSUE THREAD

**Issue by gfd05600** [kabucom/kabusapi#518]
カブステ銘柄登録については50名柄になっていますが、ＪＰＸ400銘柄登録しＰＵＳＨ配信でリアルタイムで最適な投資対象の抽出したいので登録数を撤廃出来ないでしょうか？。せめてＴＯＰＩＸ100銘柄くらいは登録できるようご検討お願いいたします。

**Comment by cyber-minion** [comment]
ご不便おかけし申し訳ございません。当制限に関しては改善を検討させていただきます。
