### ISSUE TITLE
【要望】/sendorder (及び/cancelorder) のPasswordパラメータの任意化等について　→【未対応】

### ISSUE THREAD

**Issue by kc-api-f** [kabucom/kabusapi#52]
外部プログラムに取引パスワード情報を預ける事と、
本番用の環境を十分に検証することなくザラ場でkabuステーションAPIを活用する事について、
その度胸がない状態なのでお願いがあります。

つまり、
外部プログラムに取引パスワード情報を預ける事なく、
本番用の環境に限りなく近い形でkabuステーションAPIを試用検証できる手段が欲しいです。

具体的には、起動が必須であるkabuステーションに対して、
注文確認ダイアログをポップアップする(その理由文字列やURL付き)までを外部プログラムで行い、
注文を実行するかどうかの最終決定(と取引パスワード入力)のみを人間がkabuステーションを操作して行えるような
/sendorder拡張(か/promptorderのようなもの)を要望いたします。

ご検討を頂けると幸いです。

**Comment by yasuyuki-nakazawa** [comment]
スクリプトやアドイン経由で発注リクエストをkabuステーションに行った際に、自動ではなく、kabuステーション側で取引パスワードの入力と確認を行いたいという要望と理解いたしました。
自動化という趣旨からは外れてしまいますが、最終確定を人間が行う手段がほしいということは要望として検討させて頂きます。

**Comment by kc-api-f** [comment]
理解し辛い要望文をご確認くださり、ありがとうございました。
その通りです。

**Comment by kc-api-f** [comment]
おっしゃるとおり、kabuステーションの入力補助のような感じになってしまいますが、
kabuステーションの「既存機能」であるリスト発注を「APIで活用」できるのは非常にありがたいです。
個人的に求めている機能は、これだと感じました。

実装はなかなか難しいかと存じますが、ご検討いただけましたこと、感謝申し上げます。
ありがとうございました。
