### ISSUE TITLE
【質問】ログイン時のセッションについて

### ISSUE THREAD

**Issue by hieeeee** [kabucom/kabusapi#522]
kabuステーションAPIのセッションは後勝ちだと認識していますが、バッチをパラレル実行した場合、セッションはどのようになるのでしょうか？
例えば下記のような状況です。
・クライアントは1台
・cron等で5バッチを同時実行
この場合でも後勝ちとなり、一番最後のバッチが優先されるのでしょうか？
それともクライアント単位でセッションが管理され、5バッチ全て正常終了となるのでしょうか？

**Comment by tsuchinaga** [comment]
常に後勝ちで、有効なのは1つだけです

なので、一番最後に実行されたバッチだけが有効になります

**Comment by hieeeee** [comment]
やはりパラレル実行は出来ず、単一実行のみということですね。
承知しました。
ご回答ありがとうございました。
