### ISSUE TITLE
【質問】REST API 情報系の流量制限、発注系の流量制限、その他について

### ISSUE THREAD

**Issue by kitty2117** [kabucom/kabusapi#525]
おせわになります。
流量制限について確認させてください

１．情報系の流量制限について
情報系の流量制限は情報のタグでくくられているAPIで
時価情報・板情報、銘柄情報、注文約定照会、残高照会、先物銘柄コード取得
オプション銘柄コード取得、詳細ランキング、為替情報、規制情報、優先市場、ソフトリミット、プレミアム料取得
で、この機能は毎秒１０回しかつかえない
ここで要求された銘柄は自動的に登録銘柄に登録される、例えば、9104の規制情報を取得しても9104が登録銘柄に登録されるし、9101の優先市場情報を取得しても登録銘柄に登録される、
詳細ランキングや残高照会、注文約定照会ではresponsがリスト形式のようですが、これはリストのすべての銘柄が登録銘柄に登録される？

２．発注系の流量制限について
注文発注（現物・信用）、注文発注（先物）、注文発注（オプション）、注文取消
この機能は毎秒５回しか使えない。ただし、二銘柄三銘柄、例えば、1570,2038,6920の三銘柄各々に５回で毎秒計１５回の操作をしても問題はない

３．取引余力のタグ
取引余力のタグにも流量制限がありますが、これは情報系や発注系の流量制限とは別枠と考えていいでしょうか？

４．登録銘柄のタグ
登録銘柄のタグのAPIには流量制限はなく、時価情報・板情報（情報系）を取得直後に登録銘柄解除を実行しても
情報系の流量には影響しないと考えていいでしょうか？

REST APIをたたいて何かしたら、その銘柄が銘柄登録されるのでそれを削除しないとPUSH系の処理がパンクしそうです。
登録銘柄管理が結構大変になりそうな気がします。
【要望】ですが、銘柄登録とREST APIは分割できないでしょうか？
PUSHする銘柄だけ銘柄登録するとか、REST用銘柄登録とPUSH用銘柄登録を作るとか

**Comment by yasuyuki-nakazawa** [comment]
１.登録銘柄の対象になる、ならないに関しては、整理してリファレンスを更新させていただきます。
　併せて、こちらにて回答させていただきます
２.発注の流量制限としては、銘柄の別を問わずに5件となります。
３,４.流量制限対象に関しては再度確認いたします

**Comment by yasuyuki-nakazawa** [comment]
RESTに関しての銘柄登録の要望に関してですが、
当該APIはご存じのとおり、カブステーションとのインターフェースになっております。
カブステーション上に存在しない銘柄に関しては、サーバー側に情報を取得に行く必要があり、RESTで都度のサーバアクセスを避けるために、APIとして利用する銘柄情報に関しては、カブステの画面枠に表示されている情報とは分けて、銘柄を裏側で取得、管理しています。
そのため、PUSH、RESTの別をとらず、扱える銘柄を絞ることで、サーバの負荷を抑えるという方針をとっておる次第で、当点に関しては、ご理解、ご了承いただけると幸甚です

**Comment by kitty2117** [comment]
> RESTに関しての銘柄登録の要望に関してですが、 当該APIはご存じのとおり、カブステーションとのインターフェースになっております。 カブステーション上に存在しない銘柄に関しては、サーバー側に情報を取得に行く必要があり、RESTで都度のサーバアクセスを避けるために、APIとして利用する銘柄情報に関しては、カブステの画面枠に表示されている情報とは分けて、銘柄を裏側で取得、管理しています。 そのため、PUSH、RESTの別をとらず、扱える銘柄を絞ることで、サーバの負荷を抑えるという方針をとっておる次第で、当点に関しては、ご理解、ご了承いただけると幸甚です

早い返信ありがとうございます
流量の調査報告お待ちします。
要望に関しては、ユーザースクリプトとユーザー側のPCの負荷が大きくなるので、なんかいい方法ないかな？
たとえば kabuステで保持してる登録銘柄テーブルにpushフラグのようなカラムを追加して、そこがONになってるとPUSH対象にするとか？（５０銘柄は５０銘柄のまま増えないけど）、そうするとkabuステの裏に控えるauKabuコムの基幹システム（名前なんでしょう？）には負荷が増えない気もします。
まぁ、可否はともかく、いろいろとよろしくお願いします。

追伸
あと、気になったのですが、プログラミングガイドのような物をつくって、流量とウエイト時間の事も書くとよいのかもしれない、例えば、RESTで板情報をとったら、0.05秒？くらいはウエイトいれないとエラーになることがありますとか
すでに、エラーで再送要求を何度もするスクリプト書いたり、毎秒１０銘柄登録してデータとって、毎秒１０銘柄登録削除するようなスクリプト書いてる人いるかもしれない。。。

**Comment by kitty2117** [comment]
今、試しに、銘柄登録５０で動かしてみましたが、
pythonではpushは受けれなくなりますね。数秒でディスコネクトしてる感じ
GolangとかC＋＋とかC＃じゃないとだめかも

もうひとつ、銘柄登録は３で、REST APIで情報取得は５０銘柄で情報取得後に登録解除をしてみました
フローは
1.listから證券コードsymbol取得
2. GET /board/{symbol}で情報取得
3. PUT /unregister でsymbolを削除
4. 0.15秒スリープ
5. １に戻る
unregisterのレスポンスがかなりおそくて実用性は低いですね。
１～３秒くらいかかってる感じ
流量制限するなら、この銘柄登録かもしれません、3秒に一回とか。。。

RESTで600銘柄監視は無理っぽい

**Comment by tsuchinaga** [comment]
これまでkabuステーションでどのようにして600銘柄監視してトレードされていたんですか？

ご理解の上だとは思いますが、kabuステーションAPIは名前の通りkabuステーションを操作するためのインターフェースです。
手動ではkabuステーションを利用してこのように実現していた。APIだとそれができない。改善してほしい。と道筋を立てたほうが話が通りやすいと思いますよ

**Comment by kitty2117** [comment]
> これまでkabuステーションでどのようにして600銘柄監視してトレードされていたんですか？

人間の100倍の銘柄をみて、人間の100倍のスピードでトレードできると思ってkabusapiAPIを始めてます、なぜならコンピュータだから。口座もkabusapiAPIの為に作ったので、kabuステーションで人手で取引したことないです

始まって1年ばかりの試みなので、いきなりできるとは思っていないし、自分も緩いスクリプトしか書けないし

tsuchinagaさんは、どう思って始めたのですか？何がしたくて始めたのですか？

PythonもAPIもよくわかってないので、いろいろ試してる感じです

そういう事でよろしくお願いします

**Comment by tsuchinaga** [comment]
僕はもともとkabucomを使ってグリッド戦略をやってたので、その自動化でkabuステーションAPIを利用しています。
細かい計算を含める高頻度の売買を自動化したいという目的で、スクリーニングとかデータ集め・分析に利用することは考えていません。

過去データや多くの銘柄のデータを必要とされている方はスクリーニングの課題を解決したいのだろうと思いますが、
そもそもkabuステーションはスクリーニングに適したツールじゃないんですよね。

pythonで何が出来て何が出来ないかは存じ上げないのでPUSHについての問題には触れませんが、
kabuステーションを利用して手動で出来ることは現在のRESTの流量で十分できると感じています。
※リアルタイム資産評価などAPIでサポートされていない機能もあって不満はありますが

**Comment by kitty2117** [comment]
> 過去データや多くの銘柄のデータを必要とされている方はスクリーニングの課題を解決したいのだろうと思いますが、 そもそもkabuステーションはスクリーニングに適したツールじゃないんですよね。

スクリーニングというか、動意づいた株をいち早く見つけたいんじゃないかと思います
所謂、いなご株
自分もそうだけど、いなごを見つけて乗っかる
そうすると低い頻度（REST頻度）で多くの株を見て、動き始めた株を高頻度（push頻度）で追いかけると都合がいい
でも、現状だと、低頻度と高頻度を銘柄別に分けることができない
いなごトレーダーがどれくらいいるかわからないけど、いなごトレーダーが儲かればau株コム証券も幸せになれる、沢山取引すれば手数料増えるし、他の金融商品も買うかもしれない
あるいは、いなごトレーダーなんてたいして収益にならないからスルーでいいやという判断になるかもしれないけど
でも、コンピュータの処理能力考えると、いなご狙ってる人はそこそこいるんじゃないかな、むしろコンピュータはいなごの為にあるのかもしれない

てな事を適当に書いてみます

**Comment by kitty2117** [comment]
混乱マークついてるので、
もう一回説明してみます。説明が下手で申し訳ない

スクリーニング自体は、スクリーニングできる株式サイトがあるので、そこでやります。
注目株一覧とか、○日のストップ高銘柄一覧とかから１００とか２００銘柄をリスト化します。
このリストを監視対象にして、RESTで３０秒に１回とか１分に１回データを取りに行きます。
それで、特買とか特売がついてるものや、急激に値段が上がったものや下がったもの、出来高が急増した物を探してきて、
pushして、取引対象にします。
日ばかりとかディトレードですね、そういう取引をコンピュータでやりたい人は多いのではないか？ということです。

で、現状のkabusapiだと監視リストが全部登録銘柄（PUT /register）になってしまいます。REST(GET /board/{symbol})で情報取得すると銘柄登録されてしまうから、
それで動意づいた株を見つけてpushしようとすると、監視リストの銘柄がすべてがpushされてしまい、処理ができなくなる、本来３０秒とか６０秒に一回情報とればいい銘柄まで毎秒何件も情報が送られて来るようになる
そこで、登録銘柄の一部の株だけpushする機能があるとうれしいという話です
登録銘柄数は現状５０ですが、この数も１００とか２００になれば、それだけ、動意づいた株を探しやすくなります。

**Comment by tsuchinaga** [comment]
いえ、僕の言っていることが伝わっていないみたいで混乱しています。
kabuステーションで手動で出来ることを自動化するためにkabuステーションAPIが使えますよ。と言っているだけで、
kabuステーションで出来ないことをkabuステーションで出来るようにしろ。auカブコムも儲けられるやろ。コンピュータはそのためにあるやろ。という論で話されてびっくりしています。

**Comment by tsuchinaga** [comment]
あまりにもissueの本筋と離れてしまったので、レスポンスはここまでとします。

@kitty2117 さん、横やり失礼しました。

**Comment by kitty2117** [comment]
ああ、そういう趣旨でしたか

ここは、ユーザーの意見を汲み取る場でもあるので、勝手いっていいと思います
無理なことは実現できないだかですから

じゃ終わりということで

**Comment by yasuyuki-nakazawa** [comment]
スクリーニングとしても利用していただからように、リアルタイム株価予測の提供を検討している点は補足いたします
出来高急増等もサーバー側で処理した内容をスクリーニングできますので、用途的にも合うかもしれません

**Comment by kitty2117** [comment]
> スクリーニングとしても利用していただからように、リアルタイム株価予測の提供を検討している点は補足いたします 出来高急増等もサーバー側で処理した内容をスクリーニングできますので、用途的にも合うかもしれません

リアルタイム株価予測の概要見ました。これがやりたかった奴です
既にあったのか、API公開楽しみにしています。

あと、Tick配信の実装のときに登録銘柄全部に送らないで指定した奴だけPUSHしてくれるとうれしいです。
ついでに板情報のPUSH配信も指定できるようになるとうれしい

**Comment by yasuyuki-nakazawa** [comment]
こちら、クローズさせていただきます
ご要望、ご意見はお気軽にご連絡くださいませ
