### ISSUE TITLE
【質問】ログファイル　%appdata%\KabuS\Log\APILog　は何ですか？

### ISSUE THREAD

**Issue by kitty2117** [kabucom/kabusapi#526]
%appdata%\KabuS\Log\APILog\PLAIN_20220427_11.log

このファイルはなんでしょうか？
ファイル名はPLAINは素データ？_20220427は日付、_11は時間
見た感じREST APIのリクエストとレスポンスが書いてあるように見えます

>07:57:38.0934,I,6848,0009 1ALNFIUgAlqkBnq57iijo5+urq0zJR7at ...
sshかなんかで暗号化されている？

>10:59:59.4198,I,2408,0007 【Board】(6920@1)
>10:59:59.4198,I,2408,0007 【Board】({"OverSellQty":324900.0, ...
これはGET \board\{symbol}の要求とレスポンス？

**Comment by yasuyuki-nakazawa** [comment]
plainは素データです。もう一つの方は暗号化データで基本的には利用しないものとなります。有事の際に素データと突き合わせを行うものとなります
ストレージが圧迫されるようでしたら、暗号化データを保存しない設定にされることを提案いたします

これらのログファイルはrestのリクエストとレスポンスが記録されています

**Comment by kitty2117** [comment]
> これらのログファイルはrestのリクエストとレスポンスが記録されています

自分のスクリプトで同じようなログを出すようにしていたので、これ見ればある程度わかるってことですね

ありがとうございます
