### ISSUE TITLE
【質問】kabuステーションAPIの利用規程の第3条18項の解釈について

### ISSUE THREAD

**Issue by hieeeee** [kabucom/kabusapi#527]
kabuステーションAPIの利用規程の第3条18項に「同一銘柄に対しての注文は 5 件を上限」との記載がありますが、当規定は同一銘柄に対しての注文が1日5件までという認識でしょうか？それとも同タイミングの注文が5件までというでしょうか？

**Comment by yasuyuki-nakazawa** [comment]
回答まで今しばらくお待ちくださいませ

**Comment by hieeeee** [comment]
こちら確認の進捗はいかがでしょうか？

**Comment by yasuyuki-nakazawa** [comment]
補足いたします。
同程度の価格帯に多数同一方向の注文があれば、板の占有率等を高い状態で約定しないケースが多数あれば疑念（見せ玉形態）を見られる可能性もあることを考慮すると、同時に5注文という一定の制限を設けたということも想定されるため、
両観点より、確認させていただいておりますので、少々お時間くださいませ。

**Comment by katskats** [comment]
「同一銘柄注文を1日5件」
それは本当ですか？?

と、なるとデイトレードで同一銘柄の売買は「1日5回以下」

1. 買い注文を1件入れる
　 買いが約定
2. 売り注文を1件入れる
　 売りが約定
3. 買い注文を1件入れる
　 買いが約定
4. 売り注文を1件入れる
　 売りが約定
5. 買い注文を1件入れる

　 APIの利用不可！！

使い物にならなくなりますが...

**Comment by hieeeee** [comment]
＞両観点より、確認させていただいておりますので、少々お時間くださいませ。
承知しました。ご確認お願いします。

ちなみにAPIリファレンスの「注文発注（現物・信用）」内に下記記載があったため、同時注文の話なのではないか、と思っています。
https://kabucom.github.io/kabusapi/reference/index.html#tag/order
＞同一の銘柄に対しての注文は同時に5件ほどを上限としてご利用ください。

**Comment by cyber-minion** [comment]
> 同程度の価格帯に多数同一方向の注文があれば、板の占有率等を高い状態で約定しないケースが多数あれば疑念（見せ玉形態）を見られる可能性もある

上記リスクを回避するという意図で、同時に5注文と制限させていただいております。

**Comment by hori-ryota** [comment]
こちら

> 同一銘柄注文を1日5件までという認識でお願いします。

ではなく、同時に5注文（板に5つ以上の注文を表示させる行為）を制限しているという認識で確定して大丈夫でしょうか

**Comment by cyber-minion** [comment]
はい、同時に5注文を制限しているということで大丈夫です。

**Comment by hieeeee** [comment]
> はい、同時に5注文を制限しているということで大丈夫です。

上記内容、承知しました。
疑問解消しましたので、当件クローズいたします。
