### ISSUE TITLE
【質問】デイトレ信用のプレミアム料について、更新はいつされる？

### ISSUE THREAD

**Issue by kitty2117** [kabucom/kabusapi#528]
お世話になります。
料金についての質問です。

デイトレ信用のプレミアム料というのが存在します。これは、つまり貸株料ってことですよね？
で、わからないのは、このプレミアム料がいつ決定されるかです。

具体的には、
A株をデイトレ信用で空売りする場合、プレミアム料は空売り前に確認したほうが良いのか？（毎回変わる？）
あるいは、場が開く前に一回確認しとけば、場中は変更されないのか？ということです。
プレミアム料の更新されるタイミングを教えてください

**Comment by kitty2117** [comment]
追加質問です
GET /margin/marginpremium/{symbol}のレスポンスですが
字面である程度内容の想像はできますが
TickMarginPremiumはさっぱりわかりません
それとUpperとLowerがあるということは、Premium料は取引毎に変わると考えたほうが良いということでしょうか？

{
  "Symbol": "9433",
  "GeneralMargin": {
    "MarginPremiumType": null,
    "MarginPremium": null,
    "UpperMarginPremium": null,
    "LowerMarginPremium": null,
    "TickMarginPremium": null
  },
  "DayTrade": {
    "MarginPremiumType": 2,
    "MarginPremium": 0.55,
    "UpperMarginPremium": 1,
    "LowerMarginPremium": 0.3,
    "TickMarginPremium": 0.01
  }
}

**Comment by cyber-minion** [comment]
プレミアム料については、こちらをご参照いただければと思います。
https://kabu.com/item/shinyo/premium.html

プレミアム料が決定されるのは、21時以降となります。また、プレミアム料が場中に更新されることはありません。
TickMarginPremiumについては、リファレンスに記載されているように「プレミアム料刻値」となります。下限から加算して、刻値から外れる場合は発注エラーになります。

**Comment by kitty2117** [comment]
> プレミアム料については、こちらをご参照いただければと思います。 
> プレミアム料が決定されるのは、21時以降となります

整理すると、
一般信用（デイトレ）は前日の21時に翌日に空売りできる株式のオークションが行われ、そこでプレミアム料を多く支払った人が空売りする権利を得られる

通常kabusapiの場合、一般信用（デイトレ）は前日の権利取りがないのでLongしかできない、Shortは制度信用で行う必要がある

こういう事ですね
ありがとうございました
