### ISSUE TITLE
【質問】PUSH配信のリファレンスにおける板情報の説明文について

### ISSUE THREAD

**Issue by sanrei** [kabucom/kabusapi#53]
Sell1とBuy1についてですが、SignとQtyの説明が逆になっている気がします。
RESTの方のリファレンスにある通り、Signは気配フラグ、Qtyは数量を意味する、ということでOKですか。

**Comment by yasuyuki-nakazawa** [comment]
ご指摘のとおりです。RESTの方のリファレンスと同意になります。
リファレンスは補正させて頂きます。

**Comment by sanrei** [comment]
ご回答ありがとうございます！

**Comment by yasuyuki-nakazawa** [comment]
リファレンスの記載補正ならびに、諸追記実施させて頂きました。
