### ISSUE TITLE
【不具合】ドキュメントの記載が変　POST: /sendorder

### ISSUE THREAD

**Issue by kitty2117** [kabucom/kabusapi#531]
POST: /sendorder のドキュメントの記載が少し変です

'ClosePositinOrder'はintになっていますが、ドキュメントの右のサンプルにはリスト指定で記載されており、
'ClosePosions'の記載がない、この’ClosePosions’がリスト指定ですよね？

```
{
  "Password": "xxxxxx",
  "Symbol": "9433",
  "Exchange": 1,
  "SecurityType": 1,
  "Side": "1",
  "CashMargin": 3,
  "MarginTradeType": 3,
  "MarginPremiumUnit": 12.34,
  "DelivType": 2,
  "AccountType": 4,
  "Qty": 500,
  "ClosePositionOrder": [
    {
      "HoldID": "20200702E01N04699739",
      "Qty": 500
    }
  ],
  "FrontOrderType": 30,
  "Price": 0,
  "ExpireDay": 20200903,
  "ReverseLimitOrder": {
    "TriggerSec": 1,
    "TriggerPrice": 40000,
    "UnderOver": 2,
    "AfterHitOrderType": 1,
    "AfterHitPrice": 0
  }
}
```

それと【質問】ですが
’ClosePositions’のパラメーター説明で
※建玉IDは「E」から始まる番号です
との注意書きがあります。
"HoldID": "20200702E01N04699739”
この真ん中あたりのEのことでしょうか？
20200702というのは日付？E01が売り建玉でN04699739がその日のシリアルナンバー？
このHoldIDはGET: /positionsで取得できる"ExecutionID"と考えていいでしょうか？

【要望】もひとつ
kabusapiで使うID関係の名前がよくわからなかったので、英語名を統一というか、同じIDなら英語名も統一するってのは無理でしょうか？既存スクリプトへの影響おおきそうだけど、次期のメジャーバージョンアップくらいでお願いします。
HoldIDとExecutionIDとか、orderIDとIDとか

**Comment by yasuyuki-nakazawa** [comment]
・ご指摘のClosePositinOrderの記載に関してはリストになっておりますね。確認いたします。
・建玉IDに関してはEで始まる照会IDがあるのですが、取得方法含めてご提示いたしますのでお待ちくださいませ

**Comment by kitty2117** [comment]
お世話になってます

ExecutionIDは取得できました、Eではじまってます
GET: /positionsのレスポンス
```
[{'AccountType': 4,
  'Commission': 90.0,
  'CommissionTax': 9.0,
  'CurrentPrice': 12565.0,
  'Exchange': 1,
  'ExchangeName': '東証ETF/ETN',
  'ExecutionDay': 20220512,
  'ExecutionID': 'E2022051200F6Q',
  'Expenses': 2.0,
  'ExpireDay': 20320511,
  'HoldQty': 0.0,
  'LeavesQty': 3.0,
  'MarginTradeType': 2,
  'Price': 12575.0,
  'ProfitLoss': -131.0,
  'ProfitLossRate': -0.3472498343273691,
  'Side': '2',
  'Symbol': '1570',
  'SymbolName': 'ＮＥＸＴ\u3000ＦＵＮＤＳ\u3000日経平均レバレッジ・インデックス連動型上場投信',
  'Valuation': 37695.0}]
```
このGET: /positionsのレスポンスのドキュメントの説明が "ExecutionID": "20220404E02N04738464"となっています。
```
[
  {
    "ExecutionID": "20220404E02N04738464",
    "AccountType": 4,
    "Symbol": "8306",
    "SymbolName": "三菱ＵＦＪフィナンシャル・グループ",
    "Exchange": 1,
    "ExchangeName": "東証プ",
    "ExecutionDay": 20220404,
    "Price": 704,
    "LeavesQty": 500,
    "HoldQty": 0,
    "Side": "1",
    "Expenses": 0,
    "Commission": 1620,
    "CommissionTax": 162,
    "ExpireDay": 20220404,
    "MarginTradeType": 1,
    "CurrentPrice": 414.5,
    "Valuation": 207250,
    "ProfitLoss": 144750,
    "ProfitLossRate": 41.12215909090909
  }
]
```

あと【質問】ですが
このExecutionIDは、例えば板が薄くて売り板がこんな時に
成行で２００株の買い注文を出すと
１０２０円　１００株
１０１０円　１００株
この場合
１０２０円１００株のポジション情報と1010円100株のポジション情報が作成されて、
ExecutionIDも二つ発行されると考えていいでしょうか？

**Comment by yasuyuki-nakazawa** [comment]
>このGET: /positionsのレスポンスのサンプル説明が "ExecutionID": "20220404E02N04738464"となっています。
こちらについては、リファレンス上も正しく表示するように修正いたします。

**Comment by yasuyuki-nakazawa** [comment]
また、質問に関してですが、
指定の例ですと、ポジションも割れますので、ExecutionIDも２つに割れた形で発行されることになります

**Comment by cyber-minion** [comment]
混乱させてしまい申し訳ございません。ご指摘いただいた箇所を修正いたしましたので、ご確認いただければと思います。
