### ISSUE TITLE
【要望】株式分割、合併について

### ISSUE THREAD

**Issue by genbu-jp** [kabucom/kabusapi#532]
株式分割、合併について。
実施前日以前に、その有無や掛率が分かるフィールドをAPIに含めて頂ければ有り難く思います。
可能か分かりませんが、取りあえずご要望させて頂きます。

**Comment by yasuyuki-nakazawa** [comment]
ご要望頂いている分割、併合に関してですが、結論的には、現状のAPIとしてご提供することができません。
ご承知のとおり、カブステーションAPIはカブステーションとのインターフェースとなっており、カブステに保有していない情報を連携することができません。
そのため、分割、併合に関しては事前に当該情報をシステム上保有しておらず、ご提供ができない状態となっておりますこと、ご理解いただければと思います。

**Comment by genbu-jp** [comment]
承知いたしました！
早速ご返事いただき、ありがとうございました！
