### ISSUE TITLE
【質問】AskPriceとBidPriceが逆転する現象について

### ISSUE THREAD

**Issue by ultragenma** [kabucom/kabusapi#534]
質問が遅くなり古いデータですが、2022-04-22の先物価格について気になるレスポンスがありました。
push配信で日経先物ミニの5月限、6月限、日経先物ラージ6月限のデータを取得していました。基本的に板はAskPrice<BidPriceで逆転することはありえないと考えていましたが、ミニ6月限(167060019)、ラージ6月限(167060018)でAskPrice>BidPriceとなる瞬間が数回出ていました。SystemTimeは自分で追加したものです。

・この原因は東証、カブコム証券、カブステーションのどの段階で起きていると考えられますでしょうか？
・先物のメジャー限月ではナノ秒オーダーでのデータ更新が予想されますが、更新時に東証またはカブコム証券のデータベースはロックされずデータ入力されているのでしょうか？
・株、先物、オプション全てで起きうる現象でしょうか？

push配信ごとにAskPrice<BidPriceであることを確認すれば良い現象ではありますが、何か知見がありましたら教えていただきたく思います。

```
{
	"data": [
		{
			"AskPrice": 27120.0,        # 正常
			"AskQty": 17.0,
			"BidPrice": 27125.0,
			"BidQty": 9.0,
			"CurrentPrice": 27100.0,
			"CurrentPriceChangeStatus": "0058",
			"CurrentPriceTime": "2022-04-22T14:53:00+09:00",
			"Symbol": "167050019",
			"SystemTime": "2022-04-22 14:53:00.186",
			"VWAP": 27279.7649
		},
		{
			"AskPrice": 27120.0,        # 異常
			"AskQty": 54.0,
			"BidPrice": 27110.0,
			"BidQty": 387.0,
			"CurrentPrice": 27105.0,
			"CurrentPriceChangeStatus": "0057",
			"CurrentPriceTime": "2022-04-22T14:53:00+09:00",
			"Symbol": "167060019",
			"SystemTime": "2022-04-22 14:53:00.112",
			"VWAP": 27256.202
		},
		{
			"AskPrice": 27120.0,        # 異常
			"AskQty": 7.0,
			"BidPrice": 27110.0,
			"BidQty": 52.0,
			"CurrentPrice": 27100.0,
			"CurrentPriceChangeStatus": "0057",
			"CurrentPriceTime": "2022-04-22T14:53:00+09:00",
			"Symbol": "167060018",
			"SystemTime": "2022-04-22 14:53:00.185",
			"VWAP": 27192.8293
		}
	]
},
```

**Comment by yasuyuki-nakazawa** [comment]
情報が古いため、どこまで調査可能か不明ですが、いったん確認してみます

**Comment by cyber-minion** [comment]
PUSH配信の仕様としましては、値が更新される際にデータが配信されることとなっておりますので、本事象は各値の更新タイミングによるものと考えられます。

以下は過去の類似の問い合わせで、ご参考いただければと思います。
https://github.com/kabucom/kabusapi/issues/218#issuecomment-761005325

**Comment by cyber-minion** [comment]
> ・株、先物、オプション全てで起きうる現象でしょうか？

すべてで起きうる現象です。

> ・この現象が起きてる際、カブステーションの板はどのように表示されますでしょうか？

この現象はkabuSAPIだけで発生しますので、当該事象発生時はkabuSの板は影響されず、正常に表示されます。
対応策があるかを含めて継続検討とさせていただきたく考えております。

**Comment by cyber-minion** [comment]
本件はクローズさせていただきます。
