### ISSUE TITLE
【質問】銘柄情報 GET /symbol/{symbol}のレスポンスについて

### ISSUE THREAD

**Issue by kitty2117** [kabucom/kabusapi#536]
お世話になります
銘柄情報のレスポンスについて教えてください

GET /symbol/{symbol}のレスポンスに
'KCMarginBuy'、'KCMarginSell、,'MarginBuy'、'MarginSell'という信用取引できるかどうか？のフラグがあるのですが、
このフラグは場中に変更されるでしょうか？

場中に変わる場合は、発注処理にフラグ確認が必要になり、流量の問題もありエラーの処理をどうするか考えるないといけなくなりそうです。
東証が制限する場合とau株コム証券で制限する場合と場の状況とか開示情報とかいろいろあるんだろうな。。。
そうすると毎回フラグ確認しないといけない気もしますが、、、

取引関連で、
その銘柄が取引されているか？の情報は
GET /board/{symbol}のレスポンスの'CurrentPriceStatus'で判断できると思ってよいでしょうか？

よろしくお願いします。

**Comment by yasuyuki-nakazawa** [comment]
こちら、場中には変更がなかったと思われますが、確認いたしますのでお待ちください

**Comment by yasuyuki-nakazawa** [comment]
確認いたしました。基本的に場中に変更されることはありません。
ただし、ごくまれに銘柄情報が差し変わることがあることがある点は補足させていただきます

**Comment by kitty2117** [comment]
> 確認いたしました。基本的に場中に変更されることはありません。 ただし、ごくまれに銘柄情報が差し変わることがあることがある点は補足させていただきます

お世話になってます
基本的に変わらないなら、場の開く前に確認して、場中に確認は不要と言う事ですね
ただ、希に変わることがあると
発注エラーが起きたら、取引できるか確認する実装しようと思います
