### ISSUE TITLE
【質問】信用取引返済の成行取引の決済価格の取得方法

### ISSUE THREAD

**Issue by kitty2117** [kabucom/kabusapi#539]
おせわになります。

いま、サガミホールディングスの株の信用買いのポジションを持っています。
GET: positionsで取得したデータ
’’’
  [{'AccountType': 4,
  'Commission': 135.0,
  'CommissionTax': 13.0,
  'CurrentPrice': 1172.0,
  'Exchange': 1,
  'ExchangeName': '東証プ',
  'ExecutionDay': 20220524,
  'ExecutionID': 'E202205240XXXX',
  'Expenses': 54.0,
  'ExpireDay': 20320521,
  'HoldQty': 0.0,
  'LeavesQty': 100.0,
  'MarginTradeType': 2,
  'Price': 1182.0,
  'ProfitLoss': -1202.0,
  'ProfitLossRate': -1.0169204737732656,
  'Side': '2',
  'Symbol': '9900',
  'SymbolName': 'サガミホールディングス',
  'Valuation': 117200.0}]
’’’

このポジションを成行で返済売りした場合、約定価格はどのＡＰＩをたたけばよいでしょうか？

GET: boardで取得したデータのAskPriceは成行の場合その価格になるかわからない

’’’
{'AskPrice': 1174.0,
 'AskQty': 200.0,
 'AskSign': '0101',
 'AskTime': '2022-05-27T12:47:27+09:00',
 'BidPrice': 1176.0,
 'BidQty': 400.0,
 'BidSign': '0101',
 'BidTime': '2022-05-27T12:47:27+09:00',
 'Buy1': {'Price': 1174.0,
          'Qty': 200.0,
          'Sign': '0101',
          'Time': '2022-05-27T12:47:27+09:00'},
 'Buy10': {'Price': 1165.0, 'Qty': 900.0},
 'Buy2': {'Price': 1173.0, 'Qty': 900.0},
 'Buy3': {'Price': 1172.0, 'Qty': 700.0},
 'Buy4': {'Price': 1171.0, 'Qty': 1900.0},
 'Buy5': {'Price': 1170.0, 'Qty': 3600.0},
 'Buy6': {'Price': 1169.0, 'Qty': 1500.0},
 'Buy7': {'Price': 1168.0, 'Qty': 3100.0},
 'Buy8': {'Price': 1167.0, 'Qty': 1300.0},
 'Buy9': {'Price': 1166.0, 'Qty': 1100.0},
 'CalcPrice': 1175.0,
 'ChangePreviousClose': 2.0,
 'ChangePreviousClosePer': 0.17,
 'CurrentPrice': 1175.0,
 'CurrentPriceChangeStatus': '0057',
 'CurrentPriceStatus': 1,
 'CurrentPriceTime': '2022-05-27T12:47:17+09:00',
 'Exchange': 1,
 'ExchangeName': '東証プ',
 'HighPrice': 1187.0,
 'HighPriceTime': '2022-05-27T09:00:00+09:00',
 'LowPrice': 1165.0,
 'LowPriceTime': '2022-05-27T09:10:47+09:00',
 'MarketOrderBuyQty': 0.0,
 'MarketOrderSellQty': 0.0,
 'OpeningPrice': 1187.0,
 'OpeningPriceTime': '2022-05-27T09:00:00+09:00',
 'OverSellQty': 74300.0,
 'PreviousClose': 1173.0,
 'PreviousCloseTime': '2022-05-26T00:00:00+09:00',
 'SecurityType': 1,
 'Sell1': {'Price': 1176.0,
           'Qty': 400.0,
           'Sign': '0101',
           'Time': '2022-05-27T12:47:27+09:00'},
 'Sell10': {'Price': 1185.0, 'Qty': 500.0},
 'Sell2': {'Price': 1177.0, 'Qty': 700.0},
 'Sell3': {'Price': 1178.0, 'Qty': 600.0},
 'Sell4': {'Price': 1179.0, 'Qty': 1700.0},
 'Sell5': {'Price': 1180.0, 'Qty': 1000.0},
 'Sell6': {'Price': 1181.0, 'Qty': 500.0},
 'Sell7': {'Price': 1182.0, 'Qty': 1300.0},
 'Sell8': {'Price': 1183.0, 'Qty': 2600.0},
 'Sell9': {'Price': 1184.0, 'Qty': 1600.0},
 'Symbol': '9900',
 'SymbolName': 'サガミホールディングス',
 'TotalMarketValue': 35604596200.0,
 'TradingValue': 32890700.0,
 'TradingVolume': 27900.0,
 'TradingVolumeTime': '2022-05-27T12:47:17+09:00',
 'UnderBuyQty': 76000.0,
 'VWAP': 1178.8781}
’’’

**Comment by yasuyuki-nakazawa** [comment]
注文約定照会の情報取得で可能です

**Comment by kitty2117** [comment]
> 注文約定照会の情報取得で可能です

信用返済の成行取引の約定価格を調べるときのGET: ordersのパラメータの設定は
’’’
params={
              'id' : 'xxxxxxxxxxxxxxxxxxxx',
              'Details' : 'True',
              'state' : 5,
              'cashmargin' : 3
}
    # 発注を検索する
    # paramsは設定しない項目があってもよい
    # params = { 'product': 0 }             # product - 0:すべて、1:現物、2:信用、3:先物、4:OP
    # params['id'] = '20201207A02N04830518' # id='xxxxxxxxxxxxxxxxxxxx'
    # params['updtime'] = 20201101123456    # updtime=yyyyMMddHHmmss
    # params['details'] =  'True'          # details='true'/'false'
    # params['symbol'] = '9433'             # symbol='xxxx'
    # params['state'] = 5                   # state - 1:待機（発注待機）、2:処理中（発注送信中）、3:処理済（発注済・訂正済）、4:訂正取消送信中、5:終了（発注エラー・取消済・全約定・失効・期限切れ）
    # params['side'] = '2'                  # side - '1':売、'2':買
    # params['cashmargin'] = 3              # cashmargin - 2:新規、3:返済
’’’
にすると
GET: ordersのレスポンスの['Price']、これが指値の価格になる？（成行の場合は０）
['Details']の中の['Price']が約定価格でしょうか？
['Details']がリスト形式なのは、成行の場合、複数のポジションになることもあるので、リスト形式になっている
['Details']が取得できるのは、params={’state’ : 5}の時だけになる
['Details']の['ExecutionID']は信用新規の時だけに設定されて、信用返済の場合は空白になる？

この理解であっていますか？

’’’
ordersのレスポンス
[
  {
    "ID": "20220404A02N04738436",
    "State": 5,
    "OrderState": 5,
    "OrdType": 1,
    "RecvTime": "2022-04-04T18:00:51.763683+09:00",
    "Symbol": "8306",
    "SymbolName": "三菱ＵＦＪフィナンシャル・グループ",
    "Exchange": 1,
    "ExchangeName": "東証プ",
    "TimeInForce": 1,
    "Price": 704.5,
    "OrderQty": 1500,
    "CumQty": 1500,
    "Side": "1",
    "CashMargin": 2,
    "AccountType": 4,
    "DelivType": 2,
    "ExpireDay": 20220404,
    "MarginTradeType": 1,
    "MarginPremium": null,
    "Details": [
      {
        "SeqNum": 1,
        "ID": "20220404A02N04738436",
        "RecType": 1,
        "ExchangeID": "00000000-0000-0000-0000-00000000",
        "State": 5,
        "TransactTime": "2022-04-04T18:00:51.763683+09:00",
        "OrdType": 1,
        "Price": 704.5,
        "Qty": 1500,
        "ExecutionID": "",
        "ExecutionDay": "2022-04-04T18:02:00+09:00",
        "DelivDay": 20220406,
        "Commission": 0,
        "CommissionTax": 0
      }
    ]
  }
]
’’’

ドキュメントの書き方が、証券会社のシステム部員の暗黙知が前提になってるところあるような気がします。
大体わかるけど、細かいところでよくわからないところもあります。。。

よろしくお願いします

**Comment by cyber-minion** [comment]
Details内にあるRecType=8のレコードでPriceをご確認ください。

**Comment by kitty2117** [comment]
> Details内にあるRecType=8のレコードでPriceをご確認ください。

もうひとつ教えてください

成行の信用買いで5００株の注文をしたときに
449円で200株
450円で100株
451円で200株
の約定になった場合にはDetailsの詳細情報も３つ作成されるのでしょうか？
それとも一つの詳細情報でPriceの中に平均約定価格がはいっている？
平均約定価格を自分で計算する必要があるでしょうか？

よろしくお願いします

**Comment by kitty2117** [comment]
> Details内にあるRecType=8のレコードでPriceをご確認ください。

もうひとつ教えてください

成行の信用買いで5００株の注文をしたときに
449円で200株
450円で100株
451円で200株
の約定になった場合にはDetailsの詳細情報も３つ作成されるのでしょうか？
それとも一つの詳細情報でPriceの中に平均約定価格がはいっている？
平均約定価格を自分で計算する必要があるでしょうか？
Details内にExcutionIDがあるので三つできるのかな

よろしくお願いします

**Comment by cyber-minion** [comment]
Details（注文詳細）は１つで、その中でそれぞれ約定した分の約定価格や約定番号などの情報が作成されます。

**Comment by kitty2117** [comment]
>Details（注文詳細）は１つで、その中でそれぞれ約定した分の約定価格や約定番号などの情報が作成されます。

おせわになっています

Detailsの中にリスト形式で三つの詳細情報がある形式ですよね？
449円で200株
450円で100株
451円で200株なら
こんな感じになる？

’’’
    "Details": [
      {
        "SeqNum": 1,
        "ID": "20220404A02N04738436",
        "RecType": 8,
        "ExchangeID": "00000000-0000-0000-0000-00000000",
        "State": 5,
        "TransactTime": "2022-04-04T18:00:51.763683+09:00",
        "OrdType": 1,
        "Price": 449,
        "Qty": 200,
        "ExchangeID": "E0000000-0000-0000-0000-00000000",
        "ExecutionDay": "2022-04-04T18:02:00+09:00",
        "DelivDay": 20220406,
        "Commission": 0,
        "CommissionTax": 0
      },
     {
        "SeqNum": 1,
        "ID": "20220404A02N04738436",
        "RecType": 8,
        "ExchangeID": "E0000000-0000-0000-0000-00000000",
        "State": 5,
        "TransactTime": "2022-04-04T18:00:51.763683+09:00",
        "OrdType": 1,
        "Price": 450,
        "Qty": 100,
        "ExecutionID": "",
        "ExecutionDay": "2022-04-04T18:02:00+09:00",
        "DelivDay": 20220406,
        "Commission": 0,
        "CommissionTax": 0
      },
     {
        "SeqNum": 1,
        "ID": "20220404A02N04738436",
        "RecType": 8,
        "ExchangeID": "E0000000-0000-0000-0000-00000000",
        "State": 5,
        "TransactTime": "2022-04-04T18:00:51.763683+09:00",
        "OrdType": 1,
        "Price": 451,
        "Qty": 200,
        "ExecutionID": "",
        "ExecutionDay": "2022-04-04T18:02:00+09:00",
        "DelivDay": 20220406,
        "Commission": 0,
        "CommissionTax": 0
      }
    ]
’’’

この三つのデータから、平均約定価格、約定数量、手数料、消費税を計算できる。
