### ISSUE TITLE
【お知らせ】kabuステーションAPIの仕様変更に関して(時刻のタイムゾーン付きフォーマットの統一）

### ISSUE THREAD

**Issue by yasuyuki-nakazawa** [kabucom/kabusapi#54]
2020年9月3日(木）【予定】のkabuステーションバージョンアップ後より、以下の変更を実施させて頂きます。

【修正内容】
API経由で返される時刻項目に関して、タイムゾーンが入っているもの、入っていないものが混在する
下記項目の時刻に統一でタイムゾーン付で定義させて頂きます

orderメソッドのレスポンス
・	RecvTime
・	TransactTime
・	ExecutionDay
Boardメソッドのレスポンス
・	CurrentPriceTime
・	PreviousCloseTime
・	OpeningPriceTime
・	HighPriceTime
・	LowPriceTime
・	TradingVolumeTime
・	BidTime
・	Sell1.Time
・	AskTime
・	Buy1.Time
PUSH配信の配信内容
・	CurrentPriceTime
・	PreviousCloseTime
・	OpeningPriceTime
・	HighPriceTime
・	LowPriceTime
・	TradingVolumeTime
・	BidTime
・	Sell1.Time
・	AskTime
・	Buy1.Time

**Comment by tsuchinaga** [comment]
orderメソッド は 情報/注文約定照会のことで、  
Boardメソッド は 情報/時価情報・板情報のことという認識であっていますか？

**Comment by yasuyuki-nakazawa** [comment]
はい。記載のとおりです
