### ISSUE TITLE
【質問】APIログファイルの非同期アップロードに失敗しました。に対する対処について

### ISSUE THREAD

**Issue by hiuchida** [kabucom/kabusapi#540]
C:\Users\ACCOUNT\AppData\Roaming\KabuS\LogにあるログファイルKabuS_yyyymmdd.logにほぼ毎日
＞07:03:08.4666,W,14312,0042 APIログファイルの非同期アップロードに失敗しました。
＞System.IO.IOException: ストリームが長すぎます。
のエラーが出ていますが、何か対処が必要でしょうか？

また、kabuステーションアプリのメニューに「OPEログアップロード」とありますが、これを手で実行する目的はなんでしょうか？

**Comment by yasuyuki-nakazawa** [comment]
解決法の一つとして、API設定から、暗号化ログに関するチェックボックスをオフに変更してください
原因としては、アップロード時のメモリ不足が考えられますが、上記対応を行うことで、一部ログの保存が回避されるため、改善が見込まれます

**Comment by yasuyuki-nakazawa** [comment]
また、オペログの件ですが、なんらかの不調や問い合わせがあった際に、カブステのログを調査のため、送信していただく必要があり、それを簡素化する意味でアップロード機能を設けております
当該ログの自動取得は実施していないためです

**Comment by hiuchida** [comment]
暗号化ログのチェックをオフにして、しばらく様子をみてみます。
メモリに関しては、64GB積んでいて、利用可能が48GBくらいあるので、KabuS.exeが使っていないだけのような気がします。

**Comment by yasuyuki-nakazawa** [comment]
情報ありがとうございます（メモリ）
次回、CPUの利用状況も見ていただけると幸甚です。

**Comment by yasuyuki-nakazawa** [comment]
暗号化オフで問題が発生しなくなったということからの想定ですが、
ログのアップロードの際にログを圧縮して送信しています。その際にCPUリソースを使用してしまうことにより影響受けしているケースがありました。
そのため、今回の回避策をご提案させていただきました。
CPU使用率が影響している可能性が高いため、改善に関しては引き続き検討させていただきます

**Comment by cyber-minion** [comment]
解決済みのようですので、いったんクローズさせていただきます。
