### ISSUE TITLE
【質問】kabu stationの早朝ログアウトについて

### ISSUE THREAD

**Issue by officetomo1121** [kabucom/kabusapi#544]
昨日より作成したスクリプトを走らせておりましたが、早朝時間帯に、kabu stationから強制ログアウトされる事に気づいてしまいました。

これは毎朝、kabu stationを手動起動し直すしか方法はないのでしょうか？

皆さんはどうしておられますか？

**Comment by yasuyuki-nakazawa** [comment]
早朝にセッションは強制的にログアウトさせていただいております。
こちらはお手数ですが、ログインをしていただけますよう、よろしくお願いいたします
（オープンAPIではないため、一定の制約がある点はご了承いただければと存じます）

**Comment by officetomo1121** [comment]
ご回答ありがとうございます
毎日ログインし直すしかないのですね
承知致しました。ありがとうございます

**Comment by yasuyuki-nakazawa** [comment]
こちらはクローズさせていただきます
