### ISSUE TITLE
【質問】kabuステーションを起動できません

### ISSUE THREAD

**Issue by Raliru** [kabucom/kabusapi#545]
昨日、初めてkabuステーションをインストールしましたが起動しません。
「銘柄情報の取得に失敗しました。」のエラーメッセージが出たので「SymbolCache.bin」を削除しましたが、改善されませんでした。
また、再インストールも試しましたが、こちらも改善されませんでした。

やはりインターネット環境が整ってないからでしょうか。
自宅に光回線を引かないと使用できないのでしょうか。

**Comment by yasuyuki-nakazawa** [comment]
カブステーションのログファイルの内容を連携いただけるともう少し適切な対処を支援できるかと思います
ログの内容をご連携いただけますでしょうか。
銘柄情報の削除に失敗するケースは通信が原因であることが多かったですが、現在のお使いのインターネット環境はどれくらいのスループットが出ているか等の情報も頂けると幸甚です

**Comment by Raliru** [comment]
> ログの内容をご連携いただけますでしょうか。

添付させて頂きます。

[KabuS_20220603.log](https://github.com/kabucom/kabusapi/files/8832417/KabuS_20220603.log)



> 銘柄情報の削除に失敗するケースは通信が原因であることが多かったですが、現在のお使いのインターネット環境はどれくらいのスループットが出ているか等の情報も頂けると幸甚です

現在６.５Mbpsくらいの速度で通信しております。

大変お手数おかけします。

**Comment by Raliru** [comment]
追加で質問なのですが、上記で添付したログの中に口座番号がそのまま載っていました（今はマスク済みです）。
この場合、パスワードを変更するなどの対策で大丈夫でしょうか。

**Comment by yasuyuki-nakazawa** [comment]
過去の事例も見ておりますが、回線帯域に加えて、セキュリティソフトによる通信遮断も当該エラーが出る原因として多くあげられていました。
現在、6.5Mの速度で通信していることから、帯域に関して問題ないと思われます。
セキュリティソフトをお使いの場合は切り分けのため、一旦オフにした状態でカブステの起動をお試しいただけますでしょうか。
その場合、カブステをセキュリティソフトのホワイトリストに登録等で改善されるケースがございます。

**Comment by yasuyuki-nakazawa** [comment]
>パスワードを変更するなどの対策で大丈夫でしょうか。
パスワードの変更はお勧めいたします。併せてカブステAPIのパスワードの変更も検討ください

**Comment by Raliru** [comment]
返信遅くなり大変申し訳ございません。

「セキュリティソフトをお使いの場合は切り分けのため、一旦オフにした状態でカブステの起動をお試しいただけますでしょうか。」

とのことですが、当方Windows標準搭載のセキュリティソフトしか使っていないため、やはりネットワーク関係のトラブルなのだと思います。
有線の環境を整えるなどしてから再チャレンジしてみようと思います。

「パスワードの変更はお勧めいたします。併せてカブステAPIのパスワードの変更も検討ください」

カブステAPIのパスワードの変更もしたいと思います。

**Comment by Raliru** [comment]
ご多忙の中、対応してくださりありがとうございました。

クローズさせていただきます。
