### ISSUE TITLE
【不具合】（先物）時価情報・板情報の時間ずれについて

### ISSUE THREAD

**Issue by hmhjapan** [kabucom/kabusapi#546]
■[必須] 不具合事象(概要)
　url = 'http://localhost:18080/kabusapi/board/167090019@24'　で2022-06-03 18:28:27にテストし、
   kabusapi_board.pyのCurrentPriceTime、PreviousClose、TradingVolumeTimeはずれている。
■[必須] 本来想定されるアクションと事象
　2022-06-03 18:28:27でテストし、CurrentPriceTimeは2022-06-03T18:28:01+08:00で、PreviousCloseは2022-06-03T15:15:59+08:00、TradingVolumeTimeは2022-06-03T18:28:01+08:00で想定されている。
■[必須] 不備発生時刻（常時の場合は、常時で記載ください)
　16:30:01以降に発生します(ほかの時間帯でまだテストしませんでした)
■[任意] お使いの環境(OS、Excelのバージョン等)、サンプル(Macro、アドインのバージョン）
 環境：windows10 profession、pycharm 2022.1(Profession Edition) 、python3.8
  サンプル：https://github.com/kabucom/kabusapi/blob/master/sample/Python/kabusapi_board.py
■[任意] 不備部分のログ
system time: 2022-06-03 18:28:27.414864
200 OK
('Content-Length', '1623')
('Content-Type', 'application/json; charset=utf-8')
('Server', 'Microsoft-HTTPAPI/2.0')
('X-Content-Type-Options', 'nosniff')
('X-XSS-Protection', '1; mode=block')
('X-Frame-Options', 'DENY')
('Content-Security-Policy', "default-src 'none'")
('Access-Control-Allow-Origin', '*')
('Date', 'Fri, 03 Jun 2022 09:28:27 GMT')
('Connection', 'close')

{'AskPrice': 27630.0,
 'AskQty': 3.0,
 'AskSign': '0101',
 'BidPrice': 27635.0,
 'BidQty': 77.0,
 'BidSign': '0101',
 'Buy1': {'Price': 27630.0, 'Qty': 3.0, 'Sign': '0101'},
 'Buy10': {'Price': 27585.0, 'Qty': 168.0},
 'Buy2': {'Price': 27625.0, 'Qty': 112.0},
 'Buy3': {'Price': 27620.0, 'Qty': 132.0},
 'Buy4': {'Price': 27615.0, 'Qty': 141.0},
 'Buy5': {'Price': 27610.0, 'Qty': 176.0},
 'Buy6': {'Price': 27605.0, 'Qty': 172.0},
 'Buy7': {'Price': 27600.0, 'Qty': 282.0},
 'Buy8': {'Price': 27595.0, 'Qty': 193.0},
 'Buy9': {'Price': 27590.0, 'Qty': 172.0},
 'CalcPrice': 27630.0,
 'ChangePreviousClose': -90.0,
 'ChangePreviousClosePer': -0.32,
 'ClearingPrice': 27400.0,
 'CurrentPrice': 27630.0,
 'CurrentPriceChangeStatus': '0058',
 'CurrentPriceStatus': 1,
 'CurrentPriceTime': '2022-06-02T18:28:01+08:00',
 'Exchange': 24,
 'ExchangeName': '大阪夜間',
 'HighPrice': 27700.0,
 'HighPriceTime': '2022-06-03T17:16:13+08:00',
 'LowPrice': 27630.0,
 'LowPriceTime': '2022-06-03T16:30:06+08:00',
 'OpeningPrice': 27675.0,
 'OpeningPriceTime': '2022-06-03T16:30:01+08:00',
 'PreviousClose': 27720.0,
 'PreviousCloseTime': '2022-06-03T00:00:00+08:00',
 'SecurityType': 901,
 'Sell1': {'Price': 27635.0, 'Qty': 87.0, 'Sign': '0101'},
 'Sell10': {'Price': 27680.0, 'Qty': 185.0},
 'Sell2': {'Price': 27640.0, 'Qty': 155.0},
 'Sell3': {'Price': 27645.0, 'Qty': 125.0},
 'Sell4': {'Price': 27650.0, 'Qty': 191.0},
 'Sell5': {'Price': 27655.0, 'Qty': 165.0},
 'Sell6': {'Price': 27660.0, 'Qty': 185.0},
 'Sell7': {'Price': 27665.0, 'Qty': 203.0},
 'Sell8': {'Price': 27670.0, 'Qty': 154.0},
 'Sell9': {'Price': 27675.0, 'Qty': 158.0},
 'Symbol': '167090019',
 'SymbolName': '日経225mini 22/09',
 'TradingValue': 17290807500.0,
 'TradingVolume': 6251.0,
 'TradingVolumeTime': '2022-06-02T18:28:01+08:00',
 'VWAP': 27660.8663}
上記のことをご確認の上に、ご解答をよろしくお願いいたします。

**Comment by cyber-minion** [comment]
確認いたします。

**Comment by cyber-minion** [comment]
ご利用のPCの日付は日本時間（タイムゾーン）になっていますでしょうか。タイムゾーンは＋8:00でなっておりませんでしょうか。

**Comment by cyber-minion** [comment]
お手数ですが、タイムゾーンを「+9:00」にして頂き、事象が解消するかご確認いただけますでしょうか。

**Comment by hmhjapan** [comment]
タイムゾーンを「+9:00」にして、テストの結果は下記の通りです。

system time: 2022-06-09 18:50:12.342787
200 OK
('Content-Length', '1627')
('Content-Type', 'application/json; charset=utf-8')
('Server', 'Microsoft-HTTPAPI/2.0')
('X-Content-Type-Options', 'nosniff')
('X-XSS-Protection', '1; mode=block')
('X-Frame-Options', 'DENY')
('Content-Security-Policy', "default-src 'none'")
('Access-Control-Allow-Origin', '*')
('Date', 'Thu, 09 Jun 2022 09:50:12 GMT')
('Connection', 'close')

{'AskPrice': 28315.0,
 'AskQty': 256.0,
 'AskSign': '0101',
 'BidPrice': 28320.0,
 'BidQty': 87.0,
 'BidSign': '0101',
 'Buy1': {'Price': 28315.0, 'Qty': 256.0, 'Sign': '0101'},
 'Buy10': {'Price': 28270.0, 'Qty': 368.0},
 'Buy2': {'Price': 28310.0, 'Qty': 281.0},
 'Buy3': {'Price': 28305.0, 'Qty': 348.0},
 'Buy4': {'Price': 28300.0, 'Qty': 454.0},
 'Buy5': {'Price': 28295.0, 'Qty': 234.0},
 'Buy6': {'Price': 28290.0, 'Qty': 303.0},
 'Buy7': {'Price': 28285.0, 'Qty': 747.0},
 'Buy8': {'Price': 28280.0, 'Qty': 306.0},
 'Buy9': {'Price': 28275.0, 'Qty': 234.0},
 'CalcPrice': 28320.0,
 'ChangePreviousClose': 90.0,
 'ChangePreviousClosePer': 0.32,
 'ClearingPrice': 28140.0,
 'CurrentPrice': 28320.0,
 'CurrentPriceChangeStatus': '0058',
 'CurrentPriceStatus': 1,
 'CurrentPriceTime': '2022-06-09T18:50:07+09:00',
 'Exchange': 24,
 'ExchangeName': '大阪夜間',
 'HighPrice': 28345.0,
 'HighPriceTime': '2022-06-09T17:59:39+09:00',
 'LowPrice': 28165.0,
 'LowPriceTime': '2022-06-09T16:37:25+09:00',
 'OpeningPrice': 28230.0,
 'OpeningPriceTime': '2022-06-09T16:30:01+09:00',
 'PreviousClose': 28230.0,
 'PreviousCloseTime': '2022-06-09T00:00:00+09:00',
 'SecurityType': 901,
 'Sell1': {'Price': 28320.0, 'Qty': 87.0, 'Sign': '0101'},
 'Sell10': {'Price': 28365.0, 'Qty': 178.0},
 'Sell2': {'Price': 28325.0, 'Qty': 256.0},
 'Sell3': {'Price': 28330.0, 'Qty': 297.0},
 'Sell4': {'Price': 28335.0, 'Qty': 313.0},
 'Sell5': {'Price': 28340.0, 'Qty': 686.0},
 'Sell6': {'Price': 28345.0, 'Qty': 317.0},
 'Sell7': {'Price': 28350.0, 'Qty': 542.0},
 'Sell8': {'Price': 28355.0, 'Qty': 294.0},
 'Sell9': {'Price': 28360.0, 'Qty': 762.0},
 'Symbol': '167090019',
 'SymbolName': '日経225mini 22/09',
 'TradingValue': 242236670500.0,
 'TradingVolume': 85698.0,
 'TradingVolumeTime': '2022-06-09T18:50:07+09:00',
 'VWAP': 28266.3155}

**Comment by hmhjapan** [comment]
CurrentPriceTime、TradingVolumeTimeのずれ事象は解消されました。
PreviousCloseTimeを確認したいです、テスト結果は「'PreviousCloseTime': '2022-06-09T00:00:00+09:00',」です。
PreviousCloseTimeの正しい値は[「2022-06-09T15:16:00+09:00 」ですか。

また、kabu ステーションAPIは日本時間（タイムゾーン）に限定されましたか、ほかの国のタイムゾーンで正しい日付を取得できないですか。

**Comment by yasuyuki-nakazawa** [comment]
>kabu ステーションAPIは日本時間（タイムゾーン）に限定されましたか、ほかの国のタイムゾーンで正しい日付を取得できないですか。
システム的な観点で調査・確認しております。
今しばらくお待ちください

**Comment by hmhjapan** [comment]
調査・確認の結果が出たら、ご連絡をよろしくお願いいたします。

**Comment by yasuyuki-nakazawa** [comment]
回答遅くなりすみません
kabuステは日本時間+西暦でないと正しく動作いたしません。
それに伴いまして、APIとしても当該仕様を引きずってしまう関係上、この仕様に制約されてしまいます。

**Comment by hmhjapan** [comment]
kabu ステーションAPIは日本時間（タイムゾーン）に限定されと認識しました。
ご回答ありがとうございました。
この件をクローズします。
