### ISSUE TITLE
【質問】検証用環境はどのように使うべきか

### ISSUE THREAD

**Issue by rippusu** [kabucom/kabusapi#547]
昨日からサンプルコードでAPIの使い方を勉強している者です。
使用環境は本番用と検証用とありますが、検証用の存在意義がよくわかりません。
たとえば検証用でboard関数を使っても0しか返ってきません。
検証用はどのような使い方を想定しているのでしょうか？

**Comment by cyber-minion** [comment]
作成したスクリプトは正常に実行できるか（文法的に問題ないか）をテストする際にご利用いただけます。
0と返却されれば、本番環境での実行はエラーとならないということになります。

**Comment by rippusu** [comment]
> 作成したスクリプトは正常に実行できるか（文法的に問題ないか）をテストする際にご利用いただけます。 0と返却されれば、本番環境での実行はエラーとならないということになります。

**Comment by rippusu** [comment]
ご回答ありがとうございます。理解いたしました。
