### ISSUE TITLE
【お知らせ】kabuステーションAPIの仕様変更に関して（注文期日の設定改善）

### ISSUE THREAD

**Issue by yasuyuki-nakazawa** [kabucom/kabusapi#55]
2020年9月3日(木）【予定】のkabuステーションバージョンアップ後より、以下の変更を実施させて頂きます。

■注文有効期限(ExpireDay)の設定に「0：当日」の追加

発注API(sendorder)の注文有効期限(ExpireDay)の設定値として、「0」当日を追加いたします。
現状は8桁の数値(yyyymmdd)の形式にて注文期限を設定しているが、「0」を指定していることで、kabuステーション上の発注画面の「本日」に対応する日付を自動設定するように改善します。

「本日」は直近の注文可能日となり、引けまでの間は、当日が、引け後については翌取引所営業日が設定されます。
休前日の場合は、休日明けの取引所営業日が設定されます。

※日替わりに関しては、kabuステーションが日付変更通知を受信したタイミングとなります。
　未受信の場合は日替わりされていないため、当日(ExpreDay=0)を指定しても、翌営業日が設定されないため発注エラーとなります。

**Comment by kabucomapi** [comment]
お世話になります。
要望への対応ありがとうございます。
これで非常に使い勝手が向上します。
ありがとうございました。
