### ISSUE TITLE
【要望】情報系の流量制限の解放、四本値ダウンロード

### ISSUE THREAD

**Issue by kitty2117** [kabucom/kabusapi#550]
お世話になります

情報系の流量制限が１０回/secはすこし少ないです。

ドテン買いやドテン売りが二つくらい重なると流量制限オーバーです。
まぁ、発注関係はQueueにいれてるのでいいのですが、今後は、リアルタイム株価予想、四本値ダウンロードなどを実装予定と聞きます。
リアルタイム株価や詳細ランキングを１５分くらいでポーリングして、監視銘柄入れ替え（四本値のダウンロードはshort trem と long termで二回）を行うことを考えると１０回は少ないと思う。
流量のコントロールができなくなりそうです。
リアルタイム株価や四本値ダウンロードがどうなるかわからないので、具体的に流量どれだけ増やせとか言えないですが、
１０回じゃ足りないのはなんとなく思う。

それともう一つ
四本値に関してですが、EVER-Chartと同じで、1,5,10,15,30分足と１日足くらいになるとありがたいです。
いっその事、４本値ダウンロードはEVER-Chartをプロキシーにしてもいいです。

よろしくお願いします

**Comment by cyber-minion** [comment]
ご要望ありがとうございます。上記は検討させていただきます。

**Comment by kitty2117** [comment]
よろしくお願いします
