### ISSUE TITLE
【質問】最新の資産状況について（前日との変動額）

### ISSUE THREAD

**Issue by YOHSIKI** [kabucom/kabusapi#552]
お世話になっております。
当日の相場が終了した時点(15:01)で最新の資産状況を取得したいです。（当日の利益を含む）

以下のAPIで取得できる現物の取引余力から資産を逆算することは可能でしょうか。

******************************************************************************
取引余力（現物）
http://localhost:18080/kabusapi/wallet/cash
StockAccountWallet | number <double>現物買付可能額
******************************************************************************

信用取引で銘柄を買付している場合、取引余力には信用建玉代金に対する拘束金なども含まれると思いますが、
どのような計算をすればよいか知りたいです。
以下の例で、総資産Xを算出するための計算式をご教示お願いいたします。

例）
総資産　　　：X万円
信用建玉代金：500万円（経費含む）
買付可能額　：1000万円(15:01に上記APIで取得したStockAccountWalletの値とします）
※損失が発生した場合、特定口座なので徴収済み納税金額から損失の20%が返却されますが、
　買付可能額に反映されるのは翌日になるのでこれは考慮しなくてよいです。（差が生じても良いです。）
　単純に当日09:00～15:00の間に増減した金額を15:01に計算したいです。

以上お手数かけしますが、ご教示のほどよろしくお願いいたします。

**Comment by yasuyuki-nakazawa** [comment]
イメージはリアルタイム資産評価のサマリーがわかれば良い感じでしょうか

**Comment by YOHSIKI** [comment]
ご確認ありがとうございます。
当日の損益が含まれるのであれば、それでも良いと思います。

あるいは、マイページ上で確認できる値で具体例を挙げるなら、「資産管理」→「買付出金可能額」→「建玉可能額・買付可能額」画面の「余力推移」に表示される信用建玉に対する「必要保証金うち現金」の値を、APIで取得できる「現物買付可能額」に合算したものが所望の値と理解しております。

逆に言えば、この「必要保証金うち現金」の算出式を知ることができれば、総資産を計算できるのではないかと考えております。マイページで確認したところ、信用の建玉金額をYとすると「必要保証金」、「必要保証金うち現金」は以下の通りでした。

建玉金額　　　　　：Y
必要保証金　　　　：Y*0.31
必要保証金うち現金：Y*0.01

「必要保証金うち現金」は建玉金額の1%という認識でよろしいでしょうか。

**Comment by yasuyuki-nakazawa** [comment]
>必要保証金うち現金」は建玉金額の1%という認識でよろしいでしょうか。
「必要保証金うち現金」は、「増担保規制」が適用される場合に発生する金額となります。

**Comment by yasuyuki-nakazawa** [comment]
資産総額は以下が原因のため、算出はできないと考えます。
1、APIは外国株式に対応していないため、評価額が取得が不可
2、APIで現金合計(受渡後)は取得不可

**Comment by cyber-minion** [comment]
解決済みのようで、いったんクローズさせていただきます。
