### ISSUE TITLE
【要望】kabuステーションへの複数セッション

### ISSUE THREAD

**Issue by kitty2117** [kabucom/kabusapi#553]
おせわになります

今、システム構成考えていたのですが、メモ兼ねての要望投稿です
こんな感じ↓
’’’
　　　　　　　　　　push tick , rest order ,rest query orders, rest query positions, rest board, etc
kabuステーション <----------> script1 - tickからhistorical data作成、テクニカル分析、トレード
　　|　　　|　　　　　　　　　　　　　テクニカル分析とトレードチェックは5秒に一度くらい？
　　|　　　|　　　　　　　　　　　　　　　　　　　　　　　　　|
　　|　　　|　　　　　　　　　　　　　　　　　　　　　　　　　|  script1がscript2を子プロセスで起動
　　|　　　|　　rest new function, rest symbol, etc　　　　　　　　|
　　|　　　+-------------------> script2 - リアルタイム株価、詳細ラんキング
　　|　　　　　　　　　　　　　　　　　動意づいた株の検索して、
　　|　　　　　　　　　　　　　　　　　historical dataのダウンロードしてscript1へ引き渡し、DBに格納
　　|　　　　　　　　　　　　　　　　　１０分に一度程度？
　　|　　　push tick
　　+---------------------------> script3 - tickデータからhistorical data作成してDBに格納
　　　　　　　　　　　　　　　　　　　翌日以降に使用
'''
問題点として
負荷的にscript1でhistoricaslデータつくるだけで、パンクする？　-->c#とか、golangでリライト
script1とscript2の処理が被ると流用制限に引っかかる？　　　　-->流量制限上げてください
そもそも、kabuステーションと複数セッションができない　　　-->複数セッションお願いします

スクリプト複数やめろよって話もあるでしょうが、
負荷や流量が難しくなりすぎて、ちょっと無理かも

あと、REST APIの銘柄登録の機能にkabuステーションに登録されている銘柄を取得するAPIがないです
複数scriptを動かすと、それもあると便利に使えそうです。

よろしくお願いします

**Comment by kitty2117** [comment]
そうか、script1とscript2をいれかえればいいのか

’’’
　　　　　　　　　　rest new function, rest symbol, etc
kabuステーション ---------------> main script - リアルタイム株価、詳細ラんキング
　　|　　　　　　　　　　　　　　　　　　　動意づいた株の検索して、
　　|　　　　　　　　　　　　　　　　　　　historical dataのダウンロードしてscript1へ引き渡し、DBに格納
　　|　　　　　　　　　　　　　　　　　　　１０分に一度程度？
　　|　　　　　　　　　　　　　　　　　　　　｜
　　|　　　　　　　　　　　　　　　　　　　　｜mainの子プロセスでn個のtrade script起動
　　|　　　　　　　　　　　　　　　　　　　　｜
　　|　　　　　　　　push tick , rest order ,rest query orders, rest query positions, rest board, etc
　　+----------------------------> trade script- tickからhistorical data作成、historical DB作成、テクニカル分析、トレード
　　　　　　　　　　　　　　　　　　　　　　テクニカル分析とトレードチェックは5秒に一度くらい？
'''
これができれば、(main scriptなしでもいいかも)１００銘柄でも監視できる

kabuステーションに１０セッションつなげるようにして、各々にtickデータのpushできればいい
あとは流量を毎秒100くらいにしたらうまくいくのかな

今は、低価格帯のＣＰＵでも4core8threadとかなので、時代の流れということで是非お願いします

**Comment by yasuyuki-nakazawa** [comment]
株価の取得に関しては、REST方式よりもPush方式による時価情報取得をお勧めします。
これであれば、流量制限を意識する必要はありませんので。

気になる点としては、historiacl dataのダウンロード部分ですが、カブステAPIではHistorical情報の取得はできませんが、
これは別手段で取得ということでしょうか

**Comment by kitty2117** [comment]
回答ありがとうございます

kabuステAPI拡張で、今後tickのPUSH配信、４本値ダウンロード、リアルタイム株価が予定になっていると認識しています
過去の要望でも「historical dataは権利関係が折り合えば」という話が何度も書き込まれてます。
それから、historical dataは現状ではDLできないので、pushされた板情報から４本値つくっています。
スクリプトの起動時に過去に蓄積したhistorical dataを読み込んで、pushされる板情報からアップデートしています
kabuステAPIが拡張されたら、
リアルタイム株価で銘柄をスクリーニングして、GET Symbolして、その銘柄の4本値をダウンロードして、tickのpush配信でアップデートしていくのかな？そのサイクルを場中に繰り返します。
流量については、発注をキューにいれて処理しているのですが、３銘柄監視してるだけで、キューに未処理が２件になることがあります。１０倍なら未処理２０件？スクリーニングと４本値DLが被ると、流量たりなくなる？

kabuステ（情報ウインドウを表示しない）のCPU負荷を見ていると、常に１％以下になっているので、
おそらく２０倍くらいの情報配信の余力があるのかなと思います。
比べてユーザースクリプトはかつかつなので、複数セッションでユーザースクリプトを複数動かせれば、かなり楽になる人おおいんじゃないかな

**Comment by kitty2117** [comment]
５分足、４本値の提供というのは、
９時５分になると、090500,1000,1010,950,990,3341(日付、始値、高値、安値、終値、売買高)がpushされてくるイメージ？
historical dataだとこの４本値のデータを９時から１０時までの間のデータ？

厳密には違うのか
４本値ダウンロードもhistorical dataも１０時から１１時までの１分足データをダウンロードするイメージでしたが、みんなどういう意味で４本値という言葉をつかっているんだろう？
