### ISSUE TITLE
【要望】kabuステーションとEver-ChartのGUI

### ISSUE THREAD

**Issue by kitty2117** [kabucom/kabusapi#555]
お世話になります

API関係ないのですが、ここに書いていいのかな？
トレードシステムのチューニングしていて、kabuステとEver-Chartを使い始めました。
気になった点があるので、お知らせします。はじめてつかってみたのでよくわかってないですが。。。

kabuステのチャート表示機能にボリンジャーバンドを表示する機能があるのですが
sigmaやma計算する期間の数字を変更できませんでした。固定で5,25,75、これはバグ？仕様？
Ever-Chartだと簡単に変更できました

Ever-Chartのストキャスティクスの表示画面で、スケールラインの数字の表示がおかしいです。
スケールラインを80,50,20にしても、画面には20,40としか表示されない

優先順位低いし、他社のツールでも代替できるので、どうでもいいことかもしれないけど、
とりあえず、ご報告

**Comment by yasuyuki-nakazawa** [comment]
kabuステーションのチャートの件ですね。
内容を確認してみますので、お待ちくださいませ

**Comment by kitty2117** [comment]
Ever-Chartだと、数字変更で変わりますが、
kabuステだと、数字を入力できるような感じなんですが、数字いれても、数字がかわらない

**Comment by kitty2117** [comment]
返信ありがとうございます
任意の期間が設定できないのは仕様ってことですね

**Comment by yasuyuki-nakazawa** [comment]
はい。現状仕様となります。
ご了承くださいませ
