### ISSUE TITLE
【質問】

### ISSUE THREAD

**Issue by Cobra0320** [kabucom/kabusapi#556]
カブコム証券のカブステーションAPIを使って225先物やFXの自動売買したいと思っております。そこでいくつか質問があります…  まだ、口座開設もカブステーションのダウンロードも一切していないので教えてください。

 1⃣カブステーションのプラットフォーム上でオリジナルのロジックをコード化したものを書き込み利用できるという事だと思いますが…  元々カブステーションに搭載されているテクニカル指標でしかコーディングは出来ないのでしょうか？  　
それ以外でも可能ですか？また、チャートの描画などについては、規定以外のものでも表示可能でしょうか？  

 2⃣書き込んだロジックで自動化した場合に、テスト売買などは出来ますか？     

3⃣バックテスト機能などはありますか？

**Comment by yasuyuki-nakazawa** [comment]
>カブステーションのプラットフォーム上でオリジナルのロジックをコード化したものを書き込み利用できるという事だと思いますが… 

こちらは少々違います。カブステーション側にREST形式でやり取りできるインターフェースを追加している形となります
そのため、お好きな言語でプログラムを記述いただくことが可能です。受信できるデータに関してはリファレンスを参照ください
また、プッシュ形式のデータ受領方法もございます。

>チャートの描画などについては、規定以外のものでも表示可能でしょうか？
チャートを操作するAPI等はございません。

>書き込んだロジックで自動化した場合に、テスト売買などは出来ますか？
テスト売買を行うことはできません。ただし、インターフェースの確認という形でのテストモードの機能はございます
バックテストは不可です

**Comment by cyber-minion** [comment]
解決済みのようで、いったんクローズさせていただきます。
