### ISSUE TITLE
【要望】VBAでの注文約定照会のQueryについて 　→【対応予定】

### ISSUE THREAD

**Issue by kabucomapi** [kabucom/kabusapi#56]
VBAでの注文約定照会のQueryに、注文IDで抽出できる仕様を追加いただけると、使い勝手が向上して助かります。
発注後、約定した数量を監視する時に、取引区分全ての情報が含まれる応答ですと、監視すべき発注情報を抽出するのに手間と時間がかかり、トレードにおいて不利になります。また、抽出ミスで誤発注につながるおそれもあるので、是非実装いただきたい機能です。
また、口座の情報についても一括取得ではなく、IDによる絞込ができると大変助かります。
よろしくお願いいたします。

**Comment by yasuyuki-nakazawa** [comment]
当件、検討しております。
注文約定照会におきましては、注文番号による照会、指定時間異常の更新情報の照会、PUSHによる変更通知等の検討を進めております。

**Comment by yasuyuki-nakazawa** [comment]
当件、対応する方向で整理しています。
注約照会の情報取得にフィルタリング機能を追加することで機能改善を図る予定です。
対象の注文番号、更新時間等、一定のパラメータを指定した条件で情報取得できる仕様を想定。
希望の取得条件等があれば、連携いただけると設計として考慮していきます

**Comment by kabucomapi** [comment]
お世話になります。
仕様追加の件、ご検討いただきありがとうございます。
私が現状開発している単純な売買システムにおいては、注文番号での抽出ができれば足りますが、複雑な発注ロジック開発に発展した場合は他の条件が必要になると考えています。
また、親注文に付与されるシーケンス番号以下の情報が、どのような条件で追加されるのか解析できていないので、その点が明確になると他の抽出条件も必要になる可能性があると考えます。公開可能な範囲で、どのような条件でシーケンス番号以下の情報が付与されるのか示していただけると助かります。例えば、注文変更するとシーケンス番号が付与される等、、、一つ一つ条件を想定しながら本番環境で解析するのは困難です。

それと、この話題とは別ですが、他の方も指摘されていたように、口座残高のリクエストに関するレスポンスが遅いように感じます。発注はスムーズに進みますが、その後、誤発注等防止の為に口座残高を確認するのですが、その待ち時間が長く高速注文を阻害しています。口座残高の確認は不要かもしれませんが、できる限り安全性を向上させる為確認するようにしてあます。このボトルネックが解消されると、さらに良いシステムになると思います。（レスポンスが遅いのは私のコードが原因かもしれません）

**Comment by kabucomapi** [comment]
少し検討してみましたが、私は約定の監視をしたいので、OrderStateとOrdTypeの値が一致しないものを抽出できると助かりますが、信頼性の観点から、注文番号で抽出したうえて上記値を管理するかを決めることになります。

**Comment by yasuyuki-nakazawa** [comment]
kabuステーション ver 5.12.4 にて注文約定照会と残高照会のフィルタリング機能を追加させて頂きました
