### ISSUE TITLE
【質問】信用保証金現金の残高を取得したいが可能か？

### ISSUE THREAD

**Issue by tettuan** [kabucom/kabusapi#560]
KabuStation本体のリアルタイム資産評価にて、現金の中に表示されている預かり金・信用保証金現金の合計を取得したいのですが、APIで可能でしょうか？

ドキュメントを拝見したところ、
/wallet/cash では現金買付可能額のみ、
/wallet/margin では新規余力のみ、
でした。
どちらも余力を取得する目的であろうと思います。

今回、余力原資となる現金のうち、増し担保で拘束されている現金がどの程度あるのかを知りたいため、お尋ねいたしました。

**Comment by yasuyuki-nakazawa** [comment]
こちら、確認中です。お待ちくださいませ

**Comment by yasuyuki-nakazawa** [comment]
確認しましたが、まし担保で拘束されている現金を抽出することはできません。

**Comment by tettuan** [comment]
ご確認ありがとうございます。
まし担保の拘束金額を知りたいわけではありません。
kabu station に表示されている、
保証金の総額が分かればよいのです。

そちらは取得可能でしょうか？

**Comment by cyber-minion** [comment]
連絡が遅くなり申し訳ございません。確認しましたが、保証金の総額も現状取得できない状況です。

**Comment by cyber-minion** [comment]
こちらのissueはいったんクローズさせていただきます。
