### ISSUE TITLE
calcpriceとは？

### ISSUE THREAD

**Issue by Uchiii7** [kabucom/kabusapi#562]
calcpriceとは？

**Comment by hori-ryota** [comment]
[【質問】計算用現値CalcPriceについて · Issue \#35 · kabucom/kabusapi](https://github.com/kabucom/kabusapi/issues/35)

**Comment by yasuyuki-nakazawa** [comment]
@hori-ryota さんの方でご回答いただいておりますが、こちら、計算用現値のこととなります

**Comment by cyber-minion** [comment]
解決済みのようですので、クローズさせていただきます。
