### ISSUE TITLE
【要望】PUSH配信する銘柄の現在登録されている一覧を取得するAPIを作成してほしい

### ISSUE THREAD

**Issue by necorox** [kabucom/kabusapi#563]
現状だと、registerを実行し、一度適当な銘柄を保存しないと現在保存されている一覧が取れないので、今登録している銘柄の一覧をAPIで取得できるようにしていただきたいです。

**Comment by yasuyuki-nakazawa** [comment]
単に登録銘柄が取得できるような参照系のインターフェースが欲しいということで理解いたしました。
当該ニーズは連携させていただきます

**Comment by yasuyuki-nakazawa** [comment]
すみません、こちらですが、registを銘柄指定なしで実行してみていただけますか？
銘柄一覧が取れるかと思います

**Comment by necorox** [comment]
上記試したところ400エラーとなりました。一応レスポンス記載しておきます。
HTTP Error 400: Bad Request
{'Code': 4001018, 'Message': '銘柄が登録できませんでした'}

**Comment by yasuyuki-nakazawa** [comment]
obj = { 'Symbols':[] }
のように指定して取得してみていただけますか

**Comment by necorox** [comment]
なるほど、obj ={} や obj指定しないは試してましたが、そちらは試してませんでした。
上記の内容で、現在登録されているリストの内容を取得できました。
ありがとうございます。

**Comment by yasuyuki-nakazawa** [comment]
無事取得できたとのことで、よかったです
