### ISSUE TITLE
【質問】

### ISSUE THREAD

**Issue by konitec** [kabucom/kabusapi#566]
お世話になります。
手順に沿って、Excelアドインをインストールして、Excelを立ち上げましたが、
リボンに「kabuSTATION アドイン」が追加されません。
どのように対応したらよいかを教えていただけないでしょうか？

**Comment by yasuyuki-nakazawa** [comment]
確認します
以下がご参考にはなるかと思いますが、いかがでしょうか
https://github.com/kabucom/kabusapi/issues/485

**Comment by konitec** [comment]
ありがとうございます。
実施してみたら、上手くいきました。

**Comment by cyber-minion** [comment]
解決済みですので、クローズいたします。
