### ISSUE TITLE
【質問】kabuステーションの自動起動

### ISSUE THREAD

**Issue by kitty2117** [kabucom/kabusapi#567]
お世話になります

kabuステーションをスクリプトで自動起動するにはどうすればよいでしょうか？
具体的には、08:55:00時に起動してログイン、15:05:00時にログアウトしてシャットダウン
こんな感じのスクリプトを作成することは可能でしょうか？
毎日手動でやるのも面倒です

**Comment by hori-ryota** [comment]
一般的なwindowsの自動操作でできるかと思いますよ

**Comment by yasuyuki-nakazawa** [comment]
horiさんがおっしゃっている通り、Windows操作でアプリケーションの起動、プロセスの終了は可能です
ただし、終了時に確認メッセージが出力されますので、自動化するためには強制的にプロセスを落とす必要があるか、もしくは終了時の確認メッセージボックスに対して「OK」のクリックリクエストを送信する必要がございます。
また、カブステーションは終了時に画面レイアウト含め諸情報を保存しておりますので、強制終了した場合は当該処理が走らないため、この点はご留意くださいませ

**Comment by kitty2117** [comment]
つまり、batファイルに
kabustation.exe id=xxx pw=xxxx
みたいな事書いて、タスクスケジューラに登録しろということでしょうか？
kabuステの実行ファイルの場所と、ログインIDとログインパワードを指定するスイッチはどうすれば良いのでしょうか？

**Comment by hori-ryota** [comment]
> 一般的なwindowsの自動操作

はGoogle検索で「Windows 自動操作」で出てくるような各ツールの話ですね。ツールの使い方の詳細は（私は）サポートできないので引っ込みます

**Comment by kitty2117** [comment]
検索してみました
GUIの操作登録してマクロにするツールあるんですね
kabuステの事は、gatewayサービスみたいに思っていて、GUIには想い至らなかった
以前、ローカルホスト以外からkabuステにアクセスする話あったけど、MACやLinuxからやってる人はみんなゲートウェイサービスだと思ってそう

現状では、kabuステの実行ファイルにidとpw渡して起動はできないのでGUIの操作登録を使えということですね、、、

ありがとうございました
