### ISSUE TITLE
【不具合】「この要求の送信中にエラーが発生しました」

### ISSUE THREAD

**Issue by tsujitakg** [kabucom/kabusapi#568]
■[必須] 不具合事象(概要)
kabuSTATIONアドインでAPIに接続しようとすると「この要求の送信中にエラーが発生しました」のメッセージが出て接続できない

■[必須] 本来想定されるアクションと事象
エクセルからのログインがなされトークンが取得される

■[必須] 不備発生時刻（常時の場合は、常時で記載ください)
2022/7/28 午前9時ころ
それ以前は問題なく作動していた

■[任意] お使いの環境(OS、Excelのバージョン等)、サンプル(Macro、アドインのバージョン）
OS：win11
Excelバージョン：Office Personal 2019
使用Excelファイル：kabuSTATION_API_ORDER_sample.xlms(サンプルプログラム)

■[任意] 不備部分のログ

**Comment by yasuyuki-nakazawa** [comment]
kabuステAPI、kabuステーションそれぞれのログにはどのようなエラーがかかれているかご確認いただけますでしょうか。
また、当該事象以降、このエラーが発生して接続できない状況は継続しておりますか？

**Comment by tsujitakg** [comment]
ログの取り方をご教示ください。
継続して接続できない状況です。

**Comment by tsujitakg** [comment]
当該時刻のログです
08:43以降に回線が切れてなんどか接続を試行したけれどExcel上に「この要求の送信中にエラーが発生しました」のメッセージボックスがでて接続できず、08:54にkabuステーションを閉じています

KabuS_20220727.log

08:43:41.5703,I,2624,0022 KeepSession at 2022/07/27 08:43:41
08:47:01.5848,I,2624,0012 KeepSession at 2022/07/27 08:47:01
08:50:08.8940,I,2624,0021 UpdateService.UpdateCheck : start
08:50:08.8940,I,2624,0021 UpdateService.DoUpdateCheck : start
08:50:08.9096,I,2624,0001 UpdateService.Callback : start
08:50:08.9096,I,2624,0001 UpdateService.Callback : ImportantAppVersion = 5017000000
08:50:08.9096,I,2624,0001 UpdateService.Callback : CurrentAppVersion   = 5017000000
08:50:08.9096,I,2624,0001 UpdateService.Callback : myVer               = 5017000000
08:50:08.9096,I,2624,0001 UpdateService.Callback : UpdateKind          = UpdateNone
08:50:21.5933,I,2624,0035 KeepSession at 2022/07/27 08:50:21
08:53:41.6162,I,2624,0013 KeepSession at 2022/07/27 08:53:41
08:54:00.8219,I,2624,0001 カブステAPI停止
08:54:00.8219,I,2624,0011 HttpListener終了済時のException
System.Net.HttpListenerException (0x80004005): スレッドの終了またはアプリケーションの要求によって、I/O 処理は中止されました。
   場所 System.Net.HttpListener.GetContext()
   場所 t4.b()
08:54:00.8219,I,2624,0010 HttpListener終了済時のException
System.Net.HttpListenerException (0x80004005): スレッドの終了またはアプリケーションの要求によって、I/O 処理は中止されました。
   場所 System.Net.HttpListener.GetContext()
   場所 t4.a()
08:54:01.1031,I,2624,0001 Logoff at 2022/07/27 08:54:01
08:54:01.1499,I,2624,0001 Finalize Start
08:54:01.2124,I,2624,0001 Finalize End

APIログは当該時間のものはありません

**Comment by tsujitakg** [comment]
今朝までは問題なく稼働していたのでwindowsをロールバックしたところ状況は回復しました。
但し、原因は不明です。

7月中旬以降、kabuSTATION_API_ORDER_sample.xlmsが開けない事象も起きそちらも対処したもののwindows updateが原因ではないかと疑っていました。
そのため、今回もロールバックしてみてました。

PCを2台使用していますが2台とも同じ現象が出ますので、他の方々にも問題が生じているのではないかと思っています。

**Comment by yasuyuki-nakazawa** [comment]
当該エラーを拝見いたしましたが、セキュリティソフト（ウィルスソフト）のご利用はいかがでしょうか。
通信遮断を受けているように見えます

**Comment by tsujitakg** [comment]
yasuyuki-nakazawaさん、返信できませんでした、すみません。
セキュリティソフトの影響ではないと思われます。
Windows10と11の2台で利用していますが7月はそれぞれのWindows Updateの翌日(別々の日)から利用できなくなりました。
8月は11の方だけやはりWindows Updateの翌日から利用できなくなりロールバックで復活し、10の方は問題は起きませんでした。
いずれも同じセキュリティソフト(Kaspersky)を使用しています。

**Comment by yasuyuki-nakazawa** [comment]
記載の件から推測ですと、OSのアップデートでWindows11にした場合に事象が発生ということで、
再現性含めて検証してみます

**Comment by cyber-minion** [comment]
他のユーザーさんにて同じ事象が発生しており、アドインをアンインストール→再インストールで改善されたそうです。
再発した際、下記手順にてお試しいただければと思います。

https://github.com/kabucom/kabusapi/issues/599#issuecomment-1292999358

**Comment by cyber-minion** [comment]
本件はいったんクローズさせていただきます。再発しましたらご連絡ください。
