### ISSUE TITLE
【不具合】kabuSTATION_API_ORDER_sample が動作しません

### ISSUE THREAD

**Issue by ttkk12** [kabucom/kabusapi#569]
■[必須] 不具合事象(概要)
kabuSTATION_API_ORDER_sampleを読み込もうとするものの、ファイルが開かれずエクセルがハングアップしたり、添付のエラーが出たりします。またファイルを直接読み込んだ場合はシステムエラーが発生します。

■[必須] 本来想定されるアクションと事象
kabuSTATION_API_ORDER_sampleが読み込まれ、ここから注文ができます。

■[必須] 不備発生時刻（常時の場合は、常時で記載ください)
2022年6月末までは通常通り使えていました。しばらく使用していませんでしたが、7月20日過ぎに使用した際から使えなくなっています。

■[任意] お使いの環境(OS、Excelのバージョン等)、サンプル(Macro、アドインのバージョン）
Win10、Excel2019 32bit、マクロアドインは現時点で最新版をダウンロードしています

■[任意] 不備部分のログ

![capture02](https://user-images.githubusercontent.com/110325813/182014892-11d7719d-9072-48b0-85a3-3ab8d80194db.JPG)
![capture01](https://user-images.githubusercontent.com/110325813/182014893-41bef5dd-a8fc-4d72-af59-a615efe8252f.jpg)

**Comment by cyber-minion** [comment]
添付ログは拝受し、こちらにて調査いたします。
※ログの中に口座番号が入っていたため、ファイルはこちらにて削除させていただきました。

**Comment by cyber-minion** [comment]
ファイルにアクセスできないとのエラーですので、以下をご確認いただけますでしょうか。
・ファイルが存在するか
・ファイルを再度、デスクトップ等にダウンロードしてファイルが開けるか
・PCを再起動して改善するか

**Comment by ttkk12** [comment]
指示いただいた方法で1回は操作可能でした。

ただ、そのあと一度エクセルを保存じて、再度起動するとエクセルが起動しなくなり、タスクマネージャーから強制終了、再起動するとこのようなメッセージが出て、このエクセルが使えなくなります。
これは前に申告させていただいた時から生じている事象です。

全てのエラーをお伝えできておりませんが、このようなループにはまってしまっています
![20220803](https://user-images.githubusercontent.com/110325813/182480337-1d3d1170-7c4c-4f2e-b6a0-68f6f9d3c391.jpg)
。

**Comment by cyber-minion** [comment]
本件は調査・確認しております。今しばらくお待ちください。

**Comment by cyber-minion** [comment]
念のため確認ですが、アドインをダウンロードした際、すべてのファイルをダウンロードしましたでしょうか。

※ダウンロードの際、ブラウザにて「ファイルダウンロードを継続しますか」というようなメッセイージが表示される場合があります。そうなった場合、「継続」をクリックする必要があります。

**Comment by ttkk12** [comment]
ご対応ありがとうございます。
改めて旧アドイン、エクセルをすべて削除し、ファイルを再度ダウンロードしなおしました。「ファイルダウンロードを継続しますか」のメッセージは出ませんでした。その後の動作については残念ながらこれまでと変わりありません。
追加で必要な証跡等ありましたら指示いただけるでしょうか。ログ等も複数種類あるようなのでパス等を指摘いただけると幸いです。

**Comment by ttkk12** [comment]
その後しばらく使用していなかったのですが、2日ほどにアドインに組み込んだ際に通常に動作し、保存後もエラー無く動作しました。以前もこれを数日繰り返すと動作しなくなったのですが、とりあえずご報告させていただきます。
Excelのバージョンアップ等は特にしていません。Windows側にて添付のアップデートがありました
![キャプチャ](https://user-images.githubusercontent.com/110325813/185730032-28bcf246-4a7f-4b5f-8d06-e7ded823e0ba.JPG)
。

**Comment by cyber-minion** [comment]
本事象、最近再発していますでしょうか。

**Comment by ttkk12** [comment]
先日の自動回復の報告後、2，3回APIを使用しましたが不具合は再発していません。
いったんクローズとして、再発時に再度このスレッドに投稿するようにします。
いろいろとご対応ありがとうございました。

**Comment by cyber-minion** [comment]
承知いたしました。再発時に再度投稿いただければと思います。
