### ISSUE TITLE
【質問】kabuSログファイル

### ISSUE THREAD

**Issue by omake5656** [kabucom/kabusapi#57]
トークン取得可能、銘柄情報の取得可能ですが、
いざ注文発注しようとすると
"Code":4001005,"Message":"パラーメータ変換エラー - 詳細はkabuSログファイルを確認してください"
とコケます。

kabuSログファイルというのは KabuSTATION のどこかに出力されるものなのでしょうか？

以上よろしくお願いいたします

**Comment by tsuchinaga** [comment]
#11 に回答がありますよ

> kabuステーションのログは下記のパスに格納されております。  
> %appdata%\KabuS\Log

**Comment by omake5656** [comment]
ご助言ありがとうございました。確認いたします。
既出とのこと、申し訳ありませんでした
