### ISSUE TITLE
【質問】成行の空売りが規制される

### ISSUE THREAD

**Issue by kitty2117** [kabucom/kabusapi#571]
お世話になります

取引していると下記のようなエラーが発生します

{'Code': 100317, 'Message': '同一銘柄の信用新規売り（空売り）の注文数量合計が50単位を超えるため、空売りの価格規制違反を未然に防止する観点から、成行または成行を含む執行条件でのご注文はお受けできません。'}

これは、例えば、単位１００株価格３００円の株を空売りする場合は、100（株）×50（単位）×300（円）＝1,500,000（円）を成行で注文すると、その後はその銘柄の空売りの成行はできなくなる、ということでしょうか
前場と後場で同じ規制があるようです

このエラーの回避方法は成行の空売り注文でなく、例えば、GET boardで取得できる ’Buy10’ 買気配数量10本目の価格で指値すればよい？買い板にならんでいる株数より少ない空売り株数ならこれで回避できる？

空売りの価格規制違反とは、どこの誰がどんな根拠で規制しているのでしょうか？証券取引等監視委員会かな？

よろしくお願いします

**Comment by kitty2117** [comment]
それともう一点
信用の買いポジションを成行で売る場合は、エラーメッセージを見る限り関係なさそうですが、それは問題ないでしょうか？

**Comment by kitty2117** [comment]
GET /symbol/{symbol}で取得できるUpperLimitとLowerLimitを場の始まり前に取得して
UpperLimitの価格で買い注文をすれば、成行買いと同じになり
LowerLimitの価格で売り注文をすれば、成行売りと同じになるのかな？
そうすると、指値で成行の売買と同じ効果がでる

この解釈でいいのかな？

**Comment by yasuyuki-nakazawa** [comment]
回答またお待ちください

**Comment by yasuyuki-nakazawa** [comment]
APIの仕様ではなく、空売り規制に抵触している行為であるため、リジェクトされているものになります。
以下の空売り規制のため、エラーが返却されています。

今回の例ですと、主に以下の点に抵触する注文は実施できません。
①ワンショット上限
　成行または不成により、51単元以上を発注すること

②累計数量上限
　成行または不成で、累計注文が同一銘柄で51単元以上


エラーメッセージにあるように「注文数量合計が50単位を超える」となっていることから、
成行で数量を小間切れで発注をしているかと推測されますが、いかがでしょうか。

**Comment by yasuyuki-nakazawa** [comment]
> このエラーの回避方法は成行の空売り注文でなく、例えば、GET boardで取得できる ’Buy10’ 買気配数量10本目の価格で指値すればよい？買い板にならんでいる株数より少ない空売り株数ならこれで回避できる？

エラーを回避して注文を行うには、指値で発注ください。

> 信用の買いポジションを成行で売る場合は、エラーメッセージを見る限り関係なさそうですが、それは問題ないでしょうか？

新規ポジションに対しての返済(売)のことと想定しての回答となりますが、
こちら返済は対象外となります。


> GET /symbol/{symbol}で取得できるUpperLimitとLowerLimitを場の始まり前に取得して
> UpperLimitの価格で買い注文をすれば、成行買いと同じになり
> LowerLimitの価格で売り注文をすれば、成行売りと同じになるのかな？

実質的には成り行き的な動きになるかと思いますが、指値であれば上述の規制からは外れると思慮いたします

**Comment by kitty2117** [comment]
おはようございます
お世話になります

株価４００円くらいの株を１分足スキャルピングしてて発生したので、
値段の安い株で成行の空売りはあまり現実的ではないということですね

GET boardの’Buy10’でやろうと思います

ありがとうございます
