### ISSUE TITLE
【質問】kabuステのHOTキーと連携

### ISSUE THREAD

**Issue by nyamtan** [kabucom/kabusapi#572]
お世話になります。
kabuステーションではＨＯＴキーで別のウインドウで銘柄に連動できますが、自作プログラムウィンドウもこれと同じに連動させてみたいです。kabuステでの銘柄遷移時のタイミングやその時表示中の銘柄コードはAPIで取得できないでしょうか。

**Comment by yasuyuki-nakazawa** [comment]
申し訳ございません。
カブステAPIはカブステーションのUIを操作するためのAPIではないため、APIを介しての画面操作は実施できません。
要望されている機能を実現する場合は、カブステーションに関して直接Windowsメッセージを送信するようなプログラムを書くことで実現は可能だと思慮いたします。

**Comment by cyber-minion** [comment]
こちら、いったんクローズさせていただきます。
