### ISSUE TITLE
オフラインテスト【質問】

### ISSUE THREAD

**Issue by tashida0726** [kabucom/kabusapi#574]
APIを使ってトレードするプログラムをテストする場合に、オフラインで注文の発行やステータスのチェックのみ出来るようなモードはありませんでしょうか？
前にそれように本番用とは別のAPI用URLを見たような気もするのですが見つかりません。

**Comment by yasuyuki-nakazawa** [comment]
スタブ的なテストモードは存在しますが、ステータスの変更等を確認することはできません。
テストモードに関しては、APIシステム設定の「検証用」をご利用することで疎通の確認は可能となっております。

**Comment by cyber-minion** [comment]
本件、いったんクローズさせていただきます。
