### ISSUE TITLE
【質問】デイトレ信用の利率と返済について

### ISSUE THREAD

**Issue by kouyuus** [kabucom/kabusapi#575]
ご担当者様
お世話になります。
２点お伺いさせてください。

①デイトレ信用の総費用に関しまして
総費用は
1)売り建ての場合
手数料＝０
貸株料＝株価×1.80%/365日
※プレミアム料なし、当日返済の場合
2)買い建て
手数料＝０
金利＝株価×1.80%/365日
名義書き換え料＝単位数＊55円
と理解しているのですが、正しいでしょうか。

②返済に関しまして
仮に上記が正しいとして、
返済はトレード毎でしょうか、それとも一日の中で複数トレードを持ち越しての返済はできるのでしょうか。
これは例えば、同じ銘柄の空売りを一日に複数回行ったとして、
上記の貸株料は何回加算されるのかを知りたくお伺いします。
また複数トレード持ち越すことができる場合、CashMarginは何を選択することが適切でしょうか。

お忙しいところ恐縮ですが、よろしくお願いいたします。

**Comment by yasuyuki-nakazawa** [comment]
こちらは、手数料や利率等の被用のご質問ですね。
回答お待ちください

**Comment by cyber-minion** [comment]
お待たせいたしました。デイトレ信用に関する費用は以下となります。

▼新規売の場合
総費用 = 貸株料 + プレミアム料
※貸株料：1注文あたり約定金額100万円以上であれば0%、1注文あたり約定金額100万円未満であれば1.80%
　例えば、90万円の約定でしたら、貸株料 = 90万円 * 1.8% = 1.62万円
※プレミアム料：1日につき1株あたり当社指定の価格

この建玉に対する返買の費用は、貸株料 + プレミアム料 となります。

▼新規買の場合
総費用 = 金利
※金利：1注文あたり約定金額100万円以上であれば0%、1注文あたり約定金額100万円未満であれば1.80%
※名義書換料は、買い建玉がある状態で当該銘柄の決算期末等を越えた場合に発生する費用ですので、信用建玉について権利確定日をまたいで建玉ではない場合は発生しません。

この建玉に対する返売の費用は金利となります。


詳しくはホームページにてご確認いただければと思います。
https://kabu.com/item/shinyo/about/deitore.html



また、返済する場合、建玉を指定する必要があります。
建玉指定の方法は、ClosePositionOrder（決済順序）とClosePositions（返済建玉指定）とあります。
https://kabucom.github.io/kabusapi/reference/index.html#operation/sendorderPost
返済の場合、CashMarginは「3」と指定ください。

**Comment by cyber-minion** [comment]
解決済みのようですので、クローズさせていただきます。
