### ISSUE TITLE
【質問】各銘柄の刻み幅を取得する方法はありますか

### ISSUE THREAD

**Issue by necorox** [kabucom/kabusapi#576]
表題の通りです。
/symbol/{symbol}
に数量の単位の売買単位がありましたが、価格の単位の刻み幅（0.1円刻みなのか1円なのか10円なのか）がありませんでした。
APIにて各銘柄の刻み幅を取得する方法はありますでしょうか？
無い場合、上記APIか、/board/{symbol}に該当の情報を追加してほしいです。

**Comment by hishiharahaz** [comment]
@necorox さん
APIにて、呼値は取得できなかったと思います。
現状ですと、以下になるかと思います。
1. /symbol/{symbol}で「PriceRangeGroup」を取得する。
2. PriceRangeGroupが、10000：株式(TOPIX100採用銘柄以外)か10003：株式(TOPIX100採用銘柄)を判断する。
3. 以下の呼値表より、呼値が決まる。
https://www.jpx.co.jp/equities/trading/domestic/07.html
※JPXサイトより

**Comment by yasuyuki-nakazawa** [comment]
回答いただいている通り、呼び値の取得はできません。
URL記載のとおりのルールがございますので、こちらを取り込み頂けますでしょうか。

**Comment by necorox** [comment]
@hishiharahaz @yasuyuki-nakazawa 
わかりました。ご回答ありがとうございます。

**Comment by cyber-minion** [comment]
解決済みのようですので、クローズさせていただきます。
