### ISSUE TITLE
【質問】注文約定照会 state	 について

### ISSUE THREAD

**Issue by john-banjirou** [kabucom/kabusapi#577]
質問失礼します。

1 | 待機（発注待機）
2 | 処理中（発注送信中）
3 | 処理済（発注済・訂正済）
4 | 訂正取消送信中
5 | 終了（発注エラー・取消済・全約定・失効・期限切れ）

上記になっております。
IOC注文をしたと仮定します。
約定の株数は、3 | 処理済、を見た後で、初めて、変わることがない、
この認識で間違いがないでしょうか？

もうすこし言いますと、
3 | 処理済、を、確認。そして、約定照会をする。
この約定照会で得た約定株数で、これ以後、この約定株数は、かわることがない、と考えてよろしいでしょうか？
（IOC注文は、不出来、は、自動的に取消しされる、と存じています）

よろしくおねがいします。

**Comment by yasuyuki-nakazawa** [comment]
IOCの約定状態を確認したいということでしょうか。
IOCの場合は即座に約定か執行かわかりますので、State=5 を確認の上、約定数をご確認いただいたほうが良いと思慮いたします

**Comment by cyber-minion** [comment]
解決済みのようですので、クローズさせていただきます。
