### ISSUE TITLE
【質問】GET /ranking 詳細ランキングの日付切り替え時間

### ISSUE THREAD

**Issue by kitty2117** [kabucom/kabusapi#578]
お世話になります。

kabuステーション（GUI）だと、詳細ランキングに当日、１営業日前、２営業日前、３営業日前のランキング表示ができるようになっています。

このランキングなのですが、場の始まる前のある時間（何時かわからない、気づくと変わっている）に日にちの切り替えが行われて、当日のデータが該当なし？になってランキングが取得できなくなります。
この日付の切り替えのおおよその時間はわかるでしょうか？

場の始まる前の朝一番に監視銘柄のスクリーニングを行いたいのですが、kabusapiだと１営業日前や２営業日前のランキングが取得できないので、日にち切り替え前にランキング情報を取得したいと思います
kabsapiでも、１営業日前とか２営業日前のランキング取得できると一番良いけど

よろしくお願いします。

**Comment by hishiharahaz** [comment]
@kitty2117 さん
以下によると7:53頃にクリアされるようです。
https://kabucom.github.io/kabusapi/reference/index.html#operation/rankingGet

**Comment by kitty2117** [comment]
> @kitty2117 さん 以下によると7:53頃にクリアされるようです。 

hishiharahazさん
マニュアルに書いてあったんですね
ありがとうございます

7時53分だと、ランキングのDLして、銘柄情報みたり、諸々で処理には10分くらいかかるかも、7時40分くらいからやるか
朝早いな、他のサイトで代替も考えて良いかも

**Comment by hishiharahaz** [comment]
@kitty2117 さん
引けた後の15:00過ぎにランキングDLしておいて、後ほどスクリーニングするでもよさそうな気がします。

**Comment by kitty2117** [comment]
言われてみれば、そうですね
15時過ぎに起動して、監視リスト作り

tickと出来高あたりに、その日の高安反転回数あたりを加味して、スクリーニングかな
4本値の時系列データダウンロード早くできるようにならないかな
