### ISSUE TITLE
【質問】win pcを持ってない。API利用開始の初期設定する方法。

### ISSUE THREAD

**Issue by hilomaca** [kabucom/kabusapi#579]
win pcを持っていません。
API利用開始の初期設定する方法を教えて下さい。

以下で詰まっています。
・winアプリを入れて、winアプリでAPI利用設定、APIパスワード設定するところ。

(WEBのどこかでできる？)

**Comment by hishiharahaz** [comment]
@hilomaca さん
以下に初期設定の記載があります。
ご確認ください。
https://kabucom.github.io/kabusapi/ptal/howto.html

**Comment by hilomaca** [comment]
※ ちゃんと理解している方の対応をお願いします。

確認しました。
何も解決しませんでした。

これまでと同じwinアプリでAPI利用設定、APIパスワード設定する手順でした。


具体的には、
kabuステーション「APIシステム設定」の章のkabuステーションはwinアプリです。
私はwin PCを持っていません。

**Comment by yasuyuki-nakazawa** [comment]
お困りのポイントがわからないので、具体的に教示いただけると回答できるかと思います

まず、win pcをお持ちでない　というのは、Windows pcではなく、仮想的にWindowsを動かし、そのＯＳ上でカブステーションをインストール稼働させているということでしょうか？

**Comment by yasuyuki-nakazawa** [comment]
APIパスワードを設定するところと記載ございますが、その部分の何にお困りなのでしょうか？

**Comment by yasuyuki-nakazawa** [comment]
カブステーションAPIはサーバーとやりとりするAPIではなく、カブステーションと介してやり取りするインターフェースとなっています
オープンAPIをご想像されてらっしゃるようでしたら、その点は異なります

**Comment by hilomaca** [comment]
普通のWEB APIだと思っていました。
REST API, PUSH API と書いているのにWEB APIではないということでしょうか？
それって、どこかのWEBページに説明ありますでしょうか？

システム構成図みたいなWEBページはありますでしょうか？
（簡単なもので結構です）

kabu station(win アプリ)を起動しておいて、そいつがlocalhostのサーバーになってRESTの受け口になるイメージでしょうか？
(アプリ開発中にlocalhost起動して動作確認するときみたいな)

**Comment by hilomaca** [comment]
ちなみにherokuでpython動かして自動売買させようと思ってたのですけどダメっぽいですね。

**Comment by yasuyuki-nakazawa** [comment]
>どこかのWEBページに説明ありますでしょうか
以下をご参照ください
https://kabu.com/company/lp/lp90.html

>システム構成図みたいなWEBページはありますでしょうか？
こちらは適切なものはないと思われます

>kabu station(win アプリ)を起動しておいて、そいつがlocalhostのサーバーになってRESTの受け口になるイメージでしょうか？
そうですね。そういったイメージとなります

**Comment by yasuyuki-nakazawa** [comment]
>ちなみにherokuでpython動かして自動売買させようと思ってたのですけどダメっぽいですね。
>あと、google colabのjupyternotebookから叩いたり。
>
>どこかに仮想win上げるか、安いPC探します

前提がカブステーションが起動していること。カブステーションとの疎通を実施することとなりますので、
WindowsOS配下でカブステーションが起動している必要があります。

**Comment by hilomaca** [comment]
認識あっています。　
ありがとうございました。
