### ISSUE TITLE
【質問】リファレンスsendorderのDelivTypeについて（信用返済時）

### ISSUE THREAD

**Issue by takasheep** [kabucom/kabusapi#58]
Pythonにてサンプルを参考に実口座でテストを行っております。

リファレンス上、sendorderのDelivTypeについては、
「※現物売、信用返済の場合は「0(指定なし)」を指定する。」
とありますが、信用返済発注の際、0指定ではエラーとなり発注できませんでした。
「パラメータ変換エラー」が返ります。

その他の項目も含めて試行錯誤した結果、DelivTypeに、2（お預り金）を指定すると発注できました。
これはリファレンスの記載が誤っているのか、それとも違う原因でしょうか。

ちなみに新規発注時は、"DelivType": 2で発注出来ております。

エラーになったJSONも貼っておきます。
{"Password": "******", "Symbol": "4452", "Exchange": 1, "SecurityType": 1, "FrontOrderType": 26, "TimeInForce": 0, "Side": "1", "CashMargin": 3, "MarginTradeType": 1, "DelivType": 0, "FundType": "  ", "AccountType": 12, "Qty": 100, "ClosePositionOrder": null, "ClosePositions": [{"HoldID": "E20200903*****", "Qty": 100}], "Price": 6527, "ExpireDay": 20200903}'

どうぞよろしくお願い致します。

**Comment by yasuyuki-nakazawa** [comment]
当件、確認いたしました。下記となります。こちらを元に設定の程、よろしくお願いいたします
・現物買はDelivTypeを指定する
・現物売はDelivTypeを指定なし
・信用新規はDelivTypeを指定なし
・信用返済はDelivTypeを指定する

リファレンスについては更新させて頂きます。

**Comment by takasheep** [comment]
ご確認ありがとうございました。内容了解しました。
リファレンスの修正よろしくお願いします。

なお、信用新規については、"DelivType":0で指定して成功してました。見間違え失礼しました。

**Comment by yasuyuki-nakazawa** [comment]
コメント、ご確認ありがとうございます。
新規に関しては 0：指定なし　が正ということは確認いたしました。
