### ISSUE TITLE
【質問】GET /rankingのresponseについて

### ISSUE THREAD

**Issue by kitty2117** [kabucom/kabusapi#580]
お世話になります。

GET /rankingのレスポンスに、売買高’TradingVolume’、売買代金’Turnover’というのがあります。

売買高’TradingVolume’の計算方法はどうなっているでしょうか？
実際に取引された株数の計算はどうすればいいでしょうか？
(表示の数字)×10000 ?
(表示の数字)×単位株数 ?

売買代金’Turnover’の計算方法は100万倍すれば売買代金になるのかな？

よろしくお願いします。

**Comment by cyber-minion** [comment]
売買高と売買代金は、以下となっています。
※リファレンスを補完するようにいたします。

①売買高
　売買高を千株単位で表示する
　※百株の位を四捨五入

②売買代金
　売買代金を百万円単位で表示する
　※十万円の位を四捨五入

**Comment by kitty2117** [comment]
早い返信ありがとうございます。

それでいろいろやってみます。
