### ISSUE TITLE
【質問】Excel Addin がエクセルから消えません

### ISSUE THREAD

**Issue by sotoboft** [kabucom/kabusapi#582]
Addinファイルは削除しましたが、エクセルはそれらを探そうとして見つからずエラーを返します。有効なアドインのリストから削除しても、エクセルを再起動すると復活してしまいます。初期状態に戻すにはどうすればよいでしょうか？
復活するアドインは、Kabusuteaddin-Addin, Kabusuteaddin-Addin64, Kabusuteaddin-Addin64-Packedです。有効なアドインとして復活しますが、アドイン・ファイルは削除されているので、有効なはずはないです。チェックをはずすと、リストから削除しますかと聞かれ一旦その場では削除されます。しかし、エクセルを再起動すると復活し、しかしファイルが存在しないのでエラーになります。これらを完全になくしてしまいたいのですが、方法が分かりません。

**Comment by yasuyuki-nakazawa** [comment]
レジストリに保存されていることが想定されます。少々お待ちくださいませ

**Comment by cyber-minion** [comment]
確認ですが、PC再起動でも直らない状況でしょうか。

**Comment by sotoboft** [comment]
はい、実はこの問題はかれこれ１年くらい継続しています。

**Comment by sotoboft** [comment]
ネットなどにある方法をいろいろ試したのですが、どれもうまくいきませんでした。

**Comment by sotoboft** [comment]
なお、エクセルのバージョンは、Microsoft Excel for Microsoft 365 MSO (バージョン 2207 ビルド 16.0.15427.20182) 64 ビット、OSはWindows10です。

**Comment by cyber-minion** [comment]
エラー発生時の画面キャプチャをいただくことは可能でしょうか

**Comment by sotoboft** [comment]
![Msg1](https://user-images.githubusercontent.com/86093609/187136968-f0ea4f02-570b-4680-beb5-43ce1f747dcc.png)
![Msg2](https://user-images.githubusercontent.com/86093609/187137007-7f5e3616-f355-4f62-9700-7e662824df2b.png)
![Msg3](https://user-images.githubusercontent.com/86093609/187137017-51579baf-2d01-4165-8a0a-d00917928c94.png)
![Msg4](https://user-images.githubusercontent.com/86093609/187137031-4efeba4e-b285-4f35-a65f-24221fca0c4a.png)
![Msg5](https://user-images.githubusercontent.com/86093609/187137042-38d24ba6-494e-47ad-9c67-d45d6eb1fd14.png)
![Msg6](https://user-images.githubusercontent.com/86093609/187137048-65ceec93-6e7a-4b3a-b362-e8be5ca32973.png)
![Msg7](https://user-images.githubusercontent.com/86093609/187137066-58d29be8-4047-400f-bc6e-b84d0a0c75af.png)
![Msg8](https://user-images.githubusercontent.com/86093609/187137075-1f57f1e1-d818-494e-af41-6c479ade0c92.png)
![Msg9](https://user-images.githubusercontent.com/86093609/187137107-0cb2f8dd-0a3d-4c99-9b11-76ca12a14811.png)

ご連絡ありがとうございます。
エクセルを立ち上げる度に添付の９つのメッセージが順番に現れます。OKを押すと次のメッセージが現れます。すべてOKでしのぐとエクセルを立ち上げられます。
エラーというと大げさですが、これらのメッセージをOKでしのげば、エクセルは立ち上がるので、エクセルが使えないというわけではありません。これらのエラーは存在しないアドインファイルを読みに行こうとするために起こると考えられます。ですので、アドインからこれらの存在を消したいのですが、消せなくて困っています。
補足しますと、消せないと書きましたが、アドインの管理で一旦は消すことができます。しかしエクセルを終了し立ち上げ直すとそれらが復活してしまうので、同じことの繰り返しになります。

**Comment by cyber-minion** [comment]
キャプチャの共有、ありがとうございます。確認いたします。
※ユーザ名を隠して、再添付させていただきました。

**Comment by cyber-minion** [comment]
以下をお試しいただけますでしょうか。
※試し済みでしたら申し訳ございません。
※Excelからアドインを外してから、アドインファイルを削除する、で改善するか確認したいというのが意図です。

１．アドインファイルを再度ダウンロードし、Excelにインストール済みの状態にする。
２．Excelを終了し（すべてのファイルを閉じるように）、再起動する。
３．ファイル > オプション > アドイン の順に開き、リストからKabusuteaddin関連のところでチェックを外す。
４．Excelを終了する。
５．アドインファイルを削除し、Excelを再起動する。

**Comment by sotoboft** [comment]
![Msg10](https://user-images.githubusercontent.com/86093609/187170164-21be1ffe-d1d0-4022-9cec-c3a9a9a7cc64.png)
まずアドインファイルを配置しExcelを立ち上げたところで、添付のエラーが出ました。「いいえ」を選択するともう一度同じメッセージが出て、再び「いいえ」を選んでエクセルが立ち上がります。「はい」を選ぶと、変な文字の羅列のエクセルファイルが立ち上がります。その後、どちらの場合においても、指示通りの操作をしたところ、やはり同じ現象が起こります。ただ、エラーメッセージの出る回数は少なくなりました。（９個→６個）
アドインのチェックを外したはずのところにチェックが勝手に戻ってしまっているのが原因と思います。アドインファイルを残しておいても削除しても、外したチェックは、エクセルを再起動すると元に戻ってしまいます。

**Comment by cyber-minion** [comment]
お手数ですが、以下の手順をお試しいただけますでしょうか。

１．Excelを終了する。
２．下記場所にて、アドインのファイルを削除する。
　　C:\Users\Username\AppData\Roaming\Microsoft\AddIns
３．Excelをセーフモードで起動する。
　　セーフモードの起動方法：
　　①「スタート」アイコンを右クリック
　　②ファイル名を指定して実行(R) をクリック
　　③「excel /safe」を入力し、「OK」をクリック
４． ファイル > オプション > アドイン > 設定　の順に開き、リストからKabusuteaddin関連のところでチェックを外す。
５．Excelを終了し、PCを再起動する。

**Comment by sotoboft** [comment]
試しましたが進展はありませんでした。どうしてもアドインの残像が復活してしまいます。どこか（レジストリ？）にべた書き
されているとしか思えません。

**Comment by sotoboft** [comment]
レジストリで気になるのは添付の黒枠で囲んだあたりです。これらが消えないのが問題なのではないかと推察しますが、手動で消してしまってよいものかどうか分かりかねます。
![registry](https://user-images.githubusercontent.com/86093609/187445785-f61800e3-3315-4d6a-bc81-497158c80338.png)

**Comment by cyber-minion** [comment]
こちらで確認したところ、上記黒枠内のものがないので、削除いただき、改善するかご確認いただければと考えております。

**Comment by sotoboft** [comment]
これら（＋OPEN9）を削除したところ問題は解決しました。ありがとうございました。
これらはいったい何だったのでしょうね？　少なくとも私が書き入れたものではなく、勝手に入ってきたものです。
