### ISSUE TITLE
【不具合】

### ISSUE THREAD

**Issue by tsukui42** [kabucom/kabusapi#585]
■[必須] 不具合事象(概要)
時間が経過すると呼び出しがログイン認証になってしまう。

最初はＡＰＩが使えているが、10分後にエラーになるときもあれば30分後にエラーになるときもある。
kabuステーションにはログインできていて、問題なく操作ができる状態。右上のアイコンは緑色になっている。
試しに30秒置きにランキングを取得してみて、どれくらいの時間でそうなるのか、時間帯に影響するのか調べている。
今のところは場中ではない時間で調べてみて、朝でも昼でも夜でもこの症状となる。

■[必須] 本来想定されるアクションと事象
ＡＰＩがエラーせずに使い続けたい。

■[必須] 不備発生時刻（常時の場合は、常時で記載ください)
常時。

■[任意] お使いの環境(OS、Excelのバージョン等)、サンプル(Macro、アドインのバージョン）
ＭＡＣにＶＭｗａｒｅ　ｐｌａｙｅｒをインストールし、ｗｉｎｄｏｗｓ１１を使っている。
環境依存が怪しいとは考えています。

■[任意] 不備部分のログ
HTTP Error 401: Unauthorized
{'Code': 4001007, 'Message': 'ログイン認証エラー'}

**Comment by cyber-minion** [comment]
事象発生時に、ログイン/ログアウトのアイコンはどのような状態でしたでしょうか。

※このアイコンです
![image](https://user-images.githubusercontent.com/69830869/189574141-78762bdf-95b5-48ca-94be-6dd76a308de5.png)

**Comment by tsukui42** [comment]
事象発生時は青色です。うまくいっているときは緑色なのでログアウト状態ということですね。
おそらくですが、ホストOSのMacがスリープの時に事象が発生するようです。
ですが、スリープしたらすぐに事象が発生するわけではないのが難しいところです。
スリープしたらゲストOSの時刻が進まなくなるようでして、それが関係あるのかどうか。
もし、不正な時刻でログアウトするような仕様があれば教えてください。

まずは、ホストOSをスリープにさせない設定にし、長時間の接続試験を続けてみます。

**Comment by cyber-minion** [comment]
ログイン状態の確認ですが、3分間ごとにチェックが行われます。そのため、接続が切断されると、ログアウトとして処理いたします。

> ・・・スリープにさせない設定にし・・・

引続きご確認いただければと思います。

**Comment by cyber-minion** [comment]
また、カブステは早朝にセッションは強制的にログアウトさせていただいておりますので、利用可能時間は6:30から翌早朝6:15までとなります。

**Comment by tsukui42** [comment]
なんとか24時間近い連続動作が確認できました。その前に数回場中にログアウトしたのでまだ安定するかは様子見が必要ですが、その時の再現性を報告できる材料もなく、また再現したら改めてサポート依頼します。
