### ISSUE TITLE
【質問】カブステーションが起動しません。

### ISSUE THREAD

**Issue by gfd05600** [kabucom/kabusapi#586]
問い合わせ先がここでよいのか分かりません。ここと違うなら問い合わせ先を教えてください。

Ｗｉｎ10を1１にアップグレードするためＵＥＦＩのセキュリテイとＴＰＭ２．０の設定をＢＩＯＳを設定変更した関係でしょうか？。なおKabis/logをみましたが何らもログ記録はありませんでした。

エラー内容

プラットフォームのバージョン情報
	Windows 			: 10.0.22000.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.8.4341.0 built by: NET48REL1LAST_C
	clr.dll 			: 4.8.4515.0 built by: NET48REL1LAST_C
	dfdll.dll 			: 4.8.4341.0 built by: NET48REL1LAST_C
	dfshim.dll 			: 10.0.22000.1 (WinBuild.160101.0800)

ソース
	配置の URL			: file:///C:/Users/gfd05600/OneDrive/Desktop/kabu%E3%82%B9%E3%83%86%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3.appref-ms%7C
						X-Powered-By	: ASP.NET
	配置プロバイダの URL		: http://download.r10.kabu.co.jp/kabustation/KabuStation.application
	アプリケーションの URL	: http://download.r10.kabu.co.jp/kabustation/Application%20Files/KabuStation_5_17_0_0/KabuStation.exe.manifest
						X-Powered-By	: ASP.NET

ID
	アプリケーション ID		: KabuStation.exe, Version=5.17.0.0, Culture=neutral, PublicKeyToken=84ffc82f90a07440, processorArchitecture=msil, type=win32

エラーの概要
	以下はエラーの概要です。これらのエラーの詳細はログに一覧表示されています。
	* C:\Users\gfd05600\OneDrive\Desktop\kabuステーション.appref-ms| のライセンス認証により例外が発生しました。 次の失敗メッセージが検出されました:
		+ アプリケーションの結合データ形式が無効です。 (HRESULT からの例外:0x800736B2)

コンポーネント ストア トランザクションの失敗の概要
	トランザクション エラーは検出されませんでした。

警告
	この操作中に警告は発生しませんでした。

操作の進行状況
	* [9/12/2022 2:30:37 AM] : C:\Users\gfd05600\OneDrive\Desktop\kabuステーション.appref-ms| のライセンス認証が開始されました。
	* [9/12/2022 2:30:46 AM] : 配置で指定されたように必要な更新チェックを実行しています。
	* [9/12/2022 2:30:47 AM] : 新しい更新を実行しています。
	* [9/12/2022 2:30:47 AM] : アプリケーションのインストールが開始されました。
	* [9/12/2022 2:30:47 AM] : アプリケーション マニフェストの処理は正常に完了しました。
	* [9/12/2022 2:30:47 AM] : 互換性のあるランタイム バージョン 4.0.30319 が見つかりました。
	* [9/12/2022 2:30:47 AM] : 信頼の要求とプラットフォームの検出が完了しました。
	* [9/12/2022 2:31:03 AM] : サブスクリプションの依存のダウンロードは完了しました。
	* [9/12/2022 2:31:03 AM] : ダウンロードされたアプリケーションのコミットが開始されました。

エラーの詳細
	この操作中に次のエラーが検出されました。
	* [9/12/2022 2:31:12 AM] System.Runtime.InteropServices.COMException
		- アプリケーションの結合データ形式が無効です。 (HRESULT からの例外:0x800736B2)
		- ソース:System.Deployment
		- スタック トレース:
			場所 System.Deployment.Internal.Isolation.IEnumSTORE_ASSEMBLY.Next(UInt32 celt, STORE_ASSEMBLY[] rgelt)
			場所 System.Deployment.Internal.Isolation.StoreAssemblyEnumeration.MoveNext()
			場所 System.Deployment.Application.ComponentStore.CollectCrossGroupApplications(Uri codebaseUri, DefinitionIdentity deploymentIdentity, Boolean& identityGroupFound, Boolean& locationGroupFound, String& identityGroupProductName)
			場所 System.Deployment.Application.SubscriptionStore.CommitApplication(SubscriptionState& subState, CommitApplicationParams commitParams)
			場所 System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
			場所 System.Deployment.Application.ApplicationActivator.ConsumeUpdatedDeployment(SubscriptionState& subState, ActivationDescription actDesc)
			場所 System.Deployment.Application.ApplicationActivator.PerformDeploymentUpdate(SubscriptionState& subState, String& errorPageUrl)
			場所 System.Deployment.Application.ApplicationActivator.ProcessOrFollowShortcut(String shortcutFile, String& errorPageUrl, TempFile& deployFile)
			場所 System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			場所 System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
			場所 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			場所 System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			場所 System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)

コンポーネント ストア トランザクションの詳細
	トランザクション情報はありません。

**Comment by gfd05600** [comment]
ちなみに、ノートＰＣでは正常にkabusapiとカブステーションは起動します。

**Comment by cyber-minion** [comment]
事象発生となったシステムの.NETのバージョンを教えていただけますでしょうか。

**Comment by gfd05600** [comment]
［.NET Framework 3.5 用の2022-08累積的な更新プログラム (x64 向け Windows 11 用) 4.8(KB5016594) 9/11/2022に正しくインストールされました］とwindows updateに更新履歴より

**Comment by gfd05600** [comment]
ちなみに、win11はインサイダープレビュー版の11です。バージョンは10
と表示される

**Comment by cyber-minion** [comment]
.NETが有効になっているか、ご確認いただけますでしょうか。

確認方法：
１．コントロールパネル > プログラム > プログラムと機能 > Windowsの機能の有効化または無効化　を開く
２．.NETに関するボックスが選択されていることを確認
![image](https://user-images.githubusercontent.com/69830869/189577782-e94410bb-a527-4fcd-81ef-286bc163c6cd.png)

**Comment by gfd05600** [comment]
ASP.NET4.8にはチエックがありませんでした。

これはチエックを入れてokですか、それとも再起動ですか

**Comment by gfd05600** [comment]
.NET Framework (NET2.0および3.0を含む)のなか2項目チエックがありません
これはそのままですか

**Comment by cyber-minion** [comment]
> ASP.NET4.8にはチエックがありませんでした。

チェックを入れて、OKをクリックしてください。その後、カブステが起動できるかご確認ください。

> .NET Framework (NET2.0および3.0を含む)のなか2項目チエックがありません
> これはそのままですか

Windows Communication Foundationの2項目かと思いますが、そのままで結構です。
![image](https://user-images.githubusercontent.com/69830869/189583231-73e7280a-5251-462c-81eb-af4f12b51f87.png)

**Comment by gfd05600** [comment]
チェックを入れて、OKをクリックしました。カブステが起動できません。

ノートパソコンも見てみました、.NET4.8にはチェックが入れてなくても起動します。

**Comment by cyber-minion** [comment]
お手数ですが、以下の手順で改善するかご確認いただけますでしょうか。

１．Windowsキー+Rを押す
２．%localappdata%\apps　を入力し、OKを押す
３．2.0のフォルダを削除
４．カブステを再インストールする

**Comment by gfd05600** [comment]
ありがとうございました起動しました。

これの原因は2.0のホルダーが障害ですか

**Comment by gfd05600** [comment]
ノートパソコンには2.0が生きていましたがカブステは起動しました。
念のためBIOSのCMOSクリアーしておきました。

**Comment by cyber-minion** [comment]
エラーメッセージからみて、.NET Frameworkの問題と思われますので、2.0フォルダ（.NETに関するテンポラリファイルを保存するもの）の削除をお試しいただきました。

**Comment by gfd05600** [comment]
APIから発注注文、返済注文、銘柄情報、確認して異状ありません。
websocketも先物の16:15プレオープニングセッションの気配値を確認してクローズとします。お世話になりました。
