### ISSUE TITLE
【質問】GET /board/{symbol} のHighPriceとLowPriceの取得時間について

### ISSUE THREAD

**Issue by kitty2117** [kabucom/kabusapi#588]
お世話になります。
板情報の取得について教えてください。

場の終了後（１０分から３０分後くらい、あと、翌日の朝）にranking情報を取得してranking銘柄の高値、安値の情報取得をしています。
で、HighPriceとLowPriceが取得できない株と取得できる株があります。

一日の高安で再ランキングしたいのですが、場終了後どのタイミングでGET /board/したら、HighPriceとLowPriceを取得できるでしょうか？

よろしくお願いします。

**Comment by cyber-minion** [comment]
高/安値が取得できない銘柄ですが、情報取得時に銘柄登録されていますでしょうか。
また、可能な範囲で取得部分のコードを公開いただけると助かります。

**Comment by kitty2117** [comment]
早い返信ありがとうございます。

スクリプトはこんな感じです。
kabuStiationは５０銘柄登録状態でこのスクリプトを呼びます。

'''

def main():
    # tick回数
    t = 5
    t_res = ranking(g.IP_PORT, g.X_API_KEY, t) # ランキング取得のAPIのラッパー関数
    time.sleep(0.5)
    # 売買高上位
    t = 3
    v_res = ranking(g.IP_PORT, g.X_API_KEY, t)
    time.sleep(0.5)
    # 売買代金
    t = 4
    r_res = ranking(g.IP_PORT, g.X_API_KEY, t)
    time.sleep(0.5)

    # 各ランキングのマージ
    #################################
    def purge_underX(priority, ranking, x, y):
        # x:株価　y:売買代金（100万円）
        new_ranking = []
        for r in ranking['Ranking']:
            r['priority'] = priority
            r['OpenPrice'] = 0
            r['HighPrice'] = 0
            r['LowPrice'] = 0
            r['ClosePrice'] = 0
            r['hi-low-ratio'] = 0
            # 株価３００円以下はいれない
            if int(r['CurrentPrice']) < x:
                continue
            # 売買代金が￥5,000,000,000以下は入れない
            if int(r['Turnover']) < y:
                continue
            # 騰落率計算
            i = (float(r['ChangePercentage'])**2)**0.5

            dd = [
                r['priority'],  # 0
                r['No'],  # 1 ランキング
                r['Symbol'],  # 2 銘柄コード
                r['SymbolName'],  # 3 会社名
                r['CurrentPrice'],  # 4 現値
                i,  # 5 騰落率
                r['TradingVolume'],  # 6 売買高
                r['Turnover'],  # 7 売買代金
                r['OpenPrice'],  # 8
                r['HighPrice'],  # 9
                r['LowPrice'],  # 10
                r['ClosePrice'],  # 11
                r['hi-low-ratio']  # 12
            ]
            new_ranking.append(dd)
        return new_ranking
    #################################

    # tick回数
    if True:
        res1 = purge_underX(1, t_res, 200, 3000)
        print('tick回数')
        cnt = 0
        for d in res1:
            cnt = cnt+1
            print(cnt, d)

    # 売買高上位
    if True:
        res2 = purge_underX(2, v_res, 200, 3000)
        print('売買高')
        cnt = 0
        for d in res2:
            cnt = cnt+1
            print(cnt, d)

    # 売買代金
    if True:
        res3 = purge_underX(3, r_res, 200, 3000)
        print('売買代金')
        cnt = 0
        for d in res3:
            cnt = cnt+1
            print(cnt, d)
    # 重複削除
    tmp2 = {}

    for dd in res3:
        tmp2[dd[2]] = dd

    for dd in res2:
        tmp2[dd[2]] = dd

    for dd in res1:
        tmp2[dd[2]] = dd

    if len(tmp2) < 50:
        res2 = purge_underX(2, v_res, 200, 1000)
        for dd in res2:
            tmp2[dd[2]] = dd
    if len(tmp2) < 50:
        res1 = purge_underX(1, t_res, 200, 1000)
        for dd in res1:
            tmp2[dd[2]] = dd

    # リスト銘柄の詳細情報を取得
    cls_Symbols(g.IP_PORT, g.X_API_KEY) # 全銘柄登録削除のラッパー関数
    tmp3 = []
    for key in tmp2.keys():
        tmp3.append(tmp2[key])
    # 並び変え
    tmp2 = sorted(tmp3, key=lambda x: x[1])
    tmp1 = []
    cnt = 0
    for d in tmp2:
        cnt = cnt+1
        if cnt % 50 == 1:
            cls_Symbols(g.IP_PORT, g.X_API_KEY)

        sc = d[2]  # Symbol
        print(f'{cnt}  {sc}  ')
        market = 1  # 東京市場
        info = get_board(g.IP_PORT, g.X_API_KEY, sc, market)
        d[8] = info['CurrentPrice']
        d[9] = info['HighPrice']
        d[10] = info['LowPrice']
        d[11] = info['OpeningPrice']
        if d[9] == None:
            d[12] = 0
        else:
            cc = (float(d[9])-float(d[10]))/float(d[8])*100
            d[12] = '{:.2f}'.format(cc)
        tmp1.append(d)
        # _echo(d,'a','ranking.test')

    print('*****')

    tt = datetime.datetime.today().strftime('%y%m%d')
    fname = f'../{tt}_ranking_.csv'

    def save_ranking(tmp, fname):
        tt = datetime.datetime.today().strftime('%y%m%d-%H%M')
        f = open(f'../{tt}_ranking_.csv', 'w', encoding='utf-8')
        print('種別,順位,証券コード,銘柄名,価格,騰落率,出来高,売買代金,高値,安値,hi-low-ratio,証券コード,銘柄名', file=f)
        for dd in tmp:
            txt = f'{dd[0]},{dd[1]},{dd[2]},{dd[3]},{dd[4]},{int(dd[5])},{int(dd[6])},{dd[7]},{dd[9]},{dd[10]},{dd[12]},{dd[2]},{dd[3]}'
            print(txt)
            print(txt, file=f)
        f.close()

    save_ranking(tmp1, fname)

    return

'''
それとアウトプットです。
９月１５日１５：０5にスクリプトうごかした出力です。
８０+銘柄がリストされています。
よろしくお願いします。

-----------------------------------

種別,順位,証券コード,銘柄名,価格,騰落率,出来高,売買代金,高値,安値,hi-low-ratio,証券コード,銘柄名
1,1,4385,メルカリ,2321.0,2,14357,33138.5286,2365.0,2227.0,5.95,4385,メルカリ
2,1,1357,日経Ｄインバ/ETF(C),361.0,0,40341,14579.2115,None,None,0,1357,日経Ｄインバ/ETF(C)
1,2,9558,ジャパニアス,1908.0,13,5956,12136.6098,2164.0,1882.0,14.78,9558,ジャパニアス
1,3,6619,ＷＳＣＯＰＥ,2979.0,2,16999,51641.4554,3175.0,2955.0,7.39,6619,ＷＳＣＯＰＥ
1,4,6920,レーザーテク,18380.0,1,4823,89569.3925,18790.0,18315.0,2.58,6920,レーザーテク
1,5,9984,ＳＢＧ,5438.0,0,11456,62253.1002,5479.0,5368.0,2.04,9984,ＳＢＧ
1,6,1570,日経レバ/ETF(C),14480.0,0,6299,91136.6803,14545.0,14395.0,1.04,1570,日経レバ/ETF(C)
3,7,9101,郵船,10040.0,0,3307,33226.031,None,None,0,9101,郵船
1,7,4192,スパイダー,809.0,1,8396,7001.5798,876.0,797.0,9.77,4192,スパイダー
1,8,4934,Ｐアンチエイ,3210.0,0,3627,13466.717,None,None,0,4934,Ｐアンチエイ
1,9,8306,三菱ＵＦＪ,723.6,0,33660,24355.0419,725.6,720.6,0.69,8306,三菱ＵＦＪ
2,9,7211,三菱自,615.0,0,15041,9210.0835,618.0,603.0,2.44,7211,三菱自
1,10,9468,カドカワ,2711.0,8,4645,12980.5605,2940.0,2694.0,9.07,9468,カドカワ
3,11,9983,ファストリ,82450.0,0,348,28616.769,82450.0,81600.0,1.03,9983,ファストリ
1,11,5727,邦チタ,2630.0,3,4549,12149.1432,2755.0,2600.0,5.89,5727,邦チタ
1,12,9202,ＡＮＡＨＤ,2806.5,1,5835,16352.5893,2820.0,2768.5,1.84,9202,ＡＮＡＨＤ
1,13,9020,ＪＲ東日本,7681.0,1,3377,26005.2522,7777.0,7525.0,3.28,9020,ＪＲ東日本
1,14,5401,日本製鉄,2253.0,2,10524,23796.7955,2292.5,2239.0,2.37,5401,日本製鉄
3,15,6861,キーエンス,52060.0,0,483,25153.217,52280.0,51720.0,1.08,6861,キーエンス
2,15,9434,ＳＢ,1500.5,0,11137,16692.8893,1503.5,1492.5,0.73,9434,ＳＢ
1,15,4666,パーク２４,2176.0,8,4185,9057.3582,None,None,0,4666,パーク２４
1,16,9201,ＪＡＬ,2700.0,1,9365,25193.6206,2711.0,2658.0,1.96,9201,ＪＡＬ
2,16,9501,東電ＨＤ,488.0,0,10773,5272.7403,494.0,486.0,1.64,9501,東電ＨＤ
1,17,9603,ＨＩＳ,2383.0,3,4700,10951.3159,2383.0,2265.0,4.95,9603,ＨＩＳ
2,18,1459,楽天Ｗベア/ETF(C),1448.0,0,10357,15003.7409,1457.0,1440.0,1.17,1459,楽天Ｗベア/ETF(C)
1,18,4384,ラクスル,2788.0,21,2935,7816.3489,None,None,0,4384,ラクスル
1,19,4165,プレイド,615.0,4,7335,4738.3667,685.0,610.0,12.20,4165,プレイド
1,21,7203,トヨタ,2040.0,0,15098,30794.5578,2046.5,2034.0,0.61,7203,トヨタ
3,21,6273,ＳＭＣ,65620.0,1,288,19014.098,None,None,0,6273,ＳＭＣ
2,21,1360,日経ベア２/ETF(C),881.9,0,8781,7744.6672,886.5,877.2,1.05,1360,日経ベア２/ETF(C)
3,22,9107,川崎汽,8040.0,1,2217,17972.061,8200.0,8040.0,1.99,9107,川崎汽
1,23,6966,三井ハイテク,8200.0,8,3137,26776.097,9220.0,8150.0,13.05,6966,三井ハイテク
3,23,4063,信越化,16185.0,0,1062,17200.4585,16260.0,16165.0,0.59,4063,信越化
2,23,1605,ＩＮＰＥＸ,1536.0,1,8472,13014.036,1549.0,1526.0,1.50,1605,ＩＮＰＥＸ
3,24,8316,三井住友ＦＧ,4309.0,0,3979,17139.8751,4321.0,4288.0,0.77,8316,三井住友ＦＧ
1,24,4689,ＺＨＤ,419.2,1,13294,5585.0627,423.9,416.3,1.81,4689,ＺＨＤ
1,25,7267,ホンダ,3577.0,0,5604,20066.7741,None,None,0,7267,ホンダ
2,25,5020,ＥＮＥＯＳ,510.1,0,7946,4063.6141,514.9,509.5,1.06,5020,ＥＮＥＯＳ
1,26,9519,レノバ,3790.0,1,4070,15473.8795,3905.0,3705.0,5.28,9519,レノバ
3,27,6954,ファナック,21920.0,0,726,15950.7495,22060.0,21875.0,0.84,6954,ファナック
1,27,6098,リクルート,4483.0,0,3422,15362.1162,4550.0,4440.0,2.45,6098,リクルート
1,28,4194,ビジョナル,9380.0,19,2314,21381.047,None,None,0,4194,ビジョナル
3,28,9432,ＮＴＴ,3863.0,0,4103,15834.1156,3872.0,3843.0,0.75,9432,ＮＴＴ
2,28,4755,楽天グループ,651.0,0,7311,4767.0239,661.0,645.0,2.46,4755,楽天グループ
1,29,7974,任天堂,62400.0,1,1413,88681.423,63420.0,61370.0,3.29,7974,任天堂
2,29,9104,商船三井,3410.0,0,7000,23829.1525,3425.0,3365.0,1.76,9104,商船三井
2,30,8604,野村,505.8,0,6758,3413.4916,None,None,0,8604,野村
1,30,2413,エムスリー,4532.0,0,2081,9437.2333,4589.0,4469.0,2.65,2413,エムスリー
1,31,7201,日産自,546.4,1,11406,6217.364,547.9,539.0,1.63,7201,日産自
2,31,6752,パナＨＤ,1130.0,1,6363,7163.8171,None,None,0,6752,パナＨＤ
1,32,9021,ＪＲ西日本,5747.0,1,2235,12878.0506,5821.0,5627.0,3.38,9021,ＪＲ西日本
3,33,4661,ＯＬＣ,20420.0,0,724,14833.168,None,None,0,4661,ＯＬＣ
2,33,6723,ルネサス,1321.0,0,6056,8024.1646,None,None,0,6723,ルネサス
1,34,4449,ギフティ,2502.0,2,1921,4728.3148,None,None,0,4449,ギフティ
3,35,6367,ダイキン,24240.0,0,567,13794.1905,24570.0,24230.0,1.40,6367,ダイキン
1,35,7011,三菱重,5228.0,0,2150,11212.5809,5244.0,5151.0,1.78,7011,三菱重
1,36,6594,日電産,9236.0,1,1634,15121.5868,9305.0,9160.0,1.57,6594,日電産
1,37,8035,東エレク,42760.0,1,1366,58263.41,None,None,0,8035,東エレク
3,37,8766,東京海上,7767.0,1,1685,13062.1883,None,None,0,8766,東京海上
1,38,8308,りそなＨＤ,532.4,0,8534,4538.3607,534.2,527.3,1.30,8308,りそなＨＤ
2,38,3660,アイスタイル,595.0,1,5464,3259.9085,None,None,0,3660,アイスタイル
2,39,9143,ＳＧＨＤ,2151.0,2,5459,11812.5365,2184.0,2146.0,1.77,9143,ＳＧＨＤ
2,40,5486,日立金,2162.0,3,5250,11320.4911,2164.0,2142.0,1.02,5486,日立金
3,41,6501,日立,6828.0,0,1852,12650.1088,6860.0,6801.0,0.86,6501,日立
2,41,5406,神戸鋼,640.0,1,4984,3192.864,None,None,0,5406,神戸鋼
1,41,8801,三井不,2950.0,1,3166,9291.3674,None,None,0,8801,三井不
3,42,7741,ＨＯＹＡ,14780.0,0,835,12334.994,14865.0,14640.0,1.52,7741,ＨＯＹＡ
2,42,8411,みずほＦＧ,1641.5,0,4942,8106.377,None,None,0,8411,みずほＦＧ
1,42,4395,アクリート,3045.0,12,1278,3833.8621,None,None,0,4395,アクリート
3,43,9433,ＫＤＤＩ,4324.0,0,2845,12277.4257,4332.0,4291.0,0.95,9433,ＫＤＤＩ
1,43,4911,資生堂,5152.0,2,2110,10814.4727,5156.0,5034.0,2.37,4911,資生堂
1,44,6178,日本郵政,985.0,0,9490,9330.6437,None,None,0,6178,日本郵政
1,45,6301,コマツ,2836.0,0,3669,10417.2102,None,None,0,6301,コマツ
3,46,9022,ＪＲ東海,17035.0,0,709,12115.6615,17210.0,16790.0,2.47,9022,ＪＲ東海
1,46,8591,オリックス,2263.0,1,3517,7955.2529,None,None,0,8591,オリックス
1,47,6758,ソニーＧ,10470.0,0,3046,31888.25,10550.0,10365.0,1.77,6758,ソニーＧ
3,48,6857,アドテスト,7610.0,1,1521,11638.111,7730.0,7590.0,1.84,6857,アドテスト
2,48,4188,三菱ケミＧ,718.8,0,4538,3257.7643,720.2,716.2,0.56,4188,三菱ケミＧ
3,49,4502,武田,3876.0,0,2997,11608.2474,3879.0,3860.0,0.49,4502,武田
3,50,8031,三井物,3283.0,0,3463,11342.1162,None,None,0,8031,三井物
1,50,3923,ラクス,1564.0,1,2461,3862.2213,None,None,0,3923,ラクス

**Comment by cyber-minion** [comment]
高/安値が取得されていない銘柄は、API登録銘柄リストに入っていますでしょうか。

**Comment by kitty2117** [comment]
スクリプトの中ほどに
# リスト銘柄の詳細情報を取得
という部分があるのですが、そこで全登録銘柄を削除しています。cls_symbols()という関数が全銘柄登録削除のラッパー関数です。その後も５０銘柄の情報取得したら全銘柄を削除しています

高安が取得できた銘柄も高安が取得できなかった銘柄も登録銘柄にははいっていません

**Comment by cyber-minion** [comment]
高安値が取得できていない銘柄に関しては、カブステAPIログをご確認いただき、高値、安値が取得されているかご確認いただけますでしょうか。

**Comment by cyber-minion** [comment]
価格情報取得の前には銘柄登録してから、再度ご確認いただけますでしょうか。

**Comment by kitty2117** [comment]
試してみました
詳細情報取得のところでその都度、銘柄登録をして、情報取得、銘柄登録削除の流れにしてみました
この時、time.sleep(0.2)をコメントアウトすると、かなり低頻度ですがNoneでました。
カブコムシステムの銘柄登録の作業負荷がかなり高いんですね。。。
しばらく、time.sleep(0.2)で動かしてみます。
また、なんかNoneでたら、連絡します。

ありがとうございました

スクリプト変更部分
'''
    # リスト銘柄の詳細情報を取得
    cls_Symbols(g.IP_PORT, g.X_API_KEY)
    tmp3 = []
    for key in tmp2.keys():
        tmp3.append(tmp2[key])
    # 並び変え
    tmp2 = sorted(tmp3, key=lambda x: x[1])
    tmp1 = []
    cnt = 0
    for d in tmp2:
        cnt = cnt+1
        sc=d[2]
        set_Symbol(g.IP_PORT,g.X_API_KEY,sc)
        time.sleep(0.2) # これをコメントアウトすると低頻度でNone
        print(f'{cnt}  {sc}  ')
        market = 1  # 東京市場
        info = get_board(g.IP_PORT, g.X_API_KEY, sc, market)
        unregister_symbol(g.IP_PORT,g.X_API_KEY,sc)
        time.sleep(0.2) # ここはよくわからんけど、コメントアウトするとまずい？
        d[8] = info['CurrentPrice']
        d[9] = info['HighPrice']
        d[10] = info['LowPrice']
        d[11] = info['OpeningPrice']
        if d[9] == None:
            d[12] = 0
        else:
            cc = (float(d[9])-float(d[10]))/float(d[8])*100
            d[12] = '{:.2f}'.format(cc)
        tmp1.append(d)


'''
