### ISSUE TITLE
【質問】返済建玉ID

### ISSUE THREAD

**Issue by tksun123890** [kabucom/kabusapi#590]
返済建玉IDはどこに記載されているIDでしょうか？

**Comment by yasuyuki-nakazawa** [comment]
残高照会(positions)に建玉IDがございますので、そちらを指定すれば処理可能です
ExecutionIDがあり、データとしてはEで始まる番号が対象のモノとなりますので、ご確認くださいませ

**Comment by tksun123890** [comment]
kabuステーションの残高照会画面にも、WEBの残高照会画面にも表示されていないようですが、
どの残高照会に表示されているのでしょうか？

**Comment by yasuyuki-nakazawa** [comment]
建玉IDはカブステーション上ではなく、カブステAPIのPosition()の結果で取得することが可能です

**Comment by cyber-minion** [comment]
解決済みのようですので、クローズさせていただきます。
