### ISSUE TITLE
【質問】価格データの更新に関して

### ISSUE THREAD

**Issue by MR1derland** [kabucom/kabusapi#593]
kabuステーションAPI内の価格データの更新は、ティックごとに更新されるのかorローソク足（バー）ごとの更新なのか、教えて頂きたいです。

**Comment by cyber-minion** [comment]
PUSH APIのデータ更新頻度に関するご質問でしょうか？

**Comment by MR1derland** [comment]
kabuステーションAPIの仕様をまだしっかりと把握できていないのですが、PUSH APIのデータ更新頻度に関する質問とご理解いただいて問題ないかと思います。

**Comment by cyber-minion** [comment]
PUSH配信は、値が更新される際に配信される仕様となっております（場間（昼休み）、引け後での配信はございません）。
配信されるデータに関しましては、こちらのページにてご確認いただければと思います。
https://kabucom.github.io/kabusapi/ptal/push.html

**Comment by MR1derland** [comment]
承知致しました。
ご回答ありがとうございます。

**Comment by cyber-minion** [comment]
解決済みのようですので、クローズさせていただきます。
