### ISSUE TITLE
【質問】日経平均とTOPIXの指数の情報をWEB SOCKETで取得したい

### ISSUE THREAD

**Issue by xyz2900** [kabucom/kabusapi#594]
日経平均とTOPIXの指数の情報をWEB SOCKETで取得したいのですが
登録シンボルがわかりません。
どこを見れば良いでしょうか？

**Comment by cyber-minion** [comment]
銘柄コードは以下にて指定いただければと思います。※市場は「1」と指定ください
日経平均株価：101
TOPIX：151

当該情報の提供に関しましては今後リファレンス等の拡充を検討していきたいと思いますが、現状はいったんkabuステーションにてご確認いただければと思います。
![image](https://user-images.githubusercontent.com/69830869/195261200-ed6b1d7d-018d-4651-b9be-799824a0a7a8.png)

**Comment by cyber-minion** [comment]
解決済みのようですので、クローズさせていただきます。
