### ISSUE TITLE
【質問】PythonでのAPIトークン取得ができない

### ISSUE THREAD

**Issue by monkeydarts1** [kabucom/kabusapi#595]
サンプルプログラムの kabusapi_token.py　を実行したところ、トークンが取得できませんでした。
実行環境はGoogle Colaboratoryとローカルのコマンドプロンプトで、
Colaboratory　では　<urlopen error [Errno 99] Cannot assign requested address>
コマンドプロンプトでは　<urlopen error [WinError 10061] 対象のコンピューターによって拒否されたため、接続できませんでした。>
と出ています。

以上よろしくお願いします。

**Comment by yasuyuki-nakazawa** [comment]
APIへのリクエスト自体はローカルから行われるということでよろしいでしょうか
ローカルと同一のIPからのリクエスト以外は拒否される仕組みとなっております。

**Comment by monkeydarts1** [comment]
はい、コマンドプロンプトはローカルのＰＣから実行しているので、同一のＩＰからリクエストをしています。

**Comment by yasuyuki-nakazawa** [comment]
kabuステーション側のログまたは、API側のログに何か出ていないでしょうか？

**Comment by monkeydarts1** [comment]
解決しました。

kabuステーションAPIの設定をkabuステーション側でし忘れていたようです。
ありがとうございました。
