### ISSUE TITLE
【不具合】信用ポジションがないときにもwallet/margin/{symbol}の'MarginAccountWallet'の値が０になる

### ISSUE THREAD

**Issue by kitty2117** [kabucom/kabusapi#597]
■[必須] 不具合事象(概要)
信用ポジションがない時にwallet/margin/{symbol}で信用余力を求めるとMarginAccountWalletの値が０になる

■[必須] 本来想定されるアクションと事象
信用ポジションがない時にwallet/margin/{symbol}で信用余力を求めるとMarginAccountWalletの値が正常に返される

■[必須] 不備発生時刻（常時の場合は、常時で記載ください)
寄り付き後、数分間は正常にMarginAccountWalletが取得できるが、数分経過するとMarginAccountWalletが０しか返さなくなる
毎秒２回程度のwallet/margin/{symbol}を呼び出している

■[任意] お使いの環境(OS、Excelのバージョン等)、サンプル(Macro、アドインのバージョン）
win10,python10
スクリプトは、ほぼサンプルそのまんまです。
'''

def l0_wallet_margin(ipport, x_api_key, symbol):
    # 銘柄の信用取引余力の取得
    url = f'http:{ipport}/kabusapi/wallet/margin/{symbol}@1'
    req = urllib.request.Request(url, method='GET')
    req.add_header('Content-Type', 'application/json')
    req.add_header('X-API-KEY', x_api_key)
    #
    msg = {}

    try:
        with urllib.request.urlopen(req) as res:
            #print(res.status, res.reason)
            # for header in res.getheaders():
            #    print(header)
            tt = datetime.datetime.now().strftime('%H%M%S.%f')
            print(f'{tt} GET /wallet/margin/{symbol}')
            print()
            msg = json.loads(res.read())

    except urllib.error.HTTPError as e:
        print(e)
        msg = json.loads(e.read())
    except Exception as e:
        print(e)
        msg = json.loads(e.read())

    return msg
'''

■[任意] 不備部分のログ
１０月２１日　PLAIN_20221021_09.logがら抜粋
９時１８分から０しか返さなくなる
’’’
09:14:03.9522,I,9592,0009 【WalletMargin】(1570@1)
09:14:03.9542,I,9592,0009 【WalletMargin】({"MarginAccountWallet":817960.0,"DepositkeepRate":155.8,"ConsignmentDepositRate":30.0,"CashOfConsignmentDepositRate":0.0})
09:17:57.4997,I,9592,0009 【WalletMargin】(9227@1)
09:17:57.5007,I,9592,0009 【WalletMargin】({"MarginAccountWallet":530020.0,"DepositkeepRate":62.9,"ConsignmentDepositRate":30.0,"CashOfConsignmentDepositRate":0.0})
09:17:57.8258,I,9592,0009 【WalletMargin】(1570@1)
09:17:57.8268,I,9592,0009 【WalletMargin】({"MarginAccountWallet":0.0,"DepositkeepRate":0.0,"ConsignmentDepositRate":30.0,"CashOfConsignmentDepositRate":0.0})
09:17:57.9359,I,9592,0009 【WalletMargin】(4165@1)
09:17:57.9369,I,9592,0009 【WalletMargin】({"MarginAccountWallet":530020.0,"DepositkeepRate":62.9,"ConsignmentDepositRate":30.0,"CashOfConsignmentDepositRate":0.0})
09:17:58.3271,I,9592,0009 【WalletMargin】(4344@1)
09:17:58.3271,I,9592,0009 【WalletMargin】({"MarginAccountWallet":0.0,"DepositkeepRate":66.7,"ConsignmentDepositRate":30.0,"CashOfConsignmentDepositRate":0.0})
09:17:58.4364,I,9592,0009 【WalletMargin】(8303@1)
09:17:58.4374,I,9592,0009 【WalletMargin】({"MarginAccountWallet":528946.0,"DepositkeepRate":62.8,"ConsignmentDepositRate":30.0,"CashOfConsignmentDepositRate":0.0})
09:17:58.8716,I,9592,0009 【WalletMargin】(1570@1)
09:17:58.8716,I,9592,0009 【WalletMargin】({"MarginAccountWallet":0.0,"DepositkeepRate":0.0,"ConsignmentDepositRate":30.0,"CashOfConsignmentDepositRate":0.0})
09:17:58.9799,I,9592,0009 【WalletMargin】(6526@1)
09:17:58.9809,I,9592,0009 【WalletMargin】({"MarginAccountWallet":368950.0,"DepositkeepRate":47.1,"ConsignmentDepositRate":30.0,"CashOfConsignmentDepositRate":0.0})
09:18:02.8289,I,9592,0009 【WalletMargin】(6526@1)
09:18:02.8289,I,9592,0009 【WalletMargin】({"MarginAccountWallet":0.0,"DepositkeepRate":0.0,"ConsignmentDepositRate":30.0,"CashOfConsignmentDepositRate":0.0})
09:18:02.9401,I,9592,0009 【WalletMargin】(1570@1)
09:18:02.9521,I,9592,0009 【WalletMargin】({"MarginAccountWallet":0.0,"DepositkeepRate":0.0,"ConsignmentDepositRate":30.0,"CashOfConsignmentDepositRate":0.0})
09:18:04.3052,I,9592,0009 【WalletMargin】(1570@1)
09:18:04.3062,I,9592,0009 【WalletMargin】({"MarginAccountWallet":0.0,"DepositkeepRate":0.0,"ConsignmentDepositRate":30.0,"CashOfConsignmentDepositRate":0.0})
09:18:05.3514,I,9592,0009 【WalletMargin】(6526@1)
09:18:05.3524,I,9592,0009 【WalletMargin】({"MarginAccountWallet":0.0,"DepositkeepRate":0.0,"ConsignmentDepositRate":30.0,"CashOfConsignmentDepositRate":0.0})
09:18:06.0768,I,9592,0009 【WalletMargin】(4344@1)
09:18:06.0778,I,9592,0009 【WalletMargin】({"MarginAccountWallet":0.0,"DepositkeepRate":0.0,"ConsignmentDepositRate":30.0,"CashOfConsignmentDepositRate":0.0})
09:18:07.7336,I,9592,0009 【WalletMargin】(1570@1)
09:18:07.7346,I,9592,0009 【WalletMargin】({"MarginAccountWallet":0.0,"DepositkeepRate":0.0,"ConsignmentDepositRate":30.0,"CashOfConsignmentDepositRate":0.0})
09:18:08.1490,I,9592,0009 【WalletMargin】(1570@1)
09:18:08.1490,I,9592,0009 【WalletMargin】({"MarginAccountWallet":0.0,"DepositkeepRate":0.0,"ConsignmentDepositRate":30.0,"CashOfConsignmentDepositRate":0.0})
09:18:13.8440,I,9592,0009 【WalletMargin】(1570@1)
09:18:13.8450,I,9592,0009 【WalletMargin】({"MarginAccountWallet":0.0,"DepositkeepRate":0.0,"ConsignmentDepositRate":30.0,"CashOfConsignmentDepositRate":0.0})
09:18:15.5036,I,9592,0009 【WalletMargin】(1570@1)
09:18:15.5046,I,9592,0009 【WalletMargin】({"MarginAccountWallet":0.0,"DepositkeepRate":0.0,"ConsignmentDepositRate":30.0,"CashOfConsignmentDepositRate":0.0})
09:18:16.2338,I,9592,0009 【WalletMargin】(1570@1)
09:18:16.2348,I,9592,0009 【WalletMargin】({"MarginAccountWallet":0.0,"DepositkeepRate":0.0,"ConsignmentDepositRate":30.0,"CashOfConsignmentDepositRate":0.0})

’’’

PLAIN_20221020_09.log
９時５０分ころから0しか返ってこなくなる。
’’’
09:51:03.3887,I,13564,0007 【WalletMargin】(6048@1)
09:51:03.3887,I,13564,0007 【WalletMargin】({"MarginAccountWallet":29360.0,"DepositkeepRate":71.9,"ConsignmentDepositRate":50.0,"CashOfConsignmentDepositRate":20.0})
09:51:03.8118,I,13564,0007 【WalletMargin】(6048@1)
09:51:03.8118,I,13564,0007 【WalletMargin】({"MarginAccountWallet":29360.0,"DepositkeepRate":71.9,"ConsignmentDepositRate":50.0,"CashOfConsignmentDepositRate":20.0})
09:51:06.7240,I,13564,0007 【WalletMargin】(4344@1)
09:51:06.7390,I,13564,0007 【WalletMargin】({"MarginAccountWallet":587246.0,"DepositkeepRate":71.9,"ConsignmentDepositRate":30.0,"CashOfConsignmentDepositRate":0.0})
09:51:07.7811,I,13564,0007 【WalletMargin】(6048@1)
09:51:07.7821,I,13564,0007 【WalletMargin】({"MarginAccountWallet":0.0,"DepositkeepRate":0.0,"ConsignmentDepositRate":50.0,"CashOfConsignmentDepositRate":20.0})
09:51:11.6144,I,13564,0007 【WalletMargin】(6048@1)
09:51:11.6154,I,13564,0007 【WalletMargin】({"MarginAccountWallet":0.0,"DepositkeepRate":0.0,"ConsignmentDepositRate":50.0,"CashOfConsignmentDepositRate":20.0})
09:51:12.3453,I,13564,0007 【WalletMargin】(6048@1)
09:51:12.3453,I,13564,0007 【WalletMargin】({"MarginAccountWallet":0.0,"DepositkeepRate":0.0,"ConsignmentDepositRate":50.0,"CashOfConsignmentDepositRate":20.0})
09:51:12.7673,I,13564,0007 【WalletMargin】(6048@1)
09:51:12.7673,I,13564,0007 【WalletMargin】({"MarginAccountWallet":0.0,"DepositkeepRate":0.0,"ConsignmentDepositRate":50.0,"CashOfConsignmentDepositRate":20.0})
09:51:15.3634,I,13564,0007 【WalletMargin】(6048@1)
09:51:15.3644,I,13564,0007 【WalletMargin】({"MarginAccountWallet":0.0,"DepositkeepRate":0.0,"ConsignmentDepositRate":50.0,"CashOfConsignmentDepositRate":20.0})
09:51:16.4021,I,13564,0007 【WalletMargin】(6048@1)
09:51:16.4041,I,13564,0007 【WalletMargin】({"MarginAccountWallet":0.0,"DepositkeepRate":0.0,"ConsignmentDepositRate":50.0,"CashOfConsignmentDepositRate":20.0})
09:51:18.6903,I,13564,0007 【WalletMargin】(6048@1)
09:51:18.6903,I,13564,0007 【WalletMargin】({"MarginAccountWallet":0.0,"DepositkeepRate":0.0,"ConsignmentDepositRate":50.0,"CashOfConsignmentDepositRate":20.0})
09:51:19.4169,I,13564,0007 【WalletMargin】(6048@1)
09:51:19.4179,I,13564,0007 【WalletMargin】({"MarginAccountWallet":0.0,"DepositkeepRate":0.0,"ConsignmentDepositRate":50.0,"CashOfConsignmentDepositRate":20.0})

’’’

**Comment by cyber-minion** [comment]
９時１８分から、また９時５０分から0しか返ってこなくなるとありますが、事象はそれぞれ（時間的に）どれくらい続いていたのでしょうか？

**Comment by kitty2117** [comment]
先ほど、保証金を入れてくれとのメールが来ました。なんか数千円必要なみたいです。

時系列はこんな感じです。
[1]１０月２０日（木）の０９：５１分からゼロになっていて、その後１０：４３分までゼロ、スクリプトを落とす
[2]１０月２１日（金）の０９：１８分までは取引ができていて、その後wallet/marginがゼロしか返さなくなる、すぐにスクリプトを落とす
[3]１０月２４日（月）の０９：０１分にアクセスして、wallet/marginをするがゼロしか返さない、すぐにスクリプトを落とす
[4]１０月２４日（月）１７：００くらい、保証金不足のメールがくる

保証金で考えるとこういう事でしょうか？
[1]１０月２１日の時点で保証金不足が発生して、取引制限、ユーザースクリプトを落とす
　引け後、値洗いが実行されて保証金不足でない事になる
[2]１０月２４日の時点では保証金不足が解消しており、また、取引ができるようになるが、０９：１８にまた保証金不足になり、wallet/marginがゼロしか返さなくなる
　引け後、値洗いが実行されて、保証金不足と判定される
[3]１０月２４日前場の時点で保証金不足が発生しており、最初から取引ができない。
[4]で保証金不足のメールくる

保証金不足で取引できるかできないかグレーな時には、send_orderするとパラメーター不正になる？

**Comment by cyber-minion** [comment]
追加の確認で恐れ入りますが、下記２点ご確認いただけますでしょうか。
・可能額APIが0を返すときにカブステ画面でも可能額は0になっていますでしょうか
・毎秒2回程度、APIを実行しているようですが、毎秒1回とした場合に可能額が取得できますでしょうか

**Comment by kitty2117** [comment]
株ステ画面についてですが、可能額の見方がわかりません。
wallet/marginの実行回数ですが、スクリプトの作りが毎秒１回とかそういう作りになっていません。テスト用にスクリプト起さないといけないです。。。

PLAIN_20221020_09.logからの抜粋ですが
09:07:51～09:07:53で毎秒１回とれてます。
09:07:28で秒２回アクセスしてますが、情報は取れてます。
ほかに09:07:39秒でも秒２回情報はとれています。その後９：５１分からゼロになります。
'''
09:07:28.0180,I,13564,0007 【WalletMargin】(9115@1)
09:07:28.0190,I,13564,0007 【WalletMargin】({"MarginAccountWallet":114223.0,"DepositkeepRate":33.7,"ConsignmentDepositRate":30.0,"CashOfConsignmentDepositRate":0.0})
09:07:28.4430,I,13564,0007 【WalletMargin】(4176@1)
09:07:28.4430,I,13564,0007 【WalletMargin】({"MarginAccountWallet":114223.0,"DepositkeepRate":33.7,"ConsignmentDepositRate":30.0,"CashOfConsignmentDepositRate":0.0})
09:07:30.1211,I,13564,0007 【WalletMargin】(4176@1)
09:07:30.1221,I,13564,0007 【WalletMargin】({"MarginAccountWallet":114223.0,"DepositkeepRate":33.7,"ConsignmentDepositRate":30.0,"CashOfConsignmentDepositRate":0.0})
09:07:33.3464,I,13564,0007 【WalletMargin】(9115@1)
09:07:33.3474,I,13564,0007 【WalletMargin】({"MarginAccountWallet":114223.0,"DepositkeepRate":33.7,"ConsignmentDepositRate":30.0,"CashOfConsignmentDepositRate":0.0})
09:07:35.3176,I,13564,0007 【WalletMargin】(9115@1)
09:07:35.3586,I,13564,0007 【WalletMargin】({"MarginAccountWallet":114223.0,"DepositkeepRate":33.7,"ConsignmentDepositRate":30.0,"CashOfConsignmentDepositRate":0.0})
09:07:37.3467,I,13564,0007 【WalletMargin】(9115@1)
09:07:37.3467,I,13564,0007 【WalletMargin】({"MarginAccountWallet":114223.0,"DepositkeepRate":33.7,"ConsignmentDepositRate":30.0,"CashOfConsignmentDepositRate":0.0})
09:07:39.0159,I,13564,0007 【WalletMargin】(9115@1)
09:07:39.0159,I,13564,0007 【WalletMargin】({"MarginAccountWallet":114223.0,"DepositkeepRate":33.7,"ConsignmentDepositRate":30.0,"CashOfConsignmentDepositRate":0.0})
09:07:39.7489,I,13564,0007 【WalletMargin】(9115@1)
09:07:39.7489,I,13564,0007 【WalletMargin】({"MarginAccountWallet":114223.0,"DepositkeepRate":33.7,"ConsignmentDepositRate":30.0,"CashOfConsignmentDepositRate":0.0})
09:07:42.0371,I,13564,0007 【WalletMargin】(4176@1)
09:07:42.0371,I,13564,0007 【WalletMargin】({"MarginAccountWallet":114223.0,"DepositkeepRate":33.7,"ConsignmentDepositRate":30.0,"CashOfConsignmentDepositRate":0.0})
09:07:43.7032,I,13564,0007 【WalletMargin】(9115@1)
09:07:43.7172,I,13564,0007 【WalletMargin】({"MarginAccountWallet":114223.0,"DepositkeepRate":33.7,"ConsignmentDepositRate":30.0,"CashOfConsignmentDepositRate":0.0})
09:07:47.5706,I,13564,0007 【WalletMargin】(9115@1)
09:07:47.5706,I,13564,0007 【WalletMargin】({"MarginAccountWallet":114223.0,"DepositkeepRate":33.7,"ConsignmentDepositRate":30.0,"CashOfConsignmentDepositRate":0.0})
09:07:49.8551,I,13564,0007 【WalletMargin】(9115@1)
09:07:49.8551,I,13564,0007 【WalletMargin】({"MarginAccountWallet":114223.0,"DepositkeepRate":33.7,"ConsignmentDepositRate":30.0,"CashOfConsignmentDepositRate":0.0})
09:07:51.2143,I,13564,0007 【WalletMargin】(9115@1)
09:07:51.2293,I,13564,0007 【WalletMargin】({"MarginAccountWallet":114223.0,"DepositkeepRate":33.7,"ConsignmentDepositRate":30.0,"CashOfConsignmentDepositRate":0.0})
09:07:52.8874,I,13564,0007 【WalletMargin】(4176@1)
09:07:52.8884,I,13564,0007 【WalletMargin】({"MarginAccountWallet":114223.0,"DepositkeepRate":33.7,"ConsignmentDepositRate":30.0,"CashOfConsignmentDepositRate":0.0})
09:07:53.6195,I,13564,0007 【WalletMargin】(9115@1)
09:07:53.6545,I,13564,0007 【WalletMargin】({"MarginAccountWallet":114223.0,"DepositkeepRate":33.7,"ConsignmentDepositRate":30.0,"CashOfConsignmentDepositRate":0.0})

'''
PLAIN_20221020_10.logを見ると再アクセスまで何秒か空き時間があってもゼロが帰ってきています。
'''
10:00:07.0960,I,13564,0007 【WalletMargin】(4344@1)
10:00:07.0960,I,13564,0007 【WalletMargin】({"MarginAccountWallet":0.0,"DepositkeepRate":0.0,"ConsignmentDepositRate":30.0,"CashOfConsignmentDepositRate":0.0})
10:00:08.1341,I,13564,0007 【WalletMargin】(4344@1)
10:00:08.1351,I,13564,0007 【WalletMargin】({"MarginAccountWallet":0.0,"DepositkeepRate":0.0,"ConsignmentDepositRate":30.0,"CashOfConsignmentDepositRate":0.0})
10:00:10.4233,I,13564,0007 【WalletMargin】(4344@1)
10:00:10.4233,I,13564,0007 【WalletMargin】({"MarginAccountWallet":0.0,"DepositkeepRate":0.0,"ConsignmentDepositRate":30.0,"CashOfConsignmentDepositRate":0.0})
10:00:15.8162,I,13564,0007 【WalletMargin】(4344@1)
10:00:15.8172,I,13564,0007 【WalletMargin】({"MarginAccountWallet":0.0,"DepositkeepRate":0.0,"ConsignmentDepositRate":30.0,"CashOfConsignmentDepositRate":0.0})

'''

**Comment by cyber-minion** [comment]
>株ステ画面についてですが、可能額の見方がわかりません。

画面にはよりますが、発注ダイアログですと、以下のように確認できます
![image](https://user-images.githubusercontent.com/69830869/197513718-65fe58ee-1a4f-4f0f-b33d-1105a041a693.png)

**Comment by kitty2117** [comment]
昨夜、保証金の不足を入金したのですが、それで、信用新規建玉可能額がゼロでなくなりました。
おそらくそれで取引制限がかかっていたのかな
２０日に制限がかかって、２１日に制限が復活したのが謎だけど、取り合えず動きました。

ありがとうございました
