### ISSUE TITLE
【不具合】SendOrderでパラメーター不正がでるが、パラメータは正常になっている　#597も参照

### ISSUE THREAD

**Issue by kitty2117** [kabucom/kabusapi#598]
■[必須] 不具合事象(概要)
SendOrderで注文をするとパラメーター不正とでるが、パラメーターを確認してもおかしいところが見つからない

■[必須] 本来想定されるアクションと事象
SendOrderのパラメータで売買で実行される

■[必須] 不備発生時刻（常時の場合は、常時で記載ください)
wallet/margin/{symbol}でMarginAccountWalletが0しか返さなくなるタイミングで発生している様子

■[任意] お使いの環境(OS、Excelのバージョン等)、サンプル(Macro、アドインのバージョン）
win10,python10

■[任意] 不備部分のログ
PLAIN_20221021_09.logから
#597で報告のwallet/margin/{symbol}でMarginAccountWalletが0しか返さなくなるタイミングで発生している様子

'''
09:17:57.4997,I,9592,0009 【WalletMargin】(9227@1)
09:17:57.5007,I,9592,0009 【WalletMargin】({"MarginAccountWallet":530020.0,"DepositkeepRate":62.9,"ConsignmentDepositRate":30.0,"CashOfConsignmentDepositRate":0.0})
09:17:57.6072,I,9592,0009 【Board】(9227@1)
09:17:57.6091,I,9592,0009 【Board】({"OverSellQty":421200.0,"UnderBuyQty":381500.0,"TotalMarketValue":16886089000.0,"MarketOrderSellQty":0.0,"MarketOrderBuyQty":0.0,"BidTime":"2022-10-21T09:17:57+09:00","AskTime":"2022-10-21T09:17:57+09:00","Exchange":1,"ExchangeName":"東証グ","TradingVolume":530800.0,"TradingVolumeTime":"2022-10-21T09:17:52+09:00","VWAP":1107.6980,"TradingValue":587966100.0,"BidQty":3700.0,"BidPrice":1112.0,"BidSign":"0101","Sell1":{"Price":1112.0,"Qty":3700.0,"Sign":"0101","Time":"2022-10-21T09:17:57+09:00"},"Sell2":{"Price":1113.0,"Qty":1900.0},"Sell3":{"Price":1114.0,"Qty":2000.0},"Sell4":{"Price":1115.0,"Qty":3300.0},"Sell5":{"Price":1116.0,"Qty":1300.0},"Sell6":{"Price":1117.0,"Qty":2300.0},"Sell7":{"Price":1118.0,"Qty":5100.0},"Sell8":{"Price":1119.0,"Qty":2400.0},"Sell9":{"Price":1120.0,"Qty":4400.0},"Sell10":{"Price":1121.0,"Qty":33400.0},"AskQty":1700.0,"AskPrice":1110.0,"AskSign":"0101","Buy1":{"Price":1110.0,"Qty":1700.0,"Sign":"0101","Time":"2022-10-21T09:17:57+09:00"},"Buy2":{"Price":1109.0,"Qty":800.0},"Buy3":{"Price":1108.0,"Qty":1000.0},"Buy4":{"Price":1107.0,"Qty":2000.0},"Buy5":{"Price":1106.0,"Qty":1400.0},"Buy6":{"Price":1105.0,"Qty":3100.0},"Buy7":{"Price":1104.0,"Qty":1500.0},"Buy8":{"Price":1103.0,"Qty":2200.0},"Buy9":{"Price":1102.0,"Qty":1400.0},"Buy10":{"Price":1101.0,"Qty":3400.0},"Symbol":"9227","SymbolName":"マイクロ波化学","CurrentPrice":1111.0,"CurrentPriceTime":"2022-10-21T09:17:52+09:00","CurrentPriceChangeStatus":"0056","CurrentPriceStatus":1,"CalcPrice":1111.0,"PreviousClose":1141.00000,"PreviousCloseTime":"2022-10-20T00:00:00+09:00","ChangePreviousClose":-30.00000,"ChangePreviousClosePer":-2.63,"OpeningPrice":1120.0,"OpeningPriceTime":"2022-10-21T09:00:00+09:00","HighPrice":1126.0,"HighPriceTime":"2022-10-21T09:00:00+09:00","LowPrice":1094.0,"LowPriceTime":"2022-10-21T09:09:11+09:00","SecurityType":1})
09:17:57.7162,I,9592,0009 【SendOrder】({"Password":"****************","Symbol":"9227","Exchange":1,"SecurityType":1,"Side":1,"CashMargin":2,"MarginTradeType":1,"DelivType":0,"AccountType":4,"Qty":300.0,"ClosePositionOrder":1,"FrontOrderType":20,"Price":1101.0,"ExpireDay":0})
09:17:57.7162,I,9592,0009 【SendOrder】({"Code":4002013,"Message":"パラメータ不正：MarginTradeType - 詳細はkabuSログファイルを確認してください"})

'''

■ e.t.c
今まではテクニカル分析するのは数秒に１回にしていたが、不具合はでていない。
pushから生成した疑似ティック情報を受け取る度にテクニカル分析して余力問い合わせして発注するように変えたら
発生するようになりました。

**Comment by kitty2117** [comment]
ログ情報追加
１０月２４日の前場　PLAIN_20221024_09.log
wallet/margin/{symbol}が最初から0になっています。
'''
09:00:57.1976,I,2176,0017 【WalletMargin】(5834@1)
09:00:57.2946,I,2176,0017 【WalletMargin】({"MarginAccountWallet":0.0,"DepositkeepRate":0.0,"ConsignmentDepositRate":30.0,"CashOfConsignmentDepositRate":0.0})
09:01:37.9359,I,2176,0017 【WalletMargin】(5834@1)
09:01:37.9359,I,2176,0017 【WalletMargin】({"MarginAccountWallet":0.0,"DepositkeepRate":0.0,"ConsignmentDepositRate":30.0,"CashOfConsignmentDepositRate":0.0})
09:01:38.6734,I,2176,0017 【WalletMargin】(5834@1)
09:01:38.6744,I,2176,0017 【WalletMargin】({"MarginAccountWallet":0.0,"DepositkeepRate":0.0,"ConsignmentDepositRate":30.0,"CashOfConsignmentDepositRate":0.0})
09:01:39.0952,I,2176,0017 【WalletMargin】(5834@1)
09:01:39.0962,I,2176,0017 【WalletMargin】({"MarginAccountWallet":0.0,"DepositkeepRate":0.0,"ConsignmentDepositRate":30.0,"CashOfConsignmentDepositRate":0.0})
09:01:39.5164,I,2176,0017 【WalletMargin】(5834@1)
09:01:39.5174,I,2176,0017 【WalletMargin】({"MarginAccountWallet":0.0,"DepositkeepRate":0.0,"ConsignmentDepositRate":30.0,"CashOfConsignmentDepositRate":0.0})
09:01:40.5623,I,2176,0017 【WalletMargin】(5834@1)
09:01:40.5623,I,2176,0017 【WalletMargin】({"MarginAccountWallet":0.0,"DepositkeepRate":0.0,"ConsignmentDepositRate":30.0,"CashOfConsignmentDepositRate":0.0})
09:01:42.2299,I,2176,0017 【WalletMargin】(5834@1)
09:01:42.2299,I,2176,0017 【WalletMargin】({"MarginAccountWallet":0.0,"DepositkeepRate":0.0,"ConsignmentDepositRate":30.0,"CashOfConsignmentDepositRate":0.0})
09:01:43.2759,I,2176,0017 【WalletMargin】(5834@1)
09:01:43.2769,I,2176,0017 【WalletMargin】({"MarginAccountWallet":0.0,"DepositkeepRate":0.0,"ConsignmentDepositRate":30.0,"CashOfConsignmentDepositRate":0.0})
09:01:45.5695,I,2176,0017 【WalletMargin】(5834@1)
09:01:45.5695,I,2176,0017 【WalletMargin】({"MarginAccountWallet":0.0,"DepositkeepRate":0.0,"ConsignmentDepositRate":30.0,"CashOfConsignmentDepositRate":0.0})
09:01:49.1034,I,2176,0017 【WalletMargin】(5834@1)
09:01:49.1044,I,2176,0017 【WalletMargin】({"MarginAccountWallet":0.0,"DepositkeepRate":0.0,"ConsignmentDepositRate":30.0,"CashOfConsignmentDepositRate":0.0})
09:01:50.7704,I,2176,0017 【WalletMargin】(5834@1)
09:01:50.7714,I,2176,0017 【WalletMargin】({"MarginAccountWallet":0.0,"DepositkeepRate":0.0,"ConsignmentDepositRate":30.0,"CashOfConsignmentDepositRate":0.0})
09:01:51.5050,I,2176,0017 【WalletMargin】(5834@1)
09:01:51.5060,I,2176,0017 【WalletMargin】({"MarginAccountWallet":0.0,"DepositkeepRate":0.0,"ConsignmentDepositRate":30.0,"CashOfConsignmentDepositRate":0.0})
09:01:51.6181,I,2176,0017 【WalletMargin】(4592@1)
09:01:51.6971,I,2176,0017 【WalletMargin】({"MarginAccountWallet":0.0,"DepositkeepRate":0.0,"ConsignmentDepositRate":30.0,"CashOfConsignmentDepositRate":0.0})
'''

連続で同じ要求だすとだめなのかな。
テストも取引もできないのでよろしくお願いします。

**Comment by cyber-minion** [comment]
>({"Password":"****************","Symbol":"9227","Exchange":1,"SecurityType":1,"Side":1,"CashMargin":2,"MarginTradeType":1,"DelivType":0,"AccountType":4,"Qty":300.0,"ClosePositionOrder":1,"FrontOrderType":20,"Price":1101.0,"ExpireDay":0})
09:17:57.7162,I,9592,0009 【SendOrder】({"Code":4002013,"Message":"パラメータ不正：MarginTradeType - 詳細はkabuSログファイルを確認してください"})

このエラーが発生したときのkabuSログを共有いただけますでしょうか？

**Comment by kitty2117** [comment]
kabuSログって？\KabuS\Logの下にあるKabuS_20221021.logかな？

KabuS_20221021.log
'''
09:17:57.7162,E,9592,0009 信用区分選択エラー : QuoteCode=9227/T, CashMargin=2, Side=1, MarginTradeType=1
09:17:57.7162,I,9592,0009 KabuSApiManager.PreRelationCheck=ERROR_CD_004_002_013
'''

１０月２０日にも同様エラーが起きています。
PLAIN_20221020_09.log
'''
09:57:44.4325,I,13564,0007 【SendOrder】({"Password":"****************","Symbol":"9115","Exchange":1,"SecurityType":1,"Side":1,"CashMargin":2,"MarginTradeType":1,"DelivType":0,"AccountType":4,"Qty":600.0,"ClosePositionOrder":1,"FrontOrderType":20,"Price":741.0,"ExpireDay":0})
09:57:44.4325,I,13564,0007 【SendOrder】({"Code":4002013,"Message":"パラメータ不正：MarginTradeType - 詳細はkabuSログファイルを確認してください"})
'''
KabuS_20221020.log
'''
09:57:44.4325,E,13564,0007 信用区分選択エラー : QuoteCode=9115/T, CashMargin=2, Side=1, MarginTradeType=1
09:57:44.4325,I,13564,0007 KabuSApiManager.PreRelationCheck=ERROR_CD_004_002_013
'''

よろしくお願いします。

**Comment by cyber-minion** [comment]
"CashMargin":2　ですと、「新規」発注ですが、
それに対して、"ClosePositionOrder":1　で返済建玉を指定しているので、エラーになったのではと考えております。
"ClosePositionOrder"をコメントアウトしていただき、再度お試しいただけますでしょうか？


![image](https://user-images.githubusercontent.com/69830869/197940504-63d52840-1cd0-419b-a0a8-47f25eaf6e6c.png)

**Comment by kitty2117** [comment]
今朝の取引のログPLAIN_20221026_09.logから抜粋ですが、
'''
09:06:00.6969,I,3364,0007 【SendOrder】({"Password":"****************","Symbol":"4385","Exchange":1,"SecurityType":1,"Side":1,"CashMargin":2,"MarginTradeType":1,"DelivType":0,"AccountType":4,"Qty":200.0,"ClosePositionOrder":1,"FrontOrderType":20,"Price":2299.0,"ExpireDay":0})
09:06:00.8109,I,3364,0007 【SendOrder】({"Result":0,"OrderId":"20221026A01N00101162"})
'''

新規の信用の注文ですが、ClosePositionOrder:1ですが、正常に取引できました
おそらく#597の関連で、保証金不足で取引制限されたために信用新規CashMargin:2ができない状態になっていたのかと思います。どうなんだろう？

**Comment by cyber-minion** [comment]
エラーとなっていた、9115と9227は、制度信用売建不可となっているため、発注エラーになったかと考えております。

![image](https://user-images.githubusercontent.com/69830869/197958877-e728241b-0ac5-48fb-9011-45a835ea9c7e.png)

**Comment by kitty2117** [comment]
なるほど、それで、パラメーター不正となったということですね。

ありがとうございました

ユーザースクリプトで信用の可不可は場の始まる前にチェックしてた項目ですが、それが動いてない。これユーザースクリプトでどっかバグってるな。。。orz
