### ISSUE TITLE
【質問】注文件数の上限

### ISSUE THREAD

**Issue by usigma** [kabucom/kabusapi#6]
利用規定によると「同一銘柄に対しての注文は5件を上限としてご利用ください」とありますが、
同時に注文を出しておける件数が5件まで、という理解でよろしいでしょうか？

**Comment by yasuyuki-nakazawa** [comment]
ご認識のとおりとなります。
同一銘柄の有効注文(同時に注文を出しておける注文)が5件の意です。
なお、当該数値に関しては改定することもございます。
