### ISSUE TITLE
【質問】wifi環境が変わるとkabuステーションが立ち上がりません

### ISSUE THREAD

**Issue by Yamamotoda** [kabucom/kabusapi#603]
通常自宅の光回線だと問題ないのですがファミリーマートのドコモd-WIFI環境だとkabuステーションが立ち上がりません。
対応策がありますか？
立ち上げ画面の〇通常はこちら（40000）と〇ログインできない場合（443）両方試しましたがだめでした。

**Comment by cyber-minion** [comment]
可能でしたら、安定した通信環境にてご利用いただければと思います。
ご参考として、kabuステーションを利用する推奨環境はこちらです。
https://kabu.com/support/requirements.html#anc14

**Comment by cyber-minion** [comment]
こちら、いったんクローズさせていただきます。
