### ISSUE TITLE
【質問】FundType パラメータの「信用代用」と「信用取引」の違いについて

### ISSUE THREAD

**Issue by supermomonga** [kabucom/kabusapi#604]
https://kabucom.github.io/kabusapi/reference/index.html#operation/sendorderPost

こちらに記載の `FundType` パラメータにつきまして、「信用代用」（`AA`）と「信用取引」（`11`）の違いについて質問致します。

1. 信用代用（`AA`）を指定して購入された現物株式は代用有価証券となる、という理解で正しいでしょうか
2. 信用取引（`11`）を指定して購入された現物株式はどの様な扱いとなるのでしょうか

また、これらにつきまして、ドキュメントへの追記をご検討頂けると助かります。

**Comment by yasuyuki-nakazawa** [comment]
確認いたします。少々お待ちくださいませ

**Comment by yasuyuki-nakazawa** [comment]
1．ご認識通りとなります
2．発注エラーになります。
信用口座を開設している場合は、AAを指定してください。
ただし、代用不適格のような規制が入っている場合は、02 （保護）を指定する必要があります。

リファレンスへの反映は追記の方向で検討いたします

**Comment by supermomonga** [comment]
> 1．ご認識通りとなります

承知しました、ありがとうございます。

> 2．発注エラーになります。

どういった場合において信用取引（`11`）を指定すべきでしょうか？

**Comment by cyber-minion** [comment]
> どういった場合において信用取引（11）を指定すべきでしょうか？

商品が信用の場合、「FundType=11」となりますが、指定は不要です。当該項目をリファレンスから削除する方向で検討させていただきます。

**Comment by supermomonga** [comment]
なるほど、承知致しました。ありがとうございます。
