### ISSUE TITLE
発注において、自動売買の指定は出来ないのでしょうか【質問】

### ISSUE THREAD

**Issue by sunaka** [kabucom/kabusapi#606]

**Comment by yasuyuki-nakazawa** [comment]
自動売買というのは、条件による取引ということでしょうか。
現状ですと、API経由で逆指し値注文をはじめ、引け指定、寄り指定の注文は実施いただけます。
リレー注文や、Uターン注文は現状サポートしておりません

**Comment by cyber-minion** [comment]
こちらはいったんクローズさせていただきます。
