### ISSUE TITLE
【要望】KabuステーションのHOTとの連携

### ISSUE THREAD

**Issue by kabusukebe** [kabucom/kabusapi#61]
自作アプリで監視している銘柄のチャートなどを素早く確認できるように、以下のような機能があると嬉しいです。

* HOTに銘柄を反映するREST API
* HOTの銘柄変更を取得できるPUSH API

ご検討よろしくお願いいたします。

**Comment by yasuyuki-nakazawa** [comment]
kabuステーションの操作（HOT連動）と、HOT銘柄取得ということで認識しました。
これまでにない観点でのご要望ですが、検討させて頂きます。

**Comment by yasuyuki-nakazawa** [comment]
kabuステーションAPIでkabuステーションを動作させるという点に関しては、現状対応を見送らせていただきます。
・外部要求からのkabuステーションのアクションの口を設けることのリスク、
・HOTキー連動は親画面を主軸に複数画面の制御を行う必要もあり、親画面のない他画面制御
という点から、申し訳ございませんが、直近の改善計画からは落とさせていただきます。

**Comment by rewish** [comment]
@yasuyuki-nakazawa 
承知いたしました。
ご検討ありがとうございました。

**Comment by kabusukebe** [comment]
@yasuyuki-nakazawa 
承知いたしました。
ご検討ありがとうございました。
