### ISSUE TITLE
【質問】オプション板情報取得で任意の銘柄情報が取得できません

### ISSUE THREAD

**Issue by nyao4** [kabucom/kabusapi#611]
銘柄コード取得→板情報取得を行っているのですが、現在2022年12月26875円以下全ての銘柄がプット、コールともに正しく板情報が取得できません。

raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request

いまいち解決方法が分からず、どのようにすれば正しく板情報を取得できますでしょうか。

**Comment by nyao4** [comment]
おそらく原因はレジスト数エラーだとだと思います。
銘柄情報を取得する際、未登録の銘柄の場合は自動的に登録され、登録数上限50を超えて銘柄情報を取得しようとしたために発生したエラーだと思われます。
ということで、全登録銘柄解除の操作を行ったところ無事26875円以下の情報も取得できました。
お騒がせして申し訳ありませんでした。

**Comment by nyao4** [comment]
おそらく原因はレジスト数エラーだと思います。
銘柄情報を取得する際、未登録の銘柄の場合は自動的に登録され、登録数上限50を超えて銘柄情報を取得しようとしたために発生したエラーだと思われます。
ということで、全登録銘柄解除の操作を行ったところ無事26875円以下の情報も取得できました。
お騒がせして申し訳ありませんでした。

**Comment by cyber-minion** [comment]
解決できてよかったです。ではクローズさせていただきます。
