### ISSUE TITLE
【質問】信用建玉の成行返済で「決済指定内容に誤りがあります」

### ISSUE THREAD

**Issue by daisuke-b** [kabucom/kabusapi#613]
同一銘柄で同数量（100株）ずつ、2本の建玉を信用買いで保有しておりました

それらをAPIから連続して（約定0.5秒違い）順番に成行返済したところ、
片方は成功、片方は失敗（決済指定内容に誤りがあります）となりました

記録していた発注（sendorder）時のパラメータを比較しても指定した建玉ID以外に全く違いはありません

【成功時】
2022/12/06 10:11:06.632 {"Password":"XXXXXXXX","Symbol":"7012","Exchange":1,"SecurityType":1,"Side":"1","CashMargin":3,"MarginTradeType":3,"AccountType":4,"Qty":100,"DelivType":2,"ClosePositions":[{"HoldID":"E2022120600AAA","Qty":100}],"FrontOrderType":10,"Price":0,"ExpireDay":0}

【失敗時】
2022/12/06 10:11:07.098 {"Password":"XXXXXXXX","Symbol":"7012","Exchange":1,"SecurityType":1,"Side":"1","CashMargin":3,"MarginTradeType":3,"AccountType":4,"Qty":100,"DelivType":2,"ClosePositions":[{"HoldID":"E2022120600BBB","Qty":100}],"FrontOrderType":10,"Price":0,"ExpireDay":0}

※建玉IDの下は仮のものに置き換えています

失敗した方の建玉は仕方なく画面から手動で返済しました

ほとんどは成功するのですが稀にこのエラーが発生します

このエラーにはどんな原因が考えられますでしょうか

タイミングが原因だったり？（リトライすれば成功するとか）

またなにか原因を把握するためのログなどありますでしょうか

よろしくお願いいたします

**Comment by daisuke-b** [comment]
===============================
①ソースコードについて
===============================

c#です

メインのスレッドとは別にワーカースレッドが複数常駐しています

1ワーカーは信用の[新規発注⇒返済]を担います

1ワーカーはメインからの指示を受けて1銘柄の1回分の新規発注⇒返済を終えたら待機に戻ります

1ワーカーは1つの建玉を建て、一定時間後にその建玉を返済したらまた待機に戻るとお考えください

今回は2つのワーカーが同じ銘柄の建玉を建て、当該銘柄の時価が条件に達したのでどちらのワーカーも同じタイミングで成行返済を実行しました

※各ワーカーから呼ばれる共通の発注処理（抜粋）
---------------------------------------------------------
try
{
    ・・・  省略　・・・

    string json = <発注用json文字列> //ワーカーから指定されるPOST用データ

    Debug(json ?? "null");  //昨日お知らせした内容はココで取ったもの

    using (var client = new HttpClient())
    {
        client.DefaultRequestHeaders.Add("X-API-KEY", apa.Token);

        StringContent content = new StringContent(json, Encoding.UTF8, "application/json");

        HttpResponseMessage response = await client.PostAsync("http://localhost:18080/kabusapi/sendorder", content);

        string responseContent = await response.Content.ReadAsStringAsync();

        return responseContent;
    }
}
catch
{
    return null;
}

---------------------------------------------------------

今回は2ワーカーが同じ銘柄を同時に別の建玉で処理していて、
時価が引っ掛かったので同時に成行返済をしたところ
0.5秒遅れで後から返済した方の返済で「決済指定内容に誤りがあります」となりました

ただ「決済指定内容に誤りがあります」は1ワーカーの処理中でも発生したことがありますので
同時並行性は関係ないかもしれません

===============================
②エラーの意味
===============================

「決済指定内容に誤りがあります」にもいくつか理由があると思っていますが
どのような事例がありますか

例

・返済済の建玉IDを指定した
・建玉の株数とは別の数量を指定した
・注文apiの秒間5件の上限を超えた

など

事例がわかればこちらで該当するものがないか調べてみます

===============================
③ログ
===============================

決済指定内容に誤りがありますの原因がわかるapiのログなどありますでしょうか

必要なら提供します

よろしくお願いいたします

**Comment by yasuyuki-nakazawa** [comment]
記載いただいている
・返済済の建玉IDを指定した
というのが原因のほとんどですが、今回は単元でのポジションですので、可能性は薄いと考えますが、
分割約定されたときの建玉ID指定ミスということが過去お問い合わせある場合では多いパターンでした。

流量制限に起因するエラーの場合は別のエラーコードが帰りますので、そちらには該当していないと考えます。
あとよくあるパターンとしては
・売買区分の指定ミス

こちらも記載いただいているログ的にはSideの指定は同じため原因とは考えにくいです。
頂いているログからエラーが発生する要因を確認してみます

**Comment by daisuke-b** [comment]
検討いただきありがとうございます

1つ補足です

今回、建玉の成行返済で「決済指定内容に・・」が発生したわけですが、
成行返済の前に指値の返済を挟んでいました

①新規注文⇒約定
②返済注文（指値）⇒一定時間経過しても約定しないため注文取消（apiのcancelorderを実行）
③返済注文（成行）⇒"決済指定内容に誤りがあります"エラー

②の部分↓（抜粋）

HttpResponseMessage response = await client.PutAsync("http://localhost:18080/kabusapi/cancelorder", content);

もちろん②（cancelorder）の戻りのresponseで"Result"が0であることを確認してから
③（成行返済）を実行していますが、②と③の間の時間はわずかで、アプリケーションのログからは100ms～200ms違いでした

cancelorderのResultが0ではあるものの、タイムラグ？によりまだ実際の注文取消が未完了だと仮定すると
1つの建玉に対して指値の返済注文が残っているにもかかわらず成行の返済注文を追加してしまうことになり
決済指定内容に誤りが・・となる？と思ったりしました

■こういうこと（タイムラグ）ってあるものでしょうか

■取消完了はcancelorderのResultを見るだけでは不十分でしょうか

ちなみに③が成功している場合も②を挟んでいます

失敗頻度が稀で、建玉ID以外に成功時との違いがなので
これぐらいしか理由が見当たらないことから
②と③の間はもう少し時間を空けるなどして様子を見ようと思いますが
ご意見いただければ幸いです

**Comment by cyber-minion** [comment]
情報提供、ありがとうございます。
（指値/成行以外のパラメータで）同じパラメータ設定で、②で発注はできたのですが、③で成行に変更し発注したらエラーになったということですね？

**Comment by daisuke-b** [comment]
はい。その通りです

②を取り消し（cancelorder）した後です

**Comment by yasuyuki-nakazawa** [comment]
システム的に取消が完了する前に発注した場合は、対象となるポジションが拘束されている状況であるため、
エラーとなることが想定されますが、注文取消の完了をご確認されてからの成行注文を出された感じでしょうか？

**Comment by cyber-minion** [comment]
> ②と③の間の時間はわずかで、アプリケーションのログからは100ms～200ms違いでした

注文取消→成行注文の実行間隔が短かったと思慮いたします。
もっと間隔をあけていただき、再発するか様子を見ていただけますでしょうか？

**Comment by daisuke-b** [comment]
了解です

間隔を開けて様子を見ます

しばらく再発しなければクローズします

検討いただきありがとうございました
