### ISSUE TITLE
【質問】注文、注文受付、残高、約定、建玉の関係について

### ISSUE THREAD

**Issue by h-tsun3** [kabucom/kabusapi#614]
用語が難しくて混乱している株取引初心者です。よろしければ以下の質問にお答えください。

国内株の信用取引における新規注文発注時（/sendorder）には、APIからOrderId（受付注文番号）が返されます。
一方、返済注文時には、HoldID（返済建玉ID）が必要ですが、OrderIdに紐づくHoldIDの取得方法が分かりません。

注文約定照会（/orders）ではパラメータとしてid（注文番号）を取ることができますが、これは先ほどのOrderId（受付注文番号）のことでしょうか？
もしそうでないとすれば、どのようにして利用者はid（注文番号）を知り得るのでしょうか？

残高照会（/positions）のレスポンスの配列は、各々ExecutionID（約定番号）を持ちますが、実際に表示されるのは、建玉ではないでしょうか。
そして、このExecutionID（約定番号）が、返済注文時に必要なHoldID（返済建玉ID）ということではないですか？
もしそうでないとすれば、どのようにして利用者はHoldID（返済建玉ID）を知り得るのでしょうか？

**Comment by cyber-minion** [comment]
> OrderIdに紐づくHoldIDの取得方法

OrderId（受付注文番号）にて注文約定照会APIを呼び出すと、「Details（注文詳細）」が返却されますが、その中にある「ExecutionID（約定番号）」が「HoldID（返済建玉ID）」になります。

また、「ExecutionID」は残高照会でも取得可能です。

**Comment by h-tsun3** [comment]
良く分かりました。有難うございました。

**Comment by cyber-minion** [comment]
解決済みですので、クローズさせていただきます。
