### ISSUE TITLE
【要望】注文約定照会の執行条件の値0の説明について

### ISSUE THREAD

**Issue by hiuchida** [kabucom/kabusapi#615]
注文約定照会(/orders)のレスポンスの執行条件(OrdType)について、注文詳細(Details)の配列の一部で値として0が返る場合があります。
説明が1:ザラバ、2:寄り・・・と値0の説明はないので、仕様通りの動作ならば、説明を追記して頂きたいです。

**Comment by cyber-minion** [comment]
確認のうえ、必要に応じてリファレンスを補完するようにいたします。いったん少々お時間をいただければ幸いです。

**Comment by yasuyuki-nakazawa** [comment]
正式回答は別途させていただきますが、対象のデータは注文の取り消しまたは、約定済みのデータ等ではございませんでしょうか

**Comment by cyber-minion** [comment]
OrdTypeは、0とnullになる場合があります。具体的には以下のパターンとなります。リファレンスを補完するようにいたします。

・RecType=[3] 期限切れ, [7] 失効, [8] 約定　の場合、ORDTYPEが０になる
・RecType=[6] 取消　の場合、ORDTYPEが null になる

**Comment by cyber-minion** [comment]
リファレンスを修正しました。ご確認いただければ幸いです。

**Comment by cyber-minion** [comment]
リファレンスを修正済みですので、いったんクローズさせていただきます。

**Comment by jima206** [comment]
クローズしたところ失礼します。
以下のリファレンスを参照してもOrdTypeやRecTypeの数字がそれぞれ何を意味するのか記載されていないのですが、別の詳細なリファレンスがどこかにあるでしょうか？
https://kabucom.github.io/kabusapi/reference/index.html

その場合そのリファレンスの掲載先をご教示いただけないでしょうか？
もしくは、OrdTypeとRecTypeの読み方（各数字が何を意味するのか）について一覧をご回答いただけないでしょうか？
よろしくお願いいたします。

**Comment by hiuchida** [comment]
OrdTypeやRecTypeの表が見えないということですが、

Responseの下の部分がクリックできて、正常終了の「> 200 OK」をクリックすると、JSONの1階層目の項目の一覧が表示されます。
さらに今回は、Details配列の中の説明で、「Details >」をクリックすると、2階層目の項目の一覧が表示されます。

Redocというツールが生成しているようですが、ちょっと分かりにくいかもですね。

**Comment by jima206** [comment]
hiuchidaさん
ありがとうございます、見つけることができました。
またgithubの使い方に慣れておらず、恐らくhiuchidaさんを巻き込む形となってしまいました。失礼いたしました。
丁寧にご回答いただき大変助かりました。
