### ISSUE TITLE
[質問]サンプルのエクセルマクロを使った自動発注

### ISSUE THREAD

**Issue by maruyama-fay** [kabucom/kabusapi#617]
サンプルの「kabuSTATION_API_ORDER_sample.xlsm」を流用して発注ボタンを押さずに自動発注する方法を教えてください。
以下のような処理概要です。

「kabuSTATION_API_ORDER_sample.xlsm」の右側の使っていないセルに
・計算式を入れて、ある条件が整ったら1などのフラグを表示されるようにする。
・フラグの立った行、たとえば2行目がフラグオンなら2行目の銘柄が発注される。

・前提としては、データは正しくセットされている。
・発注ボタンの行番号入力のセルD4に行番号を自動セットされて、ボタンが勝手に押される。といった仕組みでも可能。

Worksheet_Calculateで色々試しているのですが、上手くいかず。
何かヒントがあれば教えていただけますでしょうか。

**Comment by yasuyuki-nakazawa** [comment]
サンプルは参考ということで、発注ボタンのイベントをトリガーに発注処理を実施するものとなっております。
自動発注に関しては様々な手段があるかと思いますが、Excelを利用してという前提ということであれば、
WorksheetのChangeイベントをフックして、諸条件を満たした板場合に発注処理を実行するということも可能かと思います。

**Comment by maruyama-fay** [comment]
回答ありがとうございます。
Excel前提の質問でした。マクロにてテストして具体的な質問になった際に、また投稿したいと思います。
一旦クローズします。ありがとうございました。
