### ISSUE TITLE
【質問】PUSH配信のBIDSIGNの数字の意味はなんでしょうか？

### ISSUE THREAD

**Issue by nori-2023** [kabucom/kabusapi#621]
【質問】PUSH配信のBIDSIGNの数字の意味はなんでしょうか？

0101，0120、0107などの数字があります。この数字の意味は何でしょうか？ほかにもあったら教えてください

**Comment by yasuyuki-nakazawa** [comment]
APIリファレンスで時価情報のレスポンスに値の意味は記載ございます。
こちらにも、転記いたします。

0000 | 事象なし
0101 | 一般気配
0102 | 特別気配
0103 | 注意気配
0107 | 寄前気配
0108 | 停止前特別気配
0109 | 引け後気配
0116 | 寄前気配約定成立ポイントなし
0117 | 寄前気配約定成立ポイントあり
0118 | 連続約定気配
0119 | 停止前の連続約定気配
0120 | 買い上がり売り下がり中
