### ISSUE TITLE
【質問】午後の寄り付きについて

### ISSUE THREAD

**Issue by mik2008** [kabucom/kabusapi#622]
特定の銘柄が午前に寄り付いたかどうかは OpeningPrice から判断可能ですが、
午後の寄り付き有無を何かしら間接的にでも判断出来ればいいなと思っています。
kabuステーション側の機能にないと言えばそれまでなのですが、
現在価格の値などの他の情報もしくはそれらの組み合わせで午後の寄り付き有無を間接的にでも判断する手段は何かございますでしょうか…？

**Comment by yasuyuki-nakazawa** [comment]
後場の寄り付き状況を判断したいという内容ですよね。
現状ですと、後場寄りを判断することはできない認識です。前場に値段がつかない場合は後場の値段を見てということで判断をできるかとは思いますが。
後場開始という情報は取引所から受診していますので、気配値とセット等で可能かは確認してみます

**Comment by yasuyuki-nakazawa** [comment]
現状ですが、取引所側の情報としても後場の寄り値という形で情報を受信していない都合上、ご依頼されているものを直接的にご提供することはできないと思慮いたしました。
一方で、Push接続であれば、後場に来た最初の情報を寄りつき情報と見立てて処理することは可能かと思いますので、そちらの方でもご検討いただければ幸甚です

**Comment by mik2008** [comment]
承知しました
ご対応ありがとうございました
