### ISSUE TITLE
【質問】DockerコンテナからAPIへのアクセスがうまくいきません

### ISSUE THREAD

**Issue by fdfpy** [kabucom/kabusapi#623]
お世話になります。最近になってAPIを触っている者ですが分からない点があり、質問させてください。
Windows11上にDokcerコンテナを立ち上げ、curlコマンドで"http://localhost:18080/kabusapi/token"にアクセスしましたがうまくいきません。Win11上のDocker コンテナからKabu station APIにアクセスができている方が入れば、どのようにすればいいか教えていただけないでしょうか。
ちなみに、実施したことを下記に示します。

(1)Docker Desktopn for windowsでコンテナを作成

★docker-compose.yml
version: "3"
services:

  be:
    container_name: be0
    build: ./be
    volumes:
      - ./be/app:/app
    ports:
      - "5000:5000"
    command: tail -f /dev/null   #コンテナ起動状態を維持するため
    links:
      - db

★Dockerfile
FROM ubuntu:20.04
FROM python:3.9.2-buster

RUN apt-get update
RUN apt-get install lsof

RUN apt install -y nodejs npm
RUN npm install python-shell
RUN npm install express
RUN npm install mysql

RUN mkdir /app
ADD requirements.txt /app

ENV PYTHONUNBUFFERED 1
EXPOSE 5000

WORKDIR /app
RUN pip3 install -r requirements.txt

(2)iitenkida7様 commented on Sep 11, 2020(from #34)に従い、Win11上にnginxを導入

(3)Win11上ホスト コマンドプロンプトにて下記コマンドを実施し、トークンが取得できることを確認済

curl -X POST -H "Content-Type: application/json" "http://localhost:18080/kabusapi/token" -d "{\"APIPassword\":\"mypassword\"}"

(4)Win11 Dokcerコンテナ上で下記のコマンドを実施。応答が正常であることを確認

sh-5.0# curl (Win11のローカルIPアドレス):80
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
html { color-scheme: light dark; }
body { width: 35em; margin: 0 auto;
font-family: Tahoma, Verdana, Arial, sans-serif; }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>

(5))Win11 Dokcerコンテナ上で下記のコマンドを実施。APIにアクセス不可であることを確認

sh-5.0# curl -X POST -H "Content-Type: application/json" "http://(Win11のローカルIPアドレス):80/kabusapi/token" -d "{\"APIPassword\":\"mypassword\"}"
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.22.1</center>
</body>
</html>

**Comment by cyber-minion** [comment]
確認ですが、同一端末にカブステが起動していますでしょうか？

**Comment by fdfpy** [comment]
はいそうです。dockerもKabustationも同じWIn11　PC上に稼働させています

**Comment by hysdsk** [comment]
DockerコンテナからホストOSのアプリケーションに接続するときは`host.docker.internal`で接続できます。
https://docs.docker.jp/v19.03/docker-for-mac/networking.html

あと、おそらくKabuステーションでホスト名のバリデーションを行っているようなので、Hostヘッダをつける必要がありました。一応以下のコマンドでトークンが取得できることを確認しました。
```
curl -X POST -H "Content-Type: application/json" -H "Host: localhost" -d @data.json http://host.docker.internal:18081/kabusapi/token
```

**Comment by fdfpy** [comment]
ご教授いただいたやり方でdockerコンテナからKabu stationに接続ができました。ありがとうございました。
