### ISSUE TITLE
【質問】返済売の場合にエラー？

### ISSUE THREAD

**Issue by fujitake-corder** [kabucom/kabusapi#624]
お世話になります。
信用デイトレにて売買する際に、新規買に対する返済売を実施しようとすると
　Error Code:4001001  Message:内部エラー
とエラーが表示され、KabuSのログ内を確認しますと、以下のエラーが表示されます。
> 13:54:53.5371,E,4048,0011 リクエスト処理中のエラー
> System.NullReferenceException: オブジェクト参照がオブジェクト インスタンスに設定されていません。
>   場所 t4.b(HttpListenerRequest A_0, HttpListenerResponse A_1, Boolean A_2)
>   場所 t4.b(HttpListenerContext A_0)

以下、リクエスト時の送信情報になります。(パスワードはマスクしております。)
{"Password":"******","Symbol":"6731","Exchange":1,"SecurityType":1,"Side":"1","CashMargin":3,"MarginTradeType":3,"DelivType":2,"AccountType":4,"Qty":100,"ClosePositionOrder":0,"FrontOrderType":27,"Price":5,"ExpireDay":0}

恐れ入りますが、リクエスト情報にて不備ございましたら、ご指摘の程お願いいたします。

**Comment by cyber-minion** [comment]
こちらにて、同じパラメータで問題なく返済売注文を出すことができました。

一度、カブステを再起動していただき、返済注文を出せるか確認いただけますでしょうか？
もし、エラーとなる場合は、カブステ本体から返済注文が出せるか確認いただけますでしょうか？

**Comment by fujitake-corder** [comment]
ご連絡ありがとうございます。
　・PCを再起動した場合でも同様にエラーが発生します。（別日にPC起動し試しましたが同様でした。）
　・カブステ本体から返済注文する事は出来ました。

**Comment by cyber-minion** [comment]
以下の手順でログをアップロードいただけますでしょうか？その後、実施の日時をご連絡願います。

ログアップロード手順
１．カブステ画面右上にある </> を右クリック
２．「OPEログアップロード」をクリック
![image](https://user-images.githubusercontent.com/69830869/214211237-cce3ea4e-10cc-4869-b49e-60b777d9ca71.png)

**Comment by fujitake-corder** [comment]
アップロードいたしました。
実施時間は01/25 08:33になります。

**Comment by cyber-minion** [comment]
ログのアップロード、ありがとうございます。
追加の依頼で恐れ入りますが、可能な範囲で結構ですので、実行されているプログラムを共有していただけますでしょうか？

**Comment by fujitake-corder** [comment]
売却実行する際の処理は以下になります。(C#)
>                    UriBuilder url = new UriBuilder([カブステのURL]);
>                    parameter.Password = "XXXXXXXXXX";
>                    url.Path = "kabusapi/sendorder";
>                    string token = Program.AutoTrading.Api_Token.Token;
>                    CashBuySellResponse JsonResult = null;
>                    JsonSerializerOptions options = new()
>                   {
>                       DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull
>                    };
>                    var client = new HttpClient();
>                    var request = new HttpRequestMessage(HttpMethod.Post, url.ToString());
>                    request.Headers.Add("ContentType", "application/json");
>                    request.Headers.Add("X-API-KEY", token);
>                    JsonSerializer.Serialize<CashBuySellParameter>(parameter, options);
>
>                    HttpResponseMessage response = client.SendAsync(request).Result;
>                    if (Api_Properties.StatusCodeCheck(response, url) == null)
>                    {
>                        JsonResult = JsonSerializer.Deserialize<CashBuySellResponse>(response.Content.ReadAsStringAsync().Result);
>                    }

売却実行している処理は上記になります。
更にプログラム必要であれば売却処理を記述したファイルを送付致します。
よろしくお願いします。

**Comment by cyber-minion** [comment]
request.ContentにJsonのパラメータを設定していないことが原因で、C#のサンプルコードのKabusapi_Sendorder_Cash_sell.csの51行目を参考として、処理を見直していただければと思います。

**Comment by fujitake-corder** [comment]
初歩的なミスで申し訳ないです。
ご指摘頂いた修正を実施し、実行する事ができました。
本件はクローズさせて頂きます。
