### ISSUE TITLE
【質問」先物などの銘柄コードとEXCHANGEの番号を知りたい

### ISSUE THREAD

**Issue by nori-2023** [kabucom/kabusapi#625]
PYTHONでの先物などの銘柄コードとEXCHANGEの番号を知りたい。
カブコム証券で一覧で閲覧できるところはありませんか？

**Comment by yasuyuki-nakazawa** [comment]
APIにて先物の銘柄コードを取得することが可能です
/symbolname/future
市場（Exchange）に関しては、先物ということで、種類は限られるかと思います。
こちらはAPIリファレンスに記載ございますので、ご参照いただければと存じます。
銘柄情報取得のレスポンスをご参照ください
