### ISSUE TITLE
"Code":10019,"Message":"パスワードをご確認ください"

### ISSUE THREAD

**Issue by USS123** [kabucom/kabusapi#626]
初心者です。
kabuSTATION_API_ORDER_sample.xlsmの発注ですが、
カブコムのログインパスワードを変えてから発注できなくなりました。
本番用ログインボタンは緑色に変わるのですが、発注ボタンをクリックすると「"Code":10019,"Message":"パスワードをご確認ください"」とエラー表示されます。
カブステーションからは注文入れることができるのですが、なぜでしょうか？

**Comment by yasuyuki-nakazawa** [comment]
ログインパスワードのほかに取引パスワードがありますが、今回はログインパスワードだけを変更して、取引パスワードは変更していない？ということでしょうか。
ログインパスワードと取引パスワードは別のモノを設定できますので、ご利用されているパスワードをご確認していただくと切り分けの一つになると思慮いたします。

**Comment by yasuyuki-nakazawa** [comment]
訂正します。ログインパスワードと取引パスワードは同一でした。
excel発注シートにあるパスワードが古いままということではないでしょうか？

**Comment by USS123** [comment]
ありがとうございました。
左上に入力欄がありますね。
うっかり見逃して数時間悩んでしまいました。

**Comment by cyber-minion** [comment]
解決したようで、いったんクローズさせていただきます。
