### ISSUE TITLE
【質問】「IFO」注文を実現するには？（先物銘柄）

### ISSUE THREAD

**Issue by aisland9** [kabucom/kabusapi#627]
ある先物の銘柄に対して、指値や逆指値で注文（新規）をする時、
同時に、その注文が約定した後の決済注文（返済）も上値と下値に両方入れたいと思っています。
どのようにAPIを組み合わせれば実現出来るでしょうか？

**Comment by cyber-minion** [comment]
W指値注文がしたいという理解でよろしいでしょうか？

**Comment by cyber-minion** [comment]
IFO注文は現在対応しておらず、申し訳ございません。
現状では、決済注文（返済）に対する操作・設定は、新規注文が約定してからになります。

**Comment by aisland9** [comment]
ありがとうございました。
クローズで大丈夫です。
