### ISSUE TITLE
【質問】「OCO」決済注文を実現するには？（先物銘柄）

### ISSUE THREAD

**Issue by aisland9** [kabucom/kabusapi#628]
建玉を持った後、仮に期待通りプラスとなったとします。
その建玉に対して、決済注文（返済）を上値と下値に実施したい（もしくは変更したい）と思っています。

その場合、おそらく１回目（API：sendoderFuturePostの「TradeType」は「新規」）の後に、２回目（API：sendoderFuturePostの「TradeType」は「返済」）を実施すると思います。
２回目の際、「ClosePositions」の「返済建玉ID」はどこから取得するのでしょうか？

**Comment by cyber-minion** [comment]
> 「返済建玉ID」はどこから取得する

返済建玉IDは、注文約定照会APIか残高照会APIで取得可能です。
過去の類似問い合わせ：https://github.com/kabucom/kabusapi/issues/614#issuecomment-1364902144

> 決済注文（返済）を上値と下値に実施したい

ただし、現状OCO注文は対応しておらず、申し訳ございません。

**Comment by aisland9** [comment]
ありがとうございます。

ちなみに、指値／逆指値で注文して、注文完了して、その後に約定が完了したのを知るには、
注文約定照会APIを呼び出して「Details（注文詳細）」の中にある「RecType（明細種別）」が「8（約定）」になったら約定完了という意味でしょうか？
（そのタイミングで、「Details（注文詳細）」の中にある「ExecutionID（約定番号）」が設定されるのか？）

**Comment by aisland9** [comment]
ありがとうございます。

ちなみに、指値／逆指値で注文して、注文完了して、その後に約定が完了したのを知るには、
注文約定照会APIを呼び出して「Details（注文詳細）」の中にある「RecType（明細種別）」が「8（約定）」になったら約定完了という意味でしょうか？
（そのタイミングで、「Details（注文詳細）」の中にある「ExecutionID（約定番号）」が設定されるのか？）

**Comment by cyber-minion** [comment]
はい、ご認識の通りです。

**Comment by aisland9** [comment]
素早いお返事ありがとうございます。

追加で質問というか確認です。既出で以下があります。
――――――――――――――――――――――――――――――
tsuchinaga commented on Oct 5, 2021 • 
【質問】指値と逆指値の同時売り注文の方法について #400
950円で買った1単元のポジションを売りでエグジットする場合で、
1000円で利確、900円で損切するとします。
950円のポジションに対して1000円の指値注文を入れた時点で、950円のポジションは拘束されるので逆指値は入れられません。
そのため価格を監視して、900円になったら指値をキャンセルして成行注文を出す必要があります。
――――――――――――――――――――――――――――――

これは１年半ぐらい前の話ですが、今でもこのような仕様でしょうか？

**Comment by cyber-minion** [comment]
> 今でもこのような仕様でしょうか

そうです

**Comment by aisland9** [comment]
ですよね、、

ありがとうございます！

**Comment by cyber-minion** [comment]
解決済みのようで、いったんクローズさせていただきます。
