### ISSUE TITLE
【質問】リアルマネーを使用せずに、APIを試せるか？

### ISSUE THREAD

**Issue by aisland9** [kabucom/kabusapi#629]
自動売買プログラムを作った後に、そのプログラムが期待通り動くかテストする必要がありますが、入金したお金を使わずに出来る方法はありますか？

**Comment by cyber-minion** [comment]
kabuステーションAPIは検証用ポートがありますので、作成したプログラムの疎通確認としてご利用いただけます。

**Comment by aisland9** [comment]
ありがとうございました。
クローズで大丈夫です。

**Comment by aisland9** [comment]
ありがとうございました。
クローズで大丈夫です。
