### ISSUE TITLE
token取得方法

### ISSUE THREAD

**Issue by baku314** [kabucom/kabusapi#63]
お世話になっております。
tokenの取得でつまずいております。ご教授いただければ幸いです。

**Comment by yasuyuki-nakazawa** [comment]
頂いている質問ですと、どの点でつまずかれているのかがわかりません。
開発言語、Token取得リクエストをコールした際のエラー内容、その際のログメッセージ等があれば支援できる可能性がございます。

**Comment by baku314** [comment]
お世話になっております。いかなる開発言語を用いて、どのようにToken取得リクエストをコールすればよいのかお教え願います。ちなみに習得しているのは、Rとエクセルです。大変お手数をおかけいたします。

**Comment by cyber-minion** [comment]
エクセルのご習得とのことですので、下記サイトをご参考いただければと思います。
https://kabucom.github.io/kabusapi/ptal/add-in.html

**Comment by baku314** [comment]
お世話になっております。
新設なご指導のおかげで発注することができました。ありがとうございました。
