### ISSUE TITLE
【質問】注文約定照会ついて

### ISSUE THREAD

**Issue by hendrix0219** [kabucom/kabusapi#630]
ご教授ください。

夜間取引にて先物miniを逆指値で16:18に発注を出し、値段が未達のため、約定せずに翌日6:00で失効しました。

約定したのか失効したのかを確認するため、2時間40分後（8:40)に、注文番号をパラメーターとして、ordersで見たのですが、[]が返って来ます。

この場合、失効するとordersリクエストしても[]になるのでしょうか？

失効していない注文の番号でテストするとレスポンスは中身有りで返ってくるので、コードは問題ないと思うのですが、、、、

よろしくお願いいたします。

**Comment by cyber-minion** [comment]
注文が失効されて、カブステを再起動すると失効した注文は[]が返ります。

**Comment by hendrix0219** [comment]
ご教授ありがとうございます！
