### ISSUE TITLE
【質問】PYTHONで先物のPUSH配信を受信されるとBidTimeのERRORが表示される

### ISSUE THREAD

**Issue by nori-2023** [kabucom/kabusapi#632]
PYTHONで先物のPUSH配信を受信されると下記のようなBidTimeのERRORが表示されるのですが、なぜでしょうか？データの受信はできているのですが。

{先物のPUSH配信されたデータの表示}
--- ERROR --- 
'BidTime'

**Comment by cyber-minion** [comment]
以下の手順でログをアップロードいただけますでしょうか？その後、アップロード実施の日時、当該事象の発生日時をご連絡願います。

ログアップロード手順
１．カブステ画面右上にある </> を右クリック
２．「OPEログアップロード」をクリック
![image](https://user-images.githubusercontent.com/69830869/214211237-cce3ea4e-10cc-4869-b49e-60b777d9ca71.png)
