### ISSUE TITLE
【質問】github pagesについて

### ISSUE THREAD

**Issue by hitoshietoh** [kabucom/kabusapi#633]
一般的に商用不可なのですがこちらは問題ないでしょうか？
https://kabucom.github.io/kabusapi/ptal/index.html

**Comment by cyber-minion** [comment]
上記質問について理解が及ばずでした。ご意図など、詳細情報をいただけますでしょうか？

**Comment by cyber-minion** [comment]
こちらいったんクローズさせていただきます。
