### ISSUE TITLE
【質問】自動ログアウト後の挙動について

### ISSUE THREAD

**Issue by spotthediff** [kabucom/kabusapi#64]
kabu stationが明け方に自動でログアウトするということですが、ログアウト後に再度新規tokenを取得する際はログインが必要になるのでしょうか?
それともログアウトしたままでもtokenにアクセスすれば新たなtokenを取得することができるのでしょうか?

**Comment by yasuyuki-nakazawa** [comment]
ログインが必要です。
未ログイン状態ですと、Token取得リクエストでエラーが返されます

**Comment by spotthediff** [comment]
ログインを自動で行う方法はありますか?

**Comment by spotthediff** [comment]
毎朝早く起きてログインしないといけないのは辛いため改善していただきたいです

**Comment by yasuyuki-nakazawa** [comment]
ログインを自動で行う手段は現状ありません。
ログインに関しては、口座番号、パスワードが必要となっており、諸セキュリティ観点の面を勘案し、
ログインセッションの継続や、自動ログイン機能はkabuステーションとしての実装予定はございません。

諸ツール等による自動ログイン等に関しては、お客様のご責任の下実施いただくこととなり、推奨はしかねます。

**Comment by kichikun-w** [comment]
既にClosedになっていますが yasuyuki-nakazawa 様へコメントさせていただきます。

私も毎朝の忙しい時間帯の再ログイン作業から解放されたいと思っています。
「早朝」が何時なのかは存じ上げませんが、通勤時間が長いサラリーマンには運用不可能になっている事もあり得ると思います。
せめて自動ログアウトの時刻を１８：００等、前日の夕刻にしていただければ、
夜寝る前に再ログインして寝る・・・と言うルーティーンが可能なので、
再ログインの実装予定が無いのであれば、自動ログアウト時刻の変更を検討していただきたいです。

「諸セキュリティ観点の面を勘案し」との事ですが、仮想通貨取引所等は一度発行したトークンセットが永遠に使える仕様が標準的です。
私は複数の仮想通貨取引所で、ノーメンテナンスで数か月、旅に出ている間もずっと、自宅のPCで自動売買プログラムを動かしていますが、いまのところ何の問題も発生していませんし、問題が発生しているという話も聞きません。
「kabuステーションでのログインが必要」と言う時点で、仮に再ログインが可能な仕様になっていたとしても、PCが限定されているので個人的には十分セキュアなように感じています。

セキュリティはもちろん大切ですが利便性も大切です。
再ログインはNG・自動ログアウトの時刻が変更不可と言うのであれば、自動ログアウトの頻度を「毎日」ではなく「毎週土曜日」にする等でも良いです。
もう少し柔軟に、良い落としどころが無いか、再検討していただければ幸いです。

**Comment by yasuyuki-nakazawa** [comment]
早朝に関してですが、およそ5時～6時となっております。
これはメンテナンス処理により、当該時刻にサーバ側とのコネクションが切断することが原因でもあります。
上述の理由から、強制ログアウトの時間を変更することは現状できかねる状況でございます。

要望としましては、継続的なAPIの利用と理解しております。
こちらに関しては、別途検討進めさせていただきます。本来的にはオープンAPIが利用かと存じますが、当APIをオープンAPIにするためには、多くの課題をクリアする必要があるため、現状の仕組みをとらせて提供いたしている次第です。

自動ログイン機能等、他案も考えられるとおもいますので、多角的に対応策は検討してまいります

**Comment by kichikun-w** [comment]
連続運用できないのでしばらく離れていたのですが、約１年が経過した今、この問題はどうなっていますでしょうか？

**Comment by yasuyuki-nakazawa** [comment]
自動ログインに関しては、見送りしております
これはカブステを利用しているために避けられない仕様となります
パスワードを保存していないために、ユーザーからのログインアクションを(セキュリティの観点でも)必須としております
この点はご了承くださいませ

**Comment by kichikun-w** [comment]
実現していただきたいのは「自動ログイン」ではなく「継続的なAPIの利用」であると言う事はご理解いただいているものと認識しております。
これについて「自動ログイン機能等、他案も考えられるとおもいますので、多角的に対応策は検討してまいります」
との事でしたが、その後、実現していただく方向には進んでいないのでしょうか？

**Comment by kichikun-w** [comment]
「本来的にはオープンAPIが利用かと存じますが、当APIをオープンAPIにするためには、多くの課題をクリアする必要があるため、現状の仕組みをとらせて提供いたしている次第です。」
「本来はオープンAPIのような形で個人向けのAPI解放できることが好ましいのですが、こちらに対しては、
超えるべき多くの課題があり、今回はいち早くAPIというソリューションをお客様にご提供するという趣旨で、カブステーションを介してインターフェース公開する方式をとらせていただいております。」
との事ですので、オープンAPI化する方向では進んでいるのですか？
この回答から半年～１年経過していますが、あと何年程毎朝ログインしなければならない状態が続くのですか？

**Comment by yasuyuki-nakazawa** [comment]
ご不便をおかけして申し訳ございません。
現状はカブステ用のインターフェース公開という整理で実現しております
ユーザーが作成されるプログラムの管理・監督の必要性等また、オープンにした際のシステム負荷等の課題があり、開放のお約束、時期感をお伝えすることができません
何卒、ご了承くださいませ
