### ISSUE TITLE
【質問】Excelアドイン　REGISTERSYMBOLにて銘柄登録後、初回BOARD情報取得が遅い件

### ISSUE THREAD

**Issue by hatsune39-108** [kabucom/kabusapi#643]
お世話になっております。
Excelアドイン　REGISTERSYMBOLにて、例えば最大登録数である５０件を登録後、BOARD関数で、
５０件の時価情報データを取得したとき、１件ごとのデータ取得に２～３秒（以上？）かかります。
これを５０件終わるまで、実行後、最初の１件目から再度、BOARD関数を実行すると、１件ごとでは、
ほぼ一瞬でデータ取得が終了します。
初回の５０件のデータ取得から、タイムラグが無い状態で、BOARD情報取得する方法はありますでしょうか？
５０件＊２＝１００件の銘柄を、交互に切り換えてのデータ取得をしたいと考えています。このため、
初回５０件のデータ取得が遅いと、実用にならない状況です。何らかの回避策はありますでしょうか？

**Comment by yasuyuki-nakazawa** [comment]
初回の情報取得については、銘柄を取得するためのリクエストをサーバ側に登録する作業が裏で行われています。
そのため、初回は一定の時間がかかります。２回目以降は高速に処理される仕組みとなっています。
扱える銘柄数が拡大できることで、当該銘柄の切り替え作業もないのですが、現状システムの負荷を勘案して現状の５０件の仕様となっております。

銘柄の追加は要望として多く上がっていることもあり、システム負荷状況を勘案の上拡大するかを検討させていただく流れとなります。

**Comment by hatsune39-108** [comment]
ご回答いただきありがとうございました。
その後、いろいろ試したところ、registersymbol、　unregistersymbol、　WebSocket　は、遅延が
ほとんど無いようでしたので、今回質問の所望動作は、WebSocket　にて、必要情報のみを取得する方向で、
検討してみます。　また、登録件数の拡大は、使い勝手が向上しますので、ぜひ検討お願いしたいです。
