### ISSUE TITLE
kabuステーションを起動しなくても本APIは使えますか？【質問】

### ISSUE THREAD

**Issue by hasegawa24** [kabucom/kabusapi#644]
kabuステーションを起動しなくても本APIは使えますか？

**Comment by hasegawa24** [comment]
pythonもしくはjavascriptでの使用を想定しております。

**Comment by yasuyuki-nakazawa** [comment]
当該ソリューションはカブステーションを介したAPIとなりますので、カブステーションを起動しない状態では利用できません。
所謂オープンAPIではなく、カブステーションがインターフェースを公開して個人利用するという形式をとっております為。

**Comment by hasegawa24** [comment]
ご丁寧にありがとうございます！理解しました。
