### ISSUE TITLE
【質問】注文約定紹介　/orders　について

### ISSUE THREAD

**Issue by john-banjirou** [kabucom/kabusapi#654]
質問、しつれいします。

/orders
この注文照会には、注文番号id、が必要です。

注文番号がない場合、注文照会の手立てはないのでしょうか？

また、一括の（たとえば、当日に、発注した注文の全件を照会する）方法は、ないのでしょうか？

**Comment by hishiharahaz** [comment]
注文番号id等のパラメータを指定しなければ全件取得できるかと思います。

**Comment by john-banjirou** [comment]
回答、ありがとうございます。

リファレンスへのその旨、明記、があると、よいと存じます。

**Comment by yasuyuki-nakazawa** [comment]
たしかに、リファレンスへのコメントが必要ですね。もうしわけございません
