### ISSUE TITLE
【質問】kabuステーションAPIのエクセルアドインのBOARD関数の使い方を教えてください

### ISSUE THREAD

**Issue by yusuketo** [kabucom/kabusapi#657]
BOARD関数の引数を以下のように書きました。

=BOARD(5570,1)

エクセルのA1セルに記載したら、
A1セル～BE１セルに、
０が一気に入力されました。

57個　0が並んでいますが、
これは何をあらわすのでしょうか？

kabuSTATION_API_function_sample.xlsx　の
時価情報（BOARD）の説明ページでも
横長の出力結果がでると記載がありますが、
こちらのサンプルでは、
銘柄コード、銘柄名、市場コード、市場名称、現値・・・と
87個の項目が記載されています。

３０コほどズレていますし、そもそも０しか出ませんでしたが、
本番用ログインで試したら、それっぽい値が出て、データ数も
サンプルで提示された項目数87個と一致しました。

なんとか出来ました！
お騒がせしました。

このコメントの消し方が分からないので、このままおいておきます。

**Comment by yasuyuki-nakazawa** [comment]
自己解決されたということで当方で後ほどクローズさせていただきます
