### ISSUE TITLE
【要望】先物ですが、micro対応をよろしくお願いします。

### ISSUE THREAD

**Issue by jisora** [kabucom/kabusapi#658]
先物ですが、micro対応をよろしくお願いします。

**Comment by yasuyuki-nakazawa** [comment]
商品拡張に関しては要望として承ります。
順次検討推進して参ります

**Comment by satosato125** [comment]
7/23(日)にマイクロ先物、ミニオプションへの対応をおこないます。

詳しくはこちらのお知らせをご確認ください。
https://github.com/kabucom/kabusapi/issues/716

**Comment by satosato125** [comment]
対応済みのため、クローズといたします。
