### ISSUE TITLE
【不具合】時価情報・板情報のBidとAskの値が逆ではないでしょうか?

### ISSUE THREAD

**Issue by kenaniki** [kabucom/kabusapi#659]
http://localhost:18080/kabusapi/board/{symbol}で取得できる"BidPrice"と"AskPrice"が逆な気がします。

**Comment by hori-ryota** [comment]
既出でドキュメントに反映されていますね

> [※①：レスポンスにある「Bid」と「Ask」は、本来の意味である「買気配」と「売気配」と逆になっております。実際に返却される値は日本語の説明に準じたものになりますので、ご注意いただきますようお願い申し上げます。ご迷惑をおかけしまして、誠に申し訳ございません。](https://kabucom.github.io/kabusapi/reference/index.html#operation/boardGet)

**Comment by kenaniki** [comment]
既出だったんですね。
教えてくださってありがとうございます。

**Comment by satosato125** [comment]
@hori-ryota 
コメントありがとうございます。

@kenaniki 
ご迷惑をおかけしており誠に申し訳ございません。

こちらはクローズとさせていただきます。
