### ISSUE TITLE
【質問】銘柄登録APIと為替情報についての質問

### ISSUE THREAD

**Issue by hiuchida** [kabucom/kabusapi#661]
銘柄登録解除のAPIリファレンスのパラメータの説明として、
『※為替銘柄を登録する場合、銘柄名は"通貨A" + "/" + "通貨B"、市場コードは"300"で指定してください。 例：'Symbol': 'EUR/USD', "Exchange": 300』
と書いてあったのですが、市場コード"300"は銘柄登録解除(/unregister)のみ指定可能で、銘柄登録(/register)では指定できないのでしょうか？

むかし指定してエラーとなった記憶がありますが、別の為替情報(/exchange)を実行するとAPI登録銘柄リストを1つ消費するので、為替情報のPUSH配信が対応しているのかどうかよく分からなくなりました。
現時点の仕様の確認をさせてください。

**Comment by yasuyuki-nakazawa** [comment]
確認いたしますのでお待ちくださいませ

**Comment by yasuyuki-nakazawa** [comment]
為替を指定してpush配信は現状できません
ご了承ください
