### ISSUE TITLE
【質問】自己解決：先物の逆指値注文で、ヒット後執行条件＝「成行」ができない

### ISSUE THREAD

**Issue by jisora** [kabucom/kabusapi#664]
先物の逆指値注文で、ヒット後執行条件＝「成行」の指定が、上手くできません。
「指値」なら、できます。
/////////////////////
（買いの場合）
執行条件	逆指値
トリガ価格	28900
以上／以下	以上
ヒット後執行条件	成行
ヒット後注文価格	0
発注結果（受付注文番号、メッセージ）	
{"Code":4001005,"Message":"パラメータ変換エラー - 詳細はkabuSログファイルを確認してください"}
///////////////////
WEBサイトからの逆指値注文でも、ヒット後執行条件として「成行」はそもそも存在しないので、
ドキュメントのミスかも知れません。
お気づきの点があれば、お教えください。

**Comment by jisora** [comment]
夜間、または日中しかできないのですね。
closeしてください。

**Comment by satosato125** [comment]
自己解決とのことですので、クローズとさせていただきます。
