### ISSUE TITLE
【質問】先物の引成や引指について、記述方法は？

### ISSUE THREAD

**Issue by jisora** [kabucom/kabusapi#665]
先物注文の引成（派生）や、引指（派生）については、逆指値と同様に、付加条件が必要だと思われます。
Pythonでの記述方法を教えて下さい。
ちなみに逆指値の付加条件は、以下の様にサンプルコード内に明記されています。
             'ReverseLimitOrder': {
                 'TriggerPrice': price,
                 'UnderOver': UnderOver_value,  # 1.以下 2.以上
                 'AfterHitOrderType': 2,  # 1.成行 2.指値
                 'AfterHitPrice': price
             }

**Comment by jisora** [comment]
18 | 引成（派生）※TimeInForceは、「FAK」のみ有効 | price= 0
28 | 引指（派生）※TimeInForceは、「FAS」のみ有効 | price=発注したい金額

レファレンス記述の設定では、注文できませんでした。

**Comment by satosato125** [comment]
引成と引指の場合、Exchangeは日中(23)、夜間(24)のいずれかを指定する必要がございます。
Exchangeが日通し(2)となっていないか、ご確認いただけますでしょうか？

また、パラメータ指定のサンプルを記載いたしますので、併せてご確認ください。
// 引成
{
"Symbol":"168060019",
"Exchange":"23",
"TradeType":"1",
"TimeInForce":"2",
"Side":"2",
"Qty":"1",
"FrontOrderType":"18",
"Price":"0",
"ExpireDay":"0",
"Password":"****************"
}

// 引指
{
"Symbol":"168060019",
"Exchange":"23",
"TradeType":"1",
"TimeInForce":"1",
"Side":"2",
"Qty":"1",
"FrontOrderType":"28",
"Price":"28000",
"ExpireDay":"0",
"Password":"****************"
}

**Comment by satosato125** [comment]
当件につきまして、リファレンスの記述が不足しており、申し訳ございません。
後日、リファレンスの修正をさせていただきます。

**Comment by jisora** [comment]
ありがとうございました。注文できました。

引成や引指は、ザラバとは無関係に
「プレ・クロージングの時間帯に、指値や成行の注文を行う」
という解釈で良いですか？

**Comment by yasuyuki-nakazawa** [comment]
この引成、引指は取引所の執行条件となりますので、注文は取引所側で待機してクロージングセッションのタイミングでマッチングされるものと思慮いたします。

プレ・オープン、プレ・クロージングは板寄せするまでの注文受付時間となります。新規・訂正・取消の各注文を受け付けますが、マッチングは行われません
https://faq.kabu.com/s/article/k000610

**Comment by satosato125** [comment]
リファレンスへの記載追加により、クローズといたします。
