### ISSUE TITLE
【質問】EXCELでBOARD関数だけがエラー(#VALUE!)になります

### ISSUE THREAD

**Issue by acct8686** [kabucom/kabusapi#668]
サンプルファイルで動作確認している段階なのですが、kabuSTATION_API_function_sample.xlsx の時価情報シートで、BOARD関数だけが値を取得できません。その他のSYMBOL , WALLET.CASH , EXCHANGE , WEBSOCKET 等は正常に値が取得できました。サンプルファイルの数式をコピーして入力しているので、数式間違いではないと思います。

当方の手順例
API本番用でログイン→API登録銘柄リストの登録→登録した銘柄の値をBOARD関数で呼び出すと#VALUE! が返ってきます。
=BOARD(8306,1) 
を入力（セル参照でも結果は同じ）すると #VALUE! になります。
CTRL+SHIFT+ENTERで配列数式入力してもダメでした。

ご教授お願い致します。

**Comment by acct8686** [comment]
自己解決いたしました。おそらく今後同様の方が現れると思いますので、原因を書いておきます。
EXCELアドインで、岡三オンライン証券のRSSを登録している場合、RSS関数にkabuSTATIONアドインと同名の「 =BOARD関数 」があります。同名の関数なので内部で競合しているようです。岡三オンラインRSSの登録を解除して、再度カブステAPIにログインすると、正常にBOARD関数の値の読込が出来ました。
以上です。

**Comment by satosato125** [comment]
@acct8686 
自己解決とのこと、承知いたしました。
また、原因についても共有いただきまして、誠にありがとうございます。
後ほどよくある質問ページへ転載させていただきます。
