### ISSUE TITLE
【要望】PUSH通知で注文件数を取得したい

### ISSUE THREAD

**Issue by hysdsk** [kabucom/kabusapi#669]
既出でしたらすみません。

Kabuステのフル板に表示できる「件数」をPUSH通知APIでも取得できると嬉しいです。
ご検討よろしくお願いいたします。

**Comment by yasuyuki-nakazawa** [comment]
Pushで取得できるのは現状リアルタイムの時価情報系となっております。
注文件数に関しても現状は取得できません。
フル板自体の取得は厳しい部分もございますが、例えば上下10本の時価情報に加えた注文件数というのでも実用に耐えますでしょうか。

**Comment by hysdsk** [comment]
@yasuyuki-nakazawa 
ご回答ありがとうございます。

> 例えば上下10本の時価情報に加えた注文件数

はい、上下10本のみ（現状取得できる気配情報）の注文件数だけでも利用価値があると思っております。

**Comment by hysdsk** [comment]
@yasuyuki-nakazawa 
本件、要望として伝わったと思いますので、クローズで問題ないです。
