### ISSUE TITLE
【要望】約定後、必ず逆指値を入れているのですが、これを自動化できるのでしょうか？

### ISSUE THREAD

**Issue by yozoraniyoukiss** [kabucom/kabusapi#67]
約定後、必ず逆指値をUターン注文で入れているのですが、APIを使ってこの作業を自動化できるのでしょうか？
できないのであれば、できるようにして頂けると助かります。宜しくご検討をお願い致します。

**Comment by yasuyuki-nakazawa** [comment]
現在、逆指値を初めとした自動執行条件の設定に対応しておりません。
逆指値は要望も高いこともあり、対応として検討させて頂きます

**Comment by yozoraniyoukiss** [comment]
楽しみにしております。

注文方式に逆指値の追加だけでなく、Uターン注文か、簡単に約定に反応して自動注文できるようにしてくれると使い勝手が向上し、個人投資家全体の損益に＋の影響をもたらせると思います。

宜しくお願い致します。
