### ISSUE TITLE
【質問】単位株数の取得について

### ISSUE THREAD

**Issue by portal-kidsprograming** [kabucom/kabusapi#672]
現物の注文発注を行った際の応答として
{'Code': 1002, 'Message': '数量は単位株数の倍数で入力してください'}
が回答されました。

この「単位株数」についてなのですが、これは「銘柄情報(/symbol/{symbol}」の応答項目である、[売買単位](TradingUnit)が「単位株数」にあたる認識で正しいでしょうか？

**Comment by satosato125** [comment]
はい、その認識で相違ございません。

**Comment by portal-kidsprograming** [comment]
ご回答ありがとうございます。理解いたしました。
クローズさせていただきます。

**Comment by portal-kidsprograming** [comment]
ありがとうございます、了解しました。
