### ISSUE TITLE
【質問】kabusapiのサンプルで GenerateTokenに関するエラー

### ISSUE THREAD

**Issue by sigebo** [kabucom/kabusapi#673]
kabsapiのｃ＃のサンプルをVisualstadio2022communityで使い始めようとしています。
ライセンスはまだですが、kabustationは起動しています。

CSharpフォルダの中にあるKabusapi_Board.csをコピーして、実行ボタンを押す前に、
エラーが表示されます。

エラー	CS0103	現在のコンテキストに 'GenerateToken' という名前は存在しません	test1	C:\Users\qhtsi\source\repos\test1\test1\Program.cs	15	アクティブ

このエラーは何かライブラリーが不足していることなので、ライセンスはまだですが、その前の問題と解釈しましたが、正しいでしょうか。
そうだとして、何が不足しているのでしょうか。
また、このあたりに参考になるドキュメントもわかりません。C#は初めてです。
なお、サイト記事でプロジェクトからNuGetからNewtonsoft.Jsonをインストールしましたが、その必要性のこともよくわかりません。

アドバイスいただければ幸いです。

using Newtonsoft.Json;
using System;
using System.Net.Http;

namespace CSharp_sample
{
    class Kabusapi_Board
    {
        static void Main(string[] args)
        {
            string Symbol = "8306";
            string Exchange = "1";
            var url = "http://localhost:18080/kabusapi/board" + "/" + Symbol + "@" + Exchange;
            string token = GenerateToken.GetToken();
            try
            {
                var client = new HttpClient();
                var request = new HttpRequestMessage(HttpMethod.Get, url);
                request.Headers.Add("X-API-KEY", token);
                HttpResponseMessage response = client.SendAsync(request).Result;
                Console.WriteLine("{0} \n {1}", JsonConvert.DeserializeObject(response.Content.ReadAsStringAsync().Result), response.Headers);
                Console.ReadKey();
            }
            catch (HttpRequestException e)
            {
                Console.WriteLine("{0} {1}", e, e.Message);
                Console.ReadKey();
            }
            catch (Exception ex)
            {
                Console.WriteLine("{0} {1}", ex, ex.Message);
                Console.ReadKey();
            }

            Console.ReadKey();
        }
    }
}

**Comment by sigebo** [comment]
pythonの場合に下記のサンプルがありましたが、
これは、GenerateToken.GetToken();に対応するように見えます。
そうしますと、この部分のコードが必要と思われますが、その部分が無いためのエラーと推測されます。この部分の記述例がないのでしょうか？

import urllib.request
import json 
host_ = '18080' # 本番環境
pass_ = 'KABUSTATIONで設定時に決めたパスワード'

# 認証用のトークンを作成する関数
def generate_token():

    obj = {'APIPassword': pass_}
    json_data = json.dumps(obj).encode('utf8')
    url = f'http://localhost:{host_}/kabusapi/token'
    req = urllib.request.Request(url, json_data, method='POST')
    req.add_header('Content-Type', 'application/json') 

    try:
        with urllib.request.urlopen(req) as res:
            content = json.loads(res.read())
        token_value = content.get('Token')
        return token_value

    except urllib.error.HTTPError as e:
        print(e)
        return e

# 関数を実行してトークンを発行
token = generate_token()
print(token)

**Comment by satosato125** [comment]
C#は初めてとのことですので、恐れ入りますが、特定のcsファイルを単独で開かれている状態でしょうか？
ファイル単独ではなく、ソリューションとしてC#のサンプル全体を読み込むようにして、お試しいただきたいです。

例えばエラーにある「GenerateToken」は下記ファイルに定義されているclassです。
https://github.com/kabucom/kabusapi/blob/master/sample/C%23/CSharp/GenerateToken.cs

**Comment by sigebo** [comment]
ご返事ありがとうございます。
ご案内の通りのclassを先のコードの前に置くと、そのエラーはなくなり、サーバーに接続できないとの、もっともなエラーとなりましたので、当面の環境は確認できたかと思います。

ソリューションとしてC#のサンプル全体を読み込むようにしてとのことですが、GIthubのどの部分をソリューションとして最初に取り込めばよいでしょうか。
ｃ＃は初めてなので基本的な質問で申し訳ないですが、よろしければご教授をお願いできませんか。

**Comment by satosato125** [comment]
サンプルでは、Visual Studioで下記のslnファイルからソリューションを開くようにしますと、slnファイルと同じ階層にあるCSharpフォルダ全体を参照できると思います。
https://github.com/kabucom/kabusapi/blob/master/sample/C%23/CSharp_sample.sln

**Comment by sigebo** [comment]
kabusapiサンプル全体のソリューションを開くため、次の操作をしました。

Githubのレポジトリの緑色の<>codeをクリック
DownloadZIPをクリックして、ローカルのkabysapiフォルダにダウンロード、解凍。
そのフォルダには
.github
ExcelAddin
ptal
reference
sample
Licence
readme.doc
ができます。

そこからsample\C#を開くと
CSharp
.gitignore
00.Readme.txt
CSharp_sample.sln
があるので、

VS2022起動
実行する操作を選択してくださいページに移る
プロジェクトやソリューションを開くを押し、
先ほどの　CSharp_sample.sln　を開く。
ソリューションエクスプローラペインには
CSharp_sample
propaties
参照
__App.config
__GenerateToken.cs
Kabusapi_APISoft.Linit.cs
以下program.csまで２０個ばかりのモジュールがあります。

この次がわからないのですが、
この状態でビルドからソリューションのビルドをすると

エラー	CS2001	ソース ファイル 'C:\kabu_API\kabusapi-C-v1.1.0\sample\C#\CSharp\GenerateToken.cs' が見つかりませんでした。	CSharp_sample	C:\kabu_API\kabusapi-C-v1.1.0\sample\C#\CSharp\CSC	1	アクティブ

となります。
ソリューションエクスプローラのGenerateToken.csには小さな赤×印が付いています。
これから、GenerateToken.csが未解決に見えます。

解決するにはどうすれば良いでしょうか。あるいはどの操作が問題なのでしょうか。
一応ソリューショ（.slnファイル）を開いたつもりなのですが・・・。

直接kabsapiの質問でなく、VSの操作に関することになってしまい、ご教示頂けるか疑問なのですが、
ご説明願えれば幸いです。

**Comment by satosato125** [comment]
いえいえ、こちらこそ失礼いたしました。

上図のエラー一覧に表示されているメッセージを見ますと、やはりcsファイルが所定のフォルダにないというエラーのように見えます。
各モジュールのパスはcsprojファイル内に定義されています。
もし仮にcsprojファイルのパスが変更されてしまっているような場合には、エラーメッセージでもそちらのパスを指しますので、プロジェクトファイルの参照がおかしいわけではないと思います。

@sigebo 様の環境ですと、
C:\kabu_API\kabusapi-C-v1.1.0\sample\C#\CSharp\
のフォルダに
GenerateToken.cs
が存在しており、ファイル名も一致しているか、ご確認をお願いいたします。

**Comment by sigebo** [comment]
そうですね。C:\kabu_API\kabusapi-C-v1.1.0\sample\C#\CSharpフォルダに、GenerateToken.csファイルがあるか調べればよいのですね。
ありませんでしたので、githubの展開を見ると、ありますので、やはりダウンロード解凍がまずいかと調べますと、
やはり解答が正しくなかったです。
それで、やり直しますと、エラーはなくなり、サーバ接続エラーが確認できました。

ｍｓＶＳの使い方も勉強になりました。ありがとうございました。
