### ISSUE TITLE
【質問】流量制限について

### ISSUE THREAD

**Issue by sigebo** [kabucom/kabusapi#677]
この掲示板の過去ログを見ますと、流量制限があることがわかりました。
・流量制限を超えると、どんな状況（どんなレスポンス）になりますか。
・この事項についてのサイト内での記述場所
・次のような処理を考えています。
　　銘柄１の板情報（中心値がわかればよい）
　　銘柄２の板情報（中心値がわかればよい）
　　（上記２ステップを反復。条件を満たすと次に進む）
　　銘柄１の現在ポジションの有無の確認
　　銘柄２の現在ポジションの有無の確認
　　銘柄１の注文
　　銘柄２の注文
　　銘柄１の注文結果の確認
　　銘柄２の注文結果の確認

・これらを手動によるよりもはるかに高速に行いたいのですが、それぞれを一件として、５件/秒以内であることが必要になるのですか。
　　ただし、この処理は１日に数回程度になります。　

・同様の処理をkabu.com.apiならば、どれくらい高速になりますか。

・一つの対策として、カブステの表示を最小限にして、カブステからのトラフィックを最小限にして、その負荷軽減分をAPIに回すとかは効果がありますか。
　　あるいはwindowの最小化でデスクトップに表示しないとか（これではバックで動くので無意味かもしれない。PCの負荷軽減にはなるが）

**Comment by yasuyuki-nakazawa** [comment]
>・流量制限を超えると、どんな状況（どんなレスポンス）になりますか。
実行回数エラーが返ります。
当件に関しての記載がリファレンス上明示されていない様に見受けられるため、改善図ります

**Comment by yasuyuki-nakazawa** [comment]
＞・これらを手動によるよりもはるかに高速に行いたいのですが、それぞれを一件として、５件/秒以内であることが必要になるのですか。
流量制限は秒5件を超過する場合にエラーということですので、秒５件内であれば問題ありません。

>・同様の処理をkabu.com.apiならば、どれくらい高速になりますか。
カブコムAPIに関しても流量制限はありますが、流量はカブステーションAPIよりも緩和されております。

要望としては短時間で一気に処理がしたいということでしょうか？

**Comment by sigebo** [comment]
>カブコムAPIに関しても流量制限はありますが、流量はカブステーションAPIよりも緩和されております。
高速であることは、お聞きしていますが、
５件/秒以内に対応した、カブコムAPIの具体的な数値が知りたいのです。おおまかな比率で良いです。

>要望としては短時間で一気に処理がしたいということでしょうか？
トラフィックは短時間であるが、沢山の処理（銘柄数）というより、条件を満たすかどうかの判断を高速に行いたいのです。
前述の予定した処理では、現状判断が２．５回/秒になりますので、これを少なくとも判断を１０回/秒くらいにしたいところです。流量は２０件/秒になります。　
念のためですが、銘柄を沢山一気に処理するのではありません。注文処理は２個を一回だけです。集中するトラフィックの期間はせいぜい１０秒くらいです。
おそらく多くのその処理を行いたいユーザ達は、同じ期間に集中します。現状ではカブコムAPIからのトラフィックに対してかなり不利になりそうです。

**Comment by satosato125** [comment]
kabuステAPIとkabu.com APIではシステム的に大きくことなりますので、kabu.com APIについて一概にお答えすることができかねますこと、ご了承ください。
なお、kabu.com APIについては接続契約などもございますので、下記のページをご一読いただけますと幸いです。
https://kabu.com/api/kabucom_api.html

kabuステAPIの流量制限につきましては、発注系のインターフェイスでは秒間5件以内、情報系のインターフェイスは秒間10件以内となっております。
想定されている処理内容ですと、最初の板情報取得の部分は情報系にあたりますので、秒間10件以内でしたらリクエスト可能です。その後の2件の発注については、情報系とは別の発注系となります。注文処理は2個を1回だけ、とのことですので、秒間5件の流量制限にはかからないもの、と思慮いたします。

また、kabuステAPIの流量制限はサーバ側の過負荷を避けるために設けてさせていただいている制限であり、kabuステやお使いのPCの性能によるものではございません。ご質問にございますような、kabuステ本体の表示やトラフィックには依らないものとなっております。

**Comment by sigebo** [comment]
情報系と注文系で流量制限値がことなることなど、大体わかりました。
・情報系のapiが１０件/秒で実行されている状況中に、注文系APIを５件/秒で平行して実行できますか。

**Comment by satosato125** [comment]
はい、情報系と発注系の制限は別となっておりますので、並行での実行が可能です。

**Comment by sigebo** [comment]
ご説明ありがとうございました。質問はすべてわかりました。
