### ISSUE TITLE
【質問】流量制限について（再投稿）

### ISSUE THREAD

**Issue by sigebo** [kabucom/kabusapi#679]
この掲示板の過去ログを見ますと、流量制限があることがわかりました。
・次のような処理を考えています。
　　銘柄１の板情報（中心値がわかればよい）
　　銘柄２の板情報（中心値がわかればよい）
　　（上記２ステップを反復。条件を満たすと次に進む）
　　銘柄１の現在ポジションの有無の確認
　　銘柄２の現在ポジションの有無の確認
　　銘柄１の注文
　　銘柄２の注文
　　銘柄１の注文結果の確認
　　銘柄２の注文結果の確認

・これらを手動によるよりもはるかに高速に行いたいのですが、それぞれを一件として、５件/秒以内であることが必要になるのですか。
　　ただし、この処理は１日に数回程度になります。　

・同様の処理をkabu.com.apiならば、どれくらい高速になりますか。

・一つの対策として、カブステの表示を最小限にして、カブステからのトラフィックを最小限にして、その負荷軽減分をAPIに回すとかは効果がありますか。
　　あるいはwindowの最小化でデスクトップに表示しないとか（これではバックで動くので無意味かもしれない。PCの負荷軽減にはなるが）

>カブコムAPIに関しても流量制限はありますが、流量はカブステーションAPIよりも緩和されております。

高速であることは、お聞きしていますが、
５件/秒以内に対応した、カブコムAPIの具体的な数値が知りたいのです。おおまかな比率で良いです。

>要望としては短時間で一気に処理がしたいということでしょうか？

トラフィックは短時間であるが、沢山の処理（銘柄数）というより、条件を満たすかどうかの判断を高速に行いたいのです。
前述の予定した処理では、現状判断が２．５回/秒になりますので、これを少なくとも判断を１０回/秒くらいにしたいところです。流量は２０件/秒になります。　
念のためですが、銘柄を沢山一気に処理するのではありません。注文処理は２個を一回だけです。集中するトラフィックの期間はせいぜい１０秒くらいです。
おそらく多くのその処理を行いたいユーザ達は、同じ期間に集中します。現状ではカブコムAPIからのトラフィックに対してかなり不利になりそうです。

**Comment by satosato125** [comment]
返答に時間をいただきまして、申し訳ございません。
元のissueにて回答いたしておりますので、こちらをご参照いただきたく存じます。
https://github.com/kabucom/kabusapi/issues/677

こちらのissueについては内容重複のため、クローズとさせていただきます。

**Comment by sigebo** [comment]
すでに回答いただいた分につては、再投稿では除外してあります。
この再投稿では、先に頂いた回答では、わかりかねる部分につて、質問いたしました。

**Comment by sigebo** [comment]
投稿の形式がまずければご指摘ください。さらにご説明頂く必要が無いと思ったときに、closewithcommentを押すものと思っておりました。

**Comment by sigebo** [comment]
最初の投稿にご返事いただいたこと確認できました。
