### ISSUE TITLE
【質問】エクセルアドインからの発注について

### ISSUE THREAD

**Issue by BlackTiger4649** [kabucom/kabusapi#68]
kabuSTATION_API_ORDER_sample.xlsmの発注において躓いています。エラーメッセージは「発注が有効になっていません」とのメッセージです。
https://gyazo.com/f680414daceefd2706a1be1f29fe3ba4

MarginTrading()の関数をステップインしてみると、「ノードの各情報を取得（検索指定）」のあたりで問題が生じているようです。xmlOrderはゼロになっているし、本番用のポート（18080）を設定しているにも拘らず、PortNo＝18081になっているし、xmlToken=""になっています。

  ' ノードの各情報を取得（検索指定）
  Set xmlOrder = XMLDocument.SelectSingleNode("//settings/setting1/OrderButton")
  Set xmlPort = XMLDocument.SelectSingleNode("//settings/setting1/PortBox")
  Set xmlToken = XMLDocument.SelectSingleNode("//settings/setting1/ApiToken")
  
  OrderControl = xmlOrder.Text
  PortNo = xmlPort.Text
  ApiToken = xmlToken.Text

コードの最初のところで躓いていますが、どのように解決すれば宜しいでしょうか？宜しくお願いします。

**Comment by BlackTiger4649** [comment]
因みに、kabuSTATION_API_PUSH_sample.xlsxとkabuSTATION_API_function.sample.xlsxのシートでは概ねちゃんとアドインは動いています。

**Comment by yasuyuki-nakazawa** [comment]
画面のリボン部分にて本番を選択頂き、ログインは可能でしょうか？

**Comment by BlackTiger4649** [comment]
ログインは可能です。本番用ログインで緑色のマークになっています。勿論、発注制御、更新制御も緑色のマークにしています。

**Comment by yasuyuki-nakazawa** [comment]
アドインの設定で実行環境が「本番」になっていないということはないでしょうか
検証のポートにアクセスするケースとして考えられるのは、その選択くらいしかないのですが。

**Comment by BlackTiger4649** [comment]
ご回答の感じからこちらに問題があるかと思い、色々と試してみました。
そして結果的に発注までこぎつけました。
当初はExcel2013 32bitでエラーとなったので、最新のアドインをダウンロードして、Excel2019 32bitで試してみたらうまくいきました。Excel2016 32bitで試してみてもうまくいきました。最後にもう一度、Excel2013 32bitで試してみたらうまくいきました。原因はアドインを最新にしたぐらいしか分かりませんが、結果的にうまくいって良かったです。
どうもありがとうございました。

**Comment by yasuyuki-nakazawa** [comment]
了解しました。
以後、同事象が発生している場合には、アドインの再インストールを案内してみます。
情報の連携ありがとうございました。
