### ISSUE TITLE
【質問】APIによる指値の買いが約定した後、APIで残高照会すると price の値が買ったときの Price と異なる

### ISSUE THREAD

**Issue by Paynomono** [kabucom/kabusapi#681]
昨日、APIで指値の買い注文をしました。

■ 注文時のパラメーター
Symbol				3940
Exchange				1
SecurityType			1
Side					'2'
CashMargin			1
DelivType			2
FundType			'02'
AccountType			4
Qty					100
FrontOrderType		20
Price				119

今朝約定したので、APIで約定情報・残高情報を確認したところ、
約定情報では、Price は 119 でした。
ただ、表題の通り、なぜか残高では Price が 120 になっていました。
これはなぜでしょうか？
（ API 経由で購入していない他の銘柄では、購入時の単価が正しく入っていました ）

**Comment by satosato125** [comment]
残高照会では、約定単価ではなく平均取得単価が表示されます。

ご参考までに、弊社PCサイトの説明をご覧いただけますと幸いです。
https://kabu.com/item/stock/account/management.html
https://kabu.com/kabuyomu/money/73.html

**Comment by Paynomono** [comment]
回答ありがとうございました！
解決しました。

**Comment by satosato125** [comment]
ご確認ありがとうございました。
解決済みとのことですので、クローズとさせていただきます。
