### ISSUE TITLE
【要望】信用残情報とコーポレートアクション情報の取得

### ISSUE THREAD

**Issue by Shikibe** [kabucom/kabusapi#683]
はじめまして。
各銘柄の**信用買残**、**信用売残**の情報を取得できるようにしてほしいです。
楽天証券のマーケットスピード２（RSS2）は信用残情報が取れます。
KabuステーションAPIでもぜひお願いしたいです。
あと、できれば株式分割・併合の情報も取得できないでしょうか？

**Comment by yasuyuki-nakazawa** [comment]
コーポレートアクションの情報は現状カブステ自体でも取得できていない（アクション後の結果は反映されている）ので、取得はできません。
信用買残、売残に関しては要望として理解いたしました
