### ISSUE TITLE
【質問】kabu.com API（法人向け）について

### ISSUE THREAD

**Issue by taskcrypto** [kabucom/kabusapi#688]
kabu.com APIを利用したアプリケーション開発を検討しているのですが、審査基準やAPI仕様をより詳しく知りたいのですが、相談窓口はあるでしょうか？
公開されている情報だけみると、法人口座を作って企画書を提出して承認されれば、面談を受けた後にAPIの制作の流れのようですが、情報が少なすぎて最低限どのような準備が必要かがよくわかりません。
小さな支援ツールから作り始めて、需要に応じて拡大していくようなものでも承認される可能性はあるでしょうか？

**Comment by yasuyuki-nakazawa** [comment]
審査基準は非公開となっております
利用に当たっては、お問い合わせ先に関しては、以下をご参照ください
https://kabu.com/support/detail.html#anc04

**Comment by taskcrypto** [comment]
ありがとうございます。クローズしてください。
