### ISSUE TITLE
【質問】PUSH配信で取得できるティック情報について

### ISSUE THREAD

**Issue by hysdsk** [kabucom/kabusapi#689]
PUSH配信でティック情報を取得して分析をしているのですが、KabuステAPIで同じことをしている方と一部データの比較をしたところ、端末によって取得できているデータの量が異なるように見えました。

PUSH配信のドキュメントには以下のように記載がありますが、この「値が更新される際」というのは端末によって異なるのでしょうか？また、異なる場合、どういった事象がトリガーとなっているか、ご教示いただけますでしょうか。
https://kabucom.github.io/kabusapi/ptal/push.html
> ※PUSH配信は、値が更新される際に配信されます。

**Comment by yasuyuki-nakazawa** [comment]
Pushに関しては、以下のフロー（概要）でデータを取得します
①取引所→②サーバー→③クライアント(kabuS)→④作成アプリ

この時、②-③間でデータの間引き処理が行われます。
※数百ミリSec間でデータを集約して送信する形をとっております

このため、クライアントによってデータに差異が発生しているものと思慮いたします。

**Comment by hysdsk** [comment]
@yasuyuki-nakazawa 
ご回答ありがとうございます。
間引きされる仕様とのこと理解しました。

知見のために二点追加で質問させていただきたいのですが、

> ①取引所→②サーバー

①と②の何れかがアローヘッドにあたるものでしょうか？①をアローヘッドとしたとき、②は御社のサーバになりますでしょうか？

> ②-③間でデータの間引き処理が行われます。

③に到達するデータは間引き後のデータになりますでしょうか？そうであればKabuステのT&Sの情報も端末によって誤差があるという理解でよろしいでしょうか？

以上です、よろしくお願いいたします。

**Comment by yasuyuki-nakazawa** [comment]
@hysdsk 
①がArrowheadのイメージです。
②は当社サーバとなります。

③に到達する時には間引き後のデータとなりますが、T&Sに関しては間引きは実施されていません。
間引かれる情報としては、リアルタイム配信される時価情報とそれに付随する各種情報です。
T&Sのような情報は間引きはせずに別途配信しております。

**Comment by hysdsk** [comment]
@yasuyuki-nakazawa 
ご説明ありがとうございます、システム構成と間引きについて理解が深まりました。
本件解決しましたので、クローズさせていただきます。
