### ISSUE TITLE
【質問】APIレスポンス構成要素について

### ISSUE THREAD

**Issue by kabucomapi** [kabucom/kabusapi#69]
お世話になります。
APIレスポンス構成要素について、その内容等で不明な点がありましたので、次のとおり質問させていただきます。
次の３分類に分けて質問しています。トレードの手法に大きな影響を与えそうな項目もございますので、ご回答いただけると助かります。
よろしくお願いいたします。

[項目の内容（意味）がわからない]：項目が示している内容（意味）がわからないもの
[項目の値が何に対応するのかわからない]：項目のとる値が、何らかの状態に紐づいていると思われるが、その対応がわからないもの
[その他]：その他の質問

注文約定照会
[その他]
SeqNum（シーケンス番号）は何をトリガーとして発生するのかわかりません。
[項目の内容（意味）がわからない]
Commission
CommissionTax
[項目の値が何に対応するのかわからない]
State
OrderState
OrdType
MarginTradeType

残高照会
[その他]
ExecutionIDが、現物ではnullとなる理由がわかりません
[項目の内容（意味）がわからない]
HoldQty

時価情報・板情報
[その他]
BidQtyとは売板に対して、直近に買われた枚数のことでしょうか？
[項目の内容（意味）がわからない]
MarketOrderSellQty
MarketOrderBuyQty
[項目の値が何に対応するのかわからない]
CurrentPriceChangeStatus
BidSign
AskSign

銘柄情報
[項目の内容（意味）がわからない]
KCMarginBuy
KCMarginSell
MarginBuy
MarginSell
[項目の値が何に対応するのかわからない]
BisCategory
PriceRangeGroup

取引余力
[その他]
銘柄指定の余力情報と、指定なしの余力情報の違いが分かりません。
[項目の内容（意味）がわからない]
ConsignmentDepositRate
CashOfConsignmentDepositRate

**Comment by yasuyuki-nakazawa** [comment]
回答いたします。
項目の値が何に対応するかというものはリファレンスに記載してあるとおりです。
その記載内容として不明ということであれば、別途ご質問いただけますよう、お願いいたします。

**注文約定照会**
・SeqNum（シーケンス番号）は何をトリガーとして発生するのかわかりません。
　→　auカブコム側の注文システムが採番しています。通番であるとは限りませんが、大小による順序は保たれています。

**残高照会**
・ExecutionIDが、現物ではnullとなる理由がわかりません
　現物取引の残高であるためです。現物取引ではExecutionIDとExecutionDayは、nullになります。
　現物の各残高は、合算され管理されるためExecutionIDとExecutionDayを表示できないことが理由となります。

**時価情報・板情報**
・BidQtyとは売板に対して、直近に買われた枚数のことでしょうか？
　→　リファレンスに記載のとおりです。最良気配数量のこととなります

・[項目の内容（意味）がわからない]
　MarketOrderSellQty：リファレンスに記載のとおりです。買い成行数量となります
　MarketOrderBuyQty：リファレンスに記載のとおりです。売り成行数量となります
[項目の値が何に対応するのかわからない]
CurrentPriceChangeStatus
BidSign
AskSign

**銘柄情報**
・[項目の内容（意味）がわからない]
　下記項目に関してはリファレンスを更新して補完させて頂きます
　KCMarginBuy：一般信用買建フラグ。※trueのとき一般信用買建可能
　KCMarginSell：一般信用売建フラグ。※trueのとき一般信用売建可能
　MarginBuy：制度信用買建フラグ※trueのとき制度信用買建可能
　MarginSell：制度信用売建フラグ※trueのとき制度信用売建可能

・[項目の値が何に対応するのかわからない]
　BisCategory：業種コード名
　PriceRangeGroup：こちら、別途開示させて頂きます

**取引余力**
・銘柄指定の余力情報と、指定なしの余力情報の違いが分かりません。
→　銘柄指定なしの場合に表示される値は口座の可能額となります。
　　銘柄指定ありの場合に表示される値は、選択された銘柄に対する可能額となります。

・[項目の内容（意味）がわからない]
　ConsignmentDepositRate：リファレンス記載のとおりです。委託保証金率
　CashOfConsignmentDepositRate：リファレンス記載のとおりです。現金委託保証金率

**Comment by kabucomapi** [comment]
リファレンスの確認不足でした。
大変ご迷惑をおかけして申し訳ありません。
