### ISSUE TITLE
【質問】「依頼中」の時の、ステータスなど

### ISSUE THREAD

**Issue by john-banjirou** [kabucom/kabusapi#690]
質問失礼します。

APIより注文をした際のことです。
注文約定照会ウィンドウの、状態の欄が、「依頼中」と表示されるときがあります。

この時、/ordersにより得られる、該当注文は、どんな値を持っているのでしょうか？
たとえば、orderstateの値がどうとか、priceがどうとか。
（他と、判別するため、特徴的ものが知りたいです）

たまーにですが、この依頼中となって、立て続けに注文が重複して出されてしまいます。
なので、依頼中の状態を判別して、それを防ぎたいと考えております。

よろしくおねがいします。

**Comment by satosato125** [comment]
kabuステーションの注文約定照会にて「依頼中」と表示されるのは、取引所へ注文を送信中の状態となります。
kabuステーションAPIの注文約定照会（/orders）ではState、またはOrderStateが「2 : 処理中（発注送信中）」の値をとります。
