### ISSUE TITLE
【質問】新規発注の際、ExchangeでSORを指定したいのですが選択肢がありません。

### ISSUE THREAD

**Issue by tomomot6** [kabucom/kabusapi#691]
信用取引の新規発注をする際に、ExchangeでSORを指定したいのですが、リファレンスを見てもSORに該当する選択肢がありません。
SORを指定したいときは、どうすればよいのでしょうか。教えてください。よろしくお願いします。

**Comment by satosato125** [comment]
申し訳ございませんが、現在、kabuステーションAPIではSORを選択することができません。

**Comment by tomomot6** [comment]
ありがとうございます。承知いたしました。
