### ISSUE TITLE
【質問】APIの流量制限について

### ISSUE THREAD

**Issue by hysdsk** [kabucom/kabusapi#692]
[REST API リファレンス](https://kabucom.github.io/kabusapi/reference/index.html)にて
> 情報系のリクエストは秒間10件ほどの流量制限を設けています。

という記載がありますが、エンドポイントごとに制限をかけているのでしょうか？
例えば、時価情報・板情報と残高照会は共に情報系のリクエストという認識ですが、合わせて10rpsに抑える必要があるのか、エンドポイントごとで10rpsなのかが知りたいです。
また、

> 発注系のリクエストは秒間5件ほどの流量制限を設けています。

とあるように、情報系と発注系とでは制限の流量が異なるため、それぞれ独立した制限だという理解であっていますでしょうか？

以上です、ご確認よろしくお願い致します。

P.S.
他にもIssueを起票させていただいておりますので、ご確認よろしくお願いします。
https://github.com/kabucom/kabusapi/issues/created_by/hysdsk

**Comment by satosato125** [comment]
情報系の流量制限はエンドポイントごとではなく、共通のものとなります。
ご提示いただいた例ですと、時価情報・板情報と残高照会は合わせて秒間10件とする必要があります。

発注系と情報系の流量制限につきましては、ご認識の通りで間違いございません。
それぞれ別に件数をカウントしておりますので、独立した制限となっております。

いろいろと返答にお時間をいただいておりまして、申し訳ございません。
順次、回答してまいりますので、少々お待ちいただけますと幸いです。

**Comment by hysdsk** [comment]
@satosato125 
ご教示ありがとうございます。
不明点がクリアになったため、本件クローズいたします。
