### ISSUE TITLE
【質問】日経平均指数

### ISSUE THREAD

**Issue by myuu1014** [kabucom/kabusapi#696]
apiを使って、日経平均指数を取得したいです。
先物は取得できますが、指数は取得不可でしょうか。
23/6/2ですと31524.22 といった値です。

**Comment by hysdsk** [comment]
@myuu1014 
取得可能ですよ。
私はRESTAPIの時価情報・板情報APIで取得しています。
銘柄コードは以下を参考にすると良いと思います。
https://kabu.com/kabustation/manual/system_setting09.html

**Comment by myuu1014** [comment]
ありがとうござます！頂いた情報で、実現できました！

**Comment by satosato125** [comment]
@hysdsk 
ご回答いただきまして、ありがとうございます。

@myuu1014 
解決済みとのことですので、こちらクローズとさせていただきます。
