### ISSUE TITLE
【質問】TOPIX Mid400 かどうか知りたいのですが対応してますか

### ISSUE THREAD

**Issue by nakanakoto** [kabucom/kabusapi#697]
TOPIX Mid400 の呼値変わったらしいので API で TOPIX Mid400 かどうか知りたいのですが対応してますか

**Comment by satosato125** [comment]
申し訳ございませんが、TOPIX Mid400銘柄かどうかを判別するような項目は提供いたしておりません。
ただし、TOPIX Mid400銘柄を含む、TOPIX 500銘柄は以下の項目から判別が可能です。

銘柄情報API（/symbol）
PriceRangeGroup = 10003の場合、TOPIX 500銘柄となります。

なお、こちらについてリファレンスの修正が遅れておりまして申し訳ございません。
リファレンスには10003の場合はTOPIX 100銘柄と記載されておりますが、呼び値の変更に伴いましてTOPIX 500銘柄となっております。
近日中に更新いたします。

**Comment by nakanakoto** [comment]
なるほど、わかりました。ありがとうございます。
