### ISSUE TITLE
【質問】API実行回数エラーについて

### ISSUE THREAD

**Issue by hysdsk** [kabucom/kabusapi#698]
Code:4001006のAPI実行回数エラーについて二点質問させてください。

１）
~こちらの制限は、RESTAPIのみの流量を見て制限をかけているのでしょうか？もしくはKabuステのUIの操作も込みでの制限なのでしょうか？自作プログラムを起動しつつUIを操作すると、UIを操作したタイミングでAPI実行回数エラーとなる事象が確認されたためです。~

２）
API実行回数エラーとなったあと、どの程度待つとこの制限は解除されるでしょうか？

以上です、ご回答よろしくお願いします。

**Comment by hysdsk** [comment]
具体的には残高照会APIと時価情報・板情報APIを流量制限にかからない感覚で交互に呼び出していますが、そのさなかにフル板で指値を入れるとAPIの流量制限にかかり当該エラーが発生する状況です。

**Comment by hysdsk** [comment]
すみません、１の質問に関して、再現しなくなってしまったので、自作プログラムの不具合を疑いますので、回答不要でよろしくお願いします。

**Comment by satosato125** [comment]
API実行回数エラーが発生してから1秒以内は同じくAPI実行回数エラーとして扱われます。
エラー発生後、1秒以上の間隔をあけて、実行をお願いいたします。

**Comment by hysdsk** [comment]
@satosato125 
一秒以上で制限が解除されること理解しました。
ありがとうございました。
