### ISSUE TITLE
【質問】PUSH API のティック情報の不整合について

### ISSUE THREAD

**Issue by hysdsk** [kabucom/kabusapi#699]
以下issueと同じく、現在価格と気配情報がズレる事象により板のステータスを判別する実装に悩んでおります。
https://github.com/kabucom/kabusapi/issues/618

そこで二点質問させてください。

１）
本事象が仕様なのか不具合なのかどちらでしょうか？
もし仕様であれば、このズレを考慮した設計と実装をしていく必要があるためです。
不具合であるならば、改善される見込みがあるのかも知りたいです。

２）
本事象は中継サーバの間引き処理により起きている事象なのか、東証から受信しているデータそのものがズレているのか、どちらになりますでしょうか？

以上です。
お忙しいところ恐縮ですが、ご回答宜しくお願い致します。

**Comment by hori-ryota** [comment]
大きな約定のときに

* 出来高については1秒以内に複数回の更新が来ることもあるが出来高は間引きしない仕様なのか
* 複数の価格を一気に消化するような出来高更新＆現在価格更新が1回の更新で来ることがあるが何を意味するのか（大きな1回の成行注文なのか間引き等なのか知りたい）
* 先に価格と出来高が更新されてから後続で気配情報が更新されることが多いように見えるがこれは常にそうなのか

らへんは私も知りたいです

**Comment by yasuyuki-nakazawa** [comment]
調査・確認いたします

**Comment by yasuyuki-nakazawa** [comment]
回答にお時間かかり申し訳ございません。
現状の調査を踏まえた結果の連携をさせていただきます。

現在価格と気配情報がずれるのは仕様となっておりまして、原因としては気配情報と現値情報の取得元が異なるためです。
カブステーションAPIはカブステが受信している各種情報を連携するインターフェースとなっておるため、当該際に関してはご理解、ご了承くださいませ。

**Comment by yasuyuki-nakazawa** [comment]
pushの仕様と致しましては、現在価格か気配情報のどちらかの情報が配信されると情報送信を行うため、今回ご指摘のずれが発生しているものと思慮いたします。

**Comment by hysdsk** [comment]
@yasuyuki-nakazawa 
返信が遅れて申し訳ありません。

ご教示ありがとうございます。
情報の取得元が異なることで整合性が担保できない旨承知しました。
重ねて二件質問させてください。

１）
取得元は二か所でしょうか？

２）
パラメータごとに取得元は公開可能でしょうか？
こちらはパラメータ間の整合性が担保されているか否かをパラメータごとに知りたいためです。

お忙しいところ恐縮ですが、よろしくお願いいたします。

**Comment by yasuyuki-nakazawa** [comment]
情報の取得もとにかんしては、申し訳ございませんが、非公開とさせてください。
なお、各種情報に関しては複数の情報ソースがあるため、2社とはかぎらないです。

**Comment by hysdsk** [comment]
@yasuyuki-nakazawa 
承知しました。

本サービスはプログラマにとってとても強力なツールとなっており、今後の品質向上や機能拡張に大変期待をしておりますので、今後ともよろしくお願いいたします。

本件クローズいたします、ありがとうございました。
