### ISSUE TITLE
【不具合】注文約定情報のAPIレスポンスで最新の発注情報が欠落する

### ISSUE THREAD

**Issue by kabucomapi** [kabucom/kabusapi#70]
お世話になります。
VBAを用いて、http://localhost/kabusapi/ordersからの応答を取得していますが、最新のオーダー情報が欠落します。最新以外にも本日の22:09分ごろの以降の発注情報が反映されません。
これは、API又はVBAの仕様上の問題でしょうか。古い情報順に並んでいるようでうが、一定数の以上の情報はオーバーフローしてしまうのでしょうか？
このままでは発注管理ができませんので、ご回答いただきますようお願いします。

前回も要望しましたが、OrderIDで注文約定情報の管理ができないと、非常に不便かつツールの有効性が低下しますので、是非とも早い段階での対応をお願いしたいです。

**Comment by cyber-minion** [comment]
保有されている注文約定件数は何件ございますでしょうか？

**Comment by kabucomapi** [comment]
現在恩赦サイト上で表示されるものは25件ですが、昨日不具合が生じた時点と同じではありません。
昨日の、不具合が生じたときには、3300個程度（  "ID" "State""OrderState" "OrdType" "Exchange"等)のパラメータでレスポスは構成されていたと記憶しています。

**Comment by kabucomapi** [comment]
本日、一時的に最新の注文約定情報が取得できるようになりましたが、発注、取消を繰り返すと34件目の注文から情報が欠落するようになりました。
このAPIの趣旨（高速取引）からして、この程度の発注、取消で注文約定情報の照会ができない仕様とは考え難いですが、、、もし、このような仕様である場合は、発注確認を行わずにトレードを繰り返すことを強いられるので、非常にリスクが高いと思います。
ご回答をお願いいたします。

**Comment by yasuyuki-nakazawa** [comment]
当該事象の再現を含めて確認を実施してみます。
注文約定情報として、2442件が最大という制限は設けておりません。
また、注文約定や残高照会の抽出において、フィルタリング機能の追加に関しては既に検討進めております。
調査結果に関しては再度展開させて頂きます。

**Comment by kabucomapi** [comment]
本日も確認したところ、一度注文約定情報を取得したあとは、エクセルを再起動するまでAPIが同じレスポンスを返してくることがわかりました。注文約定情報を取得したあとに入れた注文の情報が取得できません。VBAで情報を取得しています。
ご確認・回答いただきますようお願いします。

**Comment by kabucomapi** [comment]
お世話になります。

調査は進んでいますでしょうか？
本日はAPIログの確認をしました。
エクセルVBAから【Orders】(0)でリクエストしていますが、エクセル立ち上げ後、1度レスポンスを得た後は同じレスポンスを返してきます。APIログには1回目のレスポンスログしか残っていません。
2回目からのリクエストにも応答を返してきており、結果をresponseTextで抽出することはできますが、APIログは作成されないという状況です。
その状況が現れた後に、一度エクセルを閉じて再起動すると、上記【Orders】(0)応答後に発注した注文情報を含んだ応答が返ってきます。APIログも新たに作成されます。
この状況が解決しないので、他の開発が進まず困っております。

お手数をおかけしますがご回答いただきますようお願いします。

**Comment by yasuyuki-nakazawa** [comment]
こちらでも検証しておりますが事象が再現されません
①お使いのエクセルのバージョンはいくつでしょうか
②ctrl+alt+F9で、Excelの再計算をした場合はいかがでしょうか？
③可能であればExcel以外のスクリプトからリクエストをした際はいかがでしょうか？

**Comment by kabucomapi** [comment]
①Excel2016 32BIt,2019 64bitの両環境で試しましたが同じ症状です。
②エクセルのシート関数は使っておらず、すべてコードで実行しているので再計算は関係ないと思うのですが、上記操作を実行して、再度コードを走らせましたが症状は解消されません。
③すみませんが、エクセル以外のスクリプトを走らせることができません。

**Comment by yasuyuki-nakazawa** [comment]
Excelのバージョンは問題なさそうです
コードで実行している旨、理解しました。こちらでも再度再現試みます
二度目のアクセスのAPIログがないということで、kabuステまでリクエストが到達していないことが想像されます
macroからアドインかアドインからkabuステ部分のいずれかにポイントがあると考えます
リクエスト部分のコードを開示いただけますか？

**Comment by kabucomapi** [comment]
お世話になります。
いろいろとお手数をおかけして申し訳ございません。
下記が現在使用しているコードとなります。 MakeDicのファンクションは、各要素をディクショナリ―化するものですが、その前のobjHTTP.responseTextの時点で情報が抜けています。
エクセルを起動して、1回目の要求において、orderinfinfrespに代入されるテキスト内容が、新しい注文をいれて再度このファンクションを走らせても更新されません。2回目以降のファンクション実行において、orderinfinfrespがエンプティ―になったあと、1回目のテキストが入力される（応答によって）のが確認できます。
よろしくお願いいたします。

Public Function orderinf() As Variant 
     
    Dim JsonObject As Object
    Set JsonObject = New Dictionary
    Dim objHTTP As Object
    Set objHTTP = CreateObject("msxml2.xmlhttp")
    objHTTP.Open "GET", "http://localhost:" & PortNo & "/kabusapi/orders?product=0", False
    objHTTP.setRequestHeader "Content-Type", "application/json"
    objHTTP.setRequestHeader "X-API-KEY", ApiToken
    objHTTP.send
    
    startTime = Timer
    Do While objHTTP.readyState <> 4
        DoEvents
        If Timer - startTime > 1 Then
           MsgBox ("API応答なし")
           End
        End If
    Loop

    orderinfinfresp = objHTTP.responseText
    Set Dic = CreateObject("Scripting.Dictionary")
    Set Dic = MakeDic(orderinfinfresp)
    Set orderinf = Dic
    
End Function

**Comment by yasuyuki-nakazawa** [comment]
当方でも確認しました。
msxml2でレスポンスがキャッシュされていることが原因かとおもわれます。

**Comment by yasuyuki-nakazawa** [comment]
追記します。
ダミーパラメータを指定してキャッシュを防ぐことで対応が可能です
"GET", "http://localhost:18080/kabusapi/orders?product=0&dummy=" & DateTime.Now, False
 これで正常に稼動したことを確認しています。

APIログに情報が記載されていないことから、APIの呼び出しまで到達していないことはお分かりになるかと思います。

**Comment by kabucomapi** [comment]
お世話になります。
ご回答いただきありがとうございました。
おかげさまで、やっと問題が解決しました。これで売買ロジックを作ることができます。
また、深夜にも関わらずご対応いただきありがとうございました。
クローズしていただいて結構です。
