### ISSUE TITLE
【質問】銘柄情報APIの呼値グループについて

### ISSUE THREAD

**Issue by hysdsk** [kabucom/kabusapi#700]
以下資料によりますと、銘柄情報APIの呼値グループ（PriceRangeGroup）には呼び値コードというコードが設定されていて、呼び値がわかる仕様のようですが、10003の場合でもTOPIX100採用銘柄でないように見えます。
https://kabucom.github.io/kabusapi/reference/index.html#operation/symbolGet
![image](https://github.com/kabucom/kabusapi/assets/26004436/a5db7cc4-2374-4b05-abd8-7358b3a6692c)

例えば、2127:日本M&AセンターHDを銘柄情報を取得すると、現状10003が呼び値グループに設定されていますが、以下の岡三証券のページでTOPIX100構成銘柄一覧を確認しますと、日本M&AセンターHDは存在していないように見えます。他にも6028:テクノプロ・ホールディングスや、6141:DMG森精機も同様の状態です。
https://www.okasan-online.co.jp/jp/brand_topix100.html

このあたりの呼び値グループの仕様についてご教示いただけますでしょうか？

**Comment by satosato125** [comment]
6/5のTOPIX Mid400銘柄の呼び値変更に伴いまして、同日より呼値グループ（PriceRangeGroup）が10003となる銘柄がTOPIX100銘柄にTOPIX Mid400銘柄を加え、TOPIX500銘柄が対象となっております。

こちらのissuesも併せてご確認ください。
https://github.com/kabucom/kabusapi/issues/697#issuecomment-1578124662

リファレンスの修正が遅れておりまして、みなさまにはご迷惑をおかけしており大変申し訳ございません。

**Comment by hysdsk** [comment]
@satosato125 
ありがとうございます。TOPIX100ではなくTOPIX500である旨、理解しました。
リファレンスの修正をもって本件クローズしていただければと思います。
