### ISSUE TITLE
【質問】apiリクエストの集約について

### ISSUE THREAD

**Issue by monolith88** [kabucom/kabusapi#71]
REST apiの仕様書を見ていたのですが、発注系であれ、情報取得系であれ、一度のリクエストに対して数件までの制限があるようですね。それだと、多数の銘柄の情報を取得したり、発注するのに、一秒ずつ何回かに分けてリクエストを投げる必要があり不便です。そこで、多数の銘柄名をリスト化するなりして集約して、一回のリクエストで同時に投げることで、同時に多数の銘柄の情報を取得したり、発注することは可能でしょうか？

**Comment by cyber-minion** [comment]
1回のリクエストで複数の銘柄情報取得あるいは発注はできません。
ご指摘の観点は要望として検討させていただきます。
現状当社システム保護の課題もあり、リクエストに制限をさせていただいております。

**Comment by yasuyuki-nakazawa** [comment]
発注リクエストに関してですが、各発注を同期で行う必要がある関係上、まとめた発注というのは難しい部分がございます。
現在の流量制限に関しては、今後利用状況を見極めつつ、緩和は検討してまいります。

**Comment by yasuyuki-nakazawa** [comment]
当件は一旦クローズとさせて頂きます
