### ISSUE TITLE
【不具合】

### ISSUE THREAD

**Issue by onaga625** [kabucom/kabusapi#710]
■[必須] '注文入れてもこの表示が出ます{"Code":4001009,"Message":"APIキー不一致"}　解決策を教えてください。
■[必須] 本来想定されるアクションと事象
■[必須] 常時
■[任意]Windows10　Excel2021Excel Addin v1.8.0 Excel Macro v1.13.0
■[任意] {"Code":4001009,"Message":"APIキー不一致"}

**Comment by satosato125** [comment]
APIキー不一致のエラーは、発注に付与したトークンとAPIが発行したトークンが一致しない場合に返却されるエラーです。

APIが発行したトークンは以下のタイミングで無効となります。
下記のような操作をした場合にはもう一度トークンの取得をする必要があります。
・kabuステーションを終了した時
・kabuステーションからログアウトした時
・別のトークンが新たに発行された時

Excelアドインをご利用の場合は、下記ページの「Excelアドイン共通操作」の項4の操作を行うことでトークンを取得いたします。
[Addin](https://kabucom.github.io/kabusapi/ptal/add-in.html)
まずは正常にログインが完了し、アイコンが緑になっていることをご確認お願いします。
その後、この状態で発注ができるかお試しいただきたいです。

**Comment by onaga625** [comment]
正常にログインが完了し、アイコンが緑になっているのですが下記のメッセージがでます。
{"Code":10019,"Message":"パスワードをご確認ください"}

設定した本番用のパスワードをいれているのですが。

**Comment by satosato125** [comment]
Excelの「発注パスワード」欄にAPIログイン用のパスワードを設定しておりませんでしょうか？
Excelの「発注パスワード」に設定するのは、kabuステーションで発注のときに入力するパスワードと同じものです。

**Comment by onaga625** [comment]
ありがとうございます。
解決しました。
ワンショット手数料コースでもAPIだと手数料無料になりますか？

**Comment by satosato125** [comment]
はい、ワンショット手数料コースでは、kabuステーションAPI経由での信用取引のお取引は手数料無料となります。

**Comment by onaga625** [comment]
ありがとうございました。

**Comment by satosato125** [comment]
解決済みとのことですので、クローズとさせていただきます。
