### ISSUE TITLE
エクセルサンプルから発注できません(発注マクロがバグっているのでは！)

### ISSUE THREAD

**Issue by ieyasuo** [kabucom/kabusapi#714]

**Comment by satosato125** [comment]
こちらでの確認では、Excelマクロのサンプルの最新版から発注できることを確認しております。

発注が失敗となってしまう原因としては、パラメータの設定間違いやAPI実行の環境が整っていないことなど、様々な要因がございます。
お問い合わせの際、ご実行なさったときの詳しい状況やエラーメッセージなども一緒に記載いただきますと、エラーについての調査やサポートなども行わせていただいております。
お困りの事象などございましたら、上記内容とともにお問い合わせいただけますと幸いです。

**Comment by satosato125** [comment]
こちらに関して追記がないようですので、クローズとさせていただきます。
お問い合わせがございましたら、reopenか別途起票をお願いいたします。
