### ISSUE TITLE
【質問】返済価格の修正

### ISSUE THREAD

**Issue by h-tsun3** [kabucom/kabusapi#715]
自前で、株の信用取引のトレーリングストップを実装したいのですが、逆指値価格を修正するには、一旦返済注文を取消す必要がありますか？
それとも、返済建玉か決済順序を指定の上で、修正した価格での返済注文を行うだけで良いですか？

**Comment by yasuyuki-nakazawa** [comment]
現行のAPI仕様では訂正をサポートしておりませんので、取消していただいて、再発注していただく必要があります

**Comment by h-tsun3** [comment]
回答ありがとうございます。了解しました。値動きが激しいとすり抜けそうですね。
