### ISSUE TITLE
225MINIでの返済について（/sendorder/future）

### ISSUE THREAD

**Issue by app-yama** [kabucom/kabusapi#717]
225MINIでの返済について（/sendorder/future）
売玉有の時 返済買いの注文を出しましたがエラーになってしまいます。
新規注文（TradeType: 1 , Side: '1'）は問題なくできました。

以下のようなデータを送信していますがなにか間違いがありますでしょうか？

       payload = {
          Password: 'XXXXXXX',
          Symbol: '168090019',
          Exchange: 23,
          TradeType: 2,
          Side: '2',
          Qty: 1,
          ClosePositions: [{ HoldID: '20230719XXXXXXX', Qty: 1 }],
          FrontOrderType: 120,
          Price: 0,
          ExpireDay: 0,
          TimeInForce: 2
        }

エラーコードは８で返済建玉情報不正エラー のようです。
アドバイスいただければと思います。

**Comment by satosato125** [comment]
以下のパラメータの設定について、ご確認をお願いいたします。

ClosePositions
HoldIDは、残高照会APIで取得したExecutionIDを指定していただく必要がございます。
下記の例のように、先頭に「E」が付いているかと思いますので、ご確認をお願いします。
例：E20230719xxxxx

**Comment by app-yama** [comment]
ExecutionIDの件、ありがとうございます。確認してみます

保有数が3枚ありどれかを返済したいときにOrderIdに紐づけれないとなれば
損益が真ん中のものを決済を最初にはできないとのことで良いでしょうか？

**Comment by satosato125** [comment]
ExcutionIDは約定ごとに採番されています。
お問い合わせのように保有数が3枚あり、それぞれが別々に約定したものであれば、
それぞれに異なるExcutionIDがありますので、損益が真ん中のものを選択することも可能です。

**Comment by app-yama** [comment]
確認してみます。ありがとうございました
