### ISSUE TITLE
【質問】PUSH APIでの値が更新されるタイミングについて

### ISSUE THREAD

**Issue by spotthediff** [kabucom/kabusapi#72]
PUSH APIで値がPUSHされるタイミングはいつでしょうか?
登録された銘柄の価格に変更があったときにPUSHされるのでしょうか?
それとも出来高が発生したら価格に変動が無くてもPUSHされるのですか？

**Comment by cyber-minion** [comment]
PUSH配信は、値が更新されたら配信されますので、
登録された銘柄の価格に変更があったときにPUSHされます。

また、ご参考として、場間（昼休み）と引け後での配信はありません。
