### ISSUE TITLE
【質問】東証寄付に間に合わせるためのタイムリミット

### ISSUE THREAD

**Issue by isytmk** [kabucom/kabusapi#726]
8時59分59秒台に発注（SendOrderの結果としてOrderIDを受領）しても寄付に間に合っていないことがあります。
発注から東証への板乗りまではどれくらい時間がかかるのでしょうか？
♯86の返答からは、OrderIDが返されるときは取引所で板乗せが終わっているように読めます。（　https://github.com/kabucom/kabusapi/issues/86　）
しかし、8時59分59秒台前半にOrderIDが返っていても、成行注文の約定値が取引所の始値より不利なことが多くあります。

たとえば、本日6146ディスコの売り成行注文を発注しました。
PLAIN.logやKabuS.logを見ると08:59:59.3749にOrderIDを受領しています。（　08:59:59.3749,I,13484,0009 【SendOrder】({"Result":0,"OrderId":"20230802A02N66566373"})　）
6146ディスコの本日の始値は27,830円でした。寄付前の成行注文なら始値で約定すると思うのですが、約定価格は27,805円でした。

東証の前場寄付のための板寄せは8:59:59前に締め切っているのでしょうか？
9:00:00丁度に寄り付くとして、いつまでに発注を終えれば寄付に間に合うでしょうか？

**Comment by satosato125** [comment]
当社にて発注を受け付けてから取引所へ注文を完了するまでの時間は、状況にも依りますが10msec～50msecくらいを参考値としてお考えください。
なお、取引時間中の新規注文であれば、弊社のPCサイトよりご確認いただけます。
ログイン後の注文約定照会から注文詳細画面を開きますと、発注所要時間が表示されておりますので、ご参照をお願いいたします。

また、寄付前に発注された成行注文についてですが、寄成注文とは異なりますので、必ずしも始値で約定しないことがございます。
市況にも左右されますので、いつまでに発注を終えればよいか、というご質問には明確なお答えをお出しできません。
始値での約定をご希望の場合は寄成注文をご選択いただければと思います。

**Comment by isytmk** [comment]
返答ありがとうございます。

＞寄付前に発注された成行注文についてですが、寄成注文とは異なりますので、必ずしも始値で約定しないことがございます。
板寄せでは全ての成行注文が成立すると認識しておりましたが、そうではないのですね。　https://kabu.com/glossary/kabu2173.html
ルールに合わせて調整します。ありがとうございました。

**Comment by isytmk** [comment]
本日7270SUBARUの寄成注文を出しました。08:59:59.4926にOrderIDを受領しています。08:59:59.4926,I,12280,0005 【SendOrder】({"Result":0,"OrderId":"20230817A02N81324593"})
しかし、この注文は失効しました。kabuステーションやPCサイトによれば、注文受付日時が令和05年08月17日 09時00分となっています。
OrderIDは取引所に注文が渡された後に返される（♯86）から8時59分には受け付けられていたのではないでしょうか？
取引所に注文を渡すまでには10～50ミリ秒程度のはずではないですか？　状況により多少長くなるのはやむを得ないとしても、なぜ8:59:59.4926にOrderIDを受領した注文が執行するのでしょうか？
どのように発注すればすぐに取引所につながるのでしょうか？

**Comment by yasuyuki-nakazawa** [comment]
寄り付き、引けのタイミングはレイテンシが高くなることが多い点はご了承ください。
