### ISSUE TITLE
WEBSOCKETにて株価【質問】

### ISSUE THREAD

**Issue by toshifukamachi** [kabucom/kabusapi#727]
WEBSOCKETにて株価を取得しようとしていますが、
先物コードは取得できますが、株価は取得できません。
エクセルですが、セルの値は以下です。
=WEBSOCKET(16809005,2,"現値")

**Comment by satosato125** [comment]
先物の銘柄コードですが、9桁で返却されておりませんでしょうか？
お問い合わせに記載のものですと8桁になっておりますので、対象の銘柄が見つからない状態となっているものと思います。

**Comment by toshifukamachi** [comment]
ありがとうございました。解決しました。
