### ISSUE TITLE
【質問】C#のサンプルコードについてです

### ISSUE THREAD

**Issue by Raliru** [kabucom/kabusapi#729]
お世話になっております。
サンプルコードの[Kabusapi_Register.cs](https://github.com/kabucom/kabusapi/blob/master/sample/C%23/CSharp/Kabusapi_Register.cs)を実行したところ、なぜか[Kabusapi_Sendorder_Margin_DayTrade.cs](https://github.com/kabucom/kabusapi/blob/master/sample/C%23/CSharp/Kabusapi_Sendorder_Margin_DayTrade.cs)が実行されてしまいます。
この現象の回避策をご教授願えませんでしょうか？
よろしくお願いいたします。

下記はサンプルコードをテストした時のKabuSのAPIログです。
[Kabusapi_Sendorder_Margin_DayTrade.cs](https://github.com/kabucom/kabusapi/blob/master/sample/C%23/CSharp/Kabusapi_Sendorder_Margin_DayTrade.cs)において
`Symbol = "1111",`
に変更してテストしました。

`02:15:21.3118,I,5396,0013 【Token】({"APIPassword":"****************"})
02:15:21.3118,I,5396,0013 【Token】({"ResultCode":0,"Token":"****************"})
02:15:21.3508,I,5396,0013 【SendOrder】({"Password":"****************","Symbol":"1111","Exchange":1,"SecurityType":1,"Side":"1","CashMargin":2,"MarginTradeType":3,"MarginPremiumUnit":422,"DelivType":0,"AccountType":2,"Qty":100,"FrontOrderType":20,"Price":425,"ExpireDay":0})
02:15:21.3518,I,5396,0013 【SendOrder】({"Code":4002001,"Message":"銘柄が見つからない"})`

**Comment by satosato125** [comment]
実行環境はVisual Studioをお使いでしょうか？
Visual Studioをお使いの場合の回答となってしまいますが、デフォルトの設定では、
スタートアップオブジェクトに「Kabusapi_Sendorder_Margin_DayTrade.cs」が選択されております。

プロジェクト > CSharp_sampleのプロパティ > アプリケーション > スタートアップオブジェクト
こちらから任意のオブジェクトをご選択ください。

**Comment by Raliru** [comment]
ご返信ありがとうございます！
無事に解決いたしましたので、クローズさせていただきます。
ご対応いただきありがとうございました！
