### ISSUE TITLE
【質問】先物発注の際のエクセルに入力する銘柄コードは？

### ISSUE THREAD

**Issue by hosoku** [kabucom/kabusapi#734]
先物発注の際のエクセルに入力する銘柄コードは？
例えば先物mini9月限、あるいは12月限などの
銘柄コードが何なのか分かりません。

**Comment by hishiharahaz** [comment]
kabuSTATION_API_function_sample.xlsxに「先物銘柄コード取得」シートがありますので、先物コードと限月を入力すると銘柄コードがわかるかと思います。
https://github.com/kabucom/kabusapi/releases/tag/ExcelMacro-v1.14.0

**Comment by hosoku** [comment]
ありがとうございます！まだ確認できてないですが、エクセル確認してみます！
