### ISSUE TITLE
ｃ＋＋　でAPI呼び出し【質問】

### ISSUE THREAD

**Issue by john-banjirou** [kabucom/kabusapi#737]
質問失礼します。

C#,python,javascript,excelより、APIを使える。サンプルがある。のですが、

C++では、できるのでしょうか？
もしできるなら、簡単なサンプルを示してもらえると助かります。

宜しくおねがいします。

**Comment by yasuyuki-nakazawa** [comment]
C++でも特段問題なくAPIを呼び出すことは可能です。
サンプルのご提供に関してはご要望として検討させていただきます。
C++であれば、C#のサンプルがご参考になるかと思慮いたします。

**Comment by john-banjirou** [comment]
回答有り難うございます。

検討よろしくおねがいします。
