### ISSUE TITLE
【質問】Issueの管理方法について

### ISSUE THREAD

**Issue by hysdsk** [kabucom/kabusapi#739]
過去に起票したIssueについて、ステータスが不明のまま放置されているように見えるものが多くあります。
Issueのクローズは起票者側がするのかサービス側がするのかどちらなのでしょうか？
また、起票者の質問で更新が止まっているIssueについては調査中のステータスという認識で問題ないでしょうか？

**Comment by yasuyuki-nakazawa** [comment]
基本的にはご質問者がクローズいただく形をとらせていただいております。
回答済みに関して、一定のお時間が経過した物は管理者側でクローズするようにはしております

**Comment by hysdsk** [comment]
@yasuyuki-nakazawa 

> 起票者の質問で更新が止まっているIssueについては調査中のステータスという認識で問題ないでしょうか？

こちらはいかがでしょうか？

**Comment by yasuyuki-nakazawa** [comment]
>こちらはいかがでしょうか？
調査、確認中ということはございます
後は、一次回答後にオープンの物に関しては、質問者の方のクローズ待ちという物もございますことはご認識頂ければと存じます

**Comment by hysdsk** [comment]
@yasuyuki-nakazawa 
承知しました。
ご多忙中と存じますが、今後ともサービス運用の方何卒よろしくお願いいたします。
本件クローズいたします。
