### ISSUE TITLE
【要望】PUSH配信でVWAPと同様に平均1-3を追加

### ISSUE THREAD

**Issue by yoichiro1963** [kabucom/kabusapi#741]
PUSH配信で移動平均1、移動平均2、移動平均3の追加を要望します。

以前から要望が多い内容に近いですが、せめてVWAPと同じ感じで平均1,2,3を追加願えないでしょうか。
何とかkabuステーションAPIだけで勝てるシステムトレードを実現したいです。

よろしくお願いします。

**Comment by yasuyuki-nakazawa** [comment]
要望としては展開いたします
PUSHはカブステーション上に受信している情報を展開する仕組みになっております
移動平均1，2は画面上にチャート等が表示された際に情報算出して画面出力している情報のため、
こちらのPUSH展開に関しては対応インパクトが大きく、全体含めた対応検討となる点はご了承ください

**Comment by yoichiro1963** [comment]
すみません、遅くなりました。
回答内容は理解しました。
今後のAPI機能拡充に期待します。
