### ISSUE TITLE
【質問】信用取引の成行発注時の決済価格と決済数量の取得について

### ISSUE THREAD

**Issue by hieeeee** [kabucom/kabusapi#747]
成行発注にて信用取引実行後に注文約定照会(orders)を実行したのですが、決済価格が取得できませんでした。
過去の質問にて成行の場合はDetailsのRecType=8のレコードから決済価格が取得できるとの記載があったのですが、そもそもDetailsにRecType=8のレコードが存在しません。

また今回の注文は合計で200株なのですが、Detailsに2レコードあり、そのどちらにもQty=200が入っており、どのように決済価格と決済数量を取得すればいいのかがわかりません。(この取得結果を見ると400株決済しているようにも見える)
発注ごとの決済価格と決済数量の取得方法をご教示ください。

ちなみにリクエストパラメータはid、symbol、sideを指定しています。
以下、一部マスクしていますが、実行時のログです。
　[{'AccountType': 4,
　'CashMargin': 2,
　'CumQty': 0.0,
　'DelivType': 0,
　'Details': [{'Commission': 0.0,
　　　　　　　 'CommissionTax': 0.0,
　　　　　　　 'DelivDay': 20231011,
　　　　　　　 'ExchangeID': None,
　　　　　　　 'ExecutionDay': None,
　　　　　　　 'ExecutionID': None,
　　　　　　　 'ID': '20231006A02NXXXXXXXX',
　　　　　　　 'OrdType': 1,
　　　　　　　 'Price': 0.0,
　　　　　　　 'Qty': 200.0,
　　　　　　　 'RecType': 1,
　　　　　　　 'SeqNum': 1,
　　　　　　　 'State': 3,
　　　　　　　 'TransactTime': '2023-10-06T09:17:59.6300844+09:00'},
　　　　　　　{'Commission': 0.0,
　　　　　　　 'CommissionTax': 0.0,
　　　　　　　 'DelivDay': 20231011,
　　　　　　　 'ExchangeID': '1F11150000XXXX',
　　　　　　　 'ExecutionDay': None,
　　　　　　　 'ExecutionID': None,
　　　　　　　 'ID': '20231006B02NXXXXXXXX',
　　　　　　　 'OrdType': 1,
　　　　　　　 'Price': 0.0,
　　　　　　　 'Qty': 200.0,
　　　　　　　 'RecType': 4,
　　　　　　　 'SeqNum': 4,
　　　　　　　 'State': 3,
　　　　　　　 'TransactTime': '2023-10-06T09:17:59.902092+09:00'}],
　'Exchange': 1,
　'ExchangeName': '東証プ',
　'ExpireDay': 20231006,
　'ID': '20231006A02NXXXXXXXX',
　'MarginPremium': 0.0,
　'MarginTradeType': 3,
　'OrdType': 1,
　'OrderQty': 200.0,
　'OrderState': 3,
　'Price': 0.0,
　'RecvTime': '2023-10-06T09:17:59.6300844+09:00',
　'Side': '1',
　'State': 3,
　'Symbol': '86XX',
　'SymbolName': 'ⅩⅩⅩⅩⅩグループ'}]

**Comment by satosato125** [comment]
RecType=8のレコードは約定したタイミングに作成されます。
信用取引実行後に注文約定照会(orders)を実行した、とのことですが、少し実行タイミングが早かったのかもしれません。
もう一度、注文約定照会(orders)を実行し、RecType=8のレコードが存在するか、ご確認いただけませんでしょうか？

**Comment by hieeeee** [comment]
ご回答ありがとうございます。
バッチで処理を連続して実行していたため取得できていなかったようで、注文約定照会の前にスリープを入れたところ取得できました。
解決しましたので、クローズさせていただきます。
