### ISSUE TITLE
【質問】しばらく時間がたつとエラーになります。

### ISSUE THREAD

**Issue by e92eda** [kabucom/kabusapi#749]
まだこれから使い始めるところですが、大変便利そうで期待しております。早速ですが質問があります。
例題などからとった、下記のPythonプログラムをJupyterLabで実行しています。最初のうちはうまくいってますが、しばらく達つと、Code': 4001007, 'Message': 'ログイン認証エラー'　がでます。なぜこのようになるのでしょうか。解決法はありますか？
なお、環境はM1 Mac上でParallels　Desktopを用い、Kabuステーション、JupyterLabとも仮想Windows環境で動かしています。さくらWindows サーバー上でもやってみましたが、同様の結果です。どうぞご教示よろしくお願いします。

def generate_token():# トークン発行
    obj = { 'APIPassword': 'XXXXXX' }
    json_data = json.dumps(obj).encode('utf8')
    
    url = 'http://localhost:18080/kabusapi/token'
    req = urllib.request.Request(url, json_data, method='POST')
    req.add_header('Content-Type', 'application/json')
    
    try:
        with urllib.request.urlopen(req) as res:
            content = json.loads(res.read())
            token_value = content.get('Token')
            pprint.pprint(token_value)
    except urllib.error.HTTPError as e:
        print(e)
        content = json.loads(e.read())
        pprint.pprint(content)
    return token_value

    # トークン発行
token_value = generate_token()

結果：
HTTP Error 401: Unauthorized
{'Code': 4001007, 'Message': 'ログイン認証エラー'}
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
Cell In[37], line 32
     29     return token_value
     31     # トークン発行
---> 32 token_value = generate_token()
     34 def get_symbol(token):    # 銘柄情報取得
     35     url_symbol = 'http://localhost:18080/kabusapi/symbol/5401@1'

Cell In[37], line 29, in generate_token()
     27     content = json.loads(e.read())
     28     pprint.pprint(content)
---> 29 return token_value

UnboundLocalError: local variable 'token_value' referenced before assignment

**Comment by hori-ryota** [comment]
当てずっぽうですが別でトークン発行が実行されて古いトークンが無効になっていたりしそうな気がしました

新規トークンが発行されると旧トークンは無効になる仕組みです
https://kabucom.github.io/kabusapi/reference/index.html#operation/tokenPost

**Comment by e92eda** [comment]
ありがとうございます。当初安定しないと思っていましたが、とりあえずうまくいっているようです。毎日再起動しないと接続できない、ことも理解しました。

**Comment by yasuyuki-nakazawa** [comment]
@hori-ryota 
回答ありがとうございます。

@e92eda 
カブステーション自体は早朝にセッションがリセットされますので、そのタイミングでログイン用のトークンは不正となります。
