### ISSUE TITLE
【質問】注文約定照会のレスポンス State,OrderStateの違い

### ISSUE THREAD

**Issue by Ros522** [kabucom/kabusapi#75]
お世話になります。
注文約定照会APIの返り値であるState（状態）、OrderState（注文状態）の違いとは
どういったものになるでしょうか。

実際、注文が有効かどうか判断するにはどちらを見るのが適切でしょうか。

**Comment by tsuchinaga** [comment]
#1 より引用です

> 現状、株式の取り扱いだけですので、差はございません  
> 株式の取引においては、stateを参照いただければ、注文約定の状態が確認できます

**Comment by Ros522** [comment]
見落としていました。ありがとうございます！
