### ISSUE TITLE
【質問】信用取引の取引制限銘柄の取得方法

### ISSUE THREAD

**Issue by hieeeee** [kabucom/kabusapi#751]

**Comment by hieeeee** [comment]
信用取引において取引制限銘柄が存在しますが、取引制限銘柄かどうか判断する方法はあるでしょうか？

**Comment by hysdsk** [comment]
@hieeeee 
以下の規制情報APIで確認できますよ。
https://kabucom.github.io/kabusapi/reference/index.html#operation/regulationsGet

**Comment by hieeeee** [comment]
@hysdsk 
ありがとうございます。
解決しましたので、クローズさせていただきます。
