### ISSUE TITLE
【不具合】NK225夜間銘柄情報がNone

### ISSUE THREAD

**Issue by mikiyaasahara** [kabucom/kabusapi#752]
■[必須] 不具合事象(概要)
NK225先物12限月の夜間取引の銘柄情報がNoneで返ってきます
openingpriceなど多数
■[必須] 本来想定されるアクションと事象
実数
■[必須] 不備発生時刻（常時の場合は、常時で記載ください)
今週月曜日から同じ状況
■[任意] お使いの環境(OS、Excelのバージョン等)、サンプル(Macro、アドインのバージョン）
■[任意] 不備部分のログ

**Comment by satosato125** [comment]
こちらでNK225先物12限月の夜間取引の時価情報の取得を試してみましたが、正常に取得することができました。
時価情報取得の前に、先物銘柄コード取得をなさっているものと思いますが、年月の指定にお間違いがないか、ご確認いただけませんでしょうか？

また、上記の事象の発生した銘柄コードやログなども添付いただけますと、幸いです。

**Comment by mikiyaasahara** [comment]
実行する時間によってNoneになることがわかりました。夜間取引中は取得できます。今現在12:00はNoneです。
取引コード168120018市場コード24

**Comment by mikiyaasahara** [comment]
実数が取得できるようになりました。
ありがとうございます。
もう一点、previous close time が 0:00になってます。
訂正よろしくお願いします。
