### ISSUE TITLE
【要望】板の「出来高数」をPUSH通知APIで提供してほしい

### ISSUE THREAD

**Issue by hysdsk** [kabucom/kabusapi#754]
# 概要
[PUSH通知API](https://kabucom.github.io/kabusapi/ptal/push.html)のフィールドで価格ごとの「出来高数」が取得できるよう提供していただきたいです。
板でいうと、以下キャプチャの赤枠の情報になります。
![スクリーンショット 2023-10-25 235056](https://github.com/kabucom/kabusapi/assets/26004436/50cd2206-0cd0-4579-b0f1-81c68818529e)

## 理由
現状提供中のフィールドでも大まかには算出が可能ですが、計算コストがかかるのと、間引き処理と気配値不整合の仕様（ https://github.com/kabucom/kabusapi/issues/699 ）があるため出来高数の精度が低くなってしまうためです。

以上、ご検討よろしくお願いいたします。

# 合わせて確認いただきたい内容
- https://github.com/kabucom/kabusapi/issues/669
  - 過去に起票した要望です。再度ご検討いただけると幸いです。
- https://github.com/kabucom/kabusapi/issues/645
  - 過去に起票した質問です。未回答のため、ご確認いただけると幸いです。

**Comment by yasuyuki-nakazawa** [comment]
現状の出来高がクライアントで算出しているものか、取引所より配信されているものかを確認いたします。
前者の場合ですと、対応難易度が上がってしまいます。
改めてご回答させていただきます

**Comment by hysdsk** [comment]
@yasuyuki-nakazawa 
たしかに、クライアント側で算出している場合は同じようにこちらのアプリケーション側で算出するのが良いかと思います。その場合は間引き処理の緩和などご検討いただけると幸いです。

> 改めてご回答させていただきます

こちらお待ちしております。

**Comment by yasuyuki-nakazawa** [comment]
こちら、集計はクライアントで実施していることが確認されております。
そのため出来高単体を取得する場合は値そのものを直接引っ張ることは手間がかかることが推測されます。
一旦、ご要望としては理解いたしました。

**Comment by hysdsk** [comment]
@yasuyuki-nakazawa 
ご確認ありがとうございます、承知しました。
クライアント側で集計しているのであればPUSHで取得すべきでないと思いました。

本件クローズいたします。
