### ISSUE TITLE
【質問】信用建玉返済（closepositions）で返済時の指定方法

### ISSUE THREAD

**Issue by hieeeee** [kabucom/kabusapi#755]
信用建玉返済（closepositions）でHoldIDはEから始まるExecutionIDを指定すると思いますが、このExecutionIDは注文単位ではないと思っています。
例えば成り行きで300株購入し、100株が1000円200株が1100円で約定した場合はExecutionIDが2つ発行される認識です。
その場合、注文単位（上記で言えば300株）でまとめて返済を指定することはできないのでしょうか？

**Comment by hishiharahaz** [comment]
@hieeeee 
ClosePositionsのHoldIDを複数指定して、Qtyに合計返済数量を指定すればよいかと思います。
以下、参考にしてください。

{
"Symbol":"xxxx",
"Exchange":"1",
"SecurityType":"1",
"Side":"2",
"CashMargin":"3",
"MarginTradeType":"2",
"DelivType":"2",
"AccountType":"4",
"Qty":"200",
"FrontOrderType":"10",
"Price":"0",
"ExpireDay":"0",
"ClosePositions":[{"HoldID":"E20231002013A8","Qty":"100"},{"HoldID":"E20231002013C2","Qty":"100"}],
"Password":"xxxxxxxx"
}

**Comment by hieeeee** [comment]
@hishiharahaz 
ご回答ありがとうございます。
実装方法がわかりましたので、クローズします。
