### ISSUE TITLE
【質問】EXCEL SAMPLE PUSH の関数 WebSocket がうまくゆきません。【初心者】

### ISSUE THREAD

**Issue by SJCNobu** [kabucom/kabusapi#757]
マニュアル通りに Excel　Addinnの設定完了し、本番用と検証用の接続もできるようになりました。

でもPush Sample の説明通りにExcel関数　➡ '=WEBSOCKET(A3,B3,G2)　　G2は"現値"
A2=111,B2=2 ➡　日経２２５先物　ミニ　日通し　が帰ってくればOK
をそれぞれのセルに入れてみましたが何も値が帰ってきません。

ただ今の時刻は2023/10/27 9:45

**Comment by yasuyuki-nakazawa** [comment]
WebSocketの関数部分に参照されているセルとその後に記載されているセルの位置が異なるのはご認識通りでしょうか

**Comment by yasuyuki-nakazawa** [comment]
事象から推測される原因としては、事前に取得する銘柄をレジストする処理が必要なので、それが抜けているのではないかなと思慮いたします。
また、日経225のミニの銘柄コードは111ではないです

**Comment by SJCNobu** [comment]
皆様の回答ありがとうございます。
過去の質問の回答で解決できました。
原因は「事前に取得する銘柄をレジストする処理が必要」その通りでした。
