### ISSUE TITLE
【質問】信用建玉返済（closepositions）で返済時のエラーについて

### ISSUE THREAD

**Issue by hieeeee** [kabucom/kabusapi#758]
信用建玉返済（closepositions）で返済時に下記エラーとなり返済が失敗してしまいます。
HTTP Error 400: Bad Request
{'Code': 4001005, 'Message': 'パラメータ変換エラー - 詳細はkabuSログファイルを確認してください'}
kabusログファイルには下記エラーが返ってきていました。
不明なエラー(ERROR_CD_000_001_007)

下記パラメータを指定してAPIコールしているのですが、ログを見てもどこが問題になっているかがわかりません。
もし理由がわかるようでしたらご教示いただけるでしょうか？
'Password': APIパスワード,
'Symbol': "7211",
'Exchange' 1,
'SecurityType': "1",
'Side': "2",
'CashMargin': "3",
'MarginTradeType': "3",
'DelivType': "0",
'AccountType': 4,
'Qty': 100.0,
'ClosePositions': [
                    {'HoldID':"Exxxx",'Qty':100.0}
                  ],
'FrontOrderType': "10",
'Price': 0,
'ExpireDay': "0"

**Comment by hishiharahaz** [comment]
@hieeeee 
もしかしたらですが、「DelivType': "0"」となっているので「1:自動振替」か「2:お預り金」を指定してみてください。

https://kabucom.github.io/kabusapi/reference/index.html#operation/sendorderPost

**Comment by hieeeee** [comment]
@hishiharahaz 
ご回答ありがとうございます。
DelivTypeを「2:お預り金」にしたところ、処理が成功しました。
リファレンスで信用新規が0と記載があったので、勘違いしていました。
こちら解決したのでクローズします。
