### ISSUE TITLE
【質問】

### ISSUE THREAD

**Issue by masaki64** [kabucom/kabusapi#76]
お世話になっております。
kabuステーションAPIを利用して、「1分or5分ごとの株価データ」を蓄積し、リアルタイムで「ボリンジャーバンド」や「移動平均線」の更新、および「5分足」の作成を行いたく思っております。

「時価PUSH配信」を利用することで上記が実現可能かわからず、質問させていただきました。
「時価PUSH配信」とは、どのタイミングで株価のデータがPushされるのでしょうか。
（「値が更新される際に配信」とありますが、どの値が更新されるタイミングでしょうか。）

また、「ボリンジャーバンド」や「移動平均線」、「5分足」のデータがAPIにより取得できない認識ですが、何か取得方法はありそうでしょうか。（「時価PUSH配信」では満たせない場合、他サイトのAPIを利用、もしくはスクレイピングにより、5分足データを取得するしかないと考えております。）

以上、ご多用中、恐れ入りますがお願い致します。

**Comment by tsuchinaga** [comment]
#72 より引用

> PUSH配信は、値が更新されたら配信されますので、  
> 登録された銘柄の価格に変更があったときにPUSHされます。

とのことですので、現値以外でも板に変化があっても配信されます。

現値が更新されたかは `CurrentPriceTime` の時刻を見ればいいと思います。


現値の集計だけであれば簡単ですが、  
集計期間内(1分や5分)に約定がなかった場合や、分割・併合があった場合を考慮するのは大変なことだと思います。  
よほどこだわりがなければ他サイトのAPIを利用したりスクレイピングするほうが楽ではないでしょうか

**Comment by yasuyuki-nakazawa** [comment]
分足、日足の取得はご利用のシステム負荷状況等を勘案して公開検討いたします

@tsuchinaga さま、ご回答ありがとうございました

**Comment by masaki64** [comment]
@tsuchinaga さま、@yasuyuki-nakazawaさま、ご回答ありがとうございました。
現状では、分足、日足の取得は難しい旨、承知いたしました。
助かります！

＞分足、日足の取得はご利用のシステム負荷状況等を勘案して公開検討いたします
お願い致します。
