### ISSUE TITLE
【要望】PUSHの間引き処理を撤廃してほしい

### ISSUE THREAD

**Issue by hysdsk** [kabucom/kabusapi#760]
# 概要
タイトルの通り、PUSHの間引き処理を撤廃してほしいです。

# 背景
背景としては、PUSH通知から取得した情報をユーザ側アプリで計算して価格ごとの出来高を算出したいと考えております。https://github.com/kabucom/kabusapi/issues/754 の回答でもらったKabuステのクライアント側の処理と同じものです。しかしながら、PUSH通知で取得する情報は間引き処理が行われているため、正確な出来高の計算ができないので、本要望にいたっております。

# 補足
恐らくサーバ側の処理やネットワーク帯域など負荷的な問題から間引き処理が行われていると推測しています。ですので、間引き処理を撤廃するのではなく間隔を緩和したり、フラグやユーザの課金などを用いて一部ユーザの通知サーバのみ増強して間引きを撤廃するなどでも問題はないと思います。少なくともKabuステと同等の計算ができるレベルまで緩和いただけると助かります。

# その他
放置されているイシューがあるためご確認ください。
- https://github.com/kabucom/kabusapi/issues/645

**Comment by yasuyuki-nakazawa** [comment]
ご意見ありがとうございます。
間引きは上位サーバーレベルで実施されております。
現状はカブステのクライアントのインターフェースを公開すると言うことに閉じているため、カブステAPIではなく、オープンAPIとしての対応が必要となるため、検討にもお時間かかることが想定されます。

間引きのない情報の配信に関しては課金等も含めて、ご意見として連携させていただきます

**Comment by hysdsk** [comment]
要望として伝わったかと思いますので、クローズいたします。
