### ISSUE TITLE
【質問】発注が有効になっていませんと表示されます

### ISSUE THREAD

**Issue by USS123** [kabucom/kabusapi#763]
今まで発注できたのですが、発注結果に「発注が有効になっていません」と表示されるのはなぜでしょうか？
エクセルもkabuステーションの設定も間違いないと思うのですが・・・。

**Comment by yasuyuki-nakazawa** [comment]
アドインの発注制御を後確認ください
停止になっているかと思われます。
アドインのメニューの左上部になります。
