### ISSUE TITLE
【不具合】取引余力（信用）のDepositkeepRateが誤った値となる

### ISSUE THREAD

**Issue by kabucomapi** [kabucom/kabusapi#77]
取引余力（信用）のDepositkeepRateは御社WEBの資産管理→建玉可能額・買付可能額→余力情報の維持率を取得するものと考えていますが、0.0を返してきます。
MarginAccountWallet等の値は正常値です。
確認いただきますようお願いします。

**Comment by yasuyuki-nakazawa** [comment]
記載のDepositkeepRateですが、リファレンスの記載どおり、保証金の維持率になっております。

誤った値とのことですが、本来いくらであるべきところが、０となっているという記載にして頂けると確認もスムーズにいきます。
未決済建玉がゼロ、建玉がなしということではないでしょうか？

-- ご参考 --
【維持率の計算式】	維持率 =（受入保証金合計 － 建玉評価損 － 諸経費等 ＋ 決済損益 ） × 100 / 建玉金額

**Comment by kabucomapi** [comment]
お世話になります。
42.7%が0%となります。
よろしくお願いします。

**Comment by yasuyuki-nakazawa** [comment]
kabuステーションの「信用新規_買発注」ダイアログを出力したときはどのように表示されていますでしょうか
プルダウンにて「保証金維持率」が選択されていることを確認して頂き、
銘柄名の下部分（規制あり、なしの左部分）にパーセント表示されている数値があるかと思います。
そちらの表示の値がいくつになっておりますでしょうか？
本来の維持率が、教示いただいている42.7%という数値でこちらに出力されているかをご確認いただけますか。

**Comment by kabucomapi** [comment]
本日売買がありましたので、値は変更されていますが、66.4%と表示されています。
なお、VBAで得られる値は依然として0のままです。他の項目は正常値です。

**Comment by yasuyuki-nakazawa** [comment]
当方で確認したところ、問題なく値の取得ができております。
APIログとかいかがでしょうか？

**Comment by yasuyuki-nakazawa** [comment]
銘柄指定でリクエストされているという認識であっていますでしょうか。API呼び出し時のパラメータ等も合わせて連携いただけると幸甚です

**Comment by kabucomapi** [comment]
銘柄指定はしておりません。銘柄を指定して余力を確認する意味がよくわからないので、/wallet/marginで余力を確認しています。
MarginAccountWalletの値は伏せさせていただきますが下記のログが取得できております。
({"MarginAccountWallet":*****.0,"DepositkeepRate":0.0,"ConsignmentDepositRate":null,"CashOfConsignmentDepositRate":null})

コードとしては次のとおりです。
よろしくお願いいたします。 
   Dim objHTTP As Object
    Set objHTTP = CreateObject("msxml2.xmlhttp")
    objHTTP.Open "GET", "http://localhost:" & PortNo & "/kabusapi/wallet/margin?dummy=" & DateTime.Now
    objHTTP.setRequestHeader "Content-Type", "application/json"
    objHTTP.setRequestHeader "X-API-KEY", ApiToken
    objHTTP.send

**Comment by spotthediff** [comment]
VBAはあまりわからないのですが、上記コードの/wallet/marginにdummyパラメーターがついていて`dummy=&DateTime.Now`となっていますが、これはどのように使うものなのでしょうか?

**Comment by yasuyuki-nakazawa** [comment]
> VBAはあまりわからないのですが、上記コードの/wallet/marginにdummyパラメーターがついていて`dummy=&DateTime.Now`となっていますが、これはどのように使うものなのでしょうか?

これはキャッシュ防止ですね
この記載にしないと以前のキャッシュが返される場合があります。利用するライブラリに依存しますが。。

**Comment by yasuyuki-nakazawa** [comment]
取引余力（余力）の銘柄指定の場合は保証金率が返ります。
銘柄指定でない場合は、当該項目には0.0が返る仕様となっております。

kabuステーション側の情報を連携するインターフェースである仕様上、当該項目を連携する手段があるかどうかというところは調査・検討しております。
現状はkabuステーション発注画面表示時に当該項目を取得する仕様上、記載させて頂いた動きとなっております。

**Comment by kabucomapi** [comment]
回答ありがとうございます。
維持率取得が、カブステーション側の画面表示に制限された仕様であることを確認しました。

この仕様であれば、通常取引されている銘柄であれば、銘柄指定による維持率取得において、同時刻に取得される維持率は銘柄によらず同じ値であるとの理解で間違いないでしょうか？ご回答いただきますようお願いします。

（銘柄による影響を受けない維持率を、銘柄指定でないと取得できないという仕様を、直感的に理解でするのは難しいように思います。)

**Comment by yasuyuki-nakazawa** [comment]
はい。維持率は銘柄の選択内容にかかわらず、同値となります。
銘柄コード指定しない場合の維持率の取得改善に関しては、別途検討いたします

**Comment by kabucomapi** [comment]
検討のほどよろしくお願いします。
クローズしていただいて結構です。
