### ISSUE TITLE
【質問】registerのレスポンス

### ISSUE THREAD

**Issue by gAuk** [kabucom/kabusapi#773]
検証用のでも本番用のでもレスポンスが
{
  "Code": 4001012,
  "Message": "リクエスト不正"
}
この様になります。
こうなるのは引け後だからでしょうか？

送ったヘッダーはこんなもので
{
  X-API-KEY: ********
  Content-Type: application/json; charset=utf-8
}
jsonは
{"Symbols": [{"Symbol": "9433", "Exchange": 1}]}
でした。

**Comment by yasuyuki-nakazawa** [comment]
APIとの接続時代は問題なく処理されているでしょうか

**Comment by gAuk** [comment]
ありがとうございます。
urlが1文字間違ってました。修正し問題なく動作しました。
何度も見直しましたが見落としてました。
お恥ずかしい限りです。

**Comment by yasuyuki-nakazawa** [comment]
かしこまりました。解決されたということでよかったです
