### ISSUE TITLE
【質問】最初のトークン発行ができません。

### ISSUE THREAD

**Issue by cranfhk** [kabucom/kabusapi#774]
サンプルコード　kabusapi_token.py のAPIで下記のXXXXXを自分のAPI
APIパスワードに置き換えて実行したら

HTTP Error 401: Unauthorized {'Code': 4001013, 'Message': 'トークン取得失敗'}

が出てきます。これ以上進めなくて困っています。教えてください。

ちなみにAPI登録は日曜しました。平日になればトークン取得は可能になりますか？

************* kabusapi_token.py *********************************

import urllib.request
import json
import pprint

obj = { 'APIPassword': 'XXXXX' }
json_data = json.dumps(obj).encode('utf8')

url = 'http://localhost:18080/kabusapi/token'
req = urllib.request.Request(url, json_data, method='POST')
req.add_header('Content-Type', 'application/json')

try:
    with urllib.request.urlopen(req) as res:
        print(res.status, res.reason)
        for header in res.getheaders():
            print(header)
        print()
        content = json.loads(res.read())
        pprint.pprint(content)
except urllib.error.HTTPError as e:
    print(e)
    content = json.loads(e.read())
    pprint.pprint(content)
except Exception as e:
    print(e)

**Comment by hysdsk** [comment]
@cranfhk 
私の環境では上記のプログラムでトークンが取得できたので、プログラム自体は正しいと思いました。
```
200 OK
('Content-Length', '59')
('Content-Type', 'application/json; charset=utf-8')
('Server', 'Microsoft-HTTPAPI/2.0')
('X-Content-Type-Options', 'nosniff')
('X-XSS-Protection', '1; mode=block')
('X-Frame-Options', 'DENY')
('Content-Security-Policy', "default-src 'none'")
('Access-Control-Allow-Origin', '*')
('Date', 'Mon, 08 Jan 2024 14:54:34 GMT')
('Connection', 'close')
{'ResultCode': 0, 'Token': 'xxxxx'}
```

また、 https://github.com/kabucom/kabusapi/issues/776 のエラーは、おそらくKabuステが起動していないのではないかと思います。
> <urlopen error [WinError 10061] 対象のコンピューターによって拒否されたため、接続できませんでした。>

githubのissueやPRで同じ内容の課題なのであれば、最初のissueにコメントする形で一つにまとめると情報が辿りやすいとも思いました。

**Comment by cranfhk** [comment]
hysdsk様　ありがとうございます。
本日帰宅して実行してもやはり同じエラーが出てきます。
時間帯は昼間しかダメだということでしょうか？

HTTP Error 401: Unauthorized
{'Code': 4001013, 'Message': 'トークン取得失敗'}

**Comment by cranfhk** [comment]
教えてください。
obj = { 'APIPassword': 'XXXXX' }のXXXXX

にはau株コム証券で利用登録したAPIユーザIDのパスワードを入れるということでよろしいでしょうか？

**Comment by cranfhk** [comment]
追加質問です。TOKEN取得のプログラムではIDなしでAPIパスワードだけで取得できるということでしょうか？
IDはどこに紐づけられているのでしょうか？

**Comment by cranfhk** [comment]
解決しました。APIパスワードにkabuステーションで登録したパスワードを入れたら照合されました。
