### ISSUE TITLE
【質問】APIパスワードについて

### ISSUE THREAD

**Issue by cranfhk** [kabucom/kabusapi#775]
kabuステーションのWindows右上の </>記号マークを右クリックするとAPIパスワード(本番用）とAPIパスワード（検証用)の２つ入力を求められます。一方、HPでAPI利用登録時にAPIパスワードを登録しました。３つのパスワードはどういう関係になっているのでしょうか？
Pythonプログラムで入力するパスワードもあります。

**Comment by yasuyuki-nakazawa** [comment]
①HPのAPI利用パスワードはkabu.com APIを利用する際のパスワードとなります。
　こちらはAPIを利用してソリューションを提供しているベンダー様のツールを利用する際に必要になるモノで、カブステAPIとは関係がございません。
②カブステAPIの検証用パスワードは作成したプログラムの稼働確認(疎通確認）を行う為に必要なものとなります。
　あくまでもスタブ的に疎通確認を行う目的で利用するものです
③本番用パスワードはカブステAPIの実データにアクセスしたり、発注したりする際に必要になるパスワードとなります

**Comment by cranfhk** [comment]
ありがとうございます。

**Comment by cranfhk** [comment]
解決しました。
