### ISSUE TITLE
【質問】kabuSログファイルの位置について

### ISSUE THREAD

**Issue by hmhjapan** [kabucom/kabusapi#779]
url = 'http://localhost:18080/kabusapi/sendorder'
req = urllib.request.Request(url, json_data, method='POST')
req.add_header('Content-Type', 'application/json')
req.add_header('X-API-KEY', '*******f')

発注の時、下記のエラーが出てきます。
HTTP Error 400: Bad Request
{'Code': 4001005, 'Message': 'パラメータ変換エラー - 詳細はkabuSログファイルを確認してください'}

「kabuSログファイルを確認してください」ですが、kabuSログファイルはどこですか。

よろしくお願いいたします。

**Comment by hishiharahaz** [comment]
@hmhjapan 
kabuSログファイルは、以下に記載されているので確認ください。
https://kabucom.github.io/kabusapi/ptal/faq.html
ログの格納先はどこですか

**Comment by hmhjapan** [comment]
ご回答ありがとうございました。
