### ISSUE TITLE
【質問】Limit Trading based on difference of shares

### ISSUE THREAD

**Issue by nobuodesu** [kabucom/kabusapi#78]
We would like to place limit order based on the difference between one and the other share.
For example, i ask you in your api to buy share A if the difference between share A and share B is above 100yen.
Can I do such limit order?

**Comment by spotthediff** [comment]
I suppose to it is possible to do with Push API:

1. It need register both stocks with /register
2. Handle data from websocket (check these values for each update, then send order request if these values fulfill your condition.)

**Comment by nobuodesu** [comment]
thank you for your advice!
