### ISSUE TITLE
【質問】リアルタイムでデータを機械学習させて分析するサンプルプログラムありませんか？

### ISSUE THREAD

**Issue by cranfhk** [kabucom/kabusapi#780]
Pythonプログラムを使い取引できるのは、株式はここのみと聞いてとりあえず口座を作り、トークン発行と各種取引のサンプルプログラムは動作することは確認できました。

オー・ライリーの図書でファイナンス、アルゴリズム取引の本を購入し参考にして、au株コム証券のAPIデータを取り込んで値動きを機械学習しながら特徴量を読み取り取引できるプログラムを作成しようと思いますが、手っ取り早くサンプルプログラムもしくは実稼働させている方のプログラムを紹介いただけたらと厚かましくも思い投稿させていただきます。

データの取り扱いについては慣れているのですが、時系列およびリアルタイム取得データのインターフェースなどサンプルあれば助かると思い質問させていただきました。よろしくお願いします。

**Comment by yasuyuki-nakazawa** [comment]
APIは株式に加えて先物にも対応しております。
時価情報のAPIとしてのインターフェースは公開しておりますが、学習に関しては用いるアルゴリズムや学習も千差万別のため、この部分のサンプルのご提示は当方としては致しかねる部分ですが、ユーザーの皆様同士での情報交換に委ねさせて頂きます
