### ISSUE TITLE
デイトレ信用取引の余力について【質問】

### ISSUE THREAD

**Issue by Izumoya** [kabucom/kabusapi#786]
一般信用（デイトレ）で発注をかけたときに、信用保証現金を越える取引ができません（エラー400が返ります）。
現物株式振替分も有効にするにはどうすれば良いのでしょうか。

**Comment by hishiharahaz** [comment]
ワンショット上限のチェックでエラーとなっているかもしれません。
「システム設定　＞　APIタブ　＞　ソフトリミット(ワンショット上限)」で信用っていくらまでとしていますか。
