### ISSUE TITLE
【質問】APIで発注した注文を全てキャンセルする

### ISSUE THREAD

**Issue by myuu1014** [kabucom/kabusapi#797]
10件ほど出した新規買い注文をキャンセルしたいと思います。
その際に下記を参考にしたいと思いますが、注文中の全てのOrderIDを取得する
方法について、教えて頂きたいです。

https://github.com/kabucom/kabusapi/blob/master/sample/Python/kabusapi_cancelorder.py

本来、発注時にOrderIDが発行されますが、その際に記録しなくとも、現在未約定で、まだ
注文が出ているもののIDを取得できないでしょうか。

**Comment by yasuyuki-nakazawa** [comment]
注文約定照会で現状有効な情報を取得し、未約定（State）かをハンドリングして処理するという方法はいかがでしょうか

**Comment by myuu1014** [comment]
約定照会で状態みて判断できるのですね！
ありがとうございます！出来そうです。

約定している注文しか情報取れないと勘違いしていました。

**Comment by satosato125** [comment]
解決済みのようですので、クローズとさせていただきます。
