### ISSUE TITLE
【質問】株ステーションの利用環境について

### ISSUE THREAD

**Issue by masaki64** [kabucom/kabusapi#80]
今回、OS : CentOS7.5サーバにて、Pythonでkabusapiを実行するようなシステムを構築したいと考えていました。

今回、Localhostのみ利用可能な認識ですので、API実行を行うプログラムがあるサーバ内に株ステーションをインストールしなければならない認識でおります。

CentOS7.5サーバにて、APIを利用するためには、どのように対応する必要があるか、ご存じの方いらっしゃいましたら、ご教示いただきたいです。

ざっくりとした質問になり、申し訳ございませんが、宜しくお願い致します。

**Comment by yasuyuki-nakazawa** [comment]
ご参考となるスレッドは下記となります。
推奨しかねる方法ではございますが。
https://github.com/kabucom/kabusapi/issues/34
