### ISSUE TITLE
【質問】検証用APIで信用返済したときの挙動

### ISSUE THREAD

**Issue by dokudo91** [kabucom/kabusapi#805]
検証用APIで信用返済コードを書いたところエラーとなりました。以下はログです。
```
09:14:32.5095,I,26100,0021 【SendOrder】({"Password":"****************","SecurityType":1,"CashMargin":3,"MarginTradeType":3,"ExpireDay":0,"FrontOrderType":16,"Side":"1","Qty":500,"ClosePositionOrder":0,"Symbol":"9433","AccountType":4,"DelivType":3,"Exchange":1,"Price":0})
09:14:32.5233,I,26100,0021 【SendOrder】({"Code":1009001,"Message":"建玉が選択されていません。"})
```
まずは正しくパラメータ指定されているか教えてください。

正しくパラメータ指定されている場合は検証用APIで信用返済した場合の挙動について教えてください。
過去のIssueを見る感じ、このエラーは残高の建玉状況と一致しないときに発生するエラーのようです。
(買いで信用取引しているのであれば、売りで信用返済する必要があるみたいな。)
検証用APIであっても実際に信用取引を行って建玉を持っている状況でないと成功しませんか？

**Comment by yasuyuki-nakazawa** [comment]
検証用も建玉チェック、パラメータチェックは行われております。
おっしゃるとおり、建玉が指定されていないとエラーとなってしまっております。

**Comment by dokudo91** [comment]
個人的な意見としては、検証用APIが疎通確認用なのであれば、信用取引を実際に行う以外に成功できるパスがあると動作確認がしやすいです。
#804 で検証用APIに関する要望を出していますので、あちらにまとめて、こちらは閉じます。
