### ISSUE TITLE
【質問】HoldIDの取得方法（特定の注文のHoldIDを取得する方法について）を教えてください。

### ISSUE THREAD

**Issue by aiart-navi** [kabucom/kabusapi#807]
先物注文において、OrderIDをそのままHoldIDとして返済注文を設定していたのですが機能しませんでした。
（実行環境　Node.jsにて、REST-APIを使用）

HoldIDの取得方法について教えていただけないでしょうか？
また、特定の注文のHoldIDを取得したいのですが、OrderIDから取得する方法はありますでしょうか？
※kabuステーションの公式ドキュメントを拝見しているのですが、HoldIDの取得方法について、説明項目が見つかりませんでした。
参考ドキュメント: https://kabucom.github.io/kabusapi/reference/index.html

お手数をおかけしますが、ご回答いただけますと幸いです。
<img width="422" alt="段落テキスト - 2024-03-29T164447 012" src="https://github.com/kabucom/kabusapi/assets/126530074/37f5144e-d2eb-46f1-b448-1aa443b85786">

**Comment by aiart-navi** [comment]
ご返信いただき、誠にありがとうございます。
はい、「建玉を指定して返済を行いたく、対象となる建玉のIDを知りたい」というご質問になります。

**Comment by yasuyuki-nakazawa** [comment]
残高APIで返されるExecutionIDを指定されれば良いです

**Comment by aiart-navi** [comment]
ありがとうございます！

**Comment by satosato125** [comment]
解決済みのようですので、クローズとさせていただきます。
