### ISSUE TITLE
【要望】ログ領域の領域圧迫防止　→【対応予定】

### ISSUE THREAD

**Issue by Ros522** [kabucom/kabusapi#81]
お世話になります。
kabuステーションによって出力されるログにより
注文照会や、残高照会を定期的に行っていると数十GBのディスク容量を簡単に使い果たします。

AppData\Roaming\KabuS\Log\APILogの容量を制限するような設定を加えていただくことや
ログ出力内容の変更のご検討いただけないでしょうか。

**Comment by yasuyuki-nakazawa** [comment]
出力フォルダを圧縮フォルダにする等、暫定対応をいただけると幸甚です。
出力粒度に関しては見直し検討いたします。

**Comment by sakatsusan** [comment]
このログはユーザ側が、意識して手作業もしくは自作アプリが自動で消すようにしないといけないのでしょうか？

**Comment by yasuyuki-nakazawa** [comment]
ログの記載粒度は設定で保持できるように検討進めております。

**Comment by yasuyuki-nakazawa** [comment]
ログ容量に関しては、現状の1/3～1/2の削減を実施する方向で検討しております。
ご不便をおかけしますが、今しばらくお待ちくださいませ

**Comment by yasuyuki-nakazawa** [comment]
当件ですが、一旦暫定として対応を入れさせて頂きました。
https://github.com/kabucom/kabusapi/issues/202
※設定画面より設定変更をお願いします

およそ40％ほどのログ領域の削減が図られております。
本格対応としては、別途検討進めさせていただきます
