### ISSUE TITLE
【要望】指値価格の変更をできるようにしてもらいたい

### ISSUE THREAD

**Issue by hibino-kazuki** [kabucom/kabusapi#812]
注文済み発注（新規、返済共）の、指値、逆指値の価格を変更できるようにしていただきたいです。
自前でのトレーリングストップ注文を実現するため、強く要望します。

※
過去の質問（#715)にあるとおり、現状、注文の指値価格を訂正するには、
注文取消しの上、再注文する必要があると理解しております。

**Comment by yasuyuki-nakazawa** [comment]
ご記載の通り、現状は取消、再注文を実施する仕様となっております。
要望としては共有致します

**Comment by hibino-kazuki** [comment]
回答ありがとうございます。
ご検討の程、よろしくお願いいたします。
