### ISSUE TITLE
【質問】先物銘柄の板情報の取得方法は？

### ISSUE THREAD

**Issue by hare17** [kabucom/kabusapi#816]
先物銘柄のsymbolを取得した後、板情報の取得を行ったのですが、以下のように銘柄が見つからないと返却されます。
通常の現物の株式コードと使用するAPIが違うのでしょうか。もしくは先物銘柄の板情報は取得できないのでしょうか。

■実行したAPI
http://localhost:18080/kabusapi/board/169060019@1
■返却値
{'Code': 4002001, 'Message': '銘柄が見つからない'}

**Comment by hysdsk** [comment]
@hare17 先物は市場コードが日中とか夜間になると思います。

**Comment by hare17** [comment]
> @hare17 先物は市場コードが日中とか夜間になると思います。

URL末尾を"@2"に変更することで取得できました。ありがとうございます。
