### ISSUE TITLE
【質問】エクセルでの発注制御、更新制御をONにする方法

### ISSUE THREAD

**Issue by taroro81** [kabucom/kabusapi#82]
カブステAPIの利用設定、エクセルアドインの導入設定を行いデータ取得を行いたいのですが、kabuSTATIONアドインでの発注制御、更新制御が緑の有効に切り替わらず、関数によるデータ取得をする際に『トークンが発行されていません』とエラーが出てしまいます。
カブステーション右上に表示があるkabuステーション</>は緑に点灯しているのですが、どうすればエクセルと連携をすることが出来るでしょうか？

**Comment by taroro81** [comment]
https://kabucom.github.io/kabusapi/ptal/howto.html
https://kabucom.github.io/kabusapi/ptal/add-in.html
上記サイト上で、ご案内していただいた工程はちゃんと行ったのですが、、

**Comment by yasuyuki-nakazawa** [comment]
上記のログイン処理は実施していますでしょうか？？

**Comment by taroro81** [comment]
ファイルの解凍が上手く行えていなかったのが原因でした。
 お手数をおかけしました、申し訳ありません。
