### ISSUE TITLE
【要望】空売り規制の情報の追加

### ISSUE THREAD

**Issue by kabucomapi** [kabucom/kabusapi#84]
空売り規制の価格規制適用期間中の銘柄が判別できるように、時価情報・板情報に本情報を追加していただくことを要望します。
価格規制適用期間中は、発注方法に留意する必要があるため是非とも追加いただきたい情報です。
よろしくお願いいたします。

**Comment by yasuyuki-nakazawa** [comment]
ご要望に関しては理解いたしました。強く検討いたします

**Comment by kabucomapi** [comment]
検討のほどよろしくお願いします。
クローズしていただいて結構です。
