### ISSUE TITLE
【質問】auカブコム証券のAPIエンドポイントURLを確認

### ISSUE THREAD

**Issue by massaa39** [kabucom/kabusapi#843]
APIをPythonの環境で使用したいのですがauカブコム証券のAPIエンドポイントURLが分からず困っています。
実際のAPIエンドポイントURLを教えていただけますと幸いです。

**Comment by hori-ryota** [comment]
REST APIは `http://localhost:18080/` かと思います。どこかにあるサーバにつなぐわけではなく、ローカルに起動したkabuステーションにlocalhostで接続する形式なはずです。

PUSH API はこちらを参照。
https://kabucom.github.io/kabusapi/ptal/push.html

REST APIのURLどこに書いてあったかな〜と久々にドキュメントを見ましたが、確かに見当たらないかも…？

**Comment by massaa39** [comment]
教えていただき無事に接続できました！ありがとうございます、大変感謝しています。2024/06/17 午前8:39、hori-ryota ***@***.***>のメール:﻿
REST APIは http://localhost:18080/ かと思います。どこかにあるサーバにつなぐわけではなく、ローカルに起動したkabuステーションにlocalhostで接続する形式なはずです。
PUSH API はこちらを参照。
https://kabucom.github.io/kabusapi/ptal/push.html
REST APIのURLどこに書いてあったかな〜と久々にドキュメントを見ましたが、確かに見当たらないかも…？

**Comment by yasuyuki-nakazawa** [comment]
@hori-ryota 
ご説明ありがとうございます。
確かに現状の説明ですと、一見してわからないですね。改善は検討致します
