### ISSUE TITLE
【質問】先物銘柄コード取得APIの戻り値がNullになります

### ISSUE THREAD

**Issue by KoichiHaradaEndor** [kabucom/kabusapi#844]
ご担当者様

http://localhost:18081/kabusapi/symbolname/future
にリクエストを行ったのですが
FutureCode: "NK225"
DerivMonth: 202409
の検索条件に対して
200 OK
{Symbol: null, SymbolName: null}
が返ってきます。

自作のコードで発生したので、御社のJavaScriptサンプル (symbolname_future.js) でも試しましたが、結果は同じでした。
検索結果にnullが返される条件などございますでしょうか。

**Comment by KoichiHaradaEndor** [comment]
ご担当者様

自己解決しました。
本番環境でないと値が返されないようで、本番環境にクエリしたら回答を得られました。
ありがとうございます。

**Comment by satosato125** [comment]
解決済みとのことですので、クローズとさせていただきます。
