### ISSUE TITLE
【質問】リファレンスで使用している変数名の定義を整理している一覧表などはありますか

### ISSUE THREAD

**Issue by ironycs** [kabucom/kabusapi#845]
お世話になります。初めて質問をします。全くの初心者なので失礼やGithubの利用方法誤り等ありましたら、ご指摘ください。
kabuステーションAPIのリファレンスで変数名はアルファベットで表現されていますが、取得した情報のそれぞれが日本語でどのような定義なのかについてどこかに一覧表等の掲載がありませんか。類推することはできなくもないのですが、厳密に正しい理解をして情報を活用したいため伺ってます。
具体的には、例えば、「[REST API リファレンス」で「銘柄情報」を取得するサンプルプログラムでは戻り値を格納する変数として、下記がありますが、銘柄コードや市場のように容易に分かるものもありますが、類推しないと分からないものも私には多数あります。正しい定義をドキュメントで確認したくご教示いただけると幸いです。どうぞよろしくお願い致します。

Symbol
SymbolName
DisplayName
Exchange
ExchangeName
TradingUnit
PriceRangeGroup
UpperLimit
LowerLimit
Underlyer
DerivMonth
TradeEnd
TradeStart
ClearingPrice

**Comment by yasuyuki-nakazawa** [comment]
RESTのAPIリファレンスのResponse項目をご覧ください。
200（正常）の部分に各項目の内容記載がございます

**Comment by ironycs** [comment]
ありがとうございます。
Responseの記載はクリックすると展開されるようになっているのですね。勉強になりました。
本件、クローズ扱いで大丈夫です。お騒がせ致しました。
