### ISSUE TITLE
【不具合】空売り規制でないのに、空売り規制対象銘柄エラーが出現

### ISSUE THREAD

**Issue by oyuisao** [kabucom/kabusapi#851]
■[必須] 不具合事象(概要)
　KCMarginSellがtrue,規制情報も特にない銘柄に対して空売り注文（デイトレ）したところ、規制銘柄エラーとなりました。
■[必須] 本来想定されるアクションと事象
　空売り注文がエラーなく発注される
■[必須] 不備発生時刻（常時の場合は、常時で記載ください)
　ログ参照ください。
■[任意] お使いの環境(OS、Excelのバージョン等)、サンプル(Macro、アドインのバージョン）
　Windowsで、node.jsを利用してツールを作成しています。
■[任意] 不備部分のログ
09:16:35.5153,I,1944,0009 【Symbol】(9560@1,)
09:16:36.0154,I,1944,0009 【Symbol】({"BisCategory":"9050      ","TotalMarketValue":15484665120.0,"TotalStocks":11907.0,"FiscalYearEndBasic":20240831,"KCMarginBuy":true,"KCMarginSell":true,"MarginBuy":true,"MarginSell":false,"DisplayName":"プログリット","Exchange":1,"ExchangeName":"東証グ","TradingUnit":100.0,"PriceRangeGroup":"10000","UpperLimit":1362.0,"LowerLimit":762.0,"Symbol":"9560","SymbolName":"プログリット"})
09:16:36.3817,I,1944,0009 【MarginPremium】(9560)
09:16:36.5480,I,1944,0009 【MarginPremium】({"Symbol":"9560","GeneralMargin":{"MarginPremiumType":null,"MarginPremium":null,"UpperMarginPremium":null,"LowerMarginPremium":null,"TickMarginPremium":null},"DayTrade":{"MarginPremiumType":2,"MarginPremium":0.91,"UpperMarginPremium":106.0,"LowerMarginPremium":0.90,"TickMarginPremium":0.01}})
09:16:36.5480,I,1944,0009 【Regulations】(9560@1)
09:16:36.7315,I,1944,0009 【Regulations】({"Symbol":"9560","RegulationsInfo":[]})
09:55:00.0276,I,1944,0009 【SendOrder】({"Password":"****************","Symbol":"9560","Exchange":1,"SecurityType":1,"Side":1,"CashMargin":2,"MarginTradeType":3,"DelivType":0,"AccountType":4,"Qty":100,"ClosePositionOrder":0,"FrontOrderType":10,"Price":0,"ExpireDay":0})
09:55:00.1685,I,1944,0009 【SendOrder】({"Code":100302,"Message":"売建規制対象銘柄の為、受付することができません。"})

kabuステーション上でも9560を表示してみましたが、特に空売り規制のマークも出ていませんでした。
試しに発注してみると、kabuステーション上でも同じエラーが出ました。
APIというよりkabuステーション側の不具合かもしれないですね。

**Comment by satosato125** [comment]
デイトレ信用では当日中の返済が困難になる可能性があると当社が判断する場合、取引時間中の新規建ての注文に一時制限を設ける場合があります。
https://kabu.com/company/info/escapeclause.html#anc07

この場合、注文入力時にご注文をお受けできず、お問い合わせのエラーが表示されます。

**Comment by oyuisao** [comment]
お忙しいところご対応いただきありがとうございます。
返信遅れまして申し訳ありませんでした、理解いたしましたのでクローズします。
