### ISSUE TITLE
【質問】指値注文が頻繁に失効になる

### ISSUE THREAD

**Issue by TakashiP** [kabucom/kabusapi#852]
お世話になっております。

日経225マイクロ先物が「ある価格になったら、指値注文を発注」という取引を行っているのですが、
10回中7-8回くらいは失効になります。
・新規、決済いずれにおいても発生します。
・買い・売りいずれにおいても発生します。

成行注文は問題なく完了できています。

失効になった注文のログ例は以下の通りでして、"ExpireDay":0としているので、当日中は有効だと理解しているのですが、
失効になるケースは、1秒以内には失効になっているようです。

11:03:55.2439,I,11032,0008 【SendOrderFuture】({"Password":"****************","Symbol":"169090023","Exchange":23,"TradeType":1,"TimeInForce":2,"Side":"1","Qty":1,"FrontOrderType":20,"Price":42240.0,"ExpireDay":0})
11:03:55.3022,I,11032,0008 【SendOrderFuture】({"Result":0,"OrderId":"20240711A01N12179003"})
11:03:55.3057,I,11032,0008 【Orders】(3,20240711A01N12179003,,,,,,)
11:03:55.3057,I,11032,0008 【Orders】([{"TimeInForce":2,"CashMargin":2,"ID":"20240711A01N12179003","State":2,"OrderState":2,"OrdType":1,"RecvTime":"2024-07-11T11:03:54.5001944+09:00","Symbol":"169090023","SymbolName":"日経225マイクロ先物 24/09","Exchange":23,"ExchangeName":"大阪日中","Price":42240.0,"OrderQty":1.0,"CumQty":0.0,"Side":"1","AccountType":12,"DelivType":0,"ExpireDay":20240711,"Details":[{"SeqNum":1,"ID":"20240711A01N12179003","RecType":1,"ExchangeID":null,"State":3,"TransactTime":"2024-07-11T11:03:54.5001944+09:00","OrdType":1,"Price":42240.0,"Qty":1.0,"ExecutionID":null,"ExecutionDay":null,"DelivDay":20240712,"Commission":0.0,"CommissionTax":0.0},{"SeqNum":3,"ID":"20240711B01N12179004","RecType":4,"ExchangeID":null,"State":2,"TransactTime":"2024-07-11T11:03:54.5001944+09:00","OrdType":1,"Price":42240.0,"Qty":1.0,"ExecutionID":null,"ExecutionDay":null,"DelivDay":20240712,"Commission":0.0,"CommissionTax":0.0}]}])
11:03:55.9961,I,11032,0008 【Orders】(3,20240711A01N12179003,,,,,,)
11:03:55.9961,I,11032,0008 【Orders】([{"TimeInForce":2,"CashMargin":2,"ID":"20240711A01N12179003","State":5,"OrderState":5,"OrdType":1,"RecvTime":"2024-07-11T11:03:54.5001944+09:00","Symbol":"169090023","SymbolName":"日経225マイクロ先物 24/09","Exchange":23,"ExchangeName":"大阪日中","Price":42240.0,"OrderQty":1.0,"CumQty":0.0,"Side":"1","AccountType":12,"DelivType":0,"ExpireDay":20240711,"Details":[{"SeqNum":1,"ID":"20240711A01N12179003","RecType":1,"ExchangeID":null,"State":3,"TransactTime":"2024-07-11T11:03:54.5001944+09:00","OrdType":1,"Price":42240.0,"Qty":1.0,"ExecutionID":null,"ExecutionDay":null,"DelivDay":20240712,"Commission":0.0,"CommissionTax":0.0},{"SeqNum":4,"ID":"20240711B01N12179004","RecType":4,"ExchangeID":"7882797445387987220","State":3,"TransactTime":"2024-07-11T11:03:54.450551+09:00","OrdType":1,"Price":42240.0,"Qty":1.0,"ExecutionID":null,"ExecutionDay":null,"DelivDay":20240712,"Commission":0.0,"CommissionTax":0.0},{"SeqNum":5,"ID":"20240711F01N12179005","RecType":7,"ExchangeID":null,"State":3,"TransactTime":"2024-07-11T11:03:54.450551+09:00","OrdType":0,"Price":null,"Qty":null,"ExecutionID":null,"ExecutionDay":null,"DelivDay":20240712,"Commission":0.0,"CommissionTax":0.0},{"SeqNum":6,"ID":"20240711G01N12179006","RecType":3,"ExchangeID":null,"State":3,"TransactTime":"2024-07-11T11:03:54.5157947+09:00","OrdType":0,"Price":null,"Qty":null,"ExecutionID":null,"ExecutionDay":null,"DelivDay":20240712,"Commission":0.0,"CommissionTax":0.0}]}])

お手数ですが、考えられる原因や対策について、ご教示のほど、どうぞよろしくお願いいたします。

**Comment by TakashiP** [comment]
【自己解決】
日経平均先物のFAK取引は、kabuステーションAPIによる取引においても、
IOC取引対象に該当するため発生していた事象ではないかと思われます。

下URLにおいて、IOC取引を前提とした2Way注文の対象商品として、
「対象商品：信用取引（指値IOC）、日経225先物/日経225ミニ（FAK）、TOPIX先物/ミニTOPIX先物（IC）」
が挙げられております。
https://kabu.com/kabustation/special5.html

FASに変更したところ、発生しなくなりました。

**Comment by satosato125** [comment]
@TakashiP 様
ご確認、ありがとうございます。

解決済みとのことですので、クローズとさせていただきます。
