### ISSUE TITLE
【質問】kabuステーションのAPIアイコンの点滅について

### ISSUE THREAD

**Issue by masaru-hollandsoft** [kabucom/kabusapi#858]
kabuステーションのAPIアイコン</>が、緑、黄、と点滅していました。
APIで接続は問題なくできていたのですが、どういった意味でしょうか？

**Comment by satosato125** [comment]
APIアイコンは以下の状態を表しております。

緑(点灯)：API待機中（リクエスト受信可能な状態）
黄(点滅)：API実行中（リクエストを受信したあとの処理中の状態）
赤(点灯)：エラー発生
グレー(消灯)：停止中

**Comment by masaru-hollandsoft** [comment]
ありがとうございます。
