### ISSUE TITLE
【質問】sendorderコマンド発効後レスポンスを受け取るまでの貴社側の処理について

### ISSUE THREAD

**Issue by sakatsusan** [kabucom/kabusapi#86]
お世話になっております。

２点質問がございます。

１）発注処理の内容について
sendorderコマンドにて、発注が成功した場合に、
レスポンスとなる OrderId を受け取りますが
経路として下記を想像しました。

自作API利用アプリ→kabuステーション→貴社システム→東証で板乗せ
自作API利用アプリ←kabuステーション←貴社システム←東証で板乗せ

発注からOrderId を受けとるまで、数十ミリ秒の間に
上記図の東証での板乗せまで行われていると考えてよろしいですか？

それとも、kabuステーションもしくは貴社システムで受け取っただけで
レスポンスとなる OrderId が帰ってきているのでしょうか？

２）並行発注について

自作API利用アプリはトークンを受け取った後に、発注の必要に応じて
sendorderコマンドを発行します。
この際、マルチスレッド下で複数のhttpセッションを張りほぼ同時の
注文をKabuステーションにかけた場合、上記、東証まではすべて並行で
処理されますか？
もしくは、どこかの段階で、逐次処理に順次化されるのでしょうか？

以上よろしくお願いいたします。

**Comment by yasuyuki-nakazawa** [comment]
(1) 発注処理の内容に関して
　記載のフローのとおりです。取引所IDに関しては、（取引所がオープンとなっているかによりますが）取引システムが注文を受注したタイミングで返します。
(2)平行発注に関して
　マルチスレッドで発注を行った場合は、基本的にはマルチに注文が処理される認識ですが、確認します。
ただし、いずれの場合であっても、kabuステーションAPIには流量制限を設けいている都合上、秒間の注文リクエスト、情報リクエストにはそれぞれ制限を設けられていることをご留意ください。

**Comment by sakatsusan** [comment]
ご回答ありがとうございます。

（２）に関しまして、ご確認をよろしくお願いします。

> 秒間の注文リクエスト、情報リクエストにはそれぞれ制限

秒間の注文リクエスト上限は幾つでしょうか（どこかに記載がありますでしょうか？）

以上、よろしくお願いいたします。

**Comment by cyber-minion** [comment]
（２）の並行発注についてですが、kabuステ内にて、順次処理で注文を発注する仕組みになっております。
また、秒間リクエストについては、発注系リクエスト=5件/秒、情報系リクエスト=10件/秒となります。リファレンスに記載されております。

**Comment by sakatsusan** [comment]
ご回答ありがとうございます。

当方、迅速発注のためkabuステ内にて順次処理に変換することなく、
並行処理のまま証券取引所まで発注したいと考えております。
なお、発注系リクエスト=5件/秒以内を予定してはおります。

要望として、ご検討をお願いいたします。
もし、要望としての別Issueを立てるべきであれば、そう致します。

**Comment by yasuyuki-nakazawa** [comment]
①ユーザ→②API→③kabuステーション→④取引システム

①②間を並行処理したとしても、④の取引システム自体は受注した注文を順次処理いたします。
これは注文により取引余力が変更されるため、最終的には注文は順次処理となり、当該フローの変更はできません。

③④の間に関しても上述の利用から順次処理を行っております。
以上のことから、並列での注文受注は実施できないむね、ご理解、ご了承くださいませ

**Comment by sakatsusan** [comment]
ご回答ありがとうございます。

取引所開所時間帯で、
②のAPIにリクエストをかけリスポンスを受けるまで100～150msecと計測しましたが
④番の取引所が、リクエストからリスポンスまで、それほど時間がかかると思えない次第です。
取引所は高速受注処理をうたっていたはずでしたから。

④番の取引所処理時間は何msec程度でしょうか？
例えば東証の取引所システムの処理時間でかまいません。

これが、100～150msecより短ければ、①→②→③まで並行処理で行ってもかなりの
スループットが出ると考えております。

**Comment by yasuyuki-nakazawa** [comment]
④の取引システムは状況に左右されますが、１０ｍｓ～５０ｍｓが参考値となるとおもいます。
③～④部分は順次処理となります。①～③の発注時には、余力のチェックを行う関係上、並列処理が実施できません。
１注文の完了までは注文の余力状況に変更が入る可能性があるため、同時処理を実施できないというのが理由となります。

**Comment by sakatsusan** [comment]
ご回答ありがとうございます。

通常のREST APIはサーバに直接アクセスするため、kabuステーションのような他のソフトを経由しませんので、設計当初少々当惑しました。

要望させていただきたいのですが、④番の貴社取引システムへ直接REST命令を出せることを検討いただけると助かります。

例えば以下のような方法を考えました。
・貴社注文サーバーにログインしTokenを得られるようにする。一方、KabuステーションからもTokenを得る。
   貴社注文サーバーに注文時には両者のTokenを送信する。これで、ある程度発注を制限する。
・秒間５件以内、注文系（新規、参照、修正、削除）コマンドのみに対応でかまいません（他は今の様に株ステから受信）

要望として検討いただけると幸いです。

**Comment by yasuyuki-nakazawa** [comment]
オープンAPIの要望はかなり頂いております。
こちらは、下記スレッドにも回答してございますが、将来的には完全なオープンAPIとして開放していきたいところです。
しかしながら足元の状況としては、下記スレッドに記載の理由により、現在の形をとらせていただいております。
https://github.com/kabucom/kabusapi/issues/92
