### ISSUE TITLE
【不具合】エクセルアドインのサンプルソースコード不具合

### ISSUE THREAD

**Issue by sakatsusan** [kabucom/kabusapi#87]
エクセルアドインのサンプルソースコードを読んでいて不具合と思われる点がありましたので報告します。

１）Order.csのSendOrderParamクラスが仕様通りでない

例えば、仕様にある市場コード（Exchange)がなかったり、仕様でPasswordのパラメータが
OrderPasswordとなっていたり等です。
利用されていないようでうが、そのようなものも正確にすべきと考えます。

また、ClosePositionOrder、 ClosePositionsは、クラス内にメンバーがありませんでした。
仕様書上は、「※信用取引の場合、必須。」とありますので新規発注の際には
何を指定するかわかりません。

２）時間処理の不具合

下記のファイルおよび行番号にて、現在時刻と前回取得した時間が１秒未満には
コマンドを発行せず、前回キャッシュを利用するような実装が見受けられます。

ExcelFunctionController.cs(121):                    if ((DateTime.Now - tpl.Item1).Seconds < 1)
ExcelFunctionController.cs(164):                    if ((DateTime.Now - tpl.Item1).Seconds < 1)
ExcelFunctionController.cs(210):                    if ((DateTime.Now - tpl.Item1).Seconds < 1)
ExcelFunctionController.cs(255):                    if ((DateTime.Now - tpl.Item1).Seconds < 1)
ExcelFunctionController.cs(300):                    if ((DateTime.Now - tpl.Item1).Seconds < 1)
ExcelFunctionController.cs(348):                    if ((DateTime.Now - tpl.Item1).Seconds < 1)
ExcelFunctionController.cs(396):                    if ((DateTime.Now - tpl.Item1).Seconds < 1)
ExcelFunctionController.cs(446):                    if ((DateTime.Now - tpl.Item1).Seconds < 1)
ExcelFunctionController.cs(492):                    if ((DateTime.Now - tpl.Item1).Seconds < 1)

(DateTime.Now - tpl.Item1).Seconds  でえられる秒数は、時間の秒部分を表します。
すなわち、経過時間が60.8秒後の場合0.8秒後が得られて、一分以上経過しているにも関わらず
キャッシュが利用されると思われます。

本来は

(DateTime.Now - tpl.Item1).TotalSeconds

であるべきと思われます。

以上です、こちら側の理解に誤りがあれば、その際は申し訳ございません。

**Comment by yasuyuki-nakazawa** [comment]
１）に関しては、不要クラスです。こちらは削除させて頂きます。
２）はご指摘のとおりです。Excelの再計算を防止する目的のコードでしたが、当件は補正させて頂きます。

**Comment by sakatsusan** [comment]
回答ありがとうございます。

ClosePositionOrder、 ClosePositionsは、
仕様書上は、「※信用取引の場合、必須。」とありますが、
新規発注の際には何を指定するかわかりません。

もし、返済時のみ必要なのであれば、明示いただけると幸いです。

**Comment by yasuyuki-nakazawa** [comment]
信用新規の差異は設定不要となります。
こちらの部分に関しては、リファレンスを更新させて頂き、明示いたします。

【現記載】信用の場合必須
【新記載】信用返済の場合必須

**Comment by yasuyuki-nakazawa** [comment]
こちら、対応済みです
ご指摘ありがとうございました
