### ISSUE TITLE
【質問】PUSHの銘柄登録は場が始まるどれぐらい前からできますか?

### ISSUE THREAD

**Issue by spotthediff** [kabucom/kabusapi#872]
PUSH配信の銘柄登録を場(日経平均先物のナイトセッション)が始まる5分ほど前に行ったところ、場が始まってもデータが送られて来ませんでした。

具体的には16:20頃にカブステーションを起動し、16:25に日経平均先物Microの2024年9月限の銘柄登録をしました。
しかし、場が始まる16:30を超えてもデータが送られて来ませんでした。

その後(16:30より後に)一度カブステーションを終了し、再度起動と登録を行ったところ、データが送られてきました。

以上より、場が始まったあとにPUSH配信登録をする必要があるということでしょうか
もし、このような制限がある場合は、場が始まって最初の値動きを取れないので改善していただきたいです

**Comment by satosato125** [comment]
APIでは特にそのような制限は設けておりません。
PUSH配信は場の始まる前であっても、気配の更新などがあった場合には配信されます。
銘柄登録と配信する時間帯に制限はございません。

16:30を超えても送られてこなかったとのことですが、市場などにお間違えはなかったか、ご確認をお願いいたします。
