### ISSUE TITLE
【質問】Eから始まる建玉IDとは

### ISSUE THREAD

**Issue by shin3150** [kabucom/kabusapi#879]
建玉の返済をマクロのサンプルシートを使って行いたいのですが、Eから始まる建玉IDをどこで確認すれば良いのかわかりません。教えてください。宜しくお願いします。

**Comment by satosato125** [comment]
Excelのサンプルで
kabuSTATION_API_function_sample.xlsx
に「残高照会」のシートがございます。

ご質問のEから始まる建玉IDは、「残高照会」の実行結果で「約定番号」の欄に出力される番号が該当いたします。

**Comment by shin3150** [comment]
satosato125様

大変助かります。
ありがとうございました。

**Comment by satosato125** [comment]
解決済みのようですので、クローズとさせていただきます。
