### ISSUE TITLE
【質問】返済注文時のMarginTradeType（ 必須 信用取引区分）

### ISSUE THREAD

**Issue by kabucomapi** [kabucom/kabusapi#88]
お世話になります。
返済注文時にClosePositionOrder 必須決済順序を指定した場合に、MarginTradeType 必須 信用取引区分の指定は無視されるのでしょうか。
例えば同銘柄で一般信用（長期）買と制度信用買を保有しており、当該銘柄返済においてClosePositionOrder 日付（古い順）、損益（高い順）と、MarginTradeType 　制度信用を選択して発注したとします。
一般信用（長期）買のほうが制度信用買より以前に建てていた場合は、一般信用（長期）買が返済対象となる仕様となっています。ClosePositionOrderを指定した場合は、MarginTradeTypeは無視される仕様でしょうか？
よろしくお願いいたします。

**Comment by yasuyuki-nakazawa** [comment]
結論的にはMargineTradeTypeは必須であり、無視されません。
一般信用（長期）と制度信用の両建玉を保有している場合はMarginTradeTypeの指定を明確に実施する必要があります。

**Comment by kabucomapi** [comment]
返信が遅くなりすみません。
ご回答ありがとうございます。現在、本番環境で再検証はしておりませんが、MarginTradeTypeで指定された区分の建玉を対象に、ClosePositionOrderが適用される仕様との理解でよろしいか？
繰返しの質問ですみません。

**Comment by yasuyuki-nakazawa** [comment]
ご認識のとおりです

**Comment by yasuyuki-nakazawa** [comment]
@kabucomapi 
こちら、問題なければ、クローズの程、よろしくお願いいたします。

**Comment by kabucomapi** [comment]
クローズをお願いします。
ありがとうございました。
