### ISSUE TITLE
【質問】プラン適用期間について

### ISSUE THREAD

**Issue by kroad** [kabucom/kabusapi#880]
[kabuステーションのサービス内容のページ](https://kabu.com/kabustation/services.html)の下方の【ご利用プランの適用期間について】に、

> ProfessionalプランとPremiumプランいずれも、適用開始日から翌月第1営業日までとなります。

とありますが、例えば1/31が適用開始日で、2/1が営業日だとしたら、プランの適用区間はその2日間のみということでしょうか？

毎月第1営業日にリセットされるなら、プランを適用し続けたければ毎月第1営業日は必ず取引しなければならない、ということでしょうか？

**Comment by satosato125** [comment]
> 例えば1/31が適用開始日で、2/1が営業日だとしたら、プランの適用区間はその2日間のみということでしょうか？
はい、最初の1ヶ月についてはその2日間のみです。
その次の月のご利用については、毎月第1営業日(2/1)に次月分(2/2～3/1)の利用判定を行います。
過去3ヶ月(11/1～1/31)で1回でもお取引があれば、プラン適用条件の取引回数の条件を満たすことができますので、必ずしも毎月第1営業日にお取引いただく必要はございません。
以降も同様に、1ヶ月毎にプラン適用の判定を行いますが、過去3ヶ月間のお取引から判定いたします。

また、もし過去3ヵ月間でのお取引がなく、プラン非適用となった場合でも、日次でも判定しております。
2/2以降でもお取引があれば、その翌営業日から翌月第1営業日まで、プランが適用されます。

**Comment by kroad** [comment]
理解いたしました。ありがとうございます！
