### ISSUE TITLE
時価情報の取得精度について

### ISSUE THREAD

**Issue by sigebo** [kabucom/kabusapi#885]
カブステのkabusapiにより、リアルタイムでミニ先物の時価の直近の高値/安値をできるだけ高精度に取得したいと考えています。
直近のとは、１日や一定時間の間ではなく、任意の起点時刻の後に発生する高値/安値のことです。
kabusapiの場合は、すべてのtickのデータは取得可能ではない（間引きされる）ことは承知しています。
こうした場合は、できるだけ高頻度で時価情報を取得するほかないと思っていますが、
サンプルコードが公開されているpyson、excel、c#で顕著な差が生じるでしょうか。
むしろ取得間隔はプログラムコードの速度よりも、カブステで許容されるアクセス頻度（流動量？）の制限が支配的でしょうか。
実際試して見れば１目瞭然でしょうが、一応お尋ねします。
kabusapiには直近のtickデータの取得機能は無いと思っています。

**Comment by satosato125** [comment]
https://github.com/kabucom/kabusapi/issues/886
こちらの質問と同じため、こちらはクローズとさせていただきます。
