### ISSUE TITLE
【不具合】意図しない２段階認証について

### ISSUE THREAD

**Issue by excelderpa** [kabucom/kabusapi#887]
■[必須] 不具合事象(概要)
　日々利用しているスマートフォンでカブコム証券アプリを起動するたび２段階認証となる。
　また、日々利用しているPCでのkabustationについても、突然２段階認証が生ずる。
■[必須] 本来想定されるアクションと事象
　二段階認証は、通常と異なる端末や、ブラウザなどでアクセスがあった場合、本人が所有しているであろう、スマートフォンにて認証を行うものであると考えますが、そのスマートフォンでほぼ常時二段階認証を行うのは意味のないことで、大変困っています。
また、メールアドレスに認証コードを送信するよりは、SMSによるのがよりセキュリティが高いのではないかと思います。
通常利用のスマホやPCであれば、証明書を定期的に更新させるなどして、二段階認証は省略していただきたい。
それが困難であれば、本人同意による設定としていただきたい。

■[必須] 不備発生時刻（常時の場合は、常時で記載ください)
　ロジック非公開のため、不明。スマートフォンでは常時、ＰＣでも突然発生し、運用に支障が出ています。

■[任意] お使いの環境(OS、Excelのバージョン等)、サンプル(Macro、アドインのバージョン）
　スマートフォン android 12上でのカブコムアプリ, PC Windows10 kabustation

■[任意] 不備部分のログ
　システムエラーではないので、ログはありません。

**Comment by satosato125** [comment]
大変申し訳ございませんが、こちらではkabuステーションAPIについてのサポートやご質問を承っております。

API以外のお問い合わせにつきましては下記ページをご参照いただき、お問い合わせいただけますと幸いです。
https://kabu.com/support/default.html

**Comment by excelderpa** [comment]
承知しました。
ご案内いただいたページから問い合わせてみます。
