### ISSUE TITLE
【不具合】注文発注 ClosePositions指定での一括返済注文ができません

### ISSUE THREAD

**Issue by kabucomapi** [kabucom/kabusapi#89]
■[必須] 不具合事象(概要)　下記参照
■[必須] 本来想定されるアクションと事象　指定された建玉が発注される
■[必須] 不備発生時刻（常時の場合は、常時で記載ください)　常時
■[任意] お使いの環境(OS、Excelのバージョン等)、サンプル(Macro、アドインのバージョン）Windows10　Excel 2016　32bit
■[任意] 不備部分のログ 下記参照

御社提供のエクセルファイルkabuSTATION_API_ORDER_sampleによって、建玉指定発注を行っているのですが、1つ目に設定した注文のみが発注されて以降の注文が発注されません。１つ注文が通っているためかエラーメッセージも返されません。
また、発注パラメータ作成用の下記VBAコードの動作も確認しておりますが、ClosePositionListもFOR　NEXTで作成されています。
どこか設定等の誤りがあるかもしれんが、対応策をご回答いただきますようお願いします。

参考としてJsonConverter.ConvertToJson(param)等を示します。（一部データにマスク処理しています。）
JsonConverter.ConvertToJson(param)の内容
{"Password":"****************","Symbol":"9434","Exchange":1,"SecurityType":1,"Side":"2","CashMargin":3,"MarginTradeType":1,"DelivType":2,"AccountType":4,"Qty":500,"ClosePositionOrder":null,"ClosePositions":[{"HoldID":"E20200915*****","Qty":500},{"HoldID":"E20200915*****","Qty":100},{"HoldID":"E20200915*****","Qty":100}],"Price":0,"ExpireDay":0,"FrontOrderType":10}

ログ出力
**:**:**.6845,I,42160,0014 【SendOrder】({"Password":"****************","Symbol":"9434","Exchange":1,"SecurityType":1,"Side":"2","CashMargin":3,"MarginTradeType":1,"DelivType":2,"AccountType":4,"Qty":500,"ClosePositionOrder":null,"ClosePositions":[{"HoldID":"E20200915*****","Qty":500},{"HoldID":"E20200915*****","Qty":100},{"HoldID":"E20200915*****","Qty":100}],"Price":0,"ExpireDay":0,"FrontOrderType":10})
**:**:**.7856,I,42160,0014 【SendOrder】({"Result":0,"OrderId":"20200921************"})

御社提供のkabuSTATION_API_ORDER_sampleにおける連続発注パラメータ作成部
  ' 返済建玉ID、返済建玉指定の範囲チェック(返済建玉指定の場合、配列を作成する)
  Dim ClosePositionCount As Long
  ClosePositionCount = 0
  
  If NextRowNo > 0 Then
    ClosePositionCount = NextRowNo - RowNo
  End If
  
  '配列の要素は0から始まるため、-1
  ReDim ClosePositionList(ClosePositionCount - 1) As Object
  
  If ClosePositionCount > 0 Then
    Dim row As Integer
    row = RowNo
    For i = 0 To (ClosePositionCount - 1)
      Dim dic As Object
      Set dic = CreateObject("Scripting.Dictionary")
      dic.Add "HoldID", ActiveSheet.Cells(row, 信用_返済建玉ID)
      dic.Add "Qty", ActiveSheet.Cells(row, 信用_返済建玉数量)
      Set ClosePositionList(i) = dic
      row = row + 1
    Next
  End If

エクセルファイルの設定
![設定](https://user-images.githubusercontent.com/70043772/93766270-21552480-fc51-11ea-8fd0-0caa1ed19bf7.jpg)

**Comment by yasuyuki-nakazawa** [comment]
確認しました。
下記を補正し、お試しいただけますか。
当件はリファレンスに追記させて頂きます。

![image](https://user-images.githubusercontent.com/69886329/94119543-05889300-fe8a-11ea-9fed-9573f68bf9cb.png)

![image](https://user-images.githubusercontent.com/69886329/94119584-1507dc00-fe8a-11ea-9484-6ebe123822e2.png)

**Comment by kabucomapi** [comment]
ご回答いただきありがとうございます。
御社提供のエクセルファイルkabuSTATION_API_ORDER_sampleの下記コードからは、エクセルにおいて連続で複数の行にわたって同じ番号にすれば、それらに注文についてはパラメータが作成されるように見受けられますが（For i = 0 To (ClosePositionCount - 1)のループ部）、API仕様では１つの注文しか受付けないとの理解でよろしいでしょうか？

'配列の要素は0から始まるため、-1
ReDim ClosePositionList(ClosePositionCount - 1) As Object

If ClosePositionCount > 0 Then
Dim row As Integer
row = RowNo
For i = 0 To (ClosePositionCount - 1)
Dim dic As Object
Set dic = CreateObject("Scripting.Dictionary")
dic.Add "HoldID", ActiveSheet.Cells(row, 信用_返済建玉ID)
dic.Add "Qty", ActiveSheet.Cells(row, 信用_返済建玉数量)
Set ClosePositionList(i) = dic
row = row + 1
Next
End If

**Comment by yasuyuki-nakazawa** [comment]
APIでは１注文中に指定建玉を配列格納する仕様となります。

**Comment by kabucomapi** [comment]
回答ありがとうございます。
上記回答から、1注文に対して複数の建玉を指定して返済できると理解しますが、その際の御社提供エクセルファイルkabuSTATION_API_ORDER_sampleにおける設定例を具体的にお示しいただけないでしょうか？
よろしくお願いいたします。

**Comment by yasuyuki-nakazawa** [comment]
設定例は上記に添付した画像となりますが、いかがでしょうか。
不足点が在る場合はどのような情報が追加で必要でしょうか。

**Comment by kabucomapi** [comment]
回答ありがとうございます。実証するには複数注文を出して、約定させる必要があるので未実施です。実証するにあたり質問があります。
1.同じ銘柄で異なる返済建玉IDを生成するために、同日に時間を分けて発注すれば複数IDを取得できますか？
2.上記画像では注文数量が、500となっていますが、下の行のIDから建日が古い場合は、1番下100、下から2番目100、1番上300が発注されホールド状態となるのでしょうか？
よろしくお願いします。

**Comment by yasuyuki-nakazawa** [comment]
１．建玉IDは約定単位に付与されます。そのため、分割して発注することで建玉IDは約定ごとに付与されます。
　　また、大量ロットで発注した場合、その注文が部分約定した際にも、その約定ごとに建玉IDが付与されます。
　　そのため、１注文に対して、１建玉IDとなるとは限らず、約定次第では、１注文に複数の建玉IDが付与される形が発生します。

２．上記は建玉を指定しているため、建て日は特段意識されません。上記の例ですと、複数建玉を指定した返済注文となりますので、指定された建玉全てがホールド状態となります。

**Comment by kabucomapi** [comment]
迅速な回答ありがとうございます。
上記の場合500発注していますが、指定したIDに700の建玉が紐づいています。どの建玉が選択されて買返済されるのでしょうか？
何度もお手数をおかけしますがよろしくお願いします。

**Comment by yasuyuki-nakazawa** [comment]
当件ですが、「建玉指定」と「返済順序指定」が混在されているように見えます。
建玉指定した場合は、返済順序を指定できません。
ここでは、一旦言葉の定義を下記と定めてご説明いたします。
・建玉指定　　　・・・ポジションを指定して返済する
・返済順序指定　・・・「日付が古い、損益が高い」等を指定して返済する

▼建玉指定
発注シートにあるJ列の「注文数量」には、１注文で返済したい合計の注文数量を入力します。
M列の「注文数量」には、子明細の建玉に対して、返済したい注文数量を入力します。

記載された内容から、以下で発注したいと読み取れましたので、こちらを元に記載します。
合計で①700株を発注したい。

子明細としては、以下としたい。
・建玉A：②500株
・建玉B：③100株
・建玉C：④100株
発注シートへは、J列に①の株数、M列に②～④の株数を入力することで、期待の動きになると思われますのでお試しください

**Comment by kabucomapi** [comment]
お世話になります。
回答ありがとうございました。
問題なく発注できるようになりました。
