### ISSUE TITLE
【質問】情報を取得しようとしても「0」しか返ってこない

### ISSUE THREAD

**Issue by gaya-biz** [kabucom/kabusapi#895]
Excelで「SYMBOLNAME.FUTURE」や「BOARD」のような関数を使用しても、「0」の値しか返ってきません。
エラーコードもないため、対応のしようがなく、困っています。
環境はExcel、アドインを使用しています。
APIには接続済みで、検証環境で利用しています。
ご回答よろしくお願いいたします。

**Comment by satosato125** [comment]
解決済みとのことですので、クローズさせていただきます。
