### ISSUE TITLE
【質問】アメリカのNYダウ指数の取得について

### ISSUE THREAD

**Issue by hmhjapan** [kabucom/kabusapi#899]
kabuステーションAPIでアメリカのNYダウ指数の値を取得できますか。
取得できれば、銘柄コード(Symbol)は何ですか。
よろしくお願いいたします。

**Comment by satosato125** [comment]
申し訳ございません、kabuステーションAPIは米株未対応のため、NYダウ指数の取得はできません。

**Comment by hmhjapan** [comment]
ご回答ありがとうございました。
米株が対応できたら、嬉しいです。

**Comment by hmhjapan** [comment]
thank you
