### ISSUE TITLE
【要望】タイムスタンプのミリ秒対応

### ISSUE THREAD

**Issue by Ros522** [kabucom/kabusapi#9]
返却されるデータにおいて、現行は秒までのデータと認識しています。
WebSocketのPUSH配信の場合ですと、１秒の間に複数回通知を受けることがあり
受信データの前後関係を適切に管理するため、タイムスタンプについてミリ秒への対応を要望いたします。

**Comment by yasuyuki-nakazawa** [comment]
ご要望として承りました。
配信元情報を確認の上、対応可能なものに関してはミリ秒配信を検討いたします。
具体的に、ご要望とされている時間項目をご教示いただけますでしょうか。

**Comment by Ros522** [comment]
ご検討ありがとうございます。
時価情報・板情報APIにて対応できるもの全て、と要望させていただきます。
この中では特にCurrentPriceTimeが、前後情報を正確に把握するためにミリ秒まで欲しい情報となります。

CurrentPriceTime
OpeningPriceTime
HighPriceTime
LowPriceTime
TradingVolumeTime
BidTime
AskTime

**Comment by hori-ryota** [comment]
こちら、ミリ秒ではなく前後関係を管理する何らかの情報を付与することは難しいでしょうか？
シーケンス番号のようなものをイメージしております。

**Comment by yasuyuki-nakazawa** [comment]
シーケンスですか。
PUSH系ですが、kabuｽﾃｰｼｮﾝが受信した情報をパススルー形をとっております。
kabuｽﾃｰｼｮﾝ内で通番管理をすることができれば、前後関係を把握する通番的なものの代替にはなるかと思います。
こちらは現状を調査してみます。
ちなみにですが、スクリプトサイドで受信順にシーケンス管理する等の方法だとどのような支障がありますでしょうか？

**Comment by hori-ryota** [comment]
websocketで受け取ったデータが順序保証であれば現時点の私のユースケースでは支障はないです。
