### ISSUE TITLE
【質問】'TimeInForce': 0 とは何でしょうか？

### ISSUE THREAD

**Issue by quwup** [kabucom/kabusapi#90]
Python の下記サンプルスクリプトにおいて、「'TimeInForce': 0」との記載がありますが、これは何でしょうか？
https://github.com/kabucom/kabusapi/blob/master/sample/Python/kabusapi_sendorder.py

下記の解説にも掲載されていない項目かと思いますが、何を意味するものか、また、必要なものなのか、ご教授願います。
https://kabucom.github.io/kabusapi/reference/index.html#tag/order%2Fpaths%2F~1sendorder%2Fpost

closed の issue もざっと見ましたが、同じ質問は見当たらなかったので質問させていただきました。
が、既出だったらすみません。

**Comment by cyber-minion** [comment]
TimeInForceとは、デリバ発注時に設定する有効期間条件のことです。
1の場合、FAS
2の場合、FAK
3の場合、FOK
を意味します。

TimeInForceは派生商品用の項目で、株式では不要です。
派生商品の追加のタイミングで、リファレンスの更新を実施させて頂きます

**Comment by quwup** [comment]
ご回答ありがとうございました。
理解しました。
リファレンスの更新をよろしくお願いいたします。
