### ISSUE TITLE
【質問】逆指値と引成、あるいは他の執行条件

### ISSUE THREAD

**Issue by h-tsun3** [kabucom/kabusapi#904]
以下を実現したいと考えています。

「ある銘柄について、信用取引、寄成～引成で取引したい」
「約定価格から求めたラインにストップロスを設定したい」

これらを実現するには、以下を行うことで正しいでしょうか？

1. POST /sendorder で新規注文、執行条件は寄成（前場）
2. GET  /order または GET /positions で、1により発生した新規注文の注文詳細番号（＝約定番号、＝返済建玉ID）と約定価格を取得
3. POST /sendorder  で2で得られた注文詳細番号を用いて返済注文、執行条件は逆指値
4. POST /sendorder  で2で得られた注文詳細番号を用いて返済注文、執行条件は引成（後場）

つまり、

「建玉時に約定価格の〇%のようなストップロスは指定できないため、別途、返済注文で逆指値を行う必要がある」
「一つの建玉に対して逆指値と引成の２つの返済注文が併存可能で、片方を取消す必要はない」
「逆指値は、引成（後場）に限らず、他の返済注文と併存可能で、片方を取消す必要はない」

この仕様理解で合っていますか？

**Comment by satosato125** [comment]
> 「建玉時に約定価格の〇%のようなストップロスは指定できないため、別途、返済注文で逆指値を行う必要がある」

ご認識の通りです。

> 「一つの建玉に対して逆指値と引成の２つの返済注文が併存可能で、片方を取消す必要はない」
「逆指値は、引成（後場）に限らず、他の返済注文と併存可能で、片方を取消す必要はない」

１つの建玉に対しては１注文のみとなります。
逆指値または引成のどちらかしかご注文いただくことはできません。
