### ISSUE TITLE
【要望】kabuステーションを起動せずにkabuステーションAPIを利用したい

### ISSUE THREAD

**Issue by whitesnowtiger888** [kabucom/kabusapi#92]
現在、kabuステーションを起動しないと、kabuステーションAPIを利用できない仕様だと思います。
しかし、メモリを250MBくらい使用するため、レンタルVPS(バーチャルプライベートサーバ)上などの限られたメモリでは、リソースを圧迫してしまします。
仮想通貨などのREST APIは(というか普通のREST APIは)サーバに直接アクセスするため、kabuステーションのような他のソフトは必要ないはずです。
kabuステーションAPIから、直接auカブコム証券のサーバにアクセスする仕様にしていただけないでしょうか。

**Comment by yasuyuki-nakazawa** [comment]
提供しているAPIは本来はオープンAPI的なものであれば、利便性も格段に向上する認識ではあるものの、
第三者からのシステム負荷のコントロールや、レギュレーションに対しての壁等もあり、現在のkabuステーションを介してインターフェースを提供する形をとらせていただいております。
技術的には問題がないものの、上述した課題をひとつづつ解消していったうえで、オープンAPIの提供ができればとも思っております。
ご不便をおかけすることもあるかと思いますが、今のところは、現状の提供形態とさせてください
