### ISSUE TITLE
【質問】sample コード　kubsapi_websocket.py を実行すると--- ERROR ---  Handshake status 404 Not Found --- DISCONNECTED --- と表示されます。

### ISSUE THREAD

**Issue by takezo1004** [kabucom/kabusapi#93]

**Comment by yasuyuki-nakazawa** [comment]
kabuステーションは起動しており、API利用にいたるまでの設定は正常に完了しておりますでしょうか？

**Comment by takezo1004** [comment]
設定は正常に完了しており、kabusapi_websocket.py PUSH配信開始以外は正常に動作しております。開発はpychrmで行っております。
--- ERROR --- 
Handshake status 404 Not Found
--- DISCONNECTED --- 
--- request header ---
GET /kabusapi/websocket HTTP/1.1
Upgrade: websocket
Host: localhost:18080
Origin: http://localhost:18080
Sec-WebSocket-Key: l1A3pIt8feUpmAL5biNVcA==
Sec-WebSocket-Version: 13
Connection: upgrade


-----------------------
--- response header ---
HTTP/1.1 404 Not Found
Content-Length: 50
Content-Type: application/json; charset=utf-8
Server: Microsoft-HTTPAPI/2.0
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-Frame-Options: DENY
Content-Security-Policy: default-src 'none'
Access-Control-Allow-Origin: *
Date: Fri, 25 Sep 2020 00:10:31 GMT
-----------------------
