### ISSUE TITLE
【質問】]エクセルマクロで自動更新されない

### ISSUE THREAD

**Issue by maruyama-fay** [kabucom/kabusapi#95]
サンプルにあったBOARD関数を利用しています。
銘柄コードを入力した際は、その時点の実行結果を取得できていますが、リアルタイムに更新されません。
何か前提条件が抜けているのでしょうか？
RSSの使用経験がありますが、関数の結果は自動更新されると思っていました。

**Comment by cyber-minion** [comment]
リアルタイム更新に関しましては、PUSH配信をご利用いただければと思います。
https://kabucom.github.io/kabusapi/ptal/push.html

**Comment by maruyama-fay** [comment]
取得できました。
ありがとうございます。
