### ISSUE TITLE
【不具合】/positionsの応答が遅い

### ISSUE THREAD

**Issue by ymptech** [kabucom/kabusapi#96]
お世話になっております。
REST API「残高照会」/positionsの応答時間が遅い問題について報告させていただきます。
/positionsの応答で空("[]")が応答される場合(保有ポジションが無い場合)に、特に非常に応答が遅くなります。

毎回ちょうど5秒後にレスポンスがありますので、内部的に何かタイムアウトしているような印象です。
レスポンス内容は正常です(HTTPステータス 200 OK)
また、応答内容がある場合でも数百msはかかりますので、kabuステーションとkabu.com側サーバ間で通信が発生しているのでしょうか？
因みに/ordersの応答時間は短く、内容の有無に関わらず数ms以内に応答が返ってきます。
/positionsも原理的にはkabuステーション内部で保持しているデータを返すだけで良い様に思えますので、/orders並みに
高速化することはできませんでしょうか？

■/positions応答時間 空応答の場合 (10回試行)
5003.07ms
5000.75ms
5001.39ms
5002.98ms
5000.70ms
5001.32ms
5000.63ms
5000.92ms
5001.10ms
5001.19ms

■/positions応答時間 応答内容あり(1項目)の場合 (10回試行)
209.84ms
592.73ms
107.77ms
504.81ms
683.40ms
362.05ms
512.98ms
486.32ms
323.39ms
626.76ms

■/orders応答時間 応答内容あり(1項目)の場合 (10回試行)
1.40ms
1.71ms
1.64ms
4.07ms
1.85ms
1.45ms
1.49ms
1.65ms
1.91ms
2.48ms

■使用環境 Windows10 Pro Corei7  自作プログラム(C#)  ※Excel Addinでも同様の遅延を確認

**Comment by yasuyuki-nakazawa** [comment]
再現のためヒアリングさせてください。
記載の5000msで空応答となる場合、ならない場合に状況差異等ありますでしょうか？
また、ポジションの明細数は100を超える形でしょうか(数値に根拠はございません。検証参考値として伺っております）

**Comment by yasuyuki-nakazawa** [comment]
追記です
kabuステーション上で残高照会の画面を立ち上げた上でお試しいただけますでしょうか。

**Comment by ymptech** [comment]
ご返答ありがとうございます。
上記のテストでは全てkabuステーション上に「残高照会」「注文約定照会」の両方の画面を表示した状態で計測したものです。
ポジション明細数については、全くない状態、および信用ポジションが1項目だけある状態で確認いたしました。
念のため補足ですが、上記で応答時間が5秒となるときの空応答については、あくまで応答そのものは正常なものです。
(ポジションが全くない状態のため、HTTP応答文字列(コンテンツ)は []となります。HTTPステータスは200 OKです。)

信用ポジションのみが存在する状態で/positions?product=1 (現物ポジション取得)をリクエストしても5秒応答時間となります。
また、返済済みポジションがある状態、すなわちkabuステーション上の「残高照会」には表示されていないものの、/positionsリクエストに対しては"LeavesQty":0.0となるエントリが返ってくる状態では、応答時間は数百msになります。
全くポジション履歴の無い状態でお試しいただければ再現いただけるかと存じます。

**Comment by ymptech** [comment]
応答時間が5秒となったときのKabuSログファイルを確認すると下記のようなログが出力されていました。

00:23:46.0742,W,14468,0007 CalcPriceの取得処理に5000msec以上経過しました。
00:23:53.2521,W,14468,0007 CalcPriceの取得処理に5000msec以上経過しました。
00:23:58.8952,W,14468,0007 CalcPriceの取得処理に5000msec以上経過しました。

**Comment by yasuyuki-nakazawa** [comment]
参考となる情報です。
残高照会が画面上あがっている状態とお伺いしています
現値の取得に時間を要しているような動きで、こちらでは再現されておりません
メッセージより事象原因を調査させていただきます

**Comment by ymptech** [comment]
本日メンテ明けにテストしてみましたが、やはり同じ挙動になりました。
ポジションが無いと5秒でタイムアウトしてから応答が返ってくるかたちになります。
Wiresharkでパケットをモニタリングしても、/positionsリクエスト受付後にkabuステーションからkabu.comサーバへの通信は発生していない様子です。
推測ですが、ポジションが無い場合でも現値リクエストに対するレスポンス待受処理だけが走っているのではないでしょうか？

KabuS_20200926.log
20:42:18.4002,W,28024,0012 CalcPriceの取得処理に5000msec以上経過しました。
20:42:24.2325,W,28024,0012 CalcPriceの取得処理に5000msec以上経過しました。
20:42:31.1524,W,28024,0012 CalcPriceの取得処理に5000msec以上経過しました。

APILog\PLAIN_20200926_20.log
20:42:13.3997,I,28024,0012 【Positions】(0)
20:42:18.4002,I,28024,0012 【Positions】([])
20:42:19.2320,I,28024,0012 【Positions】(0)
20:42:24.2325,I,28024,0012 【Positions】([])
20:42:26.1519,I,28024,0012 【Positions】(0)
20:42:31.1524,I,28024,0012 【Positions】([])

**Comment by yasuyuki-nakazawa** [comment]
ポジションがない状態で当該事象の再現をさせることができました。
調査並びに対応してまいります。

**Comment by yasuyuki-nakazawa** [comment]
当件、改善させていただきます。
ご指摘の部分はポジションがない場合にも保有銘柄の評価額を算出する処理に起因して時価情報を取得しようとしていたために不要な情報取得処理が行われていたことが原因となります。
あらためて、こちらにて連携させて頂きます。

**Comment by ymptech** [comment]
ご対応ありがとうございます。引き続き宜しくお願いいたします。

これに関連して要望なのですが、ポジションのある場合であっても評価額の再計算(それにともなう時価情報の再取得)を省略することはできませんでしょうか？(例えば、positionsのパラメータに例えばrecalc=0というようなオプションをつけることで、kabuステーション内に保持している少し前の時価に基づいた評価額をそのまま返すだけにするなど)

とにかく高速にポジション一覧(最新評価額はなくてもよい)を取得したいため、ご検討いただけましたら幸いです。

**Comment by kabucomapi** [comment]
横からすみません。
よく似た内容の要望のためこちらに記入させていただきます。
残高照会につきましては、銘柄指定の問い合わせに対し、現物、信用（信用区分も判別可能）、売買区分、残数量、拘束数量を返していただけると助かります。数量については注文別ではなく合計値で取得したいです。評価額については不要で、第一に高速化を要望したいです。

書き込みが、マナー違反でしたら削除しますのでお知らせください。

よろしくお願いします。

**Comment by yasuyuki-nakazawa** [comment]
ご意見を拝聴していると、ポジションの状態の状況を短く知りたいというニーズと理解しました。
残高照会のサマリと明細が現状まとめて取得する形となっていますが、これにたいして、各種フィルタで取得できるように拡張すると共に、高速に状況把握したいという点においては、評価額を除外した場合についても検討追加させて頂きます

**Comment by kabucomapi** [comment]
お世話になります。
ご回答いただいた件、ありがとうございます。
プログラミングの技術の低い私の質問に、しっかり回答いただき助かっております。また、要望に対し、真面目に実装に向けた検討をしていただけるので感謝しております。
au株ドットコム証券様のAPIの仕組み（システム、運用体制）は、他社にはなく、間違いなく御社の強みだと感じておりますので、さらなる仕組みのブラッシュアップをお願いいたします。

**Comment by hirocha** [comment]
私はスキャルピングを行っていますのでpositionsは15秒毎（遅くとも30秒毎）に実行したいのですが、皆さんと同様にpositionsの応答に5秒かかっておりまして困っています。

https://github.com/kabucom/kabusapi/issues/96#issuecomment-708994220
私もこちら↑と全く同じ要望です。

**Comment by yasuyuki-nakazawa** [comment]
次月目処で何らかの改善を実施できるように検討しております。
よろしくお願いいたします。

**Comment by ymptech** [comment]
本日、kabuステーションver 5.12.2でテストしたところ、タイムアウトは発生せず正常動作しました。
修正いただいたようでありがとうございます。
