### ISSUE TITLE
【要望】リアルタイム株価予測の取得

### ISSUE THREAD

**Issue by kabusukebe** [kabucom/kabusapi#97]
リアルタイム株価予測の銘柄をAPI経由で取得したいです。

**Comment by yasuyuki-nakazawa** [comment]
リアルタイム株価予測の要望は高い認識はございます。
先になりますが、情報関連の強化は順次実施してまいります。要望として既に検討実施しております。

**Comment by kabusukebe** [comment]
失礼いたしました。
ではこちらは閉じておきます。
