### ISSUE TITLE
【不具合】期限切れの発注の扱いについて　→　【仕様・未対応】

### ISSUE THREAD

**Issue by kabucomapi** [kabucom/kabusapi#98]
■[必須] 不具合事象(概要)　期限切れの発注の応答が正常応答となる
■[必須] 本来想定されるアクションと事象　Resultに０が返されず、OrderIdは付与されない
■[必須] 不備発生時刻（常時の場合は、常時で記載ください)　常時
■[任意] お使いの環境(OS、Excelのバージョン等)、サンプル(Macro、アドインのバージョン）Window10 　Excel2016
■[任意] 不備部分のログ

お世話になります。
具体的な症状で説明させていただくと、後場が始まってから、寄指し（後場）の注文を入れると、正常にオーダーが受け取られたときと同じレスポンスが返ってきます。
カブステーションでキャンセルされているようですが、自動売買では誤発注の原因となる可能性があるため仕様を変更するほうが好ましいと思います。
不具合ではないのかもしれませんが、不具合項目に記載させていただきました。

**Comment by yasuyuki-nakazawa** [comment]
何点か質問させてください
①kabuステーションでキャンセルされているということですが、これは注文自体は受注されていない。ということでよろしいですか？
②期限切れ発注というのは、当日より過去の注文を発注した場合ということでしょうか
③当該注文のResultとしてはResultは０でOrderIDが付与されていないということですか

**Comment by yasuyuki-nakazawa** [comment]
こちらでも想定される事象に関して確認いたしました。
結論的には仕様となります。
Resultで０（正常）以外が返されるのは注文として受け付けられない場合に限られます。
記載の例ですと、後場が始まってから、後場の寄り指し注文を発注した時点で、注文としては正常に受け付けられているため、Resultとしては０が
結果として、受注時にすぐにビンゴ（条件に到達）し、指値が確定し注文処理を続行した結果、時限エラーとして処理され、期限切れとして注文エラーとなるフローとなったものです。

以上のことから、Resultが０（正常）以外を返すのは正式な注文として受け付けられないものに限定されるため記載の挙動となっております。

なお、発注タイミングに強く依存するため、事前のチェックとして当事象を確認することは容易ではなく、当件に関しては、要望はご理解するものの、未対応とさせて頂きます。
お手数をおかけいたしますが、よろしくお願いいたします。

**Comment by kabucomapi** [comment]
回答ありがとうございます。
仕様として理解しました。

**Comment by yasuyuki-nakazawa** [comment]
Closeさせていただきます
